### ISSUE TITLE
Bug - Aggregation fails when building type is turned off.

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#1011]
# problem

Aggregation report fails to generate when building by type is turned off in post processors. building type was turned off because no details in OSM data.
Impact function runs, no error message, no aggregation report either.
# note

version 2.05
# scenario

OSM buildings; tsunami hazard (raster), desa aggregation.
# check

pls check v2.1 first to confirm
# solution

write aggregation report for general buildings.

**Comment by timlinux** [comment]
No longer relevant in InaSAFE v4.0
