### ISSUE TITLE
Python error reading subset data - Filtered Layer

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#1085]
# Problem

python error when attempting to set key words on a shapefile where display is limited by a subset query.
# Data

smithsonian volcanoes.shp
query: location = 'java'
(can't save a scenario when no impact function selected)
# Software versions and tools

InaSAFE 2.0.5 final - InaSAFE Keyword Editor
InaSAFE 2.1.0 final - InaSAFE Keyword Editor
InaSAFE 2.1.0 final - InaSAFE Keywords Creation Wizard (is fine - no error) but key words assigned are not recognised. ie Impact function will not run
# error message (from 2.0.5)

An error has occured while executing Python code:

``` python
Traceback (most recent call last):
  File "C:/Users/u44080/.qgis2/python/plugins\inasafe\safe_qgis\plugin.py", line 479, in show_keywords_editor
    keyword_io.read_keywords(self.iface.activeLayer())
  File "C:\Users\u44080\.qgis2\python\plugins\inasafe\safe_qgis\utilities\keyword_io.py", line 104, in read_keywords
    keywords = read_file_keywords(source, keyword)
  File "C:\Users\u44080\.qgis2\python\plugins\inasafe\safe_qgis\safe_interface.py", line 340, in read_file_keywords
    raise InvalidParameterError(message)
InvalidParameterError: Cannot get keywords from a non-existent file.C:\WorkSpace\Data\Volcanoes\Volcano_smithsonian.shp|layerid=0|subset="LOCATION" = 'Java' does not exist.
```

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.2.0-Valmiera Valmiera, c3a2817
# Proposed solution

Make it happy if this the keyword editor will be retained in v2.1
# cc

@timlinux @akbargumbira

**Comment by timlinux** [comment]
I'm pleased to say this works perfectly in InaSAFE v4.0. Check out the screencast below. 

![qgis](https://cloud.githubusercontent.com/assets/178003/22012426/8dafe6aa-dcc6-11e6-95fe-1acd18ac84a6.gif)

**Comment by timlinux** [comment]
I should have mentioned that in the above screencast, the admin boundary is filtered to "DESA"='WOLOMARANG' and the buildings layers is filtered to "TYPE"="SCHOOL". The analysis runs just on the subset features and nicely returns a result.
