### ISSUE TITLE
Wrong results for building inundation depth for at the edge of imact area.

### ISSUE THREAD

**Issue by cchristelis** [inasafe/inasafe#1086]
# Problem

While investigating the inundation interpolation issue, I noticed that buildings on the edge of the impact area have wrong results as seen here:
![flood_depth_osm_building_at_edge](https://cloud.githubusercontent.com/assets/2319504/3268519/3cfe5c34-f2de-11e3-9419-6491810723b4.png)

This probably has  to do with the no the negative indexing of when looking at outside pixels.
# Solution

Either correct the pixel selection, or remove such buildings from consideration.

cc @akbargumbira @timlinux

**Comment by timlinux** [comment]
![screen shot 2017-01-17 at 5 35 02 pm](https://cloud.githubusercontent.com/assets/178003/22017102/6c7fc526-dcdb-11e6-9455-0822810f0bfe.png)

This is now resolved in InaSAFE 4.0 since we use the 'highest hazard touched' algorithm.
