### ISSUE TITLE
Wrong in categorizing low, medium and high

### ISSUE THREAD

**Issue by dichapabe** [inasafe/inasafe#1091]
## Problem

In the Generic IF (categorised_hazard_population), the output is giving the wrong estimate in each category. (Look for the comments I included in the script)

```
    # Extract data as numeric arrays
    C = hazard_layer.get_data(nan=0.0)  # Category

    # Calculate impact as population exposed to each category
    P = exposure_layer.get_data(nan=0.0, scaling=True)
    H = numpy.where(C <= high_t, P, 0)
    M = numpy.where(C < medium_t, P, 0) #shows only data below medium
    L = numpy.where(C < low_t, P, 0) #shows only data below low

    # Count totals
    total = int(numpy.sum(P))
    high = int(numpy.sum(H)) - int(numpy.sum(M))
    medium = int(numpy.sum(M)) - int(numpy.sum(L))
    low = int(numpy.sum(L))
    total_impact = high + medium + low
```
## Output:

It didn't include the estimate for Medium and Low categories, it only calls data that is below medium and below low thresholds.

![github](https://cloud.githubusercontent.com/assets/4961067/3298071/d72e987a-f5fc-11e3-9606-240f8f1c9f3a.png)
## In @assefay's revision

It includes the estimate for medium and low.

```
    # Extract data as numeric arrays
    C = my_hazard.get_data(nan=0.0)  # Category

    # Calculate impact as population exposed to each category
    P = my_exposure.get_data(nan=0.0, scaling=True)
    H = numpy.where(C <= high_t, P, 0)
    M = numpy.where(C <= medium_t, P, 0) #showing data in medium and below
    L = numpy.where(C <= low_t, P, 0) #showing data in low and below
    Z = numpy.where(C == 0, P, 0) 
    O = numpy.where(((C > 0) & (C <= high_t)), P, 0)

    # Count totals
    total = int(numpy.sum(P))
    high = int(numpy.sum(H)) - int(numpy.sum(M))
    medium = int(numpy.sum(M)) - int(numpy.sum(L))
    low = int(numpy.sum(L)) – int(numpy.sum(Z)) 
    zero = int(numpy.sum(Z))
    total_impact = high + medium + low
```
## Revision Output:

![threshold1](https://cloud.githubusercontent.com/assets/4961067/3298064/b4f4c978-f5fc-11e3-965c-9785b98336d2.png)
## Problem with the revision

When I tried to change threshold from 1, 2, 3 to 3, 2, 1 it gives different output. What I found out is that this command: `H = numpy.where(C <= high_t, P, 0)` calls all the data equal or less than High threshold which is the same as the total Population. 

I printed P (Population) and H (High):

```
print int(numpy.sum(P))
print int(numpy.sum(H))
```

![same-total](https://cloud.githubusercontent.com/assets/4961067/3297833/262f11ec-f5f9-11e3-8dee-ef5254e067e5.png)
## Proposed Solution

How I understand the old script works is that it basically look for the total of exposure then subtract it with the low, medium or high threshold. I simplified the script by just calling all the data in thresholds and counting the totals and it gives better outputs. 

```
    # Extract data as numeric arrays
    C = my_hazard.get_data(nan=0.0)  # Category

    # Calculate impact as population exposed to each category
    P = my_exposure.get_data(nan=0.0, scaling=True)
    H = numpy.where(C == high_t, P, 0)
    M = numpy.where(C == medium_t, P, 0)
    L = numpy.where(C == low_t, P, 0)
    Z = numpy.where(C == 0, P, 0)
    O = numpy.where(((C > 0) & (C <= high_t)), P, 0)

    # Count totals
    total = int(numpy.sum(P))
    high = int(numpy.sum(H))
    medium = int(numpy.sum(M))
    low = int(numpy.sum(L))
    zero = int(numpy.sum(Z))
    total_impact = high + medium + low 
```
## Output

Whatever data to be input into threshold, it gives same total number to be impacted

![threshold2](https://cloud.githubusercontent.com/assets/4961067/3298067/bddbaa3e-f5fc-11e3-9928-f53c72bc52e3.png)

Would you review this? @assefay @timlinux @mbernasocchi @maning 

Visit this branch for more details:  https://github.com/essc/inasafe/tree/proposed_computations_categorised_hazard_population

Hope it helps. Your suggestions are welcome,
Dianne

**Comment by timlinux** [comment]
I'm closing this out. In InaSAFE 4.0 we use a different workflow completely for generic hazards. I would suggest to start a new discussion if there are issues there, but we cannot constructively address it by talking about the old logic.
