### ISSUE TITLE
Code Coverage Is Less Than 80% 

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#1097]
## Problem

Some packages have coverage less than 80% (based on jenkins, per 18 Jun 2014): 
1. **impact-stats-test = 79%**
2. **realtime-test = 72%**
3. report-test = 82%
4. safe-package = 81%
5. **test = 30%**
6. tools-test = 83%
7. **utilities-test = 68%**
8. **widgets-test = 74%**
## Proposed Solution

Add more unit tests
## Expected Result

Minimum code coverage should be at least 80%

**Comment by timlinux** [comment]
Closing this out - we need to review test coverage again given all the refactors for 4.0 but we can make a new ticket if still needed as this one is stale.
