### ISSUE TITLE
RFC: Generic raster hazard with categorical values

### ISSUE THREAD

**Issue by dichapabe** [inasafe/inasafe#1105]
# Problem

Many data from different government agencies provide hazard data in categorical values. For example, MGB and Project NOAH maps in the Philippines, Malawi Flood Hazard (masdap.mw), etc. We need to improve the existing generic categorical IF to be able to use these data.
# Duration
# Current State

Draft
# Proposers

@maning
@dichapabe
# Detail

An initial implementation was developed by ESSC (https://github.com/essc/inasafe/tree/flood_categorising) for categorical flood hazard data. We proposed to port this code as the new categorical IF for the generic categorical hazard.
# Proposed solution
- Current implementation made by ESSC for flood hazard (for raster hazard) will be ported to form the basis of a generic categorical hazard
- Custom parameters implementation will be used (see RFC for that)
- The approach would be to implement a generic base class for all generic impact functions and then hazard specific subclasses can be implemented where specific action lists and post processors are required.
- Assigns the values of flood raster to low, medium and high based on a user defined input.
- Allows non-ordered assignment of threshold, for example, 3=low, 2=medium, 1=high.
- Works for population density and (partly) buildings.
  More work is needed on the following:
- [x]  Error in flood_categorised_building.py when zoom in to exposure layer
  
  ```
  File "/home/maning/.qgis2/python/plugins/inasafe-dev/safe/impact_functions/inundation/flood_categorised_building.py", line 181, in run
  val = int(round(val))
  ValueError: cannot convert float NaN to integer
  ```
- [x] Adding the subcategory `unit:categorised` for the flood hazard in the Keyword creation wizard
- [x] Improve text in the report in map
- [x] Add Action checklist
- [x] Better legend style in the printed map
- [x] Accept Null values in the IF configuration options
- [ ] Create test suite for each IF
- [x] Add OSM values of buildings in output layer
# Record of votes
# Resolution
# Reference

AIFDR/inasafe#314
AIFDR/inasafe#356
AIFDR/inasafe#1105
AIFDR/inasafe#1091
AIFDR/inasafe#1111

Code are available in this branch for reference: https://github.com/essc/inasafe/tree/generic_categorised_hazard
# CC

@assefay @akbargumbira @maning

**Comment by timlinux** [comment]
In InaSAFE 4.0 we no longer use interpolation and so you should not see these shifting artifacts. Also we have a new system for threshold definition and so I think this RFC is not valid anymore. It is fairly trivial to add a new threshold and associate it with a hazard , so I think we can deal with this further there. Thanks!
