### ISSUE TITLE
UTF8 characters in a layer path make InaSAFE crash

### ISSUE THREAD

**Issue by vdeparday** [inasafe/inasafe#1159]
If the full path has a folder name with accents ( /données/expositions/ ). InaSAFE crashes when trying to read the data with the following error:

Traceback (most recent call last):
  File "/Users/viv/.qgis2/python/plugins/inasafe/safe_qgis/plugin.py", line 526, in show_keywords_editor
    keyword_io.read_keywords(self.iface.activeLayer())
  File "/Users/viv/.qgis2/python/plugins/inasafe/safe_qgis/utilities/keyword_io.py", line 96, in read_keywords
    source = str(layer.source())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 73: ordinal not in range(128)

Going in debug mode with pdb, this is what I have found at line 96: 

(Pdb) layer.source()
u'/Users/viv/Dropbox/Worldbank/LAC/Haiti/UR Haiti/USB Key/QGIS InaSAFE/donn\xe9es/al\xe9as/inondations/hti_hazardhydrology_frequentflood_westdepartment_nathat_polygon/hti_hazardhydrology_frequentflood_westdepartment_nathat_polygonPolygon.shp'

After removing all the accent from the path manually, it worked again.

**Comment by Gustry** [comment]
@vdeparday I've made a pull request. Could you check if this solve your problem ?

**Comment by akbargumbira** [comment]
This is fixed here https://github.com/AIFDR/inasafe/pull/1674

**Comment by akbargumbira** [comment]
I merged the PR, closing this

**Comment by mbernasocchi** [comment]
@ismailsunni can you check if this is still happening when a Layername (in layer properties) includes utf8 I get:

```Ein Fehler trat bei der Ausführung von Python-Code auf: 

ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. 
Traceback (most recent call last):
  File "/home/marco/.qgis2/python/plugins/inasafe-dev/safe/gui/widgets/dock.py", line 546, in update_layer_name
    self.keyword_io.update_keywords(layer, {'title': name})
  File "/home/marco/.qgis2/python/plugins/inasafe-dev/safe/utilities/keyword_io.py", line 184, in update_keywords
    self.write_keywords(layer, existing_keywords)
  File "/home/marco/.qgis2/python/plugins/inasafe-dev/safe/utilities/keyword_io.py", line 166, in write_keywords
    write_iso19115_metadata(source, keywords)
  File "/home/marco/.qgis2/python/plugins/inasafe-dev/safe/utilities/metadata.py", line 81, in write_iso19115_metadata
    metadata.write_to_db()
  File "/home/marco/.qgis2/python/plugins/inasafe-dev/safe/metadata/base_metadata.py", line 652, in write_to_db
    self.layer_uri, metadata_json, metadata_xml)
  File "/home/marco/.qgis2/python/plugins/inasafe-dev/safe/metadata/metadata_db_io.py", line 300, in write_metadata_for_uri
    (json, xml, hash_value))
ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
```

**Comment by ismailsunni** [comment]
@mbernasocchi 
I didn't get the same problem with you. But, when I tried to replicate your problem, I got another problem when I used unicode filename, then set the title with unicode, `self.tr` will coplain (when it try to show in dock or widget). But, `tr` is fine.

What did you do to get the error?

**Comment by Gustry** [comment]
I put accents in my path, in the layer name, in the source, in the license ... I ran an analysis with the layer, everything could work nicely. I couldn't replicate your problem.
<img width="386" alt="screen shot 2017-03-06 at 22 43 48" src="https://cloud.githubusercontent.com/assets/1609292/23631340/6b36edda-02be-11e7-9852-e152880f220e.png">

**Comment by Gustry** [comment]
I can't replicate anymore. I'm closing this one. Feel free to reopen a ticket if any problem with UTF8
