### ISSUE TITLE
Better documention on the output layer of the flood/tsunami on population impact function

### ISSUE THREAD

**Issue by vdeparday** [inasafe/inasafe#1160]
- how are the polygons cut out when the function is run without aggregation? I have a layer with one polygon for my hazard zone and then it ends up being cut out in pieces with a value of impacted people for each piece but I don't know why it was cut that way and not another way.
- when running with the aggregation it seems like the polygons of the output layer are cut based on the aggregation layer but the name of the areas on which the cuts were based are not put in the output layer.
- I am thinking think the most useful output when running with the aggregation is to have the aggregation layer with the number of people impacted by area (for instance per districts). It appears in the table on the right but it would be good to have the shapefile to be able to do further work (including re-running the minimum needs function) and even include minimum needs in the output columns too. I know it can be generated by enabling “Show intermediate layers” in the option but that is too complicated and shouldn’t be required for a regular user. The other option would be to add the name to the current output layer as mentioned in bullet point #2. Or maybe have both layers in the output.

**Comment by Charlotte-Morgan** [comment]
Hi @vdeparday
I'm trolling through all things tsunami. Is this ticket still current?

**Comment by Charlotte-Morgan** [comment]
hi @vdeparday - we have new tsunami IF in the pending 3.3 release. It would be great if you can review and add comments if this is still relevant

**Comment by timlinux** [comment]
I think this is another case for treating impacts and exposure as polygons - we can produce an output layer which is the hazard union with the exposure where each polygon has the minimum needs and vulnerability attributes stored as column attributes. I'm going to park this over on 3.6 for now pending our impact function base class refactor.

**Comment by Gustry** [comment]
I think we did what @timlinux said in V4.0.
