### ISSUE TITLE
Wording / Layout needs to be adjusted in the report for Flood/Structure impact function

### ISSUE THREAD

**Issue by vdeparday** [inasafe/inasafe#1162]
Looking at the new report for the flood on building impact function (see screenshot below).
There is a section at the top called "Breakdown by building type" but it does not seem to actually give a breakdown by building type but more by Type of Hazard (the value of the attribute in the Hazard layer). The full building detailed building report is further down the page entitled "Detailed building type report"

Also, I think one of the two top sections has become redundant: "Building Type" and "Breakdown by building type", we could have all three line in the same section? 

![image](https://cloud.githubusercontent.com/assets/1036189/3726874/f72edf20-1697-11e4-8499-21f63c3ed24c.png)

**Comment by Gustry** [comment]
I'm closing this issue as we nade a big refactoring in version 4.0. This shouldn't happen anymore.
