### ISSUE TITLE
RFC: Fully embrace QGIS as a foundation library

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#1195]
# Problem

Our technological dept is high - we have many, many lines of code and our application grows in complexity with each iteration. This RFC seeks to find ways to address this problem by identifying parts of the code that can be refactored (either removed or simplified). One of the most obvious ways will be to supplant the usage of home-grown GIS functions with those provided by QGIS. This change (along with the inferential dependence on Qt4 throughout) will have a number of advantages which we will describe in this document.

# Duration

not specified yet

# Current state

This proposal is in draft

# Proposers

@timlinux

# Detail

First let us take a look at the current code layout of the `safe` package as per InaSAFE 2.1:

![selection_002](https://cloud.githubusercontent.com/assets/178003/4041538/6c59af80-2cf7-11e4-9492-3ad61f43096c.png)

## Package layout

Firstly we should mention that the package `safe` is present in order to provide an artificial boundary between the QGIS / Qt4 dependent code of the `safe_qgis` package and the `safe` package which was traditionally independent of Qt4 and QGIS. However with the release of 2.x this watershed has become less distinct - we now have impact functions that are using QGIS libraries and lots of black magic code to exclude these impact functions should QGIS / Qt4 not be present on the host operating system.

The `safe_qgis` and `safe` packages basically co-exist as fairly loosely coupled pair of applications, with the social contract in place being **'safe_qgis shall use safe via the safe.api, whereas safe shall never use safe_qgis'**. This contract makes the code base somewhat impenetrable for new developers and adds a substantial amount of wrapper code and indirection as various models in on top level package try to make use of modules in the counterpart package.

## Duplication

In QGIS we used to jokingly call ourselves the 'drunk' GIS as over time we accumulated two of everything (like we were 'seeing double') because our backwards compatibility made it difficult to discard old code when new improvements were made. In InaSAFE this split persona between `safe` and `safe_qgis` has been the cause of us incurring similar technical debt. For example we have two translation systems (gettext for `safe` and Qt4 for `safe_qgis`). We also have layered systems for dealing with keywords and probably most pertinent: we have a large amount of code in `safe` that provides basic low level GIS functionality that is already present in QGIS.

## Plugin loading mechanism

The plugin (i.e. impact function) loading mechanism within InaSAFE is problematic:

* Plugins are actually classes that are instantiated early on in the initialisation of InaSAFE and those instances persist for the duration of the application.
* Because a single instance is used for the life of the application run, plugins are not able to maintain their own state.
* The use of docstrings to define metadata and constraints is undesirable - it does not allow for rich metadata to be used to describe impact functions.

## Discoverability

The current arrangement makes discoverability harder than it needs to be. For example post processors are modules in the `safe` package, while aggregation is functionality provided in the `safe_qgis` package - whereas these two elements would in other circumstances naturally fit within the same package.

## Modularity

We bundle in third party code into our plugin:

![selection_003](https://cloud.githubusercontent.com/assets/178003/4042338/b7fb0d02-2d02-11e4-9e5b-6c1dd0f0981a.png)

This is a useful approach to provisioning third party packages in the absence of python virtual environments within QGIS's python implementation, but also adds clutter to the code base.

More germane is the fact that we are implementing a monolithic application which incurs penalties in terms of approachability, testing overhead and complexity. For example some parts of the code base could quite adequately be implemented as third party PyPI packages and then incorporated into the plugin at build time. The new parameters subsystem is an example of this.

## Resuability

If we are thoughtful about our implementation we would notice that we have silo'd a lot of functionality that would be very useful to others in a broader context. For example our impact functions could be used very nicely within the QGIS processing framework as part of complex workflows. Similarly there are elements of the processing framework that could be put to good use in InaSAFE.

# Proposed solution

## Candidate packages and modules to deprecate:

**in safe.common**

* geodesy
* interpolation
* interpolation1d
* interpolation2d
* numerics
* polygon

**in safe.engine**

* deprecate this whole package
* reimplement buffer generator in utilities as a QGIS native function

**in impact_functions**

* Reimplement all impact functions to use QGIS native API
* deprecate plugin related code
* deprecate utilities

**messaging**

Hive off as a third party package hosted in pypi

**storage**

* Completely deprecate this package

# See also

#949 (Unify Hazards as polygonal data)

# Record of votes

+1 Tim Sutton
+1 Marco Bernasocchi

# Resolution

# CC

@Charlotte-Morgan 
@vdeparday 
@ingenieroariel 
@ismailsunni 
@akbargumbira 
@mbernasocchi

**Comment by akbargumbira** [comment]
Just to summarize the state of InaSAFE now with this RFC, right now most of the old style numpy code are removed. The dependency left to that are the impact functions and safe layers module. We have chucked the dependencies in between and can just pass QgsMapLayers to the IF.

**Comment by timlinux** [comment]
I'm closing this as I think it is not relevant anymore. There is ongoing work to use QGIS more and more but it is iterative and does not need this RFC to inform it.
