### ISSUE TITLE
InaSAFE Realtime deployed on BNPB server

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#1200]
Raise realtime deployment on BNPB server through AIFDR monthly meeting

**Comment by Charlotte-Morgan** [comment]
@akbar - please update this ticket

**Comment by akbargumbira** [comment]
AIFDR server was broken in December 2014, we set it up again in Kartoza server.

**Comment by timlinux** [comment]
Closing this as old, but it looks like we will re-surface the idea again soon.
