### ISSUE TITLE
We need to add a smoothing algorithm to realtime shake contours

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#1201]
We need to smooth MMI contours. @charlottemorgan could you start by giving us a bullet list of 'rules' about how the output should be smoothed? Can be in plain english perhaps with some before and after views of the same data. @akbargumbira can give you some of the generated datasets to play with if that helps.

**Comment by Charlotte-Morgan** [comment]
Hi @samnawi - i'm giving this ticket to you. Can you please look at the QGIS processing tools and see if there is anything available to generalise lines?

**Comment by timlinux** [comment]
@samnawi is this still a priority? If not can we close this?

**Comment by timlinux** [comment]
Closing as this issue has been moved to the dedicated realtime repo.
