### ISSUE TITLE
Cannot generate PDF report with OpenLayer as the background

### ISSUE THREAD

**Issue by emirhartato** [inasafe/inasafe#1206]
# Problem

I would like to have OpenStreetMap layer as the background for the PDF report, but when I click "Print", and "Open PDF", there is nothing happen. I have tried with different template and extent but still it does nothing.
# System

OS Windows 8.1 64-Bit
Core i7-4700HQ with 4GB RAM
InaSAFE 2.1.0 Final and QGIS 2.4 64-Bit
# Data

Here is the data that I have used: https://dl.dropboxusercontent.com/u/11990722/Flood_Population_MASDAP.rar

Thank you

**Comment by timlinux** [comment]
I am going to close this - we should use the QuickMapServices plugin for tiled map layers rather - or the baked in add OSM button that I added a few versions back.

![screen shot 2017-01-27 at 2 32 49 pm](https://cloud.githubusercontent.com/assets/178003/22371085/a3bebabe-e49d-11e6-957c-6b893ccc9fa9.png)

**Comment by Gustry** [comment]
Or use the builtin QGIS TMS provider
