### ISSUE TITLE
There is no breakdown for type of building in aggregation result

### ISSUE THREAD

**Issue by emirhartato** [inasafe/inasafe#1213]
# Problem
When we are running flood IF for affected buildings using aggregation, the result shows there some residential and place of worship buildings. But, when under aggregation table, all the result is '0'.

![screenshot_092014_044728_am](https://cloud.githubusercontent.com/assets/1563226/4342617/e7e41d4a-4046-11e4-93b9-8df9ae0075a9.jpg)
![screenshot_092014_044802_am](https://cloud.githubusercontent.com/assets/1563226/4342620/eae5db46-4046-11e4-8036-8cd8aaf88d02.jpg)

# System
QGIS 2.4 / InaSAFE 2.1.0 from QGIS official repo

# Data

Building: https://dl.dropboxusercontent.com/u/11990722/osm_15092014.rar
Hazard: https://dl.dropboxusercontent.com/u/11990722/q5_atkins_flood_hazard.rar
Aggregation layer (use column 'Area' as aggregation): http://www.worldpop.org.uk/data/summary/?contselect=Africa&countselect=Malawi&typeselect=Population

# Expected outcome
We should has breakdown for type of building under aggregation table

cc: @severinmenard

**Comment by ismailsunni** [comment]
Been fixed in 3.5
