### ISSUE TITLE
RFC: Population Data and Rasterization

### ISSUE THREAD

**Issue by iyan31** [inasafe/inasafe#1217]
# Problem

Currently, there is no access to official population data in Indonesia (BPS) that is ready to use in InaSAFE. Local disaster management agencies often asked about this alternatives, even offer to give the data in tabular format rather than AsiaPop. While it is possible to use AsiaPop data, there are higher demand to use population data from government. On the other hand, when using AsiaPop in Maumere the population from AsiaPop is 10 times higher than official population data.

BNPB as leading sector in disaster management, have the access the population data from BPS in vector and tabular data. To use it in InaSAFE, they rasterize the data in village level to 1ha (100 x 100 m) cell size, but they do not consider the settlement area.
# Duration

not specified yet
# Current state

This proposal is in draft
# Proposers

@iyan31
@vasanthi0808
@mahardika
@dewisulistio
@raniedwianugrah
@debiholic
@samnawi
# Detail

The use of AsiaPop in InaSAFE, while it is successful in some parts of Indonesia, there is also some problems in other parts of Indonesia. 
# Proposed Solution
1. BPS currently already have census block data. If we can access to these data, especially in raster format, it would add official recognition on population data.
2. Rasterize BPS population data (vector) with advice and assitance from BPS, BNPB and Demographer or academic institution.
3. Some cases in the local government needs to run the analysis using their own population data. this might need a new feature in InaSAFE to allow them to export a vector population data before running InaSAFE, or make a new plugin for QGIS to export the vector population data into raster format by combining population data in vector format, settlement area and other variable.

**Comment by timlinux** [comment]
Picking up on this a little - @Charlotte-Morgan do you have any thoughts on this - do we want to add a tool like is being discussed above, park this or close it?

**Comment by timlinux** [comment]
In InaSAFE 4 (and even in 3.x) we can directly use census data as polygon census areas. Normalising for settlement vs rural distributions is IMHO something that should come from census experts and not be core functionality of InaSAFE. I am going to close this out as we can already support vector population data in InaSAFE. Please re-open if you wish to continue the discussion. Thanks
