### ISSUE TITLE
RFC : Reporting standard

### ISSUE THREAD

**Issue by harrymahar** [inasafe/inasafe#1218]
# Problem
Standard layout and report in InaSAFE is not quite interesting and not ready to use enough for users especially for beginner users therefore the result not often used for implementation stage (e.g contingency planning).

# Duration
TBD

# Proposer
@mahardika
@ismailsunni 
@debiholic
@harrymahar
@wulankhairunisa
@raniedwianugrah
@dewisulistio
@vasanthi0808

# Detail
1. For volcano buffering, the result of InaSAFE classification doesn't match with the threshold (3, 5, 10 km). There are more than 3 classifications in the Layers panel. 
1. How to input satellite imagery  on the result map (without openlayers plugin)
1. Simplification of the final report (margin, map)
1. Different minimum needs in different areas. e.g. some people don't eat rice, don't need blanket (they use sarong)
1. Missing age classification
1. Missing building breakdown in aggregation report
1. Too many classify for population result

![peta](https://cloud.githubusercontent.com/assets/2534179/4373407/7a2b3156-432c-11e4-85ea-74c765a3e57e.PNG)
![tabel 2](https://cloud.githubusercontent.com/assets/2534179/4373586/c185a81e-432d-11e4-82b3-93e5e9ca519b.PNG)

# Proposed Solutions
1. Adding a text box for user to add new minimum needs
1. Need more variations for paper orientation and layout 
1. Creating other export format besides PDF, for example .png and .jpeg for the map, and .xls and .csv for the table 
1. Better symbology on the running result, better to use graduate color than random color  
1. Working with BNPB to create a default layout that suit their standard

# Related Issues:
1. Improve information for affected population statistic from InaSAFE PDF output (https://github.com/AIFDR/inasafe/issues/1214)
2. PDF report table does not come with the style
(https://github.com/AIFDR/inasafe/issues/1115)
3. Enable by default **print as raster** in the map composer template
(https://github.com/AIFDR/inasafe/issues/1112)

# RFC Provenance

This RFC was discussed at the InaSAFE workshop in Jakarta, Tuesday 23 September 2014. The following people were in Attendance:

- Harry Mahardhika
- Dewi Sulistioningrum
- Dino
- Wulansari Khairunisa 
- Vasanthi
- Mahardika F
- Ranie D A

# Resolution

# CC

**Comment by mahardika** [comment]
still need more end-users comments on what should the table looks like. Will try to get Dewo (GIS - BNPB) to put some comments on this soon

**Comment by timlinux** [comment]
I will review this and see what we still need to do...

**Comment by Charlotte-Morgan** [comment]
I think this ticket is superceded by #2920
