### ISSUE TITLE
RFC: Requesting for Ash Volcano Eruption Impact Function

### ISSUE THREAD

**Issue by adissadis** [inasafe/inasafe#1221]
# Problem

Ash volcano eruption in vector format are common hazard type that some people ask. Nowadays is only have ash volcano eruption in raster format (based on http://inasafe.org/en/training/socialisation/functionality_datasets.html)
# Duration

TBA
# Current state

Draft
# Proposers

@adissadis
@mahardika
@cchristelis 
# Detail

Ash volcano impact function in InaSAFE is only for raster format. On the other hand digitizing vector data is quick way for quick response. 
# Proposed Solution

Create some impact function for ash volcano vector hazard input. The exposure data for this impact function is population and structure. We suggest to put some disclaimer on the result that said "this analysis is an estimate based ash in the air"
# Exposure Needed

This impact function analysis will need structure and population exposure.
# RFC Provenace

This RFC was discussed at the InaSAFE workshop in Jakarta, Wednesday 24 September 2014. The following people were in Attendance:
- Christian Christelis
- Ranie Dwi Anugrah
- Maning 
- Elida Nurokhmah
- Dewi Sulistioningrum
- Mahardika Fadmastuti
- Harry Mahardhika
- Dino
- Intan
- Vasanthi
- Wulansari Khairunisa
- Adityo Dwijananto
# Record of Votes
- 1 Adityo Dwijananto
- 1 Mahardika Fadmastuti

**Comment by timlinux** [comment]
I'm closing this - we have ash since 3.5
