### ISSUE TITLE
density scaling not working for a native UTM dataset

### ISSUE THREAD

**Issue by uniomni** [inasafe/inasafe#123]
I don't have time to investigate further, but doing the flood population impact with a UTM population dataset, gave bad scaling numbers:

Actual res 0.000452
Native res 0.094782351353
Scaling 2.27416469315e-05

It appears that Raster.get_resolution somehow used the UTM geotransform which clearly explains why the numbers were wrong. Two pathways,
Make Raster.get_resolution work like the GUI functino getWGS84resolution or work out if the front-end should have reprojected this layer.

**Comment by timlinux** [comment]
I'm closing this - counts are dealt with using zonal stats in InaSAFE 4.0 (or aligned rasters in EQ on Pop specific scenario). We can open up a new ticket there if we encounter any issues.
