### ISSUE TITLE
Update: Tsunami impact on buildings

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#1237]
# problems
Firstly, the building inundation function (tsunami) allows users to specify an inundation threshold.
The results are reported as inundated (in water deeper than the threshold) and not inundated (in water not as deep as the threshold). The output summary implies that buildings not inundated are open for business, ie can be used as evacuation centers etc. This is misleading.

Secondly, the default threshold does not reflect the standard tsunami hazard classification used BG on Tsunami hazard maps. This same classification is preferred by BNPB in perka 2/2012.

Thirdly, the default symbology used to show tsunami hazard zones is not consistent with BG standard symbology.

# proposed solution - withdrawn
that the raster flood and tsunami IF automatically report buildings affected in 3 categories:
wet - inundated: water deeper than defined threshold
wet: water not as deep as the defined threshold
dry:  water depth is less than or equal to 0

# proposed solution - updated
that the raster tsunami IF (there is no need for a vector Tsunami IF ??) has default classes and terminology the same as those used on BG tsunami hazard maps.
> 3m High Tsunami Hazard Zone
1 - 3m Moderate Tsunami Hazard Zone
< 1m  Low Tsunami Hazard Zone

that the definitions provided by BG be used as the definitions for these terms in the metadata.py #1251

that the default symbology for tsunami hazard data be the same as the map symbology used by BG #1252

# cc
@akbargumbira @timlinux @mahardika @fredychandra

**Comment by timlinux** [comment]
Status update: this ticket is on hold pending outcomes from #1428

**Comment by Charlotte-Morgan** [comment]
see #1428

**Comment by ismailsunni** [comment]
Done in #2542
