### ISSUE TITLE
We need to upload standard data packages to geonode

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#1242]
We need to upload all the standard data packages to geonode (see issue #1241) - this must happen after #1241 is done. All uploaded data should be accompanied by proper metadata. @charlottemorgan to define minimum requirements for uploaded metadata.

**Comment by fredychandra** [comment]
I have finished downloading new OSM building and roads for InaSAFE 3.0 training materials - ticket #1695. The data size around 543 MB. I need some advice how to upload it in properly in this ways of working. 
@timlinux @Charlotte-Morgan

**Comment by Charlotte-Morgan** [comment]
thank @fredychandra 
first we need to compile all the data as one package & then we will work on loading after we have Geonode training.
@akbargumbira - your help is needed with bitsync please

**Comment by Charlotte-Morgan** [comment]
hi @fredychandra & @samnawi - i'm reassigned this to Iwan now.
Thanks Fredy for the data management you did before we Iwan joined the team :)

**Comment by timlinux** [comment]
I'm going to move this onto the backlog for now. Maybe you anyway want to wait until the QGIS GeoNode spin up is ready?

**Comment by timlinux** [comment]
@Charlotte-Morgan  Can I suggest we close this out and revisit it when we have our action plan in place for 2017 activities?

**Comment by Charlotte-Morgan** [comment]
Can we put this on the agenda for Wednesday meeting please

**Comment by timlinux** [comment]
Ok I will chat with you about it in our next meeting.

**Comment by Charlotte-Morgan** [comment]
Happy to close this and make it a task for DMI work plan
