### ISSUE TITLE
We need to build a zip download tool for geonode

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#1243]
Possibly ask the WB folks to help with this? The idea is that you can define a data collection and download all the related datasets as a single zip file (with shapefiles, tiffs and qml styles).

**Comment by lucernae** [comment]
Is this still relevant? I don't understand the context?

**Comment by timlinux** [comment]
Yes - the idea is to be able to create data packs that can be used for training courses. The trainers can update GeoNode layers at any time and then download the pack which is ready to run.

**Comment by ismailsunni** [comment]
Is similar with the QGIS as interface to interact with GeoNode? In very simple way of course.

**Comment by timlinux** [comment]
Ok more clarification:

* add a new model in GeoNode for 'collections' e.g. Jakarta Training Collection, Malawi training collection
* provide a UI for user to assign one or more layers to a collection
* provide a button that lets the user download all datasets in a collection in a zip file

We should make this as a discrete django app that can be provided as a contrib module to GeoNode.

**Comment by gubuntu** [comment]
partly addressed in https://github.com/kartoza/geonode/issues/156

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geonode#397
