### ISSUE TITLE
Update: Tsunami hazard zones - update metadata.py

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#1251]
BG has tsunami hazard zone descriptions in 2 languages on published maps.

Obtain definition text for tsunami hazard zones (english and Indonesian) from BG. & use these in metadata.py

#cc @dika

**Comment by Charlotte-Morgan** [comment]
The following hazard classes are used by Badan Geology on published tsunami hazard maps and quoted in BNPB PERKA 2/2012. 

Low hazard zone < 1m
Moderate hazard zone 1-3m
High hazard zone > 3m

The following descriptions for these classes are provided in Indonesian and English by Badan Geologi. These description are the same as those on published hazard maps. 

This information was provided by Afif  from Badan Geologi 14th October 2014. It contains the tsunami hazard class descriptions as used on BG tsunami hazard maps. Permission has been granted to use this information as class descriptions for tsunami hazard data in InaSAFE.
KAWASAN RAWAN BENCANA TSUNAMI TINGGI/ HIGH TSUNAMI HAZARD ZONE
Daerah ini berpotensi dilanda tsunami dengan ketinggian genangan > 3 m dengan skala intensitas tsunami VII atau lebih (Papadoupulos dan Imamura, 2001). Tsunami dengan tinggi 3 m dapat menyebabkan kapal kecil rusak, kapal besar terdorong ke darat, banyak bangunan kayu rusak. Pasir dan bongkah terendap di pantai. Jika tinggi tsunami lebih dari 8 m mengakibatkan kerusakan sangat parah bahkan tembok pelindung tsunami, pemecah ombak dan jalur hijau rusak.
The area is potentially hit by tsunami wave with inundation depth > 3 m or reach tsunami intensity scale of VII or even more (Papadoupulos and Imamura, 2001). Tsunami wave with 4 m inundation depth cause damaged on small vessel, few ships are drifted inland, severe damage on most of wooden house. Marine and boulder are deposited on shore. If tsunami height reaches 8 m, it cause severe damage, dyke, wave breaker, tsunami protection wall and green belt were washed away.

KAWASAN RAWAN BENCANA TSUNAMI MENENGAH/ MODERATE TSUNAMI HAZARD ZONE
Daerah ini berpotensi dilanda tsunami dengan ketinggian genangan 1 - 3 m dengan skala intensitas tsunami V-VI(Papadoupulos dan Imamura, 2001). Tsunami dengan ketinggian 3 m menyebabkan banyak orang ketakutan dan lari ke tempat yang lebih tinggi. Kapal-kapal kecil terdorong arus dan saling bertabrakan, kerusakan pada sebagian bangunan kayu, sebagian besar bangunan masih bertahan.
The area is potentially hit by tsunami wave which inundation depth 1 - 3 m or equal to V-VI tsunami intensity scale (Papadoupulos and Imamura, 2001). Tsunami wave with 3 m inundation depth cause most people frightened and flee to higher elevation. Small vessels drifted and collided. Damage occurs on some wooden house, while most of them are safe.  

KAWASAN RAWAN BENCANA TSUNAMI RENDAH/ LOW TSUNAMI HAZARD ZONE
Daerah ini berpotensi dilanda tsunami dengan ketinggian genangan kurang dari 1 m dengan skala intensitas tsunami V atau kurang (Papadoupulos dan Imamura, 2001). Terasa oleh semua orang di kapal besar dan teramati di pantai. Sebagian kecil orang ketakutan dan lari ke tempat yang lebih tinggi. Kapal-kapal kecil bergerak cepat ke darat, beberapa diantaranya bertabrakan dengan yang lainnya dan terbalik. Pasir terendapkan pada tempat tertentu. Terjadi banjir pada tanah kosong dekat pantai.
The area is potentially hit by tsunami wave which inundation depth less than 1 m or similar to tsunami intensity scale of V or less in (Papadoupulos and Imamura, 2001). Tsunami wave of 1 m height causes few people frightened and flee to higher elevation. Felt by most people on large ship, observed from shore. Small vessels are drifted and collided and, some turn over. Sand is deposited on particular place. Flooding on area close to the shore.


the reference to Papadoupulos and Imamura, 2001 is http://geology.about.com/od/tsunamis/a/Tsunami-Intensity-Scale-2001.htm

**Comment by Charlotte-Morgan** [comment]
action - @me to update metadata.py and @ismailsunni to grab the details for translation

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni - can you please point me to the file that these definitions should go in?

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan : please go to https://github.com/inasafe/inasafe/blob/develop/safe/definitions.py#L677

**Comment by Charlotte-Morgan** [comment]
i think it fits in here:
raster_hazard_classification = {
    'key': 'raster_hazard_classification',
    'name': tr('Classes'),
    'description': tr(
        'Hazard classes are a way to classify the cell values '
        'in a raster layer.'),
    'types': [
        flood_raster_hazard_classes,
        generic_raster_hazard_classes,
        tsunami_raster_hazard_classes

but i would need to add detail to the tsunami raster hazard classes ?

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
If I understand correctly, the description in your comment fits in the line that I pointed before. We just need to update the classes (Currently only two classes, wet and dry). So, I think it will some thing like:

```python
tsunami_raster_hazard_classes = {
    'key': 'tsunami_raster_hazard_classes',
    'name': tr('Tsunami classes'),
    'description': tr(
        'The following descriptions for these classes are provided in Indonesian and English by Badan Geologi.'),
    'classes': [
        {
            'key': 'high_tsunami_hazard_zone',
            'name': tr('High Tsunami Hazard Zone'),
            'description': tr('The area is potentially hit by tsunami wave with inundation depth > 3 m or reach tsunami intensity scale of VII or even more (Papadoupulos and Imamura, 2001). Tsunami wave with 4 m inundation depth cause damaged on small vessel, few ships are drifted inland, severe damage on most of wooden house. Marine and boulder are deposited on shore. If tsunami height reaches 8 m, it cause severe damage, dyke, wave breaker, tsunami protection wall and green belt were washed away.'),
            'numeric_default_min': 3,
            'numeric_default_max': 9999999999,
            'optional': True
        },
        {
            'key': 'moderate_tsunami_hazard_zone',
            'name': tr('Moderata Tsunami Hazard Zone'),
            'description': tr('The area is potentially hit by tsunami wave which inundation depth 1 - 3 m or equal to V-VI tsunami intensity scale (Papadoupulos and Imamura, 2001). Tsunami wave with 3 m inundation depth cause most people frightened and flee to higher elevation. Small vessels drifted and collided. Damage occurs on some wooden house, while most of them are safe.'),
            'numeric_default_min': 1,
            'numeric_default_max': 3,
            'optional': True
        },
        {
            'key': 'low_tsunami_hazard_zone',
            'name': tr('Low Tsunami Hazard Zone'),
            'description': tr('The area is potentially hit by tsunami wave which inundation depth less than 1 m or similar to tsunami intensity scale of V or less in (Papadoupulos and Imamura, 2001). Tsunami wave of 1 m height causes few people frightened and flee to higher elevation. Felt by most people on large ship, observed from shore. Small vessels are drifted and collided and, some turn over. Sand is deposited on particular place. Flooding on area close to the shore.'),
            'numeric_default_min': 0,
            'numeric_default_max': 1,
            'optional': True
        }
    ]
}
```

**Comment by Charlotte-Morgan** [comment]
Hi @ismailsunni - I am not sure this is the correct spot. Which IF uses the tsunami raster hazard classes?

IIUC - we can use continuous raster hazard data for tsunami to assess which buildings are wet or dry based on a single threshold (default is 1m for buildings + flood raster building function and 0.7m for people + tsunami evacuation function)
If the user can enter multiple thresholds then we can add the description here and define defaults however these are different for each exposure data type...
If the user can not enter more than 1 threshold; then we need to make classified hazard data. Again - a problem because the data will be different depending on each exposure.

Maybe we need to make the tsunami IF first :)

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni & @timlinux - we need to get this fixed and into 3.3 please

**Comment by timlinux** [comment]
Just pinging on this - is there still something that needs doing here?

**Comment by Charlotte-Morgan** [comment]
we need the text in the right file. I'm not sure if we have identified the right place for it to go. I also have the reference for the logic in the tsunami IFs. 
the reference is: 
Papadopoulos, Gerassimos A., and Fumihiko Imamura. "A proposal for a new tsunami intensity scale."  ITS 2001 proceedings, no. 5-1, pp. 569-577. 2001.

**Comment by Charlotte-Morgan** [comment]
hi @easmetz  - this one too.

All the info is supplied above; its just a matter of finding the right files to put it in and checking it appears where you want it to :)

**Comment by Charlotte-Morgan** [comment]
@easmetz  - I picked this up again because it fits well with the 3.4 release
