### ISSUE TITLE
Update: tsunami hazard data symbology

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#1252]
Aim is to display BG tsunami hazard data in the same way as the technical agency maps.

# cc 
@mahardika

**Comment by Charlotte-Morgan** [comment]
Hi @samnawi 
handing this over to you.
Please update our 'standard' display of tsunami hazard data to match the classes used by BG and quoted in PERKA 2/2012.

Low hazard zone < 1m
Moderate hazard zone 1-3m
High hazard zone > 3m

It would be great to have this done for 3.3 release and any training there after.

**Comment by samnawi** [comment]
Hi @Charlotte-Morgan 
According to Tsunami Hazard Zone from Badan Geologi
![selection_085](https://cloud.githubusercontent.com/assets/8871958/13425103/4d524afe-dfd7-11e5-8128-bc3664873273.png)
I've tried to symbolized the tsunami hazard map like this
![selection_084](https://cloud.githubusercontent.com/assets/8871958/13425129/6b18b74e-dfd7-11e5-9121-c1ccfd15d987.png)

Is it OK?

**Comment by Charlotte-Morgan** [comment]
this looks nice - lets make it happen

**Comment by timlinux** [comment]
Can we close this out @samnawi ?

**Comment by samnawi** [comment]
OK @timlinux
