### ISSUE TITLE
RFC: Testing Strategy in InaSAFE

### ISSUE THREAD

**Issue by akbargumbira** [inasafe/inasafe#1273]
# Problem
## Taking Too Much Time

Right now we have a quite good testing for this project. But for me, running all the tests before making PR is painful as it will take some time to run the full tests (could take 30-40 minutes for safe, safe_qgis, and realtime package on my computer). 
## The State of Our CI

The state of jenkins and travis that we have right now is also not satisfying. We splitted up jenkins to test InaSAFE in smaller packages (safe, realtime, and each package in safe_qgis) so that Jenkins won't get stuck. It is working quite nice for safe_qgis, but not for safe as we often found it still got stuck. By splitting them up, we have also got another problem: every time the developer pushes some codes to github, jenkins will need to fetch github for all of the jobs (right now we have 8 jobs in develop tab - http://jenkins.inasafe.org/view/QGIS2-InaSAFE-develop/), which is not effective. And more likely because of that, jenkins sometimes could not fetch the latest revision for some jobs.

Our Travis is also only running safe_qgis package. For the free version, Travis only allows the job to run in less than 50 minutes. With only running safe_qgis package, it already took ~ 40 minutes. 

In short, we need to have a better strategy so that the tests could be run in instantaneous way.
# Duration

TBD
# Current State

This proposal is in **draft**.
# Proposers

@akbargumbira
# Proposed Solution

This is just my idea, perhaps others who have more experience could give better solution.
## Separating Unit Testing and Integration Testing from Validation Testing

For unittesting and integration, we should just use dummy data. At the moment, in some of our tests (especially safe package), we use real data (from inasafe_data). We could put all these dummy data in the InaSAFE repository with sensible size so that inasafe repo doesn't get that much bigger to clone and the unittesting and integration testing could run fast. Jenkins and Travis that we have now should run this kind of tests in every PR (Travis), or every commits that are pushed to develop and master branch (Jenkins and Travis).
## Validation Testing

In the validation testing, we use the real data in inasafe_data to test InaSAFE in a higher level that could concern GIS people on how InaSAFE works. The tests could be:
- Testing if our clipping or resampling method works as expected
- Running all possible IF scenarios with batch runner and compare the results with some control files.

With these 2 kind of testings, in day to day development, developers just need to make sure that the unittesting and integration testing pass. We could run validation testing prior to a release and we could have scheduled job to run it once in a while. Sure the control files for validations may need to be changed often. GIS Analyst here can help if the new results make sense compared to the previous control files.
## Test should not alter the test data

Every time the tests finished, the tests should make the test data back to a clean state. Right now, we have some test data that get altered after running the tests. Here is @timlinux's gist showing the altered test data https://gist.github.com/timlinux/88e7f02bbf019e7e8e9f. Perhaps this could be resolved in the 2.2 version.
# Record of votes
# Resolution
# CC

@timlinux @Charlotte-Morgan @assefay @mbernasocchi @mach0 @cchristelis @ismailsunni @dichapabe

**Comment by Gustry** [comment]
I think we can close that one now. We are now using docker for testing (15 minutes) and we are deprecating inasafe_data step by step.
