### ISSUE TITLE
Add standard header to all .py files

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#129]
Potential task for in-country developers:

All the python files (besides gui which is already done) need to have a standard header added. See 'standard header section' at http://inasafe.readthedocs.org/en/latest/developer-docs/coding_standards.html#code-style

**Comment by ismailsunni** [comment]
We agree to put it in the backlog as this ticket has low priority

**Comment by timlinux** [comment]
Just bumping this again. Here is my proposed standard header:

```python
__author__ = "Tim Sutton, Ismail Sunni, Etienne Trimaille"
__copyright__ = "Copyright 2016, The InaSAFE Project"
__credits__ = ["Tim Sutton", "Ismail Sunni", "Etienne Trimaille", "Charlotte Morgan"]
__license__ = "GPL"
__version__ = "4"
__maintainer__ = "Tim Sutton"
__email__ = "info@inasafe.org"
__status__ = "Production"
```

**Comment by timlinux** [comment]
See also http://stackoverflow.com/a/1523456

**Comment by timlinux** [comment]
Reading the various pros and cons I think we should go with a simpler approach and have this in every file (replacing maintainer with the actual maintainer):

```
__copyright__ = "Copyright 2016, The InaSAFE Project"
__license__ = "GPL"
__maintainer__ = "Tim Sutton"
__email__ = "info@inasafe.org"
```

**Comment by ismailsunni** [comment]
@timlinux 
What's the definition of maintainer? The last one who edit the file? The first creator? Can it be more than one person?

For email, should we always use info@inasafe.org or replace it with the maintainer's email?

Should we change the "Copyright 2016, The InaSAFE Project" next year for every updated files?

**Comment by timlinux** [comment]
I'm closing this off - standards for this are maintained in https://github.com/inasafe/inasafe/wiki/Coding-Standards#standard-headers 

Devs should incrementally improve existing headers as they work on modules. 

@ismailsunni yes the copyright should reflect the year when the module is created.

**Comment by akbargumbira** [comment]
> Hi
> 
> On Tue, Apr 3, 2012 at 3:37 AM, Ole Nielsen
> reply@reply.github.com
> wrote:
> 
> Yes that is a good idea. Only question is why each file has a version attribute when the value of that always is the same across the project?
> It seems that the potential for inconsistency is huge.
> I can look at how much hassle it will be to incorporate the git SHA1
> in there rather, which would probably be the most useful thing to have
> in there. I guess the use case for having verion as it is now is that
> if someone lifts a module out of the project there is some reference
> to which release it came from, but I agree a SHA1 or other unique
> reference would make more sense.
> 
> Wouldn't it be better to remove it and just have a project wide version code.
> Probably it would be ideal to have both.
> 
> Regards
> 
> Tim

It seems that __version__ attribute is removed and the case mentioned above is on point where now I am packaging SAFE...
