### ISSUE TITLE
We need a working, documented backup system for the server

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#1298]
Can you please spend some time to come up with a plan to ensure we have a proper backup system? Perhaps we can rsync / btsync backups to a filestore on the AIFDR cluster? Also we should document how to go about restoring the running services in the case of total hardware failure / security breach. Including but not limited to:
- osm.linfiniti.com (for osm downloader) - @timlinux to do
- experimental.inasafe.org (for nightly packages)
- test documentation builds
- live web site
- download site
- blog

We can also look at using hetzner backup services though I don't think they provide a big enough storage space. Also we could look at using backblaze - its USD 5 a month with unlimited storage.

@Charlotte-Morgan

**Comment by timlinux** [comment]
@hvisage - please take this on - with @rduivenvoorde to ensure we have a backup system in place - using the hetzner backup storage we have purchased.

**Comment by hvisage** [comment]
Okay, backups are set since this afternoon :)

The current is that it'll backup the files in /data/backups and /data/dbbackups, and will keep incrementals for 2 weeks and weekly fulls for a month. 

If there are any other directories please let me know.

@timlinux you would dump the database backups into /data/dbbackups, correct? I don't yet see any, that is why I ask.

@mach0 @rduivenvoorde

**Comment by timlinux** [comment]
@lucernae will you take over this issue and make sure that the services are being backed up

**Comment by timlinux** [comment]
@lucernae and @gubuntu One for the realtime / web side of things. We can use the wiki to describe the full procedure. We should aim to have all the services restorable from the backups and regularly tested by doing a full restore on the staging servers we plan to set up.

**Comment by timlinux** [comment]
Closing this in favour of the ticket in inasafe-realtime repo
