### ISSUE TITLE
We should consider cell height and width when clipping rasters

### ISSUE THREAD

**Issue by akbargumbira** [inasafe/inasafe#1301]
# Problem

When we do the clipping in the case when the hazard and the exposure are raster, we only consider the width of the cell size. See `get_wgs84_resolution`:

```
def get_wgs84_resolution(layer):
    """Return resolution of raster layer in EPSG:4326.

    If input layer is already in EPSG:4326, simply return the resolution
    If not, work it out based on EPSG:4326 representations of its extent.

    :param layer: Raster layer
    :type layer: QgsRasterLayer or QgsMapLayer

    :returns: The resolution of the given layer.
    :rtype: float

    """

    msg = tr(
        'Input layer to getWGS84resolution must be a raster layer. '
        'I got: %s' % str(layer.type())[1:-1])
    if not layer.type() == QgsMapLayer.RasterLayer:
        raise RuntimeError(msg)

    if layer.crs().authid() == 'EPSG:4326':
        cell_size = layer.rasterUnitsPerPixelX()
    else:
        # Otherwise, work it out based on EPSG:4326 representations of
        # its extent

        # Reproject extent to EPSG:4326
        geo_crs = QgsCoordinateReferenceSystem()
        geo_crs.createFromSrid(4326)
        transform = QgsCoordinateTransform(layer.crs(), geo_crs)
        extent = layer.extent()
        projected_extent = transform.transformBoundingBox(extent)

        # Estimate cell size
        columns = layer.width()
        geo_width = abs(
            projected_extent.xMaximum() -
            projected_extent.xMinimum())
        cell_size = geo_width / columns

    return cell_size
```

When we do the clipping, to get the resolution of the clipped layer, here is our logic:

```
if hazard_geo_cell_size < exposure_geo_cell_size and \
                        allow_resampling_flag:
                    cell_size = hazard_geo_cell_size
                    layer_extent = hazard_geoextent
                else:
                    cell_size = exposure_geo_cell_size
                    layer_extent = exposure_geoextent
```

It means that we will always get square cell of the clipped layer. If both input layers are rectangular, e.g have these resolutions: Hazard (7, 2), Exposure (10, 1), the clipped layer will have the cell size (7, 7).

This also will make other function not working as we expect e.g for the case when hazard is raster and the exposure is vector, we will buffer the extent to make the interpolation work for edge pixels using:

```
 adjusted_geo_extent = get_buffered_extent(
                    geo_extent,
                    hazard_geo_cell_size)
```

which the buffered_extent itself is expecting the cell size as a tuple (see function `buffered_bounding_box` in `safe.storage.utilities`:

```
 bbox = copy.copy(list(bbox))

    if resolution is None:
        return bbox

    try:
        resx, resy = resolution
    except TypeError:
        resx = resy = resolution

    bbox[0] -= resx
    bbox[1] -= resy
    bbox[2] += resx
    bbox[3] += resy

    return bbox
```
# Proposed Solution

For now, I will change the `get_wgs84_resolution` to return a tuple containing width and length of the cell size. But I am still not sure how we decide the cell size of the clipped layer for the case when at least one of them is rectangular. 
# CC

@timlinux @assefay @Charlotte-Morgan

**Comment by timlinux** [comment]
Thankfully another thing we don't need to deal with since we polygonise rasters. @wonder-sk I am closing here but it would be great if you comment on whether the QGIS Raster Alignment tool works well with different X & Y dimensions to raster pixels.

**Comment by wonder-sk** [comment]
Hi there... QGIS raster alignment tool indeed work seamlessly also with non-square cells - both for input rasters and for output ones.
