### ISSUE TITLE
We need to create a  Sphere minimum needs file

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#1317]
# Problem

With #1230 we can now support minimum needs profiles. We should create a globally relevant profile based on Sphere (ref?)

# Expected outcome

Non Indonesian users should be able to get some sensible minimum needs reporting 'out the box'

Assigning to @assefay to hand over to @cchristelis

**Comment by cchristelis** [comment]
Hi @mahardika, I just wanted to let you know that once the needs have been determined that I can help you with the formatting and adding it into InaSAFE.

**Comment by akbargumbira** [comment]
@cchristelis Dika is not working for AIFDR anymore. I think the items in @assefay's link can be converted to the needs profile we have as a start.

**Comment by timlinux** [comment]
I took the list from @fredychandra above and created a minimum needs profile:

![screen shot 2016-06-22 at 15 58 35](https://cloud.githubusercontent.com/assets/178003/16295484/796ff29a-3927-11e6-8036-78cdbb50e7de.png)


Running on JK Flood ( @Charlotte-Morgan 's favourite! ) I get this:

![screen shot 2016-06-23 at 09 45 40](https://cloud.githubusercontent.com/assets/178003/16295505/91574cd2-3927-11e6-8279-38965aa931d7.png)

I will make a PR for it.

**Comment by timlinux** [comment]
Note I already updated the provenance to show it as SPERE rather

**Comment by Charlotte-Morgan** [comment]
@timlinux  - sphere
