### ISSUE TITLE
Get requirement for Tsunami IF on roads

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#1427]

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
this comment is a note only, that we want to create Tsunami IF on road, population, and building similar to Flood IF, but different in default depth and other metadata. We will start doing this after IF refactor is finished.

**Comment by Charlotte-Morgan** [comment]
i do not have any specific advice on this.
May i suggest we use the same as impact on buildings #1428 until we are advised of something better

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni - here are the requirements for tsunami IF

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni 

This ticket requires a new tsunami on road impact function. the thresholds should be the same as the building impact function as per #1428 - please see the comment above from Nov 27 2015.

All tsunami IF (population, buildings and roads) should also reference the source of the expertise for the thresholds also provided in #1428  

@timlinux - this is why I have given the thumbs down to the release. The changelog does not correctly describe the new tsunami on buildings IF.  It has 3 classes with thresholds at 1, 3 and 8 m
Impact on people is at 0.7m

**Comment by Gustry** [comment]
Is this issue still a release blocker @Charlotte-Morgan ? I think it was for 3.3.
Since March, we have now Tsunami on roads, thresholds can be changed.

**Comment by Charlotte-Morgan** [comment]
hi @Gustry  - this was fixed at 3.3 and can be closed thank you
