### ISSUE TITLE
Get requirement for Tsunami IF on buildings

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#1428]

**Comment by ismailsunni** [comment]
hi @Charlotte-Morgan 

Is there any update related to this ticket? And is there any update for tsunami IF in general? This is included in scoping section in milestone version 3.1.

**Comment by Charlotte-Morgan** [comment]
According to advice from Pak Hamza.
He has offered the following thresholds for tsunami impact on buildings based on the tsunami intensity scale published by Papadopoulos and Imamura (2001)
low hazard zone < 1m
moderate hazard zone 1 - 3m
high hazard zone 3 - 8m
very high hazard zone > 8m

Published tsunami intensity scale available here http://geology.about.com/od/tsunamis/a/Tsunami-Intensity-Scale-2001.htm

This also aligns with the hazard classification used by Badan Geology on published tsunami hazard maps and quoted in BNPB PERKA 2/2012.

In these documents:
Low hazard zone < 1m
Moderate hazard zone 1-3m
High hazard zone > 3m

Please note these are hazard classes for hazard data. # 1251

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni - here are the requirements for tsunami IF
