### ISSUE TITLE
RFC: Population as points

### ISSUE THREAD

**Issue by maning** [inasafe/inasafe#1442]
# Problem

Current implementation of IFs using population as exposure rely on raster population data.  Sources of population data as raster is  limited.  However, in the Philippines there are local initiatives that create local government level data on household population using the tool Community–Based Monitoring System ([CBMS](http://www.dlsu.edu.ph/research/centers/aki/participant/cbms/Default.aspx)).  CBMS allows data collection at the household level including numerous set of population information not available in the national level census initiatives.  The household survey includes geospatial attributes coded as points.  This data can be used as a proxy data for estimating impact on population. This RFC explores another approach for improving the accuracy of affected population results that InaSAFE produces for impacts on people.
# Duration
# Current State

This proposal is in **draft - please contribute** (we will update this RFC as we get more details about the CBMS data format)
# Proposers
- Maning Sambale (@maning)
- Dianne Bencito (@dichapabe)
# Detail
# See also
#1179

**Comment by ismailsunni** [comment]
I think we can close this as we support population as point in #4592
