### ISSUE TITLE
RFC: Extending the generic categorized IF to specific hazard IF

### ISSUE THREAD

**Issue by maning** [inasafe/inasafe#1443]
# Problem

The generic categorized IF provides the basic framework for many hazard type utilizing categorical data types (low, medium, high).  For our use case in the Philippines, we are using this IF for categorical flood, categorical landslide, and categorical storm surge hazards.  But the impact layers, statistics and map obviously refers to a generic hazard impact in the resulting output.  For better usability by regular users, it would be better to create specific IF for the specific hazard.
# Duration
# Current state

This proposal is in **draft**
# Proposers
- Maning Sambale (@maning)
- Dianne Bencito (@dichapabe)
# Detail

We see two options for this.
1. Create separate IF for each hazard type (landslide, flood, stormsurge), inheriting the basic functionality of the generic categorical IF by simply replacing the reference to each hazard type (i. e. keywords, title headers, etc.).
2. Create a separate UI for generic categorical IF where users can define various attributes/parameters related to the hazard type.  For example, a dialog box defining that the hazard type is flood, landslide, etc. This attributes/parameters will then be used by the generic categorical IF to populate the keywords, title headers, etc. in the output map, statistics and impact layer.  This is similar to what @ismailsunni is building on https://github.com/AIFDR/parameters
# See also
- Developing IF for flood hazard with categorical values (#1105)
- RFC: Requesting for Landslide Impact Function (#1219)

**Comment by timlinux** [comment]
@maning in the new architecture for 4.0 we can easily add new hazards and thresholds by creating definitions in ``hazards.py`` and ``hazard_classifications.py``. In the future we plan to also develop GUI tools for creating these definitions. I think we can close this issue and rather focus on specific hazard contributions to the above mentioned files.
