### ISSUE TITLE
Failed Unit Test Without inasafe_data

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#1448]
Since we want to move from `inasafe_data`, I ran all unit test without it, and here is the list of failed unit test:
### safe/engine
- [ ] test_interpolation_from_polygons_error_handling
- [ ] test_interpolation_from_polygons_multiple
- [ ] test_interpolation_from_polygons_one_poly
- [ ] test_interpolation_lembang
- [ ] test_interpolation_tsunami
- [ ] test_interpolation_tsunami_maumere
- [ ] test_layer_integrity_raises_exception
- [ ] test_line_clipping_by_polygon
- [ ] test_line_interpolation_from_multiple_polygons
- [ ] test_line_interpolation_from_polygons_one_poly
- [ ] test_polygon_clipping
- [ ] test_polygon_hazard_and_raster_exposure_big
- [ ] test_polygon_hazard_and_raster_exposure_small
- [ ] test_polygon_hazard_with_holes_and_raster_exposure
- [ ] test_polygon_to_roads_interpolation_flood_example
- [ ] test_raster_vector_interpolation_exception
- [ ] test_tagging_polygons_by_raster_values
### safe/gui/tools/test/test_save_scenario
- [ ] test_relative_path
- [ ] test_save_scenario
- [ ] test_validate_input
### safe/gui/tools/test/test_extent_selector.py
- [ ] test_mouse_drag
### safe/gui/tools/test/test_keywords_dialog.py
- [x] test_add_keyword_when_press_ok_button
- [x] test_get_value_for_key
- [x] test_load_state_from_keywords
- [x] test_on_dsb_female_ratio_default_value_changed
- [x] test_on_rad_postprocessing_toggled
- [x] test_remove_item_by_value
- [x] test_check_aggregation
### safe/gui/tools/test/test_wizard_dialog.py
- [x] test_auto_select_one_item
- [x] test_default_attributes_value
- [x] test_existing_aggregation_keywords
- [x] test_existing_keywords
- [x] test_integrated_line
- [x] test_integrated_point
- [x] test_integrated_polygon
- [x] test_keywords_creation_wizard
- [x] test_point_layer
- [x] test_sum_ratio_behavior
- [x] test_unit_building_generic
- [x] test_unknown_unit
### safe/gui/widgets/test/test_dock.py
- [ ] test_cbo_aggregation_empty_project
- [ ] test_cbo_aggregation_toggle
- [ ] test_defaults
- [ ] test_full_run_pyzstats
- [ ] test_full_run_qgszstats
- [ ] test_has_parameters_button_disabled
- [ ] test_has_parameters_button_enabled
- [ ] test_insufficient_overlap
- [ ] test_issue1191
- [ ] test_issue160
- [ ] test_issue306
- [ ] test_issue317
- [ ] test_issue47
- [ ] test_issue581
- [ ] test_issue71
- [ ] test_layer_changed
- [ ] test_load_layers
- [ ] test_new_layers_show_in_canvas
- [ ] test_result_styling
- [ ] test_rubber_bands
- [ ] test_set_dock_title
- [ ] test_set_ok_button_status
- [ ] test_state
- [ ] test_user_defined_extent
- [ ] test_validate
### safe/impact_functions/earthquake/test/test_pager_earthquake_fatality_model.py
- [x] test_pager_earthquake_fatality_estimation
### safe/impact_functions/earthquake/test/test_earthquake_building_impact.py
- [x] test_earthquake_building_impact_function
### safe/impact_functions/earthquake/test/test_itb_earthquake_fatality_model.py
- [x] test_itb_earthquake_fatality_estimation
### safe/impact_functions/generic/test/test_categorical_hazard_population.py
- [x] test_categorical_hazard_population_impact_function
### safe/impact_functions/inundation/test/test_flood_OSM_building_impact.py
- [x] test_flood_building_impact_function
- [x] test_flood_building_impact_function_vector
### safe/impact_functions/inundation/test/test_flood_population_polygon.py
- [x] test_flood_population_evacuation_polygon
### safe/impact_functions/inundation/test/test_flood_population_raster.py
- [x] test_flood_population_evacuation
### safe/impact_functions/test/test_core.py
- [ ] test_aggregate_real
- [ ] test_get_admissible_plugins
### safe/impact_functions/volcanic/test/test_volcano_population_evacuation_polygon.py
- [x] test_volcano_circle_population_impact
- [x] test_volcano_population_evacuation_impact
### safe/impact_functions/volcanic/test/test_volcano_building.py
- [x] test_volcano_building_impact
### safe/impact_statistics/test/test_function_options_dialog.py
- [x] test_build_form
- [x] test_build_form_minimum_needs
### safe/impact_statistics/test/test_postprocessor_manager.py
- [ ] test_check_postprocessing_layers_visibility
- [ ] test_post_processor_output
### safe/impact_statistics/test/test_aggregator.py
- [ ] test_aggregate_raster_impact_native
- [ ] test_aggregate_raster_impact_python
- [ ] test_aggregate_vector_impact
- [ ] test_aggregation_attribute_in_keywords
- [ ] test_check_aggregation_no_attributes
- [ ] test_check_aggregation_none_in_keywords
- [ ] test_check_aggregation_single_attribute
- [ ] test_combo_aggregation_loaded_project
- [ ] test_get_centroids
- [ ] test_line_aggregation
- [ ] test_preprocessing
- [ ] test_set_layers
- [ ] test_set_sum_field_name
- [ ] test_setup_target_field
### safe/report/test/test_map.py
- [x] test_custom_logo
- [x] test_default_template
- [x] test_get_map_title
- [x] test_handle_missing_map_title
### safe/report/test/test_map_legend.py
- [x] test_add_class_to_legend
- [x] test_add_symbol_to_legend
- [x] test_get_legend
- [x] test_get_raster_legend
- [x] test_get_vector_legend
### safe/report/test/test_html_renderer.py
- [x] test_print_impact_table
### safe/storage/test/test_clipping.py
- [ ] test_clip_points_by_polygons
- [ ] test_clip_points_by_polygons_with_holes_real
### safe/storage/test/test_io.py
- [ ] test_bad_ascii_data
- [ ] test_3d_polygon
- [ ] test_analysis_of_vector_data_top_N
- [ ] test_attribute_types
- [ ] test_bins
- [ ] test_centroids_from_polygon_data
- [ ] test_compatible_projections
- [ ] test_donut_polygons
- [ ] test_get_bounding_box
- [ ] test_keywords_file
- [ ] test_layer_API
- [ ] test_line_to_points
- [ ] test_multipart_polygon_can_be_read
- [ ] test_nodata_value
- [ ] test_polygon_area
- [ ] test_polygon_centroids
- [ ] test_projection_comparisons
- [ ] test_raster_extrema
- [ ] test_raster_to_vector_points
- [ ] test_raster_to_vector_points2
- [ ] test_reading_and_writing_of_real_rasters
- [ ] test_reading_and_writing_of_vector_line_data
- [ ] test_reading_and_writing_of_vector_point_data
- [ ] test_reading_and_writing_of_vector_polygon_data
- [ ] test_vector_class
- [ ] test_vector_extrema
- [ ] test_vector_feature_count
### safe/test/test_qgis_environment.py
- [x] test_proj_interpretation
### safe/utilities/test/test_impact_calculator.py
- [ ] test_issue100
- [ ] test_need_clip
- [ ] test_properties
- [ ] test_run
- [ ] test_start_with_no_parameters
- [ ] test_thread
### safe/utilities/test/test_keyword_io.py
- [x] test_append_keywords
- [x] test_are_keywords_file_based
- [x] test_copy_keywords
- [x] test_get_hash_for_datasource
- [x] test_read_db_keywords
- [x] test_read_legacy_db_keywords
- [x] test_read_raster_file_keywords
- [x] test_read_vector_file_keywords
- [x] test_write_read_keyword_from_uri
### safe/utilities/test/test_styling.py
- [x] test_issue126
- [x] test_issue_121
- [x] test_transparency_of_minimum_value
### safe/utilities/test/test_gis.py
- [x] test_get_layer_attribute_names
- [x] test_is_polygonal_layer
### safe/utilities/test/test_analysis.py
- [ ] test_get_optimal_extent
### safe/utilities/test/test_utilities.py
- [x] test_get_keyword_from_file
### safe/utilities/test/test_clipper.py
- [ ] test_clip_both
- [ ] test_clip_vector
- [ ] test_vector_projections
- [ ] test_clip_raster
- [ ] test_raster_scaling
- [ ] test_raster_scaling_projected

CC @akbargumbira @timlinux @Charlotte-Morgan

**Comment by akbargumbira** [comment]
Update per 10 April:
# safe.engine.test.test_engine.TestEngine
- [ ] safe.engine.test.test_engine.TestEngine#test_interpolation_from_polygons_error_handling
- [ ] safe.engine.test.test_engine.TestEngine#test_interpolation_from_polygons_multiple
- [ ] safe.engine.test.test_engine.TestEngine#test_interpolation_from_polygons_one_poly
- [ ] safe.engine.test.test_engine.TestEngine#test_interpolation_lembang
- [ ] safe.engine.test.test_engine.TestEngine#test_interpolation_tsunami
- [ ] safe.engine.test.test_engine.TestEngine#test_interpolation_tsunami_maumere
- [ ] safe.engine.test.test_engine.TestEngine#test_layer_integrity_raises_exception
- [ ] safe.engine.test.test_engine.TestEngine#test_line_clipping_by_polygon
- [ ] safe.engine.test.test_engine.TestEngine#test_line_interpolation_from_multiple_polygons
- [ ] safe.engine.test.test_engine.TestEngine#test_line_interpolation_from_polygons_one_poly
- [ ] safe.engine.test.test_engine.TestEngine#test_polygon_clipping
- [ ] safe.engine.test.test_engine.TestEngine#test_polygon_hazard_and_raster_exposure_big
- [ ] safe.engine.test.test_engine.TestEngine#test_polygon_hazard_and_raster_exposure_small
- [ ] safe.engine.test.test_engine.TestEngine#test_polygon_hazard_with_holes_and_raster_exposure
- [ ]  safe.engine.test.test_engine.TestEngine#test_polygon_to_roads_interpolation_flood_example
- [ ] safe.engine.test.test_engine.TestEngine#test_raster_vector_interpolation_exception
- [ ] safe.engine.test.test_engine.TestEngine#test_tagging_polygons_by_raster_values

# safe.gui.widgets.test.test_dock.TestDock
- [ ] safe.gui.widgets.test.test_dock.TestDock#test_issue160
- [ ] safe.gui.widgets.test.test_dock.TestDock#test_issue71
- [ ] safe.gui.widgets.test.test_dock.TestDock#test_layer_changed
- [ ] safe.gui.widgets.test.test_dock.TestDock#test_layer_saved_as_with_keywords_and_xml
- [ ] safe.gui.widgets.test.test_dock.TestDock#test_layer_saved_as_without_keywords_and_xml
- [ ] safe.gui.widgets.test.test_dock.TestDock#test_new_layers_show_in_canvas

# safe.impact_statistics.test.test_aggregator.AggregatorTest
- [ ] safe.impact_statistics.test.test_aggregator.AggregatorTest#test_aggregate_raster_impact_native
- [ ] safe.impact_statistics.test.test_aggregator.AggregatorTest#test_aggregate_raster_impact_python
- [ ] safe.impact_statistics.test.test_aggregator.AggregatorTest#test_aggregate_vector_impact
- [ ] safe.impact_statistics.test.test_aggregator.AggregatorTest#test_check_aggregation_no_attributes
- [ ] safe.impact_statistics.test.test_aggregator.AggregatorTest#test_check_aggregation_none_in_keywords
- [ ] safe.impact_statistics.test.test_aggregator.AggregatorTest#test_check_aggregation_single_attribute
- [ ] safe.impact_statistics.test.test_aggregator.AggregatorTest#test_get_centroids
- [ ] safe.impact_statistics.test.test_aggregator.AggregatorTest#test_line_aggregation
- [ ] safe.impact_statistics.test.test_aggregator.AggregatorTest#test_set_sum_field_name
- [ ] safe.impact_statistics.test.test_aggregator.AggregatorTest#test_setup_target_field

# safe.storage.test.test_clipping.Test_Clipping
- [ ] safe.storage.test.test_clipping.Test_Clipping#test_clip_points_by_polygons
- [ ] safe.storage.test.test_clipping.Test_Clipping#test_clip_points_by_polygons_with_holes_real

# safe.storage.test.test_io.TestIO
- [ ] safe.storage.test.test_io.TestIO#test_3d_polygon
- [ ] safe.storage.test.test_io.TestIO#test_analysis_of_vector_data_top_N
- [ ] safe.storage.test.test_io.TestIO#test_attribute_types
- [ ] safe.storage.test.test_io.TestIO#test_bad_ascii_data
- [ ] safe.storage.test.test_io.TestIO#test_bins
- [ ] safe.storage.test.test_io.TestIO#test_centroids_from_polygon_data
- [ ] safe.storage.test.test_io.TestIO#test_compatible_projections
- [ ] safe.storage.test.test_io.TestIO#test_donut_polygons
- [ ] safe.storage.test.test_io.TestIO#test_get_bounding_box
- [ ] safe.storage.test.test_io.TestIO#test_keywords_file
- [ ] safe.storage.test.test_io.TestIO#test_layer_API
- [ ] safe.storage.test.test_io.TestIO#test_line_to_points
- [ ] safe.storage.test.test_io.TestIO#test_multipart_polygon_can_be_read
- [ ] safe.storage.test.test_io.TestIO#test_nodata_value
- [ ] safe.storage.test.test_io.TestIO#test_polygon_area
- [ ] safe.storage.test.test_io.TestIO#test_polygon_centroids
- [ ] safe.storage.test.test_io.TestIO#test_projection_comparisons
- [ ] safe.storage.test.test_io.TestIO#test_raster_extrema
- [ ] safe.storage.test.test_io.TestIO#test_raster_to_vector_points
- [ ] safe.storage.test.test_io.TestIO#test_raster_to_vector_points2
- [ ] safe.storage.test.test_io.TestIO#test_reading_and_writing_of_real_rasters
- [ ] safe.storage.test.test_io.TestIO#test_reading_and_writing_of_vector_line_data
- [ ] safe.storage.test.test_io.TestIO#test_reading_and_writing_of_vector_point_data
- [ ] safe.storage.test.test_io.TestIO#test_reading_and_writing_of_vector_polygon_data
- [ ] safe.storage.test.test_io.TestIO#test_vector_class
- [ ] safe.storage.test.test_io.TestIO#test_vector_extrema
- [ ] safe.storage.test.test_io.TestIO#test_vector_feature_count

# safe.utilities.test.test_analysis.TestAnalysis
- [ ] safe.utilities.test.test_analysis.TestAnalysis#test_get_optimal_extent

# safe.utilities.test.test_clipper.ClipperTest
- [ ] safe.utilities.test.test_clipper.ClipperTest#test_clip_both
- [ ] safe.utilities.test.test_clipper.ClipperTest#test_clip_raster
- [ ] safe.utilities.test.test_clipper.ClipperTest#test_clip_vector
- [ ] safe.utilities.test.test_clipper.ClipperTest#test_raster_scaling
- [ ] safe.utilities.test.test_clipper.ClipperTest#test_raster_scaling_projected
- [ ] safe.utilities.test.test_clipper.ClipperTest#test_vector_projections

# safe.utilities.test.test_impact_calculator.ImpactCalculatorTest
- [ ] safe.utilities.test.test_impact_calculator.ImpactCalculatorTest#test_issue100
- [ ] safe.utilities.test.test_impact_calculator.ImpactCalculatorTest#test_need_clip
- [ ] safe.utilities.test.test_impact_calculator.ImpactCalculatorTest#test_properties
- [ ] safe.utilities.test.test_impact_calculator.ImpactCalculatorTest#test_run
- [ ] safe.utilities.test.test_impact_calculator.ImpactCalculatorTest#test_start_with_no_parameters
- [ ] safe.utilities.test.test_impact_calculator.ImpactCalculatorTest#test_thread

**Comment by ismailsunni** [comment]
When trying to release 3.4, I found it's very painful to wait ~40 minutes for travis to finish. Hopefully, we can remove inasafe_data for testing and travis will be faster, since we use smaller data test.
From https://travis-ci.org/inasafe/inasafe/builds/134095743

Our test is taking 2231.620 seconds (37 minutes) for 581 tests. It's about 3.83 seconds per test.
Make test data needs 23.71 seconds
apt-get install needs 83.54 s

If we can make it down to 1 second per test on average, it will take about 10 minutes for testing itself. So, at most we needs 13 minutes to finish all the tests. Sounds good.

So, if we make a new test, make it less than 1 seconds.

**Comment by ismailsunni** [comment]
From #2890 and https://travis-ci.org/inasafe/inasafe/builds/134347919, we got 35 errors and 6 failures.

**Comment by Gustry** [comment]
We can close this one in V4
