### ISSUE TITLE
Some overlap parameters when running analysis

### ISSUE THREAD

**Issue by akbargumbira** [inasafe/inasafe#1481]
# Problem

Taken from this: https://github.com/AIFDR/inasafe/issues/1163

@ismailsunni:
" There are some overlap parameters from IF and from layer's keywords. For example, gender and age ratio exist in both IF and aggregation layer. Or the affected field exist in the new keywords system and the current IF. What we will do about this?"

@akbargumbira:
"In InaDRTG workshop, I had some feedbacks from the users. I tried to put myself as the user, and I found something not consistent in our UX related to postprocessor. This is before data driven for age from Dianne's PR. So, let's talk about this as if we don't have the data driven for age. The inconsistency is that if we want to set the the gender ratio, we need to set it on the global option (if we don't use aggregation), meanwhile, for the age ratio, we need to set it on the IF option. For the user, the abstraction based on that scenario is that we treat the age ratio to depend on IF, but not for the gender ratio. This makes confusion for the user to understand the workflow.

For the current state, user could easily get confused for these cases (these cases basically are the user's point of view from @ismailsunni's point):
1. For female ratio, if the user wants to use aggregation layer and he/she wants to use global default, will it use the global default on InaSAFE option or global default on keywords editor? (I just tried it, it will use the global default on keywords editor). The problem is that those two options do not synchronize each other, i.e if the user sets the female ratio on InaSAFE option, the female ratio on keywords editor does not get changed, and vice versa, if the user sets the female ratio on keywords editor, the female ratio on InaSAFE option does not get changed. I think for the latter case it's fine as the user may want to use different value from the global InaSAFE female ratio. But for the first case, I think we should make it synchronized, right?
2. For the age ratio, if the user does not use aggregation layer, and he/she sets the ratio on the IF, it will have no effect. It will stil use the global default ratio (from safe.default). Perhaps this is just a bug, raise a ticket?
3. For the age ratio, if the user uses aggregation layer, will it use the one from aggregation layer or from IF? (I just tried it, it will use the one from aggregation layer, makes sense)

I know that as the developer we know how inasafe will work, and we probably want to drive the user how they should use inasafe, but for the user this could make confusion. You see that even I need to try it first which one that inasafe will use."

**Comment by timlinux** [comment]
​Yes this is a bit complicated. I think one thing we should look at is conveying to the user the context that will be used for their analysis e.g.:

"For this analysis:

* age ratio from the aggregation layer attribute 'age' will be used by first preference
* age ratio from the aggregation layer keywords (currently set to 0.5) will be used by second preference
* ​age ration from InaSAFE global defaults will not be used since a default was defined in the aggregation keywords"

I can't think of a sensible use case for defining age, gender rations as IF parameters, we should remove them from there - or correct me if I am wrong?

**Comment by timlinux** [comment]
@Gustry Can you take note of the comments here? Lets close this out when you have finished your ratios work for 4.0

**Comment by timlinux** [comment]
Closed for 4.0
