### ISSUE TITLE
RFC: We need to develop a data model for inaSAFE

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#1624]
# Problem
we need to clearly document what data can be used in InaSAFE.

* At present it is possible for users to load data representing hazard zones (polygons or rasters) and run analyses using classified or generic impact functions; yet the results are presented as if the data represent a single scenario. #1595
* this is misleading, potentially confusing and defies the stated intention of InaSAFE in its current guise ....
* these data are better suited to 'risk assessment' but none of the IF or post processing is 'risk assessment' centric {that is not what InaSAFE is meant to be doing - its OK}

# proposed solution
- [ ] the current data model be documented: data types, units, definitions
- [ ] appropriate uses be identified and documented for different data types
- [ ] terminology be reviewed to ensure it is logical and relevant to all users
- [ ] the data model be used in the review of IF - March
- [ ] the data model be used to help with metadata
- [ ] the data model be the first part of a 'process diagram' for InaSAFE

# implications
- [ ] the review of IF will need to be followed by a revamp of post processing and reporting
- [ ] the data model will help developers to better understand what should and should not be allowed in IF, postprocessing and reporting

# cc
@timlinux @assefay @maning @iyan31 @fredychandra  @adissadis @akbargumbira @ismailsunni @borysiasty @mbernasocchi

**Comment by Charlotte-Morgan** [comment]
So finally; here is my picture of the current data model:
![image](https://cloud.githubusercontent.com/assets/5743135/6318623/362da3ca-bace-11e4-96bf-72c8bc729319.png)

I think there are 2 different types of hazard data that we are now working with since we introduced the categorical IF. But the metadata treats all hazard data as the same. Is there a need to introduce a new tier to the metadata terminology??

I hope this diagram helps developers when they work on IF and will also allow us to target our test data.

@timlinux @maning @ismailsunni @akbargumbira @assefay @mbernasocchi

**Comment by timlinux** [comment]
Hi @charlotte

I like this thinking very much. Just one query - shouldn't we have risk maps for flooding too - I bet you will find that it is the same areas that get regularly flooded in a particular region? I could also envisage e.g. using MODIS AQUA products to build a flood exposure over time dataset.

I also wanted to mention that there is already https://github.com/AIFDR/inasafe/wiki/Data-Types which could be updated to your more refined scheme above.

What are the practical end-user implications of this proposed change? My thoughts are:

* User will need to indicate in keywords whether hazard data represents a single event of an aggregation of events
* In wizard user should start by choosing whether they want to do an analysis for a single event or an aggregate risk model
* Reporting will be more nuanced, with different wording for single events than for risk models. E.g. for risk it might say 'This report represents the **modelled** risk of impact per pixel based on the 2006 tsunami' in contrast for measured hazard it might say 'This report represents a **scenario** of risk of impact based on the a flood like the one in Jakarta in 2013. I am sure I have not pegged the wording correctly, but is that your general intent?

In terms of fitting in with a generic 'core' impact function that does a class based impact analysis (unless the IF writer specifically overloads that behaviour) I think that concept is still consistent with your proposed data model above.

**Comment by Charlotte-Morgan** [comment]
hi @timlinux 
I think you understand. :) 
I have tried to document what we do currently, not what we might do in future. So flood hazard maps are a likely addition.
I should take a look at the wiki too ...

Impact on developers:
According to definitions.py we have:
- [ ] categories
- [ ] sub categories
- [ ] units

And in the units we have:
- [ ] unit_continuous
- [ ] unit_classified

The above model takes these two 'units' much higher up the structure. Its the impact on definitions.py that i wanted to chat to @ismailsunni et al about because this will impact on all IF, wizards etc

Impact on end users:
- [ ] an extra choice early in a wizard
- [ ] different key words (scenario vs risk map) that will limit available impact functions
- [ ] different reporting as in words & actions based on different user purposes ...

**Comment by timlinux** [comment]
@Charlotte-Morgan Ok thanks for the clarifications. Is it a truism that ``unit_classified`` is always 'Risk'?  I could unit_classified not also be for a single event e.g. preclassified flood depth?

Maybe it would be better not to overload the ``unit_*`` keyword too much and rather introduce a new keyword: ``hazard_context`` (again feel free to think of a better term):

```python
hazard_context = {
    'risk': 'A modelled dataset that represents the result of an analysis (rather than simple observation) for an area in order to postulate what the risk class is for any given place in that area. For example, a model of a past tsunami event might be generated and then classified to produce a raster surface representing low, medium or high risk should a similar event occur again in the future.',
   'observation': 'An GIS data layer that represents and observation / snapshot of the on-the ground situation e.g. current flood status as 9am for Jakarta.' }
```

I must say the more I think about it though, the fuzzier the concepts become for me. e.g.

* is a map of the areas that were flooded in the last 24 hours in Jakarta a risk map or an observation map? Common sense says the latter, but it is an also an aggregation of multiple reports over a time window rather than a single snapshot in time.
* If the user wants to deal with pre-classified data does that automatically make it 'risk'? The classes may represent the state on the ground for a single snapshot in time.

**Comment by Charlotte-Morgan** [comment]
no - keep it simple. 
1. does the data represent a single scenario or probabilistic hazard
2. single scenario step to the left
3. probabilistic step to the right

**Comment by timlinux** [comment]
Hehe ok - I like simple.

**Comment by Charlotte-Morgan** [comment]
in my simple mind
single scenario is suitable for contingency planning - traditional InaSAFE
probabilistic models are for risk assessment - breaking new ground (accidentally)

**Comment by Charlotte-Morgan** [comment]
As discussed during site visit - March 2015. Updated data model diagram.
![image](https://cloud.githubusercontent.com/assets/5743135/6437326/0bece044-c0f0-11e4-9b36-f9aeb968a13e.png)

**Comment by timlinux** [comment]
Note that the single event / mulitple events were removed in the IF centric wizard.

We need to work through this and see what still needs to be done - some parts of this data model are already supported so we need to check what the next actions are...

**Comment by Charlotte-Morgan** [comment]
Hi @easmetz - this is the datamodel conversation. This needs to get moved to a wiki page :)

**Comment by timlinux** [comment]
I'm going to close this as I think we have pretty much covered the concept now.
