### ISSUE TITLE
Rule based symbology

### ISSUE THREAD

**Issue by uniomni** [inasafe/inasafe#164]
Impact layers are currently only rendered with categorised colour symbologies. 
With e.g. multiple building usage types it will be necessary to symbolize them with rules according to damage level and usage type.

We envision augmenting the current style_info datastructure to accommodate clauses such as  
(type ILIKE 'masjid' OR type ILIKE 'mosque' OR type ILIKE 'place_of_worship') AND (Affected = 0)

Also, InaSAFE should maintain a library of symbols (and possibly styles) that  can be accessed by name.

**Comment by timlinux** [comment]
I think a better approach is to transfer the style from the exposure layer to the impact layer, and then augment it - e.g. adding an overlay / underlay which indicates if a road or building is affected.

**Comment by timlinux** [comment]
Additional note - my comment above is because we wish to remove / avoid any hard coding of attribute names in InaSAFE.

**Comment by timlinux** [comment]
I'm closing this. Symbology rules are defined in docs/standards.md  - see also #2828
