### ISSUE TITLE
Pending French translations

### ISSUE THREAD

**Issue by severinmenard** [inasafe/inasafe#1681]
I translated 2 pages in the documentation, can one of the admins validate them?

PS: I never know what is the right process to get the translation approved/appearing on the website. Is it better to add an issue? On another projects for which I volunteer, it took more than one month for the translation to appear on the website.

PS2: there should be a new French translator asking the permission to join the team soon (if not done already)

**Comment by mach0** [comment]
I tested the compile on test.inasafe.org ..
Could you take a look there if everything is ok?

**Comment by severinmenard** [comment]
http://test.inasafe.org/fr/training/beginner/qgis-inasafe/201-gis-for-developing-contingency-plan.html
should be completely translated

Everything is reviewed there:
https://www.transifex.com/projects/p/inasafe/translate/#fr/training-201-gis-for-developing-contingency-plan/18625231

**Comment by timlinux** [comment]
# CC

@Gustry

**Comment by timlinux** [comment]
I'm going to close this out as it is old. @Gustry is taking care of translations for French.
