### ISSUE TITLE
Impact function options dialog update

### ISSUE THREAD

**Issue by Jannes123** [inasafe/inasafe#1689]
Update tabs to use new style params
related sub tickets:
#1762

**Comment by cchristelis** [comment]
When looking at #1727, it became apparent, that we need to let the user select which parameter to use in the "flood_vector_OSM_building_impact" impact function. Using 'affected', 'FLOODPRONE' and 'inapolygon' as defaults where appropriate. This should be a drop down based on available features in the vector hazard layer.

**Comment by akbargumbira** [comment]
Yes, we already changed the IF to just look to an attribute specified in the parameter. See here https://github.com/AIFDR/inasafe/pull/1756/files#diff-d6fafa648ce30302acd36c02ba071de9R168, but it's still using the old parameter style

**Comment by cchristelis** [comment]
@akbargumbira +1, that looks good.

**Comment by timlinux** [comment]
This is no longer relevant - impact function options dialog is gone in 4.0
