### ISSUE TITLE
We need an infographic report template

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#1775]
# Problem

We need a snazzy looking infographic report from InaSAFE. This was a suggestion raised at the September 2014 workshop held in Jakarta. Here is the original (slightly ironic) mockup made by @ingenieroariel at the workshop:

![selection_002](https://cloud.githubusercontent.com/assets/178003/7001719/f6d7ec16-dc3e-11e4-9c8b-a2395c5d5f84.png)

I would very much like to see that it looks in some way like a version of the InaSAFE 'postcard' shown below.

![selection_001](https://cloud.githubusercontent.com/assets/178003/7001647/c4a15382-dc3d-11e4-9306-22b8b79274d7.png)

Postcard original sources are here: https://github.com/AIFDR/inasafe-graphics/tree/master/inasafe-postcard
# Proposed solution

@borysiasty @MariaSolovyeva and Iyan to work together to finalised the proposed layout and implement it as a QGIS composer template. 
# See also

Fledgling ticket here: https://github.com/AIFDR/inasafe/issues/1218

**Comment by Charlotte-Morgan** [comment]
hi @timlinux @borysiasty @MariaSolovyeva 
I fully support the idea of introducing infographics to the InaSAFE reports. I believe @samnawi (Iwan - the new GIS Officer at AIFDR) has some experience with infographics from a previous project with BNPB and UN. Iwan will also pickup some ticket for map templates #1314 and report templates.
 @samnawi - please comment on this ticket and post a picture if you have any immediate ideas for presenting the existing InaSAFE reports details graphically.

**Comment by samnawi** [comment]
I think is good idea to make a report from InaSAFE using infographics, because in infograhics, beside there is information about map, also we can add the other related information. So, it's more efficient to explain to user / decision maker. In my previous project in BNPB, based on our experience, when we just use a map, some user still have some question, because not all of user is familiar to read a map. Then we try to add more information on the map, until we find the infographics to be one of the BNPB (Pusdatinmas) product.

This is some infographic that ever made by BNPB
Infographics on monthly report (Februari 2015)
![screenshot from 2015-04-07 10 22 31](https://cloud.githubusercontent.com/assets/8871958/7016672/ac7cf94c-dd13-11e4-82c1-ea4493e50707.png)

Infographics for Situational Report at Indramayu Flood
![20150317_kejadianbanjirindramayu-01](https://cloud.githubusercontent.com/assets/8871958/7016681/c89dd0d8-dd13-11e4-917d-8d2aa78fc812.jpg)

Beside that, BNPB also have a project with UN to made a Provincial Infographics book (this Infographics is uploded in BNPB website, but i think the link is broken)

**Comment by maning** [comment]
The above samples by @samnawi looks really nice.  I don't know how this can be automated in QGIS composer though.  But there are some ideas over the QGIS mailinglist of using [D3 + python bridges to interact with qgis/qt map composer](http://osdir.com/ml/qgis-user-gis/2014-10/msg00292.html)

**Comment by akbargumbira** [comment]
Yeah, as map composer already has HTML frame, I think it's possible to draw maps and its statistic just by using HTML frame on map composer using D3. This is a bit ironic though, perhaps there is some way to interact with layers loaded in QGIS

**Comment by timlinux** [comment]
Hi

@samnawi Oh yeah! Those look awesome!

@maning Yes as @akbargumbira mentioned we can probably cheat by using an HTML widget. We could also get @wonder-sk to look at the possibility of adding chart widgets to the core of QGIS composer (much nicer route IMHO). The concept could be:

* add a widget to the map layout
* in widget properties specify chart type (pie / bar) & colours (nice to use QGIS symbol for fills and styling)
* in the properties select a layer/table layer from the composition that the chart should be generated for OR enter data using a simple table widget OR enter a path to a delimited text file to use for the chart.
* provide an API in python for doing the same
* provide for token replacement system so that the  delimited file path / data table / attribute table mappings can be set by normal template token replacement

@wonder-sk what do you think? Too much work and better to use an html embed, or something you can manage?

**Comment by Charlotte-Morgan** [comment]
Action:
- [ ] @samnawi to design
- [ ] discuss requirements with @charlotte
- [ ] work out what is already possible in QGIS
- [ ] talk to @martin about what we really need in QGIS
- [ ]  @borys to implement
- [ ] happy users

**Comment by wonder-sk** [comment]
Support for charts in QGIS has been on my list for quite some time - it would be great to have that in the core.

I have some concerns regarding HTML frame + D3 (or some other javascript chart library). Not only things get more complicated to set up, but there may be some hidden issues. Just recently I have seen a case of D3-based charts in composer. It somehow worked... unless you wanted to print it in atlas mode. The javascript code is run asynchronously and at the time the composer was printed to PDF, the javascript code may not have finished running, resulting in partial or missing charts.

My suggestion would be to introduce native support for charts in QGIS, so charts could be:
- rendered to an image with API
- used in composer
- displayed in GUI, allowing user interaction

The chart functionality could be built on top of an existing engine for drawing charts, I think there is no need to create yet another charting library. It could use either C++ library like Qwt or even non-C++ engine like PyQtGraph (where we would provide some C++ wrappers).

**Comment by Charlotte-Morgan** [comment]
Hi @wonder-sk  & @Gustry - I saw the work you have done on the graph results for landcover and decided that we need to tweak it a bit more before including it in a release.
Can you please point me to where this work is so that the team can review further and provide more input.

**Comment by Gustry** [comment]
Hi @Charlotte-Morgan. The graph has been disabled in the code.
The final preview was : 
![Report](https://cloud.githubusercontent.com/assets/193367/14425050/ad1f58c6-000e-11e6-8140-f6bd968e07d9.png)

**Comment by timlinux** [comment]
In my last conversation with @Charlotte-Morgan , she wanted to report on percentages, not absolute values. This makes sense to me and we could look at how to convey that visually in a nice way.

**Comment by timlinux** [comment]
I hope we can hack on this in our next site visit in Jakarta.

**Comment by Charlotte-Morgan** [comment]
Hi @felix-yew - this ticket has been waiting for you :) 
@samnawi - I will take you off this one

**Comment by Charlotte-Morgan** [comment]
@felix-yew - I think this is done ? You can comment and close if you like.

**Comment by felix-yew** [comment]
Thank you
