### ISSUE TITLE
New IFs: EQ polygon impacts

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#1798]
# problem

We have acquired some official EQ polygon hazard data from Badan Geologi and would like to use these data in risk assessment work next week.
# proposed solution

use the existing Volcano polygon IF to create new EQ IF for EQ hazard zones. Exposure data will be population raster and OSM buildings.
# known issues

this is a short term solution to an immediate opportunity to deliver science in a relevant way to the community & will be superseded by a generic polygon IF in 3.2
# cc

@timlinux @ismailsunni @fredychandra @samnawi

**Comment by Charlotte-Morgan** [comment]
Hi @akbargumbira - I just discussed this with @timlinux & we agreed that it could be better to make this a generic polygon IF for impact on buildings and population so that users can use it for any hazard zone map, they would just need to specify the field and attributes

**Comment by akbargumbira** [comment]
@Charlotte-Morgan no problem

**Comment by timlinux** [comment]
I think we can close this - as it is handled in 4.0
