### ISSUE TITLE
We need to fix tif uploading for InaSAFE geonode

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#1812]
# Problem

Currently you cannot upload tifs to the GeoNode running on http://geonode.insafe.org

![screen shot 2015-04-17 at 10 17 59](https://cloud.githubusercontent.com/assets/178003/7198289/11b55aa0-e4eb-11e4-8f44-2c13f07b86a6.png)
# CC

@ingenieroariel

**Comment by NyakudyaA** [comment]
We can close this. Raster layers can be uploaded to geonode
