### ISSUE TITLE
We need to fix invite user functionality in GeoNode

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#1813]
# Problem

When I try to invite a user (in this case Charlotte), I get this:

![screen shot 2015-04-17 at 10 20 27](https://cloud.githubusercontent.com/assets/178003/7198321/68aaea96-e4eb-11e4-8d58-8463743d8caa.png)

I was trying to use this url:

http://geonode.inasafe.org/account/invite_user/

**Comment by NyakudyaA** [comment]
Is this still a valid case?

**Comment by Gustry** [comment]
We can't replicate anymore. We reinstalled geonode
