### ISSUE TITLE
RFC: ParamaterManager for parameter rework

### ISSUE THREAD

**Issue by Jannes123** [inasafe/inasafe#1816]
## Problem

Managing parameter creation and default value creation.  This will basically form the back end of parameter widgets.
## Proposed Solution

Implementing a Parameter Manager which :
1. Will be created on IF selection when an IF is selected from the registry when the IF is initialized.
2. Can query layers and get keyword names and available values.  These will be made available to the user and then the IF.
3. Can do validation based on parameter grouping.
4. Parameters can be frozen/serialized (JSON) and saved for consolidating the saving of projects.
## Diagram

https://www.lucidchart.com/documents/edit/04edb558-2a2d-4853-af3b-a58ade41e8e0
## CC

@timlinux
@cchristelis  
@lucernae
@Charlotte-Morgan
@akbargumbira
@ismailsunni 

This issues touches on #1785

**Comment by timlinux** [comment]
Closing this as we have a different implementation in InaSAFE 4.0
