### ISSUE TITLE
[Bug] Different result for general result with detailed result

### ISSUE THREAD

**Issue by adissadis** [inasafe/inasafe#1824]
# Problem
I run impact analysis for building OSM, using flood HKV raster hazard data and aggregate it with Jakarta Boundary. I notice that in the general result of **Total Building Affected is 2.914** 
![inasafe_10](https://cloud.githubusercontent.com/assets/2520159/7226593/493661f0-e774-11e4-9736-789bfeb668fb.png)

but in the detailed Building type report is very different, it said **5.053 building inundated**. 
![inasafe_11](https://cloud.githubusercontent.com/assets/2520159/7226597/52dfa4b4-e774-11e4-920a-12da46db384e.png)

It should have the same number between general report and detailed report.

# Question
1. Why there are 2.139 number of building inundated added to detailed report?
2. What is the cause of ***No Data*** value for detailed building result? Because from the number inundated building by type it already reported how many hospital, place of worship, school etc that inundated.

**Comment by Charlotte-Morgan** [comment]
@samnawi - please see if you get this too

**Comment by timlinux** [comment]
We tested it with the test dataset and the numbers are consistent now. Please reopen this issue if you do not agree.

![screen shot 2016-06-22 at 14 19 26](https://cloud.githubusercontent.com/assets/178003/16266350/b5ef3454-3884-11e6-8d8b-bca2053b1982.png)
