### ISSUE TITLE
We need standardised impact function documentation

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#186]
For each specific function we need to document standard information:
- What formats are supported (raster / vector)
- For vector what attributes are mandatory
- For vector what attributes are optional
- For vector what geometry type(s) are required
- For vector are there any other constraints e.g. topology, indexing etc.
- For raster what is the ideal resolution (if any)
- For raster what types are supported (float / int)
- For raster data how many bands are required
- For raster data is it allowed to be rescaled / resampled (e.g. pop data)
- Are there any constraints on the CRS that can be used for the dataset

This list is a brain dump from a conversation with Liana at the UR conference, and should be used to inform how we approach the creation of standardised impact function for InaSAFE.

Additional feedback from the UR2012 conference:
- The impact functions should provide details of how the function works (e.g. forumula, assumptions etc) which should be provided as part of the report - to limit the 'black box' feeling of the software.

**Comment by Charlotte-Morgan** [comment]
@easmetz - FYI

**Comment by timlinux** [comment]
Happy to say that with Version 4.0 these considerations will all be moot since we work with pretty much every permutation. I think it would be good to have more hazard specific documentation on the methodologies used but I think that is a topic for a new ticket. Closing this off for now. See also #3548
