### ISSUE TITLE
Metadata Definitions: we need to consult the 'old timers'

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#1869]
# problem
We are moving from old style to new style impact functions with associated changes to metadata and terminology. There is a risk that as terminology is standardized and IF are re written, some of the original intent may be lost.
We need to check with the 'old timers' to make sure none of the original intent is lost in the transition.

# proposed solution
can anyone please explain:
- [ ] difference between 'impacted', 'affected', 'evacuated', 'die or be displaced'
- [ ] 1 % rule - why is this value used for Jakarta flood evacuation 
- [x] where did the youth: adult : elderly ratios come from; ie  26:66:8

# cc
calling all the InaSAFE experts
@vanpuk @uniomni @ingenieroariel @vdeparday @timlinux @assefay @ismailsunni @akbargumbira @kathrynowen

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
From the 3rd point, the ratios come from this comment in the code. It was @mbernasocchi 's research.

# https://www.cia.gov/library/publications/the-world-factbook/geos/xx.html
# Age structure:
# 0-14 years: 26.3% (male 944,987,919/female 884,268,378)
# 15-64 years: 65.9% (male 2,234,860,865/female 2,187,838,153)
# 65 years and over: 7.9% (male 227,164,176/female 289,048,221) (2011 est.)

**Comment by Charlotte-Morgan** [comment]
the team at AIFDR will review this & write definitions for the first point & or change the words in the IF

**Comment by Charlotte-Morgan** [comment]
Hi @vanpuk - we are putting the finishing touches on InaSAFE 3.2 and would love to be able to add some explanation for why we use 1% as the default evacuation percentage for flood polygons. Can you recall why this value is used?

**Comment by timlinux** [comment]
Maybe I will try to skype @vanpuk and see if I can get this info from her so that we can close this ticket....

**Comment by Charlotte-Morgan** [comment]
Update: we need this info to support the new real-time flood work for this season in Jakarta. I sent an email to the likely experts - fingers crossed someone can shed some light on this soon.

**Comment by mbernasocchi** [comment]
@Charlotte-Morgan the age structure is documented here: https://github.com/AIFDR/inasafe/blob/develop/safe/defaults.py#L54

**Comment by Charlotte-Morgan** [comment]
Hey @mbernasocci thanks for the link. We have the source of the age structure covered, its just the 1% evacuation threshold we are chasing now.

**Comment by mbernasocchi** [comment]
mmm can you point me to the usage? Doesn't ring any bells in my head

**Comment by Charlotte-Morgan** [comment]
1% evacuation threshold is used for flood impact on population where flood is vector data. The default value is 1% but users can change this threshold.  This value is used to then calculate the minimum needs.  We are trying to understand the basis for the 1% default.

**Comment by mbernasocchi** [comment]
@ismailsunni added this:
https://github.com/AIFDR/inasafe/commit/3c8aecd0edf6c79f69ae3d5ce5683b91a691ea17

**Comment by vanpuk** [comment]
Hi All,
Apologies for coming late to this discussion. Yes there was a reason we picked 1% but its not a very good one. Basically we were trying to match the evacuation numbers of the 2013 floods using the 2013 flooded RW boundaries.  What we found was mathematically only 1% of the "affected population" were evacuated. Using the maps that Emir produced in that first year of floods.  I could try and find in google docs if you wish.

**Comment by Charlotte-Morgan** [comment]
Thanks Kristy, that would be great if you can. Emir is visiting this week, I might ask him too.

Charlotte Morgan
Spatial Data Analyst
DMInnovation - Jakarta
GEOSCIENCE AUSTRALIA

Mobile: +62 811 820 4648

On 10 Nov 2015, at 6:20 pm, Kristy Van Putten <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi All,
Apologies for coming late to this discussion. Yes there was a reason we picked 1% but its not a very good one. Basically we were trying to match the evacuation numbers of the 2013 floods using the 2013 flooded RW boundaries. What we found was mathematically only 1% of the "affected population" were evacuated. Using the maps that Emir produced in that first year of floods. I could try and find in google docs if you wish.

-
Reply to this email directly or view it on GitHub<https://github.com/AIFDR/inasafe/issues/1869#issuecomment-155393405>.

Geoscience Australia Disclaimer: This e-mail (and files transmitted with it) is intended only for the person or entity to which it is addressed. If you are not the intended recipient, then you have received this e-mail by mistake and any use, dissemination, forwarding, printing or copying of this e-mail and its file attachments is prohibited. The security of emails transmitted cannot be guaranteed; by forwarding or replying to this email, you acknowledge and accept these risks.
-------------------------------------------------------------------------------------------------------------------------

**Comment by ismailsunni** [comment]
Hi @mbernasocchi 

That's me, but it's not the origin of it. We made a big refactor on InaSAFE, so may be the history is re-written. The commit is submitted on 27 Jan 2015. Meanwhile, the 1% has been already in InaSAFE since 2012 or 2013.

Hi @vanpuk 
Long time no see.
It rings a bell. I think that's the reason why we choose 1%.

**Comment by timlinux** [comment]
I think we can close this out. In the future we could look at supporting variable evacuation rates per administrative area, but lets open a separate ticket for that.
