### ISSUE TITLE
We need to update documentation that references which IF's we have

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#1890]
Here are my notes for 3.1 release planning regarding what the state of play is pre 3.1 and as at 3.1:

Please note that as of 3.1 we do not yet have the intermediate base classes (shown as the second column in each image). I have left them in the diagram as they are useful to illustrate which types of input data can be used with each IF.
# Earthquake

![inasafe_impact_function_class_heirarchy_earthquake - impactfunctionbaseclasses](https://cloud.githubusercontent.com/assets/178003/7428609/ce1c5672-eff3-11e4-9c58-777feb4f7ecb.png)

(Unchanged in 3.1) Naming changes not shown here
# Generic

![inasafe_impact_function_class_heirarchy_generic - impactfunctionbaseclasses 3](https://cloud.githubusercontent.com/assets/178003/7429096/d515ac00-effb-11e4-9931-83633e52dab2.png)
# Inundation

In version 3.0 we have this:

![inasafe_impact_function_class_heirarchy_inundation - impactfunctionbaseclasses](https://cloud.githubusercontent.com/assets/178003/7429301/8233a394-efff-11e4-9372-b2bcfd00ba3e.png)

In 3.1 the same impact functions are available, though the naming has been changed:

![inasafe_impact_function_class_heirarchy_inundation - impactfunctionbaseclasses 1](https://cloud.githubusercontent.com/assets/178003/7429393/c1ee44e8-f000-11e4-83aa-dd48b327de07.png)
# Volcano

![inasafe_impact_function_class_heirarchy_volcanic - impactfunctionbaseclasses 1](https://cloud.githubusercontent.com/assets/178003/7429426/449f243e-f001-11e4-9800-73313d328c40.png)

(Unchanged in 3.1)  Naming changes not shown here

**Comment by timlinux** [comment]
@iyan31 Can you check if there are lists of IF's in the HOT documentation work, and update the list. @lucernae can you update the list above and make sure it is correct?

**Comment by iyan31** [comment]
Will check with the team

**Comment by timlinux** [comment]
Moving this back to the backlog. iyan31 can you update this ticket with current status? Note that since the above diagram were made we have added new IF's so we need to update it.

**Comment by adissadis** [comment]
Hi @timlinux currently we don't put any diagram about list of impact function in our training material (QGIS training material). So, i think its safe for update it.

cc @iyan31

**Comment by timlinux** [comment]
Closing this as we have a different implementation in InaSAFE 4.0
