### ISSUE TITLE
Have "make test" output more descriptive

### ISSUE THREAD

**Issue by uniomni** [inasafe/inasafe#190]
As we link the output of make test more and moreclosely to the release requirements, it'd be good for it to produce 
output that can be cut and pasted directly into the release form for signatures.

I propose a simple change so that results that pass and currently produce no output (the UNIX way) instead put the word None. Is there some magic awk command that can do this?

For example the current output

<pre>
-------------------------------------------------------------------------------------------
TOTAL                                                          4976    885    82%   
----------------------------------------------------------------------
Ran 217 tests in 320.510s

OK

-----------
PEP8 issues
-----------

------------------------------------------------
List of unwanted dependencies in InaSAFE library
------------------------------------------------

------------------------------
Strings that should be deleted
------------------------------

---------------------------------------
Audit of IP status for bundled data    
---------------------------------------

----------------------------------------------------------------
Missing translations - for more info run: make translation-stats
----------------------------------------------------------------
</pre>

Should be replaced by

<pre>

                                                              Stmts   Miss   Cover
--------------------------------------------------------------------------------
TOTAL                                                          4976    885    82%   
--------------------------------------------------------------------------------
Ran 217 tests in 320.510s

OK

-----------
PEP8 issues
-----------
None

------------------------------------------------
List of unwanted dependencies in InaSAFE library
------------------------------------------------
None

------------------------------
Strings that should be deleted
------------------------------
None

---------------------------------------
Audit of IP status for bundled data    
---------------------------------------
None

----------------------------------------------------------------
Missing translations - for more info run: make translation-stats
----------------------------------------------------------------
None

</pre>

**Comment by timlinux** [comment]
I'm closing this. I dont think it is good to invest any more time in it right now since we have moved on to Travis CI, Landscape and friends.
