### ISSUE TITLE
Review Raster on Vector Interpolation based on September workshop discussion

### ISSUE THREAD

**Issue by akbargumbira** [inasafe/inasafe#1917]
# Problem

With the current implementation, we get the interpolated values from the neighbours to the centroid of the vector. We discussed a bit about this and the intention is that we want to set the vector (not making it centroid) to the worst value of the grids that lie in that vector

**Comment by akbargumbira** [comment]
cc @cchristelis as it's also related to NaN

**Comment by timlinux** [comment]
The building should be assigned to the highest value of any intersecting pixels - so for example if a building is near a flood and it touches one deep water cell it should be considered flooded.

One approach would be to classify the flood into high/med/low and then assign the building to highest class it touches.

**Comment by timlinux** [comment]
@cchristelis please give an estimate on how much work will be involved

**Comment by timlinux** [comment]
This is moved to 3.6 - we will follow the principle of 'most exposed part of polygon applies to the whole polygon'.

**Comment by Gustry** [comment]
This is now done in 4.0. We assign the highest hazard class to buildings.
