### ISSUE TITLE
LayerParameter Classes

### ISSUE THREAD

**Issue by Jannes123** [inasafe/inasafe#1942]
Options should present user with loaded layers and allow him to select

**Comment by Jannes123** [comment]
Helper functions for:

* Name
* Type (rast/vect)
* Filename

**Comment by ismailsunni** [comment]
Does anyone remember the context of this issue?
It seems not clear and I can't find any LayerParameter in InaSAFE's code. I will close this and if anyone think it's still valid, I am open to reopen this ticket. :)
