### ISSUE TITLE
QGIS crash after InaSAFE analysis

### ISSUE THREAD

**Issue by vdeparday** [inasafe/inasafe#1952]
On QGIS 2.8.2-1 and InaSAFE 3.1 experimental on Windows, QGIS totally crashed after running an analyis.
The output layer gets added to the workspace but one second later a pop window says 

qgis-bin.exe has stopped working or something along those lines

QGIS closes.

**Comment by NyakudyaA** [comment]
Is this still the case.  We need to test with current LTR of QGIS

**Comment by timlinux** [comment]
I think we can close this out - I have not seen reports like this recently.
