### ISSUE TITLE
The plugin exited with error status: 1

### ISSUE THREAD

**Issue by haytastan** [inasafe/inasafe#1964]
I use QGIS 2.8 Wien. I haven't able to load InaSAFE v3.1.0 and got the error message:
The plugin exited with error status: 1
![error_message_inasafe-v3 1 0](https://cloud.githubusercontent.com/assets/7123870/7862229/3f2c042e-055d-11e5-9280-d4e0938418f6.jpg)

I need help.
Best regards,
Dr.Hayati Taştan
haytastan@gmail.com

**Comment by akbargumbira** [comment]
Hi, can you explain more about the crash?
- When you said it crashes when you load the plugin, is it when you install it? or when you enable it (checking the checkbox)?
- What kind of windows are you on? 32bit or 64?

Thanks

**Comment by timlinux** [comment]
I also tested here on Win8 64 bit and previously on Win 7 64 bit and it is working fine for me.

@haytastan could you perhaps also tell us which other plugins you have installed? It might help to diagnose the issue - and also perhaps try setting your locale in QGIS manually to English and see if that makes any difference?

**Comment by haytastan** [comment]
Dear Akbargumbira and Dear timlinux,

I have been using windows-7 64bit. I got the following phyton error when I install it:
Best regards,

Dr. Hayati Tastan

---------------------------------------------------------------

inasafe plugin has not been installed due to an error when calling its classFactory() method

Traceback (most recent call last):
  File "C:/PROGRA~1/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/hayati.tastan/.qgis2/python/plugins\inasafe\__init__.py", line 86, in classFactory
    from safe.plugin import Plugin
  File "C:/PROGRA~1/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/hayati.tastan/.qgis2/python/plugins\inasafe\safe\plugin.py", line 44, in 
    from safe.utilities.keyword_io import KeywordIO
  File "C:/PROGRA~1/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/hayati.tastan/.qgis2/python/plugins\inasafe\safe\utilities\keyword_io.py", line 32, in 
    from safe.utilities.utilities import (
  File "C:/PROGRA~1/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/hayati.tastan/.qgis2/python/plugins\inasafe\safe\utilities\utilities.py", line 30, in 
    from safe.storage.utilities import read_keywords
  File "C:/PROGRA~1/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/hayati.tastan/.qgis2/python/plugins\inasafe\safe\storage\utilities.py", line 10, in 
    from ast import literal_eval
  File "C:/PROGRA~1/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PCI Geomatics\Geomatica 2014\Examples\python\ast.py", line 1, in 
    from pci.ast import ast
  File "C:/PROGRA~1/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PCI Geomatics\Geomatica 2014\exe\pci\__init__.py", line 51, in 
    sys.exit(1)
SystemExit: 1


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS Version:
2.8.2-Wien Wien, 1b929ef

Python dizini: ['C:/PROGRA~1/QGISWI~1/apps/qgis/./python', u'C:/Users/hayati.tastan/.qgis2/python', u'C:/Users/hayati.tastan/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\bin\\python27.zip', 'C:\\PCI Geomatics\\Geomatica 2014\\Examples\\python', 'C:\\PCI Geomatics\\Geomatica 2014\\exe', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1\\bin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/hayati.tastan/.qgis2//python', 'C:/eclipse/plugins/org.python.pydev_4.0.0.201504132356/pysrc', 'C:/eclipse/plugins/org.python.pydev_3.6.0.201406232321/pysrc', 'C:/Users/hayati.tastan/.qgis2/python/plugins\\inasafe', 'C:\\Users\\hayati.tastan\\.qgis2\\python\\plugins\\inasafe\\safe_extras\\parameters', 'C:\\Users\\hayati.tastan\\.qgis2\\python\\plugins', 'C:\\Users\\hayati.tastan\\.qgis2\\python\\plugins\\inasafe\\safe_extras']

**Comment by timlinux** [comment]
Hi. Sorry for the really long delay in replying here. Do you still have this issue with the latest released InaSAFE? I'm going to close out this issue, please re-open if you are still having the issue and we will investigate further.

Regards

Tim
