### ISSUE TITLE
Use Python's locale module instead of os.environ['LANG']

### ISSUE THREAD

**Issue by ingenieroariel** [inasafe/inasafe#198]
The current locale handling causes a failed test in OSX, here is some debugging information from the shell:

```
>>> import locale
>>> locale.getdefaultlocale()
('en_US', 'UTF8')
>>> os.environ['LANG'] = 'id'
>>> locale.getdefaultlocale()
('en_US', 'UTF8')
>>> os.environ['LC_ALL'] = 'in_ID.UTF-8'
>>> locale.getdefaultlocale()
('id_ID', 'UTF8')
```

http://docs.python.org/library/locale.html#locale.getdefaultlocale

Proposed implementation:

```
def ugettext(s):
    """Translation support
    """
    path = os.path.abspath(os.path.join(os.path.dirname(__file__),
                                        '..', 'i18n'))
    lang, encoding = locale.getdefaultlocale()
    filename_prefix = 'inasafe'
    t = gettext.translation(filename_prefix,
                            path, languages=[lang], fallback=True)
    return t.ugettext(s)
```

**Comment by akbargumbira** [comment]
IMO, we should treat QGIS as our proxy. If we can get settings from QGIS, get it first from there i.e get the locale like settings.value('locale/userLocale'). And also no need to change os.environ['LANG'] on the tests, this is not convenient. We should not pollute user's computer just by running InaSAFE tests

**Comment by timlinux** [comment]
Closing this as old - translations are working well under our current system
