### ISSUE TITLE
Provenance is not displayed in some of the IFs analysis report

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#1980]
When developing issue #1958, I noticed several concerns:

The provenance is not displayed in some of the IF or not consistent:
- classified polygon population (uses minimum needs, but not displaying provenance)
- flood raster population (uses minimum needs, but hard coded provenance in the report to show BNPB regulation)
- continuous hazard population (uses minimum needs, but not displaying provenance)
- itb fatality and pager (uses minimum needs, and displaying provenance under **provenance's** section)
- flood polygon population (uses minimum needs, and displaying provenance under **notes'** section)
- volcano polygon population (uses minimum needs, but not displaying provenance)
- volcano point population (uses minimum needs, but not displaying provenance)

What to do about this @akbargumbira ?
Should we leave standardized it to display provenance under the provenance's section?

**Comment by akbargumbira** [comment]
Thanks for pointing this. I believe @cchristelis is working on this with
the Population Exposure Mixin. And just a note that the provenance
shouldn't be hardcoded, but rather take it from the runtime provenance in
parameter.

**Comment by timlinux** [comment]
This is old and superceded by the v4 architecture. Closing.
