### ISSUE TITLE
Standardize Building Type Parameter

### ISSUE THREAD

**Issue by akbargumbira** [inasafe/inasafe#1990]
# Problem
All our IF's on building need a standardize way to get the building type.

# Proposed Solution
1. Remove all parameter in IF option related to building type field
2. Get the building type field from layer keywords
3. As a fallback, don't stop the analysis if the field doesn't exist in the building layer. But rather use the same old way that we do (looking for some attributes e.g amenity, type, etc)

**Comment by timlinux** [comment]
We did this with new value_map in 3.4
