### ISSUE TITLE
Align Rasters Tool

### ISSUE THREAD

**Issue by wonder-sk** [inasafe/inasafe#1998]
# Align Rasters Tool

The idea is to add support for alignment of rasters to QGIS. By the alignment of rasters it is meant that several raster layers are resampled to a common coordinate reference system, having the same image size, cell size and cells are perfectly aligned among the individual raster layers. Aligned rasters are required for impact functions in InaSAFE when either hazard and exposure are raster layers.

The tool will consist of two parts:
- API in QGIS analysis library - for use in Processing framework, InaSAFE or other plugins
- module for Processing framework - to allow users to use the tool from graphical interface
## Integration with InaSAFE

InaSAFE code will be updated to use the raster alignment tool if it is available, creating temporary rasters. If an older version of QGIS is used, it will use current code path within InaSAFE: clipping of rasters to the requested extent if the rasters are aligned, terminating with an error otherwise.
## Implementation Details

The tool will be mainly built around GDAL library and its warping algorithms. The implementation will use C API calls for that (i.e. not running `gdalwarp` command line utility) to allow greatest flexibility. All the heavy lifting will be done by GDAL, with the Align Rasters tool serving as a wrapper that processes multiple files at once with the same resampling configuration. There are several reasons for choosing GDAL:
- the warping code is proven with time by broad community
- covers lots of situations (raster data types, raster bands, nodata values etc)
- has optimized code paths for high performance warping
- lots of configuration options
- already a dependency of QGIS

The GDAL library allows a wide range of configuration options to be used for resampling:
- clipping to region of interest
- reprojection between different CRS
- resampling methods
- masking
- handling of nodata values
- pre- and post- warping routines

The choice of resampling method will mainly depend on the type of input raster layers:
- discrete data (e.g. classes) are best resampled with nearest neighbor method (or mode)
- continuous data are typically resampled with interpolation (bilinear, bicubic or others)

GDAL also supports aggregation during resampling - it is possible to use average or mode (most often encountered value) of all contributing pixels. GDAL does not support weighted aggregates - the proportion of the source pixels covering the output pixel is ignored. From GDAL 2.0 there are further aggregation options: max, min, median, first/third quartile.

Handling of raster data where values represent absolute counts within area of the cell need to be treated specially: when the change of cells' areas during resampling it is necessary to rescale also the values. This will be done using pre- and post- warping routines, where the values are first transformed to values independent from cell size (e.g. count per square kilometer), then resampled and finally converted back to values representing counts per cell.
## Module for Processing framework

A new algorithm will be added to the Processing framework to allow running the raster alignment from the user interface or even as a part of a model within the Processing framework.

Mockup of the GUI:

![image](https://cloud.githubusercontent.com/assets/193367/7952082/8b166530-09e2-11e5-8da1-9b7fe1a12c8c.png)
## Testing

Automatic tests will be added to QGIS test suite that will employ small raster layers to check correct behavior of the tool in various situations.
## Raster Resampling in GRASS

[just a note on how others do resampling]

All raster analyses are done within GRASS _region_ which consists of CRS definition, spatial extent (rectangle) and resolution (X/Y cell size). If source rasters are not aligned with the region, they are reprojected on the fly to the desired region (using nearest neighbor resampling method). There are dedicated tools for resampling:
- r.resample (explicit tool for resampling to the region as described above)
- r.resamp.interp (with selectable resampling method: NN / bilinear / bicubic)
- r.resamp.stats (resampling to coarser grid with aggregation, optionally weighted)

**Comment by wonder-sk** [comment]
CC @akbargumbira @Charlotte-Morgan @timlinux

**Comment by timlinux** [comment]
Hi @wonder-sk 

Thanks for this well written ticket! A few comments / questions from me:

1. Note that we differentiate between 
* **population count** - cells contain number of people present in that cell 
* **population density** - cells contain number of people per m2 / km2 etc

So in your wireframe above the line item should be Population count. Maybe simply having a checkbox next to item with 'Scale values' would work. Where ticking the box would indicate that for this raster values should be proportionally scaled to the new cell size.

2. In your wireframe it would be nice to have the option to also use a bookmark to define the extents - see example from one of our InaSAFE ui's:

![screen shot 2015-06-03 at 11 07 50](https://cloud.githubusercontent.com/assets/178003/7952525/d43a8108-09e0-11e5-9dd7-1a0a2e612cc4.png)

3. For clipping behaviour we have some rules as described below:

![clpextentsadjustment - process](https://cloud.githubusercontent.com/assets/178003/7952547/4c224aac-09e1-11e5-9252-b7fda80170a2.png)


Original source for this diagram is here:

https://www.lucidchart.com/invitations/accept/cc02d3a1-544a-422d-b11d-3c7d34c276d6 

4. For the reference layer I am wondering if it would be good to allow the user to override the CRS so that in effect the output layers conform to the the cell size of the reference layer, but not necessarily the same CRS. The use case for this is where you want all your layers to match the cell size of e.g. a population layer, but be output as e.g. UTM.

**Comment by wonder-sk** [comment]
Thanks for the comments:
- good idea with bookmarks. It seems there is no support for bookmarks in API yet (neither in core nor bookmarks combo box widget) - may be good to add that too. Or maybe even better to create a general "extent selector" widget - probably a combo box with basic choices (e.g. project extent, canvas extent), list of bookmarks and an option for custom extent.
- CRS selection is planned too, the mockup just isn't explicit about it :-)

**Comment by timlinux** [comment]
Hi

> It seems there is no support for bookmarks in API yet (neither in core nor bookmarks combo box widget) - may be good to add that too.

Yes please - at the moment we do hacky stuff like this to get them:

https://github.com/AIFDR/inasafe/blob/develop/safe/gui/tools/extent_selector_dialog.py#L313

> Or maybe even better to create a general "extent selector" widget - probably a combo box with basic choices (e.g. project extent, canvas extent), list of bookmarks and an option for custom extent.

Yup that would be a good option too

> CRS selection is planned too, the mockup just isn't explicit about it :-)

OK cool!

**Comment by Charlotte-Morgan** [comment]
hi @wonder-sk - this looks great.
i think its good for the user to be able to find information about their data in the tool and they can do that by trying each raster as a reference layer before they finalise the choice.
This also allows users to have a 'reference' raster (national grid in preferred coordinate system and cell size that they can use to resample things consistently.

**Comment by wonder-sk** [comment]
Work in progress is in my QGIS fork:
https://github.com/wonder-sk/QGIS/tree/raster-alignment-tool

**Comment by wonder-sk** [comment]
The raster alignment tool for QGIS is now ready in my branch - and it can be merged to QGIS master next week. The tool is available under menu Raster > Align Rasters.

Preview of the GUI:
![image](https://cloud.githubusercontent.com/assets/193367/8352453/d782c51c-1b67-11e5-82cc-3486faa4fba0.png)

Adding/editing a raster layer:
![image](https://cloud.githubusercontent.com/assets/193367/8352468/ebb7354a-1b67-11e5-9137-55f16edb2f7f.png)


Next step: integrate the tool into InaSAFE so that alignment is done automatically for raster-raster impact functions (with some default configuration).

**Comment by wonder-sk** [comment]
Raster Alignment tool has been merged to QGIS master branch, so it should be available in the nightly builds from tomorrow.

**Comment by timlinux** [comment]
Thanks @wonder-sk closing this. In V4.0 we are using the alignment tool in EQ functions too.
