### ISSUE TITLE
IF options help text and description

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#2018]
We need help text and descriptions for several IF options and post processor:
1. Earthquake
   - Low Threshold
   - Medium Threshold
   - High Threshold
2. ITB Earthquake
   - Doesn't have any
3. Pager Earthquake
   - Doesn't have any
4. Generic Classified Polygon Building
   - Hazard Zone Attribute
5. Generic Classified Polygon Population
   - Hazard Zone Attribute
6. Generic Classified Raster Building
   - Low Hazard Class
   - Medium Hazard Class
   - High Hazard Class
7. Generic Classified Raster Population
   - Low Hazard Class
   - Medium Hazard Class
   - High Hazard Class
8. Generic Continuous Hazard Population
   - Categorical Thresholds
9. Flood Polygon Population
   - Evacuation Percentage
10. Flood Polygon Roads
    - Won't have any
11. Flood Raster OSM Building
    - Thresholds
12. Flood Raster Population
    - Thresholds
13. Flood Raster Roads
    - Min Threshold
    - Max Threshold
14. Flood Vector Building 
    - Won't have any
15. Tsunami Population Evacuation
    - Thresholds
16. Volcano Point Building
    - Distance
    - Volcano Name Attribute
17. Volcano Point Population
    - Distance
    - Volcano Name Attribute
18. Volcano Polygon Building
    - volcano name attribute
19. Volcano Polygon Population
    - volcano name attribute

For the post processor part:
1. Gender
2. Age
3. Minimum Needs
# Notes

@timlinux @akbargumbira @ismailsunni :
I will update this from time to time, please comment on incorrect grammar/vocabulary.

**Comment by ismailsunni** [comment]
@lucernae can you give some indication which part have you done and not done?

**Comment by ismailsunni** [comment]
No longer valid for InaSAFE v4.
