### ISSUE TITLE
Raster Hazard Classes are invalid ?

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2037]

**Comment by Charlotte-Morgan** [comment]
# Problem
In definitions.py flood_raster_hazard_classes are described as being wet or dry  ..

This is appropriate for binary vector data but not raster data where the values should be numeric.

# proposed solution

**Comment by ismailsunni** [comment]
hi @Charlotte-Morgan 

key as in 
```
        {
            'key': 'wet',
            'name': tr('wet'),
            'description': tr('Water above ground height.'),
            'numeric_default_min': 1,
            'numeric_default_max': 9999999999,
            'optional': True
        },
        {
            'key': 'dry',
            'name': tr('dry'),
            'description': tr('No water above ground height.'),
            'numeric_default_min': 0,
            'numeric_default_max': (1 - small_number),
            'optional': True
        }
```

is used for accessing the class so that each class has different key. It's like mapping the value to the key.
It will be store in `value map` in keyword file. So, it's ok to have text key in raster dataset.

You can go to tweak the text string :)

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni.
thanks - i can look at strings. Raster Hazard keys are valid :)

**Comment by timlinux** [comment]
This is also dealt with nicely in v4 code where you can have either string values or numeric ranges (and in so doing catering for raster and vector data).
