### ISSUE TITLE
We need a backup scheme in place for the user map

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2042]
@rduivenvoorde Currently our docker project for the user map has no backups in place. Before migrating we need to make a dump and then we need to update the docker-compose.yml config to inlcude my pg-backup docker container which automatically makes backups.

**Comment by timlinux** [comment]
Here is how you run it interactively

```
docker run --name="inasafe-usermap-backups" --hostname="inasafe-usermap-backups"  --link=inasafe_db_1:db  -v `pwd`/backups:/backups -i -d kartoza/pg-backup
```

**Comment by rduivenvoorde** [comment]
@timlinux all on kartoza4?

**Comment by timlinux** [comment]
I have set it running on kartoza4 - this ticket is more for when we migrate to the new server, it must be get the date migrated and backups running on the new server.

**Comment by timlinux** [comment]
@lucernae set up a backup system for it some time ago I think. @lucernae will you please check one of the dumps restores nicely? I will close this in the meantime.
