### ISSUE TITLE
Icons between sites and application should match

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2048]
Currently the size, placement and style of icons between http://blogtest.inasafe.org, http://docs.inasafe.org and http://geonode.inasafe.org are all different. Can we make these consistent and use the white icon / logo as per the t-shirt?

**Comment by Charlotte-Morgan** [comment]
and also can we please make icon on the internet page tabs consistent
![image](https://cloud.githubusercontent.com/assets/5743135/8202927/620c29be-1508-11e5-9162-380a138254a0.png)

**Comment by rduivenvoorde** [comment]
Is there a place where we can set the 'canonical' favicon? 
This can be used for other key images like icons too.
Something like: http://inasafe.org/icons

So all webapps can use an url like: http://inasafe.org/img/...

**Comment by rduivenvoorde** [comment]
If I understand correctly this repo (should) contain all logo's etc:
https://github.com/AIFDR/inasafe-graphics

What about making that availabe as http://inasafe.org/graphics, so all apps could point to this, and we can keep it updated by a 'git pull'? Maybe add a separate directory for the live/online versions?

**Comment by timlinux** [comment]
> If I understand correctly this repo (should) contain all logo's etc:
> https://github.com/AIFDR/inasafe-graphics

Correct - for master copies anyway,

> What about making that availabe as http://inasafe.org/graphics, so all apps could point to this, and we can keep it updated by a 'git pull'? Maybe add a separate directory for the live/online versions?

Do you mean for CSS etc so that we can update theming from one place? If yes that sounds like a nice route to take.

**Comment by rduivenvoorde** [comment]
Yes. So there is one canonical online image directory to be used for images in css and html: logo's, common used icons, favicon.ico etc
But the main reason behind it was that I was thinking where to put it online.

**Comment by timlinux** [comment]
> Yes. So there is one canonical online image directory to be used for images in css and html: logo's, common used icons, favicon.ico etc

Ok I like that.

> But the main reason behind it was that I was thinking where to put it online.

I was also going to be linked to from http://blogtest.inasafe.org/for-contributors/for-documentation-writers-and-designers/design-and-media/

@maria at the bottom of the above page we should change the text on the small buttons to white.

**Comment by rduivenvoorde** [comment]
ok, we created http://blogtest.inasafe.org/style as part of the wordpress blog site.

By putting it in the /home/web/inasafe.org/wp-content dir it is backed up together with the rest of the website (to be clear: it's not in git)

Added autoindx on it so you could view the images.

Tried to make it already available on http://inasafe.org/style too so everybody can already start using it, but that one is (I think) on kartoza2 where I do not have sudo to change the (apache?) config
