### ISSUE TITLE
IF issue : Breakdown the analysis results of Building Type  on BIG data (non OSM downloader)

### ISSUE THREAD

**Issue by fredychandra** [inasafe/inasafe#2089]
# PROBLEM

The analysis result for building structure exposure have no breakdown for it building type, whereas it has already selected the structure classified (attribute).

# DETAIL

- I run it at Qgis 2.8.1
- InaSAFE 3.2.0 dev-master
- The exposure data type is from Badan Informasi Geospatial (BIG). It has a fix string (text) to  
     classify building type or public service infrastructure. Actually The text/each type of building come 
     from BIG standard code. https://drive.google.com/drive/my-drive
- Use Keyword > Exposure > Structure > Classified > NAMA_UNSUR
- Here is the attribute

  ![attribute_infrastructure_big](https://cloud.githubusercontent.com/assets/6345285/8537706/ffef36e2-248c-11e5-8e4b-a64a3e7add2a.PNG)
- Here is InaSAFE IF analysis result (red pen mark)
![1_building exposure analysis results](https://cloud.githubusercontent.com/assets/6345285/8537858/b07afd42-248e-11e5-8916-8ca7aa962079.PNG)

# Proposed Solution

- In the InaSAFE future version, the InaSAFE IF analysis result for building structure exposure should can breakdown as classified inside the attribute not only from OSM data that download from OSM downloader but also can run and classify from others data type like BIG

#CC 
@Charlotte-Morgan 
@ismailsunni 
@timlinux

**Comment by Charlotte-Morgan** [comment]
@fredychandra - +1
I agree that it would be good for reports of affected buildings to also be available for standard buidlign type codes used by BIG. @timlinux - how does this relate to the JakSAFE work which IIRC also wanted to be able to report against different building type classifications? 
# cc
@iyan31

**Comment by Charlotte-Morgan** [comment]
see #1666

**Comment by akbargumbira** [comment]
This is not far to achieve as things are in line already:
- Specifying building type when user assigns building keywords in keyword wizard (done)
- Updating all the IFs to get building type from exposure keywords (in @ismailsunni's PR)

**Comment by samnawi** [comment]
I try use IF like @fredychandra's doing, but I run it in QGIS 2.8.2.
The result is has the breakdown of the building type, but just appear others and *sekolah*. 
![screenshot_1](https://cloud.githubusercontent.com/assets/8871958/8543143/f7d286a2-24c4-11e5-8773-b8c636ba5900.jpg)

Whereas, in the attribute we can see not only *sekolah*, but also *, Mesjid, Gereja, Kantor Desa,* etc.
![screenshot_2](https://cloud.githubusercontent.com/assets/8871958/8543148/0436289a-24c5-11e5-90ca-bf8bc8ad54ff.jpg)

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan @fredychandra @samnawi @akbargumbira @timlinux 

My PR in #2080 (for issue #1991 ) will fix this. It will make the user able to choose which field where the  building type located. I also have updated the IF so it will work.

I only update the IF that has building classification previously (not all building IF has it, volcano point building). But, I can add it to them, easily.

**Comment by ismailsunni** [comment]
I think we can close this since it's been implemented in #2080
