### ISSUE TITLE
Post Processor UI - needs work

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2093]
# problem

the UI in the post processors looks a bit strange when the check box is a long way from the parameter
![image](https://cloud.githubusercontent.com/assets/5743135/8539470/61a22a48-24a6-11e5-887f-9031390be62e.png)
# proposed solution

would it be possible to put the check box to the left of the parameter so that it always appears close regardless of the parameter length?

**Comment by Gustry** [comment]
We don't have this window anymore. I'm going to close this issue.
