### ISSUE TITLE
Communicate the limitations of running with big datasets to users

### ISSUE THREAD

**Issue by ingenieroariel** [inasafe/inasafe#210]
Either by docuemntation or the GUI, when users select detailed datasets with a big viewport we should set their expectations instead of them having to wonder wether or not it is going to  finish successfully.

Perhaps warnings when the data is too big? Like OSM does. (Ask Liana for more info).

**Comment by ismailsunni** [comment]
We had memory checker for this issue. Is it enough? If so, we can close this ticket.

cc @timlinux @ingenieroariel

**Comment by cchristelis** [comment]
The memory checker only considers raster layers. The number of features within the extents might be  a worthwhile additional checker. Its gonig to be a bit harder to map to memory usage than pixels in a raster, but there should be some correlation. Also the overhead of determining this number should not be ignored.

**Comment by cchristelis** [comment]
I had a look at counting features within a area of interest. This can also be included quite nicely in the new style impact functions' validator. The question is at how many features the analysis starts becoming unreasonably slow...

https://gist.github.com/cchristelis/c126d24986dc8e9df786

**Comment by timlinux** [comment]
I wonder if simply having better progress reporting and the ability to kill analysis is a nicer way.  There are caveats with approach suggested in that measuring the job size will probably take as long as doing the job - and the job with size detection will take longer than the job without. See also #727 where we recommend progress callbacks.  I'm going to close this out in favour of callbacks.

**Comment by timlinux** [comment]
When we do the 7 base class refactoring, lets also plan for putting progress indicator call backs and using the threads stuff that is being worked on in QGIS to keep the display updated nicely.

**Comment by timlinux** [comment]
So the main task here is to add progress reporting to all IF's

**Comment by ismailsunni** [comment]
Related to #727

**Comment by timlinux** [comment]
In 4.0 we have callbacks for analysis progress. I will add a paragraph to limitations like this:

![screen shot 2017-01-17 at 11 48 53 am](https://cloud.githubusercontent.com/assets/178003/22008157/25e90a30-dcab-11e6-81c5-646fc40a77fd.png)
