### ISSUE TITLE
IF Report : Printed road affected report clipped

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2106]
# Problem
Both of Tsunami and Flood roads IF, when the report is printing, the table of detailed road type is clipped.
![selection_063](https://cloud.githubusercontent.com/assets/8871958/8591423/6d55f0ce-2652-11e5-8951-4d9ea17817ba.png)

# Proposed Solution
Make the report fix with the page

cc : 
@Charlotte-Morgan 
@timlinux 
@ismailsunni

**Comment by samnawi** [comment]
@Charlotte-Morgan Can we closed this ticket and move to ticket #2373 ?

**Comment by ismailsunni** [comment]
@samnawi I think they are the same issue and we can close this ticket and mark it as duplicated

**Comment by ismailsunni** [comment]
Duplicated with #2373
