### ISSUE TITLE
why do we ship simplejson and use json most of the time

### ISSUE THREAD

**Issue by mbernasocchi** [inasafe/inasafe#2119]
in safe_extras we have simplejson but it is used in only 5 places (1 time in runner.py and 4 in raven).

the builtin json module is used 15 times.

raven seems that should work with the builtin also: https://github.com/getsentry/raven-python/blob/master/raven/utils/json.py

I think we could just use the builtin

**Comment by ismailsunni** [comment]
We do not use simplejson anymore. Closing this.
