### ISSUE TITLE
We need a way to test that Realtime is running

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2160]
# Problem

It is possible for InaSAFE Realtime to stop working and for no one to notice.
Today - the last Realtime event is dated 13th July, yet there have been 17 earthquakes in Indonesia since that date, 5 of which are greater than 5.0
We seem to be unaware of system failures unless a person looks at it.
InAWARE provides links to files that do not exist.
# proposed solution

We need to build an automatic system to check that EQ realtime is running and generating reports regularly. This system needs to run automatically and send a message to an administrator or trigger a server restart if there is an error.
I propose a daily / 12 hourly test where a dummy shakemap is sent to realtime. This dummy data is tagged in a way so that the resulting impact assessment is filtered off and stored in a test location (not delivered to the real output).
If a new file is not delivered to the test location at the expected time - a message is sent to an administrator to check the system / the server is poked to make it run ...
# cc

@hadighasemi @davidr007 @ismailsunni @lucernae @timlinux @dynaryu

**Comment by lucernae** [comment]
Actually I'm aware of this and already sent email to BMKG at 14th or 15th. They just responded yesterday because of the long holiday season and will send the push map immediately. 

This is actually expected, because I changed some of the server parameters and found some bug, if the server restarts or docker container restart, BMKG will not be able to connect. The bug itself is fixed, but since they are on holiday and perhaps haven't read the email, they aren't able to follow my notes to reconnect. But, they responded yesterday.

Sorry, I should have told you when that happen.

**Comment by Charlotte-Morgan** [comment]
Its great that you are already working on this issue. Do you have an automatic test in place or does it rely on you checking manually?

**Comment by lucernae** [comment]
What concerns me the most in this case is, we have no way to tell if BMKG is able to connect or not right now. I found this problem by chance last time when testing the new realtime. The processing itself will be ran as long as the server is up. But, I think the general idea is good, we should have set up some dashboard just to see that the system is in healthy condition.

**Comment by timlinux** [comment]
@davidr007 Do you know if there is an alternative url  / site that presents a list of shake events. We could connect to that regularly and cross reference the events list there with those that we have processed - e.g. on a jenkins scheduled test.

**Comment by timlinux** [comment]
@lucernae it might be good for you to go and have a poke around the BMKG web site and see if you can pick up something like this.

**Comment by timlinux** [comment]
@lucernae can you update the status of where we are with this?

**Comment by timlinux** [comment]
Closing this in favour of the ticket in inasafe-realtime repo
