### ISSUE TITLE
Can inasafe get some data related to addr:housenumber points

### ISSUE THREAD

**Issue by marcobra** [inasafe/inasafe#2163]
Sometimes is good in a disaster plan to have all the addr:housenumber involved in a scenario, listed.
Can inasafe take care/use this useful data ?

We are trying to use inasafe to elaborate "Protezione civile" local plan.
https://www.openstreetmap.org/relation/43144#map=18/44.40486/8.68555

http://mappa.italiasicura.gov.it/#/interventi?zoom=16&lat=44.404013010999904&lon=8.680145815282714

Thank
Marco

**Comment by Gustry** [comment]
Do you mean to add addr:housenumber  to the attribute table in the OSM Downloader ?

**Comment by marcobra** [comment]
yes i have most data linked to addr:housenumber

**Comment by Gustry** [comment]
I've updated the attribute table so I think I can close this issue.
