### ISSUE TITLE
Calculation of number of displaced people using the earthquake fatality model

### ISSUE THREAD

**Issue by dynaryu** [inasafe/inasafe#2168]
1. calculation
   Currently the number of displaced people is computed as the product of the displacement rate and exposed population. I'd like to suggest that the people survived (exposed population - fatalities) should be used instead of the exposed population. 
2. mmi range for displacement rate
   We need to use the same mmi range. if we chose the mmi range between 2 and 10 (range(2,11) in python) then displacement rate should be provided accordingly at the same mmi range.
3. rounding
   Not aware of any utility function to provide rounding of any figures out of the computation. We need a function something like http://stackoverflow.com/questions/15769948/round-a-python-list-of-numbers-and-maintain-the-sum.

**Comment by Charlotte-Morgan** [comment]
hi @dynaryu 
thank you for raising this issue. It looks like you have concerns about:
- [ ] how the calculation works
- [ ] how the results are presented
- [ ] how the rounding is applied

The developers would find it helpful if you are able to provide examples of:
- [ ] a scenario with the current results and what you want the preferred results look like

# cc @timlinux @griffij @lucernae @davidr007

**Comment by timlinux** [comment]
See also #1960

**Comment by timlinux** [comment]
Thanks @dynaryu - lets get your PR #1960 applied first and then clarify which of the above issues is not addressed in your PR. Could you take a look at my Pull Request which sorts out some coding standards issues and then we can go ahead and apply #1960

**Comment by dynaryu** [comment]
1 and 2 are resolved in the PR #2178. Regarding the 3, I'd like to know any logics behind the population_rounding function.

**Comment by lucernae** [comment]
hi @dynaryu . population_rounding function accepts a number and rounds it with the following logic:
1. If the number is less than 1000, we round them to the nearest multiplication of 10 (using a ceiling function to be precise). So, if the number is 9 or 8 or 7 or 5 or 2, it will be rounded to 10. If the number is 333 it will be rounded to 340.
2. If the number is between 1000 and 100000, we round them (with similar logic) to the nearest multiplication of 100. So, if the number is 3333 it will be rounded to 3400.
3. If the number is greater than 100000, we round them to the nearest multiplication of 1000. So, 1234567 becomes 1234000.

You can see the implementation [here](https://github.com/AIFDR/inasafe/blob/develop/safe/impact_functions/core.py#L107)

Let me know if you need another help

**Comment by timlinux** [comment]
@dynaryu can we close out this issue if everything is cleared up for you with @lucernae 's explanation above? Thanks!

**Comment by dynaryu** [comment]
Thanks for the explanation, @lucernae. Should we use the same rule (either in absolute or relative ) regardless how large or small the original number is?

**Comment by timlinux** [comment]
I'm moving this over to milestone 3.6. Is there anything we can do to progress this? @dynaryu

**Comment by Charlotte-Morgan** [comment]
@dynaryu  - please let us know if this can be closed or if there is more to do.
## cc 
@easmetz @RikkiWeber - please poke @dynaryu :)

**Comment by timlinux** [comment]
I'm going to close this out - In v4 all rounding should be managed centrally and at report rendering time, so I think it is better to create any rules in standards (e.g. like in #2920) and then we apply them uniformly to all scenarios.
