### ISSUE TITLE
map all kw to new metadata

### ISSUE THREAD

**Issue by mbernasocchi** [inasafe/inasafe#2173]
adresses PR #2165
need to put the correct XML mappings for the following _standard_properties:
##### BaseMetadata:
- [x] title
- [x] license
- [x] scale
- [x] source
- [x] url
- [ ] layer_mode
- [ ] layer_geometry
- [ ] keyword_version
- [ ] scale
- [ ] source
- [ ] layer_purpose ---> this can be inferred from the class (ImpactLayerMetadata, AggregationLayerMetadata, HazardLayerMetadata, ExposureLayerMetadata)

##### HazardMetadata
- [ ] hazard_category
- [ ] hazard
- [ ] continuous_hazard_unit
- [ ] vector_hazard_classification
- [ ] raster_hazard_classification

##### ExposureMetadata
- [ ] exposure
- [ ] exposure_unit

##### AggregationMetadata
- [ ] aggregation attribute
- [ ] adult ratio attribute
- [ ] adult ratio default
- [ ] elderly ratio attribute
- [ ] elderly ratio default
- [ ] female ratio attribute
- [ ] female ratio default
- [ ] youth ratio attribute
- [ ] youth ratio default

**Comment by mbernasocchi** [comment]
added most, still to add the correct mappings to xml

**Comment by ismailsunni** [comment]
hi @mbernasocchi what's the status of this PR?
Btw, can you update it with develop branch? There is a fix that makes your PR pass.

**Comment by ismailsunni** [comment]
We also need to keyword for hazard:

value_map : to store the value mapping in hazard classification as dictionary. If it doesn't use classification, let it empty.
field: to store the field name for hazard. The field contains the value for the hazard or the classes.

In the future, we want to use `hazard_field` and `hazard_value_map` to replace them. See #2074 Or we can do it in this iteration.

For exposure:
structure_class_field: to store the field name for exposure layer.

**Comment by ismailsunni** [comment]
Superseded in #2538
