### ISSUE TITLE
Branding within InaSAFE should use new look and feel

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2181]
In particular the dock panel here:

<img width="330" alt="screen shot 2015-08-15 at 20 42 08" src="https://cloud.githubusercontent.com/assets/178003/9290323/241394e4-438e-11e5-9e72-279a7d8e3923.png">

And on reports etc. should use monochrome gunungan logo. Ideally should use new css too - to match the new web site...

**Comment by timlinux** [comment]
CC @MariaSolovyeva I may need some help with you on this....

**Comment by ismailsunni** [comment]
I think we can close this, right?
