### ISSUE TITLE
We need to clarify high, medium, and low hazard levels in the EQ impact summary.

### ISSUE THREAD

**Issue by dynaryu** [inasafe/inasafe#2182]
When "Might Be Impacted" is chosen in the EQ event, the result is as follows:

In the event of earthquake how many population might be impacted
People impacted 40
People in high hazard area  0
People in medium hazard area    0
People in low hazard area   40

Suggestions:
1. The thresholds are to be defined by entering three values in the categorical thresholds. It's hard to know how these values are used just by looking at the input window. Also the provided thresholds need to be provided in the results.
2. People exposed to certain level of hazard should be provided even when either ITB or PAGER fatality function is selected. In this case, "Might be impacted" can be removed.
3. "Might be impacted" seems ambiguous. Can be replaced with "Might be exposed"

**Comment by Charlotte-Morgan** [comment]
hi @dynaryu - is this in realtime or in the desktop version?
The team here is already planning to review the terminology and definitions for InaSAFE3.2 & this is the sort of thing we need to address.
#cc
@timlinux

**Comment by dynaryu** [comment]
@Charlotte-Morgan 
It's in the desktop version.

**Comment by Charlotte-Morgan** [comment]
hi @dynaryu - we will be reviewing all impact functions, thresholds and terminology in the next week - we will look at this then, once all the other code changes are in freeze

**Comment by Charlotte-Morgan** [comment]
@samnawi - can you please take a look and see if this is still an issue following the report updates @timlinux did ?

**Comment by timlinux** [comment]
So we should also encode this as best practice in #2920 . Revisiting this I am thinking that we should do two things:

1. Include the thresholds used in parentheses after the legend items
1. Include a section in the IF report **notes** section detailing what the thresholds used were

![screen shot 2016-06-22 at 10 59 04](https://cloud.githubusercontent.com/assets/178003/16260660/acf48ad2-3868-11e6-958f-560281c94fc9.png)

would be rather:

![screen shot 2016-06-22 at 10 59 04](https://cloud.githubusercontent.com/assets/178003/16260718/e309fefe-3868-11e6-96ea-80757cfbfcfe.png)

**Comment by timlinux** [comment]
@easmetz will you add some rules so the reporting standards RFC?

**Comment by ismailsunni** [comment]
Move to 3.6 per discussion with @timlinux

**Comment by timlinux** [comment]
This is dealt with in the standards and in the new IF architecture, I think it is better we continue the conversation there.
