### ISSUE TITLE
We need access to the zoho server to configure geonode to send notifications

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2185]
Hi @mach0 

Can you help with this - I can't seem to log in with the credentials I have for ZOHO?

Thanks

Tim

**Comment by timlinux** [comment]
# CC

@gubuntu

**Comment by Charlotte-Morgan** [comment]
hi @mach0 - can you help with this please ?

**Comment by timlinux** [comment]
I think we can deal with this another way. Closing for now.

**Comment by mach0** [comment]
Is there still something missing? Shall I search for passwords? I only got this message right now ..

**Comment by timlinux** [comment]
@mach0 Will be great if you can track down the ZOHO details for inasafe and share with me - I will add to my keypads
