### ISSUE TITLE
Testing in QGIS 2.8.3

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#2188]
Problem
------------
For version 3.2, we want to support InaSAFE for QGIS 2.8.3. Currently, Travis is running on QGIS 2.8.1.
I have tried to run all tests in my local machine with QGIS 2.8.3, and all tests pass. But we have some problem with test in Travis (see : https://travis-ci.org/AIFDR/inasafe/builds/76292598)

Related issue:
#2065 

This issue also closes #2078

**Comment by ismailsunni** [comment]
Update:

I remove the 250th test that create the error, then Travis also stops running after 250 tests. :dancer: 

See : 
- https://travis-ci.org/AIFDR/inasafe/builds/76292598
- https://travis-ci.org/AIFDR/inasafe/builds/76308430

**Comment by timlinux** [comment]
We should move testing to QGIS 2.14 - lets close this out and focus on that rather - work is in progress to make InaSAFE run in docker using QGIS 2.14. CC @Gustry
