### ISSUE TITLE
Make Sure The Document for Application Translation is Well Described

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#2197]
## Problem

The wiki https://github.com/AIFDR/inasafe/wiki/Internationalisation is not updated. Please make it happy.

**Comment by ismailsunni** [comment]
Can you check my update @timlinux ?

I am still not sure about `dynamic_translation`. I think it's not working anymore.

**Comment by timlinux** [comment]
@ismailsunni your update generally looks ok for me,. I think / hope we are still using dynamic translations to deal with translatable strings coming from the user's data. Thanks for making these updates.
