### ISSUE TITLE
Ability to work with remote data

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#22]
We need to be able to easily use remote data by fetching it dynamically as needed.
- open streetmap (through e.g. PostGIS mirror) 
- WFS
- WCS

**Comment by timlinux** [comment]
In InaSAFE 4.0 PostGIS data is working nicely. We still need to test with WCS and WFS.

**Comment by NyakudyaA** [comment]
In Inasafe 4.0 WCS and WFS working nicely. Tested with layers from http://oondra.kartoza.com/ 
![mix](https://cloud.githubusercontent.com/assets/2510900/22425141/5ae68292-e702-11e6-96cb-e5646190564e.png)

**Comment by Gustry** [comment]
Thanks @NyakudyaA for the comment.
Let's close this ticket.
