### ISSUE TITLE
Impact Layer Merge Tool does not work with Aggregation [bug]

### ISSUE THREAD

**Issue by harrymahar** [inasafe/inasafe#2229]
# Problem
Impact Merge Layer Tool does not work using aggregation

# Detail
I want to merge the results of the Jakarta flood impact function both for the building and population using Impact Layer Merge tool in InaSAFE. Unfortunately, It was only can managed to merge the impact function without aggregation. When I want to merge those impact using aggregation function by using the district boundaries of Jakarta, the results box said it created successfuly. However, it does not created in the selected folder.

# Screenshot
![impact merge layer_agregasi_error](https://cloud.githubusercontent.com/assets/2534179/9462937/63131374-4b43-11e5-8b4f-ca94ae5f4271.PNG)

![impact merge layer_agregasi_error2](https://cloud.githubusercontent.com/assets/2534179/9462945/71000988-4b43-11e5-8372-fc9a43e5f3f5.PNG)

![impact merge layer_agregasi_error3](https://cloud.githubusercontent.com/assets/2534179/9462961/8b181b62-4b43-11e5-9c31-1bd4dd3c6ec3.PNG)

# Platform
Windows 8.1 64 Bit
RAM 4 GB
QGIS 2.8.3 Wien
InaSAFE 3.2.0 dev-master

# Data used
Hazard : Jakarta_Flood_18113__WGS84.shp (Raster)

Exposure : 
*Java_Population_WGS84.tiff (Raster)
*Jakarta_Building_WGS84.shp (Vector)

Agregation : Jakarta_District_Boundary.shp

**Comment by timlinux** [comment]
Thanks @harrymahar @lucernae can you look into this please?

**Comment by lucernae** [comment]
@timlinux it seems the merge only happens when the first and second layer's are already aggregated.
So, it had no effect when the first and second layer is processed using 'entire area' aggregation but it is trying to be merged using another aggregation layer.

Perhaps we should offer relevant aggregation layer based on first and second layer in order to make the user less confused?

**Comment by harrymahar** [comment]
Hai @timlinux and @lucernae , Today I try to merge the result again. I start again using same data using Flood Impact Function in DKI Jakarta. The different thing that I did when I merge the impact function results was I match the extent of the results. So, they had similar extent view and positition in QGIS. Finally, when I merge those data, The PDF results was created based on aggregation layer which is Jakarta_District_Boundary. Eventhough it succeed to create the result, All PDF has same area display despite the result has divided based on district boundary and has different number of result. 

As my conclusion about this bug, Merge impact Layer Tool works both without aggregation and with aggregation as long as the results that want to be merged have same extent. But, the problem is all PDF which created after we merge the result has same area display despite the result has divided based on district boundary and has different number of result. 

![impact merge result](https://cloud.githubusercontent.com/assets/2534179/9484861/24769c28-4bdc-11e5-91d5-2c4e5b806a4d.PNG)

![merge result](https://cloud.githubusercontent.com/assets/2534179/9484864/2b1f4d0e-4bdc-11e5-9cbc-290f0b3a8db7.jpg)

**Comment by harrymahar** [comment]
halo @lucernae @timlinux  today I try again to use impact layer and the result still same, PDF's created but the display area for each District has same display despite has different result numbers. I think there is still a bug for this function

**Comment by lucernae** [comment]
Yes, I haven't fix the issue about the display. This tool has any other bug :). So I guess we expect the pdf also display relevant district right?

**Comment by timlinux** [comment]
Impact merge tool is gone in 3.5 - closing this!
