### ISSUE TITLE
Roads impact report category ordering

### ISSUE THREAD

**Issue by cchristelis** [inasafe/inasafe#2231]
# Problem

The category ordering of the road types in the impact report is currently incidental. We would like to have it arranged in a more deterministic way.

# Proposed solution

Add a category ordering to the keywords and/or use a default based on the fact that we are expecting the default situation to be a OSM download.

# Related issues

#1765

**Comment by ismailsunni** [comment]
We also have the ordering now in the impact report, and group the road into several categories. Closing this now.
