### ISSUE TITLE
Impact Layer Merge Tool bug and spec

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#2233]
See issue #2229.

While investigating it. I found another issue and perhaps some part of the code which isn't clear for me. Can someone clarify this? @ismailsunni @timlinux 

- [x] ```self.entire_area_mode``` is not reset back to False if we change aggregation layer from Entire area to an aggregation layer without closing the dialog. This is probably just a bug, I just have to add some code to reset it back.
- [x] If the first and second layer were results from un-aggregated analysis. Do we still able to merge it using aggregation layers?
- [x] If the first and second layer were results from aggregated analysis. Do we still able to merge it using 'Entire Area' aggregation?
- [x] If one of the layer is aggregated and the other doesn't. What should we do? :D
- [x] I found that in ```self.merge``` method, we get the dictionary of aggregated report from the dom in the impact report. Is this safe? What if the report DOM structure was changed? Is there any alternatives?
- [x] Related with above issue. Because we get it from the DOM, some of the keys possibly not match with aggregation layer if it contains Unicode. This is perhaps an issue with the postprocessor when generating the report.
- [ ] Generated PDF should display the map with relevant aggregation boundaries.

**Comment by timlinux** [comment]
>  self.entire_area_mode is not reset back to False if we change aggregation layer from Entire area to an aggregation layer without closing the dialog. This is probably just a bug, I just have to add some code to reset it back.

Yes I think this is a bug

> If the first and second layer were results from un-aggregated analysis. Do we still able to merge it using aggregation layers?

No - we need them to be aggregated to the same aggregation layer.

> If the first and second layer were results from aggregated analysis. Do we still able to merge it using 'Entire Area' aggregation?

If both were created using entire area, I think we should be able to merge them

> If one of the layer is aggregated and the other doesn't. What should we do? :D

Warn the user nicely that it is not supported please :-) 

> I found that in self.merge method, we get the dictionary of aggregated report from the dom in the impact report. Is this safe? What if the report DOM structure was changed? Is there any alternatives?

Impact merge was very hacky - the idea was to rewrite it once we have proper IF metadata in e.g. json format so that we can parse the outputs in a more rigourous way - something for 3.3 maybe


> Related with above issue. Because we get it from the DOM, some of the keys possibly not match with aggregation layer if it contains Unicode. This is perhaps an issue with the postprocessor when generating the report.

Hmm ... perhaps forcing the keys to ascii here might work?
