### ISSUE TITLE
Definitions: we need to update definitions

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2272]
We need to update definitions so that they are helpful to users. 
Where possible we should use published international definitions for disaster related terms.
I propose updating definitions using this source http://www.unisdr.org/we/inform/terminology
unless anyone objects

# cc
@maning @assefay @adissadis @iyan31 @timlinux @vdeparday

**Comment by Charlotte-Morgan** [comment]
hi @easmetz  - as discussed.
handing this to you. Please check our definitions and if a UNISDR definition exists, we should update and reference the source.

I think the file is definitions.py
#cc @timlinux  - please confirm the file

**Comment by Charlotte-Morgan** [comment]
hi @easmetz  - this is the file you need
C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe\safe\definitions.py

**Comment by timlinux** [comment]
I think this is already done in 3.4? @easmetz can you close this ticket if you are done?

**Comment by easmetz** [comment]
I am continuously updating definitions.py definitions as we go along and discover new words that need to be defined. There's a few more to go, I'd like to leave this open. No idea when this will be finished. I'd like to say by 3.5 but more definitions keep popping up.

**Comment by easmetz** [comment]
This is a good updated UNISDR terminology paper. http://www.preventionweb.net/files/45462_backgoundpaperonterminologyaugust20.pdf

**Comment by Charlotte-Morgan** [comment]
@easmetz - is this ticket and pull requests redundant now?

**Comment by easmetz** [comment]
They may be more definitions we need to add in the future but this ticket is done in terms of Version 3.5 since the pull requests have been merged.
