### ISSUE TITLE
Introduce preprocessing for polygon hazards

### ISSUE THREAD

**Issue by uniomni** [inasafe/inasafe#229]
InaSAFE preprocesses input layers (reprojection, clipping, resampling as appropriate).
However, with the recent addition of functionality for hazard layers being polygons with exposure being points or raster data we need to take into account those combinations.

Specifically, in addition to the reprojection and clipping, I suggest hazard rasters get resampled to a resolution that guarantee that each polygon has at least one raster point inside it. I believe one can find the minimal polygon area from any polygon vector layer and use that to determine the appropriate resolution (e.g. min_area/4).

**Comment by Charlotte-Morgan** [comment]
see #2473

**Comment by timlinux** [comment]
Closing this: this is old and we will address these problems via #2987
