### ISSUE TITLE
WEB SITE: Search for AIFDR

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2290]
We need to update branding on the new website and search for any references to AIFDR and links to the AIFDR web site. Branding needs to be updated now that AIFDR ceases to exist.
# proposed solution

Backward looking references can be retained but web links might need to be updated
Forward looking references should be revised
InaSAFE related stories from the AIFDR website should be copied to the InaSAFE web site.
# proposed action

@MariaSolovyeva or someone to find all the references using some smart search ..
@me to advise on new wording
# cc

@timlinux @iyan31

**Comment by Charlotte-Morgan** [comment]
Hi @timlinux
Grateful if someone can get on to this, especially now that the new site is live and the AIFDR site is coming down.

**Comment by timlinux** [comment]
So I propose that we use ``DMInnovation`` instead of ``AIFDR`` for all 'current' links

**Comment by MariaSolovyeva** [comment]
Hello @Charlotte-Morgan 
Here is the list of references to AIFDR on the website:

Home page: http://inasafe.org/ - just below the screenshot "InaSAFE is free software that was developed jointly by Indonesia (BNPB), Australia (AIFDR) and the World Bank (GFDRR)."

Press page: http://inasafe.org/about-inasafe/press/ - 3 last articles

Supporters page http://inasafe.org/about-inasafe/supporters/ - the Australian Aid logo leads to http://www.aifdr.org/

**Comment by MariaSolovyeva** [comment]
@Charlotte-Morgan , please let me know with what we exchange those links

**Comment by Charlotte-Morgan** [comment]
hi @MariaSolovyeva 
proposed changes 
Home page: http://inasafe.org/ - just below the screenshot "InaSAFE is free software that was developed jointly by Indonesia (BNPB), Australian Government and the World Bank (GFDRR)."
use this link http://dfat.gov.au/geo/indonesia/development-assistance/Pages/disaster-risk-management-in-indonesia.aspx

Press page: http://inasafe.org/about-inasafe/press/ - 3 last articles
hopefully these articles have been copied to the InaSAFE web site now (the AIFDR web site will be pulled down on 30th September).

Supporters page http://inasafe.org/about-inasafe/supporters/ - the Australian Aid logo leads to http://www.aifdr.org/
please use this link http://dfat.gov.au/geo/indonesia/development-assistance/Pages/disaster-risk-management-in-indonesia.aspx

**Comment by MariaSolovyeva** [comment]
ok, done!

**Comment by Charlotte-Morgan** [comment]
Great - can you please grab the 3 articles and put them on the InaSAFE page? Not just links but grab the whole thing. It will all go off line on 30 September ie tomorrow.

**Comment by MariaSolovyeva** [comment]
@Charlotte-Morgan , the articles are on the site

**Comment by Charlotte-Morgan** [comment]
hi @MariaSolovyeva - thanks for rescuing the articles and cross posting. The articles contain internal links that are no longer valid ... so i might need to edit the articles to fix this.

Can you please also change the link on the supporters page:
Supporters page http://inasafe.org/about-inasafe/supporters/ - the Australian Aid logo leads to http://www.aifdr.org/
please use this link http://dfat.gov.au/geo/indonesia/development-assistance/Pages/disaster-risk-management-in-indonesia.aspx

Thanks

**Comment by timlinux** [comment]
@Charlotte-Morgan can you check on that link? Currently the website is updated to point to it but it gives an error: 401 UNAUTHORIZED

**Comment by timlinux** [comment]
@MariaSolovyeva can you replace the link for the Australian Gov in the logos on supporters page with this one:

http://dfat.gov.au/geo/indonesia/development-assistance/Pages/development-assistance-in-indonesia.aspx

Then we can close this.
