### ISSUE TITLE
Where possible we should support on the fly projection

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2293]
I am pretty sure that #2288 is actually caused by lack of on the fly projection support which we should be able to support pretty easily in cases like that.

Lets systematically work through all IF's and get them on the fly projection ready.

**Comment by ismailsunni** [comment]
Is it possible to put it in IF base class? In prepare method or something like that.

**Comment by lucernae** [comment]
I think we could do that. We haven't filled anything in that method. It should be able to handle reprojection and extent clipping, but we haven't use that.

**Comment by timlinux** [comment]
I'm moving this to 4.0 so we can do #2987

**Comment by Gustry** [comment]
We can now manage layers using different CRS. We will always use the exposure CRS for reporting.
