### ISSUE TITLE
Flood Polygon Building Says No Impact Incorrectly

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#2296]
## Problem

I am trying to fix #1158 
![qgis 2 8 3-wien - 1156_053](https://cloud.githubusercontent.com/assets/1421861/9576868/1aa7354e-5006-11e5-88e2-9acd8ba46b97.png)
It says that not buildings were impacted by this flood. But, if you look at the layer, there should be some impacted building.

The data : https://www.dropbox.com/s/6a1j624ja5g44y1/haiti.zip?dl=0

It happens after I pull from develop 4ce19d9

Before, it gives another different error.

**Comment by timlinux** [comment]
I think this is related to on the fly projection - see also #2293 

The previous error you got was an invalid geometry type gdal exception right?

**Comment by ismailsunni** [comment]
Hi @timlinux yes, exactly. So, we will pass it to version 3.3 ?

**Comment by timlinux** [comment]
Yes I think so unless I can come up with a fix in time....we can add it to our know issues list....for the release announcement.

**Comment by Gustry** [comment]
I'm going to close this one because we have now InaSAFE 4.0 with only one IF
