### ISSUE TITLE
We need to be able to produce csv's of output data

### ISSUE THREAD

**Issue by tdhu** [inasafe/inasafe#23]
Once a run has completed, we need to be able to automatically produce csv files of output tables.  These tables may include calculated parameters. For example, once we have estimated the number of people who will be seriously impacted we will need to apply calculations from BNPB's PERKA 7/2008. This allows us to calculate the:
- amount of rice in kg's
- amount of drinking water
- number of family kits
- number of toilets
- amount of cleaning water

THese results need to be automatically created and stored in a table that is easily accessed.

**Comment by timlinux** [comment]
@ismailsunni lets put this on the plan for 3.4 if you can manage it. Otherwise we will hold over until 3.5 if you can't. For now I would like to suggest that you just export the impact table and ignore the other elements (aggregated impacts, notes, actions etc.).

# CC

@Charlotte-Morgan @samnawi

**Comment by timlinux** [comment]
By the way I added it to the release cycle so that we can show the tangible benefits of all @ismailsunni 's hard work in storing impacts as JSON rather than as generated HTML.

**Comment by uniomni** [comment]
Keep it coming. It is so inspiring to follow your progress ;-)

**Comment by ismailsunni** [comment]
hi @timlinux 
Some options how it will work:

1. Add "get csv" button in the dock. Cons: it will make the dock more crowded
2. Add option to generate CSV in settings. Cons: if someone forget to disable it, he/she will get csv whenever he/she runs an analysis. Another cons, one needs several clicks to enable / disable it.
3. Add tab in impact report dialog and change print button to more generic. Cons: not so obvious

Any other idea?

btw, hi @uniomni, long time no see :)

**Comment by timlinux** [comment]
Yay we can do this in version 4!
