### ISSUE TITLE
Feature update: Softcode postprocessors

### ISSUE THREAD

**Issue by cchristelis** [inasafe/inasafe#2332]
# Problem

The postprocessors are built around the OSM data structures and naming conventions. This causes any non-conforming building or road exposure to cause false Zeros and 'No Data'

# Proposed solution

Softcode postprocessors' building and road types based on exposure layer.

# Related issues:
- #2318 
- #2320

**Comment by Gustry** [comment]
See this PR : https://github.com/inasafe/inasafe/pull/2743

**Comment by Gustry** [comment]
The PR #2743 has been merged. I'm closing this issue.
