### ISSUE TITLE
We need to update socialisation training

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2354]
# Problem
We need to update socialisation training materials for InaSAFE 3.2 

The following files need to be updated - high priority (release blocker)
by Charlotte
- [x] index.rst 
- [x] objective.rst
- [x] introduction.rst (new file)
- [x] inasafe_concepts (new file)
- [x] datasets.rst

by HOT
- [x] introduction to  qgis.rst
- [x] run basic inasafe.rst

----------------------------------------------------------------------------------------------
The following files need to be updated - not so high priority (not  a release blocker)
- [ ] intermediate inasafe.rst (was inasafe in more detail)
- [ ] other hazards.rst
- [ ] FAQ.rst

the following files from the current socialisation training material may not be required (TBC)
- [x] rastervsvector.rst (moved to introduction)
- [x] overview.rst (covered in introduction)
- [x] hints and tips (cover in introduction)

-------------------------------------------------------------------------------------
Proposed action:
- [x] migrate word docs to rst and merge to develop via pull requests
- [x] tweak links, formatting etc & connection between files once they are all in place
- [ ] translate and load Indo imagery - HOT
- [ ] get Indonesian versions of imagery from @MariaSolovyeva 

# cc
people copied here should raise any concerns asap if the above proposal does not meet workflow requirements or causes other problems (or if there is a better way to do it)
@timlinux @ismailsunni @iyan31 @adissadis @rduivenvoorde @samnawi

**Comment by Charlotte-Morgan** [comment]
Hi @adissadis @timlinux @rduivenvoorde @MariaSolovyeva 
i have updated this file to show what has been merged in PR 285 & what actions are still to be done.
Thanks @adissadis for stepping in to finish the files i started.

**Comment by Charlotte-Morgan** [comment]
updated again - i think we are in a position to remove the release blocker status - but still need to keep working on this

**Comment by Charlotte-Morgan** [comment]
hi @adissadis, @timlinux, @rduivenvoorde @MariaSolovyeva
I took the release blocker status off this ticket but it is still a really high priority.
Could eveyone please do their bit to get this into the bug fix release 3.2.1 this week?

**Comment by timlinux** [comment]
Can we close this?

**Comment by Charlotte-Morgan** [comment]
hi @adissadis - can this be closed?

**Comment by adissadis** [comment]
hi @Charlotte-Morgan yes this can be closed
