### ISSUE TITLE
We Need to Update the Scenario Data

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2366]
In http://data.inasafe.org/ScenarioData/ there is some scenario data in there, and I think we must update it, also keep some relevant scenario and archive the other scenario that not relevant. 
Make it more tidy, and in line with the new version of InaSAFE with new feature and new function in there.

# CC
@Charlotte-Morgan @fredychandra @iyan31 @adissadis

**Comment by Charlotte-Morgan** [comment]
@iyan31 @adissadis - please advise if you use these data; if not i can remove them

**Comment by Charlotte-Morgan** [comment]
@iyan31 @adissadis - grateful for your input please

**Comment by adissadis** [comment]
@Charlotte-Morgan Hi Charlotte,i prefer to update this data because if there any people who want to try InaSAFE with other scenario, they can download from here. And I will discuss with @samnawi  more about this issue.

**Comment by adissadis** [comment]
@Charlotte-Morgan after i discussed with @samnawi i think its better to keep those data. Because it might be useful for people who want to learn about other sample data. Also the keyword data is no need to be updated because we don't need to give them data that ready-to-run so people can learn again how to make those data run in InaSAFE.

What i purpose is manage the folder, so it might be something like this:

1. Training Data
     - Training Data Package
     - InaSAFE 3.1. Data
     - InaSAFE 3.2 Data

2. Other scenario data
     - Earthquake
          * Lembang
          * Yogyakarta
          * Padang
          * etc
     - Volcano
          * Merapi
          * Rokatenda
          * etc
     - Flood
     - Tsunami

3. Other Resource
     - Movie
     - Presentations
     - InaSAFE Use Cases

**Comment by Charlotte-Morgan** [comment]
Hi @adissadis - i am happy to keep the data and thank you for the feedback on the folder structure.
Now that we have the website we might not share all resources in the same way, similarly we hope to move the data to the GeoNode one day.

Specifically on the Other Scenario Data
Would you like to update the file names to match the naming convention we use with training data and also prepare metadata for each data set / location. I hope this does not impact too much on training materials.

My aim is to have all the data well documented. This is something we need before we can migrate to GeoNode.

**Comment by Charlotte-Morgan** [comment]
hi @adissadis - how is this going. please let me know when you have data ready to put back on line

**Comment by timlinux** [comment]
I think this is done now right? Can we close it off?

**Comment by Charlotte-Morgan** [comment]
I think not yet for scenario data - only socialisation data have been reviewed?

**Comment by adissadis** [comment]
@Charlotte-Morgan yes it only socialisation for now. For other training data, we currently updating training material screenies and also updating training data.

**Comment by Charlotte-Morgan** [comment]
@adissadis - do you have data ready to put on line?
#3012

**Comment by timlinux** [comment]
@adissadis just a reminder about this : we are planning to release on Wed 10 Aug - it would be great to have the scenario data update in time for the release.

**Comment by Charlotte-Morgan** [comment]
Hey @adissadis - thank you and sorry I missed it last time when you shared the data.
I have followed your advice and placed the new data in the folder as requested.  The only think I changed was to make a zip file for each folder to make it easier for people to download the data packages.
I hope this is ok - you will see the data online as soon as it is synced

**Comment by timlinux** [comment]
Thanks @adissadis and @Charlotte-Morgan - the data seems to be online now:

![screen shot 2016-08-09 at 2 12 38 pm](https://cloud.githubusercontent.com/assets/178003/17515900/72827e42-5e3b-11e6-839e-91090715a77d.png)

I'll close this out - please re-open if there is something more to do.
