### ISSUE TITLE
BUG : The aggregation result not appear (Could not compute)  when using BIG data (Non OSM)

### ISSUE THREAD

**Issue by fredychandra** [inasafe/inasafe#2370]
# Problem

The aggregation result could not compute when running IF Dock using BIG data

![image](https://cloud.githubusercontent.com/assets/6345285/9899903/223b1d24-5c87-11e5-8fb4-cc391a503591.png)
# Data

Hazard    : Polygon, EQ_TTU.shp
Exposure : Infrastructure_WGS84.shp (BIG data)
Aggregate : Village.shp (BPS data)
# Propose Solution

Make the aggregation work and classified the building/infrastructure type into aggregation level
# Related Issue

@samnawi ticket #2369 

cc : @ismailsunni @timlinux @cchristelis

**Comment by timlinux** [comment]
I have an idea of a quick hack that might fix this and related issues when using non-oms data...I'll see if I can fix it this afternoon before 3.2 goes out.

**Comment by timlinux** [comment]
Just a note that we agreed to defer this fix until 3.3

**Comment by timlinux** [comment]
@ismailsunni Please back port to 3.3 if possible.

**Comment by Gustry** [comment]
Is it not related to my postprocessing PR ?

**Comment by samnawi** [comment]
Hi @timlinux @ismailsunni & @Gustry I found something strange in this issue.

When I use the Nagekeo Data :
Hazard --> NGK_Earthquake_Hazard_WGS84
Exposure --> NGK_Infrastructure_WGS84
Aggregation --> NGK_Desa_BPS_WGS84
**Result** --> Fine, working properly with aggregation.

When I use the TTU Data :
Hazard --> TTU_Earthquake_Hazard_WGS84
Exposure --> TTU_Infrastructure_WGS84
Aggregation --> TTU_Villages_BPS_WGS84
**Result** --> InaSAFE can run, but could not compute the aggregation.

Data ---> I'm sorry, I could not upload.
Hi @ismailsunni Would you like to help me upload this data that I've shared with you?

Thank you.

Environment : 
Win 7 64Bit
QGIS 2.8.8

**Comment by ismailsunni** [comment]
Uploaded @samnawi :
[Data-NGK-TTU.zip](https://github.com/inasafe/inasafe/files/261059/Data-NGK-TTU.zip)

**Comment by Gustry** [comment]
The develop branch can now work with "non OSM data" if you use the new values mapping. Maybe you should try again with the develop branch.

**Comment by samnawi** [comment]
Hi @Gustry Yeah... I just try the new value mapping in the develop branch.
As I comment in above https://github.com/inasafe/inasafe/issues/2370#issuecomment-218716666, The result is good when using Nagekeo data, but I still got the problem (Running well without aggregation result) when using TTU data, [Ambon Infrastructure data](https://www.dropbox.com/s/yjhuy2f1c7vhqgf/Ambon%20Infrastructure.zip?dl=0), and [Padang Infrastructure data](https://www.dropbox.com/s/zzpwi1bso3hhyn0/Padang%20Infrastructures.zip?dl=0).

The Padang hazard data could downloaded from [here](http://data.inasafe.org/InaSAFE%203.2%20Data/West%20Sumatera.zip)

Thank you.

**Comment by Gustry** [comment]
I think this ticket has been fixed in InaSAFE v4.
