### ISSUE TITLE
BUG : The roads IF report still truncated

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2373]
@cchristelis Thank's for fixed the issue #2321.
But, I still found the truncated issue that I found in the Flood hazard (both of vector and raster) VS roads.
Maybe it's because there are so many type in here.
![selection_196](https://cloud.githubusercontent.com/assets/8871958/9846131/2ac8fe54-5afa-11e5-92c8-5e16118f7cd6.png)

# Proposed Solution
Fixed it with the paper size.

# CC
@Charlotte-Morgan @fredychandra @timlinux 

Thank you

**Comment by timlinux** [comment]
@ismailsunni Can you check this and close it if resolved already?

**Comment by ismailsunni** [comment]
Hi @samnawi @timlinux 
I think we can close this since our value mapping for the road or structure will limit the number of road/building type.
