### ISSUE TITLE
We need to update references to 'Attribute values' in the docs

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2381]
I found a problem in the defintions.py which refers to value maps incorrectly. To fix it I changed the term to ``Attribute value map`` .

Unfortunately (sorry everyone!) we will need to search and replace this term in the docs :

``Attribute values`` -> ``Attribute value map``

**Comment by Charlotte-Morgan** [comment]
@timlinux - is this still an issue?

**Comment by timlinux** [comment]
@Charlotte-Morgan I need to trawl through the docs and check.

**Comment by timlinux** [comment]
I did a search through the docs for ```Attribute values``` and did not find any references to it. Closing this out.
