### ISSUE TITLE
BUG : Sorting the hazard classification

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2385]
# Problem

Some of the hazard classification in the report, has no consistency order and the wrong order.
# Screenshot

![selection_224](https://cloud.githubusercontent.com/assets/8871958/9954024/d5abb22c-5e0f-11e5-9d65-9007508a6b7c.png)
![selection_227](https://cloud.githubusercontent.com/assets/8871958/9954098/6ece5c8e-5e10-11e5-8e9a-70c71248c69e.png)
![selection_226](https://cloud.githubusercontent.com/assets/8871958/9954033/dcf88db6-5e0f-11e5-9509-575df94ca43b.png)
# Proposed Solution
- For all IF, make the order from the worst on the top.
- Fixed the wrong order.
# CC

@Charlotte-Morgan @fredychandra @timlinux 

Thank you

**Comment by samnawi** [comment]
Hi @ismailsunni , could we re-opened this ticket?
Because, when I, @felix-yew and @ivanbusthomi doing systematic testing for InaSAFE 3.4, we still found the not sequence hazard classification.

**Tsunami Raster VS Buildings**
![image](https://cloud.githubusercontent.com/assets/8871958/15498537/386b38e6-21ca-11e6-9462-62535c4d08a4.png)

**Volcano Point VS Buildings**
![image](https://cloud.githubusercontent.com/assets/8871958/15498606/7fe65750-21ca-11e6-8f9f-40a4c2e230ba.png)

@felix-yew & @ivanbusthomi could you add the table from InaSAFE systematic testing that related to this issue?

Thank You.

**Comment by Gustry** [comment]
@samnawi I made a PR with reordering in buildings IF : https://github.com/inasafe/inasafe/pull/2825 You should have a look.

**Comment by ivanbusthomi** [comment]
@Gustry Ok, I'll have a look.

**Comment by ivanbusthomi** [comment]
Hi @Gustry , I have tried your PR on some IF and cases, and it looks quite good to me. here are some screenshot
* This screenshot related to @samnawi 
![1](https://cloud.githubusercontent.com/assets/7351977/15501220/8bf3140a-21d6-11e6-80ee-cc0b5bbb8ddd.PNG)
and this one:
![3](https://cloud.githubusercontent.com/assets/7351977/15501240/b4d0a374-21d6-11e6-9970-8bf2e960dab5.PNG)
and this one is in the map pdf report
![2](https://cloud.githubusercontent.com/assets/7351977/15501253/bdee7ca6-21d6-11e6-89d8-e5fc92367611.PNG)

* here are the comparison before and after:
![before-after](https://cloud.githubusercontent.com/assets/7351977/15501295/f209df30-21d6-11e6-817d-0c6e54ae27fc.png)

### a few things related to the sequence order
after doing the testing, we noticed that there are some cases that the sequence order is descending from the high class to the lower one,like in the screen shot above. but there are some other cases that the sequence order is ascending from low class to the higher one (for example : low --> medium --> high).
So we had a quick discussion in terms of the consistency regarding this, and we decided that it would be good if it from low class to higher one. Is it possible to make happen?

Do you need me and/or @felix-yew to make a list, which IF result in descending order, and which IF result in ascending order?

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi  - please let the developers know exactly which IF reports need the order to be changed

**Comment by felix-yew** [comment]
Hi @Gustry we have compiled a check list about sequence order. Here is the link

https://drive.google.com/file/d/0B05hpjhYVKxgUGdqUDBxZWx0QUE/view?usp=sharing

Maybe you can make it happy :smile: 

Cc: @Charlotte-Morgan @timlinux @ismailsunni @samnawi @ivanbusthomi

**Comment by Charlotte-Morgan** [comment]
@felix-yew @ivanbusthomi  - that looks great.
As discussed a 'v" means that the report needs fixing and '-' means its already happy.

**Comment by Gustry** [comment]
I made a PR for that issue https://github.com/inasafe/inasafe/pull/2833 but we should wait https://github.com/inasafe/inasafe/pull/2825 to be merged to test.

**Comment by Gustry** [comment]
Thanks for this useful doc @felix-yew. I had some comments where it should be fixed for sure. I didn't check every IF in the document.
For 'v', it could be nice to know if it was the legend or the report, as it's two different places in the code.

I just had a look in every IF for the legend, it should be ok. I made a new PR https://github.com/inasafe/inasafe/pull/2954

**Comment by felix-yew** [comment]
Hi @Gustry 

I have tried InaSAFE 3.5 dev, then I run the tsunami raster vs buildings polygon and find this problem again. See the image below :
In the report table
![image](https://cloud.githubusercontent.com/assets/13621886/17316471/57247bfc-589e-11e6-97f0-86bbd28057c7.png)

In the map
![image](https://cloud.githubusercontent.com/assets/13621886/17316540/1f00f3b2-589f-11e6-94ea-106fbd58134e.png)

Make it happy :smile:

**Comment by Charlotte-Morgan** [comment]
Hi @felix-yew - this issue is known and is being addressed in the standards #2920.  However, this aspect is still in draft and we will not expect developers to implement the standard for this particular point until 3.6

**Comment by timlinux** [comment]
What is the consensus here - are we holding this over to 3.6 where we do a full revision of the legends (based on standards doc)?

**Comment by Gustry** [comment]
This seems to be fixed in version 4.
Please re-open if you want.
