### ISSUE TITLE
Action Checklists in all of IF

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2389]
# Problem
In Roads impacted report, there is no checklist action in the report.

![selection_229](https://cloud.githubusercontent.com/assets/8871958/9955453/69cdd5ec-5e1b-11e5-902e-efc382d92b83.png)

# Proposed Solution
Make the action checklist for the all of IF.
@fredychandra for the next version, maybe you can give the advice about the content of action checklist.

# CC
@Charlotte-Morgan @timlinux 

Thank you.

**Comment by timlinux** [comment]
If you can provide input on what actions you would like to see, we can include this in 3.2.1

**Comment by fredychandra** [comment]
HI @samnawi and @ismailsunni 
Here are two check lists that I propose to use in  Road Impact Analysis Result. We can add more if find something else. 

1.  Try to Identify which potential roads that able to access for evacuation and logistic distribution 
     purpose. What type of transportation reliable to use in that order?
2. Identify what equipment needed to open access of affected roads. Where the resources or  
    equipment to open access affected roads located? who/what department responsible to mobilize? 

Thank you

**Comment by Charlotte-Morgan** [comment]
@fredychandra - thank you for your suggestion
Does this 'plain english version" fit with the other action list styles?
Which roads can be used to evacuate people or to distribute logistics?
What type of vehicles can use the unaffected roads?
What sort of equipment will be needed to reopen roads & where will we get it?

**Comment by fredychandra** [comment]
:+1: Charlotte, this looks fantastic :)

**Comment by ismailsunni** [comment]
Sample result:
<img width="377" alt="screen shot 2015-09-29 at 4 54 58 pm" src="https://cloud.githubusercontent.com/assets/1421861/10161043/81dbc3e8-66cb-11e5-930c-88e49fb7a90f.png">
The branch that I work on it: https://github.com/ismailsunni/inasafe/tree/fix_2388_2389

Please check @samnawi @fredychandra @Charlotte-Morgan

**Comment by ismailsunni** [comment]
Closed in #2421

**Comment by fredychandra** [comment]
HI @ismailsunni 
I just checked again the action list on IF : Flood on Road. I realize that the action 1 & 2 already consist in action no 2 - 5. We should erase no 1 & 2 action list. 

![capture](https://cloud.githubusercontent.com/assets/6345285/11706217/28c25592-9f29-11e5-9739-2c9a0a8cd8b9.PNG)

thank you

**Comment by fredychandra** [comment]
# Problem

We should break down more specific action check list in IF for population and buildings in each hazards. 

Previous check list for IF **Population** only :  
 •	How will warnings be disseminated?
•	How will we reach evacuated people?
•	Are there enough shelters and relief items available for 535 people?
•	If yes, where are they located and how will we distribute them?
•	If no, where can we obtain additional relief items from and how will we transport them to here?

and previous check list for IF **Building** only :  
•	Are the critical facilities still open?
•	Which structures have warning capacity (eg. sirens, speakers, etc.)?
•	Which buildings will be evacuation centres?
•	Where will we locate the operations centre?
•	Where will we locate warehouse and/or distribution centres?
•	Where will the students from the 44 closed schools go to study?

# Proposed Solution

Add more specific action check list. I have listed some point  below that I adopt and modified from Sphere Project Minimum Standard Checklist in Humanitarian Response 2011 edition.
http://www.spherehandbook.org/

**Checklist for Population**

* How will warnings be disseminated?
* What are people’s likely movements? What are the security factors for the affected population and for potential relief responses?
* How will we reach evacuated people?
* Which group or population is most affected? Who are the vulnerable people in the population and why?
* Who are the key people to consult or contact? 
* What kind of food that population consume in daily life? 
* What are the critical non-food items  required by the affected population?
* Are there enough water supply, sanitation, hygiene promotion, food item, shelter, non-food item and medicines and relief items available for ...people?
* If yes, where are they located and how will we distribute them?
* If no, where can we obtain additional relief items from and how will we transport them to here?
* What related existing risks to health, e.g. potential epidemic diseases.? What appropriate health action should be done?

**Checklist for Building**

* Are the water supply facilities still function?
* Are the health centers still operating?
* Are the schools still active?
* Are the other public service accessible?
* Which structures have warning capacity (eg. sirens, speakers, etc.)?
* Which buildings will be evacuation centers?
* Where will we locate the operations center?
* Where will we locate warehouse and/or distribution centers?
* Where will the students from the 44 closed schools go to study?

# CC
@ismailsunni 
@Charlotte-Morgan please check if the english is in appropriate grammar or not? :)
@samnawi

**Comment by Charlotte-Morgan** [comment]
Hi @fredychandra - thank you for reviewing this and the update.
As discussed we tweaked the english and reorganised the lists a bit.
I have made the edits.

please see PR #2513 for changes to default action lists for roads, population and buildings.

@ismailsunni - please review

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
I have checked your PR #2513 it looks good, but we need to update the unit test to make it pass the travis guardian.
I will make another PR that contains your PR.

**Comment by ismailsunni** [comment]
I think we can close this since we have merged @Charlotte-Morgan 's update.
