### ISSUE TITLE
The name of volcano point hazard category

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2390]
# Problem
If we run the volcano point analysis, the name of hazard category is presented as the numeric format. I think it's not good and possibly make the user confuse.

![selection_230](https://cloud.githubusercontent.com/assets/8871958/9955667/116d130c-5e1d-11e5-9cbc-0093abaff2db.png)

# Proposed Solution
make it more nice, like 3 km, 5 km, or radius 3 km, 5km, or something like that.
@Charlotte-Morgan and @fredychandra may be you can give some advices about it.

# CC 
@timlinux 

Thank you.

**Comment by fredychandra** [comment]
Hi @samnawi @Charlotte-Morgan @timlinux @ismailsunni @lucernae 

The heading on the table is Hazard Category should change to be relevance with the content. The content actually say about radius  (distances) from center of volcano (eruption point) that might affect [people; building; road; crops]. 

I think the heading of the table result analysis  can be change into Hazard Buffer.

Thank you,

**Comment by Charlotte-Morgan** [comment]
I think the reason it says category is because it uses a categorical IF and the results try to relate to the words the user would have put into the analysis - 
I would like to review all volcano related terminology together - rather than fix just one at a time

**Comment by ismailsunni** [comment]
Fixed in #2544 (add radius)
