### ISSUE TITLE
UI: reporting papercuts

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2409]
The following are some suggestions for consistent style and terminology in InaSAFE reports:
- [x] numbers are right aligned
- [ ] numbers use a separator (comma)
- [ ] terminology in the report matches terminology in the dock question and impact function. eg how many buildings will be flooded in a flood impact function should also use the words xxx buildings are flooded etc in the report.

a paper component to this ticket has been hand delivered :)
# cc
@fredychandra

**Comment by timlinux** [comment]
@ismailsunni has taken care of this. We will do a further revision for #2920
