### ISSUE TITLE
CSS for geonode obscures toolbar

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2413]
Hi @MariaSolovyeva 

Can you please add some padding to push the content further down in the geocode theme?

If you visit: http://staging.geonode.inasafe.org/maps/new you will see a page like this:

<img width="884" alt="screen shot 2015-09-24 at 09 59 03" src="https://cloud.githubusercontent.com/assets/178003/10064476/f6418fd8-62a2-11e5-8646-62c1c94a60d8.png">

Under the green second level nav menu there is actually a toolbar. You can see this by going to the browser console and doing:

``` javascript

$(".second-menu").hide()
```

Now the page shows the hidden toolbar:

<img width="878" alt="screen shot 2015-09-24 at 10 01 26" src="https://cloud.githubusercontent.com/assets/178003/10064505/4b567970-62a3-11e5-9152-1fea365b9e72.png">
# Proposed solution

Add more padding underneath the second level nav bar. Maybe just for the maps page? I don't know what is best....

**Comment by ismailsunni** [comment]
Hi @MariaSolovyeva 
I remember that you gave me a piece of CSS for this issue to be added in the server. Can you write that code here? And where should I add? I remember you can't modify the files in the server.

**Comment by MariaSolovyeva** [comment]
Hello @ismailsunni ,

Add this piece of code to static.css file:

```
/** Remove the add map page secondary menu **/
body.ext-gecko > .x-panel {
  padding-top: 30px;
}
body.ext-gecko .second-menu {
  display: none;
}
```

**Comment by timlinux** [comment]
@MariaSolovyeva @ismailsunni has applied this change to the server but we still get the problem - can you check on it?

![screen shot 2016-06-22 at 10 52 00](https://cloud.githubusercontent.com/assets/178003/16260379/7dd62de2-3867-11e6-9699-60d4077d329d.png)

**Comment by timlinux** [comment]
@ismailsunni We actuall are missing our InaSAFE branding on the new GeoNode you span up - can you re-instate it?

**Comment by ismailsunni** [comment]
Hmm, I need to check where I left this ticket after feature freeze.

**Comment by gubuntu** [comment]
no longer applicable with GeoNode_QGIS-server

**Comment by gubuntu** [comment]
@ismailsunni please close this.
@lucernae pls create a new issue for reinstating InaSAFE branding in GeoNode.
