### ISSUE TITLE
add Keywords Creation Wizard confirmation dialog 

### ISSUE THREAD

**Issue by tomkralidis** [inasafe/inasafe#2422]
As part of the `Keywords Creation Wizard` workflow, it would be valuable to provide a confirmation dialog once the user completes this wizard to display what was saved and where it was saved to on disk.

**Comment by timlinux** [comment]
@borysiasty Could we add a final page on the wizard that confirms the keywords created (using ```keyword_io.to_message(keywords)```) and dropping the results in a web view would be fine. Also showing the names of the files that were written if applicable would be great.
