### ISSUE TITLE
WEB: Bug - link to realtime

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2423]
the link to realtime map on inasafe.org does not connect to realtime page

#cc
@timlinux

**Comment by ismailsunni** [comment]
cc @MariaSolovyeva

**Comment by timlinux** [comment]
Fixed now: 

![selection_001](https://cloud.githubusercontent.com/assets/178003/12229837/088f4dea-b854-11e5-8bbc-ab663976ad81.png)
