### ISSUE TITLE
There is too much duplication of code in notes and actions

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2426]
Whilst reviewing all the IF's for #2409, I found that the actions and notes contain a lot of duplicate code.

Please look at moving the terms to definitions.py or similar and generally moving duplicated notes items into a central place then just importing them into each module that needs them.

**Comment by Gustry** [comment]
Just to link the issue : https://github.com/inasafe/inasafe/issues/2765

**Comment by timlinux** [comment]
Closing - we will address this in #2987
