### ISSUE TITLE
Wizard code cleanup

### ISSUE THREAD

**Issue by borysiasty** [inasafe/inasafe#2449]
- [x] Refactor into small modular architecture: one class per wizard tab.
- [x] We need to have an easy way to add new IF types e.g. @Samweli 's code does not 'just work' when he added his IF
- [x] Address fragility of tests

**Comment by timlinux** [comment]
@borysiasty could you make some time in the next 2 weeks to look at this please?

**Comment by borysiasty** [comment]
Ok!

Where can I find more details about problems with @Samweli 's code? Is it just the need to update tests in PR #2442 or doesn't it work at all?

**Comment by borysiasty** [comment]
Ok @timlinux !

Where can I find more details about problems with @Samweli 's code? Is it just the need to update tests in PR #2442 or doesn't it work at all?

**Comment by ismailsunni** [comment]
hi @borysiasty @timlinux 
I checked in @Samweli 's PR, all is good. It's working in wizard also.

We only need to add an image/icon for the new exposure type:
![area icon](https://cloud.githubusercontent.com/assets/1421861/11232423/9cca230c-8de5-11e5-8242-44378a3aa782.png)

**Comment by Samweli** [comment]
hi @ismailsunni, i have added an icon for area, you can find it here https://thenounproject.com/term/inland/8685/

**Comment by ismailsunni** [comment]
Hi @Samweli 
Thanks. Actually, if you have already the icon for area, you can add it to InaSAFE by yourself in your PR. You only need to put it under `resources/img/wizard/` and give a proper name. It should be something like `keyword-subcategory-area.svg

**Comment by Samweli** [comment]
Ok, thanks @ismailsunni , i have already done that, here https://github.com/Samweli/inasafe/blob/develop/resources/img/wizard/keyword-subcategory-area.svg

**Comment by ismailsunni** [comment]
Done in #2771
