### ISSUE TITLE
Crash Minidump when try to use InaSAFE keyword editor twice 

### ISSUE THREAD

**Issue by adissadis** [inasafe/inasafe#2467]
# Problem
My qgis crashed when i try to use InaSAFE keyword editor twice

# Description
I use several data from field survey for InaSAFE analysis and when i want to define the keyword for each data, my qgis crashed when i want to define keyword in second time. 

# Platform
InaSAFE 3.2.3 from QGIS repository
Windows 7
QGIS 2.8

# Data used
1. ancaman_banjir (flood hazard)
2. marunda_inasafe (exposure)
3. batas_rt (aggregation)

You can download these data in:
https://drive.google.com/folderview?id=0B3X6jqdE4HueSzFyT0oyc2E0aGc&usp=sharing

# Step to produce this error
1. Load ancaman_banjir, marunda_inasafe, and batas_rt
2. Define keyword for first layer (whether ancaman_banjir, marunda_inasafe, or batas_rt)
3. Define keyword for second layer
4. Minidump crash and QGIS Force Closed

**Comment by adissadis** [comment]
cc: @timlinux

**Comment by ismailsunni** [comment]
Hi @adissadis 
I have merged the fix to the develop, can you confirm it that it's fixed? If so, please close the ticket...

Thanks

**Comment by adissadis** [comment]
Hi @ismailsunni yes it fixed now. Thank you @borysiasty for fixing this.
