### ISSUE TITLE
[Bug] Building type not appear in InaSAFE result

### ISSUE THREAD

**Issue by adissadis** [inasafe/inasafe#2468]
# Problem
My InaSAFE result didn't provide detailed building type eventhough i already select attribute that have building type inside it

# Description
I have several data from field survey. I already define all the data using keyword editor (you need to open qgis several time because it will crashed when you tried to define the second time - issue #2467 ).

For exposure data, i set 'amenity or type' for detailed building type.
![image](https://cloud.githubusercontent.com/assets/2520159/11268058/87b1905c-8ee1-11e5-8b1f-b6d0278043be.png)

When i run InaSAFE, i got 'unknown type' and 'other' not as i expected (breakdown by school, clinic, restaurant, place_of_worship, etc).

![image](https://cloud.githubusercontent.com/assets/2520159/11268069/9c7411d6-8ee1-11e5-951d-309990ad40dd.png)

# Platform
InaSAFE 3.2.3 from QGIS repository
Windows 7
QGIS 2.8

# Data used
1. ancaman_banjir (flood hazard)
2. marunda_inasafe (exposure)
3. batas_rt (aggregation)

You can download these data in:
https://drive.google.com/folderview?id=0B3X6jqdE4HueSzFyT0oyc2E0aGc&usp=sharing

**Comment by samnawi** [comment]
I think it similar with issue #2089

**Comment by Gustry** [comment]
I was trying to debug this issue, but I noticed this is not a bug. It's a feature which has been hard coded in the plugin.
https://github.com/inasafe/inasafe/blob/develop/safe/impact_reports/building_exposure_report_mixin.py#L363
The plugin  will aggregate every impacted object if there are less than 25 into the "Other" group.

We should maybe inform the user, or better, the user should be able to set this value in the settings.

CC : @timlinux @ismailsunni

**Comment by ismailsunni** [comment]
Thanks @Gustry 
Ah yes, the 25 threshold. I just remembered that after you mentioned it.
And I agree with the idea to enable the user set the value in the setting.

What do you think @timlinux ?

**Comment by Gustry** [comment]
FYI, ``building_exposure_report_mixin`` seems to be the only with the threshold.

**Comment by adissadis** [comment]
+1 for enable the user set the value in setting

Because if the user only analyze small area, they might not get the detailed result if the object inside the area is less than 25.

**Comment by ismailsunni** [comment]
@Gustry can you proceed to create the option for setting the value of the threshold?

**Comment by Gustry** [comment]
@ismailsunni Can you have a look to the PR ?
It's not finished. I have one issue to display the parameter : 
 - The minimum value is set to 1 in the source code. But in the GUI, it is set to -1.
 - We can't edit the value in the GUI.
 - The display is not good when we collapse the settings.
![qgis1](https://cloud.githubusercontent.com/assets/1609292/12262483/7fe4127a-b928-11e5-8d1d-0cf8da3d579f.png)
![qgis2](https://cloud.githubusercontent.com/assets/1609292/12262484/8054c25e-b928-11e5-8723-283289b786ed.png)
I'm learning how to use Parameters in InaSAFE, did I miss something ? Thanks

**Comment by ismailsunni** [comment]
Hi @Gustry 
I am not sure what's the problem. But, if you set the maximum value explicitly (e.g. `threshold.maximum_allowed_value = 100`), it will fix the first two problem in your comment. I don't understand since by default it will be set to `sys.maxint`.

> The display is not good when we collapse the settings. 

I am not sure I understand about this. 

Thanks @Gustry
