### ISSUE TITLE
RFC: do we need an OSM downloader query specifically for Jakarta Flood data

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2469]
# Problem
There are some great flood related data in OSM we should make it easy for people to use

# Proposed solution
I propose that we create some specific OSM downloader queries to download flood hazard data and evacuation centers for Jakarta.  These data can then be used as 'real world' data to test flood evacuation functions and to build smarter flood impact functions.

* Evacuation Centers.
Overpass turbo query is evacuation_center=yes
![image](https://cloud.githubusercontent.com/assets/5743135/11268778/4b7bca36-8ee5-11e5-91b9-f8ecdbfb94e6.png)
retain only polygons (current data)
these data include attributes on the capacity, water source and number of toilets available
more advice on fields to retain and filtering to create derived attributes later

* Flood prone areas
Overpass turbo query is flood_prone=yes
admin_level 8 and 9 have attributes for flood depth and duration
![image](https://cloud.githubusercontent.com/assets/5743135/11268996/b1eafb06-8ee6-11e5-90e1-f7d6db69e542.png)
more advice on fields to retain and filtering to create derived attributes later

# Institutional outcomes
By making better use of these data in maps and analyses, we will also encourage their maintenance.

# cc
@Gustry @timlinux @iyan31 @fredychandra @samnawi

**Comment by timlinux** [comment]
@Charlotte-Morgan can you put the raw overpass queries in here as text too please?

**Comment by Charlotte-Morgan** [comment]
I hope this is what you want

evacuation_center=yes
``
/*
This has been generated by the overpass-turbo wizard.
The original search was:
“evacuation_center=yes”
*/
[out:json][timeout:25];
// gather results
(
  // query part for: “evacuation_center=yes”
  node["evacuation_center"="yes"]({{bbox}});
  way["evacuation_center"="yes"]({{bbox}});
  relation["evacuation_center"="yes"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
``

and 

flood_prone= yes
``
/*
This has been generated by the overpass-turbo wizard.
The original search was:
“flood_prone=yes”
*/
[out:json][timeout:25];
// gather results
(
  // query part for: “flood_prone=yes”
  node["flood_prone"="yes"]({{bbox}});
  way["flood_prone"="yes"]({{bbox}});
  relation["flood_prone"="yes"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
``

**Comment by timlinux** [comment]
Thanks @Charlotte-Morgan - @Gustry this will be a great first task for you when you start work on the 1st!

**Comment by Gustry** [comment]
There are two PR : 
* inasafe : https://github.com/inasafe/inasafe/pull/2501
* osm-reporter : https://github.com/kartoza/osm-reporter/pull/66

**Comment by Charlotte-Morgan** [comment]
noting this was an RFC and no one has answered the question raised - it was not a feature request

**Comment by Gustry** [comment]
Sorry @Charlotte-Morgan, I've followed [Tim's comment above](https://github.com/inasafe/inasafe/issues/2469#issuecomment-159516559).
This RFC has been implemented. Can we close the ticket ?

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry,
Thank you for developing this new feature and merging to develop.
I think there may need to be some tweaking / refinement regarding fields we retain and if we should modify the truncated field names.

@iyan31 @adissadis - what do you think about tweaking the field names?

**Comment by adissadis** [comment]
I agree with you about tweaking the field name. In case if the attribute not showed as `flood_prone=yes` but instead is showed as `flood_area=yes' or else. Is that what you mean Charlotte?

**Comment by Charlotte-Morgan** [comment]
hi @adissadis - that sounds like you want to tweak the query?
I was mostly thinking of changing the field names that have been truncated in the shape file format after the query has run and the data are saved. There may also be some fields we can drop.

**Comment by adissadis** [comment]
Ok i got what you mean @Charlotte-Morgan. Lot of column with `null` field beside flood_prone coloum. If we only need `flood_prone` column, maybe we can drop some that not related such as fire_hazard.

**Comment by Gustry** [comment]
No problem to clean the attribute table. Tell me which one you want to drop ;-)

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry 
For the evacuation-centers; may I suggest that we retain all fields in the data but change some of the field names to cope with the truncated fields. My suggestion is to replace the name in the Attribute Name column with the field name in the proposed name column. 
![image](https://cloud.githubusercontent.com/assets/5743135/12576396/f5c4d51a-c445-11e5-91cf-6292b8105dd9.png)

@samnawi @adissadis @iyan31 please comment or make better suggestions on how to deal with field names.

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry - here is a suggestion for the floodprone data from the OSM downloader
same as above; please retain all fields and change the attribute name to that in the proposed name field.  I have no idea what SEND is - someone please fix this for me

![image](https://cloud.githubusercontent.com/assets/5743135/12576543/0bf9f5b2-c447-11e5-8008-8e65d2217e16.png)

@iyan31 or @adissadis - maybe you are more familiar with these data and can explain the SEND field

**Comment by iyan31** [comment]
I agree that the proposed name is simpler. This preset is specifically used during RT Mapping in 2014-2015. Flood send is what Indonesians usually mean as "banjir kiriman" meaning that the flood is originated from other place and they got the impact from it. For example when the flood happen in the upstream or from the higher place and some part of Jakarta also affected.

**Comment by Gustry** [comment]
I've updated the attribute table according to the table above. So I think I can close this issue.

**Comment by Charlotte-Morgan** [comment]
thanks @Gustry
