### ISSUE TITLE
RFC: A better approach to clipping, aggregation and post-processing

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2473]
# Status

This RFC is in draft
# Problem

Right now there are a number of problems with our current architecture:
- Clipping of datasets happens externally to the impact function, meaning that client classes need to 'know' too much about how to prepare data for impact functions.
- We have dual concepts of **analysis area** and **aggregation area** which may be in conflict. For example when the analysis area is contained by the aggregation area, does it make sense to clip the aggregation area to the extents of the analysis area?
- During report production we have seeming inconsistencies between the total counts for the analysis extents and the sum of the counts within the aggregation areas. This is because the analysis extent may include exposure data that is external to any aggregation area.
- The post-processing and aggregation logic in InaSAFE is convoluted and hard to trace and maintain. It also suffers from similar shortcomings to the aggregation - the proper execution of post-processing happens externally outside of the context of the impact function. This wastes CPU cycles as data is revisited _post-hoc_ and defers a lot of overhead and complexity to client classes.
# Analysis

It is useful to first understand the generalised process of what happens during analysis under our current regime:
1. User sets analysis extent behaviour (user defined extents, intersection of layers, etc.)
2. User sets aggregation extent behaviour (current view frame, aggregation layer)
3. Hazard and exposure layers are clipped to the analysis extent
4. Impact function is run to generate an impact layer
5. Summary statistics are computed for the impact layer (which coincides with the aggregation area extents)
6. Aggregation is performed by iterating over each aggregation area, creating a subset of impacted features and then performing post-processor statistics (age ratio, gender ratio etc. analysis)
7. Summary report is produced which includes the _whole area_ statistics and the _by aggregation area_ statistics

In the final steps we basically revisit data we already had available during IF execution and in step 5 the stats generated do not coincide with only the aggregation areas.

Conceptually the process looks like this:

![1](https://cloud.githubusercontent.com/assets/178003/11361457/64920d0a-9296-11e5-902d-665307a60b2a.png)
Initial project with analysis area, aggregation areas, hazard (floods) and exposure (roads).

![2](https://cloud.githubusercontent.com/assets/178003/11361494/97e83972-9296-11e5-9df9-70b67184afd5.png)
Exposure and aggregation are clipped to the analysis extents of the analysis

![3](https://cloud.githubusercontent.com/assets/178003/11361645/74e56fa2-9297-11e5-93a7-b905615e9ea4.png)
The exposure is intersected with the hazard layer (to indicate which road segments are flooded) and with the aggregation layer (to indicate which area each flooded segment falls in).
# Proposed Solution

The proposed improved workflow will look more like this:
## For vector polygon hazard on linear exposure features:

Again we have the same starting scenario:

![4](https://cloud.githubusercontent.com/assets/178003/11361719/e6574b9c-9297-11e5-9214-c5b34a192d1d.png)
1. First of all, **analysis extents** will only be used when there is no **aggregation layer**.
2. **Intersect roads with aggregation areas** - this will split each road where it crosses an aggregation area boundary. Any parts that extend beyond the aggregation area will be discarded. Manual equivalent: `Vector -> GeoProcessing Tools -> Intersection` ![5](https://cloud.githubusercontent.com/assets/178003/11362935/716f2dc4-929f-11e5-9713-7fdd9a9ae39b.png)
3. **Intersect floods with aggregation areas** - this will split any polygons that cover more than one aggregation area and assign the minor parts the attributes of the parent flood. Any parts that do not overlap with an aggregation area are discarded.  Manual equivalent: `Vector -> GeoProcessing Tools -> Intersection` ![6](https://cloud.githubusercontent.com/assets/178003/11362894/32de5350-929f-11e5-8d7e-e5cbf2caa474.png)
4. **Convert flood polygons to lines** - we will use the resulting layer to intersect the roads in the step below. Manual equivalent: `Vector -> Geometry Tools -> Polygons to lines`.  Shown as blue dotted lines below. ![7](https://cloud.githubusercontent.com/assets/178003/11364392/d6447c32-92a8-11e5-81d8-189b00121ac2.png)
5. **Split roads with flood lines** - this will further split the product of step 2 above such that no road crosses any flood polygon border. Manual equivalent: `Processing Toolbox -> QGIS Algorithms -> Vector Overlay Tools -> Split lines with lines`. ![8](https://cloud.githubusercontent.com/assets/178003/11366157/3c8afbbe-92b4-11e5-8b35-368dda6478b1.png)

This process can be described as a QGIS processing model:

![selection_007](https://cloud.githubusercontent.com/assets/178003/11366729/d0a623c0-92b7-11e5-87df-e5ec35f3cc2e.png)
- Purple items are inputs
- White items are processing steps
- Blue items are outputs

The following is the model itself. Save it in your `<home>/.qgis2/processing/models folder` as `inasafe-flood-on-roads-with-aggregation.model`.

`cat inasafe-flood-on-roads-with-aggregation.model`

```
{
    "values": {
        "inputs": {
            "VECTORLAYER_AGGREGATION": {
                "values": {
                    "pos": {
                        "values": {
                            "y": 61.0, 
                            "x": 531.0
                        }, 
                        "class": "point"
                    }, 
                    "param": {
                        "values": {
                            "isAdvanced": false, 
                            "name": "VECTORLAYER_AGGREGATION", 
                            "shapetype": [
                                2
                            ], 
                            "value": null, 
                            "exported": null, 
                            "hidden": false, 
                            "optional": false, 
                            "description": "Aggregation"
                        }, 
                        "class": "processing.core.parameters.ParameterVector"
                    }
                }, 
                "class": "processing.modeler.ModelerAlgorithm.ModelerParameter"
            }, 
            "VECTORLAYER_ROADS": {
                "values": {
                    "pos": {
                        "values": {
                            "y": 60.0, 
                            "x": 120.0
                        }, 
                        "class": "point"
                    }, 
                    "param": {
                        "values": {
                            "isAdvanced": false, 
                            "name": "VECTORLAYER_ROADS", 
                            "shapetype": [
                                1
                            ], 
                            "value": null, 
                            "exported": null, 
                            "hidden": false, 
                            "optional": false, 
                            "description": "Roads"
                        }, 
                        "class": "processing.core.parameters.ParameterVector"
                    }
                }, 
                "class": "processing.modeler.ModelerAlgorithm.ModelerParameter"
            }, 
            "VECTORLAYER_FLOODS": {
                "values": {
                    "pos": {
                        "values": {
                            "y": 52.0, 
                            "x": 871.0
                        }, 
                        "class": "point"
                    }, 
                    "param": {
                        "values": {
                            "isAdvanced": false, 
                            "name": "VECTORLAYER_FLOODS", 
                            "shapetype": [
                                2
                            ], 
                            "value": null, 
                            "exported": null, 
                            "hidden": false, 
                            "optional": false, 
                            "description": "Floods"
                        }, 
                        "class": "processing.core.parameters.ParameterVector"
                    }
                }, 
                "class": "processing.modeler.ModelerAlgorithm.ModelerParameter"
            }
        }, 
        "helpContent": {}, 
        "group": "InaSAFE", 
        "name": "Flood on roads with Aggregation", 
        "algs": {
            "QGISINTERSECTION_1": {
                "values": {
                    "name": "QGISINTERSECTION_1", 
                    "paramsFolded": true, 
                    "outputs": {}, 
                    "outputsFolded": true, 
                    "pos": {
                        "values": {
                            "y": 205.0, 
                            "x": 357.0
                        }, 
                        "class": "point"
                    }, 
                    "dependencies": [], 
                    "params": {
                        "INPUT2": {
                            "values": {
                                "name": "VECTORLAYER_AGGREGATION"
                            }, 
                            "class": "processing.modeler.ModelerAlgorithm.ValueFromInput"
                        }, 
                        "INPUT": {
                            "values": {
                                "name": "VECTORLAYER_ROADS"
                            }, 
                            "class": "processing.modeler.ModelerAlgorithm.ValueFromInput"
                        }
                    }, 
                    "active": true, 
                    "consoleName": "qgis:intersection", 
                    "description": "Intersect roads with aggregation"
                }, 
                "class": "processing.modeler.ModelerAlgorithm.Algorithm"
            }, 
            "QGISINTERSECTION_2": {
                "values": {
                    "name": "QGISINTERSECTION_2", 
                    "paramsFolded": true, 
                    "outputs": {
                        "OUTPUT": {
                            "values": {
                                "description": "flood-agg-intersect", 
                                "pos": {
                                    "values": {
                                        "y": 239.0, 
                                        "x": 1018.0
                                    }, 
                                    "class": "point"
                                }
                            }, 
                            "class": "processing.modeler.ModelerAlgorithm.ModelerOutput"
                        }
                    }, 
                    "outputsFolded": true, 
                    "pos": {
                        "values": {
                            "y": 194.0, 
                            "x": 818.0
                        }, 
                        "class": "point"
                    }, 
                    "dependencies": [], 
                    "params": {
                        "INPUT2": {
                            "values": {
                                "name": "VECTORLAYER_AGGREGATION"
                            }, 
                            "class": "processing.modeler.ModelerAlgorithm.ValueFromInput"
                        }, 
                        "INPUT": {
                            "values": {
                                "name": "VECTORLAYER_FLOODS"
                            }, 
                            "class": "processing.modeler.ModelerAlgorithm.ValueFromInput"
                        }
                    }, 
                    "active": true, 
                    "consoleName": "qgis:intersection", 
                    "description": "Intersect flood with aggregation"
                }, 
                "class": "processing.modeler.ModelerAlgorithm.Algorithm"
            }, 
            "QGISPOLYGONSTOLINES_1": {
                "values": {
                    "name": "QGISPOLYGONSTOLINES_1", 
                    "paramsFolded": true, 
                    "outputs": {}, 
                    "outputsFolded": true, 
                    "pos": {
                        "values": {
                            "y": 363.0, 
                            "x": 781.0
                        }, 
                        "class": "point"
                    }, 
                    "dependencies": [], 
                    "params": {
                        "INPUT": {
                            "values": {
                                "alg": "QGISINTERSECTION_2", 
                                "output": "OUTPUT"
                            }, 
                            "class": "processing.modeler.ModelerAlgorithm.ValueFromOutput"
                        }
                    }, 
                    "active": true, 
                    "consoleName": "qgis:polygonstolines", 
                    "description": "Flood polygons to lines"
                }, 
                "class": "processing.modeler.ModelerAlgorithm.Algorithm"
            }, 
            "QGISSPLITLINESWITHLINES_1": {
                "values": {
                    "name": "QGISSPLITLINESWITHLINES_1", 
                    "paramsFolded": true, 
                    "outputs": {
                        "OUTPUT": {
                            "values": {
                                "description": "roads-flood-intersect", 
                                "pos": {
                                    "values": {
                                        "y": 563.0, 
                                        "x": 799.0
                                    }, 
                                    "class": "point"
                                }
                            }, 
                            "class": "processing.modeler.ModelerAlgorithm.ModelerOutput"
                        }
                    }, 
                    "outputsFolded": true, 
                    "pos": {
                        "values": {
                            "y": 518.0, 
                            "x": 599.0
                        }, 
                        "class": "point"
                    }, 
                    "dependencies": [], 
                    "params": {
                        "INPUT_B": {
                            "values": {
                                "alg": "QGISPOLYGONSTOLINES_1", 
                                "output": "OUTPUT"
                            }, 
                            "class": "processing.modeler.ModelerAlgorithm.ValueFromOutput"
                        }, 
                        "INPUT_A": {
                            "values": {
                                "alg": "QGISINTERSECTION_1", 
                                "output": "OUTPUT"
                            }, 
                            "class": "processing.modeler.ModelerAlgorithm.ValueFromOutput"
                        }
                    }, 
                    "active": true, 
                    "consoleName": "qgis:splitlineswithlines", 
                    "description": "Split roads with flood lines"
                }, 
                "class": "processing.modeler.ModelerAlgorithm.Algorithm"
            }
        }
    }, 
    "class": "processing.modeler.ModelerAlgorithm.ModelerAlgorithm"
}
```

When installed it will appear as a model in the processing toolbox under `Models -> InaSAFE -> Flood on roads with aggregation` as per the image below. Double clicking on the model will open the run dialog as shown below:

![selection_006](https://cloud.githubusercontent.com/assets/178003/11366700/99399700-92b7-11e5-9bf4-ce784530f979.png)
## For vector polygon hazard on polygon exposure features:

In this case we will use building polygon footprints impacted by a flood polygon to illustrate. We have this starting scenario:

![b1](https://cloud.githubusercontent.com/assets/178003/11367461/6fc6ffac-92bc-11e5-9a1f-7b8a3f22fa99.png)
1. First of all, **analysis extents** will **not** be used as there is an **aggregation layer**.
2. **Extract buildings within aggregation areas** - this will select each building where it wholly or partially intersects an aggregation area boundary. Any parts that extend beyond the aggregation area will be deselected. Manual equivalent: `Processing Toolbox -> QGIS Algorithms -> Vector Selection Tools -> Extract By Location`. The following operators should be used:  ![extract by location_011](https://cloud.githubusercontent.com/assets/178003/11367932/93bab932-92bf-11e5-8628-289741d9b56b.png)
   - intersects
   - overlaps
   - within
     ![b4](https://cloud.githubusercontent.com/assets/178003/11368004/f11cdc7c-92bf-11e5-8b45-ca790f999b3d.png)
3. **Intersect floods with aggregation areas** - this will split any polygons that cover more than one aggregation area and assign the minor parts the attributes of the parent flood. Any parts that do not overlap with an aggregation area are discarded.  Manual equivalent: `Vector -> GeoProcessing Tools -> Intersection` ![b3](https://cloud.githubusercontent.com/assets/178003/11367814/dfa1ef6a-92be-11e5-84c9-56ce5714a518.png)

This process can be described as a QGIS processing model:
- Purple items are inputs
- White items are processing steps
- Blue items are outputs

The following is the model itself. Save it in your `<home>/.qgis2/processing/models folder` as `inasafe-flood-on-buildings-with-aggregation.model`.

`cat inasafe-flood-on-buildings-with-aggregation.model`

```
{
    "values": {
        "inputs": {
            "VECTORLAYER_AGGREGATION": {
                "values": {
                    "pos": {
                        "values": {
                            "y": 61.0, 
                            "x": 531.0
                        }, 
                        "class": "point"
                    }, 
                    "param": {
                        "values": {
                            "isAdvanced": false, 
                            "name": "VECTORLAYER_AGGREGATION", 
                            "shapetype": [
                                2
                            ], 
                            "value": null, 
                            "exported": null, 
                            "hidden": false, 
                            "optional": false, 
                            "description": "Aggregation"
                        }, 
                        "class": "processing.core.parameters.ParameterVector"
                    }
                }, 
                "class": "processing.modeler.ModelerAlgorithm.ModelerParameter"
            }, 
            "VECTORLAYER_FLOODS": {
                "values": {
                    "pos": {
                        "values": {
                            "y": 63.0, 
                            "x": 875.0
                        }, 
                        "class": "point"
                    }, 
                    "param": {
                        "values": {
                            "isAdvanced": false, 
                            "name": "VECTORLAYER_FLOODS", 
                            "shapetype": [
                                2
                            ], 
                            "value": null, 
                            "exported": null, 
                            "hidden": false, 
                            "optional": false, 
                            "description": "Floods"
                        }, 
                        "class": "processing.core.parameters.ParameterVector"
                    }
                }, 
                "class": "processing.modeler.ModelerAlgorithm.ModelerParameter"
            }, 
            "VECTORLAYER_BUILDINGS": {
                "values": {
                    "pos": {
                        "values": {
                            "y": 59.0, 
                            "x": 222.0
                        }, 
                        "class": "point"
                    }, 
                    "param": {
                        "values": {
                            "isAdvanced": false, 
                            "name": "VECTORLAYER_BUILDINGS", 
                            "shapetype": [
                                2
                            ], 
                            "value": null, 
                            "exported": null, 
                            "hidden": false, 
                            "optional": false, 
                            "description": "Buildings"
                        }, 
                        "class": "processing.core.parameters.ParameterVector"
                    }
                }, 
                "class": "processing.modeler.ModelerAlgorithm.ModelerParameter"
            }
        }, 
        "helpContent": {}, 
        "group": "InaSAFE", 
        "name": "Flood on buildings with aggregation", 
        "algs": {
            "QGISEXTRACTBYLOCATION_1": {
                "values": {
                    "name": "QGISEXTRACTBYLOCATION_1", 
                    "paramsFolded": true, 
                    "outputs": {
                        "OUTPUT": {
                            "values": {
                                "description": "buildings-in-aggregation", 
                                "pos": {
                                    "values": {
                                        "y": 476.0, 
                                        "x": 491.0
                                    }, 
                                    "class": "point"
                                }
                            }, 
                            "class": "processing.modeler.ModelerAlgorithm.ModelerOutput"
                        }
                    }, 
                    "outputsFolded": true, 
                    "pos": {
                        "values": {
                            "y": 360.0, 
                            "x": 488.0
                        }, 
                        "class": "point"
                    }, 
                    "dependencies": [], 
                    "params": {
                        "INPUT": {
                            "values": {
                                "name": "VECTORLAYER_BUILDINGS"
                            }, 
                            "class": "processing.modeler.ModelerAlgorithm.ValueFromInput"
                        }, 
                        "PREDICATE": [
                            "intersects", 
                            "touches", 
                            "overlaps"
                        ], 
                        "INTERSECT": {
                            "values": {
                                "name": "VECTORLAYER_AGGREGATION"
                            }, 
                            "class": "processing.modeler.ModelerAlgorithm.ValueFromInput"
                        }
                    }, 
                    "active": true, 
                    "consoleName": "qgis:extractbylocation", 
                    "description": "Extract by location"
                }, 
                "class": "processing.modeler.ModelerAlgorithm.Algorithm"
            }, 
            "QGISINTERSECTION_2": {
                "values": {
                    "name": "QGISINTERSECTION_2", 
                    "paramsFolded": true, 
                    "outputs": {
                        "OUTPUT": {
                            "values": {
                                "description": "flood-agg-intersect", 
                                "pos": {
                                    "values": {
                                        "y": 359.0, 
                                        "x": 872.0
                                    }, 
                                    "class": "point"
                                }
                            }, 
                            "class": "processing.modeler.ModelerAlgorithm.ModelerOutput"
                        }
                    }, 
                    "outputsFolded": true, 
                    "pos": {
                        "values": {
                            "y": 194.0, 
                            "x": 818.0
                        }, 
                        "class": "point"
                    }, 
                    "dependencies": [], 
                    "params": {
                        "INPUT2": {
                            "values": {
                                "name": "VECTORLAYER_AGGREGATION"
                            }, 
                            "class": "processing.modeler.ModelerAlgorithm.ValueFromInput"
                        }, 
                        "INPUT": {
                            "values": {
                                "name": "VECTORLAYER_FLOODS"
                            }, 
                            "class": "processing.modeler.ModelerAlgorithm.ValueFromInput"
                        }
                    }, 
                    "active": true, 
                    "consoleName": "qgis:intersection", 
                    "description": "Intersect flood with aggregation"
                }, 
                "class": "processing.modeler.ModelerAlgorithm.Algorithm"
            }
        }
    }, 
    "class": "processing.modeler.ModelerAlgorithm.ModelerAlgorithm"
}
```

When installed it will appear as a model in the processing toolbox under `Models -> InaSAFE -> Flood on buildings with aggregation` as per the image below. Double clicking on the model will open the run dialog as shown below:
## For raster hazard on polygon exposure features:

In this case we will use building polygon footprints impacted by a flood raster to illustrate. We have this starting scenario:

![r1](https://cloud.githubusercontent.com/assets/178003/11368900/e90ff3ac-92c4-11e5-85b3-96e650aa9712.png)

In the underlying flood raster shown above, the orange and green areas represent floods of different depths, whilst the black area represents `no data`.
1. First of all, **analysis extents** will **not** be used as there is an **aggregation layer**.
2. **Extract buildings within aggregation areas** - this will select each building where it wholly or partially intersects an aggregation area boundary. Any parts that extend beyond the aggregation area will be deselected. Manual equivalent: `Processing Toolbox -> QGIS Algorithms -> Vector Selection Tools -> Extract By Location`. The following operators should be used:  ![extract by location_011](https://cloud.githubusercontent.com/assets/178003/11367932/93bab932-92bf-11e5-8628-289741d9b56b.png)
   - intersects
   - overlaps
   - within
     ![b4](https://cloud.githubusercontent.com/assets/178003/11368004/f11cdc7c-92bf-11e5-8b45-ca790f999b3d.png)
3. **Intersect flood raster with aggregation areas** - this will clip the raster extents to not exceed the extents of the aggregation area (within pixel size limits). Any parts of the raster that do not overlap with an aggregation area but are within its extents are set to `no data`.  Manual equivalent: `Processing Toolbox -> GDAL/OGR -> [GDAL] Extraction -> Clip raster by mask layer`. Use `flood` as input layer and and `aggregation`. ![clip raster by mask layer_012](https://cloud.githubusercontent.com/assets/178003/11369386/3da695a4-92c7-11e5-81ec-1a9e4aebf719.png) which will produce: ![r2](https://cloud.githubusercontent.com/assets/178003/11369393/4c98a58e-92c7-11e5-8499-675dd2574538.png)
4. **Assign zonal statistics to each building** - this will 

This process can be described as a QGIS processing model:
- Purple items are inputs
- White items are processing steps
- Blue items are outputs

The following is the model itself. Save it in your `<home>/.qgis2/processing/models folder` as `inasafe-flood-on-buildings-with-aggregation.model`.

`cat inasafe-raster-flood-on-buildings-with-aggregation.model`

```
```

When installed it will appear as a model in the processing toolbox under `Models -> InaSAFE -> Flood on buildings with aggregation` as per the image below. Double clicking on the model will open the run dialog as shown below:
# Expected Outcome
# CC

**Comment by Charlotte-Morgan** [comment]
Hi Tim,

Lets get lots of thinking and input on this one. I've picked a shortlist of likely contributors. I hope I have missed some people.
# CC
@charlotte-morgan @samnawi @vdepardy @maning @assefay

**Comment by timlinux** [comment]
![imag3606](https://cloud.githubusercontent.com/assets/178003/12974640/33e89230-d0be-11e5-90d4-7d3ee79b56b2.jpg)

This was I brain storming session I had with myself :-)

**Comment by timlinux** [comment]
haha with wifi password included free :-)

**Comment by Gustry** [comment]
Clipping using Processing for flood on buildings (using flood classes) : https://github.com/Gustry/inasafe/tree/processing

You can make some non-rectangular analysis if you use an aggregation layer. You can use some selected features for the area. Check `Use only selected features` in the processing settings.

**Comment by timlinux** [comment]
In our discussions with @wonder-sk he expressed doubts about using processing yet (proposing we wait a year or two for the processing framework to mature). I think we can take the approach of writing our own basic clipping functions when we refactor for the 7 IF base classes and do this work inline in our IF's. I am moving this to milestone 3.6 because for 3.5 we rather want to focus on polishing what we have.

**Comment by Gustry** [comment]
We can now close this ticket with inasafe v4.
