### ISSUE TITLE
Create offline installer for InaSAFE

### ISSUE THREAD

**Issue by vdeparday** [inasafe/inasafe#2474]
It would be great to create an offline installer for InaSAFE. Most workshops we have done don't have the Internet capacity to enable 20 to 30 people to download InaSAFE then we resort to the manual install. However, for newcomers it is sometimes hard to do as the folder is different on all computers (you have to rename the folder to inasafe, etc...) so we often have to do every computer one by one. Couldn't we create a simple .exe (or .bat) that finds the right folder and copies the content there. It is simple but it would make facilitation a lot easier. Thoughts?

**Comment by timlinux** [comment]
Hmm Interesting @vdeparday ...I think we could come up with something - just for windows right? And was your thinking to bundle just the plugin in the installer of a full QGIS + data + plugin?

I normally just take a zip file of the plugin with me and pass it around on a memory stick for those that can't access the internet.

**Comment by vdeparday** [comment]
I meant only the plugin. Windows only would be fine. Yes, we do that too, but since the users folder is different for everyone and also different depending on the laptop brand, it can get quite confusing for users and if you have a large room, you can easily loose 30min or more very quickly. And also, it gives the wrong feeling across that this is hard to install.

**Comment by emirhartato** [comment]
+1 for @vdeparday idea. Windows version is enough as most people uses Windows in the workshop.

**Comment by timlinux** [comment]
@vdeparday OK its clear thanks - and thanks @emirhartato for your input. I think the simplest might be to make an NSIS installer automatically whenever I run make release and then we post it on the InaSAFE.org web site together with the release.

**Comment by timlinux** [comment]
Ok this is done - see https://github.com/inasafe/inasafe/releases/tag/version-3_2_4 (where you can download the installer) and https://github.com/inasafe/inasafe/pull/2505 for the changes related to this.
