### ISSUE TITLE
Realtime for flood

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#2476]
Create code for flood realtime processor.
(Spec may change)
# Specification
- [x] Get flood hazard from PetaJakarta (API may change)
- [x] Convert hazard data to InaSAFE Hazard from PetaJakarta
- [x] Get population data for Jakarta and assign keywords (Population data may change)
- [x] Process impact report/layer
- [x] Generate PDF Report and Map (Indonesian, and English)
- [x] Send impact layer to InaSAFE Django Realtime
- [x] Send PDF report and map to InaSAFE Django Realtime
- [x] extract impact layer and save impact data and boundaries in InaSAFE Django Realtime
- [ ] Accomodate ad hoc and on demand report generation

**Comment by timlinux** [comment]
@lucernae Can we close this off? I see you still have one todo list item...
