### ISSUE TITLE
Extra Keywords Step is Missing in Wizard

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#2485]
Problem
-----------

Previously, we have this extra keyword step in wizard for example set the name attribute in volcano IF. I found that this step is missing when I want to check @Samweli 's PR #2442. We need to take it back since it's an important thing for the wizard.

For bug reproduction, just use wizard with any volcano IF. It will not ask you about the extra keywords.

cc @borysiasty @timlinux

**Comment by ismailsunni** [comment]
This is invalid. The additional keywords step indeed not showing up in IFCW, since it shows up in keywords wizard.

Have a good day :D

**Comment by borysiasty** [comment]
Exactly, just started writing the same :)

**Comment by Charlotte-Morgan** [comment]
yay - everything is working well
