### ISSUE TITLE
Prepare Raster Exposure Population of Jakarta (Jakarta Clipped from World Population)

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#2497]
Right now, I'm using Population Raster from Realtime Shake and clipped it with Jakarta's boundary.

@Charlotte-Morgan @samnawi just inform me if you want to update/check/change the layer

<img width="666" alt="screen shot 2015-12-03 at 11 17 55" src="https://cloud.githubusercontent.com/assets/831865/11551828/9c8d4402-99af-11e5-9b89-cc50b9283e3c.png">

**Comment by samnawi** [comment]
Hi @lucernae 
I still on progress to prepare the population data in vector type (As in the previous discussion, we will use the population vector data first, then use the wordl pop as 2nd plan). 
I've been sent the sample to your email.

**Comment by lucernae** [comment]
@samnawi awesome dude! I will try it today.

**Comment by samnawi** [comment]
But it still for central jakarta (as sample that we get from BPBD DKI)

**Comment by timlinux** [comment]
Closing as this issue has been moved to the dedicated realtime repo.
