### ISSUE TITLE
Map template for Jakarta Flood Realtime

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2507]
As the discuss with @Charlotte-Morgan and @lucernae, I'm in charge to help make a map template for Jakarta Flood Realtime.

In my perspective, if this map will used by BPBD DKI Jakarta to support their report, I suggest to produce one map that include information about : 
- Depth
- Population
- Flood gate status --> just a point to show the location and status (using color maybe)

But, I still confuse about the content of the map, especially the symbology for depth and population impacted in one map, or we just show one of them?

Please check in this picture. I try to compile from the current BPBD DKI flood map and InaSAFE template.
![peta realtime 1](https://cloud.githubusercontent.com/assets/8871958/11622737/74b8ee56-9cfa-11e5-84cb-66d27880654f.jpeg)

And this is the current map, as a comparison.
![peta](http://bpbd.jakarta.go.id/assets/media/flood/banjir-150210-001.jpg)

Please give the feedback for this map.

Thank you.

#cc 
@timlinux @fredychandra

**Comment by Charlotte-Morgan** [comment]
In my mind we will have 2 maps; 1 for flood areas by depth class and one for affected population. If you can symbolise both sets of information on a single map that is good; but we also need to include the impact summary on the same page. We need info about the location of affected people, minimum needs, disclaimers etc .... and it has to be what the customer wants :)

**Comment by samnawi** [comment]
Ok @Charlotte-Morgan 
There is some revised from the map template.
I try to combine the flood depth information and an estimates of IDP from InaSAFE analysis.
Also put the map / ID report in the top left corner.

In the previous, I've seen the flood map that contain the information from InaSAFE analysis. So, in this map, I try to put the total of affected population and the minimum needs in the center bottom of the map.
![peta realtime 6](https://cloud.githubusercontent.com/assets/8871958/11835694/f19b1e94-a407-11e5-87f7-072fb0a45a03.jpeg)

In this map, I've an idea to put the infographic like your post in gitter to explain the result from InaSAFE analysis.
![peta realtime 5](https://cloud.githubusercontent.com/assets/8871958/11835693/f19a5d9c-a407-11e5-9d2b-184c77ce28a0.jpeg)

But, for the good reason, I think we must show it to people from BPBD DKI and looking for their feedback.

**Comment by Charlotte-Morgan** [comment]
hey @samnawi - this looks great. I will try to get feedback from BPBD DKI Jakarta on this soon

**Comment by Charlotte-Morgan** [comment]
@lucernae  - here is one we prepared earlier :)

**Comment by lucernae** [comment]
Thank's @Charlotte-Morgan :)
I'm still in the phase of recreating the template so it accepts variable.
I haven't touch the infographics yet, but I plan to discuss about it this week with @timlinux

**Comment by Charlotte-Morgan** [comment]
I think its fine to do the version without infographics for now

**Comment by samnawi** [comment]
@lucernae This is the [link](https://www.dropbox.com/s/6houkh4v1v4f9y0/Flood_RT_Template.qpt?dl=0) if you want to download the *.qpt

**Comment by lucernae** [comment]
![impact-map-en](https://cloud.githubusercontent.com/assets/831865/13272537/6f6ade88-dacf-11e5-9d76-551f8d970118.png)

This is our current implementation generated PDF report. @timlinux @Charlotte-Morgan at least now I know some basic of QGIS Composer programming, so feel free to evolve the design.

Some notes are:
- [ ] I forgot to ask @samnawi to give me images of DKI Jakarta logo, BNPB, North arrow, and supported by logo. For InaSAFE logo, I think I can find it in realtime.
- [ ] We doesn't have yet impact function that can calculate and display Population impacted as vector.
- [ ] A slight change in Flood depth legend, based on PJ API (it has 5 states/class)
- [ ] Disclaimer not yet decided
- [ ] Maybe we want Data Source to be a bit more like table?
- [ ] It seems the place for InaSAFE Analysis Result is a bit cramped. So I still generate it on a new page.

**Comment by samnawi** [comment]
@lucernae This is the [link](https://www.dropbox.com/sh/hp95w71yy7rhg9r/AABlAnzCXhRfhkQ3UCgJzqUxa?dl=0) to download a couple of logos that you mean.

For the supported logo, we still wait a feedback from BPBD DKI about it.

Thank you.

**Comment by Charlotte-Morgan** [comment]
Note: the template map provided for flood realtime predated the existence of any available flood data and the dots on the map do not relate to the flood polygon backdrop :)

**Comment by lucernae** [comment]
@Charlotte-Morgan @samnawi 
Currently generated map:
Still needs some works on positioning and some issues with the qgis version used (the one that caused all the population being shown).

![impact-map-en](https://cloud.githubusercontent.com/assets/831865/14139192/c88b37fa-f69b-11e5-9c84-f891b65e530e.png)

What is needed, next:
- [ ] Black logo of inasafe (I currently used white one)
- [ ] Disclaimer text
- [ ] Logo in supported by section
- [ ] Check text in Source Data and Contacts

**Comment by Charlotte-Morgan** [comment]
Hi @lucernae 
Logo: you already have Jaya Raya and BPBD DKI logos at the top of the page. Please use the InaSAFE supporters logo at the bottom of the page. This it the combined BNPB Australian Aid and WB - GFDRR as on the InaSAFE dock in QGIS.

Data Sources: 
1. Hazard Data
Flood: BPBD DKI Jakarta / PetaJakarta.org
2. Exposure Data
Population: Population Agency DKI Jakarta Prov.

Contacts: @samnawi - please check this bit

Disclaimer text: This impact estimate is automatically generated and only takes into account the population affected by flood hazard in Jakarta.  The estimate is based on flood hazard data from BPBD DKI Jakarta and population exposure data from the Population Agency, DKI Jakarta Province.  Limitations in the estimates of flood hazard and population may result in significant misrepresentation of the on-the-surface situation in the figures shown here. Consequently, decisions should not be made solely on the information presented here and should always be verified with other reliable information sources.
This report was generated by InaSAFE version x.x.x Visit http://inasafe.org for more information.

**Comment by lucernae** [comment]
Currently generated map
![impact-map-en](https://cloud.githubusercontent.com/assets/831865/14165800/2178a8a2-f737-11e5-9429-4d343cbd74f4.png)

Note that:
- I decreased font size for Disclaimer and contact to make it fit.

**Comment by timlinux** [comment]
Can we close this off? Is there anything you still need to do here @lucernae . Please re-open if you have pending tasks.
