### ISSUE TITLE
Keywords Wizard crashes on repeated use

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2514]
As reported by user Gumbi from Malawi, the wizard is crashing on repeated use. Here is how to replicate:

* add two layers to QGIS which have no keywords
* use the KW wizard to assign keywords to the first layer
* use the KW wizard to assign keywords to the second layer

QGIS will crash at some point in the last step above

**Comment by borysiasty** [comment]
More details: Windows 8.1 Pro 64bit and QGIS version 2.10.1

**Comment by samnawi** [comment]
Is it same case with ticket #2467 - Crash Minidump when try to use InaSAFE keyword editor twice ?

**Comment by borysiasty** [comment]
@timlinux - I see you were able to reproduce it. Was it occuring in various steps of the wizard, or always in the same point? What layers and OS did you use? I can't cause it registering random layers, but only tried on Debian for now.

**Comment by timlinux** [comment]
Thanks @borysiasty I will test on windows and put out a 3.2.5 release.
