### ISSUE TITLE
Flood: vector flood on vector population - BUGS

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2519]
It is great to see a new impact function that uses population vector data, this is a very useful addition to the InaSAFE suite.

# problem
We are having some trouble using the new flood on vector population IF with our data.
The data we have are population counts attached to vector admin boundaries. The data include a name field.

# suggestions
* key words:
purpose - exposure
exposure - population
geometry - polygon
data type - continuous (real values not classes)
attribute field - total population

* parameters:
population field - not required
type field - needs explanation
name field - village name

When we use this with standard flood hazard data (vector) we are not offered an impact function - ie no "might" option in the dock.

If we try the IFCW - there is no option for polygon exposure and polygon hazard for flood.

# proposed solution
please update the wizards for the new IF
if possible, new data types should align with the existing data model, keywords and nomenclature 
IF parameters should be documented

@timlinux - @samnawi will send you some data to see if its possible to use with this new IF

**Comment by Charlotte-Morgan** [comment]
I have also looked at the test data
I think it would be fine to assign key words 'attribute field = population' to this data set
I also note that  using the test population and test flood data there is no 'might' option in the dock

**Comment by Charlotte-Morgan** [comment]
see #2543 and pr #2551

**Comment by ismailsunni** [comment]
Been addressed in #2551, closing this.
