### ISSUE TITLE
Python bug when creating a pdf map 

### ISSUE THREAD

**Issue by severinmenard** [inasafe/inasafe#2523]
I get this error message after It tried to created a pdf map with these steps, both in EN or FR:
- run analysis
- when done, clicking on Print
- then clicking on Open PDF
- then trying to save the PDF. The error appears as soon as I click on the Save button

Traceback (most recent call last):
  File "C:/Users/Severin/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1885, in print_map
    self.print_map_to_pdf(impact_report)
  File "C:/Users/Severin/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1916, in print_map_to_pdf
    output_path = str(output_path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe2' in position 69: ordinal not in range(128)

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

**Comment by ismailsunni** [comment]
Hi @severinmenard 
It seems the problem lies on unicode in output_path. There is unicode in the path. I can reproduce the error in my local. Working on the fix now....

**Comment by ismailsunni** [comment]
The fix will be added to the next version (probably 3.2.5). I will close this, you can reopen it later if you still have a problem.
