### ISSUE TITLE
Generic Population Vector IF Revisited

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#2543]
Based on your @timlinux 's message in gitter:
>  Ismail can you look into the flood on population IF from @Samweli - it needs to be changed to use ‘population’ instead of ‘area’ and the exposure should be continuous, not classified I think. Also can you please test it with @samnawi 's test dataset (not redistributable) and make sure it works properly with that?

I revisited the IF, and come up some possible improvements:
- [x] The value in population field of impact layer should represent the calculated number of population in the polygon. See below:
<img width="857" alt="screen shot 2016-01-04 at 8 57 24 am" src="https://cloud.githubusercontent.com/assets/1421861/12082205/3f9aa6ce-b2c1-11e5-8991-86610cbe4ff2.png">
- [x] Change exposure type from exposure area to exposure population.
- [x] Show action list and notes and other common information in the impact layer. See another IF for reference.
- [x] Change exposure layer mode from classified to continuous.
- [x] Show area name (currently, it shows area id in the impact report)
- [x] Show number of population in each hazard level
- [x] Move area_name_field from additional_keyword to exposure_class_field (if possible)

cc @Samweli

**Comment by Samweli** [comment]
Ok @ismailsunni, i'm working on the improvements, i will get back once finished.
Thanks.

**Comment by ismailsunni** [comment]
Hi @Samweli 
Check also #2519

**Comment by Samweli** [comment]
Ok @ismailsunni.

**Comment by Charlotte-Morgan** [comment]
please review feedback and suggestions in #2519

**Comment by ismailsunni** [comment]
All issues have been addressed in #2551, closing this...
