### ISSUE TITLE
Consistency Order at the General Information

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2545]
I found some inconsistency in the general information.
Some report write Total information on the top, the other is under the breakdown information

![selection_015](https://cloud.githubusercontent.com/assets/8871958/12113408/fdde383a-b3d4-11e5-9eea-2b0de8624cb5.png)

# Proposed Solution
Make it consistent, so it will be nice

Thank you

# CC
@Charlotte-Morgan @ismailsunni

**Comment by ismailsunni** [comment]
Hi @samnawi 
The left side, the `total affected population` is different with right one `total`. In the right side, the `total affected population` is similar with `affected buildings`. Perhaps we should change the terminology to `total affected buildings`. And we also need to put the real total (affected + non affected) in the left side (of your image).

So, I propose:
For building:
- Breakdown by hazard level (ordered from high, medium, to low; descending order)
- Total affected building
- Non affected building
- Total building.

For population:
- Breakdown by hazard level (if available)
- Total affected population
- Non affected population
- Total population
- (Empty row)
- Population needing evacuation
- Number of fatalities
- Number of people displaced

I put the last three in the bottom and separated by an empty line to indicate that they are quite different and to make them more shown. Also, by doing this way, we have similar format with the building one.

I have been working on it in my branch. But, I haven't included the some of the request (like total population)

Any suggestion and comment are very welcome.

**Comment by samnawi** [comment]
Yeah @ismailsunni I agree with your propose. That's what I mean. :D

**Comment by ismailsunni** [comment]
Hi @samnawi
I have made a PR for this in #2568
But, it's little bit different with my suggestion above. It turns out that `number of fatalities` and `number of people displaced` are specific in EQ IF and it's similar with a breakdown. So, it will be in the top of the report.
Please try my PR

**Comment by samnawi** [comment]
yeah... I think also. That is the breakdown information.
