### ISSUE TITLE
BUG: Error in analysis results - raster flood on raster population

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2553]
# problem
InaSAFE dev 3.3.0 is getting the results wrong (very big) for flood raster on population raster analysis when population data key words are set to allow resampling = true (ie the default setting)
![image](https://cloud.githubusercontent.com/assets/5743135/12196747/e11d077e-b633-11e5-9e25-6d2df6c89bc5.png)

When allow resampling = false (ie checked ) the results appear to be more correct but still different to InaSAFE 3.2 master.
![image](https://cloud.githubusercontent.com/assets/5743135/12196755/f56eeda0-b633-11e5-9ad9-46f20361c090.png)

![image](https://cloud.githubusercontent.com/assets/5743135/12196766/07af74ee-b634-11e5-9e24-6ba5c5b92422.png)

In master, the analysis results are only slightly different when resampling is allowed / not allowed as expected. (no pics because my data are now version 3.3 :( )

# environment
Windows 7, QGIS 2.8.3, InaSAFE 3.2 master & InaSAFE dev 3.3.0 (5db8f80) 
# proposed solution
fix the analysis error
develop test data that will highlight this type of regression in future

@samnawi  - please add details of this issue & thankyou for finding it :)

# cc
@samnawi @adissadis @ismailsunni 

see #2531

**Comment by samnawi** [comment]
I also found this problem, both in my Linux and Windows Computer

**1. Raster Flood Vs Raster Population**
* allow resample = **false**
![flood people resample false](https://cloud.githubusercontent.com/assets/8871958/12196944/2c03d6ae-b635-11e5-9922-e40f5c0c6cc8.png)

* allow resample = **true**
![flood people resample true](https://cloud.githubusercontent.com/assets/8871958/12196953/3f4947c6-b635-11e5-822b-efaa60a0d197.png)

**2. Raster Tsunami VS Raster Population**
* allow resample = **false**
![tsunami people resample false](https://cloud.githubusercontent.com/assets/8871958/12196967/65ab751a-b635-11e5-98c0-47be7d4a5b31.png)

* allow resample = **true**
![tsunami people resample true](https://cloud.githubusercontent.com/assets/8871958/12196976/746c48fe-b635-11e5-89ce-ea181e50dc49.png)

But, This problem **not found** in the **Raster EQ Vs Raster Population**
* allow resample = false
![eq people resample false](https://cloud.githubusercontent.com/assets/8871958/12197032/0d1534e4-b636-11e5-9471-34d6ab96a396.png)

* allow resample = true
![eq people resample true](https://cloud.githubusercontent.com/assets/8871958/12197018/e108e42c-b635-11e5-8185-d654b46d3e8d.png)

# Environtment
Win7 64 Bit and Linux Ubuntu 14.04
InaSAFE 3.3.0.dev-08960bc


Thank you

**Comment by adissadis** [comment]
I also found this problem:

* With resampling:
![image](https://cloud.githubusercontent.com/assets/2520159/12227203/27a52554-b85b-11e5-9a7d-6624aed102b0.png)

* Without resampling:
![image](https://cloud.githubusercontent.com/assets/2520159/12227207/3aa7f384-b85b-11e5-91b8-93f44b248c97.png)


## Enviroment
Windows 7 64bit 
InaSAFE 3.3 dev master (sync from Github)
QGIS 2.8.4

**Comment by timlinux** [comment]
Hmm very odd - @ismailsunni can you think of any reason for this? I will probably have to bisect the commits back to find the culprit....

**Comment by timlinux** [comment]
Replicated here on develop:

```
Allow resampling false:
---------------------------------

In the event of a flood similar to 2007 in jakarta how many people might need evacuation

People in >= 1.0 m of water	1,104,000
Population needing evacuation 1	1,104,000
Total affected population	1,104,000
Unaffected population	11,647,000

Allow resampling true:
---------------------------------


People in >= 1.0 m of water	3,777,000
Population needing evacuation 1	3,777,000
Total affected population	3,777,000
Unaffected population	39,384,000
```

**Comment by timlinux** [comment]
```
Using test data:
==========


Allow resampling false:
---------------------------------

People in >= 1.0 m of water	100
Population needing evacuation 1	100
Total affected population	100
Unaffected population	100

Allow resampling true:
---------------------------------

People in >= 1.0 m of water	100
Population needing evacuation 1	100
Total affected population	100
Unaffected population	100
```

```
[Continuous Flood]
exposure = ../home/timlinux/.qgis2/python/plugins/inasafe/safe/test/data/exposure/pop_binary_raster_20_20.asc
hazard = ../home/timlinux/.qgis2/python/plugins/inasafe/safe/test/data/hazard/continuous_flood_20_20.asc
function = FloodEvacuationRasterHazardFunction
extent = 106.686999, -6.375461, 106.982858, -6.080876
extent_crs = EPSG:3857
```

**Comment by timlinux** [comment]
Using progressively smaller extents:

```
Allow resampling false:
---------------------------------

In the event of a flood similar to 2007 in jakarta how many people might need evacuation



People in >= 1.0 m of water	25,700
Population needing evacuation 1	25,700
Total affected population	25,700
Unaffected population	260,000


Allow resampling true:
---------------------------------


People in >= 1.0 m of water	88,700
Population needing evacuation 1	88,700
Total affected population	88,700
Unaffected population	866,000


[a flood similar to 2007 in Jakarta]
exposure = ../home/gisdata/InaSAFEPackages/Jakarta/data/penduduk jawa.tif
hazard = ../home/gisdata/InaSAFEPackages/Jakarta/data/Banjir jakarta 2007.tif
function = FloodEvacuationRasterHazardFunction
extent = 106.686999, -6.375461, 106.982858, -6.080876
extent_crs = EPSG:3857
```

**Comment by timlinux** [comment]
```
Allow resampling false:
---------------------------------

In the event of a flood similar to 2007 in jakarta how many people might need evacuation

People in >= 1.0 m of water	2,400
Population needing evacuation 1	2,400
Total affected population	2,400
Unaffected population	20,700


Allow resampling true:
---------------------------------


People in >= 1.0 m of water	5,900
Population needing evacuation 1	5,900
Total affected population	5,900
Unaffected population	57,800


[a flood similar to 2007 in Jakarta]
exposure = ../home/gisdata/InaSAFEPackages/Jakarta/data/penduduk jawa.tif
hazard = ../home/gisdata/InaSAFEPackages/Jakarta/data/Banjir jakarta 2007.tif
function = FloodEvacuationRasterHazardFunction
extent = 106.686999, -6.375461, 106.982858, -6.080876
extent_crs = EPSG:3857
```

![selection_004](https://cloud.githubusercontent.com/assets/178003/12233562/71a1cb7a-b870-11e5-87b9-4ef8358cc4ee.png)

**Comment by timlinux** [comment]
Just for update - as @Charlotte-Morgan pointed out this only replicates with unaligned rasters. The test data in safe/test/data is aligned so it does not replicate. I tried clipping some data out aligned and I get the same values. It's actually a bit odd because the clipper does  align them when it clips them...still investigating further....

**Comment by Charlotte-Morgan** [comment]
And - IIRC - its only flood and tsunami, not all raster on raster (ie not earthquake)
@timlinux - what tweaks did you do to flood on pop IF on 18th December? :)

**Comment by samnawi** [comment]
I try to make it smaller extent analysis, and I still found the wrong result for jakarta Flood Vs Population
![jkt48](https://cloud.githubusercontent.com/assets/8871958/12262671/d87ac900-b95b-11e5-8b3f-9dc9ddd99c9d.png)

But, when I try to use the other data (I use NGK Flood), and the result is good. it's strange.
![ngk flood](https://cloud.githubusercontent.com/assets/8871958/12262741/464747a6-b95c-11e5-91d7-1a6b4e0a0458.png)

I also not found the problem when use **raster hazard VS raster population** in generic IF. In this example I use landslide raster data from BNPB 
![landslide ngk](https://cloud.githubusercontent.com/assets/8871958/12262770/7ae6f506-b95c-11e5-8681-bf1cbb9ecb2e.png)

**Comment by timlinux** [comment]
@Charlotte-Morgan 

> And - IIRC - its only flood and tsunami, not all raster on raster (ie not earthquake)
> @timlinux - what tweaks did you do to flood on pop IF on 18th December? :)

I don't think any:

https://github.com/inasafe/inasafe/commits/develop/safe/impact_functions/inundation/flood_raster_population/impact_function.py

(or was there a specific changeset you had in mind?)

**Comment by timlinux** [comment]
So I have been investigating further with a very small test set that replicates the issue) - the resampler is somehow magically assigning 147 to each cell:

![array view population_002](https://cloud.githubusercontent.com/assets/178003/12779387/61052f66-ca70-11e5-80c6-68a259b4b46a.png)

**Comment by Charlotte-Morgan** [comment]
I was not sure if you were planning to use this IF to test ideas for RFC #2473 - but maybe you know the meaning of 147.31914 :(

**Comment by timlinux** [comment]
Yeah it would be a good starting candidate for #2473. I am still busy debugging to see where the 147 comes from.

**Comment by timlinux** [comment]
So the above matrix was for cases where **allow resampling == true**. When resampling is disabled we get a matrix for the people layer like this:

![array view population_003](https://cloud.githubusercontent.com/assets/178003/12782507/673c32b2-ca84-11e5-87f1-5d12a69040f4.png)

**Comment by timlinux** [comment]
Note for self: 147 seems to be coming from the flood layer....


![layer properties - flood unaligned style_004](https://cloud.githubusercontent.com/assets/178003/12785738/9d851822-ca96-11e5-861b-ebf7b059db41.png)

**Comment by Charlotte-Morgan** [comment]
well spotted

**Comment by ismailsunni** [comment]
Hi @timlinux 
In case you haven't realised about it.
Your unit test in your branch is not working because, the `hazard_geo_cell_size` > `exposure_geo_cell_size`. See https://github.com/timlinux/inasafe/blob/inasafe-2553/safe/impact_functions/base.py#L881

hazard geo cell size:  0.000806068257796
exposure geo cell size:  0.000453413394994

**Comment by ismailsunni** [comment]
Output from `clip_parameters` function:

No resampling:
```
{
'cell_size': 0.0004534133949940511, 
'adjusted_geo_extent': [106.83483825046963, -6.171823121175932, 106.84209286478954, -6.16657356275995], 
'extra_exposure_keywords': {}
}
```
With resampling:
```
{
'cell_size': 0.0002686894192652079, 
'adjusted_geo_extent': [106.83483825046963, -6.171823121175932, 106.84209286478979, -6.166573562759938], 
'extra_exposure_keywords': {'resolution': 0.0004534133949940511}
}
```
Only cell_size and resolution are very different.

**Comment by ismailsunni** [comment]
From master.
Output from `get_clip_parameters` function:

No resampling:
```python
[
    {},  # extra_exposure_keywords
    [106.83483825046963, -6.171823121175932, 106.84209286478954, -6.16657356275995],  # adjusted_geo_extent
    0.000453413394994,  # cell_size
    <qgis._core.QgsRasterLayer object at 0x11e52d770>,  # exposure_layer
    [106.83483825046963, -6.171823121175932, 106.84209286478954, -6.16657356275995],  geo_extent
    <qgis._core.QgsRasterLayer object at 0x11e52d5a8>  # hazard_layer
]
```


With resampling:
```python
[
    {'resolution': 0.0004534133949940511},  # extra_exposure_keywords
    [106.83483825046963, -6.171823121175932, 106.84209286478979, -6.166573562759938],  # adjusted_geo_extent
    0.000268689419265,  # cell_size
    <qgis._core.QgsRasterLayer object at 0x11e52d770>,  # exposure_layer
    [106.83483825046963, -6.171823121175932, 106.84209286478954, -6.16657356275995],  geo_extent
    <qgis._core.QgsRasterLayer object at 0x11e5470e8>  # hazard_layer
]
```

It seems, from develop and master branch, the output of clip parameters are the same for both cases.

As far as I know, the `allow_resampling` value is only used in this clip_parameter method. So, it's really strange.

**Comment by ismailsunni** [comment]
For easier debugging and testing, I move the TestDockRegressions in separated file, and added it to master branch.
- Develop based: https://github.com/ismailsunni/inasafe/blob/fix_2553_hair_loss/safe/gui/widgets/test/test_dock_regressions.py *all pass
- Master based: https://github.com/ismailsunni/inasafe/blob/master_2553_hair_loss/safe/gui/widgets/test/test_dock_regressions.py *one failed test

**Comment by ismailsunni** [comment]
Update of the tale...

After cornering the bug, I found out that there is something strange in `setup_impact_function` method in analysis.py. See https://github.com/ismailsunni/inasafe/blob/master_2553_hair_loss/safe/utilities/analysis.py#L867 and https://github.com/ismailsunni/inasafe/blob/fix_2553_hair_loss/safe/utilities/analysis.py#L438

For both version (develop and master), they started with the same exposure layer (I even checked the sha value). But, when the method assigned the exposure layer to impact function, somehow, they become different.

FYI, my method: switching between the branches, and see where the difference start coming out. It would be easier if I have two PyCharm. Oh wait.... I can do it. Copy the project, switch to different branch, and debug in paralel. Sounds a good plan. *I didn't think about it before I write this comment. Shame on me.

**Comment by ismailsunni** [comment]
Finally, found the problem....

After looking deep down until raster.py, in `get_resolution method`, I found out that the resolution keyword is not stored. So, the problem lies when inasafe try to add extra keyword for resolution, in `_clip_raster_layer` in clipper.py.

After all, it was me when migrating the metadata.. 

Trying to fix it now...

**Comment by ismailsunni** [comment]
The problem is....
In one place, resolution accept a tuple as a valid type, and in the other place (in this clipper method) resolution is a float. Which is not good.

When I change the valid type to resolution, it works again. But, I need to make sure that the other usage of resolution is not affected.

At least, now we know where is the problem...
