### ISSUE TITLE
Wiki for Impact Function Development and Metadata

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#2558]
## Problem

Currently, we don't have wiki or document that explain how we develop impact function and about the metadata. There are some document/comment/RFC that related to it, but it's not easy to read them as they are scattered in several places.
## Proposed Solution

Create one as wiki page.

**Comment by timlinux** [comment]
Lets get #2987 done first ...

**Comment by ismailsunni** [comment]
We only have one IF. I don't think we need to create it to help people create new IF.
For the metadata, we have had already a definitions for each property.
Let's close this.

**Comment by Gustry** [comment]
We should have documents to explain how to add new exposure, new hazard, new hazard classification, new postprocessor ... ;-)

**Comment by ismailsunni** [comment]
Haha, true...
