### ISSUE TITLE
BUG: Auto version update of keywords

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2569]
When we have data with key words assigned (eg version 3.2) and we open that data in version 3.3,
most the keywords migrate neatly. There is a problem though with the URL field which gets extra 'code' as well as the URL.
![image](https://cloud.githubusercontent.com/assets/5743135/12288096/da5f157a-ba03-11e5-9704-64bb2a7b7372.png)

Please make it so only the url is in the URL field

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan can you give some details about this?

**Comment by Charlotte-Morgan** [comment]
aagghh - i closed window without posting comment - you know!

**Comment by Charlotte-Morgan** [comment]
i have added the details at the top of the ticket again.
