### ISSUE TITLE
Use aggregation layer in the command line

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2572]
# Problem

According to the [usage.txt](https://github.com/inasafe/inasafe/blob/develop/bin/usage.txt), we can use an aggregation layer in the command line.
However, the source code doesn't manage the aggregation layer. The Analysis object is not aware of the aggregation layer.
# Solution

Be sure that InaSAFE can use the aggregation layer in the command line : 
https://github.com/inasafe/inasafe/blob/develop/bin/inasafe#L266

**Comment by lucernae** [comment]
@Gustry there are some features like pdf report generation and aggregation layer that is not quite connected yet. I'm currently trying to fix it for WB project.

**Comment by Gustry** [comment]
We still need to fix the command line with inasafe v4.

**Comment by lucernae** [comment]
Ah so this is going to be in the final

**Comment by Gustry** [comment]
@myarjunar Can you have a look to this ticket ?

**Comment by timlinux** [comment]
See also #4318 for more thoughts on this

**Comment by Gustry** [comment]
I'm closing this ticket. We have a separate repo on github for CLI: https://github.com/inasafe/inasafe_cli
