### ISSUE TITLE
InaSAFE OpenStreetMap Downloader cannot download relation

### ISSUE THREAD

**Issue by adissadis** [inasafe/inasafe#2576]
# Problem
InaSAFE OpenStreetMap Downloader cannot download polygon that have relation inside it

# Description
I tested download flood_prone area in Jakarta and it turn out i got only building that have `flood_prone=yes` not the administration boundary. 

![image](https://cloud.githubusercontent.com/assets/2520159/12287910/b33cfed6-ba02-11e5-918a-530b4b5aa694.png)

I checked at JOSM and found that the administrative boundary in Jakarta is using relation now. 

![image](https://cloud.githubusercontent.com/assets/2520159/12288081/b321449c-ba03-11e5-9f48-abc6b01472af.png)

And when I test using QuickOSM plugin in QGIS, they success download area that have `flood_prone=yes` attribute both relation or not.

![image](https://cloud.githubusercontent.com/assets/2520159/12287964/26eb7aa6-ba03-11e5-9eda-32b922760673.png)

# Proposed solution
Maybe if possible InaSAFE OSM Downloader can also have capabilities to download relations from OSM data

# System
Windows 7 64bit
InaSAFE 3.3 dev-master sync from github

**Comment by Gustry** [comment]
Hi @adissadis 
Can you try again that you have the expected result ?

**Comment by adissadis** [comment]
Thanks @Gustry! Now i can donwload the boundary also. I will close this issue now.
