### ISSUE TITLE
QdateTime in the keywords creation wizard

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2585]
If I try to create keywords in the last step of the wizard, I can see a QT object ``PyQt4.QtCore.QDateTime`` for the date.
By the way, the date field is not shown in the dock, is it normal ?
![qgis4](https://cloud.githubusercontent.com/assets/1609292/12446547/e7c6b864-bf6a-11e5-87b9-36b2e84f181d.png)

**Comment by ismailsunni** [comment]
Yes, it is not normal. I have made a fix in #2586. Thanks @Gustry
