### ISSUE TITLE
Transparency Problem in OSX

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#2587]
## Problem

In the impact result for population, InaSAFE will make the cells with 0 value transparent. But, this feature is not working in OSX. See sample result below:
1. **Ubuntu 14.04** 
   Less white area, since it's transparent. And the transparency is set.
   ![virtualbox_ubuntu-14](https://cloud.githubusercontent.com/assets/1421861/12474259/6a210b84-c04c-11e5-8b7b-72fd1822f7d5.png)
2. **OSX**
   More white area, since it's not transparent. And the transparency is not set.
   <img width="1254" alt="screen shot 2016-01-21 at 2 38 02 pm" src="https://cloud.githubusercontent.com/assets/1421861/12474293/9eb953a6-c04c-11e5-974e-9b83b0ee447f.png">

From @samnawi it works on Windows, so perhaps it's OSX specific.

Notes, I have script to set the transparency, https://github.com/ismailsunni/scripts/blob/master/qgis_raster_transparency.py, that works properly in OSX.
## Proposed Solution

Make it happy.

cc @timlinux , have you ever encountered this before?

**Comment by Gustry** [comment]
@timlinux It might be related to your issue with EQ and the displaced raster.

**Comment by timlinux** [comment]
Hmm yes it may be the same issue....

**Comment by Gustry** [comment]
We don't have any raster output in InaSAFE. I'm closing this ticket.
