### ISSUE TITLE
We should deprecate all usage or Interpolation

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2592]
# Problem

We get a lot of confusion / dissatisfaction when we produce results based on interpolated data. See for example  #2419

Here is a short breakdown of the issue:
## Figurative approach

When doing analysis with raster hazards, we commonly use interpolation to infer the impact levels on people or infrastructure on the underlying flood pixels. Why do we do that? Its because pixels edges in a hazard raster are contrived edges (e.g. flood waters do not naturally follow pixel boundaries) and so a building close to an edge of a flooded pixel (but outside it) is probably also affected by it. We can call this a **figurative** approach.

**Advantage:**
- Does not treat pixel edges literally

**Disadvantage:**
- Confusing when humans view the interpolated results which appear to show exposure affected even though it is not in the hazard areas.
-  Interpolating data which is already probably interpolated (e.g. flood pixels) is probably not ideal

Example image from @adissadis 

![4fcf4174-a89b-11e5-8eae-1812346fb551](https://cloud.githubusercontent.com/assets/178003/12973964/11ebe498-d0b9-11e5-9f3a-5080a02eb278.png)
## Literal approach

Conversely one might prefer to take a **literal** approach whereby all impacts are based on discrete lookups of pixel values. In the case of point exposure features, we would just find the pixel value of whatever pixel underlies the point. In the case of polygons exposure features, we would use the maxima of all pixels which intersect the polygon. The logic with the latter is that any part of a building that is affected (e.g. flooded or touching a lava flow) renders the whole building affected.

**Advantage:**
- Much more logical and easy to explain to users

**Disadvantage:**
- Probably misses more nuanced interpretation of (often incomplete) datasets.
# Proposed solution

We propose to refactor all code that uses interpolation to determine impact levels to rather use direct lookups (i.e. the "literal" approach described above).
# See also:

https://github.com/inasafe/inasafe/issues/2419
# CC

@Charlotte-Morgan 
@ismailsunni 
@samnawi 
@adissadis

**Comment by Gustry** [comment]
We can now close this ticket with inasafe v4.
