### ISSUE TITLE
Key Words Wizard: needs tweaks for population vector data

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2596]
The new vector flood and vector population data IF has created a new type of exposure data. The KW wizard needs some tweaks to cope with this new data type.

The following issues are noted when stepping through the wizard:
exposure
population
* continuous (@borys this wizard step need updating because it asks the wrong question about classified)
* count (update the description to include per pixel, building or area)
* select attribute (wizard bug - missing constant)
* attribute for id - needs a description
* attribute for area name - needs a description

steps above with an asterix need review please.
none of this is fatal but not easy for users to work through this one

refer to #2551

@samnawi @borysiasty @ismailsunni @timlinux @adissadis

**Comment by ismailsunni** [comment]
Closing this, been addressed in #2551.
