### ISSUE TITLE
bug:OSM downloader timing out

### ISSUE THREAD

**Issue by easmetz** [inasafe/inasafe#2598]
# problem
The OSM downloader has been timing out for me.

# proposed solution
make it happy

# cc
@easmetz

**Comment by Charlotte-Morgan** [comment]
Hi @easmetz  - maybe you are trying a large area
do you get an error message or does it just hang?

**Comment by Charlotte-Morgan** [comment]
i think this is a user problem - test ticket only
Closing this ticket
