### ISSUE TITLE
BUG: User extents error message

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2604]
# Problem
When I choose the analysis extent as the intersection of the hazard and exposure layers (Flood vector and population vector); i get the warning that there are no overlapping extents.

![image](https://cloud.githubusercontent.com/assets/5743135/12778837/97fa0ee8-ca97-11e5-9e10-73375d68c964.png)

However, this warning is not correct, the data do have overlapping extents.

# proposed solution
Is it possible that the extent checker --> warning issuer needs to be tweaked to recognise vector on vector analysis??

**Comment by Gustry** [comment]
@Charlotte-Morgan Is-it possible to get more details ? I can't replicate with vector on vector.
Is-it vector population on vector flood ?
Is-it possible to share your dataset ?

**Comment by Charlotte-Morgan** [comment]
Hi Etienne
I've had this message with a number of scenarios. Today with maumere tsunami and OSM buildings. These data are available as standard training data.
Always in 3.3 dev. I think the original was vector on vector. Jakarta flood and population. These data have been shared previously.


Charlotte  Morgan
Spatial Data Analyst
DMInnovation - Jakarta
GEOSCIENCE AUSTRALIA

Mobile: +61 412 949642
Mobile: +62 8118204648


On 5 Feb 2016, at 7:11 PM, Etienne Trimaille <notifications@github.com<mailto:notifications@github.com>> wrote:


@Charlotte-Morgan<https://github.com/Charlotte-Morgan> Is-it possible to get more details ? I can't replicate with vector on vector.
Is-it vector population on vector flood ?
Is-it possible to share your dataset ?

-

**Comment by Gustry** [comment]
Thanks for the detail.
As you wrote your comment by email, you maybe didn't see my update in my previous comment. I was asking if you can check that you are using the good extent in the extent selector dialog ? (eg Use intersection of hazard and exposure layers) ?
I still can't replicate with Maumere.

**Comment by Charlotte-Morgan** [comment]
Yes I was.

Charlotte  Morgan
Spatial Data Analyst
DMInnovation - Jakarta
GEOSCIENCE AUSTRALIA

Mobile: +61 412 949642
Mobile: +62 8118204648


On 5 Feb 2016, at 7:33 PM, Etienne Trimaille <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the detail.
As you wrote your comment by email, you maybe didn't see my update in my previous comment. I was asking if you can check that you are using the good extent in the extent selector dialog ? (eg Use intersection of hazard and exposure layers) ?
I still can't replicate with Maumere.

-

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry 
Back and my desk and having another look at this. I was concerned that maybe i was bogged down in the flood vector on pop vector PR when I saw this message.
However, I can confirm the issue.

# operating env
Windows & GQIS 2.8.3
InaSAFE 3.3 cd7c751 (refreshed today) 

# Data 
Maumere tsunami raster
OSM buildings

# Error
when "use intersection of hazard and exposure layers" is selected

**Comment by Gustry** [comment]
I made a commit above to fix the problem when you are using `Use intersection of hazard and exposure layers`.
However, for the second screenshot, it's the normal behaviour. The user extent overlaps the exposure and the hazard extents :
![bf71b14a-ce86-11e5-8f36-74b1fce06bc7](https://cloud.githubusercontent.com/assets/1609292/12898472/24209db0-cead-11e5-8c0d-9cf9f65088f0.png)
