### ISSUE TITLE
[Realtime] Report button problem in Mozilla Firefox

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2607]
I got a problem with report button in http://realtime.inasafe.org/ when I access it using Mozilla Firefox. There is no respon when I click this button.
![image](https://cloud.githubusercontent.com/assets/8871958/12808799/5cc42394-cb4c-11e5-99c8-b304ed60252a.png)

But, this button work properly when I access using Chrome.

Thank you.

# CC 
@lucernae

**Comment by lucernae** [comment]
Fix is on the way....
