### ISSUE TITLE
BUG: Default map template needs more metadata

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2613]
The default map needs to stand alone with sufficient information for users.

The following tsunami inundation map does not have sufficient information to inform someone looking at it what they are viewing.
![image](https://cloud.githubusercontent.com/assets/5743135/12840250/61f90ae6-cc14-11e5-9d7c-e3fb097a9022.png)
# proposed solution

the analysis information should include:
hazard type
exposure type
impact function (maybe)

some location information (if we are working in wgs84 - what is the grid showing? - should it be lat longs)

@samnawi  - please make it happy
@easmetz - please review and contribute to feedback on map templates
@timlinux - fyi

**Comment by samnawi** [comment]
Hi @Charlotte-Morgan 
As I know (correct me if I wrong), all of the elements in a map template uses a convention based approach. 
I'm not see the convention to show what you mean in [here](https://github.com/inasafe/inasafe/wiki/Map-Composer-Templating).
In the previous, I've been post a comment on #1314. Do you mean like this ?
![image](https://cloud.githubusercontent.com/assets/8871958/12878128/9d0d1a34-ce51-11e5-99ea-cd8d72d53d2f.png)

**Comment by timlinux** [comment]
I guess this should form part of the #2920 reporting standards conversation. Moving to 3.6 for now. 

cc @easmetz

**Comment by Charlotte-Morgan** [comment]
I think this is done in version 4.0
