### ISSUE TITLE
Bounding Box in Analysis Area

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2618]
I just realized from this picture 
![image](https://cloud.githubusercontent.com/assets/8871958/12879545/74aa40d8-ce67-11e5-88de-50a11e9ee43c.png)
Whether the value at the East column and West column in the bounding box is not reversed?
I think in the coordinate in the east column should bigger than west column.

I also found it at the bounding box in OSM Downloader
![image](https://cloud.githubusercontent.com/assets/8871958/12879691/bd7dcff8-ce69-11e5-86d5-cba581e1663d.png)

# Proposed Solution
Make it Happy

# CC 
@Charlotte-Morgan @timlinux @ismailsunni 

Thank you.

**Comment by Charlotte-Morgan** [comment]
## problem confirmed
In Indonesia we are south of the equator and east of Greenwich.
the north coord should be smaller than ie less south than the south coord
and
the west coord should be smaller than ie less east than the east coordinate

## proposed solution
+1

**Comment by Gustry** [comment]
Thanks for the report. This has been fixed in https://github.com/inasafe/inasafe/pull/2619
