### ISSUE TITLE
Buildings which overlap partially the flood are not affected

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2629]
# Problem

I'm working on a small test dataset with some buildings and floods. The red point is the centroid of my building.
![selection_003](https://cloud.githubusercontent.com/assets/1609292/13014677/5229ff20-d1b5-11e5-827c-1144733b4b6f.png)

If I run the analysis, only buildings with the centroid inside the flood will be marked as affected by the IF.
![selection_004](https://cloud.githubusercontent.com/assets/1609292/13014681/56a8ca36-d1b5-11e5-86f2-f52ba52ba00c.png)

According to another dataset, it's not the normal behaviour : 
![selection_005](https://cloud.githubusercontent.com/assets/1609292/13014360/b54f5296-d1b3-11e5-9b2a-a39ca92dc3f7.png)

![selection_006](https://cloud.githubusercontent.com/assets/1609292/13014370/c113aa32-d1b3-11e5-9c16-948897c3df52.png)

I don't know what it is wrong with my first dataset.
The first flood has ternary description (low, medium, high).
The second flood has a binary description (wet and dry).

**Comment by ismailsunni** [comment]
Perhaps this is duplicated of #2419

**Comment by Gustry** [comment]
In #2419, there are all using raster as a hazard layer. Yes, there is some interpolation when InaSAFE uses a raster layer.
But in my case, layers are only vector layers. So I don't think it's a duplicate as my scenario is not using interpolation.

**Comment by timlinux** [comment]
We will fix this with the 7 princes in #2987 - the impact on a feature should be the greatest hazard which it touches.

**Comment by Gustry** [comment]
I'm going to close this one due to InaSAFE v4
