### ISSUE TITLE
Some IF don't show 'not affected' in the legend

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2630]
# Problem

In some IF, the `not affected` features are not shown in the legend. But we can see the `not affected` column in the report.

![selection_008](https://cloud.githubusercontent.com/assets/1609292/13022550/9d7496f2-d1e2-11e5-85f1-7f5bf0468cad.png)
# Proposed solution

I think it could be nice to have the same result in the legend compare to the report.
# PS

By the way, I'm wondering why the `Medium Hazard Zone` is green. For me, it doesn't seem logical. Is-it a feature ? :)

**Comment by timlinux** [comment]
See also #2920 - we need to standardise the legend display.

**Comment by Gustry** [comment]
We have the reporting standard now.
