### ISSUE TITLE
Python error when adding a WMS

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2636]
# Problem
When I add a WMS layer, InaSAFE throws an exception : 
```
ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. 
Traceback (most recent call last):
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 848, in update_layer_name
    self.keyword_io.update_keywords(layer, {'title': name})
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/utilities/keyword_io.py", line 296, in update_keywords
    self.write_keywords(layer, existing_keywords)
  File "/home/etienne/.qgis2/python/plugins/inasafe/safe/utilities/keyword_io.py", line 262, in write_keywords
    raise e
ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
```

Just for information, this is my layer source : 
`contextualWMSLegend=0&crs=EPSG:4326&dpiMode=7&featureCount=10&format=image/jpeg&layers=Roads&styles=default&url=http://127.0.0.1/qgisltr?MAP%3Dtest.qgs`

**Comment by ismailsunni** [comment]
I am trying the WMS from http://mesonet.agron.iastate.edu/cgi-bin/wms/iowa/rainfall.cgi?. The keyword wizard is not enabled. And the dock shows an error, not finding `layer_purpose` in its keyword. And the error is appended to the keywords table from the previous selected layer.

It's quite different with what you got @Gustry .

Btw, it seems your WMS layer source is not valid. Or is it valid?

**Comment by Gustry** [comment]
I still have this issue. My layer seems to be valid, I can see it in QGIS.
This python error occurs everytime if I hide/display layers in QGIS if I have one WMS.

**Comment by timlinux** [comment]
For WMS layers, we should anyway simply ignore them from an analysis point of view since they are just pictures.  @Gustry please try to replicate - if you can, move it over to 3.6 otherwise close it out. @ismailsunni thinks it may not be an issue anymore with kw refactoring.

**Comment by Gustry** [comment]
I can't replicate these last few days. I'm going to close this ticket.
