### ISSUE TITLE
InaSAFE Realtime Shakemap cross referenced with BMKG Website

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#2651]
### Problem

We want to cross reference shakemap list from BMKG website here:
http://www.bmkg.go.id/BMKG_Pusat/Gempabumi_-_Tsunami/Gempabumi/Gempabumi_Terkini.bmkg
especially for critical magnitude. This allows several functions:
- we can be sure that the grid is (or not yet) delivered 
- we can annotate the process, is it processed, still processing, failed or we can put some additional comments

### Proposed Solution

Make it happy :D

- We can crawl BMKG website each hour to get the list (is it realtime enough?)
- We can put the incoming shake not yet received in InaSAFE Django database and display it as not yet received (the grid.xml)

**Comment by timlinux** [comment]
Can you give an update on this @lucernae - I would like to see this in place for 3.5

**Comment by lucernae** [comment]
Done, and waiting to be pushed.
