### ISSUE TITLE
BUG: Tsunami on buildings

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2663]
The following problem is reported in the tsunami impact on buildings analysis.

**Comment by timlinux** [comment]
@Charlotte-Morgan is there a bit more info missing here?

**Comment by Charlotte-Morgan** [comment]
:( yes

**Comment by Charlotte-Morgan** [comment]
Apologies - this addtional information should have been included in the original report.

The following problem is reported in the dock when the IF is run using the IFCWizard. It is not fatal.
I do not get this problem reported if I run directly from the dock.
![image](https://cloud.githubusercontent.com/assets/5743135/13662613/673dac58-e6ce-11e5-935d-59609fa1ecd6.png)

**Comment by Gustry** [comment]
This error is fixed in the PR https://github.com/inasafe/inasafe/pull/2661

But for master, I can make a patch.

**Comment by Charlotte-Morgan** [comment]
ok - great. thanks @Gustry

**Comment by Gustry** [comment]
It has been fixed in master (3.3)
For develop (3.4), I'm waiting the merge of my PR #2661
