### ISSUE TITLE
We need a tsunami impact on roads impact function

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2666]
### Problem

We need a dedicated IF for tsunami on roads with specific thresholds as per tsunami on buildings.

### Proposed Solution

Please see 
 * https://github.com/inasafe/inasafe/issues/1427 
 * https://github.com/inasafe/inasafe/issues/1428 

1. create a new package in impact_functions/inundation called tsunami_raster_road
1. copy test package from impact_functions/inundation/tsunami_raster_buildings and then tweak as needed
1. copy __init__.py from impact_functions/inundation/tsunami_raster_buildings tweak with author etc
1. copy impact function implementation from flood_raster_road/impact_function.py to  tsunami_raster_road/impact_function.py
1. refactor both impact functions moving common code to a utilities module in safe.utilities
1. update tsunami impact function to work with multiple thresholds and use tsunami specific reporting - copy notes implementation from tsunami_raster_buildings
1. Metadata 
  * copy metadata from tsunami_raster_buildings and tweak
  * and ask Charlotte for input if needed. 
  * please see https://github.com/inasafe/inasafe/issues/1251 for metadata notes
  * we should put the english metadata in now and the Indonesian can come with translations.
  * the metadata between tsunami on roads and on buildings is probably going to be similar or the same in parts so use DRY and do imports across IF’s as needed
1. create an empty parameter_definitions.py and import the three threshold parameters from tsunami_raster_buildings. We will do proper implementations in the future if we need them to be different from building thresholds
1. Register your new IF in safe/impact_functions/__init__.py
1. Test in travis
1. Test interactively to ensure that it works in the wizard and dock

# CC

@Charlotte-Morgan @ismailsunni

**Comment by Gustry** [comment]
I'm closing this as Tsunami on roads is InaSAFE 3.3
