### ISSUE TITLE
We need to represent the impact summary as data not markup

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2671]
Currently we produce html reports for the impact summary. We need to move this over to producing JSON (geojson) and store that with the

**Comment by timlinux** [comment]
In the JSON we will have

* impact summary table
* aggregation table
* notes
* actions
* etc.

**Comment by ismailsunni** [comment]
I think we can close this ticket since we have the json impact data in develop branch. The geojson will be addressed later in 3.5 via this #2803
