### ISSUE TITLE
We need a new panel in wizard for class assignments

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2673]
The idea is that if we have 

* roads
* buildings
* in the future landcover

The user should map the concepts in the type column to known concepts. These will be used in aggregation.

There should be a simple ui similar to the wet / dry classification tree where the user drags type values from the left into the classification tree on the right.

**Comment by borysiasty** [comment]
/me will ask @Gustry for more info next week.

**Comment by ismailsunni** [comment]
The steps:
1. @borysiasty will add new step in the wizard to map the exposure. You can find the list of the mapping value in here https://github.com/inasafe/inasafe/blob/develop/safe/postprocessors/building_type_postprocessor.py#L40 (for building, you can find the other in the _similar_ python files.
2. @ismailsunni to make it sure the keywords is working properly
3. @Gustry will use the value mapping to use in the aggregator. See #2675

**Comment by timlinux** [comment]
Here are the current classes we map to:

### Buildings:

* Medical
* Schools
* Places of worship (I think we should rather change this to 'Place of worship'
* Residential
* Government
* Public Building
* Fire Station
* Police Station
* Supermarket
* Commercial
* Industrial
* Utility
* Sports Facility
* Other

### Roads

* Motorway / highway
* Motorway link
* Primary road
* Primary link
* Tertiary
* Tertiary link
* Secondary
* Secondary link
* Road, residential, living street, etc

**Comment by borysiasty** [comment]
@ismailsunni @timlinux @Gustry - as I understand the only solution (apart from hardcoding ;) ) is to read the maps every time from BuildingTypePostprocessor.field_values and RoadTypePostprocessor.field_values. Some day maybe we'll move them to the metadata, but for now this is the way to go, isn't it?

**Comment by borysiasty** [comment]
@ismailsunni @timlinux @Gustry - After some thinking (and working) I guess we can directly use the existing classification (mapping) step. From wizard's point of view the situation is almost identical. I only see one difference: for hazards, the available classifications are defined in impact functions and returned by ImpactFuctionManager (thus there may be multiple classifications available for given layer).

For the exposure classification, the wizard has to read the mapping directly from BuildingTypePostprocessor.field_values and RoadTypePostprocessor.field_values. Please let me know if there any future plans to unify those hazard and exposure mapping/classification or not (I suppose there aren't at the time, as the purpose is different).

**Comment by borysiasty** [comment]
@timlinux - in your list of classes for roads you didn't include
 - Track
 - Cycleway, footpath, etc
 - Other
that are definded in the RoadTypePostprocessor. Did you omitted them intentionally? I implemented just reading the exact mapping from the Postprocessor.

**Comment by samnawi** [comment]
I've tried to regroup the roads in this [comment](https://github.com/inasafe/inasafe/issues/2682#issuecomment-196786570). I consider regrouping the road classification based on my comparison of some regulation in Indonesia and OSM features.

**Comment by timlinux** [comment]
@borysiasty Ok I think that is fine - we will no doubt want to tweak the list based on @samnawi 's feedback anyway. What would be ideal is if the list is defined in definitions.py or somewhere central.

**Comment by borysiasty** [comment]
@samnawi @timlinux: i made a temporary definitions file: https://github.com/borysiasty/inasafe/blob/develop/safe/gui/tools/wizard_metadata.py
I guess @ismailsunni will  be moving it to definitions.py some day ;), in the meantime feel free to edit it.

**Comment by ismailsunni** [comment]
@samnawi @timlinux @borysiasty 
Yes, for the final list, we should consult with @samnawi or @Charlotte-Morgan. If possible, we should have also the description for each class, and the Bahasa Indonesia's term for each of them also. We should also do it for the structure.

@samnawi do you think you have resource to do it? Does the list in https://github.com/inasafe/inasafe/issues/2682#issuecomment-196786570 final? If so, please add some description and Bahasa Indonesia's term for each of them.

**Comment by borysiasty** [comment]
@ismailsunni I guess we can close this one (I don't have such permissions).

**Comment by ismailsunni** [comment]
@borysiasty yes, we can.

The ticket for updating the mapping #2740 
The ticket for soft coding the exposure #2675
