### ISSUE TITLE
We need to soft code class assignments in aggregation

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2675]
See #2673 - this metadata should be used in building and road aggregators to replace the hard coded classes.

**Comment by timlinux** [comment]
Assigning first to @borysiasty, then assign to @ismailsunni for keywords, then to @Gustry for processing update.

**Comment by Gustry** [comment]
Work in progress in t the PR #2743

**Comment by Gustry** [comment]
I would like to review the behaviour if the user doesn't map every values like in this example : 
![inasafe keywords creation wizard_074](https://cloud.githubusercontent.com/assets/1609292/15036782/220123da-1294-11e6-8233-7eeb0fabf0ed.png)

I think, it would be a good idea if the final user is aware about these unclassified values in the dock.
Should we create a automatically a `unclassified` item ?
![selection_075](https://cloud.githubusercontent.com/assets/1609292/15036791/3ee75820-1294-11e6-8aba-ccea71eb9d93.png)

If we create the new item automatically, should we use the  `unclassified` in the impact report ?
If we don't use these unmapped values, should the report ignore all these features ?

CC : @timlinux @Charlotte-Morgan @ismailsunni @borysiasty

**Comment by ismailsunni** [comment]
From my opinion, `unclassified` is good to have for un-mapped value. It should be also shown in the dock.
> If we create the new item automatically, should we use the unclassified in the impact report ?
yes

> If we don't use these unmapped values, should the report ignore all these features ?
I think if we ignore it, it will be strange result. Many holes in the impact layer. The main idea of value mapping is giving the user overview how the hazard impact the exposure. Not selecting which one is ignored, which one is counted.

So, my conclusion, yes for automatically assigning un-mapped to `unclassified` and we need to show it on the dock.

But, I think we have discussion about it with @samnawi also, regarding `other` and `unclassified` class.

**Comment by Gustry** [comment]
For me `other` and `unclassified` are two different things.

But if we think that all values could/should be mapped in the default classes (included `other`), yes, `other` and `unclassified` look duplicated. If we go on that way, I propose that we remove `other` from the right panel in the wizard, we add a text saying that all unclassified values will go in `other` and the wizard will take every values in `other` automatically.

**Comment by Gustry** [comment]
The PR #2743 has been merged. I'm closing this issue.
