### ISSUE TITLE
We need smart road impact reports

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2682]
Can we improve the way road impacts are reported to users? Do the current road classes reflect user requirements? Do we need all the classes or can they be grouped? Will changing the grouping and order of classes affect the truncation of reports?

@samnawi - please make this a priority to review all tickets that mention 'road' and come up with a suggestion for the way we report on the new tsunami on roads IF.

@fredychandra - pitch in here if you want

**Comment by Charlotte-Morgan** [comment]
#2231 #2106  #2373 etc - check these out

**Comment by timlinux** [comment]
Please cc @Gustry in to replies

**Comment by samnawi** [comment]
I've already doing rapid comparison from road classification from BIG (SNI 19-6502.2-2000 --> the website still down), PU - Ministry of Public Work ([RSNI T-14-2004](http://www.pu.go.id/uploads/services/service20130717123737.pdf)), the [wiki openstreetmap ](http://wiki.openstreetmap.org/wiki/Map_Features#Highway) and also from Indonesia [Openstreetmap](http://wiki.openstreetmap.org/wiki/Id:Jalan). 

I'm not sure to make a group of the road classification. But, I try to group it like this (just to make it simple) :
1. Motorway : Motorway, Motorway link
2. Artery / Primary : Trunk, Trunk link, Primary, Primary link
3. Secondary : Secondary, Secondary link
4. Local : Tertiary, Tertiary link
5. Residential : Residential, Living street
6. Path : Footway, pedestrian, steps, path, cycleway, track
7. Other : Service, Unclassified, road, bus guideway, etc

@harrymahar already doing some effort for this and he already put in [here](http://wiki.openstreetmap.org/wiki/Id:Jalan) --> _although still need to communicate with related agency_. Would you like to add some comment in here about your classification in here?

Thank you.

**Comment by ismailsunni** [comment]
I think we can close this since we have implemented that smart road impact report.
