### ISSUE TITLE
Improvements to Tsunami impact on roads report

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2691]
### Problem

Tsunami on roads still has a few issues in its reporting:

![selection_006](https://cloud.githubusercontent.com/assets/178003/13848411/56487cde-ec5a-11e5-96fa-be02d0ac1629.png)

![selection_007](https://cloud.githubusercontent.com/assets/178003/13848413/590b555e-ec5a-11e5-9d4a-555bac885d2f.png)
### Expected Behaviour
- Units should be explicit
- Table headings should span all columns
- Aggregation column headings should be in bold
- Aggregation report should be in (m) not number of features
### CC

@Charlotte-Morgan

**Comment by timlinux** [comment]
See also #2680

**Comment by timlinux** [comment]
For the first image above the (m) might be better asa suffix to column headers rather than row headers.

**Comment by Gustry** [comment]
See comment : https://github.com/inasafe/inasafe/pull/2680#issuecomment-198193826
Some fixes are in master : https://github.com/inasafe/inasafe/commit/56a7ef1965de2f63dced204a19b297e34c50280e

Need to frontport to develop

**Comment by Gustry** [comment]
Good evening @Charlotte-Morgan and @timlinux 
How would you like to highlight some columns in the table ? (inundated roads)

**Comment by Gustry** [comment]
So everything has been fixed, except the highlight.

**Comment by timlinux** [comment]
Discussed with Etienne - we will wait for Qt table implementation for dock reporting for doing things like highlighting the flooded columns.

**Comment by ismailsunni** [comment]
I think we will move it to 3.5 @timlinux @Gustry ?
For the Qt Table

**Comment by Gustry** [comment]
We will not do Qt Table anymore. We just need to highlight columns which are affected in the HTML.

**Comment by timlinux** [comment]
Also make group headings span multiple columns:  e.g. "Breakdown by road type"

**Comment by Charlotte-Morgan** [comment]
Here is my attempt at what a table should look like. 
Title with units at the top.
Affected and not affected clearly separated with headings and colour if possible.
Notes further explain things.

If it's not possible to highlight things now - that's fine; the use of headings can solve that.

![image](https://cloud.githubusercontent.com/assets/5743135/16683061/10b113bc-4528-11e6-8e0a-00ab2013eb9a.png)

**Comment by timlinux** [comment]
I moved over to 3.6 - we can add column highlighting then. @Gustry has already made various other tweaks there.

**Comment by Charlotte-Morgan** [comment]
highlighting of columns can be part of standards implementation I think

**Comment by Gustry** [comment]
@lucernae Is there an easy way to highlight some columns in the reporting ?

**Comment by lucernae** [comment]
The easiest way is to apply css class.
What is possible now would be:
- Apply highlighting using css class in jinja2 template
- Double header (Affected, then hazard classes. Not affected, then hazard classes). But, I assume our terminology now is slightly different?

I think we can add it to Reporting Standard, so I can have a reference. Also do we want it to apply to not just roads exposure?

For the unit, I'm quite troubled. How can I get the unit from exposure type definition? Is it already defined now?

**Comment by Charlotte-Morgan** [comment]
Agree - the concept of a double header is already in the standards. Though you are right @lucernae, the terminology might change a little once we refine the way we use affected / displaced

**Comment by Charlotte-Morgan** [comment]
I do not entirely agree with this ticket. We do need to add units but not on the type.

**Comment by timlinux** [comment]
This is done in 4.1
