### ISSUE TITLE
EQ Realtime - feedback on Indonesian disclaimer on the report page

### ISSUE THREAD

**Issue by easmetz** [inasafe/inasafe#2698]
@adelebearcrozier, Anjar and Nugi have supplied feedback on the Indonesian disclaimer on the report page for EQ Realtime.
## cc

@samnawi could you please check what we have as existing disclaimer wording?
@adelebearcrozier do you have any specific feedback from the volcanic ash team?

**Comment by timlinux** [comment]
This is what the Indonesian disclaimer currently looks like:

![screen shot 2016-04-21 at 15 17 32](https://cloud.githubusercontent.com/assets/178003/14710081/42b11196-07d4-11e6-96c6-152027b7253e.png)

There was previously a problem with the text being truncated, but this has since been fixed. Could you confirm if this text needs to be changed?

**Comment by timlinux** [comment]
@samnawi I assigned to you - can you validate the text and provide feedback if it needs to be changed, otherwise close this issue?

**Comment by samnawi** [comment]
Hi @timlinux Is the validation just about the sentences or more than that? I think the Indonesian disclaimer is good, Is the validation just about the sentences or so? I think the Indonesian disclaimer already well as the English version.

**Comment by Charlotte-Morgan** [comment]
@samnawi  - we need to know if the disclaimer makes sense. We had feedback from Adele that the EQ disclaimer was not well written. 

@ivanbusthomi - copying you in here, please comment

**Comment by ivanbusthomi** [comment]
In my opinion, the sentence is quite well written in Bahasa Indonesia. Although i find it a little bit too hard to understand (especially in the 2nd sentence, what do you think mas @samnawi ? ), overall it does make sense. I'll think of an alternative to reword the sentence a bit, so it does less confusing and more clear.

**Comment by timlinux** [comment]
Closing this in favour of the ticket in inasafe-realtime repo
