### ISSUE TITLE
We need a new analysis extents mode to support cases where entire exposure must be used

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2700]
### Problem

Currently with flood polygons on population we can get hard to read reporting because the report shows population numbers for only those census areas that intersect with the hazard.

One way to address this is to add a new extent selector option that will run the analysis at the extent of the exposure layer, thus ensuring that all exposure polygons are included in the population calculations.

This is somewhat illustrated here where you can see that the sum of the pop data is 8000 people (stats panel, bottom left), but the report generate shows only 3000 people in the analysis area because of the cropping effect of the extent setting process.

<img width="1403" alt="screen shot 2016-03-28 at 22 14 09" src="https://cloud.githubusercontent.com/assets/178003/14080988/6e698bec-f532-11e5-8983-e3a8409e2f1a.png">

Proposed new radio button (listed first here):

![screen shot 2016-03-28 at 22 11 08](https://cloud.githubusercontent.com/assets/178003/14080927/18d92368-f532-11e5-9bfa-2d2c75c34a6d.png)
### Expected Behaviour

Unless explicitly running the analysis only for the intersection of exposure, hazard and view, there should be a standard way to include all of the exposure data in the analysis.
### Proposed Solution

Implement the extent selector per the screen shot above.

**Comment by timlinux** [comment]
See https://github.com/timlinux/inasafe/tree/fix-2700

**Comment by Gustry** [comment]
Done in pr above
