### ISSUE TITLE
Review of all dialogues

### ISSUE THREAD

**Issue by easmetz** [inasafe/inasafe#2704]
## Problem

A review needs to be done of all the dialogues in InaSAFE wizard tools, and the help sections.

## Proposed Solution

@easmetz to conduct review and provide feedback

## Progress

- [x] Dock help
- [x] Options
- [x] Minimum Needs Configuration
- [x] Set Analysis Area (extent_selector_help) 31/2/16
- [x] OSM downloader help

![image](https://cloud.githubusercontent.com/assets/16660099/14133611/d722d000-f67a-11e5-9fc4-a12ac4094203.png)

![image](https://cloud.githubusercontent.com/assets/16660099/14133622/f3149208-f67a-11e5-9abe-f59aa8c02d3f.png)

## cc
@timlinux @Charlotte-Morgan

**Comment by timlinux** [comment]
I moved this to 3,6 as I don't think we will be done with this by 3.5. Feel free to correct me if I am wrong.

**Comment by Charlotte-Morgan** [comment]
hi @easmetz  - please give an update on this work. 
@RikkiWeber  - FYI

**Comment by easmetz** [comment]
The dialogues above have been reviewed. In the future I'll make smaller tickets for specific dialogues - I do tend to be continuously reviewing dialogues as new features are added.

**Comment by Charlotte-Morgan** [comment]
Hi @easmetz 
I propose we reopen this ticket and take the milestone off it.
Save it as a high level ticket to track progress, but break the work down to smaller tickets.
ie update IFC Wizard dialogues
Update Options dialogues
etc

**Comment by Charlotte-Morgan** [comment]
Confirming:
options help is complete
dock help is complete
impact function configuration is complete
set analysis area is done
dock help is done

looks like this is all done

Good to go and include in changelog
