### ISSUE TITLE
Impact Report InaSAFE Realtime Flood

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#2714]
Flood:
- remove border from flood hazard
- grayscale the base map
- give thin border to population impacted
- population affected class is rounded
- show district boundaries (Jakarta Timur, Jakarta Barat, Jakarta Utara)
- Use HTML table for disclaimer (justified) and Analysis Result

**Comment by samnawi** [comment]
Hi @lucernae I still see on the map, there are many circles that represent the impacted population.
![image](https://cloud.githubusercontent.com/assets/8871958/14974401/93dde0e6-111e-11e6-8f29-0d92b1d3ef9c.png)

Whether all of the white circle is has a value (I mean the value > 0) ?
If some of the white circle just has 0 value, could we remove them?

**Comment by lucernae** [comment]
@samnawi Yeah, we're aware on this and  currently working on the fix. The template itself is working fine. The white circle is shown because petajakarta had some malformed data and ruining the analysis, so the value is undefined.

**Comment by timlinux** [comment]
Where are we on this @lucernae - can you close it out if you are done?

**Comment by lucernae** [comment]
Closing it. Done.
