### ISSUE TITLE
We need to turn report mixins into simple classes

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2715]
### Problem

We just had a long discussion with @wonder-sk and @Gustry about the use of reporting mixins. Short version is that the consensus is that it would be better to rather implement the reporting as classes that you do not inherit from in the impact function and rather be used as simple object instances that you configure with the impact results and then request a report from.

This will prevent potential side effects of the Impact function state being changed by the mixin and will keep the architecture simpler.
### Expected Behaviour

```
def run()
   # do stuff
   report = BuildingsReport(parameters)
   html = report.html()

```
### Proposed Solution

@Gustry please refactor and apply to develop when you have  a chance.

**Comment by wonder-sk** [comment]
Actually it does not even need to be a class per report (there's nothing else to call apart from 'get output' method) - a simple function would do:
```
html = buildings_report(x=a, y=b)
```

**Comment by timlinux** [comment]
See also #2987

**Comment by Gustry** [comment]
The mixin does not exist anymore in V4.
