### ISSUE TITLE
InaSAFE Realtime Earthquake backlog issues

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#2717]
### Problem

Regarding InaSAFE Realtime Earthquake
Some of the issues discussed with @samnawi :

- [ ] BMKG shakes sometimes inconsistent:
      - [ ] Coming very late (may up to 2 hours late)
      - [ ] Incorrect shake id if compared with event time (example: event id 20160406150255 but event time actually 2016-04-06 21:45:28, also arrived late)
      - [ ] Past shakes sometimes coming (new shakes with past event id)
      - [ ] InAWARE got the warning on time, but grid.xml from BMKG arrived late in InaSAFE Realtime (almost 30 mins)
- [x] Calculate distance for impacted cities and sort from the shortest
- [x] Fix the legend for population

In the future, it is possible that BNPB will be the source of our grid.xml

**Comment by timlinux** [comment]
@lucernae can you try to get these close out before the 3.5 release?

**Comment by lucernae** [comment]
We're closing this. We did our best for inconsistent shakes coming from BMKG. It should be not become our problem again after we switch from BNPB source
