### ISSUE TITLE
Minidump error on closing QGIS 2.14.1 Essen after InaSAFE 3.3.1 installed

### ISSUE THREAD

**Issue by airving61** [inasafe/inasafe#2723]
### Problem
I receive a minidump error on closing QGIS 2.14.1. Uninstalling InaSAFE 3.3.1 solves the problem.
### Expected Behaviour
QGIS should close without a minidump error
### Environment
Windows 7 Pro 64bit
QGIS 2.14.1 64bit
InaSAFE 3.3.1 sourced from QGIS plugin repository
### Proposed Solution

**Comment by Gustry** [comment]
Can you give us this minidump error ? (screenshot, text ...)

**Comment by airving61** [comment]
Attached is a screenshot and a zipped version of the dump file. Hope it helps Thanks.
![2016-04-14_11h19_36](https://cloud.githubusercontent.com/assets/17354350/14524978/28bdcdc0-0233-11e6-9a60-251a86dee050.png)

[qgis-20160414-111922-9212-9296-ea85bef.zip](https://github.com/inasafe/inasafe/files/218888/qgis-20160414-111922-9212-9296-ea85bef.zip)

**Comment by timlinux** [comment]
@Gustry can you take a look at this if you have access to a windows machine? Check with @samnawi if he replicates the issue.

**Comment by timlinux** [comment]
Please back port any fix to master

**Comment by Gustry** [comment]
I couldn't replicate this morning on my laptop : 
* Windows 8.1 Pro 64 bits
* QGIS 2.14.2 64 bits
* InaSAFE 3.3.2

@samnawi Have you got some problems on windows ?

**Comment by samnawi** [comment]
yeah @Gustry I got the same problem.
Using QGIS 2.14.1 and 2.8.8.
InaSAFE develop

![image](https://cloud.githubusercontent.com/assets/8871958/14974758/466df120-1123-11e6-95d7-840898b04484.png)

**Comment by Gustry** [comment]
Everytime you quit QGIS with the cross ?
If you uninstall inasafe, the problem disappears ?

**Comment by NyakudyaA** [comment]
@Gustry  the mini dump seems to occur whenever an IF results in an error and you try to close QGIS. If an IF runs and complete then qgis closes normally. So I think there might be an issue with how to exit an IF when it has error.

OS: Windows 10
Inasafe: 3.5

**Comment by timlinux** [comment]
I tested on windows with 3.5 and can not replicate. If the problem persists, try flushing your registry entries for QGIS and test again. Closing.
