### ISSUE TITLE
InaSAFE Intermediate Ex. errors: OSM Downloader error

### ISSUE THREAD

**Issue by airving61** [inasafe/inasafe#2725]
### Problem
Whilst going through the [Intermediate Exercise] (http://docs.inasafe.org/en/training/socialisation/run_intermediate_inasafe.html) part 2. A using data over Jakarta there is a stage where you are required to download buildings (as polygons) and roads (as lines) from OpenStreetMap. Instead of the expected behaviour the following message appeared:
![2016-04-14_13h27_36](https://cloud.githubusercontent.com/assets/17354350/14530029/07ffd594-024f-11e6-960e-3cea1573459e.png)
Checking through the various logs identified that Network log showed it had apparently timed out
2016-04-14T14:44:41	1	Network request http://osm.inasafe.org/roads-shp?bbox=106.7428816,-6.166286,106.7759688,-6.1362687&qgis_version=21401&inasafe_version=3.3.1&lang=en timed out

But an earlier attempt which had also 'timed out' had manage to download a zipped shapefile of the roads (oddly called roadsroads.shp) despite the timed out message. No building polygons were downloaded.

### Expected Behaviour
Successful download of buildings and roads from OSM into shapefiles, unzipped and placed in correct folders and styled accordingly
### Environment
Windows 7 Pro 64bit
QGIS 2.14.1 64bit
InaSAFE 3.3.1

**Comment by Gustry** [comment]
This problem occurs only with QGIS 2.14.1.
InaSAFE 3.3.2 will be released soon, this bug has been fixed (https://github.com/inasafe/inasafe/commit/2f080f7a2b64b3b44b94fb8eb209dff9c5dfd0b5)

CC : @timlinux
