### ISSUE TITLE
We need to disable or fix scrutiniser

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2728]
So we added scrutiniser to improve our QA but we never really got it configured right. I suggest to either disable it or fix it and configure it nicely.

**Comment by ismailsunni** [comment]
I prefer to disable it first. Make it easier for us to see the PR's status in the list of PR page.

Btw, I have disabled it from scrutinizer (see https://github.com/inasafe/inasafe/pull/2734) . Feel free to fix the config and enable it again.

**Comment by Gustry** [comment]
Thanks Ismail for that. As the title says, I will just keep it open for me to fix scrutiniser later.

**Comment by timlinux** [comment]
Its disabled - we would like to fix it if possible. Also we should look at using coveralls.

**Comment by Gustry** [comment]
We use landscape now
