### ISSUE TITLE
PetaJakarta returns a null for state

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2735]
### Problem

Sometimes PetaJakarta returns a null record for the state column which causes an exception in flood realtime. See http://sentry.kartoza.com/kartoza/inasafe-django/group/6239/

![screen shot 2016-04-21 at 15 37 01](https://cloud.githubusercontent.com/assets/178003/14710746/f58b8c72-07d6-11e6-8b0f-31f6b94f122f.png)

### Expected Behaviour

1. PetaJakarta should return a valid state only
2. We should handle null state gracefully (just treat it as 0)

### Environment

Realtime 

### Proposed Solution

@lucernae please contact Etienne from PetaJakarta about it to let them know of the issue 
@lucernae please add a handler to deal with dodgy state data if possible

**Comment by timlinux** [comment]
We suspect that the issue in the cartography is because of an underlying PetaJakarta issue - @lucernae to investigate - if not file a separate ticket about every Kelurahan having a dot even if it is not flooded:

![screen shot 2016-04-21 at 15 42 10](https://cloud.githubusercontent.com/assets/178003/14711043/1ef2efd2-07d8-11e6-8486-e65c8c4c9c4e.png)

See http://realtime.inasafe.org/media/reports/flood/pdf/impact-map-en_CmhHwPW.pdf for an example

**Comment by timlinux** [comment]
Update from Tom Holderness

> Hi Rizky,

> Well spotted. Yes there was a bug in our API which we pushed a fix too about a week ago. Apologies I was travelling and forgot to send you a note. 

> Null and 0 both indicate that there is no flooding in the RW. But, Null is different to 0 because it indicates that RW has never been marked as flooded during the current monsoon season, whereas 0 indicates that the area was previously flood affected (hence the “last_updated” field will contain a date time to indicate when the flooding stopped).

> Does that make sense? Drop me a note if it is still unclear.

> Many thanks,

> Tomas

**Comment by Charlotte-Morgan** [comment]
So 0 and null should be treated the same - ie not affected

**Comment by lucernae** [comment]
Done.
