### ISSUE TITLE
We should render realtime PDF's as vectorised PDF not rasterised

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2736]
### Problem

When we get a report from Realtime we cannot cut and paste text from it. This is inconvenient and leaves one vulnerable to copy & paste errors.
### Expected Behaviour

If possible it would be nice to have the PDF's rendered as vectorised. The map would still be an image but the tables etc would be text that can be copy & pasted.
### Proposed Solution

@lucernae to investigate setting composer to vector mode not roaster mode before rendering. @Gustry provide support if needed.

**Comment by lucernae** [comment]
I already put some research on this, and I can't find the settings in composer. Also I treat this as low prio.

**Comment by timlinux** [comment]
![screen shot 2016-08-08 at 12 41 55 pm](https://cloud.githubusercontent.com/assets/178003/17477441/a1dd65a2-5d65-11e6-90ee-0266df36e3fa.png)


@lucernae The option is in the composition properties panel - just make sure 'print as raster' is unticked.

**Comment by timlinux** [comment]
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.
