### ISSUE TITLE
Analysis result etc. in flood realtime should be formatted in a table rather

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2737]
### Problem

In realtime the analysis results section can we please organise the data more nicely into a table

**Comment by ivanbusthomi** [comment]
Reposting this from gitter chat, just for the record and easier reference.

I think it should looks like one of these
* three columns
![three](https://cloud.githubusercontent.com/assets/7351977/15201423/01b9d6b2-181b-11e6-9008-9fa942fa8851.PNG)

* two columns
![two](https://cloud.githubusercontent.com/assets/7351977/15201424/01bc039c-181b-11e6-948b-fef48d635e5e.PNG)

**Comment by lucernae** [comment]
Done
