### ISSUE TITLE
Update Structure and Road Class Mapping

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#2740]
### Problem
Currently we still use the old class for structure and road.

### Expected Behaviour
There is a proper class for structure and report.
Please refers the new structure class from https://github.com/inasafe/inasafe/pull/2721#issuecomment-212767381

And for road : https://github.com/inasafe/inasafe/issues/2682#issuecomment-196786570

@samnawi can you check whether the road is in final status or not

**Comment by samnawi** [comment]
Hi @ismailsunni I just have a quick discuss with @harrymahar, he says that the classification in this [link](http://wiki.openstreetmap.org/wiki/Id:Jalan) is still not in final status. 
The BIG website already online again. In this [link on page 13 & 14](http://www.bakosurtanal.go.id/assets/download/sni/SNI/18.%20SNI%206502.2-2010%20Spesifikasi%20penyajian%20peta%20rupa%20bumi%2025.000.pdf), there is a road classification of RBI map from BIG and the classification that I propose in this [comment #2682](https://github.com/inasafe/inasafe/issues/2682#issuecomment-196786570) have a bit similar with that classification. This is the classification.
**1. Jalan Tol / Motorway**
Jalan untuk mengatasi kemacetan dan untuk melewatinya harus membayar sesuai tarif yang berlaku.
A road to solve the traffic and have a fare.
**2. Jalan Arteri / Primary**
Jalan yang melayani angkutan utama dengan ciri-ciri perjalanan jarak jauh dan kecepatan rata-rata tinggi.
A road that service the main transportation with a long distance travel characteristic and high average velocity.
**3. Jalan Kolektor / Secondary**
Jalan yang melayani angkutan dengan ciri-ciri perjalanan jarak sedang dan kecepatan rata-rata sedang.
A road that service the transportation with a medium distance travel characteristic and medium average velocity.
**4. Jalan Lokal / Local**
Jalan yang melayani angkutan setempat dengan ciri-ciri perjalanan jarak dekat dan kecepatan rata-rata rendah.
A road that service the transportation with short distance travel and low average velocity. 
**5. Jalan Lain / Other**
Jalan yang melayani angkutan setempat dengan ciri-ciri perjalanan dekat and kecepatan rata-rata rendah.
A road that service the transportation with short travel and low average velocity.
**6. Jalan Setapak / Track / Path**
Jalan khusus pejalan kaki.
A road to walk on foot aim.

Thank you.
