### ISSUE TITLE
Repeated figures in some reports

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2746]
### Problem
In the example below, the purple rectangles are exactly the same. In addition, if you don't use an aggregation layer, the red rectangles are repeated too.
![selection_072](https://cloud.githubusercontent.com/assets/1609292/14851283/11c04d52-0ca9-11e6-8af7-ef4334391205.png)

### Expected Behaviour
If we have less tables, it will make the report more readable for the final user.

### Proposed Solution
I wonder why do we have the first purple table and if we can remove it in that case.
For the red table 2, this one becomes useful only with we use an aggregation layer. If we don't use an aggregation layer, I wonder if we can skip it.

**Comment by ismailsunni** [comment]
+1 for this.
Currently working in the impact data, and there are many duplication. I have successfully made myself confused.

**Comment by timlinux** [comment]
Yes I agree it would be a lot simpler to have just the one table in this specific case. Note that historically there is this split between impact summary (shown on map report), impact table (shown in tabular report) and aggregation summaries (shown in tabular report). In the dock we show all three in one place. In the map composition we separate them into different places.

@Charlotte-Morgan can comment here but I think with @ismailsunni 's new work we could have the dock show only the impact table in some cases, but we need to pick carefully through each IF and make sure we don't miss out on reporting important stats if we do this.

**Comment by timlinux** [comment]
@ismailsunni thinks he has taken care of this - assigning to him to double check and close if possible,

**Comment by Charlotte-Morgan** [comment]
+1 for removing duplication
see #2920 for some ideas on revamping reports to address this and a multitude of other issues

**Comment by ismailsunni** [comment]
hi @timlinux
I have checked this, and it seems I haven't removed this.
After checking again, I have a thought to not aggregate the impact if it's use `entire area` since the result should be the same as the impact summary or impact tables. By doing this way, we can save more time since we don't do the aggregation.
We just need to change the option from `entire area` to `not using aggregation` and skip the aggregation in the code.
What do you think?
There should be a historical notes why we put `entire area` in the option.

**Comment by timlinux** [comment]
The only catch @ismailsunni is that I think the post processors won't run if we do not aggregate (which is why we have aggregation by entire area).

**Comment by Gustry** [comment]
Yes, but why do we need post processors if we don't have an aggregation layer ? (for roads and buildings)

**Comment by timlinux** [comment]
> Yes, but why do we need post processors if we don't have an aggregation layer ? (for roads and buildings)

Short answer: I don't think we do - we need to refactor the post processors into the main IF function - lets address it then...
