### ISSUE TITLE
WP Plugins not working after update

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2749]
### Problem

I upgraded to WP 4.5.1. After upgrading some of the plugins are not working / upgradable.

<img width="1219" alt="screen shot 2016-04-28 at 23 30 50" src="https://cloud.githubusercontent.com/assets/178003/14902146/733c5cd8-0d99-11e6-9c62-076306f7c910.png">
### Proposed Solution

@MariaSolovyeva can you please investigate and fix?

**Comment by MariaSolovyeva** [comment]
Hello @timlinux , yes the subscription for WPML has finished. 
The plugin is still working, just it cannot get the new updates. 
The **security updates** are still available for manual download.

So there are few options for us:
- don't purchase it again and download the security updates
- purchase one year subscription $79 (then to renew it it will cost $29 per year, if to pay it before subscription has finished)
- upgrade it to lifetime subscription $116

Let me know what you think

**Comment by timlinux** [comment]
I'm closing this - I rolled back to an older version of WP for now. In the next contract I would like to rethink our website strategy a bit. Perhaps migrate to mezzanine so it can be part of our standard web stack along with geonode, geosafe and realtime...
