### ISSUE TITLE
New QGIS projects

### ISSUE THREAD

**Issue by uniomni** [inasafe/inasafe#275]
This is a suggestion from Kristy which I think is great:

Create new QGis projects - one for each area and name them accordingly. Two benefits
- they don't need translation
- they represent an area based, multihazard approach

Then go through each project and check that 
- It loads seemlessly (i.e. no complaints about missing layers, qgis version, ...)
- Translation is OK
- All input layers have good styles
- All output layers have good styles
- Outputs and reports make sense

Then 
- Create a screenshot of each
- Document them all in the User Guide: docs/source/user-docs/inasafe_projects.rst.
  Since this will both create html and pdf for use in QGIS, perhaps we could have links to the projects so that they can be clicked   and open in QGIS.

**Comment by timlinux** [comment]
Closed as old
