### ISSUE TITLE
Notes and Action List for Land Cover IF

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#2764]
### Problem
Currently in develop, there is land cover IF but it doesn't have any action list and notes.

### Expected Behaviour
The impact report from the Land Cover IF should show notes and action list.

### Proposed Solution
Create one.

### CC
@samnawi @Charlotte-Morgan @timlinux

**Comment by Charlotte-Morgan** [comment]
hi @fredychandra - I'm assigning this to you.
Please draft up some actions similar to the action lists you prepared for other IF and work with @samnawi to make a list of relevant notes and assumptions.

Where possible use existing notes / assumptions and actions as a starting point. 
I am happy to help tweak the english if needed.

**Comment by fredychandra** [comment]
Hi @Charlotte-Morgan , Here the proposed draft for the action checklist, please revise as proper English tone and sense. 

-  What type of vegetation that planted in affected crops/fields ?
-  How long (duration) the function of land cover will be disturbed?
-  How the severity of the land cover damage? (percentage affected area from total area)
-  How many potential loss from the land cover damage? ( e.g 1 Ha rice field = 30 ton rice/one harvest period)
-  How many productivity values from crops/field will be losing during this event?
-  Which crops is in harvest period during this event?
-  How the ownership system of the land/crops/field?
-  Are the land/crops/field accessible after the event?
-  What is the urgent action  to normalize the land/crops/field?
- what tools or equipment need for early recovery to the land/crops/field?

**Comment by timlinux** [comment]
Here is my first pass (to fix the English)

* What type of vegetation is planted in affected crops/fields ?
* How long (duration) will the activity or function of the land cover will be disturbed?
* How severe is the land cover damage? (percentage affected area from total area)
* What potential losses will be incurred by the land cover damage? ( e.g 1 Ha rice field = 30 ton rice/one harvest period)
* How much productivity in the crops/fields will be lost during this event?
* Which crops were in harvest period during this event?
* What is the ownership system of the land/crops/field?
* Are the land/crops/field accessible after the event?
* What urgent actions can be taken to normalize the land/crops/field?
* What tools or equipment are needed for early recovery of the land/crops/field?

**Comment by Gustry** [comment]
I made a first PR https://github.com/inasafe/inasafe/pull/2826 to add the action list.
We can still tweak these strings later if we need.

**Comment by Charlotte-Morgan** [comment]
Please use this action list (apologies @fredychandra if I have misunderstood anything)

What type of crops are planted in the affected fields ?
How long will the activity or function of the land cover be disturbed?
What proportion of the land cover is damaged?
What potential losses will result from the land cover damage? 
How much productivity will be lost during this event?
Which crops were ready for harvest during this event?
What is the ownership system of the land/crops/field?
Are the land/crops/field accessible after the event?
What urgent actions can be taken to normalize the land/crops/field?
What tools or equipment are needed for early recovery of the land/crops/field?

**Comment by Gustry** [comment]
Thanks @Charlotte-Morgan I've updated the strings in my PR.
Just for informations, these strings are only checklist, not notes. The notes are still empty.

**Comment by Charlotte-Morgan** [comment]
@Gustry - noted that there are no notes :)
the notes should be populated (by the developer) to say what is assumed or how data are handled ie no data and zeros.  We will get back to you on this one.

**Comment by Charlotte-Morgan** [comment]
Notes have been updated and are in pr #2845

**Comment by ismailsunni** [comment]
Closed in #2485
