### ISSUE TITLE
No data in the json impact

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2769]
### Problem

Running Floods on Roads aggregated by the grid in the test data, I got this error : 

```
Problem
The following problem(s) were encountered whilst running the analysis.
ValueError

Details
These additional details were reported when the problem occurred.

Error loading impact layer.
invalid literal for int() with base 10: 'No data *'
Diagnostics

In file "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1362, in completed report = self.show_results()
In file "/home/etienne/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1420, in show_results impact_report = impact_template.generate_message_report()
In file "/home/etienne/.qgis2/python/plugins/inasafe/safe/impact_template/road_report_template.py", line 64, in generate_message_report message.add(self.format_postprocessing())
In file "/home/etienne/.qgis2/python/plugins/inasafe/safe/impact_template/template_base.py", line 153, in format_postprocessing row.add(m.Cell(format_int(int(value))))
```

This error is raised with area D in the grid. It doesn't contain any roads.
# Proposed solution

In PR https://github.com/inasafe/inasafe/pull/2743
![3858](https://cloud.githubusercontent.com/assets/1609292/15064960/963117f8-135a-11e6-87a9-ac0e3a6c76e6.png)

**Comment by Gustry** [comment]
BTW, I can't find the * statement about no data in the report.

**Comment by timlinux** [comment]
Since the table is encoded as numerical data, would it not be better to use a convention of e.g. -1 to indicate no data? And then convert the -1 to text when we render html. CSV and other formats could retain it as numerical data?

**Comment by Gustry** [comment]
I found this issue related to no_data : https://github.com/inasafe/inasafe/issues/2318

Should we keep "no data" when there is not roads in the aggregation area ?

**Comment by Gustry** [comment]
We can now close this ticket with inasafe v4.
