### ISSUE TITLE
Use PivotTable for all Impact Data

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#2772]
### Problem

Currently impact functions have quite different data output. It makes the development quite difficult since there are many case.
It would be great if we have general / uniform impact data, and we can use PivotTable and FlatTable to process the data after that.

Please see land cover IF for the example.

**Comment by Gustry** [comment]
When we create a pivot table, we need to give the list of columns (Low, Medium, High for instance).
We should be able to set columns which are affected or not and to ask the sum for affected.

**Comment by Gustry** [comment]
Maybe we should have a look at this one while we are refactoring the ReportMixin https://github.com/inasafe/inasafe/issues/2746

**Comment by Gustry** [comment]
This is not relevant in V4, we use the pivot table in the waterfall. (summary calculation)
