### ISSUE TITLE
Wiki Page for JSON Impact Data

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#2774]
### Problem

Currently, we have impact data implementation and it's written in json. We should have a wiki page explaining about this so that people who want to use the impact data JSON can use it easily.

**Comment by timlinux** [comment]
Yes please! Thanks @ismailsunni

**Comment by Gustry** [comment]
We don't have JSON anymore in version 4.
I will close this ticket until we revamp JSON.
