### ISSUE TITLE
Symbol for Land Cover in Wizard

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#2778]
### Problem
Currently, in develop we do not have symbol for land cover. 

### Expected Behaviour
There is a symbol for land cover.

### Proposed Solution
Does anyone know which symbol we should use for land cover?

cc @timlinux @Charlotte-Morgan @samnawi @borysiasty

**Comment by Charlotte-Morgan** [comment]
hi @felix-yew 
I would like you to work on this please. If possible use any standard symbology used by BIG or BNPB for landcover maps.  When you make a symbology in QGIS, please save and share the definition file.

**Comment by felix-yew** [comment]
Hi @Charlotte-Morgan @ismailsunni 

That's great, I will try to create some supporting symbology. After I finished, I will share with the team.

**Comment by ivanbusthomi** [comment]
I've talked with @felix-yew earlier about this, and apparently we couldnt find any suitable symbol in OCHA Humanitarian Icons for GIS

**Comment by felix-yew** [comment]
Yup, maybe we can modified the OCHA Humanitarian Icons for GIS. I have discussed with Mas Faisal (UNOCHA) about it and he suggest to modified symbol from other source that support the theme, i.e. from thenounproject. And I will have create it. I will share to the team, after I have finished the symbol.

**Comment by Charlotte-Morgan** [comment]
hi @felix-yew 
Apologies - i think there are two issues here.
1. an icon for landcover exposure data. @MariaSolovyeva is the person who makes these for the InaSAFE project. Can you please share your idea with her so that she can 'make it beautiful' like all the other icons.
2. standard symbology for a landcover map layer in a QGIS project - this is something I think we still need and you can work on this please.

**Comment by ismailsunni** [comment]
hi @Charlotte-Morgan 
Perhaps we can create separate issue for your second point above.

@felix-yew 
If you have find one, just post it here, so the other can give some feedback.

**Comment by felix-yew** [comment]
Hi @Charlotte-Morgan 

Sorry, I have writen a ticket #2784 about updating the InaSAFE postcard that related to create a new best icon for landcover exposure data. 

Hallo @MariaSolovyeva there are some example from thenounproject
![noun_387027_cc](https://cloud.githubusercontent.com/assets/13621886/15175665/a4523ba6-1791-11e6-8ccc-e3956a85cbb5.png)

![noun_46925_cc](https://cloud.githubusercontent.com/assets/13621886/15175694/ca493d00-1791-11e6-9acf-38e01efe8f93.png)
This icon is representing icon of plant.

And, there are some example from UNOCHA icon
source : [OCHA_Icons_User_Guide_v2.0.pdf](https://github.com/inasafe/inasafe/files/258963/OCHA_Icons_User_Guide_v2.0.pdf)

![other_cluster_environment_100px_icon](https://cloud.githubusercontent.com/assets/13621886/15175729/f1641df6-1791-11e6-829f-025300e36afe.png)
This icon is representing icon of agriculture.

![other_cluster_agriculture_100px_icon](https://cloud.githubusercontent.com/assets/13621886/15175740/f72b6b40-1791-11e6-8f5d-dffda0ac1e4f.png)
This icon is representing icon of environment.

Maybe, you can modify one of them in to a new best icon in InaSAFE :smile: that representing icon of landcover and can be used in a InaSAFE wizard and postcard.

**Comment by Charlotte-Morgan** [comment]
nice

**Comment by timlinux** [comment]
@felix-yew Thanks I gave @MariaSolovyeva a mention in our Skype chat to take a look at this. @ismailsunni can you add Maria to the GitHub team so we can assign tasks to her?

**Comment by ismailsunni** [comment]
@timlinux 
Yes, I have made an invitation for @MariaSolovyeva, please accept it.

Btw, I just read about the membership and collaborating article in github, https://help.github.com/articles/repository-permission-levels-for-an-organization/ Perhaps, in the future, we should use it more properly. For example add temporary person to outside collaborator, rather a member of a team. Anyway, it's not too urgent :)

**Comment by MariaSolovyeva** [comment]
Hello @ismailsunni , thank you, I have joined!

**Comment by Charlotte-Morgan** [comment]
Hi @MariaSolovyeva 
Great to have you working on this with us. Please make a land cover icon using one of the suggested symbols above to match the other exposure icons for InaSAFE. Thank you

**Comment by MariaSolovyeva** [comment]
Hello @Charlotte-Morgan , @felix-yew   and @timlinux ,

Here are few variants of land cover icon, let me know what you think!

![land_cover](https://cloud.githubusercontent.com/assets/10400420/15283793/d8e384f2-1b55-11e6-868b-afcd9e291f84.png)

**Comment by felix-yew** [comment]
Hi @MariaSolovyeva 

Thank you for your creative work, very beautiful icon :+1: :+1: :+1: 

I will choose ![image](https://cloud.githubusercontent.com/assets/13621886/15283944/63690c56-1b78-11e6-9698-03481e629ac3.png) because it is representing the land cover icon :smile:

**Comment by Gustry** [comment]
Me too ! Let's try to vote with github emoji. First logo first emoji, second logo second emoji ;-)

**Comment by samnawi** [comment]
:+1:

**Comment by ivanbusthomi** [comment]
:+1: :+1: :+1:  :point_left: i'm voting for 3rd logo :smile:

**Comment by MariaSolovyeva** [comment]
Thank you @all ! stopping on the third one :smile:

**Comment by ismailsunni** [comment]
ouch, I am too late to vote :) But the 3rd one is also my choice, nice icon

**Comment by timlinux** [comment]
3rd looks nice - good choice!

**Comment by ismailsunni** [comment]
Closed in #2805

**Comment by Gustry** [comment]
I'm going to reopen this issue.
We need the landcover icon in the same style as the other icons. @MariaSolovyeva Can you provide the leaf in black, without any borders ?
![3858](https://cloud.githubusercontent.com/assets/1609292/15499999/18de6606-21a7-11e6-8c45-270a8406de0c.png)

**Comment by Charlotte-Morgan** [comment]
And higher resolution would be good too.

Charlotte  Morgan
Spatial Data Analyst
DMInnovation - Jakarta
GEOSCIENCE AUSTRALIA

Mobile: +61 412 949642
Mobile: +62 8118204648


On 24 May 2016, at 5:19 PM, Etienne Trimaille <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm going to reopen this issue.
We need the landcover icon in the same style as the other icons. @MariaSolovyeva<https://github.com/MariaSolovyeva> Can you provide the leaf in black, without any borders ?
[3858]<https://cloud.githubusercontent.com/assets/1609292/15499999/18de6606-21a7-11e6-8c45-270a8406de0c.png>

-

**Comment by MariaSolovyeva** [comment]
Hello @ismailsunni , I've  just sent you a letter with SVG

**Comment by ismailsunni** [comment]
New icon from @MariaSolovyeva 

<img width="111" alt="screen shot 2016-05-25 at 18 20 50" src="https://cloud.githubusercontent.com/assets/1421861/15538363/de625fe6-22a5-11e6-9593-c102565e3b72.png">

I made a PR for this: #2848

**Comment by Charlotte-Morgan** [comment]
Nice.

On 25 May 2016, at 6:21 PM, Ismail Sunni <notifications@github.com<mailto:notifications@github.com>> wrote:


New icon from @MariaSolovyeva<https://github.com/MariaSolovyeva>

[screen shot 2016-05-25 at 18 20 50]<https://cloud.githubusercontent.com/assets/1421861/15538363/de625fe6-22a5-11e6-9593-c102565e3b72.png>

I made a PR for this: #2848<https://github.com/inasafe/inasafe/pull/2848>

-

**Comment by ismailsunni** [comment]
ok, merging the PR then.
