### ISSUE TITLE
Impact Function for Realtime Flood reporting incorrect value

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#2781]
### Problem

<img width="599" alt="screen shot 2016-05-11 at 05 40 35" src="https://cloud.githubusercontent.com/assets/831865/15165025/f9af7d0c-173c-11e6-83ba-060a2abd6f1c.png">

Too many affected people. Almost 95%

### Expected Behaviour

Don't count area where the hazard are state 0 or 1 or it is null

### Environment

Realtime Flood

### Proposed Solution

The current way affected people being calculated is by summing all the people in the 
"low", "medium", and "high" category. Since now state 0 and 1 (not flooded or not inspected) is categorized as low class flood, then the number contributed to the affected people. But, it is not make sense that we count them as affected. 
To solve this, we can take different approach:

1. Create another category/hazard class called "unaffected". Then make state 0 and 1 classified as "unaffected". Correct the calculation by only calculating "low", "medium" and "high" class as affected people.
2. Strip the hazard layer from any polygon with state 0 or 1 or null value. Classify state 2,3 and 4 as "low", "medium", and "high" respectively. Then proceed as usual. No modification in the IF needed.
3. Make more generic approach. Create more generic classification where we can dynamically specify the class to calculate. Then we can just put null value as "unaffected" class, state 0,1,2,3,4 as their own class respectively (without using "low", "medium", "high" classification). But we have to modify the report and calculation in the IF to reflect this. For example, displaying total affected population in each class and also unaffected population as well (which is taken from the any state value outside the classification, like Null or None).

CC @Charlotte-Morgan @timlinux Which is best to suit our need?

This is also indirectly related with: #2735 
Based on the reply from Tomas, we should expect a null value for the state field returned by PetaJakarta and properly classified it as "unaffected".

**Comment by Charlotte-Morgan** [comment]
hi @lucernae 
I agree that the affected is too high.  I think we need to check with @samnawi too for his understanding of BPBD DKI Jakarta requirements, but from me I like your suggestion 2 above.

We need to make sure the notes explain how null, 0 and 1 have been handled.

**Comment by timlinux** [comment]
Thanks for your inputs here @lucernae! I agree with @Charlotte-Morgan that 2 above is a nicer approach. And we provide the download shapefile with just the affected polygons too so that you don't need to do hiding of unaffected polygons in the symbology.

**Comment by timlinux** [comment]
Can you update this issue with the current status please @lucernae ?

**Comment by lucernae** [comment]
Done with approach 2. Conclusion:

We're not counting null, 0, and 1 value.
