### ISSUE TITLE
EQ Realtime Tweaks

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2783]
Hi @lucernae 
some of the recent changes you have made to EQ realtime page look great.
I really like the filter on size and limited number of reports on the front page. 
Here are a few suggested tweaks for the english. I hope this is easy for you. We will demo this at UR 2016 next week and I am making some screenies today.

**In the context filter**
![image](https://cloud.githubusercontent.com/assets/5743135/15174510/399d9ba2-178c-11e6-9e70-6eab600188c0.png)
Please make it say "Recent Large Earthquakes"  and "Recent Small Earthquakes"

Would it also be possible to manage future events by making the default filter have todays date

**In the map title**
![image](https://cloud.githubusercontent.com/assets/5743135/15174582/80d5ed80-178c-11e6-98a2-1f488b89ed3e.png)
I suggest "Earthquake events with magnitudes greater than or equal to 5 since <date>"
and
"Earthquake events with magnitudes less than 5 since <date>"

**The product title**
we all call this earthquake realtime but I see its called shake map and InaSAFE Shake Realtime
is this something we want to change?
![image](https://cloud.githubusercontent.com/assets/5743135/15174865/e4153170-178d-11e6-9f5a-6aab72b4e564.png)

@easmetz @ivanbusthomi @timlinux

**Comment by lucernae** [comment]
Putting this on my to do list.

About the product title, previously it just says "Map". But since we also have Flood Realtime, I put two different name there.
We can just choose which one we want. Maybe "Earthquake Realtime" will do for both title?

**Comment by ivanbusthomi** [comment]
@lucernae the things we discussed earlier regarding the "upcoming" earthquake
![papua](https://cloud.githubusercontent.com/assets/7351977/15175872/9738bda4-1792-11e6-860f-6a0d27123c30.PNG)
have you edited the data?how long does it take to refresh?

**Comment by lucernae** [comment]
@ivanbusthomi I haven't. I'm still busy with the flood realtime. I will try to sort that out by tomorrow.

**Comment by Charlotte-Morgan** [comment]
+1 for Earthquake Realtime

**Comment by timlinux** [comment]
@Charlotte-Morgan or maybe even better 'Realtime Earthquake', 'Realtime Flood'

Also we should put the 'near realtime' caveat in bold to make it clearer that there is a lag.

The top box on the page could are retitled 'InaSAFE Shake Realtime' -> 'InaSAFE Realtime Earthquake Reports'

**Comment by timlinux** [comment]
@lucernae can you update the status here please and either close if done or set the milestone to 3.6

**Comment by lucernae** [comment]
I've changed the contextual filter text, the map title, the upcoming report.

So, minus:
- [ ] near realtime caveat in bold
- [ ] Retitle page to --> InaSAFE Realtime Earthquake Reports
- [ } Earthquake Realtime as menu title

**Comment by timlinux** [comment]
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.
