### ISSUE TITLE
Update the new InaSAFE Postcard

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#2784]
### Problem
We have run out of postcards!!
We need to print some more. 
Should we make some small updates in the 'InaSAFE postcard' ?

### Expected Behaviour
Some things we could change:

1.Some icon in Hazard, maybe can add the Volcanic Ash and the Generic Hazard icon, I think it is important because we already have this IF in current version.

![image](https://cloud.githubusercontent.com/assets/13621886/15175866/8ac16396-1792-11e6-830a-57fb4b0b1597.png)

2.in Exposure, can add the Land cover icon
![image](https://cloud.githubusercontent.com/assets/13621886/15175975/1b3fe596-1793-11e6-9aac-2552d58f8f79.png)

The land cover icon is the new one for exposure data type, some options for a new landcover icon are presented in #2778 
-------------------------------------------------------------------------------------------------------------------------------
There are some example from thenounproject
![noun_387027_cc](https://cloud.githubusercontent.com/assets/13621886/15175665/a4523ba6-1791-11e6-8ccc-e3956a85cbb5.png)

![noun_46925_cc](https://cloud.githubusercontent.com/assets/13621886/15175694/ca493d00-1791-11e6-9acf-38e01efe8f93.png)

And, there are some example from UNOCHA icon
source : [OCHA_Icons_User_Guide_v2.0.pdf](https://github.com/inasafe/inasafe/files/258963/OCHA_Icons_User_Guide_v2.0.pdf)

![other_cluster_environment_100px_icon](https://cloud.githubusercontent.com/assets/13621886/15175729/f1641df6-1791-11e6-829f-025300e36afe.png)

![other_cluster_agriculture_100px_icon](https://cloud.githubusercontent.com/assets/13621886/15175740/f72b6b40-1791-11e6-8f5d-dffda0ac1e4f.png)

Maybe, we can modify one of them in to a new best icon in InaSAFE :smile: that can be used in a InaSAFE wizard and postcard

3.And @Charlotte-Morgan how about the logos in the postcard, because I still see the AIFDR logo in there, should we change it to DMInnovation?

4.Does anyone else have something that needs to be updated

### Proposed Solution
Make it happy :smile: 

Cc: @timlinux @MariaSolovyeva @dewisulistio

**Comment by timlinux** [comment]
@MariaSolovyeva will you take care of this?

**Comment by timlinux** [comment]
@MariaSolovyeva Obviously pending feedback from @Charlotte-Morgan before you go ahead with anything

**Comment by MariaSolovyeva** [comment]
Hello @all, I will care of it, awaiting for the feedback!

**Comment by dewisulistio** [comment]
Hello @MariaSolovyeva, I think the post card color can be changed with combination blue, black, and white like the new InaSAFE version. 
I am sorry, We need to print the new post card for exhibition in Bandung and Turkey, which are held in the next weekend. Also we're gonna use the design for the new sticker. The printing and cut process is 4-5 workdays.
Thank you for understanding

**Comment by Charlotte-Morgan** [comment]
hi @MariaSolovyeva @dewisulistio @fredychandra @samnawi @timlinux 
A few points from me:

1. we have run out of post cards in Indonesia and need more printed by the end of the week (21 May 2016)
2. we can take this opportunity to make some updates / fix errors
3. priorities from my perspective:

- add landcover icon

- add volcanic ash icon

- update logos

I am very reluctant to make other major changes such as colour schemes etc as this is a lot more work, becomes a different produce and probably needs input from @timlinux and others who are not available in the next week. To me this falls out of the 'keep it simple' priority for an urgent print run.

@dewisulistio - what impact would a multi colour product have on printing costs and turnaround time?

If there are suggestions for a 'second postcard design'  please write a ticket and allow time for feedback from the InaSAFE community.

**Comment by Charlotte-Morgan** [comment]
@MariaSolovyeva 
For the logos: we should remove the AIFDR logo and add the DMInnovation logo, 
Refering to the DFAT guidelines http://dfat.gov.au/about-us/corporate/Pages/branding-aid-projects-and-initiatives.aspx may I suggest the following logos in the following order left to right.
BNPB (no change), DMInnovation (use the round one to replace the AIFDR logo), Skippy (replace Australian Govt crest with this), WB - GFDRR (no change).

Justification for this advice - GoA crest should only be used if another government crest is used. according to link above.

**Comment by timlinux** [comment]
Just a quick note to say that for UR 2016 I still have a heap of the old cards.

**Comment by Charlotte-Morgan** [comment]
Thanks Tim
We are completely out and have events coming up in Indonesia and WHS.

Charlotte  Morgan
Spatial Data Analyst
DMInnovation - Jakarta
GEOSCIENCE AUSTRALIA

Mobile: +61 412 949642
Mobile: +62 8118204648


On 15 May 2016, at 5:16 AM, Tim Sutton <notifications@github.com<mailto:notifications@github.com>> wrote:


Just a quick note to say that for UR 2016 I still have a heap of the old cards.

-

**Comment by MariaSolovyeva** [comment]
Hello @Charlotte-Morgan , here is the logo part, am I correct with the skippy logo choice?

![sponsors](https://cloud.githubusercontent.com/assets/10400420/15286658/e787f9e6-1b66-11e6-8cce-7060352eb58e.png)

**Comment by MariaSolovyeva** [comment]
hi @all , here is the version with the volcanic ash and the land cover icons added, let me know what you think
![postcard-back2016-en](https://cloud.githubusercontent.com/assets/10400420/15286731/57ae5daa-1b67-11e6-8299-d78a571bbf42.png)

**Comment by Charlotte-Morgan** [comment]
Hi Maria
I do not see the skippy logo.
Please remove the Australian government crest and use the Australian Aid logo. The one with the words Australian Aid and a picture of a kangaroo.
Thank you
Charlotte

Charlotte  Morgan
Spatial Data Analyst
DMInnovation - Jakarta
GEOSCIENCE AUSTRALIA

Mobile: +61 412 949642
Mobile: +62 8118204648


On 16 May 2016, at 12:02 PM, MariaSolovyeva <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @Charlotte-Morgan<https://github.com/Charlotte-Morgan> , here is the logo part, am I correct with the skippy logo choice?

[sponsors]<https://cloud.githubusercontent.com/assets/10400420/15286658/e787f9e6-1b66-11e6-8cce-7060352eb58e.png>

-

**Comment by MariaSolovyeva** [comment]
Hello @all, 

Thank you @Charlotte-Morgan,

I created new PR to add the postcard to inasafe-graphics https://github.com/inasafe/inasafe-graphics/pull/4
@timlinux  , can you merge it please?

Before merge, you can already use the files from PR

Let me know if you need something else,
All the best

**Comment by dewisulistio** [comment]
Thanks @MariaSolovyeva
