### ISSUE TITLE
We need to update the dock text

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2787]
There are so many fantastic additions to InaSAFE that we need to remove some of the limitation statements 

eg statement 2 about polygon area analysis and statement 4 about population by admin boundaries 
:)

**Comment by timlinux** [comment]
Whoo yeah, good point!

**Comment by timlinux** [comment]
I removed the obvious out of date stuff. We might want to do another round of edits where we add any new limitations for the user to be aware of....but I will leave it as-is for now.
