### ISSUE TITLE
Wrong projection for the impact layer if the input is 3857

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2790]
### Problem
If the input layer is in 3857, the impact layer will be in 54004.
It seems to be a QGIS/OGR problems : 
https://hub.qgis.org/issues/11134

### Proposed Solution
* Fix in QGIS/OGR
* Or as a quickhack, hardcode the reprojection in inasafe

![3858](https://cloud.githubusercontent.com/assets/1609292/15235978/5c5a1a8a-18ea-11e6-8815-788032a5f32d.png)

**Comment by Charlotte-Morgan** [comment]
hi @Gustry - I'm just chasing some projection issues I have noticed here - the lads will update you once we work out what the problem is
@felix-yew @samnawi @timlinux

**Comment by Gustry** [comment]
@Charlotte-Morgan I provided just a quick fix in PR a few minutes ago. This fix is related to a bug in QGIS when we run an algorithm with a layer in 3857.

I plan to clean and uniform the projection in inasafe for the next release (maybe 3.5).

**Comment by Charlotte-Morgan** [comment]
thank - no issue here for now. problem was between the chair and the keyboard :)

**Comment by ismailsunni** [comment]
Btw, is this specific to 3857 only?

**Comment by Gustry** [comment]
I think so, according to the QGIS ticket, it seems that QGIS is confused between 3857 and 54004 : https://hub.qgis.org/issues/11134
