### ISSUE TITLE
Remove Volcano point

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2793]
### Problem
For now, we have duplicate IF : 
* Volcano point on buildings VS volcano polygon on buildings
* Volcano point on population VS volcano polygon on population

Since https://github.com/inasafe/inasafe/pull/2716 we polygonize volcano points in the `prepare` method and not in the IF itself.

### Expected Behaviour

We should be able to merge Volcano Point in Volcano Polygon

**Comment by timlinux** [comment]
+1 it will be great to get rid of this duplication

**Comment by ismailsunni** [comment]
Historical notes:
Long time ago, these IF (volcano point and volcano polygon) are one IF :) So, we are going back to the past again.
But, I give +1 to this ticket, since the polygonize will be happened in prepare.

**Comment by timlinux** [comment]
This will be addressed #2987 when we have the 7 standard IF's
