### ISSUE TITLE
Landcover Report Style

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#2796]
### Problem
The Landcover IF in the develop, besides there is no action and note (https://github.com/inasafe/inasafe/issues/2764), we must make it consistent style with the other report, like the terminology, style, etc.
There is some content in the report 
- The classification in the report, as the terminology in the other report, we not only written "high, medium, low", 
![image](https://cloud.githubusercontent.com/assets/8871958/15282798/d43b0c1c-1b6f-11e6-96a0-5117df8e28fd.png)
but also added the hazard zone word
![image](https://cloud.githubusercontent.com/assets/8871958/15282971/3a9dc61a-1b71-11e6-9443-70e7d3923ab1.png)

- The writing style of region name in aggregation zone, similar with the subtitle in the report.
![image](https://cloud.githubusercontent.com/assets/8871958/15282205/c3c97d54-1b6b-11e6-96e1-404d6518487c.png)
I think it's possibly to make a confusion for user.

### Expected Behaviour
Re-style the current landcover report,  make it consistent / standart like the other report

CC : @ismailsunni @timlinux @Charlotte-Morgan

**Comment by Gustry** [comment]
@samnawi I have updated the landcover report a little bit in my PR about Tsunami on Landcover.
The plots are not visible anymore for instance. I will have a look about your comments.

**Comment by ismailsunni** [comment]
@Gustry I assigned it to you since you are already working on it. Feel free to pass it if you think there is another more suitable person to do it.

**Comment by fredychandra** [comment]
Hi @Gustry , @ismailsunni 

Is it possible to add 2 column on the right side. one is total affected area, second one is percentage from total affected area versus total area? This information is useful for user for first scanning how severity damage of affected land cover.

**Comment by Gustry** [comment]
@fredychandra I'm working on the two columns, affected and percentage.

* For the Tsunami on Landcover we have 5 classes : dry, low, medium, high and very high.
Except the first one, they are all "affected", the report looks like  : 
![3858](https://cloud.githubusercontent.com/assets/1609292/15384436/d27890f0-1dc4-11e6-911c-40b2b470f43d.png)

* For the generic IF, we have 3 classes : low, medium and high. Should I add these two columns too ?

**Comment by fredychandra** [comment]
HI @Gustry , thank you for work on it. I think two column in the right is enough. I worry if we add two column in every single classes the table will look complicated. 
Perhaps we can add note (mark) for *affected (%) and give explanation in the bottom of table
_* = It is percentage affected area from total area of land cover type_  How do you think?

**Comment by Gustry** [comment]
> I worry if we add two column in every single classes the table will look complicated.

@fredychandra , sorry I was speaking about two different IF.

* This one is from Tsunami on Landcover. We have 5 classes, the first column is the dry one, so it's easy to add affecter/unaffected : 
![3858](https://cloud.githubusercontent.com/assets/1609292/15415851/d60ea91a-1e6f-11e6-8a76-a5b12fa6f7d5.png)

* This one is the generic IF, we have only low, medium and high. So we can't really add the affected column, it's the same as the total.
![3858](https://cloud.githubusercontent.com/assets/1609292/15415865/fce1e0b6-1e6f-11e6-9336-6479fadd985b.png)

> Perhaps we can add note (mark) for affected (%) and give explanation in the bottom of table

I will add the note.

**Comment by Gustry** [comment]
I have fixed the labels about `low`, `medium` and `high` and the note for affected.
