### ISSUE TITLE
Attribute error on analysis using training dataset

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#2798]
### Problem
Running analysis using the `Run intermediate Inasafe training` results in attribute error when aggregation is done by district  `Jakarta`.

Dataset used: [http://data.inasafe.org/TrainingDataPackages/Run%20Basic%20InaSAFE%20v3.2.zip]()

Run Intermediate InaSAFE/DKI Jakarta/01 Hazard Data/Jakarta_Flood_18113_WGS84.shp
```
This analysis will calculate the impact of A Flood in Jakarta like 2013 on People and bullet list the results aggregated by Jakarta District
Problem

The following problem(s) were encountered whilst running the analysis.

AttributeError

An exception occurred when running the impact analysis.
'NoneType' object has no attribute 'difference'
Diagnostics

In file "/home/admire/.qgis2/python/plugins/inasafe/safe/impact_functions/base.py", line 678, in run_analysis self._prepare()
In file "/home/admire/.qgis2/python/plugins/inasafe/safe/impact_functions/base.py", line 833, in _prepare self.aggregator.deintersect()
In file "/home/admire/.qgis2/python/plugins/inasafe/safe/impact_statistics/aggregator.py", line 476, in deintersect self.hazard_layer)
In file "/home/admire/.qgis2/python/plugins/inasafe/safe/impact_statistics/aggregator.py", line 1443, in _prepare_polygon_layer int_com.difference(int_sym))
```

### Expected Behaviour
Run without errors and produce analysis result

### Environment
Linux QGIS 2.14.2

### Proposed Solution

**Comment by Gustry** [comment]
Hi @NyakudyaA ,
This issue has been fixed : https://github.com/inasafe/inasafe/issues/2724

BTW, for the next issue, in the environment, please tell us the inasafe version you are using. Which version are you using ? how did you get InaSAFE ?

**Comment by NyakudyaA** [comment]
@Gustry I will do so. I am using testing against the develop branch of inasafe: Inasafe 3.4.0.dev-b78f8c1

**Comment by Gustry** [comment]
I'm sorry, it might not be a duplicate

**Comment by ismailsunni** [comment]
Hi @NyakudyaA 
Can you give more detail about which layer you are using for this issue?
You said you run intermediate training, but you give link to basic training.

Other than that, I tried it on my computer, and all is fine. I am using hazard and exposure from basic training, and aggregation layer from intermediate training (the Jakarta_District_Boundary_WGS84.shp). I found all is good in develop:
<img width="1298" alt="screen shot 2016-05-25 at 17 02 27" src="https://cloud.githubusercontent.com/assets/1421861/15536329/19794424-229b-11e6-95bb-9732ac28e181.png">

**Comment by NyakudyaA** [comment]
@ismailsunni  I have just tested this again and still I get the attribute error. I am using `http://docs.inasafe.org/en/training/socialisation/run_intermediate_inasafe.html` in the section `C. Run InaSAFE for population with aggregation`. 

![attribute_error](https://cloud.githubusercontent.com/assets/2510900/15573521/ed3b02a0-2347-11e6-9038-28d65e864981.png)

**Comment by Charlotte-Morgan** [comment]
## Problem 
I am testing this with QGIS 2.14.3 and InaSAFE 3.4 tagged version on Windows
I am using Intermediate training data  same as @NyakudyaA and I get this Attribute Error too.

``` 
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 678, in run_analysis self._prepare()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 833, in _prepare self.aggregator.deintersect()
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_statistics\aggregator.py", line 470, in deintersect self.hazard_layer)
In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_statistics\aggregator.py", line 1359, in _prepare_polygon_layer int_com.difference(int_sym))
```
 ## proposed solution
If this is fixed - can the fix please be included in a bug fix release on Monday 6th as we need this to work in training on Tuesday 7th or backport to master

@ismailsunni @adissadis @harrymahr

**Comment by timlinux** [comment]
Will you take a look at this @Gustry ?

**Comment by Charlotte-Morgan** [comment]
hi @felix-yew - #3073 is closed because this issue is already reported

**Comment by NyakudyaA** [comment]
while trying to replicate #2806 . I ran the IF without aggregation and there was no error. But running  IF with aggregation results in attribute error. 

![io](https://cloud.githubusercontent.com/assets/2510900/17332442/10d8f048-58cf-11e6-8995-d07f1427c5bf.png)

With aggregation.

![io1](https://cloud.githubusercontent.com/assets/2510900/17332441/10d582f0-58cf-11e6-848d-970b677f72ee.png)
