### ISSUE TITLE
Value mapping style in the dock

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2800]
### Problem

Some very small papercuts for the value mapping in the dock.
- In the dock, the value mapping should be ordered according [road_class_order](https://github.com/inasafe/inasafe/blob/develop/safe/definitions.py#L858) and [structure_class_order](https://github.com/inasafe/inasafe/blob/develop/safe/definitions.py#L971)
- Secondly, the bullet should use the beautiful name. (with the capital letter)

FYI, it might be useful https://github.com/inasafe/inasafe/commit/e596dd07b713b30547c6e59d9d28c14aeb685fbf#diff-891a49b88796e551fd4cec1cab344caa

**Comment by ismailsunni** [comment]
Can we close this? I don't think the ordering is worth the effort
