### ISSUE TITLE
[Bug] The Aggregation Error when run Raster Flood Jakarta with Roads

### ISSUE THREAD

**Issue by dewisulistio** [inasafe/inasafe#2807]
### Problem
We trying to run Jakarta Flood HKV 2007 (Raster Data), Roads Jakarta, and Jakarta District Boundary, the result analysis is fails because the Aggregation Error. The Details diagnostics not showing. 

**Running with InaSAFE Dock with aggregate**

![flood raster data on roads with aggregate](https://cloud.githubusercontent.com/assets/2524177/15417840/2bd158b6-1e84-11e6-854b-d1a2b624ff86.png)

**Running with InaSAFE Dock without aggregate**
![flood raster data on roads without aggregate](https://cloud.githubusercontent.com/assets/2524177/15417853/47347322-1e84-11e6-9d75-7120cf181956.png)

**Running with IFCW**
![bug flood raster data on roads with ifcw](https://cloud.githubusercontent.com/assets/2524177/15417872/8c56c5c2-1e84-11e6-8224-f3329ce6bbbf.png)

### Environment
Windows 7 64bit 12GB ram
QGIS 2.8.9
InaSAFE 3.4 dev-master

### Data Used
1. Jakarta HKV Flood
2. Roads from OSM Downloader
3. Roads Jakarta
4. Jakarta District Boundary

cc : @timlinux @ismailsunni @samnawi

**Comment by ismailsunni** [comment]
hi @dewisulistio 
Can you copy paste to here the message in the dock? Especially, under the diagnostic one.
Thanks

It's very helpful when you create an issue with an error, you paste the full error message.

**Comment by dewisulistio** [comment]
Hi @ismailsunni 

The details diagnostics not showing in the dock when I tried run Raster Flood and Roads.

**Comment by ismailsunni** [comment]
Ah yes, sorry, I didn't see the scroll bar is in the bottom.

**Comment by ismailsunni** [comment]
Hi @dewisulistio I can't replicate it here, with QGIS 2.8.3. Can you try with another version of QGIS? 2.14.x may be?

<img width="1370" alt="screen shot 2016-07-14 at 09 57 00" src="https://cloud.githubusercontent.com/assets/1421861/16826674/5b2a9348-49a9-11e6-811b-fc67df7cc895.png">

**Comment by ismailsunni** [comment]
I have tried also with QGIS 2.14.2 It works. 
<img width="1374" alt="screen shot 2016-07-14 at 11 05 31" src="https://cloud.githubusercontent.com/assets/1421861/16827671/fd1e067c-49b2-11e6-90ed-0096295a06f8.png">

**Comment by felix-yew** [comment]
Hi @dewisulistio 

I have tried in QGIS 2.14.3 and it works, too.
Flood vs Roads (with aggregation)
![image](https://cloud.githubusercontent.com/assets/13621886/16827729/84c069ee-49b3-11e6-8ede-bf623a09c2b0.png)

Flood vs Roads (no aggregation)
![image](https://cloud.githubusercontent.com/assets/13621886/16827755/a61d6826-49b3-11e6-9658-44c1adb52812.png)

Flood vs Roads (IFCW)
![image](https://cloud.githubusercontent.com/assets/13621886/16827757/b521f1de-49b3-11e6-883b-bc53b140c5dd.png)

Environment
Windows 7 64-bit/ RAM 12GB
QGIS 2.14.3
InaSAFE 3.5.0. dev-master

**Comment by ismailsunni** [comment]
Close it, not found in 2.14
