### ISSUE TITLE
[Bug] All Hazard Impact Function Can Not Run for Building and Roads in QGIS Bahasa Indonesia

### ISSUE THREAD

**Issue by harrymahar** [inasafe/inasafe#2813]
### Problem
All hazard impact function to run affected Building and Roads scenario in QGIS Bahasa Indonesia does not work.

This week, I running all hazard (Flood, Earthquake, Volcano, Volcanic Ash and Tsunami) for all scenario (Population, Buildings, Roads, and LandUse) using InaSAFE 3.4.0 dev-master. I am using QGIS 2.8.9 (LTR) with Bahasa Indonesia and I have one major **bug (problem)** when I **run building and roads scenario** in all hazard impact function. I always got an error that said **key error** in analysis result. However, I **did not found** this bug for **population and land use scenario**. 

When I change my QGIS language into English and try to run building and road scenario again, it works and I can get the analysis result.

this is the diagnosis :

```

1. In file "C:/Users/Asus A450C/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1362, in completed report = self.show_results()
2. In file "C:/Users/Asus A450C/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1420, in show_results impact_report = impact_template.generate_message_report()
3. Infile"C:/Users/AsusA450C/.qgis2/python/plugins\inasafe\safe\impact_template\building_report_template.py", line 63, in generate_message_report message.add(self.format_postprocessing())
4. In file "C:/Users/Asus A450C/.qgis2/python/plugins\inasafe\safe\impact_template\template_base.py", line 142, in format_postprocessing table.caption = v['caption']
```
### Expected Behaviour
Eventough there are some bug related with the result (in other issues). At least, I can run and get the result for my scenario in QGIS with english language rather than can not run and always have  **key error** in QGIS Bahasa Indonesia.

### ScreenShoot
![eq_building_error](https://cloud.githubusercontent.com/assets/2534179/15420335/6489fd36-1e96-11e6-976f-a3b6f7caf608.JPG)

![ifcw_floodroad_error_indo](https://cloud.githubusercontent.com/assets/2534179/15420343/8063cc4e-1e96-11e6-852b-b749e3580be7.JPG)

![ifcw_floodroad_error_indo2](https://cloud.githubusercontent.com/assets/2534179/15420356/92776c60-1e96-11e6-992d-3d6af6f2b358.JPG)

### Environment
Windows 10 64 Bit
RAM 8 GB
QGIS 2.8.9 Wien (Long Term Release) in Bahasa Indonesia
InaSAFE 3.4.0 dev-master

### Proposed Solution
All scenario and all InaSAFE features should be works both in QGIS English and Bahasa Indonesia because many of InaSAFE users more familiar using QGIS in Bahasa Indonesia because they think that would be easier for them to understand all QGIS and InaSAFE features and tools.

cc : @timlinux @Charlotte-Morgan  @ismailsunni @samnawi @felix-yew

**Comment by Gustry** [comment]
This should be fixed in PR https://github.com/inasafe/inasafe/pull/2820

**Comment by harrymahar** [comment]
Thankyou @Gustry . Looking forward to see it.
