### ISSUE TITLE
'Type Error' when running Raster Tsunami Maumere with Roads

### ISSUE THREAD

**Issue by dewisulistio** [inasafe/inasafe#2816]
### Problem
While we tried to run Tsunami Maumere IF, Roads Maumere, and Maumere Village, the results analysis is fails because Type Error. I am using OSM downloader to change the roads data, and the results still Type Error.
```
**The Diagnostics**
1. In file "C:/Users/Dewi/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 677, in run_analysis self._impact = self._calculate_impact()
2. In file "C:/Users/Dewi/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 1395, in _calculate_impact result_layer = self.run()
3. In file "C:/Users/Dewi/.qgis2/python/plugins\inasafe\safe\impact_functions\inundation\tsunami_raster_road\impact_function.py", line 458, in run hazard_zone = self.hazard_classes[affected]
```
**Running with InaSAFE Dock with aggregate**  
![tsunami maumere - roads with aggregate](https://cloud.githubusercontent.com/assets/2524177/15421599/74b88fa8-1e9e-11e6-840e-6b76909dd089.png)
 
**Running with InaSAFE Dock without aggregate**
![tsunami maumere - roads without aggregate](https://cloud.githubusercontent.com/assets/2524177/15421680/d5d2eea0-1e9e-11e6-859c-ae9459baa4cc.png)

**Running with IFCW**
![tsunami maumere - ifcw](https://cloud.githubusercontent.com/assets/2524177/15421704/ed3ce168-1e9e-11e6-874a-7d5bb8392bdd.png)

### Environment
Windows 7 64bit 12GB ram
QGIS 2.8.9
InaSAFE 3.4 dev-master

### Data Used
1. Maumere_Tsunami_Mw8.1_WGS84
2. Maumere_Road_WGS84
3. Roads (OSM Downloader)
4. Maumere_Village_WGS84

**Comment by ismailsunni** [comment]
hi @dewisulistio 
I am using the dataset in http://data.inasafe.org/InaSAFE%203.2%20Data/, and I couldn't replicate this issue. Are you using the same data?
<img width="1296" alt="screen shot 2016-05-20 at 19 03 29" src="https://cloud.githubusercontent.com/assets/1421861/15427199/9a0d3ca8-1ebd-11e6-9724-6749f3df91e1.png">

And can paste here the full diagnostic, is seems there still some left (not stopping in 3 item)

**Comment by adissadis** [comment]
@ismailsunni i'm still got the same error as dewi even i use the training data from the link that you sent before. Here's my error log:

```

Processing started

Please wait - processing may take a while depending on your hardware configuration and the analysis extents and data.

This analysis will calculate the impact of Tsunami in Maumere (Mw 8.1) on Roads .

The following postprocessors will be used:

Road type: Calculates road types related statistics.
Preparing aggregation layer

Clipping the aggregation layer to match the intersection of your preferred analysis area.

Calculating impact

This may take a little while - we are computing the areas that will be impacted by the hazard and writing the result to a new layer.

Problem

The following problem(s) were encountered whilst running the analysis.

TypeError
Suggestion

You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/AIFDR/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Details

These additional details were reported when the problem occurred.

An exception occurred when running the impact analysis.
list indices must be integers, not QPyNullVariant
Diagnostics

In file "C:/Users/Adityo/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 679, in run_analysis self._impact = self._calculate_impact()
In file "C:/Users/Adityo/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 1411, in _calculate_impact result_layer = self.run()
In file "C:/Users/Adityo/.qgis2/python/plugins\inasafe\safe\impact_functions\inundation\tsunami_raster_road\impact_function.py", line 404, in run hazard_zone = self.hazard_classes[affected]

```

**Comment by ivanbusthomi** [comment]
Hi @ismailsunni this is the data that i used. it's been more than two hours, but the processing for the whole island is still running. it works perfectly using smaller extent though.

[testing-for-tsunami.zip](https://github.com/inasafe/inasafe/files/281465/testing-for-tsunami.zip)

**Comment by dewisulistio** [comment]
Hi @ismailsunni it's just 3 items for detail diagnostics. I used the data same with adityo

**Comment by Charlotte-Morgan** [comment]
hi @dewisulistio - can you please check if this is still a problem with #2881

**Comment by dewisulistio** [comment]
Hi @ismailsunni  @Charlotte-Morgan It's working in QGIS 2.14.3

![tsunami maumere road](https://cloud.githubusercontent.com/assets/2524177/15670088/c6586272-274d-11e6-8740-0a57408ae0d4.png)

**Comment by dewisulistio** [comment]
![ambon roads](https://cloud.githubusercontent.com/assets/2524177/15670180/3f4e55c4-274e-11e6-8561-c29c05e606af.png)

**Comment by Gustry** [comment]
I couldn't replicate with the data provided and @dewisulistio said it's working. I'm closing this issue. Feel free to reopen if needed.
