### ISSUE TITLE
[BUG] Error when running Earthquake and Landuse with aggregation in large analysis area

### ISSUE THREAD

**Issue by wulankhairunisa** [inasafe/inasafe#2817]
### Problem

AttributeError happens when running Earthquake (vector) and Landuse (vector) with Nagekeo administration (as aggregation layer). I set the analysis area for whole area of Nagekeo District. 

![49](https://cloud.githubusercontent.com/assets/2551072/15421535/0cef1dec-1e9e-11e6-82c3-5df9eac5ff1f.png)
![49a](https://cloud.githubusercontent.com/assets/2551072/15421651/aa13fc6e-1e9e-11e6-9fe9-128c3133ddfa.png)

```
Problem
The following problem(s) were encountered whilst running the analysis.
* AttributeError

Suggestion
You can try the following to resolve the issue:
* Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
* Check the InaSAFE documentation to see if you are trying to do something unsupported.
* Report the problem using the issue tracker at https://github.com/AIFDR/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
* Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.

Details
These additional details were reported when the problem occurred.
* An exception occurred when running the impact analysis.
* 'NoneType' object has no attribute 'wkbType'

Diagnostics
1. In file "C:/Users/Wulan Khairunisa/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 677, in run_analysis self._impact = self._calculate_impact()
2. In file "C:/Users/Wulan Khairunisa/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 1395, in _calculate_impact result_layer = self.run()
3. In file "C:/Users/Wulan Khairunisa/.qgis2/python/plugins\inasafe\safe\impact_functions\generic\classified_polygon_landcover\impact_function.py", line 128, in run if not impact_geometry.wkbType() == QGis.WKBPolygon and \
```

But when I ran the analysis using smaller analysis area, InaSAFE can produce the result layer succesfully. 
![49b](https://cloud.githubusercontent.com/assets/2551072/15421534/0ceecffe-1e9e-11e6-9b26-a910c2d92300.png)

It seems like this impact function still can work only for smaller area, not for large area (**if we use aggregation layer**). Whet we don't use aggregation, InaSAFE can produce the result.

### Environment
InaSAFE 3.4.0.dev-master
QGIS 2.8.9

The analysis has been run and got this same problem in laptop that using:
Windows 7 32bit/64bit
Windows 10 64bit

### Data used
1. Hazard: Nagekeo_Earthquake_Hazard_WGS84.shp
2. Exposure: Nagekeo_Landuse_WGS84.shp
3. Aggregation: Nagekeo_Batas_Desa_BPS_WGS84.shp

CC: @timlinux @ismailsunni @samnawi

**Comment by ismailsunni** [comment]
Hi @wulankhairunisa 
I think I have fixed this. Can you test it again against develop? If you still got the problem, please let me know. Can you also point where I can get the Nagekeo_Landuse_WGS84.shp ? I couldn't find it from http://data.inasafe.org/InaSAFE%203.2%20Data/ or http://data.inasafe.org/InaSAFE%203.1%20Data/

@NyakudyaA can you help me to check testing this also?

**Comment by felix-yew** [comment]
Hi @wulankhairunisa 

I have tried also in QGIS 2.14.3 and it works.

![image](https://cloud.githubusercontent.com/assets/13621886/16827896/f5beff42-49b4-11e6-936d-f9f0a6a61bcd.png)

Environment
Win 7 64-bit/ RAM 12 GB
QGIS 2.14.3
InaSAFE 3.5.0 dev-master

Cc: @ismailsunni

**Comment by NyakudyaA** [comment]
@wulankhairunisa  Can you please supply a link to the data source  ` Nagekeo_Landuse_WGS84.shp ` and  `Nagekeo_Batas_Desa_BPS_WGS84.shp`

**Comment by ismailsunni** [comment]
Close it, not found in QGIS 2.14
