### ISSUE TITLE
Wizard value mapping text needs improving

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2823]
### Problem

Currently the new value map text looks like this:

<img width="1001" alt="screen shot 2016-05-21 at 23 22 54" src="https://cloud.githubusercontent.com/assets/178003/15450922/da624d04-1fab-11e6-8543-1b5ec7cb2cd4.png">

Am I wrong or is it not true that it is not only the post processor that uses the value mappings, but the impact function itself? Maybe nice to say "We need to map the TYPE attributes to known categories."

Also replace "Un-mapped' with "Unclassified"

### Environment
* InaSAFE : master
* QGIS : all
* OS : all
* Data used : 
  * Exposure : /Users/timlinux/dev/python/inasafe/safe/test/data/exposure/roads.shp  
  * Hazard : 
  * Aggregagtion :

### Proposed Solution

**Comment by Gustry** [comment]
@timlinux Please review https://github.com/inasafe/inasafe/pull/2824

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry  - looking at this for the first time.
Can you please tell us where you got the class names from for structures - did someone provide advice on these already?

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry - i would like to tweak the terminology and text strings in this

**Comment by Charlotte-Morgan** [comment]
please see comments in #2721

**Comment by Gustry** [comment]
The value mapping has been improved by @Charlotte-Morgan in https://github.com/inasafe/inasafe/pull/2845
