### ISSUE TITLE
Wizard: generic hazard data should only have generic classes ?

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2829]
## Problem

If I select generic hazard data for a fire boundary polygon in the kw wizard; I am then offered both generic classes (3 classes) and flood classes (2 classes) in subsequent steps to assign key words
However, if I select flood classes (because my data are binary) I am not able to run any impact functions in the dock. if nothing is offered.

The same happens if I choose flood hazard and generic classes.

To me it looks like generic hazard and flood classes should be an inadmissible combination.
Similarly, flood hazard and generic classes should not be possible.
## proposed solution (now)

remove the option for classes types in the wizard if there are no supporting IF 
## proposed solution (longer term)

support data with 2, 3 or 4 classes regardless of hazard type and impact function.
## cc

@timlinux, @ismailsunni @samnawi @easmetz @felix-yew @ivanbusthomi @fredychandra

**Comment by borysiasty** [comment]
@ismailsunni I guess this ticket is for you. The wizard just lists classifications given from `ImpactFunctionManager.raster_hazards_classifications_for_layer()` and `ImpactFunctionManager.vectors_hazards_classifications_for_layer()`. See https://github.com/inasafe/inasafe/blob/develop/safe/gui/tools/wizard/step_kw25_classification.py#L72 .

**Comment by ismailsunni** [comment]
Well, it's an old problem actually.
So, in our metadata system, we do not pair hazard type with hazard classes. We only put all possible values for  the IF.
So, the short solution would be either:
1. Remove flood_classes support on generic IF, so we can only use generic classes, or
2. Better information / training / explanation on what no to do.

I believe, in the long term we should pair (or pack) hazard_classes in the hazard type. Thus, we need to modify / update the IF metadata system a little bit.

Please add some comment if you have @timlinux

**Comment by ismailsunni** [comment]
Done in version 4
