### ISSUE TITLE
Do we need value mapping for landcover data?

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2830]
## Problem

Landcover impact function reports use raw field values that may include duplicates or typos and not be in English or translatable
## Proposed solution

Either a magic thing that turns dodgy data into happy data 

or

a value mapper where the user assigns values in their data to a predefined classification.

the latter is very likely to be needed for the Volcanic ash realtime product as the users have specified the classifications they wish to see in the report.
## cc

@ivanbusthomi @Gustry @timlinux @lucernae

**Comment by Charlotte-Morgan** [comment]
On second thoughts - why don't we just fix the data :)

**Comment by timlinux** [comment]
We discussed this in our meeting on 07 June 2016 - because we have cases with landcover classes having typos etc. we want to rather use standard terms. @Charlotte-Morgan will get a standard list of named classes that the user data can be mapped to.

**Comment by timlinux** [comment]
We will do:

- [ ] allow dragging multiple items into the value mapping tree
- [ ] require value mapping for landcover to map landcover types to standard terms
- [ ] validate old keywords to ensure they have the needed value mapping

**Comment by Gustry** [comment]
We added a value mapping for landcover in InaSAFE V4.
Can we close this issue ?

**Comment by timlinux** [comment]
Yes I think we can close it
