### ISSUE TITLE
Remove Python Zonal Stats

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#2832]
### Problem
Currently we have two zonal stats (python and QGIS). Since the zonal stats QGIS is more reliable, we should stop our support for python zonal stats. See issue: #2751 
### Expected Behaviour
- [x] InaSAFE should only support QGIS zonal stats
- [x] Remove related code to python zonal stat
- [x] Remove option to choose zonal stats in option dialog

### Environment
All

### Proposed Solution
See expected behaviour above.

**Comment by Gustry** [comment]
@ismailsunni We couldn't remove `calculate_zonal_stats` ?
https://github.com/inasafe/inasafe/search?utf8=%E2%9C%93&q=calculate_zonal_stats

**Comment by ismailsunni** [comment]
@gustry yes, of course. I forget to remove the main code :D, now in PR here #2838

**Comment by Gustry** [comment]
I though your PR was not finished. but then I saw you merged it without removing the main code !
