### ISSUE TITLE
We need a report template for realtime volcanic ash

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2839]
## problem

We need to compose a report template for realtime volcanic ash.

All the user requirements are in #2491
Wiki page for map composer templating is here
 https://github.com/inasafe/inasafe/wiki/Map-Composer-Templating.

@ivanbusthomi  - I would like to assign this to you. You will need to work closely with @lucernae to get his advice and lessons learned from other realtime templates. 
@lucernae - please jump in and give some hints before @ivanbusthomi starts if you think there are any traps for new players 

When - soon :)
## cc

@timlinux @adelebearcrozier @samnawi @heriwaseso

**Comment by lucernae** [comment]
@Charlotte-Morgan I already speak with Ivan via Skype about it :D.
@ivanbusthomi for reference, you can take a look at:
https://github.com/inasafe/inasafe/blob/develop/realtime/fixtures/realtime-template.qpt for Shake and
https://github.com/inasafe/inasafe/blob/develop/realtime/flood/fixtures/realtime-flood.qpt for flood

**Comment by ivanbusthomi** [comment]
Hi mas @lucernae

here is the template that i've created using qgis 2.14.1
[ash_realtime_template.zip](https://github.com/inasafe/inasafe/files/320009/ash_realtime_template.zip)

and here is the project folder just in case i did something wrong exporting it
[_realtime ash report project.zip](https://github.com/inasafe/inasafe/files/320000/_realtime.ash.report.template.zip)

here is a screenie of how it looks like
![screen cap](https://cloud.githubusercontent.com/assets/7351977/16144401/ed1180e0-349c-11e6-8d3f-eab5e70271a5.PNG)

___
**CC** @Charlotte-Morgan @samnawi

**Comment by timlinux** [comment]
@lucernae can you give a status update on this please?

**Comment by Charlotte-Morgan** [comment]
Hi @lucernae, @ivanbusthomi and @timlinux.
I have some printouts of different versions of the template prepared by @ivanbusthomi . 
The above version looks very like what the clients asked for in #2491. We also have some versions with 'InaSAFE styling' which look good and a version with a bigger map; however detail in table 1 is lost.

**Comment by timlinux** [comment]
@Charlotte-Morgan ok good, lets use @ivanbusthomi 's above layouts to start with @lucernae  - we can always come back and tweak it after...

**Comment by Charlotte-Morgan** [comment]
hi @ivanbusthomi - I have reviewed the template and made some suggestions for minor changes to ensure the details are as per the request in #2491 . Most the fixes are small I hope.
## cc
@adelebearcrozier

**Comment by ivanbusthomi** [comment]
Hi @Charlotte-Morgan 
I think we can close this since we now have a final template in https://github.com/inasafe/inasafe/issues/2491#issuecomment-238151595

**cc** @timlinux @lucernae
