### ISSUE TITLE
We need a wiki page for InaSAFE reporting standards

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2840]
## Problem
We have many IF reports that are inconsistent wrt terminology, styles, titles, etc
We reviewed this at the time of the 3.2 release
We did not record our decisions :(

## Proposed solution
We need to document the preferred style for IF reports so that:
- we can agree on a standard way we want to communicate
- we can provide guidance to developers writing new IF on standard report components

## Action
- review existing reports
- identify what is good, what is not so good
- develop guidelines for discussion / consultation
- update reporting style to match guidelines
- write a wiki page

## Useful links
DMI 3.4 test reports as PDF - current status of reports 
https://drive.google.com/open?id=0B-d6psrlP1qWNXppcjVPWDR1V0U

previous review of terminology (3.2)
https://docs.google.com/spreadsheets/d/1dnR60NPtkemkUqKxB_mhNrNCgd_zQ4-3LoCCEppxVeE/edit#gid=0

Current human interface doc
https://github.com/inasafe/inasafe/wiki/human-interface-guidelines

Blank test report
https://docs.google.com/spreadsheets/d/1TU4rZZjEFN5bcvu9tmyIOhMfR3zUZsH_biE2mdj7DdI/edit#gid=1838591513 

## cc
@fredychandra @samnawi @felix-yew @ivanbusthomi @timlinux @Gustry @ismailsunni

**Comment by easmetz** [comment]
I have created a google doc for the draft reporting standards wiki (https://docs.google.com/document/d/1rhipAU4mdykbKQ4Qx4I5XuUwSSd33IY7Iw99tvOQsMo/edit?usp=sharing). I will put it in the gitter chat when it is ready for discussion/feedback.

**Comment by easmetz** [comment]
Also @Charlotte-Morgan I can't access the previous review or the blank test report at the moment so I have requested access. When I click on the DMI 3.4 test reports as PDF link it takes me to my blank Drive dashboard. This is the same problem we had last week - could you please re-share the link? Thanks!

**Comment by Charlotte-Morgan** [comment]
hi @easmetz, thanks for the feedback, I have fixed the links above - I hope it works now.

**Comment by Charlotte-Morgan** [comment]
@easmetz 
Please make your document above open for comment now, then we can add any existing standards.

Here are some thoughts on what needs to go in the standards:
**Map**
Title
Legend order
Legend colours
Marginalia

**Report**
General report
Alignment 
Headings
Units

Aggregation reports
Action lists
Notes and assumptions

**Terminology**
Hazard zones, hazard classes, hazard areas
Impacted, affected, inundated, shaken, killed

examples of good reports:
:) - hold that thought

**Comment by easmetz** [comment]
I have opened the document to commenting and editing now (I have updated the link) and I've copied your suggestions in.

**Comment by Gustry** [comment]
* We should also add the `No Data` : https://github.com/inasafe/inasafe/issues/2318#issuecomment-137404834

* Also about affected/unaffected. Some IF report unaffected features (written as `Not affected`, `Dry`), some don't (generic landcover show only `Low`, `Medium` and `High`).

**Comment by Charlotte-Morgan** [comment]
@easmetz - can you please close this when the ideas are incorporated into the standards. Of course the standard doc replaces the idea of a wiki page :)

**Comment by Charlotte-Morgan** [comment]
I have copied comments that need action to #2920

**Comment by Charlotte-Morgan** [comment]
closing this one now - replaced by #2920
