### ISSUE TITLE
Provide small tests data for Ash Raster on Polygon Landcover

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#2842]
Currently, I used tsunami raster as ash.
This files will be included in the repo for tests data loaded in 'Load test data' button.
It doesn't have to be big, just small enough to represents Ash Raster with different hazard type (various value) and it intersects current landcover exposure data:
https://github.com/inasafe/inasafe/blob/develop/safe/test/data/exposure/landcover.shp

Or if necessary, we can add another landcover exposure specific for Ash.

CC: @Charlotte-Morgan @samnawi @ivanbusthomi @timlinux

**Comment by Gustry** [comment]
> Or if necessary, we can add another landcover exposure specific for Ash.

I think we should avoid to have multiple landcover exposure. We should have one layer which contains some specials use cases.

The ash test data should be very simple and dummy where we can deduce the result. It's also on my roadmap to make the expected results more uniform across each IF. It becomes difficult to maintain tests as the values and the expected results are different  in every IF.

**Comment by lucernae** [comment]
Yeah, I also prefer less files to worry about :D

**Comment by ismailsunni** [comment]
Yes, agree with @Gustry 
The ideal is we can calculate the result by hand to make it sure that the result from IF is correct.

Just create a dummy file, as long as it's less than 100kb.

**Comment by ivanbusthomi** [comment]
@Gustry  @ismailsunni I'm already working on some dummy raster data based on the one @timlinux  extracted earlier. I will upload it here once completed. I hope it will work perfectly with the test data @lucernae mentioned

**Comment by ivanbusthomi** [comment]
Hi @Gustry @lucernae @ismailsunni ,this is the dummy volcanic ash raster data that i've prepared, based on the one that Tim extracted. 
What i do was assigning correct projection to the extracted data, and moving and resizing it to the extent of landcover dummy data.

![preview](https://cloud.githubusercontent.com/assets/7351977/15538626/9ac82a84-22a7-11e6-9229-f5b5f6b5f0da.PNG)

I've tried it using the landcover test data as exposure, and set the keyword with continuous tsunami hazard. It looks good to me. Please test it, and let me know if anything is not doing good.

![result](https://cloud.githubusercontent.com/assets/7351977/15538643/b072f83c-22a7-11e6-99af-08d412df494d.PNG)

### Dummy Volcanic Ash Data
[dummy.zip](https://github.com/inasafe/inasafe/files/281826/dummy.zip)

**Comment by lucernae** [comment]
forgot to mention it. thanks @ivanbusthomi , I will include it and edit my test files.

**Comment by ivanbusthomi** [comment]
Your welcome @lucernae Is the data too big? i can make the resolution lower and update it if you want

**Comment by Gustry** [comment]
The ash file has been included in inasafe. I'm going to close this issue. Feel free to reopen.
