### ISSUE TITLE
The aggregation result not appear in printed PDF.

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#2847]
### Problem
After I, @samnawi and @ivanbusthomi have been analysis the InaSAFE 3.4.0. between some of Hazard data and Exposure data and add with Aggregation data, there is some problem with the result. In the Print Table in PDF, there is no aggregation result. We have some problems when we have printed the PDF result in different hazard that we use it. 
This is one of example from printed PDF InaSAFE analysis result:
![image](https://cloud.githubusercontent.com/assets/13621886/15536993/20d12d9c-229e-11e6-96f8-183675e1217c.png)

There is some problems that I have capture it :
![image](https://cloud.githubusercontent.com/assets/13621886/15537273/9b3b8de2-229f-11e6-8eab-a9d7a501e652.png)

### Environment
* InaSAFE : 3.4.0.
* QGIS : 2.14.1.
* OS : Windows 7 64-bit
* Data used :
  One of the problem result, i.e. Landslide Hazard (Generic)
  * Hazard : https://www.dropbox.com/s/97usybl1c5rkj7x/01%20Hazard.7z?dl=0
  * Exposure : https://www.dropbox.com/s/do20e70vzlis767/02%20Exposure.7z?dl=0
  * Aggregation : https://www.dropbox.com/s/tryg3qbo2bvi51u/03%20Aggregation.7z?dl=0

### Proposed Solution
Make it happy.

Cc: @Charlotte-Morgan @timlinux @ismailsunni @samnawi @ivanbusthomi

**Comment by Gustry** [comment]
@felix-yew I was going to try this issue but after downloading your data, I don't have any .shp in the hazard folder and also in exposure/landcover and also in exposure/structure. Exposure/road is empty. Is-it normal ? I don't think so, I can't test.
And don't hesitate to put everything in one URL, it's quicker download instead of one per one. Thanks.
And if you want, you can also include the qgis project.

**Comment by felix-yew** [comment]
Hi @Gustry I apologize about the empty roads in link that I share. Now, @ivanbusthomi preparing the data to convert in to the *.zip file, after finish preparing He will put in to one URL and share the data.

Thank you.

**Comment by timlinux** [comment]
@felix-yew Can you provide the shp yet? Thanks!

**Comment by Charlotte-Morgan** [comment]
I have taken a guess at the data required but have not tested it.
Here are the TTU landslide data and the BIG infrastructure data as used in the TTU Risk Assessment workshop.

[TTU_Infrastruktur_WGS84.zip](https://github.com/inasafe/inasafe/files/353897/TTU_Infrastruktur_WGS84.zip)
[TTU_Ancaman_Longsor_WGS84.zip](https://github.com/inasafe/inasafe/files/353898/TTU_Ancaman_Longsor_WGS84.zip)

**Comment by timlinux** [comment]
@ismailsunni can you test with the data above and confirm if we can replicate? It may be resolved by your PR #3039

**Comment by NyakudyaA** [comment]
I have tested and I can replicate.  I used dummy aggregation layer because it was not provided. Please @felix-yew  provide aggregation layer.
OS: Ubuntu 16.04
Inasafe: 3.5

![ins](https://cloud.githubusercontent.com/assets/2510900/17330506/4fa845d8-58c7-11e6-81c8-939733200f73.png)

**Comment by ismailsunni** [comment]
@timlinux still not working. I am sure this is different problem with #3039
