### ISSUE TITLE
Open composer in print impact results  in initial blank map.

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#2851]
### Problem

During printing results of impact  analysis when we choose open composer the initial map is blank. 

![floods](https://cloud.githubusercontent.com/assets/2510900/15540712/23cd2d6c-2289-11e6-9dea-fc4e8b5ba0b1.png)
### Expected Behaviour

Open map composer with a map already drawn. Make the properties of the map default to render instead of rectangle.
### Environment
- InaSAFE : 3.4
- QGIS : 2.14.3
- OS : Ubuntu 15.10
- Data used : 25/05/2016
  - Exposure : `DKI Jakarta/02 Exposure Data/Java_Population_WGS84.tif`
  - Hazard :  `DKI Jakarta/01 Hazard Data/Jakarta_Flood_18113_WGS84.shp`
  - Aggregation : Entire Area
### Proposed Solution

Update the map composer to always use render settings as the default setting for the map so that it draws map layers that are active in qgis as opposed to rectangle. In order to draw the map you manually have to change the main properties of the map.

**Comment by Gustry** [comment]
Is this issue related to #2925 @NyakudyaA ?

**Comment by NyakudyaA** [comment]
@Gustry It is not related. Tim says it's a change that need to be made upstream to QGIS so that the default settings of a map is set to `Render` or `cache` unless there is a way to do it in inasafe. 
![item](https://cloud.githubusercontent.com/assets/2510900/15923232/653b0d92-2e2c-11e6-88be-d52bc09225dc.png)

**Comment by timlinux** [comment]
Yes its an upstream change that is needed. I think the main thing to fix is that the QPT template should remember the state of the map preview mode. I'm going to tag this for 3.6 but even then we will probably not see the benefit of our upstream fix until 2017 when QGIS 3.2 LTR is available. Lets make the upstream fix so long and then close this ok?

**Comment by Gustry** [comment]
We don't provide `Open in composer` for now in 4.1

**Comment by Gustry** [comment]
This feature to open in composer is finally back in 4.3.
I made a patch on InaSAFE about this on the PR above. I don't understand why we said it's an upstream bug. maybe I missed something.
![screen shot 2017-11-29 at 18 19 43](https://user-images.githubusercontent.com/1609292/33370246-ec28e380-d531-11e7-860d-6c89775db5c8.png)

Anyway, in QGIS 3, it seems this option is not existing anymore:
![screen shot 2017-11-29 at 18 18 37](https://user-images.githubusercontent.com/1609292/33370189-c8d85122-d531-11e7-93ec-48dca7301d24.png)

**Comment by Gustry** [comment]
I merged, please try again @NyakudyaA and feel free to close if your issue is fixed

**Comment by NyakudyaA** [comment]
@Gustry  Nice will close when I have tested tomorrow.  Also saw that in QGIS 3.0 the composer has changed a bit and they removed those settings for `Cache and Rectangle`

**Comment by Gustry** [comment]
Yes, It's my screenshot from yesterday about QGIS 3 ;-)

**Comment by NyakudyaA** [comment]
@Gustry Just tested and it's working properly. I will close
