### ISSUE TITLE
Symbology problem in Classified Volcanic Ash Raster on Vector exposure

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#2858]
### Problem
When I tried running Classified volcanic ash raster on building polygon, the result layer are not visible in map canvas, even though the layer name and details is in table of content. I got no error or anything, the process run smoothly. The screenshot below shows what i got after the process finished.
![1](https://cloud.githubusercontent.com/assets/7351977/15596771/4b4c1044-23f4-11e6-88cd-946d97e7f0aa.PNG)

Then i tried toggling off the unaffected building. Apparently the affected building are visible (which most of them are in low level).
![2](https://cloud.githubusercontent.com/assets/7351977/15596792/8394e43a-23f4-11e6-9929-0ec6aa56da86.PNG)

The same thing happened when i use the centroid data exposure as shown in the screenshot below:
![5](https://cloud.githubusercontent.com/assets/7351977/15597104/2171849a-23f7-11e6-914d-9394a30aa9d9.png)

I tried it in QGIS version 2.8.8 but the problem didn't happened

### Expected Behaviour
The affected building in result layer should be shown regardless the symbology of certain level are toggled on or off

### Environment
* InaSAFE : 3.4 develop
* QGIS : 2.14.1 Essen (Windows) and 2.14.3 (Ubuntu 16.04)
* OS : Windows 7 64 bit and Ubuntu 16.04
* Data used :
  * Exposure : Building Polygon and Centroid
  * Hazard : Classified Raster of Semeru Ash
  * Aggregation : None

This  is the data :point_right: [data.zip](https://github.com/inasafe/inasafe/files/285898/data.zip) :point_left: 

### Proposed Solution
Make it happy :smile: 

cc: @felix-yew @samnawi @Charlotte-Morgan @ismailsunni @timlinux

**Comment by Gustry** [comment]
Can you try #3013 to see if the problem is fixed ?
Thanks
