### ISSUE TITLE
BUG: 3.4 key words are not auto updating

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2866]
The key word version is not updating for data with version 3.3 key words.

eg Tsunami raster

**Comment by ismailsunni** [comment]
Can you elaborate what does it mean with not updating @Charlotte-Morgan ?

**Comment by felix-yew** [comment]
Hi mas @ismailsunni, maybe I can add some information about this issue. When I have been tried with InaSAFE version 3.4.0, something strange in the dock.

![image](https://cloud.githubusercontent.com/assets/13621886/15642784/bc2cc9bc-2673-11e6-88cc-f9fe39c9f2b8.png)
Not only in Tsunami Raster, but in other data. Could there be an error in merging process?

Cc: @Charlotte-Morgan @timlinux

**Comment by Charlotte-Morgan** [comment]
thanks @felix-yew - this explains what i was trying to say.  Previously when we open data with keywords already assigned, the keywords update to the new version.

**Comment by ismailsunni** [comment]
@felix-yew and @Charlotte-Morgan 
Thanks, I understand now.

**Comment by felix-yew** [comment]
Hi mas @ismailsunni, I use your PR #2868 to fix this issue and LGTM

![image](https://cloud.githubusercontent.com/assets/13621886/15645401/5fd5670a-2682-11e6-8b46-a928781ea322.png)
The InaSAFE and keyword version is already suitable.

Nice :+1:

**Comment by felix-yew** [comment]
Hi mas @ismailsunni maybe I can add some information about your PR #2868 in this issue, I find in icon in landcover and tsunami matrix.

![image](https://cloud.githubusercontent.com/assets/13621886/15645850/f55bb14c-2684-11e6-8684-a9d3164ebf03.png)
In PR #2868 in land cover has the new icon/logo of land cover. And function of raster tsunami on (polygon) land cover is available.

Maybe it can help you mas.

**Comment by ismailsunni** [comment]
Fixed in #2868
