### ISSUE TITLE
BUG:3.4 Tsunami on Roads - TypeError

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#2879]
### Problem
I tried running the 3.4 version of InaSafe using ambon data of raster tsunami hazard against roads.
I got a TypeError. here are the detailed report
```
Problems:
TypeError

Details
An exception occurred when running the impact analysis.
list indices must be integers, not QPyNullVariant

Diagnostics
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 679, in run_analysis self._impact = self._calculate_impact()
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 1411, in _calculate_impact result_layer = self.run()
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_functions\inundation\tsunami_raster_road\impact_function.py", line 404, in run hazard_zone = self.hazard_classes[affected]
```
### Expected Behaviour
It should work without error

### Environment
* InaSAFE : 3.4
* QGIS : 2.8.8
* OS : Windows 7 64bit
* Data used : [testing-for-tsunami.zip](https://github.com/inasafe/inasafe/files/281465/testing-for-tsunami.zip)
  * Exposure : OSM Roads 
  * Hazard : Ambon Tsunami Raster
  * Aggregation : No

### Proposed Solution
Make it happy :smile:

**Comment by Charlotte-Morgan** [comment]
@ismailsunni  and @ivanbusthomi 
I have just tested a small area with a fresh OSM download and no error.
It was rather slow - but completed with no error.
The user also had very good progress bars to know that it was still running

**Comment by ivanbusthomi** [comment]
@Charlotte-Morgan and @ismailsunni 
here is a screenie of what i got using freshly downloaded road data from OSM downloader and tsunami raster
![tsunami-2.8.8](https://cloud.githubusercontent.com/assets/7351977/15664622/b9107c4e-272f-11e6-8132-4870fc4fff43.PNG)

Strangely, i tried on 2.14.1 using the exact same data, without redownloading from OSM downloader, and it works just fine
![tsunami-2.14](https://cloud.githubusercontent.com/assets/7351977/15664625/be793f0e-272f-11e6-9049-160306488445.PNG)

**Comment by Charlotte-Morgan** [comment]
Yes - i tested the same area and it work for me in 2.8.3

**Comment by ismailsunni** [comment]
@ivanbusthomi 
I have created another PR for it #2883, please check it with the same data that give you error.

**Comment by ivanbusthomi** [comment]
@ismailsunni 
I just check it in 2.8.8, it gave me another error:
```
Problems:
Aggregation Error

Details:
The target_field contains Null values. The impact function should define this.
Aggregation error occurred.

Diagnostics:
```

I didnot set any aggregation layer, and just do the entire analysis area. Here is my keyword setup for hazard (in case i did something wrong with my setup)
![key](https://cloud.githubusercontent.com/assets/7351977/15665592/37e977b8-2736-11e6-871a-80571b540d3f.PNG)

and keyword for roads (automatically set up by OSM downloader)
![key2](https://cloud.githubusercontent.com/assets/7351977/15665599/4bfa548e-2736-11e6-944b-75e6f778491d.PNG)

**Comment by Charlotte-Morgan** [comment]
I'm testing too

**Comment by Charlotte-Morgan** [comment]
@ismailsunni @ivanbusthomi  - mine works fine
![image](https://cloud.githubusercontent.com/assets/5743135/15665851/c56e3960-2737-11e6-9798-9d2a13251b51.png)

**Comment by ismailsunni** [comment]
Closing this in #2883
