### ISSUE TITLE
BUG:3.4 Tsunami on Infrastructure - IndexError

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#2880]
### Problem
I got an IndexError when running Tsunami hazard (Raster and vector) on Point Infrastructure using ambon data. here are the detailed result

This is my Keyword Setup
* Exposure Infrastructure
![keyword infrastructure](https://cloud.githubusercontent.com/assets/7351977/15649170/a380b164-2699-11e6-8b0d-26ca68e938b7.PNG)

* Tsunami Vector
![keyword hazard vector](https://cloud.githubusercontent.com/assets/7351977/15649039/b96e921c-2698-11e6-8400-03559e04d214.PNG)
* Tsunami Raster
![keyword hazard raster](https://cloud.githubusercontent.com/assets/7351977/15649041/bc405fde-2698-11e6-8194-a6abf16d2627.PNG)

```
Problems:
IndexError

Details:
Error loading impact layer.
list index out of range

Diagnostics:
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1357, in completed report = self.show_results()
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 1415, in show_results impact_report = impact_template.generate_message_report()
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_template\abstract_road_building_report_template.py", line 66, in generate_message_report message.add(self.format_postprocessing())
In file "C:/Users/busthi/.qgis2/python/plugins\inasafe\safe\impact_template\abstract_road_building_report_template.py", line 86, in format_postprocessing header.add(m.Cell(attributes[0], header=True, align='left'))
```
### Expected Behaviour
It works without error

### Environment
* InaSAFE : 3.4
* QGIS : 2.14.1
* OS : Windows 7 64bit
* Data used : [Testing data.zip](https://github.com/inasafe/inasafe/files/289488/Testing.data.zip)

  * Exposure : Both Tsunami Vector and Raster
  * Hazard : Infrastructure
  * Aggregation : No

### Proposed Solution
make it happy :smile:

**Comment by ismailsunni** [comment]
Closed in #2881
