### ISSUE TITLE
Papercut: 3.4 wrong symbol in legend

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2884]
The symbol text is incorrect in the tsunami impact legend.
It should read
The Low hazard zone: > 0 - 1.0m

not <0

![image](https://cloud.githubusercontent.com/assets/5743135/15664931/ecdc5e1a-2731-11e6-86b3-2d65f3ec7128.png)

**Comment by Gustry** [comment]
Two PR on master and develop.
