### ISSUE TITLE
Tsunami vector classes

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2885]
## Problem

Tsunami vector classes are not offered to the user in the key words.
Generic classes do not reflect the tsunami hazard classes (+ very high)
## proposed solution

In C:\Users\AIFDR_ADMIN.qgis2\python\plugins\inasafe\safe\definitions.py 
add the tsunami_vector_hazard_classes

these can be copied from 
tsunami_raster_hazard_classes

then reference these in the key words wizard
![image](https://cloud.githubusercontent.com/assets/5743135/15665329/918aa3fc-2734-11e6-9ae2-98d389fbbd33.png)
## cc

@felix-yew @ismailsunni

**Comment by timlinux** [comment]
See #2987 - We have a plan to make generic impactions used only in cases where the hazard is not know, and that any registered hazard will automatically be able to use the 7 princes (standard IF implementations). I would like to write up #2987 nicely with @ismailsunni and then park this ticket until that is implemented - which should fix this issue.

**Comment by Gustry** [comment]
We have now many tsunami classifications in InaSAFE V4. I'm closing this one.
