### ISSUE TITLE
We need to update socialisation training

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2895]
## problem
we need to update socialisation training materials for version 3.4
We will be using online training on Tuesday - Jakarta time

## proposed solution 
We have comments from @easmetz from Feb 2016
https://docs.google.com/document/d/1cMn-itlwGzI3jl-G1w4VPGR64K0tJw8LgzctCZ6NfQc/edit

We have comments from @felix-yew today based on InaSAFE 3.4

## Proposed solution
- [X] We should update text - I can do that :) 
- [ ] we should update screenies and icons - HOT @adissadis to manage that 
- [ ] we should fix any broken links

- [ ] we finish edits and look to publish on Monday

## cc
@MariaSolovyeva @timlinux @easmetz @rduivenvoorde - so you know what we are doing
@MariaSolovyeva  - we will need your new postcard and icons if they are not already in the icon repo
@timlinux - we will need help to publish

**Comment by Charlotte-Morgan** [comment]
see #310

**Comment by felix-yew** [comment]
Some little information to check and update :
- Jakarta_flood take a long time analysis process (population and buildings)
- Jakarta_intermediate can not work properly in whole Jakarta area, but in small area can work
- Jakarta_basic can work properly
- Padang can work properly (population and buildings analysis)
- Maumere can work properly (buildings analysis)
- Broken link explanation
- Some 'instructure' image need update
- Icon/symbol of volcanic ash need to add in hazard
- Icon/symbol of land cover need to add in exposure

**Comment by Charlotte-Morgan** [comment]
Thanks everyone. The update was completed and a new version of socialisation training docs are not on the public website. 

The materials were used for training on Tuesday 7th June 2016.

There are some lessons to learn from the workflow - for next time.
