### ISSUE TITLE
We need to create standard for file naming conventions

### ISSUE THREAD

**Issue by easmetz** [inasafe/inasafe#2897]
### Problem

Users can currently input layers with special characters in their assigned keywords (e.g. '&') without returning an error, producing abnormal results.

### Proposed Solution

Create standard and put it in:

- help content
- wiki
- wizard dialogue

all of the above?

or create error if a special character is used?

### CC
@Charlotte-Morgan @ismailsunni

**Comment by easmetz** [comment]
Comments from @ismailsunni 
https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML

The other special characters are: " ' < > (double quotation mark, apostrophe, less-than sign, greater-than sign). Please avoid to use those characters.

**Comment by Charlotte-Morgan** [comment]
Hi @easmetz  - i think this could be added to #2840 too

**Comment by Charlotte-Morgan** [comment]
It could go in this wizard screen
![image](https://cloud.githubusercontent.com/assets/5743135/15774344/10c6f8be-29a6-11e6-8b55-50cb81b7acf9.png)

**Comment by ismailsunni** [comment]
I made a new PR #2918, it will handle the special character properly.
<img width="348" alt="screen shot 2016-06-08 at 10 02 18" src="https://cloud.githubusercontent.com/assets/1421861/15881431/2028ca9a-2d60-11e6-99d4-dfe76436ab5e.png">
Notice the `&` character in the image above.

IMHO, it will solve all related problem, no need to warning the user or create new help dialog.

**Comment by easmetz** [comment]
@Charlotte-Morgan do you think I should still include this in the wizard screen?

**Comment by Charlotte-Morgan** [comment]
hi @easmetz - if @ismailsunni has fixed this, then no need to clutter the wizard

**Comment by ismailsunni** [comment]
Ok, I will close this since it's already covered in #2918
