### ISSUE TITLE
Layer order: impact layer should draw over hazard layer

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2899]
## Problem
the impact layer is drawing under the hazard layer and not visible to the user immediately
the user will print a map of the hazard data and not the impact layer if they do not turn off or reorder layers

eg - this happened for jakarta flood raster on pop raster and padang earthquake raster on pop raster

![image](https://cloud.githubusercontent.com/assets/5743135/15774719/060139b0-29a8-11e6-93ac-957c5e150d46.png)

# proposed solution
IIRC - the standard behaviour @easmetz is for impact layers to draw above hazard layers or for the hazard layer to be turned off.
This is most relevant for raster on raster analysis and where the exposure data are population rasters.

I think this is a regression.

**Comment by ismailsunni** [comment]
@Charlotte-Morgan In this comment https://github.com/inasafe/inasafe/issues/2322#issuecomment-137406373, the impact layer will be put above the exposure layer.

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni - confirm impact layer should be above exposure layer. is there other logic that says it should be above hazard or that hazard is turned off?

**Comment by Gustry** [comment]
I described the behaviour in the PR : https://github.com/inasafe/inasafe/pull/2905
Should we change something else ?

**Comment by ismailsunni** [comment]
@Charlotte-Morgan as far as I know, it's only put the impact above the exposure, and not consider the hazard.
@Gustry I think your PR is LGTM

**Comment by Gustry** [comment]
Yes before, inasafe didn't care about the hazard layer. It put only the impact layer above the exposure layer and the hazard layer has never been turned off.
