### ISSUE TITLE
BUG: impact layer symbology has no detail

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2900]
## problem

the impact layer styling is not reflecting the range of values in the impact layer

eg people affected in Padang eq
zoomed in to a smallish area to avoid the memory error and got a single colour impact map
however the legend has 5 classes.

The user would have to resymbolise this to make the results meaningful
eg Padang map and legend
![image](https://cloud.githubusercontent.com/assets/5743135/15774875/f10041ae-29a8-11e6-8f76-34945800eb06.png)
## proposed solution

the legend range needs to better reflect the data range

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni and @Gustry  - this would be a good one to fix for 3.4.1 if possible

**Comment by timlinux** [comment]
Ah ok so we just remove classes from the legend that don't exist in the data.

**Comment by Gustry** [comment]
I don't think so.
We need to rescale the legend according to the extent, isn't it ?

**Comment by Charlotte-Morgan** [comment]
Yes. We need to rescale do there is variation in the map of results.

**Comment by Gustry** [comment]
It works with a flood in Jakarta, I have two legends : 
![selection_082](https://cloud.githubusercontent.com/assets/1609292/15965608/36d811d6-2f1f-11e6-9c61-32f68efc44a2.png)

**Comment by Gustry** [comment]
I wanted to try with a EQ raster on population (like in the screenshot), but I got two other errors #2947 and #2945 while I was loading a EQ raster in QGIS. I would like to debug this issue but it seems I can't have a working dataset for now.

**Comment by Charlotte-Morgan** [comment]
@gustry  
Appreciate your attention to this.  It is important. 
Some thoughts that may be relevant. 
I think the legend is dynamic. Maybe the change was made back at 3.2 or the change I'm observing could have occurred back then not recently. 
You may like to consider that in the past the legend was dynamic with a set number of classes with proportional classes ie if there were 5 classes, each had 20% of the colour on the map. 
At 3.2 iirc we changed this to try and make the legend consistent regardless of analysis extent, maybe using equal intervals from the dataset?? The down side of this is that it's possible to get a map with only one colour. Not ideal. 

Re the Padang dataset. We do use this for training. It's big and gives memory errors, that's part of the training. It's also unique in that it is not supplied with key words, also for training purposes. Maybe also the issue with the wizard unless I was reviewing the wrong version. 
This could explain your extra bugs. 
Key words you need are eq hazard, raster, continuous, MMI. 
Zoom to a small area or the building extent to avoid memory problems. 
The full dataset is available in data.inasafe.org socialisation /other hazards.zip.  West Sumatra. 
Have fun.

**Comment by Gustry** [comment]
Thanks @Charlotte-Morgan for all these explanations.

Could you classify your new layer in QGIS ?
![selection_005](https://cloud.githubusercontent.com/assets/1609292/16013824/413b8dca-318f-11e6-9b46-626c09595fd1.png)

My minimum and my maximum are equal, so I can't reclassify my legend. So the legend is normal, except we can hide unused classes like Tim said with the funnel button.

**Comment by timlinux** [comment]
![screen shot 2016-07-04 at 12 32 28 pm](https://cloud.githubusercontent.com/assets/178003/16558032/76bd1f5e-41e3-11e6-9d10-2dde497c29f0.png)

If we rescale we might get a different legend (fudged example below):

![screen shot 2016-07-04 at 12 35 47 pm](https://cloud.githubusercontent.com/assets/178003/16558158/05ef50f2-41e4-11e6-98e0-d254c1ff3e7c.png)


![screen shot 2016-07-04 at 12 35 55 pm](https://cloud.githubusercontent.com/assets/178003/16558163/0a40cb9a-41e4-11e6-9ee4-65ff9699c5d1.png)

But the thing I am wondering is: Ís the red area in your original screenshot a single population pixel or multiple pixels all classified into the same colour? In @Gustry I think it is all one pixel.

If it is the latter then I think we can just create an equal interval scaling for the pixel values.

**Comment by timlinux** [comment]
So there are a few different options:

1) Scale the values to the min max of the original exposure layer. This gives an advantage that maps generated from the same exposure layer will be comparable. Disadvantage is that the problem above will probably not be resolved.
2) Scale the values according the min max of the impact layer. This gives the advantage that the map should always be visually differentiated (assuming more than one pixel is covered), but disadvantage that maps are not comparable.

I think we should go with 2 which will work in all cases where more than one pixel value is encountered, but means that 'green' on one map will mean something completely different on the next.

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry @timlinux - thanks for the suggestions.
I do not like 1 above because we frequently have a problem - ie Java population where the population is not evenly distributed and the scaling will be meaningless, but comparable for other analyses using the same data set.

In much of our data, the cell values have been rasterised from large polygons and the apparent local detail small cells in the data is misleading when in reality many cells have exactly the same values.

Scaling according to min max in impact layer is likely to give a better cartographic result but has the disadvantage that different people in the same training group or working on contingency plans for adjacent villages might get the same colour on their map, which means different things.

There are other options like standard deviations and quantiles where a colour means the top 25% of affected etc - which is preferable to scaling according to the data min max values.

The final option is to stop displaying by count of people per cell. This is proposed in #2920 and up for discussion.

**Comment by timlinux** [comment]
OK lets wait on #2987 and #2920 to pan out. With the exception of Earthquake hazards in #2987 I think we would in any case follow  your last approach (stop displaying count of people per cell) since we would  use zonal stats for cases where population raster exposure are provided - and then use the same workflow as when working with polygon population data thereafter.

**Comment by Charlotte-Morgan** [comment]
Lets fix this with standards for 3.6
We need to change the way the impact layer is displayed

**Comment by Gustry** [comment]
In version 4.0 we don't have any raster with a color ramp. Can we close this ticket ?

**Comment by Charlotte-Morgan** [comment]
Yes - we have a work around - don't display raster results :)
