### ISSUE TITLE
Bug: we have lost the report headings

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2902]
## Problem
impact reports no longer have headings
![image](https://cloud.githubusercontent.com/assets/5743135/15775561/b9ddb59a-29ac-11e6-98da-ff13f597e7b6.png)

## proposed solution
All reports should have column headings
 in this case it would have been Hazard Category and Number of Buildings Affected

**Comment by Gustry** [comment]
`Affected buildings` is already in the table as a row. I'm not sure that we should add it again in the column heading.
And buildings in dry zone are not really affected. So we should just put `buildings`, no ?

BTW, these figures are repeated with the next table, except the affected figures. I think the report would be more readable if we remove some duplicated figures. See https://github.com/inasafe/inasafe/issues/2746
![b9ddb59a-29ac-11e6-98da-ff13f597e7b6](https://cloud.githubusercontent.com/assets/1609292/15775945/26cd03a4-2985-11e6-9a6f-8b3e44285918.png)

**Comment by timlinux** [comment]
We should also style the affected rows so that they appear visually grouped - it will make the **Affected buildings** total more readable.

Adding the headings ``Hazard zone`` and ``Building Count`` in the first table would probably work well.

**Comment by timlinux** [comment]
See also #2951 - we should standardise the layout of impact summary table

**Comment by timlinux** [comment]
@Charlotte-Morgan I think you are actually referencing the impact summary table when you mention that we have no headings. I just wonder what useful labels we can add since the column contains different types of elements:

* hazard zone labels
* building state labels
* total

Which means we would need to use something really generic for the label - which I think would not add much value to the reader. For the numeric column we could add a header '# Buildings' or something?

**Comment by Charlotte-Morgan** [comment]
I think we can address this by adding table titles that can include units when required.
see #2920 for some suggestions on how this might work as part of an overall revamp of how we present all results

**Comment by Gustry** [comment]
For roads, we can add headings from @Charlotte-Morgan's example 
![image](https://cloud.githubusercontent.com/assets/5743135/16682948/5bcacf6a-4527-11e6-9341-3912856109ed.png)

For buildings, do we need some headings ?

**Comment by Gustry** [comment]
We have no headings for roads and buildings : 
<img width="494" alt="screen shot 2016-07-21 at 09 22 42" src="https://cloud.githubusercontent.com/assets/1609292/17009433/c64a95ee-4f24-11e6-8135-33e6bcbcee81.png">

I think I can close this one for now.
