### ISSUE TITLE
Review: Tsunami IF

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2907]
## problem

Tsunami experts have asked that the default thresholds and classes for tsunami IF be revised.
## current situation

tsunami impact on people - default threshold is 0.7m
tsunami impact on buildings, roads and landcover
- default thresholds are 1.0, 3.0, 8.0. 
  This gives 5 classes:
  ![image](https://cloud.githubusercontent.com/assets/5743135/15811913/b98cb25c-2bd8-11e6-9c58-9ecdfc482582.png)
## proposed solution

NO CHANGE - tsunami impact on people - default threshold is 0.7m 
REVISE tsunami impact on buildings, roads and landcover
- default thresholds required are  1.0, 3.0
  This will give 3 classes
  - low < 1m
  - medium 1 - 3 m
  - high > 3m
## justification

the original classes were proposed by Pak Hamza, tsunami hazard modelling expert.
sources suggest that BNPB prefer that InaSAFE default analysis is aligned with the tsunami hazard classes as published on BG maps and specified in Perka 2 / 2012
## implications
- [ ] revise impact functions and reports
- [ ] revise documentation and definitions
## action
- [ ] CM to confirm with experts
## cc

@timlinux @Gustry @fredychandra @felix-yew @samnawi @easmetz

**Comment by Gustry** [comment]
So if I understand, we don't need ` Dry zone` (ie not affected) ?

**Comment by Charlotte-Morgan** [comment]
I've written to Pak Hamza for feedback on this.

**Comment by timlinux** [comment]
@Charlotte-Morgan Shall we move this to 3.6 pending further feedback?

**Comment by Gustry** [comment]
@ismailsunni Can you confirm this will be covered soon ? As we will have many thresholds for the same  hazard.

**Comment by ismailsunni** [comment]
Yes, it will covered when we have many thresholds for the same hazard

**Comment by Charlotte-Morgan** [comment]
let me follow up with @RikkiWeber on this one. I had forgotten we had this ticket :(

**Comment by Charlotte-Morgan** [comment]
I have my doubts about this change. I think we actually should offer thresholds for single event scenarios (as per advice from Pak Hamza) and thresholds for risk assessment as per Perka 2 / 2012 which are relevant to multiple event / hazard maps. Different data --> different purpose --> different thresholds --> different reports.
let me talk to @RikkiWeber and others @fredychandra @samnawi @ivanbusthomi @felix-yew about this

**Comment by RikkiWeber** [comment]
Pak Hamzah and BG both use the same thresholds which are for single scenarios.
low hazard = <1m
medium hazard 1-3m
high hazard >3m

You can introduce a 4th category if you wish, which would be the "dry zone"
The above is for buildings/infrastructure. For impact on people:
low hazard = <0.7m
medium hazard = 0.7-3m
high hazard = >3m

I am not familiar with what Perka 2/2012 states, however if it is multiple event hazard maps then it makes sense that it has a different set of thresholds with different reasons behind them. If you want me to look into it please send me through the relevant section from Perka 2/2012.

**Comment by Charlotte-Morgan** [comment]
thank @RikkiWeber  - lets discuss more next week

**Comment by Charlotte-Morgan** [comment]
Valuable discussion with @RikkiWeber today.
Tsunami hazard data produced by Badan Geologi in Indonesia is all single scenario; this includes the published  hazard maps and raster scenarios.

### recommendation ###
Default hazard classes in InaSAFE should reflect those used on the published maps and in Perka 2 / 2012 
high hazard >3.0m
medium hazard 1.0 -3.0m
low hazard  <1.0m

Please include a dry zone =<0m
This classification is relevant to buildings, roads and landcover exposure; and should be used as the default for tsunami inundation impact assessments. The reference is BNPB Perka 2 / 2012.

For impact on population - there is a modification as recommended by Pak Hamza
high hazard >3.0m
medium hazard 0.7-3.0m
low hazard  <0.7m

dry zone should not be used for population inundation 
----------------------------------------------------------------------------------
The current 5 class classification for buildings, roads and landcover:
very high hazard >8.0m
high hazard 3.1 - 8.0m
medium hazard 1-3m
low hazard  <1m
dry zone  =<0m

and modified for population:
very high hazard >8.0m
high hazard 3.1 - 8.0m
medium hazard >0.7-3.0m
low hazard  <0.7m

should be retained; however, these should not be the default. 
The reference for this is "based on (Papadoupulos and Imamura, 2001) 

There is probably no need to offer 'generic classes for tsunami hazard'

**Comment by ismailsunni** [comment]
We have implemented all tsunami hazard classes in version 4.0, I think we can close this.
