### ISSUE TITLE
Key error when using raster layer generated from shakemap converter

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#2908]
### Problem
I have converted grid [http://earthquake.usgs.gov/earthquakes/shakemap/global/shake/b000l219/download/grid.xml](url) to a tif using the shakemap converter but the raster that is generated is unusable in doing an impact assessment. 

![shakemap](https://cloud.githubusercontent.com/assets/2510900/15822913/afec9a8a-2bf8-11e6-83ef-1db6ab865280.png)

The raster layer results in an key error before running analysis. 

[shakemap_error.txt](https://github.com/inasafe/inasafe/files/300396/shakemap_error.txt)

### Expected Behaviour
Allow impact analysis to be done using the raster layer. 

### Environment
* InaSAFE :  3.14
* QGIS :  2.14.1
* OS :  Ubuntu
* Data used : 
  * Exposure :  Buildings /roads from Openstreetmap downloader
  * Hazard : Raster layer generated by shakemap converter
  * Aggregation :

### Proposed Solution
Generate raster layers that has the correct extent and usable in doing  analysis.

**Comment by ismailsunni** [comment]
Hi @NyakudyaA 
I think it's better to copy and paste the error message in the ticket rather than upload text file contains it. Make it faster to read the problem
Thanks

**Comment by ismailsunni** [comment]
I tried in my computer, I got different error.
```
Problem

The following problem(s) were encountered whilst running the analysis.

AggregationError
Suggestion

You can try the following to resolve the issue:

Aggregation error occurred.
Details

These additional details were reported when the problem occurred.

No attribute "safe_ag" was found in the attribute table for layer "Estimated buildings affected". The impact function must define this attribute for postprocessing to work.

Aggregation error occurred.
Diagnostics
```

But, it seems you can try my PR #2919 to fix your error. Let me know if you have tried it @NyakudyaA

**Comment by NyakudyaA** [comment]
@ismailsunni I have tried it and I get the same aggregation error as the one have above.

**Comment by ismailsunni** [comment]
I am closing this, and create new issue for the aggregation error in #2934
