### ISSUE TITLE
RFC: Thoughts on reporting standards

### ISSUE THREAD

**Issue by easmetz** [inasafe/inasafe#2910]
### Problem
After talking to @Charlotte-Morgan and with some feedback from @timlinux and @Gustry , I have reviewed the current reports for all hazard and exposure data and created a reporting standards document for discussion (see #2840). I have also used information from PERKA 2 and UNISDR, particularly when defining hazard classes.

### Proposed Solution

Everyone to read the google document https://docs.google.com/document/d/1rhipAU4mdykbKQ4Qx4I5XuUwSSd33IY7Iw99tvOQsMo/edit?usp=sharing and give feedback

Thanks!

**Comment by Charlotte-Morgan** [comment]
This ticket is superceded by #2920 the RFC for reporting standards

**Comment by Gustry** [comment]
I'm going to close this one, we have the RFC in 2920.
