### ISSUE TITLE
Symbology of Peta Jarkarta Flood layer is not clearly visible

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#2911]
### Problem
After downloading a flood layer from Peta Jakarta the symbology of the layer makes it not clearly visible especially when you have a raster layer in the layer list.  In the properties of the flood layer the column that is used to style the layer is missing. Also the downloaded layer is not displayed by default.

![jk](https://cloud.githubusercontent.com/assets/2510900/15851921/5f270ee4-2c9f-11e6-94ab-6f9d93f95eb5.png)

Flood layer generated is not toggled on.
![jk1](https://cloud.githubusercontent.com/assets/2510900/15851947/7b99cd0a-2c9f-11e6-8008-3aa5a859800b.png)

Flood layer is not clearly visible.
![jk3](https://cloud.githubusercontent.com/assets/2510900/15851951/831218c6-2c9f-11e6-872b-39be3d88aaa7.png)
Missing column used to style layer.
![jk4](https://cloud.githubusercontent.com/assets/2510900/15852011/dbd423e6-2c9f-11e6-9706-de5572d2bf45.png)

### Expected Behaviour
Make layer visible by changing the transparency levels of the symbols. 
Make sure the style is applied correctly and the column that is used to style the layer is visible.
Make the flood layer default as on in QGIS.

![jk6](https://cloud.githubusercontent.com/assets/2510900/15852017/e7837bb0-2c9f-11e6-8b56-e83ddca0ba8f.png)

### Environment
* InaSAFE : 3.14
* QGIS : 2.14.1
* OS :  Ubuntu 16.04
* Data used :
  * Exposure : 
  * Hazard : Flood layer downloaded from Peta Jakarta
  * Aggregation :

### Proposed Solution
Symbolize the layer  correctly and allow the layer to be visible with respect to other layers.

**Comment by timlinux** [comment]
> Make layer visible by changing the transparency levels of the symbols. 

0 - not flooded is intentionally fully transparent.
Other layers are semi transparent by design, so I don't think I want to change those.

> Make sure the style is applied correctly and the column that is used to style the layer is visible.

Ok I fixed this thanks

> Make the flood layer default as on in QGIS.

I think this is your settings - InaSAFE does not do anything special here so you should change it in QGIS settings.
