### ISSUE TITLE
Recompute statistics based on  extent choosen when generating reports.

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#2912]
### Problem

After generating reports I zoom into an area so that I can analyze my results. I decide to print the results and I encounter two options for printing. 
*  Print based on analysis extend 
*  Print based on current extent.
 
![analysis](https://cloud.githubusercontent.com/assets/2510900/15859980/8cffb654-2cc7-11e6-959c-f7008515dfd1.png)

Regardless of which option you choose the summary statistics are based on the analysis extent.
![smaller_extend](https://cloud.githubusercontent.com/assets/2510900/15860129/25a29020-2cc8-11e6-88de-8a61f2b7eb18.png)

The map that is drawn is based on the extend that I have specified but the report is based on the analysis extend.

### Expected Behaviour
Show report statistics of print area chosen.

### Environment
* InaSAFE :  3.14
* QGIS :  2.14.1
* OS : 
* Data used : 
  * Exposure : Any datasets from [http://data.inasafe.org/](url)
  * Hazard :  Any datasets from [http://data.inasafe.org/](url)
  * Aggregation : Any

### Proposed Solution
* Create dynamic statistics which can be incorporated into the report based on the chosen print  option. If chosen  extent does not match analysis extent then  recalculate the analysis results on the fly. 

* Incorporate an overview map if the chosen print option is not the analysis extent so that we can use the results of the analysis extent but just show that the relationship between the current extent and analysis extent.

**Comment by timlinux** [comment]
While I agree this would be nice functionality I think I am going to close this as 'won't' do - there are going to be lots of technical issues with this proposed interaction and I don't think there is a strong enough demand for it to justify the complexity it will add.
