### ISSUE TITLE
BUG: Minimum Needs EN is missing clean water

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2921]
## problem
the minimum needs report in english is missing the statement on clean water
![image](https://cloud.githubusercontent.com/assets/5743135/15884002/75024e08-2d77-11e6-9bdf-9d5ed9c6168f.png)

## proposed solution
reinstate the default minimum needs statement for clean water in  BNPB_en profile as per the details in the BNPB_ID profile
![image](https://cloud.githubusercontent.com/assets/5743135/15884062/cfa06d90-2d77-11e6-84c3-0720ad6217f6.png)

**Comment by ismailsunni** [comment]
Hmm, I still have that clean water in my InaSAFE (from develop). Which version of InaSAFE are you using?
<img width="767" alt="screen shot 2016-06-08 at 13 37 33" src="https://cloud.githubusercontent.com/assets/1421861/15885005/4644d2b4-2d7e-11e6-8e94-bfc7485d608f.png">

May be, it's getting deleted accidentally? Because it's stored in the local machine.

You can copy from `/inasafe-dev/resources/minimum_needs` if you have the InaSAFE's source

**Comment by Charlotte-Morgan** [comment]
### environment ###
QGIS 2.14.3
InaSAFE 3.4.0
Win 7 64bit

I also noticed this line is missing on the reports from testing done by DMI team

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
Can you try to remove `BNPB_en.json` under `.qgis2/minimum_needs/` directory in your home directory?
In windows it should be : `C:Users/[your username]/.qgis2/minimum_needs/`, then close all QGIS, then open it again. It should reset the minimum needs to the proper one.

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni - that fixed it on my machine. 
I'm not a computer expert, but I do not think that will fix it on other peoples machines?

**Comment by ismailsunni** [comment]
> I'm not a computer expert, but I do not think that will fix it on other peoples machines?
It will fix it also on the other people. InaSAFE will check if there is missing files, and add it with the default one.

Well, I am guessing that it's accidentally removed it (modify the minimum needs file). It will be stored in your local computer disk, just like when we update a layer / file / document. So, there are 3 solutions:

1. Delete manually the local file, and InaSAFE will restore it back (like we did)
2. Add a button to "restore from default"
3. Remove the minimum needs from the dialog, close the dialog, and open it. It will give you back the default one like before. You can test it.

It seems the 3rd options will solve the problem easily. Basically, it just does like in 1st option.

Just bear in mind, that this only works for default minimum needs from InaSAFE

PS : I just got the 3rd solution while writing this comment.

**Comment by timlinux** [comment]
I think @Charlotte-Morgan meant that fixing it on hers won't help other people - we need to figure out a way to let the user reset their minimum needs to 'factory default' easily.

**Comment by timlinux** [comment]
Note that I think this is not a bug or regression unless we can demonstrate that the clean water was removed without user intervention. If not it is more a case that the user has customised their minimum needs in a way that makes them inconsistent with the factory settings....

**Comment by timlinux** [comment]
@Gustry how about we add a 'reset to default' option on the minimum needs dialog?

**Comment by Charlotte-Morgan** [comment]
that sounds good

**Comment by Gustry** [comment]
I made a PR #3025
