### ISSUE TITLE
Empty report map when using IFCW on volcano on buildings

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#2925]
### Problem
After running IFCW for volcano on buildings using [http://docs.inasafe.org/en/training/socialisation/run_other_hazards.html](url). The report is generated fine but the map is blank because the resultant  layer are not toggled on by default. I have my QGIS settings as not to draw any layers added.

Custom qgis configuration.

![setup](https://cloud.githubusercontent.com/assets/2510900/15890799/a51b3aa6-2d71-11e6-9671-eb0fb78b355e.png)

Layers added are not on by default.
![result](https://cloud.githubusercontent.com/assets/2510900/15890820/be82ca4a-2d71-11e6-9f01-c21cc0d934fa.png)

Generated report contains blank map.

![empty](https://cloud.githubusercontent.com/assets/2510900/15890837/d2796acc-2d71-11e6-874d-a7c467ca2a7c.png)

### Expected Behaviour
Generate report with map visible.

### Environment
* InaSAFE :  3.14
* QGIS :  2.14.1
* OS :  Ubuntu 16.04
* Data used :
  * Exposure :  `Other Hazard/Sinabung/02 Exposure Data/Sinabung_buildings_WGS84.shp`
  * Hazard :  `Other Hazard/Sinabung/01 Hazard Data/Sinabung_Hazard_Map_2015_WGS84.shp`
  * Aggregation :

### Proposed Solution
Overwrite any custom qgis settings and add any layers as toggled on in QGIS when using any inasafe process.

**Comment by NyakudyaA** [comment]
@Gustry  has this been implemented yet because it still does not set the loaded layers as active when I retested it today using the develop branch.

**Comment by Gustry** [comment]
Feel free to reopen if you notice the problem, I will check later

**Comment by NyakudyaA** [comment]
i have tested this:
![classified](https://cloud.githubusercontent.com/assets/2510900/16195181/adcabc5e-36f8-11e6-954c-f2070bc32fa1.png)

Inasafe version : 3.15

**Comment by NyakudyaA** [comment]
i have tested this:
![classified](https://cloud.githubusercontent.com/assets/2510900/16195181/adcabc5e-36f8-11e6-954c-f2070bc32fa1.png)

Inasafe version : 3.15

**Comment by Gustry** [comment]
Hum, ok I misunderstood your problem I think.

3 weeks ago, I made a fix to make the **impact** layer visible, even if the QGIS checkbox (`By default, new layers added to the map should be displayed`) is not checked. So now, every new layer provided by InaSAFE should be visible.

But your last two comments, it's not a layer provided by inasafe. You loaded these layers from QGIS. So your issue should be "the wizard and the dock doesn't show layers which are not visible". And this is a feature, not a bug !
![inasafe 3 5 0 dev-dc76c8c options_003](https://cloud.githubusercontent.com/assets/1609292/16462309/eb4a797c-3e30-11e6-9ead-99d80706802b.png)

Ok, I admit, the settings is speaking about the dock only, not the wizard. I'm going to fix the label.

**Comment by NyakudyaA** [comment]
@Gustry I did not load the layer using QGIS. I loaded the layers using IFCW. According to your fix they should automatically draw if they are loaded by inasafe. That is the behavior I was reporting that it was not working as expected.

**Comment by Gustry** [comment]
I made a fix for the impact layer added at the end of the IFCW. Not for layers added while running the frist questions in the IFCW.
Do you think that InaSAFE should override the QGIS settings when we load a hazard/exposure layer using IFCW ?
There are two settings in conflict : QGIS about new layer not visible by default, and InaSAFE not showing hidden layers

**Comment by NyakudyaA** [comment]
I understand but the impact layer added at the end of IFCW does not seem to be behaving that way. The layer added is not on by default. I think inasafe should override the default QGIS settings and show the layers as visible as i think it also affect other options like choosing AOI for analysis.

![options](https://cloud.githubusercontent.com/assets/2510900/16484588/3ae77906-3eba-11e6-8f64-bbdc8e5c3266.png)

You cannot drag on map to choose an area because it wil not be visible by default.

**Comment by Gustry** [comment]
Ok, yes it's a problem to draw the bounding box if layers are not visible. Can you try the PR #3000 ?

**Comment by NyakudyaA** [comment]
LGMT

**Comment by Gustry** [comment]
Thanks for the review
