### ISSUE TITLE
Template options greyed when definining custom configurations in Inasafe Options

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#2927]
### Problem

When trying to define custom template options for inasafe the file picker is greyed out and we cannot choose custom template options.

If one once to define a custom north arrow it is not possible to define it using inasafe options. 

![template_options](https://cloud.githubusercontent.com/assets/2510900/15892803/3a018242-2d7c-11e6-834c-90c4da429c99.png)

### Expected Behaviour
Allow the buttons to be active when a given option is selected.

### Environment
* InaSAFE : 3.4
* QGIS :  3.14.1
* OS : Ubuntu
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :

### Proposed Solution
Activate the buttons and make all actions active.

**Comment by Gustry** [comment]
Thanks Admire. I made a PR for that.
