### ISSUE TITLE
Update travis to 2.14 and use the QGIS testing framework

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2930]
We said a few days ago we want to support only QGIS 2.14, as it will be the next LTR at the end of the month.

* Travis is still using QGIS 2.8, we should update it to QGIS 2.14.

After that, we should try to use the QGIS testing framework : 
* Deprecate our own testing framework `get_qgis_app` 
* Use https://github.com/qgis/QGIS/blob/master/python/testing/mocked.py
* Use and contribute to some custom assert methods : https://github.com/qgis/QGIS/blob/master/python/testing/__init__.py#L43

**Comment by ismailsunni** [comment]
Do you mean 2.14? Since 2.16 is regular release and hasn't been released.

**Comment by Gustry** [comment]
Sorry, I was travelling in the future

**Comment by timlinux** [comment]
Closing in favour of #2977
