### ISSUE TITLE
Discrepancies in the building report about the threshold

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#2932]
### Problem
Since the PR https://github.com/inasafe/inasafe/pull/2564 we can set the building threshold. In the impact table, inasafe will aggregate every impacted object if there are less than 25 objects into the "Other" group. So if there is less than 25 buildings affected, the value mapping will change on the fly during the analysis for that table.

But the postprocessor (`Buildings closed`) is not aware about this threshold, so the value mapping won't be changed. This bring some discrepancies in the report.

Building layer : 
![selection_080](https://cloud.githubusercontent.com/assets/1609292/15910879/4eaba460-2dcd-11e6-8b60-209ff9de5862.png)

Impact report :
![selection_081](https://cloud.githubusercontent.com/assets/1609292/15910988/f005851a-2dcd-11e6-8141-2da51ff36155.png)

### Expected Behaviour
Tables should have the same behaviour : 

### Environment
* InaSAFE : Develop
* Data used :
  * Exposure : A building layer with less than 25 features in one category.

### Proposed solution
* remove the building threshold ? The behaviour to aggregate every groups in "Other" does not fit well with the new value mapping according to me.
* or make the building postprocessor aware about the threshold ? (If the user want to report using the value mapping defined for the layer, he must put "1" in the threshold parameter to avoid the aggregation).

**Comment by Gustry** [comment]
Can I have some feedback about this ticket ? Thanks.

**Comment by timlinux** [comment]
For me I would prefer to remove the threshold - it seems artificial and non-transparent to me. @Charlotte-Morgan that ok for you?

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry 
thank you for raising this issue. I had no idea we had a threshold :)
I agree that the tables should have the same behaviour and if I am not mistaken we will move to one analysis with one set of data / results from which we can present tables and reports.

+1 to remove the threshold
or, if there was a good reason - we need to add it to the notes to say what the behaviour is and why ie building types with less than xx affected features are grouped. But I do not really like this.

**Comment by timlinux** [comment]
> or, if there was a good reason - we need to add it to the notes to say what the behaviour is and why ie building types with less than xx affected features are grouped. But I do not really like this.

Me too (don't like this) - I think we should just get rid of them - they are confusing and probably not useful at helping our users understand what is affected. e.g. 24 schools being affected in a district is a LOT - 24 hours probably not so significant, I think it is better the users make these kind of judgements rather than the IF...

**Comment by Gustry** [comment]
I made a PR to remove the building threshold. #3016
