### ISSUE TITLE
Aggregation Error

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#2934]
### Problem

While debugging issue #2908 , I got another error:

```
Problem

The following problem(s) were encountered whilst running the analysis.

AggregationError
Suggestion

You can try the following to resolve the issue:

Aggregation error occurred.
Details

These additional details were reported when the problem occurred.

No attribute "safe_ag" was found in the attribute table for layer "Estimated buildings affected". The impact function must define this attribute for postprocessing to work.

Aggregation error occurred.
Diagnostics
```
### Expected Behaviour

No Error
### Environment
- InaSAFE :  develop
- QGIS : 2.8.3
- OS : OSX
- Data used :
  - Exposure : From OSM Downloader
  - Hazard : Download from http://earthquake.usgs.gov/earthquakes/shakemap/global/shake/b000l219/download/grid.xml and convert it with InaSAFE shakemap converter
  - Aggregation :
### Proposed Solution

Make it happy. Perhaps remove `safe_ag` since it's misleading.

**Comment by timlinux** [comment]
``safe_ag`` should  be removed its just weird :-P The name is unintuitive and in the new design proposal we have we should not have this any more.

**Comment by Gustry** [comment]
We don't have this field `safe_ag` anymore in inasafe v4.
