### ISSUE TITLE
Key error when using Open street map layer as a background layer when doing analysis.

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#2938]
### Problem
Added `Maumere_Tsunami_WGS84.tif` and then proceeded to add `openstreet tile layer`. Zooming to extend of the hazard layer or extend of the open street tile layer results in key error.

![add](https://cloud.githubusercontent.com/assets/2510900/15927001/58a86f08-2e3f-11e6-84af-ede243aaa70d.png)

Select Open street map and zoom to its extend.  The following error appears:
``` Problem

The following problem(s) were encountered whilst running the analysis.

KeyError
Suggestion

You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/AIFDR/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Details

These additional details were reported when the problem occurred.

layer_purpose
Diagnostics

In file "/home/admire/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 1699, in layer_changed if keywords['layer_purpose'] == 'impact':
```

### Expected Behaviour
Render tile layer as a back drop to the hazard and proceed to do any analysis.

### Environment
* InaSAFE :  3.14
* QGIS : 2.14.1
* OS :  Ubuntu 16.04
* Data used : [http://data.inasafe.org/InaSAFE%203.2%20Data/Maumere.zip](url)
  * Exposure :  
  * Hazard :  ` Other Hazard/Maumere/01 Hazard Data/Maumere_Tsunami_WGS84.tif `
  * Aggregation :

### Proposed Solution
Add background layers and report  no errors.

**Comment by Gustry** [comment]
Thanks @NyakudyaA for repoting.
Is the diagnostic full ?

**Comment by NyakudyaA** [comment]
@Gustry yes that is the full diagnostics

**Comment by ismailsunni** [comment]
@NyakudyaA I think you need to update your InaSAFE from the repository. I have fixed this issue in #2908 and it has been backported to master also (https://github.com/inasafe/inasafe/pull/2936/commits/19f13c98b4666b3585b65525e710abd1b5ce6749).

**Comment by NyakudyaA** [comment]
@ismailsunni yes it is sorted.

**Comment by ismailsunni** [comment]
Closing this then.
