### ISSUE TITLE
Wrong classes in Keywords creation for volcano hazard

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#2940]
### Problem

When defining  keywords for volcano hazard using the Keywords creation wizard it shows wrong classification types for the hazard.

![classes_vol](https://cloud.githubusercontent.com/assets/2510900/15931645/eeef2f7e-2e58-11e6-8c20-cf890b4b0470.png)
### Expected Behaviour

Show types which are particular to that hazard.
### Environment
- InaSAFE :  3.14
- QGIS :  2.14.1
- OS :  Ubuntu 16.04
- Data used :
  - Exposure : 
  - Hazard :  `/home/user/.qgis2/python/plugins/inasafe/safe/test/data/hazard/volcano_krb.shp`
  - Aggregation :
### Proposed Solution

Only show types of classification which are valid for that hazard.

**Comment by timlinux** [comment]
So @ismailsunni and I have come up with a plan for world peace and better handling of generic impact functions so that they are only used when there is not a registered hazard for the analysis. I am going to park this for 4.0 until we have discussed with @Charlotte-Morgan

**Comment by ismailsunni** [comment]
Done in version 4.
