### ISSUE TITLE
Impact function centric wizard fails to select layer already loaded in QGIS

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#2941]
### Problem
I have a hazard layer already loaded in QGIS and when I launch the IFCW it only shows one option for selecting hazard layer even when in QGIS there is a hazrard layer loaded.

![poly_vol](https://cloud.githubusercontent.com/assets/2510900/15932840/8603418a-2e5d-11e6-8dd7-516b2b1ecb20.png)

### Expected Behaviour
Allow all options to be active when a hazard layer already exist in QGIS.

### Environment
* InaSAFE :  3.14
* QGIS : 2.14.1
* OS :  Ubuntu 16.04
* Data used : 
  * Exposure : 
  * Hazard : `/home/user/.qgis2/python/plugins/inasafe/safe/test/data/hazard/volcano_krb.shp`
  * Aggregation :

### Proposed Solution
Make all options active.

**Comment by borysiasty** [comment]
Probably those layers' keywords don't match the selected function requirements, and nothing is wrong with the wizard :)
