### ISSUE TITLE
Enable on the fly reprojection of openstreet map layer

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#2944]
### Problem
When adding open street map layer as a background it does not automatically zoom to the extent of your other layers loaded in QGIS.

![open](https://cloud.githubusercontent.com/assets/2510900/15960670/2bb63738-2f01-11e6-9028-3f8eaa00ff3c.png)

We should automatically enable on the fly re-projection when open street layer is added. Just like the `Open layers plugin` does.
![open_fly](https://cloud.githubusercontent.com/assets/2510900/15960708/5055bf6e-2f01-11e6-9d86-e97db818cca2.png)

### Expected Behaviour
Zoom to extend of layer already loaded in QGIS

### Environment
* InaSAFE :  3.14
* QGIS :  2.14.1
* OS :  Ubuntu 16.04
* Data used : http://data.inasafe.org/InaSAFE%203.2%20Data/Maumere.zip
  * Exposure : 
  * Hazard :  `Maumere/01 Hazard Data/Maumere_Tsunami_WGS84.tif` and `/home/admire/.qgis2/python/plugins/inasafe/safe/test/data/hazard/volcano_krb.shp`
  * Aggregation :

### Proposed Solution
Enable on the fly projection of open street map layer so that it can zoom to the extent of other layers.

![auto](https://cloud.githubusercontent.com/assets/2510900/15960812/d491ac8e-2f01-11e6-9ff5-474153899a6b.png)

**Comment by timlinux** [comment]
@NyakudyaA I tested this and it works perfectly for me

![qgis](https://cloud.githubusercontent.com/assets/178003/16906464/85484e36-4ce2-11e6-85b2-da694371c698.gif)

I think there is maybe something in your local settings causing this. Please re-open if you can find a way to replicate on a machine with clean settings or identify which settings cause it.
