### ISSUE TITLE
Attribute Error: Padang EQ on population

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2948]
### Problem
There is an attribute error when I run the Earthquake on population analysis regardless of which IF i choose.

### Error Message
![image](https://cloud.githubusercontent.com/assets/5743135/15988865/3ee21374-308a-11e6-8695-8a1c0a2f5bc9.png)

### Expected Behaviour
The analysis should run with no errors
### Environment
* InaSAFE : 3.5.0 dev 
* QGIS : 2.14.2
* OS : windows 7 64
* Data used :
  * Exposure : West_Sumatera_Population_WGS84.tif
  * Hazard : Padang_EQ_2009_WGS84.tif
  * Aggregation : none
* scenario:
[Padang on Pop scenario.txt](https://github.com/inasafe/inasafe/files/310634/Padang.on.Pop.scenario.txt)

### Proposed Solution
make it happy again

**Comment by Gustry** [comment]
@Charlotte-Morgan I made a PR to fix this bug.
It was related to the new legend order and occurred when we run the IF without an aggregation layer.
