### ISSUE TITLE
Specification for Raster Reclassification Tools

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#2961]
This issue will be directly related with Raster to Vector Reclassification Tools.
I will write the spec here to avoid confusion when developing the tools.
## What is this tool?

 The tools is used to convert raster hazard layer to vector layer. The value of each pixel in the raster is 'reclassified' using certain algorithm as one cluster of polygon for a certain class of threshold. The output would be a vector layer with each polygon as a clustered pixel value of raster that already been reclassified.
## What kind of raster hazard can be used?

In order to avoid confusion, only certain raster hazard layer can be used as the input of the tool.
- [ ] Hazard layer for Tsunami Raster Landcover IF
- [ ] Hazard layer for Ash Raster Landcover IF
## How does the pixel value will be reclassified?

Since the conversion actually takes place when the IF run, this tool is used to view what kind of vector hazard the IF will use. So, the reclassification rules is based on that particular IF's hazard thresholds. Thus, we get the general threshold ranges from the IF's options.

**Comment by timlinux** [comment]
Some quick comments:

* Can you also put some wireframes in your description too please?
* Can you describe what input layers are supported (raster etc, needs keywords etc.)
* Can you describe the outputs that will be created (example and metadata)
* Why not also support flood thresholds?

**Comment by timlinux** [comment]
Maybe we should disable for 3.5....we don't have an immediate need for it...

**Comment by lucernae** [comment]
We don't have any use for it now, right? @timlinux

**Comment by timlinux** [comment]
Yes I think we can shelve this for now thanks @lucernae
