### ISSUE TITLE
Failure to use extent option properly when using IFCW tsunami raster on landcover

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#2967]
### Problem

Running IFCW  tsunami on land cover results in `no overlapping extent` when using the option `Use intersection of hazard,exposure and this bounding box`.

![option](https://cloud.githubusercontent.com/assets/2510900/16197482/842ea414-3702-11e6-9621-d47dde5a9097.png)

The screen shot above explains what happens.

![no_overlap](https://cloud.githubusercontent.com/assets/2510900/16197456/6d69095e-3702-11e6-8ff4-d92c2be17b9f.png).

The error is mainly because the two layers do not overlay each other and because the layers added by IFCW are not toggled on by default as #2925 .

Land cover on zoom to full extent.

![landcover_ext](https://cloud.githubusercontent.com/assets/2510900/16197859/efa2f348-3703-11e6-89c4-c01120d30b88.png)

Raster layer on zoom to full extent

![tsunami_landcover](https://cloud.githubusercontent.com/assets/2510900/16197876/02166e7e-3704-11e6-8b26-7fb82cc0e7e1.png)
 

### Expected Behaviour.
Make sure the a user can create  a bounding box and enable him to use the option `Use intersection of hazard,exposure and this bounding box`

### Environment
* InaSAFE : 3.5
* QGIS : 2.14.3
* OS : Ubuntu 16.04
* Data used : Data from inasafe plugin repo
  * Exposure : `.qgis2/python/plugins/inasafe/safe/test/data/exposure/landcover.shp` 
  * Hazard :  `.qgis2/python/plugins/inasafe/safe/test/data/hazard/tsunami_wgs84.tif`
  * Aggregation : 

### Proposed Solution
Enable on the fly reprojection for any layers that are added by IFCW so that layers overlay each other.

![correct](https://cloud.githubusercontent.com/assets/2510900/16198148/20eb6326-3705-11e6-8736-dd3d554ff9c0.png)

**Comment by timlinux** [comment]
I tested this and it is working fine now with @Gustry's fix for #2925 

![screen shot 2016-07-18 at 12 09 13 pm](https://cloud.githubusercontent.com/assets/178003/16906358/8c797f38-4ce0-11e6-834c-46a03b80df30.png)
