### ISSUE TITLE
Exception error on using IFCW on raster flood vs raster population

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#2970]
### Problem

Running IFCW on raster flood vs raster population results in `exception error`

![exception_when_runing_raster_pop](https://cloud.githubusercontent.com/assets/2510900/16227021/94367f60-37ae-11e6-9b2e-b34f455220fc.png)

`
InaSAFE - ERROR - Error loading impact layer.
Traceback (most recent call last):
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/utilities/analysis_handler.py", line 368, in completed
    qgis_impact_layer = read_impact_layer(self.impact_function.impact)
  File "/home/admire/.qgis2/python/plugins/inasafe/safe/utilities/gis.py", line 426, in read_impact_layer
    raise Exception(message)
Exception: Input layer must be a InaSAFE spatial object. I got <type 'NoneType'>
src/core/qgsmessagelog.cpp: 45: (logMessage) [5ms] 2016-06-21T09:44:44 InaSAFE[0] Error loading impact layer.
`

### Expected Behaviour
Run without any errors.

### Environment
* InaSAFE :  3.5
* QGIS :  2.14.3
* OS :  Ubuntu 16.04
* Data used : From inasafe plugin repository. `.qgis2/python/plugins/inasafe/safe/test/data`
  * Exposure :  `exposure/people_allow_resampling_true.tif`
  * Hazard : `hazard/jakarta_flood_design_x10.tif`
  * Aggregation : `Entire Area`

### Proposed Solution
Run without errors

**Comment by ismailsunni** [comment]
Hmm, I can't replicate it in my laptop. Anyone able to replicate this? @timlinux @Gustry @lucernae 
<img width="1393" alt="screen shot 2016-07-04 at 06 41 36" src="https://cloud.githubusercontent.com/assets/1421861/16548237/83a1a2fc-41b2-11e6-8290-ac70e30cb6ec.png">

And what IF did you use? I use Raster flood on population

**Comment by felix-yew** [comment]
Hi @NyakudyaA 

I have tried in QGIS 2.14.3 and it works.
![image](https://cloud.githubusercontent.com/assets/13621886/16828182/b337177e-49b7-11e6-8d6c-479716807502.png)

Environment
Win 7 64-bit/ RAM 12 GB
QGIS 2.14.3
InaSAFE 3.5.0 dev-master

Cc: @ismailsunni

**Comment by NyakudyaA** [comment]
@ismailsunni  I have tested and it works.  I will close the issue.
