### ISSUE TITLE
Share InaSAFE realtime earthquake impact map with BMKG

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#2986]
BMKG has requested that InaSAFE realtime also return the impact map to them

Proposed solution
 make it happen

**Comment by timlinux** [comment]
@Charlotte-Morgan can you confirm if we can go ahead and do this? Last we chatted you wanted to wait for their agreement? Or does that only apply to BNPB. @lucernae please track this and get it done via a bit sync share ASAP.

**Comment by Charlotte-Morgan** [comment]
Hi - It is fine for BMKG to get the impact results back - they supply the shake map and want to get the results too. We should do this / should have done this a long time ago, there is no barrier.

It is only when BNPB want to change work flows or stop the existing relationship between BMKG and DMI for datasharing that we need to discuss.

@lucernae  - please make this happen :)

**Comment by timlinux** [comment]
Closing this in favour of the ticket in inasafe-realtime repo
