### ISSUE TITLE
RFC: 7 Princes - Standardise all impact functions into 7 base IF's

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#2987]
**STATUS**: In Draft
# Background

Whenever we introduce support for a new hazard (lets say Tsunami), there is invariably code duplication and a maintenance overhead incurred as we clone existing IF's and modify them for a the new hazard. In addition, the new IF (let's say Raster Tsunami on Roads) is inherently characterised by the geometry type / data format of the hazard. So if we are actually generally interested in Tsunami impacts, we really want to cater for e.g.:
1. Polygon Tsunami impact on roads
2. Polygon Tsunami impact on polygon buildings
3. Polygon Tsunami impact on point buildings
4. Polygon Tsunami impact on polygon population
5. Polygon Tsunami impact on raster population
6. Polygon Tsunami impact on polygon landcover
7. Polygon Tsunami impact on raster landcover
8. Raster Tsunami impact on roads
9. Raster Tsunami impact on polygon buildings
10. Raster Tsunami impact on point buildings
11. Raster Tsunami impact on polygon population
12. Raster Tsunami impact on raster population
13. Raster Tsunami impact on polygon landcover
14. Raster Tsunami impact on raster landcover

And this is a more simple case where the hazard can only have e.g. continuous hazard data. Add support for classified data and we double the number of permutations. Add a new exposure type and we add more permutations. You can see why adding a new hazard becomes a high overhead activity with lots of code to maintain and a lot of work to do to keep everything consistent across all IF's and their reporting.
# Proposed solution

Our proposed solution looks something like this:

![inasafe4 0architecture](https://cloud.githubusercontent.com/assets/178003/16364847/a48b29f6-3bf0-11e6-993f-022b957f73f1.png)

In our solution there are some key points to note:
- When support for new hazards is added in InaSAFE, we do not create new impact functions we create **new metadata**.
- We do not generate reports, we generate datasets. The datasets are then used to create one or more reports.
- For a given family (e.g. impact on line features), all the reporting will be consistent as the IF methodology will be precisely the same regardless of Hazard type.
- We never have more than a handful of Impact Functions (5 illustrated here plus a few niche once like Earthquake damage curve based ones that do not fit this model).
- We assiduously avoid introducing special case logic into the impact functions.
- All hazards are first converted to classified data (barring the EQ exceptions), then polygonized. 
- We have two hazard polygonization strategies we can consider: 
  - **Cell based** where we create a polygon for each cell extent from an original raster, and 
  - **region based** where we create a polygon for each contiguous region of cells with the same class value.
# Proposed outputs

It is our proposal that the outputs of IF's should be as homogenous as possible. Speaking to the generalised case in our proposed solution all the impact functions would produce a dataset which:
- is a vector based dataset
- is clipped to the aggregation area. All data outside the aggregation area would be excluded (see also #2473).
- has no feature that overlaps more than one aggregation area
- has no feature that overlaps more than one hazard zone

There would always be three primary outputs:
- A spatial dataset containing the impact layer (and its QML style definition)
- A spatial dataset containing the processed hazard dataset (and its QML style definition) where hazards are polygonised and classified.
- A (Geo)JSON document which describes the analysis process followed and it's provenance.

We envisage that all of these products would be written into a single GeoPackage dataset for ease of sharing.

The spatial dataset for the impact layer would be geometry specific depending on the exposure layer used. However the attributes would be largely standardised as per the following example:

| aggregation_id | aggregation_name | hazard_id | hazard_class | exposure_id | exposure_class |
| --- | --- | --- | --- | --- | --- |
| 1 | Menteng | 1 | medium | 1 | school |
| 1 | Menteng | 1 | medium | 2 | house |
| 2 | Foo | 1 | low | 3 | hospital |
| 2 | Foo | 1 | low | 4 | school |

The above is the general case (using  flood on buildings in this instance). There are a couple of variants to this tabular structure proposed depending on whether the exposure is linear (e.g. roads), polygonal (e.g. buildings, population areas, land cover) or raster (e.g. population counts). I illustrate these below (scroll across to the right to see the whole table):

| aggregation_id | aggregation_name | hazard_id | hazard_class | exposure_id | exposure_class | exposure_count |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | Menteng | 1 | medium | 1 | census area 1 | 800 |
| 1 | Menteng | 1 | low | 1 | census area 1 | 1000 |
| 2 | Foo | 1 | high | 3 | census area 2 | 2000 |
| 2 | Foo | 1 | low | 3 | census area 2 | 500 |

**Above:** Flood on polygon population areas - exposure count represents number of people

| aggregation_id | aggregation_name | hazard_id | hazard_class | exposure_count |
| --- | --- | --- | --- | --- |
| 1 | Menteng | 1 | medium | 800 |
| 1 | Menteng | 1 | low | 1000 |
| 2 | Foo | 1 | high | 2000 |
| 2 | Foo | 1 | low | 500 |

**Above:** Flood on raster population - exposure_count represents number of people

| aggregation_id | aggregation_name | hazard_id | hazard_class | exposure_id | exposure_class | exposure_count |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | Menteng | 1 | medium | 1 | agricultural | 800 |
| 1 | Menteng | 1 | low | 1 | urban | 1000 |
| 2 | Foo | 1 | high | 3 | mixed use | 2000 |
| 2 | Foo | 1 | low | 3 | agricultural | 500 |

**Above:** Flood on polygon landuse areas - exposure count represents ha of affected land

| aggregation_id | aggregation_name | hazard_id | hazard_class | exposure_id | exposure_class | exposure_count |
| --- | --- | --- | --- | --- | --- | --- |
| 1 | Menteng | 1 | medium | 1 | main | 100 |
| 1 | Menteng | 1 | medium | 2 | secondary | 200 |
| 2 | Foo | 1 | low | 3 | tertiary | 50 |
| 2 | Foo | 1 | low | 4 | main | 300 |

**Above:** Flood on roads - exposure_count represents road distance in m
# Using metadata to drive analysis behaviour

A key consideration in this proposal is that the metadata and not algorithms are used to drive the analysis and reporting behaviour. To support this we propose to move the metadata and properties that are currently implemented in the Impact Functions into [defnitions.py](https://github.com/inasafe/inasafe/blob/develop/safe/definitions.py) (or similar system). Taking again our example of Tsunami hazards above, we might implement something like this in the metadata in [definitions.py](https://github.com/inasafe/inasafe/blob/develop/safe/definitions.py#L269):

``` python
hazard_tsunami = {
    'key': 'tsunami',
    'name': tr('Tsunami'),
    'description': tr(
        'A <b>tsunami</b> describes a large ocean wave or series or '
        'waves usually caused by an underwater earthquake or volcano. '
        'A <b>tsunami</b> at sea may go unnoticed but a <b>tsunami</b> '
        'wave that strikes land may cause massive destruction and '
        'flooding.'),
    'actions': [ 
        tr(''),
        tr(''),
        tr(''),
        tr('')],
    'notes': [
        tr(''),
        tr(''),
        tr(''),
        tr(''),
    ],
    'parameters': [
    ],
}
```

You can see the actions and notes and parameters get moved out of the impact function (e.g. [impact_function.py](https://github.com/inasafe/inasafe/blob/develop/safe/impact_functions/inundation/tsunami_population_evacuation_raster/impact_function.py#L57)). Parameters would be in the form of thresholds - we could look at supporting other parameters in the future, but in the short term we feel that is not needed. The above is intended as an example and in the final implementation we expect that there would be additional metadata such as hazard units, threshold units etc.

There are some limitations to this approach - in particular we at the outset lose the ability to do 'smart' notes and actions based on context, but I would posit that the benefit of massive reduction in complexity and code maintenance outweighs this loss for the short term. For the longer term I believe we can add more nuanced behaviour to the metadata handler so that we can e.g. have expressions in the metadata to cover these cases. 
# See also
- https://github.com/inasafe/inasafe/issues/2473 - Irregular clipping RFC
- https://github.com/inasafe/inasafe/issues/2920 - Standardised reporting RFC
# CC

@Charlotte-Morgan 
@Gustry 
@ismailsunni 
@lucernae 
@samnawi 
@felix-yew 
@ivanbusthomi 
@easmetz 
@adissadis

**Comment by Charlotte-Morgan** [comment]
This makes a lot of sense. Losing the dynamic content of the notes and actions is noted; but something we can probably manage without.

**Comment by ismailsunni** [comment]
@timlinux How do we recognise the exposure_count in the impact layer?
For example, a polygon impact layer can have exposure_count as number of peole or ha of affected area.

Moreover, in the area and road case, I don't the we need the exposure_count field. We can get the value of the affected road or area from the hazard class, and do the simple length or area function.

The only thing that I can think of for the exposure_value is using it to store the value from a raster exposure layer (currently only population raster). But, it'll be better if we put the number of population in the specific population field in the impact layer.

**Comment by ismailsunni** [comment]
Another question:
For the hazard_id, exposure_id, and aggregation_id, will we get them from feature.id() or we can specify one field from the layer to be treated as the id?
