### ISSUE TITLE
Duplicate information in Notes and Assumptions on Earthquake IF

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#2998]
### Problem
When I tried running Earthquake scenario with PAGER model IF using Padang dataset, I noticed that the note and assumptions contains both ITB model and PAGER model like the one in the screenshot below
![err1](https://cloud.githubusercontent.com/assets/7351977/16474987/1332d046-3ea5-11e6-8ba7-5887ef0b843f.PNG)

This also happened when I use the ITB model
![err2](https://cloud.githubusercontent.com/assets/7351977/16474963/ee3568c6-3ea4-11e6-8a61-bbf605a232ef.PNG)

Notice that there are still minus values in the unaffected that might be related to issues #2969 

### Expected Behaviour
Notes and assumptions should show correct earthquake model that is used in the analysis

### Environment
* InaSAFE : 3.4.2
* QGIS : 2.14
* OS : Windows
* Data used : Padang dataset
  * Exposure : Population raster
  * Hazard : Earthquake Continuous Raster
  * Aggregation : No

### Proposed Solution
Make it Happy
___
**CC** @Charlotte-Morgan @felix-yew @samnawi @lucernae @timlinux @ismailsunni

**Comment by Charlotte-Morgan** [comment]
@easmetz if you are able, could you please discuss with Hadi and ask him to contribute.? 
@RikkiWeber

**Comment by Charlotte-Morgan** [comment]
I've asked @RikkiWeber to get @hadi and @dynaryu to check this one. They may not be able to do it until later this week.

**Comment by timlinux** [comment]
@Charlotte-Morgan I think we can close this - I think it was a simple bug. in https://github.com/inasafe/inasafe/pull/3116 I made a fix for it so I think we can close this.

**Comment by Charlotte-Morgan** [comment]
hey @ivanbusthomi - please check that this is resolved and close if it is

**Comment by ivanbusthomi** [comment]
it has been fixed, thanks
