### ISSUE TITLE
ImportError: No module named common.utilities

### ISSUE THREAD

**Issue by uniomni** [inasafe/inasafe#300]
Sometimes, InaSAFE fails to load in QGIS with the error below.
Setting PYTHONPATH=. does not help.

All tests pass and it is fine to load the module from the Python command line:

<pre>
nielso@shiva:~/sandpit/inasafe-dev$ python
Python 2.7.2+ (default, Oct  4 2011, 20:06:09) 
[GCC 4.6.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from safe.common.utilities import setup_logger
>>> 
</pre>

OGIS error message:

<pre>
Couldn't load plugin inasafe-dev due an error when calling its classFactory() method

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 164, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/nielso/.qgis//python/plugins/inasafe-dev/__init__.py", line 77, in classFactory
    from safe_qgis.plugin import Plugin
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 309, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/nielso/.qgis//python/plugins/inasafe-dev/safe_qgis/__init__.py", line 9, in 
    from safe.common.utilities import setup_logger
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 309, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named common.utilities

Python version:
2.7.2+ (default, Oct  4 2011, 20:41:12) 
[GCC 4.6.1]

QGIS version:
1.8.0-Lisboa Lisboa, exported

Python path: ['/usr/share/qgis/python', '/home/nielso/.qgis//python', '/home/nielso/.qgis//python/plugins', '/usr/share/qgis/python/plugins', '/usr/local/lib/python2.7/dist-packages/pip-1.1-py2.7.egg', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/Numeric', '/usr/lib/python2.7/dist-packages/PIL', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/pymodules/python2.7/ubuntuone-dev-tools', '/usr/lib/pymodules/python2.7/libubuntuone', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/ubuntuone-client', '/usr/lib/python2.7/dist-packages/ubuntuone-control-panel', '/usr/lib/python2.7/dist-packages/ubuntuone-couch', '/usr/lib/python2.7/dist-packages/ubuntuone-file-storage-api', '/usr/lib/python2.7/dist-packages/ubuntuone-installer', '/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode', '/home/nielso/.qgis/python/plugins/inasafe-dev']
</pre>

**Comment by solomonvimal** [comment]
Hi,

I am not able to install the inasafe plugin in Ubuntu 16.04. I get the error 
![inasafe_error](https://user-images.githubusercontent.com/2102394/36290955-21723c3e-127d-11e8-9717-8ed7b9b5e6fb.png)

Can you help me understand what this mean? 

Thanks for your time,
Solomon

**Comment by ismailsunni** [comment]
Hi @solomonvimal 
Is it the first time you install InaSAFE?

I can suggest you to uninstall it, then restart QGIS, then install InaSAFE again. Can yo also tell me which QGIS version that you are using?

**Comment by ismailsunni** [comment]
@solomonvimal 
Yeah, I have fixed the problem in https://github.com/inasafe/inasafe/pull/4910 but I haven't pushed it to PyPi.
