### ISSUE TITLE
We need names for the 7 princes

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3007]
# problem

We have the concept of 7 princes #2987 but alas these heros have no names.
Of course there is a precedent of the unnamed dancing princesses but I propose we should fix this problem.
# proposed solution

The princes should be named so that we can refer to them directly. In my opinion we could number them (very nerdy), we could give them names like PIF, IPIF, POIF etc but they may be offended.
Alternatively we could use existing names for groups of 7 well known gentlemen (Doc, Grumpy, Happy, Sleepy, Bashful, Sneezy, Dopey)

@Gustry @ismailsunni - I think you can fix this problem
@lucernae - here is your chance to express the wishes of the 12 dancing princesses

**Comment by timlinux** [comment]
We have killed one....

-[ ] Prince Count Dracular
-[ ] Prince Sigma Gmale

... we are working hard on the rest...

**Comment by Gustry** [comment]
Sorry Charlotte, they are definitely nameless ...

**Comment by ismailsunni** [comment]
We have temporary name actually, Super Mega Flux Capacitor :)
