### ISSUE TITLE
We need to update data.inasafe.org with the new XML keywords

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3012]
### Problem
Some dataset in http://data.inasafe.org don't have the XML keyword file.
Now, with InaSAFE 3.5, the old .keyword file is not read anymore.
Every time we will download a dataset from data.inasafe.org, we will have to recreate these keywords.

### Proposed Solution
Run the keyword wizard to update keywords.

### Environment
* InaSAFE : 3.5
* Data used : http://data.inasafe.org

**Comment by timlinux** [comment]
Note that in 3.5, only keywords from 3.4 and 3.3 will be backwards compatible - see safe/utilities/utilities.py:484.

**Comment by NyakudyaA** [comment]
@Gustry  yes some of the datasets have keywords for 3.2 which will need to be update.

**Comment by timlinux** [comment]
I tested the data in http://data.inasafe.org/InaSAFE%203.5%20Training%20Data/ - it is all working nicely now. I saw one or two 3.3 keyword which should be fine.
