### ISSUE TITLE
installation doc update

### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe#3019]
### Problem
The plugin url at http://docs.inasafe.org/en/user-docs/install.html does not have plugins.xml in it. Screenshots should also be updated. 
### Environment
* InaSAFE : 
* QGIS : 
* OS : 
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :

**Comment by timlinux** [comment]
@adissadis can you update this - also I think we should not be sending people to the experimental repo to install QGIS, but rather the official QGIS repo.

**Comment by adissadis** [comment]
@timlinux ok i will update it. And i will deleted the experimental repo. By the way, i'm not sure about @gubuntu mean about plugin.xml. Which part is it?

**Comment by timlinux** [comment]
Plugins.xml is used to list the available plugins. By the way these pages:

http://experimental.inasafe.org
http://nightly.inasafe.org

Both have links to detailed instructions on how to set them up. But we should really not be encouraging general users to use either of those - rather they should just install from the official QGIS repo.

Regards

Tim

**Comment by timlinux** [comment]
For reference:

http://nightly.inasafe.org/plugins.xml
http://experimental.inasafe.org/plugins.xml

**Comment by adissadis** [comment]
i already remove those section and tell the user to download via official repo http://staging.docs.inasafe.org/en/user-docs/install.html

**Comment by timlinux** [comment]
Thanks very much @adissadis

**Comment by gubuntu** [comment]
my reference to plugin.xml was that it is lacking from the url in the documentation on the page I reference.

**Comment by timlinux** [comment]
Ok thanks Gav. In the light of the subsequent discussions I will close this out.
