### ISSUE TITLE
plugin installation issues

### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe#3020]
### Problem
- the official QGIS repo still has InaSAFE 3.4.2
- Even if I configure the experimental InaSAFE plugin repo, 3.3 or more recent or 'inasafe-experimental' do not appear as installation options, I still only see 3.4.2

### Expected Behaviour
- QGIS repo should have latest stable release of InaSAFE
- experimental repo should work as per docs

### Environment
* InaSAFE : 
* QGIS : 2.14.3
* OS : ubuntu
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :

**Comment by timlinux** [comment]
3.4.2 is the latest version. What version were you looking for?

You can see all our releases here:

https://github.com/inasafe/inasafe/releases
