### ISSUE TITLE
People base actions don't all have the same actions

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3031]
### Problem

In ITB Impact Function we have:

```
def action_checklist(self):
        """Action checklist for the itb earthquake fatality report.

        :returns: The action checklist
        :rtype: list
        """
        total_fatalities = self.total_fatalities
        total_displaced = self.total_evacuated
        rounded_displaced = format_int(population_rounding(total_displaced))

        fields = super(ITBFatalityFunction, self).action_checklist()
        if total_fatalities:
            fields.append(tr(
                'Are there enough victim identification units available '
                'for %s people?') % (
                    format_int(population_rounding(total_fatalities))))
        if total_displaced:
            fields.append(tr(
                'Are there enough shelters and relief items available for '
                '%s people?') % rounded_displaced)
        if rounded_displaced:
            fields.append(tr(
                'If yes, where are they located and how will we '
                'distribute them?'))
        if total_displaced:
            fields.append(tr(
                'If no, where can we obtain additional relief items '
                'from and how will we transport them?'))

        return fields
```

This logic puts in place special actions for dealing with fatalities and displaced persons. I know most pop IF's don't calculate fatalities but it seems none of the others give the actions for displaced persons relief shelters etc.

### Proposed Solution

Do we want to apply these to all pop based IF's - or should we remove if from the ITB IF for consistency.

**Background:** I noticed this while working on #3023 but I will address this ticket in a separate PR once it is decided how to proceed.

**Comment by Charlotte-Morgan** [comment]
Fatality functions for population should have action check list on victim id kits / body bags or whatever.

Actions for displaced / evacuated  people should be consistent.
We need to clarify the definition for the terms "displaced" and 'evacuated"
@easmetz #2920

**Comment by easmetz** [comment]
@Charlotte-Morgan I propose the following definitions that I have added to #2920, taken from the proposed update to the UNISDR definitions in 2015 (I have only recently found this document).

**Displaced**: Persons who, for different reasons and circumstances because of risk or disaster, have to
leave their place of residence. Ref: UNISDR 2015 update http://www.preventionweb.net/files/45462_backgoundpaperonterminologyaugust20.pdf
**Evacuated**: People who, for different reasons or circumstances because of risk conditions or disaster, move temporarily to safer places before, during or after the occurrence of a hazardous event. Evacuation can occur from places of residence, workplace, schools, hospitals to other places. Evacuation is usually a planned and organized mobilization of persons, animals and goods, for
eventual return. Ref: UNISDR 2015 update http://www.preventionweb.net/files/45462_backgoundpaperonterminologyaugust20.pdf

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi - can you please review the action check lists for the earthquake impact and see how the list for displaced is different to the fatality function. @fredychandra - do you have thoughts on this?

**Comment by ivanbusthomi** [comment]
Hi @Charlotte-Morgan,

I compared the results that I got from the three fatality functions. Apart from the difference in numbers of affected people, I did not notice any difference in the action list.
* Displaced
  ![displaced](https://cloud.githubusercontent.com/assets/7351977/18778950/154b883e-81a1-11e6-8c08-f5186808f1fd.PNG)

* ITB
  ![itb](https://cloud.githubusercontent.com/assets/7351977/18778978/2caa2666-81a1-11e6-97d7-42f53a19ee26.PNG)


* Pager
  ![pager](https://cloud.githubusercontent.com/assets/7351977/18778985/31a7396a-81a1-11e6-92ad-77577f760df1.PNG)


___
### combined
![combined](https://cloud.githubusercontent.com/assets/7351977/18779074/90258654-81a1-11e6-85cb-bef6731bac0d.PNG)

___

**CC** : @timlinux @easmetz @fredychandra @Gustry @felix-yew

**Comment by fredychandra** [comment]
Hi @ivanbusthomi 
I find action no 1 is repeating on last check list. Also the number is not exactly same with the Analysis Result.  I proposed no repetition on the check list and we can grouping the action checklist per sector as on issue #3057. 

CC : @Charlotte-Morgan @Gustry @timlinux @felix-yew

**Comment by Charlotte-Morgan** [comment]
Hi @ivanbusthomi and @fredychandra  - I think I have solved this. There is one population exposure action list in concepts.py
