### ISSUE TITLE
Logo for place

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3045]
### Problem
Currently, we do not have symbol for place.
<img width="153" alt="screen shot 2016-07-18 at 12 10 19" src="https://cloud.githubusercontent.com/assets/1609292/16906366/a97b87fc-4ce0-11e6-92f5-23cf413b9066.png">

### Expected Behaviour
We should have a symbol for place.

### Proposed Solution
The place represents : city, town, village, airports.
So it could be a group of buildings.

**Comment by timlinux** [comment]
@MariaSolovyeva can you also add it and ash fall to the graphics used in the brochure and update the graphics repo?

**Comment by felix-yew** [comment]
Hi @Gustry 

Maybe I can suggest a place symbol that I get from iconmonstr. This icon may represent the place symbol.
![iconmonstr-location-12-240](https://cloud.githubusercontent.com/assets/13621886/16974592/726933e8-4e68-11e6-9618-47bdea290072.png)
Source: https://iconmonstr.com/location-12/

Maybe @MariaSolovyeva can modify the symbol much better. :smile:

**Comment by timlinux** [comment]
I think we should take the house out the middle.

**Comment by Gustry** [comment]
Yes, it can be a kind of "google marker" as above or some signposts ?
![signpost](https://image.freepik.com/free-icon/signpost-with-three-arrows_318-48611.png)

**Comment by ismailsunni** [comment]
From noun project, urban image:
![noun_4280](https://cloud.githubusercontent.com/assets/1421861/17546840/2c67f580-5f0e-11e6-8753-27f1e9337eae.png)

Link : [Urban icon](https://thenounproject.com/ochaavmu/collection/ocha-humanitarian-icons/?i=4280)

There are more icon for city, not sure which one we should take...

**Comment by timlinux** [comment]
Maybe rather this one https://thenounproject.com/search/?q=place&i=420702

**Comment by ismailsunni** [comment]
Added in #3133
