### ISSUE TITLE
Analysis details need aggregation info

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3058]
### Problem

![screen shot 2016-07-21 at 5 33 10 pm](https://cloud.githubusercontent.com/assets/178003/17019954/3ce9b4e8-4f69-11e6-8317-1ed5056be0ed.png)

We should see the aggregation layer details here too...

**Comment by Gustry** [comment]
It's a small release blocker

**Comment by Gustry** [comment]
I think we can close this, @lucernae did it
