### ISSUE TITLE
We need a detailed abstract for each impact function

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3062]
**Note this is in draft**
### Problem

In #880, #587 and others we sought to create rich, reusable data from impact functions. We have achieved this now (subject to future tweaking of course!) and now we should start to look at how we can benefit from this.

The reporting standards RFC #2920 and the unified Impact Function approach #2987 already benefit from our 'impacts as data' work.

I think we should also generate a comprehensive report for each impact layer. Currently there is the analysis details section in the report (shown in dock and in PDF) but the information provided is very scant: the hazard and exposure layer names.

There are two parts to what I would like to achieve here:

1) Provide rich provenance data in the analysis details - something like this:

![screen shot 2016-07-19 at 1 08 30 pm](https://cloud.githubusercontent.com/assets/178003/17046655/e27a521e-4fff-11e6-9a76-4287c444d928.png)

This useful, in addition to providing some useful context to the user, will be very useful to developers when bug reports are filed so that we can easily understand the analysis environment used.

2) Generate a detailed abstract

After the impact layer has been computed, it may be passed around to different machines and lose the context of what hazard, exposure and aggregation layers were used. Also we have communally spent a lot of time to collate all the metadata in definitions.py but generally (with partial exception of the wizard) this data is not exposed to our users. I would like to embed a generated report into the abstract for each impact layer;s metadata that includes something like this:

---
# Impact report
## Hazard

**Source:**

**What is a hazard?** A hazard represents a natural process or phenomenon 
that may cause loss of life, injury or other health impacts, 
property damage, loss of livelihoods and services, social and 
economic disruption, or environmental damage. For example; flood, 
earthquake, tsunami and volcano are all examples of hazards.

**Hazard geometry: Raster:** 

A raster data layer consists of a matrix of cells organised into 
rows and columns. The value in the cells represents information such 
as a flood depth value or a hazard class. 

**Hazard layer mode: Continuous** Continuous data can be used in raster hazard or exposure data 
where the values in the data are either integers or decimal 
values representing a continuously varying phenomenon. 
For example flood depth is a continuous value from 0 to the maximum 
reported depth during a flood. 

Raster exposure data such as population data are also continuous. 
In this example the cell values represent the number of people in
cell.

Raster data is considered to be continuous by default and you 
should explicitly indicate that it is classified if each cell in the 
raster represents a discrete class (e.g. low depth = 1, medium depth 
= 2, high depth = 3).

**Hazard category: Single Event** Single event hazard data can be based on either a specific 
event that has happened in the past, for example a flood like 
Jakarta 2013, or a possible event, such as the tsunami that results 
from an earthquake near Bima, that might happen in the future.
## Exposure

**Source**

**What is exposure data?** 

Exposure represents people, property, systems, or 
other elements present in hazard zones that are subject to 
potential losses in the event of a flood, earthquake, volcano etc.

**Exposure geometry: Polygon** 

A layer composed on polygon features that represent areas of hazard 
or exposure. For example areas of flood represented as polygons 
(for a hazard) or building footprints represented as polygons 
(for an exposure). The polygon layer will often need the presence 
of specific layer attributes too - these will vary from impact 
function to impact function and whether the layer represents 
a hazard or an exposure layer. Polygon layers can also be used 
for aggregation - where impact analysis results per boundary
such as village or district boundaries.

**Exposure layer mode: Continuous** Continuous data can be used in raster hazard or exposure data 
where the values in the data are either integers or decimal 
values representing a continuously varying phenomenon. 
For example flood depth is a continuous value from 0 to the maximum 
reported depth during a flood. 

Raster exposure data such as population data are also continuous. 
In this example the cell values represent the number of people in
cell.

Raster data is considered to be continuous by default and you 
should explicitly indicate that it is classified if each cell in the 
raster represents a discrete class (e.g. low depth = 1, medium depth 
= 2, high depth = 3).

---

**Note:** When we have citations for concepts listed above, we would add them to the abstract.
- Maybe we should split continuous and classified mode descriptions to have separate vector and raster notes?

**Comment by Charlotte-Morgan** [comment]
@timlinux - we also need to include hazard_scenario ie single event or multiple event. I think the hazard descriptions for each hazard type will be different depending on whether we are dealing with a single scenario or hazard map. This is also an issue for the definitions.py and use of notes.
@easmetz - feel free to add to this comment with the correct components of the definitions.py :)

**Comment by timlinux** [comment]
@Charlotte-Morgan thanks - it is above for hazard:

> Hazard category: Single Event Single event hazard data can be based on either a specific 
event that has happened in the past, for example a flood like 
Jakarta 2013, or a possible event, such as the tsunami that results 
from an earthquake near Bima, that might happen in the future.

**Comment by Charlotte-Morgan** [comment]
yes - that is what I'm thinking

**Comment by timlinux** [comment]
@myarjunar can you take this and sort it out for 4.1?

**Comment by timlinux** [comment]
Maybe we can include these things (hazard category etc). Please review, ensure that the items mentioned above show in provenance report.

**Comment by Charlotte-Morgan** [comment]
reference this in the rich report
