### ISSUE TITLE
Realtime Flood is not updating

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#3064]
### Problem
InaSAFE realtime flood is not updating. The last recorded flood event in realtime is on 21 June 2016. 
![flood](https://cloud.githubusercontent.com/assets/7351977/17093577/558f7574-5274-11e6-8b8e-241de4da94f0.PNG)

I checked petajakarta, there are actually flood events recorded for this week.
![pj](https://cloud.githubusercontent.com/assets/7351977/17093654/b6ed78d4-5274-11e6-833b-968f26d6551a.PNG)

### Expected Behaviour
the flood event should be updating

### Environment
* InaSAFE : Realtime
* QGIS : 
* OS : 
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :

### Proposed Solution
Make it happy

___
__CC__: 
@lucernae 
@Charlotte-Morgan 
@timlinux

**Comment by timlinux** [comment]
Will you look at this urgently please @lucernae - I also noticed some errors going to sentry so you may want to check there what is going on.

**Comment by lucernae** [comment]
@timlinux already fixed yesterday, but it still regenerates past flood.

**Comment by timlinux** [comment]
Thanks @lucernae will you close this ticket out when all the backlog events are processed?

**Comment by lucernae** [comment]
Past flood regenerated.
