### ISSUE TITLE
InaSAFE 3.5 : Sphere Minimum Standard on InaSAFE Analysis Result

### ISSUE THREAD

**Issue by fredychandra** [inasafe/inasafe#3065]
### Problem
1. Several minimum standard item are not accommodated yet at InaSAFE analysis report
2. The relief item words in InaSAFE analysis report not same with sphere minimum standard words
3. Un-categorized relief item as sphere minimum standard sector

### Expected Behavior
1. The minimum standard/relief item should occur at InaSAFE analysis report
2. The relief item word should same with sphere minimum standard item words
2. The report should has  heading (categorize) for Each basic needs/relief item as sphere minimum standard sector

### Environment
* InaSAFE : 3.5 develop
* QGIS : 2.14.3
* OS : Windows 8
* Data used :
  * Exposure : Java Population
  * Hazard : Flood Class
  * Aggregation : No

### Proposed Solution

1. Add relief items below into InaSAFE Analysis report 
  a.    Clean Water (The standard is 15 Liter/person clean water for personal hygiene)
  b.   Toilet (the standard is 1 Toilet/20 person at public places)
  c.    Covered floor area  (The standard is 3.5 m2/person)
  d.   Clothing (The standard is 2 full sets of clothing, note : in the correct size that are appropriate to the culture, season and climate)
  e.  Mattresses (The standard is 1/person)
  f.  Insecticide bed nets (The standard is 1/person)
  
2. Change relief words item below : 
   a. Water bucket change to **Collecting Water Container [10 - 20 Liter]** 
   b. 20 litre water bucket with cover [bucket] change to **Storage Water Container [10 - 20 liter]**
   c. 100 litre trash bags [bags] change to **Trash Bags [100 liter]**
 
3. Add heading for each relief item categorize  into the Analysis report 
   e.g : 

   **Water Supply, Sanitation and Hygiene Pomotion (WASH)**                                            
    - Daily Clean Water                                                                                                              
    - Collecting Water Container [10 - 20 Liter]                                                                          
    - Storage Water Container [10 - 20 liter]                                                                               
    - Toilet                                                                                                                                
 
  **Food Security**                             
   - Food [Kkal]                               

  **Shelter, settlement and non-food item**
   - Covered floor area
   - Clothing [2 set]
   - Blanket [100 x 75 cm]
   - Mattresses
   - Insecticide bed nets
   - saucepan	
   - basin	
   - knife	
   - rice ladle	
   - plate	
   - spoon	
   - mug

    Related to #3027 #2920 
@timlinux @assefay @maning @easmetz @Gustry @Charlotte-Morgan @ivanbusthomi  @samnawi

@felix-yew, I think this will impact the info-graphic that  you are working on it. 

Expected (probably) for next InaSAFE 3.6 report standard
Minimum Need Standard able to break down into aggregation table too. So users can see  each item in each area (aggregation).

**Comment by timlinux** [comment]
Hi @fredychandra 

I am just wondering if you have seen this ticket: #1317 and this PR: #2983 ? It would be great if you could update this ticket following a review of the work I have done, noting anything you would like to see done differently.

Thanks!

**Comment by fredychandra** [comment]
HI @timlinux 
Yes, I have looked on the ticket #1317  and # #2983. What I have tried to review is also based on that ticket. Sorry did not following this issue on the work (ticket) that you have done. Further, I will continue post on it.

Thanks

**Comment by timlinux** [comment]
@fredychandra just for quick reference, here is what the SPHERE report looks like:

![screen shot 2016-06-22 at 15 58 35](https://cloud.githubusercontent.com/assets/178003/16295484/796ff29a-3927-11e6-8036-78cdbb50e7de.png)


Running on JK Flood ( @Charlotte-Morgan 's favourite! ) I get this:

![screen shot 2016-06-23 at 09 45 40](https://cloud.githubusercontent.com/assets/178003/16295505/91574cd2-3927-11e6-8279-38965aa931d7.png)

Note I updated the provenance to be SPHERE not Perka

So maybe you can just give me a bullet list of tweaks you would like to make?

**Comment by timlinux** [comment]
The numbers for spoon, mug, plate seem very high - maybe we should check those...

**Comment by fredychandra** [comment]
Hi @timlinux 
I checked the sphere configuration default on InaSAFE 3.5 develop 
![sphere configuration](https://cloud.githubusercontent.com/assets/6345285/17160964/77149d04-53d3-11e6-8c23-fa0e5d7dcf31.JPG)

My suggestion : 
1. The blue circle number should 0,2 
2. We can change the configuration default on the yellow high-lite (list below)
     a. Water bucket change to **Collecting Water Container [10 - 20 Liter]** 
     b. 20 litre water bucket with cover [bucket] change to **Storage Water Container [10 - 20 liter]**
     c. 100 litre trash bags [bags] change to **Trash Bags [100 liter]**


![sphere result](https://cloud.githubusercontent.com/assets/6345285/17161016/ed1f73e8-53d3-11e6-937e-90d7955d6256.JPG)

3. Then on the report (Arrow high-lite) I suggest to add relief items listed below (as ref :  sphere minimum standard) : 
    a. Clean Water (The standard is 15 Liter/person clean water for personal hygiene)
    b. Toilet (the standard is 1 Toilet/20 person at public places)
    c. Covered floor area (The standard is 3.5 m2/person)
    d. Clothing (The standard is 2 full sets of clothing, note : in the correct size that are appropriate to the culture, season and climate)
   e. Mattresses (The standard is 1/person)
   f. Insecticide bed nets (The standard is 1/person

4. Add heading for each relief item categorize into the Analysis report (see above for the detail)

Note : the number of spoon, mug and plate is OK (as sphere minimum standard). It counts as how many people need to evacuation or IDP's number

Thanks

**Comment by fredychandra** [comment]
Hi @timlinux 
I checked the sphere configuration default on InaSAFE 3.5 develop 
![sphere configuration](https://cloud.githubusercontent.com/assets/6345285/17160964/77149d04-53d3-11e6-8c23-fa0e5d7dcf31.JPG)

My suggestion : 
1. The blue circle number should 0,2 
2. We can change the configuration default on the yellow high-lite (list below)
     a. Water bucket change to **Collecting Water Container [10 - 20 Liter]** 
     b. 20 litre water bucket with cover [bucket] change to **Storage Water Container [10 - 20 liter]**
     c. 100 litre trash bags [bags] change to **Trash Bags [100 liter]**


![sphere result](https://cloud.githubusercontent.com/assets/6345285/17161016/ed1f73e8-53d3-11e6-937e-90d7955d6256.JPG)

3. Then on the report (Arrow high-lite) I suggest to add relief items listed below (as ref :  sphere minimum standard) : 
    a. Clean Water (The standard is 15 Liter/person clean water for personal hygiene)
    b. Toilet (the standard is 1 Toilet/20 person at public places)
    c. Covered floor area (The standard is 3.5 m2/person)
    d. Clothing (The standard is 2 full sets of clothing, note : in the correct size that are appropriate to the culture, season and climate)
   e. Mattresses (The standard is 1/person)
   f. Insecticide bed nets (The standard is 1/person

4. Add heading for each relief item categorize into the Analysis report (see above for the detail)

Note : the number of spoon, mug and plate is OK (as sphere minimum standard). It counts as how many people need to evacuation or IDP's number

Thanks
