### ISSUE TITLE
We need to review the IFC Wizard dialog

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3068]
## Fact

Wizards do not have help files
## problem

We need to make sure that wizard users have sufficient information to step through the wizard and make informed choices at each step.
## proposed solution

work through each wizard and review the text to make sure is provides sufficient information to users. Eg in these steps:
- [ ] selecting hazard and exposure data
- [ ] selecting data type
- [ ] **choosing an impact function - priority**
- [ ] etc
## goal

The priority is to provide support at the step where uses select an impact function and to keep the text simple so that it does not impact on the size and layout of the wizard
## cc

@timlinux

**Comment by Charlotte-Morgan** [comment]
@ivan - how is this going. 
Is there something to review?

**Comment by ivan** [comment]
@ivan sends me an email

**Comment by timlinux** [comment]
Can we get an update on this @ivanbusthomi ...or can you close it if you are happy?

**Comment by timlinux** [comment]
@ismailsunni has been adding help files for 4.2 - can you please review his work @ivanbusthomi and close if you are happy?
