### ISSUE TITLE
We need to define new concepts

### ISSUE THREAD

**Issue by easmetz** [inasafe/inasafe#3079]
### Problem

With the new system of using concepts (#3057), we only have three concepts currently defined. We need concepts defined for all key words that occur in reports.

### Proposed Solution

We need to define new concepts for:
concept_displaced
concept_evacuated
concept_affected
+ more to come

### justification

Displaced and evacuated are two words that are currently found in IF reports but are not defined. If we defined these words as concepts, we could call on them whenever they are used in any hazard IF, instead of having them permanently in the notes and assumptions for population where they may sometimes be redundant if evacuated and displaced are not used in the IF (e.g. at the moment displaced is only used in the EQ IF, but this may change in the future).

### cc
@Charlotte-Morgan @timlinux

**Comment by timlinux** [comment]
@easmetz I think it will generally be a better workflow if you define the concepts and then ask me if you need help to integrate them into various places.

**Comment by Charlotte-Morgan** [comment]
Hi @timlinux - I think this is done - closing this. Please reopen if needed

**Comment by timlinux** [comment]
Just a note for back reference - the concepts are defined but not actually referenced by anything. We need to figure out how / where to integrate them into detailed reporting...

**Comment by Charlotte-Morgan** [comment]
ok - good point. They were to be used in the wizards but some of the concept definitions were so big that they don't fit in the wizard. so we have cut down versions but the full concept for reference.
