### ISSUE TITLE
Notes and actions for exposure_population are in exposure_people_in_buildings

### ISSUE THREAD

**Issue by easmetz** [inasafe/inasafe#3082]
### Problem

In definitions.py, notes and actions for exposure_population were instead placed in exposure_people_in_buildings. The default should be exposure_population instead of exposure_people_in_buildings. I have now changed definitions.py to reflect this, but impact functions may still be directing to exposure_people_in_buildings.

### Proposed Solution

All impact functions should now be directed to exposure_population instead of exposure_people_in_buildings.

### cc

@Charlotte-Morgan @timlinux

**Comment by timlinux** [comment]
I think this is fine now - all the population IF's are referring to exposure_population which you can see from the screenshot below:

![screen shot 2016-08-05 at 10 18 07 am](https://cloud.githubusercontent.com/assets/178003/17430693/175c907c-5af6-11e6-95ba-4694a032e8e9.png)
