### ISSUE TITLE
We need all reports to have consistent analysis questions

### ISSUE THREAD

**Issue by easmetz** [inasafe/inasafe#3084]
### Problem

Currently not all reports have analysis questions (e.g. many reports on roads or land cover), and those that do are inconsistent.
### Proposed Solution
- Make sure all reports have analysis questions
- Make all analysis questions consistent with the new standards found in https://github.com/inasafe/inasafe/blob/develop/docs/reporting-standards.md
### cc

@Charlotte-Morgan

**Comment by Charlotte-Morgan** [comment]
hi @timlinux  - I guess this is the sort of thing we are looking to have implemented in version 4.0

**Comment by Gustry** [comment]
I think this is done in V4. I think I can close this ticket.
