### ISSUE TITLE
We need all reports to have robust action checklists

### ISSUE THREAD

**Issue by easmetz** [inasafe/inasafe#3085]
### Problem

Currently not all reports have complete action checklists. For example volcanic ash on places does not have an action checklist.
### Proposed Solution
- Make sure all reports have action checklists
- Make sure all action checklists include information relating to the exposure, the hazard and the impact function, using the new standards found in https://github.com/inasafe/inasafe/blob/develop/docs/reporting-standards.md
### cc

@Charlotte-Morgan

**Comment by Gustry** [comment]
I think we can also close this ticket.
Every reports have action checklist now.
