### ISSUE TITLE
We need all reports to have robust and appropriate notes and assumptions

### ISSUE THREAD

**Issue by easmetz** [inasafe/inasafe#3086]
### Problem

Currently not all reports have complete or appropriate notes and assumptions. Some action checklists do not match the impact function used. E.g. Volcanic ash on places has notes and assumptions relating to tsunami hazard.
### Proposed Solution
- Make sure all reports have notes and assumptions
- Make sure all notes and assumptions include information relating to the exposure, the hazard and the impact function, using the new standards found in https://github.com/inasafe/inasafe/blob/develop/docs/reporting-standards.md
### cc

@Charlotte-Morgan

**Comment by ismailsunni** [comment]
I think we can close this. right @timlinux @Charlotte-Morgan ? Since we have put notes and assumptions in the definition, nicely.

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni 
I think this is probably not complete but we do have place holders for all content.
I hope that @felix-yew is writing tickets for any reports that need more notes and assumptions when he checks results from the batch testing

**Comment by felix-yew** [comment]
Hi @Charlotte-Morgan @ismailsunni - sorry for the delay response. I have done for the batch runner testing and there is nothing missing. For example the volcanic ash report notes:
![image](https://user-images.githubusercontent.com/13621886/32769113-21cf650e-c94d-11e7-8a5a-e282d533c2f7.png)
the notes and assumption have been accommodated. :+1:

**Comment by Charlotte-Morgan** [comment]
thanks @felix-yew we can close I think
