### ISSUE TITLE
We need to use the word medium and not moderate

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3091]
### problem
The terminology used to describe relative hazard is inconsistent.
We should use the term medium and not moderate.
The term in the impact function notes should be the same as the term used in the impact report.

eg
Earthquake Vector vs Buildings Centroid
Earthquake Vector vs Infrastructure
Earthquake Vector vs Buildings Polygon
Tsunami Raster vs Infrastructure
Tsunami Raster vs Buildings Polygon

### proposed solution
update the terminology in the notes

### cc
@felix-yew @easmetz

**Comment by felix-yew** [comment]
Hi @Charlotte-Morgan 

Sorry for being late, I have tried an analysis of Earthquake Vector vs Buildings Centroid, and the "moderate" still appear. See the image below :
![image](https://cloud.githubusercontent.com/assets/13621886/17287051/8abb696e-57f7-11e6-8ab9-641a42f20657.png)
We hope it will have an update in the latest version.

**Comment by Charlotte-Morgan** [comment]
Hi @felix-yew - thanks for your feedback.  I think its fixed with the PR after you last looked? Maybe you can take another look please.
Oh - as discussed, this is a dynamic note reading values in the earthquake hazard data :)

**Comment by felix-yew** [comment]
Hi @Charlotte-Morgan 

Sorry, I just hear that this is a dynamic value. I have checked the Nagekeo EQ attribute table and find the medium in moderate. See the image below :
![image](https://cloud.githubusercontent.com/assets/13621886/17290972/750afe18-580b-11e6-80e1-d60337ed0a4b.png)
This image is the original attribute data. The medium is still in moderate.

![image](https://cloud.githubusercontent.com/assets/13621886/17291043/caf47660-580b-11e6-96f1-38a0268be91e.png)
And, I have created in a new attribute table with the new column field as 'H_zones'. Then, I sign the layer with the new Keyword Wizard to read it.

![image](https://cloud.githubusercontent.com/assets/13621886/17291100/241c78c8-580c-11e6-9c8c-32223afb1c95.png)
After I run the analysis, the result is good. The hazard zone change into the medium, rule out the hazard zone is not in sequence, from high-medium-low.

**Comment by Charlotte-Morgan** [comment]
Excellent - thanks @felix-yew

**Comment by Charlotte-Morgan** [comment]
If you want the dynamic list to be in hazard order and not alphabetical order you need to write a separate ticket - mark it as a papercut though

**Comment by felix-yew** [comment]
I have created a ticket about "Sequencing the hazard zone in notes" #3099

**Comment by Charlotte-Morgan** [comment]
i think this is fixed. closing this one
