### ISSUE TITLE
Sequencing the hazard zone in notes

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#3099]
### Problem

I have tried the InaSAFE 3.5 dev, and I find some problems. Some of the hazard zone sequences in the report table, especially in notes and assumptions part, has no consistency order, see the image below :
![image](https://cloud.githubusercontent.com/assets/13621886/17316124/90c6b8dc-589b-11e6-8196-341eb7f99bbb.png)

Maybe this problem is related to #2385 
### Expected Behaviour

The hazard zone in notes can be represented in sequence and by hazard classes, not by alphabetical order. 
### Environment
- InaSAFE : 2.14.3
- QGIS : 3.5 dev
- OS : Win 7 64-bit/ RAM 12 GB
- Data used :
  - Exposure : 
  - Hazard : 
  - Aggregation :
### Proposed Solution

Make it happy :smile: 

Cc: @Charlotte-Morgan @timlinux @Gustry @samnawi @ismailsunni

**Comment by Charlotte-Morgan** [comment]
Hi @felix-yew - as discussed, this is a minor papercut and is driven by the dynamic notes in the impact functions.  This might be good to hold until we have the 7 princes implemented

**Comment by Gustry** [comment]
I think we can close this issue. We reviewed all these notes.

**Comment by felix-yew** [comment]
Hi, @Gustry I think this issue has been fixed.
![image](https://cloud.githubusercontent.com/assets/13621886/23640623/7e312b04-0321-11e7-90e0-cec3d09b35d2.png)
LGTM :+1: Thank you
