### ISSUE TITLE
Wrong classes in keywords creation for a generic hazard

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#3101]
### Problem

It seems strange that when using a generic layer and trying to define keywords using generic IF they are two classes that appear.
- Flood classes
  - Generic classes

![generic](https://cloud.githubusercontent.com/assets/2510900/17327900/e550d148-58ba-11e6-8e58-4679df505307.png)
### Expected Behaviour

Show the correct classes for each subsequent IF
### Environment
- InaSAFE :  3.5
- QGIS :  2.14.3
- OS :  Ubuntu 16.04
- Data used :  from #2847
  - Exposure : 
  - Hazard : 
  - Aggregation :
### Proposed Solution

Make it happy

**Comment by ismailsunni** [comment]
Hi @NyakudyaA 
This is known issue. We will address it with #2987

**Comment by Gustry** [comment]
Can we close this issue ? Is-it fixed @ismailsunni ?

**Comment by ismailsunni** [comment]
Yes, we can close this
