### ISSUE TITLE
Minus Number in the ITB Bayesian Impact Function Result

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3103]
### Problem

Minus number on ITB Bayesian Impact Function on some areas.
### Expected Behaviour

The result should be making sense.
### Environment
- InaSAFE : 3.4.2, 3.5
- QGIS : 2.14.2
- OS : OSX, Ubuntu 16.04, Windows 7
- Data used :
  - Exposure : People (Raster Hazard/02 Exposure/Population/West_Sumatera_Population_WGS84.tif)
  - Hazard : Earthquake in Padang 2009 (Raster Hazard/01 Hazard/Padang_EQ_2009_WGS84.tif)
  - Aggregation : No

The test data can be obtained in this link [EQ Raster Hazard](https://github.com/inasafe/inasafe/files/398608/EQ.Raster.Hazard.zip)
### Proposed Solution

The ITBBayesianFatalityFunction should give a non-negative result which makes sense.

This issue related to #2969. See comment:
- https://github.com/inasafe/inasafe/issues/2969#issuecomment-237141773

I have dig around, and it seems the problem lies on how we calculate the displaced or fatalities, or even in the compute_fatality_rate.

I assigned this to @dynaryu since it seems you are the best person who knows about the EQ IF.

This issue will close #2969 since it's different problem.

cc @Charlotte-Morgan @timlinux

**Comment by wonder-sk** [comment]
Calculation of number of displaced people is not consistent with the way how number of fatalities is calculated, leading to these negative results.

For displaced people the impact function sums up medians of a fatality rate vectors. For fatalities it is the other way round: the vectors are first summed up and then the median is calculated.

Related issue: #3559

**Comment by timlinux** [comment]
Lets close this in favour of #3559
