### ISSUE TITLE
We need to create citations for concepts

### ISSUE THREAD

**Issue by easmetz** [inasafe/inasafe#3117]
### Problem
Currently concepts such as evacuated people and displaced people (found in definitions.py) do not have citations when they are taken from the UNISDR vocabulary.

### Proposed Solution
Create a citations field for all concepts in definitions.py.

### cc
@Charlotte-Morgan

**Comment by Charlotte-Morgan** [comment]
hi @easmetz 
@timlinux and I discussed the definitions.py structure a bit and he suggested we could have a 'source' for the UNISDR reference rather than a citation.

@timlinux  - please add something so Libby can add the source details for each concept

**Comment by timlinux** [comment]
@Charlotte-Morgan ok will do..

**Comment by timlinux** [comment]
@Charlotte-Morgan I'm trying to remember the discussion about source. Elsewhere I have used ``citations`` with a ``text`` and ``link`` property. I propose that for now we do the same for concepts to keep things consistent. See my incoming PR on this.

```
    'citations': [
        {
            'text': tr('UNISDR (2009) Terminology on disaster risk reduction.'),
            'link': 'https://www.unisdr.org/we/inform/terminology'
        }
    ],
}
```
