### ISSUE TITLE
BUG: The mystery totals

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3118]
# problem
Some impact report tables (population impacts) have meaningless totals in the detailed age, detailed gender and detailed minimum needs reports. The totals add people hygiene packs and rice in different units.

This explains why @felix-yew did some interesting infographic calculations :) 
eg flood raster on population raster in Jakarta.

![image](https://cloud.githubusercontent.com/assets/5743135/17471199/a52b89d0-5d6c-11e6-8f23-c92d8dbd1330.png)

the summary table above shows the total number affected

![image](https://cloud.githubusercontent.com/assets/5743135/17471252/13516f74-5d6d-11e6-9cd0-f06f215eba0d.png)

The detail table above then provided details for the affected population. The total on the right side of the tables is not required.

The same happens for aggregation reports
![image](https://cloud.githubusercontent.com/assets/5743135/17471288/497b97fa-5d6d-11e6-84f3-6ec6a0e0c6ee.png)

# proposed solution
remove the total at the right hand side of these tables.

**Comment by Charlotte-Morgan** [comment]
@felix-yew - please add to this ticket if you discover the same type of error on any other tables

**Comment by timlinux** [comment]
Oh thats bad, yeah lets fix that as a blocker for 3.5...

**Comment by felix-yew** [comment]
Hi @Charlotte-Morgan @timlinux 

I had thought that I might be wrong at that time :sweat_smile: 
I try in random IF, in tsunami we find this problem, too.
the detailed of gender and age report :
![image](https://cloud.githubusercontent.com/assets/13621886/17472619/462e0f20-5d76-11e6-9fd4-8d4ecab94162.png)
I really confuse about this total on the left and right, and the same total (on the left) between the detailed gender and age reports.

the detailed of minimum needs report :
![image](https://cloud.githubusercontent.com/assets/13621886/17472564/dfb9dae4-5d75-11e6-8923-43008f094dd8.png)

Make it happy :smile:

**Comment by ismailsunni** [comment]
Hi @felix-yew and @Charlotte-Morgan 
I believe we only remove for population.
Here for road and building:

<img width="1228" alt="screen shot 2016-08-08 at 15 10 57" src="https://cloud.githubusercontent.com/assets/1421861/17473395/7b5d097c-5d7a-11e6-9254-f4c238f72b60.png">
<img width="379" alt="screen shot 2016-08-08 at 15 09 39" src="https://cloud.githubusercontent.com/assets/1421861/17473401/8244bf5a-5d7a-11e6-885d-f3cf1d60deaa.png">

Am I correct?

**Comment by felix-yew** [comment]
Hi Mas @ismailsunni 

Yes, I think only the population IF that should be fixed immediately. For roads and buildings, I think it is in the same unit in each other and it can be added directly.

**Comment by Charlotte-Morgan** [comment]
@ismailsunni  - +1 we only remove in population IF not buildings or roads

**Comment by Charlotte-Morgan** [comment]
@felix-yew - in the population tables the total at the left is the affected population (as per the table heading)
