### ISSUE TITLE
Need question mark in analysis results of InaSAFE report

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#3122]
### Problem
There is a sentence opening statement in analysis results of InaSAFE report. But, it is really a sentence or needs a question mark?
![image](https://cloud.githubusercontent.com/assets/13621886/17502704/55fb75d4-5e14-11e6-9f58-d0850da5f770.png)

### Expected Behaviour
If there is a question, so it needs a question mark.

### Environment
* InaSAFE : 
* QGIS : 
* OS : 
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :

### Proposed Solution
Make it happy :smile:

**Comment by ismailsunni** [comment]
What do you think @Charlotte-Morgan , should we add question mark? It's easy to add, just need the green light from you :)

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni - yes please.  According to the standard fro impact report questions, we should have a question mark at the end. https://github.com/inasafe/inasafe/blob/develop/docs/reporting-standards.md
see reports / analysis question
