### ISSUE TITLE
dummy

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3129]

**Comment by timlinux** [comment]
Are you referring to me? :-)

``|>`` <- Joke flag....

**Comment by Charlotte-Morgan** [comment]
No - I have a dummy ticket for pasting pics in that will end up in standards :)

**Comment by timlinux** [comment]
Ah - by the way you don't actually need to save the ticket to do that. Just start a new issue, drag and drop your image in, copy the url then discard the issue.

**Comment by Charlotte-Morgan** [comment]
hmm - but if i do it from waffle - it auto saves. I will try a different way next time.
