### ISSUE TITLE
Check if we need to update make update-translation-strings for safe package only

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3135]
### Problem

Currently the script will check to all python file. Meanwhile, we should only care / translate to the strings under safe directory only.
### Expected Behaviour

Only get strings from safe directory.
### Proposed Solution

Check `scripts/update-strings.sh`

Notes: this is just my note. I will check tomorrow again.

**Comment by Gustry** [comment]
Tomorrow is a long day ;-)

**Comment by ismailsunni** [comment]
@gustry exactly :D

**Comment by ismailsunni** [comment]
@Gustry tomorrow has finally come :D
