### ISSUE TITLE
Pytz timezones cache initialized to empty list

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#3145]
### Problem

Pytz timezones cache initialized to empty list. So any subsequent timezone parsing failed.
Found regarding issues #2319 .
### Expected Behaviour

Pytz timezone safely parsed
### Environment
- InaSAFE : 3.5
- QGIS : 2.16
- OS : Only on Windows OSes
### Proposed Solution

Investigate why this behaviour happened in windows

**Comment by ismailsunni** [comment]
This is fixed, right @lucernae ?

**Comment by timlinux** [comment]
Please close if this is fixed @lucernae

**Comment by lucernae** [comment]
Honestly, I don't remember it anymore.
Maybe we can just close it? Since it happens only in QGIS 2.16 Windows?
