### ISSUE TITLE
BUG: Volcanic ash on airports should be able to return no results

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3151]
# problem
Volcanic ash on places (airports) returns an error if no airports are affected - when run from the IFCW.

# error message
![image](https://cloud.githubusercontent.com/assets/5743135/17613015/c81b223e-6082-11e6-85e1-0db220a58ca9.png)

# proposed solution
It should be acceptable for the impact function to return no results.
The user should get advice to say that no results were returned. I think this should not be an exception.
The same notes that are given to the user in the dock could be used in the wizard.

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
I tried in my machine, I got a prettier message, like this:
<img width="1387" alt="screen shot 2016-08-15 at 11 16 15" src="https://cloud.githubusercontent.com/assets/1421861/17655539/b79f677c-62d9-11e6-9806-506a835b9ba5.png">

Can you share your data ?

**Comment by ismailsunni** [comment]
Ah, sorry, I should use IFCW.
I will make a PR for this.
