### ISSUE TITLE
The legend of volcanic ash report is not updated yet

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#3152]
### Problem

The interval in legend is not updated yet based on the latest information from Adele. This is the current legend in the report.
![legend](https://cloud.githubusercontent.com/assets/7351977/17619492/e1cef70a-60af-11e6-97fa-1dc21dc1562c.PNG)

according to this comment in https://github.com/inasafe/inasafe/issues/2491#issuecomment-235457961, this is what it should look like.
- 0.01 - 0.1 (Very Low)
- 0.1 - 2 (Low)
- 2 - 5 (Medium)
- 5 - 10 (High)
- greater than 10 (Very High)
### Expected Behaviour

The legend should show correct interval
### Environment
- InaSAFE : 3.5
- Data used : Volcanic ash
  - Exposure : 
  - Hazard : 
  - Aggregation :
### Proposed Solution

make it happy 

---

CC: @timlinux @ismailsunni @lucernae @Charlotte-Morgan @samnawi @felix-yew

**Comment by Charlotte-Morgan** [comment]
actually it is better for classes to be mutually exclusive

Very low 0.01 - 0.1 
Low >0.1 - 2
Medium >2 - 5
High >5 - 10
Very high >10 

Please update legends for volcanic ash impact functions.
This also needs tweaking in the change log

@timlinux @adele @lucernae @ivanbusthomi

**Comment by ivanbusthomi** [comment]
> actually it is better for classes to be mutually exclusive

sorry, I missed the ">" sign :sweat_smile:

**Comment by ivanbusthomi** [comment]
I am not really sure whether it's the same problem or not, but I think it might be related, when I tried running with another interval (this interval :point_down: )
![opt](https://cloud.githubusercontent.com/assets/7351977/17620141/6fc3d3e2-60b4-11e6-85f2-7fd037340b62.PNG)

I got this :point_down: result which doesn't comply to what I expected it would be
![legend2](https://cloud.githubusercontent.com/assets/7351977/17620160/8f39cdc6-60b4-11e6-9bfa-4e80b08be12c.PNG)

Using above interval, this is what I expected it would look like
* Very low >0.05 - 0.15
* Low >0.15 - 2.5
* Medium >2.5 - 5.5
* High >5.5 - 15
* Very High >15

**Comment by ivanbusthomi** [comment]
This issue might be related to this https://github.com/inasafe/inasafe/issues/3653. This is current state of the map legend on volcanic ash,
![image](https://cloud.githubusercontent.com/assets/7351977/22283649/0426bcc8-e316-11e6-9c98-adb01b41a021.png)

**Comment by Gustry** [comment]
@ivanbusthomi I'm working on it. I will make a PR today.

**Comment by Gustry** [comment]
I made a PR and it has been merged already in develop.
Is this ticket still relevant ?

**Comment by samnawi** [comment]
![image](https://cloud.githubusercontent.com/assets/8871958/22544852/1bc19818-e969-11e6-8e46-73117a52c760.png)

I guess it's already done
