### ISSUE TITLE
TypeError in running flood vector and population vector

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#3153]
### Problem
I try the InaSAFE 3.5 release and running the flood vector and population vector with aggregation then find a TypeError. And the error occurs again when mas @samnawi has been tested the same impact function without aggregation.
![typeerror_flood v_pop v_agg_q2 16_whole area](https://cloud.githubusercontent.com/assets/13621886/17619676/25e9aef2-60b1-11e6-8014-cb496cf74911.jpg)
```
Details
These additional details were reported when the problem occurred.
An exception occurred when running the impact analysis.
NULL is not JSON serializable

Diagnostics
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 901, in run_analysis self._impact = self._calculate_impact()
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\impact_functions\base.py", line 1815, in _calculate_impact json.dump(impact_data, json_file, indent=2)
In file "C:\PROGRA~1\QGIS21~1.0\apps\Python27\lib\json\__init__.py", line 189, in dump for chunk in iterable:
In file "C:\PROGRA~1\QGIS21~1.0\apps\Python27\lib\json\encoder.py", line 434, in _iterencode for chunk in _iterencode_dict(o, _current_indent_level):
In file "C:\PROGRA~1\QGIS21~1.0\apps\Python27\lib\json\encoder.py", line 408, in _iterencode_dict for chunk in chunks:
In file "C:\PROGRA~1\QGIS21~1.0\apps\Python27\lib\json\encoder.py", line 408, in _iterencode_dict for chunk in chunks:
In file "C:\PROGRA~1\QGIS21~1.0\apps\Python27\lib\json\encoder.py", line 332, in _iterencode_list for chunk in chunks:
In file "C:\PROGRA~1\QGIS21~1.0\apps\Python27\lib\json\encoder.py", line 332, in _iterencode_list for chunk in chunks:
In file "C:\PROGRA~1\QGIS21~1.0\apps\Python27\lib\json\encoder.py", line 442, in _iterencode o = _default(o)
In file "C:\PROGRA~1\QGIS21~1.0\apps\Python27\lib\json\encoder.py", line 184, in default raise TypeError(repr(o) + " is not JSON serializable")
```
But, when I try in very small area, the impact function can work properly:
![image](https://cloud.githubusercontent.com/assets/13621886/17619732/80d8843c-60b1-11e6-8235-2a49fe78328e.png)
The image above is a map result.

And the table result.
![image](https://cloud.githubusercontent.com/assets/13621886/17619758/aa15dc0a-60b1-11e6-9cde-f9861822f59c.png)

This issue is similar with #2846 

### Expected Behaviour
This impact function can work normally.

### Environment
* InaSAFE : 3.5 release
* QGIS : 2.16 and 2.14.3
* OS : Win 7-64bit/ RAM 12GB
* Data used :
  * Exposure : 
[Population.zip](https://github.com/inasafe/inasafe/files/415113/Population.zip)
  * Hazard : 
[01 Hazard.zip](https://github.com/inasafe/inasafe/files/415107/01.Hazard.zip)
  * Aggregation : 
[03 Aggregation Data.zip](https://github.com/inasafe/inasafe/files/415110/03.Aggregation.Data.zip)

### Proposed Solution
Make it happy :smile: 

Cc: @Charlotte-Morgan @lrpower @samnawi @ivanbusthomi @timlinux @ismailsunni

**Comment by ismailsunni** [comment]
Hi @felix-yew 
I found the problem. It's the Population Vector 2013 that has NULL value in RW Attribute:
<img width="1344" alt="screen shot 2016-08-15 at 10 02 16" src="https://cloud.githubusercontent.com/assets/1421861/17654647/84a5bd80-62cf-11e6-9650-19d9bee7df66.png">

If you fix the NULL value, you will able to run the analysis.

You can run in smaller area because there is no NULL value in your smaller area (you are lucky then).

The problem is different from #2846 (mostly because GIS thing). This issue more on the the json can't handle the NULL value to be written.

I will make a fix to handle this NULL value asap.
