### ISSUE TITLE
Infographic: how should we show people?

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3155]
# problem

In the future we hope to use infographics to symbolise analysis results. 
eg we may use a single person symbol to represent 100 people
![people_man_100px](https://cloud.githubusercontent.com/assets/5743135/17621295/718a33c6-60bc-11e6-92db-b6de76eb7d91.png)

but how should we show 50 people or 89 people?
# proposed solution

We should use part of a single person to represent 50 people - but which part?
The top - 
![image](https://cloud.githubusercontent.com/assets/5743135/17621347/e4888f08-60bc-11e6-9f7f-410e3a615b51.png)

The bottom 
![image](https://cloud.githubusercontent.com/assets/5743135/17621361/ef3c7ee6-60bc-11e6-9e84-4cc68eed87cc.png)

Or maybe one side
![image](https://cloud.githubusercontent.com/assets/5743135/17621365/fa1f9bcc-60bc-11e6-825e-bab151e3be35.png)

And how will we show rounding of people - if we round people up what will they look like?
![image](https://cloud.githubusercontent.com/assets/5743135/17621380/146a47d4-60bd-11e6-94c6-52d6f6a0ad25.png)

Make it happy :)
# cc

@samnawi @timlinux @ismailsunni @fredychandra @ivanbusthomi

**Comment by mbernasocchi** [comment]
why don't you split the persons height by the amount of people it represents (e.g 100) and then color the percentage (say 50% or 89%)

**Comment by ismailsunni** [comment]
@mbernasocchi why do we need the percentage if we already know the amount?
+1 for cut it from one side.

**Comment by felix-yew** [comment]
+1 for cut it from one side, too.

**Comment by mbernasocchi** [comment]
The percentage is just in case 1 person can represent different quantity of people.
+1 for sideways

**Comment by samnawi** [comment]
:+1 for sideways

**Comment by Charlotte-Morgan** [comment]
hi @felix-yew - this ticket was a joke :)
