### ISSUE TITLE
Landuse with Earthquake or Volcano Hazard zone show no result

### ISSUE THREAD

**Issue by adissadis** [inasafe/inasafe#3169]
### Problem

There was a problem when i tried to run analysis using Nagekeo Landuse Data and Nagekeo EQ Hazard or Nagekeo Volcano Hazard Zone. It showed no result because there are no Nagekeo Landuse that affected by the hazard zone area. The data is already in the same projection and already overlap each other. And there was no clue about the error:
![image](https://cloud.githubusercontent.com/assets/2520159/18040702/12c2329a-6ddb-11e6-9905-a4635402fa0d.png)

English version:
![image](https://cloud.githubusercontent.com/assets/2520159/18040736/6b2dca2a-6ddb-11e6-9b31-f5f79c626fe4.png)
### Expected Behaviour

The analysis result will be show the number of landuse that affected by the hazard zone area.
### Environment
- InaSAFE : 3.5.1 from Repository Github
- QGIS : 2.14.5
- OS :  Windows 10 64 bit
- Data used :
  - Exposure : Nagekeo Landuse
  - Hazard : Nagekeo EQ or Nagekeo Volcano Hazard Zone
  - Aggregation : -

Data:
https://drive.google.com/file/d/0Bxk-3mw_fhapcUZuWUdfWFp2bEE/view?usp=sharing

**Comment by Gustry** [comment]
I'm closing this ticket as we made a lot of work on landcover. Please open a new ticket if you need.
