### ISSUE TITLE
[Bug] Attribute Error for All Hazard Building Impact Scenario using IFCW

### ISSUE THREAD

**Issue by harrymahar** [inasafe/inasafe#3170]
### Problem

When I want to run Earthquake for building impact scenario using IFCW **without aggregation layer**, I got Attribute Error for my scenario. When I change the hazard layer with flood, tsunami and volcano then run them with same scenario using IFCW, the result still has attribute error. However, when I add an aggregation layer for all hazard building impact function, I have a good result.

 I have this bug both in QGIS using Bahasa and English Language.

![ifcw error](https://cloud.githubusercontent.com/assets/2534179/18041589/a73ddcc2-6de4-11e6-9c6a-4290c3e8ec49.gif)

```
**Diagnose**
1. In file "C:/Users/Asus A450C/.qgis2/python/plugins\inasafe\safe\utilities\analysis_handler.py", line 378, in completed report = self.show_results()
2. In file "C:/Users/Asus A450C/.qgis2/python/plugins\inasafe\safe\utilities\analysis_handler.py", line 426, in show_results postprocessor_data = self.impact_function.postprocessor_manager.\
```
### Expected Behaviour

The result should be shows how many affected building for each of its type even without an aggregation layer
### Environment
- InaSAFE : 3.5.0.dev-master
- QGIS : 2.14.3 Essen
- OS : Windows 10 64 bit
- Data used :
  - Exposure : Building in each hazard area
  - Hazard : All Hazard (Flood Jakarta, Merapi Vulcano, Nagekeo Earthquake, Maumere Tsunami)
  - Aggregation : -

**Comment by ismailsunni** [comment]
Hi @harrymahar 
Can you paste here the trace back to make sure that I can get the same error message?

**Comment by harrymahar** [comment]
Hi @ismailsunni , I have update the issues. Please take a look. Thankyou

**Comment by felix-yew** [comment]
Hi @harrymahar, mas @ismailsunni , @Gustry 

I try to run in tsunami raster vs buildings also get an AttributeError.
![image](https://cloud.githubusercontent.com/assets/13621886/18075220/0e0d5f78-6e9d-11e6-896f-915998a33467.png)

```
Problem
The following problem(s) were encountered whilst running the analysis.
AttributeError

Suggestion
You can try the following to resolve the issue:

- Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
- Check the InaSAFE documentation to see if you are trying to do something unsupported.
- Report the problem using the issue tracker at https://github.com/inasafe/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
- Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.

Details
These additional details were reported when the problem occurred.

- Error loading impact layer.
- 'NoneType' object has no attribute 'get_json_data'

Diagnostics

1. In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\utilities\analysis_handler.py", line 378, in completed report = self.show_results()
2. In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\utilities\analysis_handler.py", line 426, in show_results postprocessor_data = self.impact_function.postprocessor_manager.\

```

Make it happy :smile:

**Comment by Gustry** [comment]
We made a big refactoring in version 4.0. I'm closing this issue as we are not using JSON or the postprocessor manager.
