### ISSUE TITLE
[Bug] Analysis Area with bounding box is not working in IFCW

### ISSUE THREAD

**Issue by dewisulistio** [inasafe/inasafe#3172]
### Problem

While we used function "specify extent the analysis" in IFCW to run Flood Jakarta IF (vector and raster) and Population Java; Flood Jakarta and Buildings; Flood Jakarta and Roads, we choose the bounding box and drag on map the area analysis. Then the InaSAFE results, analysis area not same with bounding box. The analysis area automatic change in accordance with the current view extent. 

The bug process IFCW in Flood Jakarta 2013

![ifcw current map extent area error 1](https://cloud.githubusercontent.com/assets/2524177/18042039/65bd0df0-6de8-11e6-8993-c07177e9c1bc.gif) 
### Expected Behaviour

The result should be shows analysis area same with bounding box
### Environment
- InaSAFE : 3.5.0 dev
- QGIS : 2.14.3 in English language
- OS : Windows 7 64 bit 12GB RAM
- Data used : 
  - Exposure : Population Java, Roads Jakarta, Buildings Jakarta 
  - Hazard : Flood Jakarta in 2013.shp (vector)
  - Aggregation : Districts Jakarta

**Comment by adissadis** [comment]
This bug also appear in all hazard for InaSAFE Bahasa Indonesian version

**Comment by timlinux** [comment]
This is fixed in v4 right @ismailsunni ? Can you test and validate @dewisulistio ?

**Comment by ismailsunni** [comment]
It was fixed, but somehow it's broken again. See #3741

**Comment by Gustry** [comment]
#3741 is fixed so let's close this one @ismailsunni
