### ISSUE TITLE
Detailed minimum needs show no result for Flood analysis with population (Bahasa Indonesia)

### ISSUE THREAD

**Issue by adissadis** [inasafe/inasafe#3173]
### Problem

When i run InaSAFE for flood raster with population raster analysis using Bahasa Indonesia i didn't get detailed minimum needs even tough i already using  aggregation data. It said "minimum needs report empty"

![image](https://cloud.githubusercontent.com/assets/2520159/18042767/848429ee-6ded-11e6-9f67-156375d4bcdb.png)

![raster-population 1](https://cloud.githubusercontent.com/assets/2520159/18042744/51dd6e6a-6ded-11e6-86b9-adba9f8df049.gif)
### Expected Behaviour

I get the detailed minimum needs when i run flood analysis with aggregation data
### Environment
- InaSAFE : 3.5.1
- QGIS : 2.14.5
- OS : Windows 10 64bit
- Data used :
  - Exposure : Java Population
  - Hazard : Flood HKV 2007
  - Aggregation : kotamadya_jakarta
## Step to produce the problem
1. Open QGIS in Bahasa Indonesia
2. Load flood hazard (raster), population (raster) and boundary (vector) in QGIS
3. Run InaSAFE Analysis using aggregation data
4. Then you will get in the result that there are no detailed statistic

Link for data:
https://drive.google.com/file/d/0Bxk-3mw_fhapNjhfdng1NzNOSlU/view?usp=sharing

**Comment by felix-yew** [comment]
Hi mas @adissadis 

I try to run the same data but in an English version. It can work properly and the result like this :
![image](https://cloud.githubusercontent.com/assets/13621886/18114558/2a38f2c8-6f62-11e6-98a4-f2caa7a37da9.png)
The detailed of a minimum needs report are successfully analyzed.

**Comment by adissadis** [comment]
@felix-yew yes this bug apparently appear only in Bahasa Indonesia

**Comment by Gustry** [comment]
Stange. This analysis is working well with English and French, but not Bahasa Indonesia.
I know there is some string comparaison in this postprocessing. This is might the problem.

**Comment by Gustry** [comment]
I'm going to close this issue. We made a big refactor in minimum needs.
