### ISSUE TITLE
Is Building threshold in post processing removed? 

### ISSUE THREAD

**Issue by adissadis** [inasafe/inasafe#3174]
### Problem
When I run any analysis against building, i just noticed that Building threshold in Impact Function Options is missing. 

![inasafe_post_processing](https://cloud.githubusercontent.com/assets/2520159/18043449/20f5d71a-6df2-11e6-93ca-5ef6cef3f59b.jpg)

Previously in InaSAFE 3.4.0 or 3.4.2, the post processing for building threshold  was there:
![inasafe_post_processing2](https://cloud.githubusercontent.com/assets/2520159/18043490/5bbf086c-6df2-11e6-86a3-b30723275fe8.png)

Looking at current version of InaSAFE is post processing for building was removed on purpose?

I knew that the purpose of threshold is for buildings attribute that below default threshold (25 features) are count as Other category. And give the option to the User to set their threshold is good if they analyze the small area.

### Expected Behaviour
If possible, could you enable again the post processing for building (especially for give the threshold) in current version of InaSAFE?

### Environment
* InaSAFE : 3.5.2
* QGIS : 2.14.5
* OS : Windows 10 64bit

**Comment by Gustry** [comment]
Yes, the building threshold has been removed in 3.5 according to a discussion with @timlinux and @Charlotte-Morgan .
This parameter was in conflict with the new value mapping for buildings in the keywords.

**Comment by adissadis** [comment]
Okay thank you @Gustry for explanation. I just wondering why is disappear in InaSAFE 3.5. I will close this issue. Thanks!
