### ISSUE TITLE
[Bug] Some Holes in Volcanic Ash Population Impact Scenario Result

### ISSUE THREAD

**Issue by harrymahar** [inasafe/inasafe#3175]
### Problem

When I run Volcanic Ash Impact Scenario for population and **using Aggregation Layer**, It works and InaSAFE show me the result. However, when I re-check the result, I saw some holes in the result layer despite those holes overlay with the hazard and the aggregation layer. Then, I re-run the scenario but without using aggregation layer and the result layer shows good result and all affected people in hazard area was counted.

![volcanicash_error](https://cloud.githubusercontent.com/assets/2534179/18043638/5ce169f0-6df3-11e6-8006-d37084f8a9f9.gif)
### Expected Behaviour

There is should be no holes in the result layer and make sure all affected people in hazard area being counted.
### Environment
- InaSAFE :  3.5.0.dev-master
- QGIS : 2.14.3 Essen
- OS : Windows 10 64 bit
- Data used :
  - Exposure : Sinabung_Population
  - Hazard : Sinabung_Volcanic_Ash_1Feb14_WGS84
  - Aggregation : Sinabung_Subdistrict_Administrative_WGS84

All the data used can be downloaded here https://drive.google.com/open?id=0B8iB2AhP6hn7RFpTTE0xam5xcWM

**Comment by Gustry** [comment]
Please try again with InaSAFE v4. I made a big refactor to impact functions. I'm going to close this issue. Feel free to open a ticket. Thanks.
