### ISSUE TITLE
Realtime : Zero Affected People on Flooded Area

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#3176]
### Problem
There are no affected people on flooded area in Flood Realtime.
http://realtime.inasafe.org/media/reports/flood/pdf/impact-map-en_lJtxCAk.pdf
![image](https://cloud.githubusercontent.com/assets/8871958/18046565/ad806406-6e02-11e6-99b3-5379a20bfb4c.png)

Whereas, when I try to download the data from https://rem.petajakarta.org/banjir/data/api/v2/rem/flooded (data attached in [here](https://www.dropbox.com/s/9kbqsrqcpyg6cqo/Jakarta%20Flood.zip?dl=0), then analyzed in InaSAFE desktop application, show the number of people affected
![image](https://cloud.githubusercontent.com/assets/8871958/18047107/4f4685fc-6e05-11e6-8ba3-ca34f08db3fc.png)

### Expected Behaviour
The maps that generated from flood real-time should show the number of people affected by flooded area.

### Environment
* InaSAFE : Realtime

### Proposed Solution
Make it happy

cc : @timlinux @Charlotte-Morgan @lrpower @lucernae @ivanbusthomi

**Comment by samnawi** [comment]
Hi @lucernae Whether the problem already fixed?
![image](https://cloud.githubusercontent.com/assets/8871958/18621144/7e77ae1a-7e49-11e6-84ca-84d122a6f4dc.png)

**Comment by lucernae** [comment]
@samnawi yes I updated QGIS again on the server and it is working. But we haven't got any new flood after that.

**Comment by samnawi** [comment]
Hi @lucernae I think it's already fixed.
