### ISSUE TITLE
We need to support additional exposure keywords for 4.0

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3177]
### Problem

In the new architecture we will support reporting on additional attributes if present:
- population (e.g. for people in buildings)
- cost (unit price e.g. for buildings)
- rate (price per m2 e.g. for buildings or landcover)
- currency abbreviation

We will use these new attributes with the post-processor architecture in 4.0 to support DALA and People in Buildings. Exposure layers without these attributes set should continue to function normally.

![screen shot 2016-09-01 at 10 03 27 am](https://cloud.githubusercontent.com/assets/178003/18159968/5d143bde-702b-11e6-97be-b9826620bf24.jpg)
### Environment
- InaSAFE : 
- QGIS : 
- OS : 
- Data used :
  - Exposure : 
  - Hazard : 
  - Aggregation :

**Comment by ismailsunni** [comment]
@timlinux can we close this? We already have `inasafe_fields` or/and `inasafe_default_values` to store this kind of number. E.g. land cover productivity is using it. For the other use case, we just need to add it to the field definition, but the keyword is already there.

**Comment by ismailsunni** [comment]
I think we have already finsihed this.
