### ISSUE TITLE
We need a function to reproject a layer to exposure CRS

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3183]
### Problem

In 4.0, we want to reproject the hazard and aggregation to exposure CRS.

<img width="720" alt="screen shot 2016-09-01 at 16 16 03" src="https://cloud.githubusercontent.com/assets/1421861/18162242/a707a648-705f-11e6-81cd-e2f8ff750d7d.png">
### Environment
- InaSAFE : 
- QGIS : 
- OS : 
- Data used :
  - Exposure : 
  - Hazard : 
  - Aggregation :

**Comment by Gustry** [comment]
PR #3232 and #3218

**Comment by Gustry** [comment]
Done in the gis/vector package
