### ISSUE TITLE
Create a function to create a buffering layer from a point and line

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3185]
### Problem

Some hazard layer will be point (volcano) or line (cyclone). We need to create a buffer layer for these layer to create a polygon hazard layer. The buffer parameter should come from the IF Buffer Zone parameter. The parameter should be in OrderedDict to get the radius, hazard class name, and the ordering.

<img width="473" alt="screen shot 2016-09-01 at 16 26 43" src="https://cloud.githubusercontent.com/assets/1421861/18162641/6fde2398-7061-11e6-8e4b-e72772451a7c.png">

There two box:
1. The left one, we will get the buffer zone parameter from IF parameter
2. The right one, we are still working on it.

For a note, there will be a case in one layer, there are many volcanoes, and each volcano has different buffer zone parameter. We will deal with it later.
### Environment
- InaSAFE : 
- QGIS : 
- OS : 
- Data used :
  - Exposure : 
  - Hazard : 
  - Aggregation :

**Comment by Gustry** [comment]
How do we manage when the hazard layer is not in degrees ?
We can't create buffers if the layer is in degrees. If the exposure CRS is in meters I would like to reproject before before this step.
If the exposure CRS is in degrees too, should we use UTM ?

**Comment by Gustry** [comment]
For the projection, it's fixed by using UTM if the layer is in 4326.
The bottleneck would be if the hazard is in 4326 and the exposure in a local projection. Indeed, points are going to be reprojected to UTM, buffering in UTM, then back in 4326, and then reprojected to exposure CRS.

@ismailsunni and @timlinux Is it normal that #3178 is not present after the buffering on the right side of the screenshot (like on the left side) ?

**Comment by ismailsunni** [comment]
@Gustry I think it's not normal. We should add the same step also.

**Comment by timlinux** [comment]
Note that we changed this workflow in our walkthrough yesterday since we said that volcano points is the only possible hazard that is points needing buffering and that cyclone would be polygons

**Comment by timlinux** [comment]
See the updated part of this diagram below:

![screen shot 2016-09-27 at 10 57 20 am](https://cloud.githubusercontent.com/assets/178003/18866655/4110186a-84a1-11e6-88ff-85d03e734dca.png)

**Comment by Gustry** [comment]
Done in the gis/vector package
And we said we are going to put the hazard preparation outside of the IF
