### ISSUE TITLE
Create Minimum Needs Post Processor for New Impact Function

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3195]
### Problem

We need a minimum needs post processor for impact layer in the new impact function. Steps:
1. Check if the impact layer has `population` field to do the age post processor
2. Get `population` field from the impact layer by using the keyword
3. For each minimum need resource (e.g. rice, water, etc), create new field to put the total number of each minimum need 
4. Get the needs value from the minimum needs profile. 
5. Calculate the total minimum needs per feature for each minimum needs, and put the number on the field in step 3.

See image below
<img width="727" alt="screen shot 2016-09-01 at 22 10 20" src="https://cloud.githubusercontent.com/assets/1421861/18172761/0487a508-7091-11e6-8670-5bafdf7bee5b.png">
### Environment
- InaSAFE : 
- QGIS : 
- OS : 
- Data used :
  - Exposure : 
  - Hazard : 
  - Aggregation :

**Comment by ismailsunni** [comment]
Update:
We agree to implement this like the other post processor. Thus, we need to:

- [ ] Define field post processor based on the current default minimum needs (sphere, BNPB, Tanzania, etc)
- [ ] Create grouping mechanism for the minimum needs post processor. It will be the _profile_ of the minimum needs
- [ ] Add setting to check which post processor or group that will be run in the analysis
- [ ] Delete legacy minimum needs system

cc @timlinux @Gustry @Charlotte-Morgan @lucernae

**Comment by timlinux** [comment]
@ismailsunni that sounds good thanks!

**Comment by Gustry** [comment]
I think we can now close this one, or is there something we need to implement ? @ismailsunni @lucernae

**Comment by ismailsunni** [comment]
Not from my side. I think @lucernae took over this part. :) You are a good guy @lucernae

**Comment by lucernae** [comment]
@ismailsunni I remembered you were assigned on grouping postprocessor based on definitions, but not for 4.0 final :D.
Also, I checklisted what I think already done :). I think we can close this and move on.

>  Add setting to check which post processor or group that will be run in the analysis

For this, currently post processors runs based on its input definitions. I don't know if we still needs settings for this?

**Comment by ismailsunni** [comment]
@lucernae yes, but after the final :)
