### ISSUE TITLE
Create Value Based on ClassValue Post Processor for New Impact Function

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3199]
### Problem

We need a post processor to calculate how much is the value of a feature. One of the possibility is the value is calculated based on the feature type class. For example, post office is 30.000.000.000. The price is the same regardless the size. So, it only applies for indivisible polygon or point

Steps:
1. Get cost (value) per unit for each class from definitions.py (parameterised)
2. Create new impact layer field for feature value

![inasafe_new_if_class_value_postprocessor](https://cloud.githubusercontent.com/assets/1421861/18250968/a2d4f7b6-73b0-11e6-9fe8-55a080068360.png)

See also #3197 
### Environment
- InaSAFE : 
- QGIS : 
- OS : 
- Data used :
  - Exposure : 
  - Hazard : 
  - Aggregation :

**Comment by Gustry** [comment]
I'm going to close this one. We will comeback on Value/Rate in V4.2
