### ISSUE TITLE
Create Value Based on ClassRate Post Processor for New Impact Function

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3200]
### Problem

We need a post processor to calculate how much is the value of a feature. One of the possibility is the value is calculated based on the size of the feature for each feature type. For example, high road has the value 1.000.000 per meter, or post office is 3.000.000 per meter square.

Steps:
1. Get rate per m2 per class from definitions.py (parameterised)
2. Create new impact layer field for total value
3. Calculate the total value by multiplying class rate with the area in m2 or distance in m

See also #3197 

![inasafe_new_if_class_rate_postprocessor](https://cloud.githubusercontent.com/assets/1421861/18251073/2d6ba852-73b1-11e6-80e9-a0b19b0db2a7.png)
### Environment
- InaSAFE : 
- QGIS : 
- OS : 
- Data used :
  - Exposure : 
  - Hazard : 
  - Aggregation :

**Comment by Gustry** [comment]
I'm going to close this one. We will comeback on Value/Rate in V4.2
