### ISSUE TITLE
We should move the metadata.db and minimum needs into .qgis2/inasafe

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3214]
### Problem

The metadata sqlite DB is stored in `~/.inasafe/metadata.db`
The minimum needs are stored in `~/.qgis2/minimum_needs/`
### Expected Behaviour

InaSAFE should store all these files under : 
`.qgis2/inasafe/`
using
`QgsApplication.qgisSettingsDirPath()`

@ismailsunni Do you think that 4.0 will break (or partially break) all previous keywords (3.5) ?

**Comment by ismailsunni** [comment]
@Gustry I am still not sure. I will introduce some new keywords. The old keywords will not work in some of the new post processor architecture since we run the post processor based on this new introduced keywords.
I will try my best to have a migration seamless. With some extra functions

**Comment by Gustry** [comment]
For the metadata file, see PR https://github.com/inasafe/inasafe/pull/3431
For the minimum needs, we will wait for the minimum needs refactoring

**Comment by myarjunar** [comment]
closed in #3810
