### ISSUE TITLE
Website - update

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3226]
We need to announce the release of version 3.4 and 3.5

**Comment by timlinux** [comment]
Sorry I am not sure how those slipped through the cracks - I have added entries for them now:

![screen shot 2016-09-23 at 8 17 29 am](https://cloud.githubusercontent.com/assets/178003/18776013/4b7636e2-8166-11e6-9431-c24bb78d6e79.png)

**Comment by Charlotte-Morgan** [comment]
great thank you :)
