### ISSUE TITLE
Separate indicator monitoring to a different worker thread

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#3230]
### Problem

InaSAFE Realtime monitoring failed to send connection problem notification.
### Expected Behaviour

I got emailed when Realtime is not working.
### Proposed Solution

Maybe we need to separate worker for InaSAFE Django job and Indicator monitoring.
Or maybe we should try using celery as builtin linux service.

**Comment by timlinux** [comment]
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.
