### ISSUE TITLE
Clean Hazard, Exposure, and Aggregation Layer's Attribute

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3239]
### Problem

Before doing GIS process in InaSAFE, we need to remove unused attribute in input layer. The definition of unused attribute is the attributes that do not registered in the fields definitions.

We should do it in the begining so that we deal with smaller data since the begining.

We need to add this step in the diagram also.
### Environment
- InaSAFE : 
- QGIS : 
- OS : 
- Data used :
  - Exposure : 
  - Hazard : 
  - Aggregation :

**Comment by Gustry** [comment]
I started an processing step to remove and rename fields. I will be fine with that part.
But I think we will need to work together to know which fields are impacted.

**Comment by ismailsunni** [comment]
Perhaps we can rename also the fields which are needed by inasafe directly.

**Comment by Gustry** [comment]
yes of course, it was the deal. To remove useless fields and to rename fields into our concepts.

**Comment by Gustry** [comment]
See PR : https://github.com/inasafe/inasafe/pull/3250

**Comment by Gustry** [comment]
Done in the gis/vector/prepare_vector_layer.py
