### ISSUE TITLE
Setup Docker Sync for Processed Shakemaps

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#3256]
### Problem

BNPB wants to sync the processed shakemaps to their server.
Should contain the PDF and PNG files of processed shakemaps
### Proposed Solution

Just setup new btsync server which shared shakemaps-extracted folders (the folder that contain all processed shakemaps with its impact layer and products).

CC: @Charlotte-Morgan @timlinux

**Comment by timlinux** [comment]
Closing this in favour of the ticket in inasafe-realtime repo
