### ISSUE TITLE
Flood Realtime: map colours do not reflect hazard data source

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3261]
# problem

the colours on the flood realtime impact map are not the same as the colours on the landing page or on the petajakarta flood map
# proposed solution

the colours on the flood realtime map should be the same as the original hazard data classification.

These are the colours on the realtime report:
![image](https://cloud.githubusercontent.com/assets/5743135/19100810/4598be90-8aec-11e6-9133-fa51514bbe1d.png)

These are the colours that should be used to match the landing page and the source hazard data
![image](https://cloud.githubusercontent.com/assets/5743135/19100794/1bf6154c-8aec-11e6-8b31-37522829b898.png)

The max depth class label should read > 150

@ivanbusthomi @lucernae

**Comment by timlinux** [comment]
Closing this in favour of the ticket in inasafe-realtime repo
