### ISSUE TITLE
Flood Realtime: Jakarta boundary error

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3262]
# problem

there is an an error with the boundary of the Jakarta province shown on the maps.
Only the outline should be a bold line. Not the extra line as shown here:

![image](https://cloud.githubusercontent.com/assets/5743135/19100996/1ddaa222-8aee-11e6-9186-c4bdd0d43a75.png)

@ivanbusthomi - can you please check the error is not in the synced data. if it is, fix and update the synced data - thanks

**Comment by lucernae** [comment]
I think the data is ok since I used the same data for my local environment.
But it turns out to be ok.

<img width="820" alt="screen shot 2016-10-05 at 15 14 43" src="https://cloud.githubusercontent.com/assets/831865/19105857/7a807eb4-8b0e-11e6-8498-63b4b663948b.png">

**Comment by Charlotte-Morgan** [comment]
hmm - I am not sure then why it is not drawing correctly in realtime reports

**Comment by lucernae** [comment]
Yes, I'm also trying to look into it with the translation issue.
But I think data is not the problem.
Maybe qgis rendering on the server.

**Comment by lucernae** [comment]
Update on this:
It seems the server version keep generating the wrong boundary. I still have no idea why, I will keep looking.

**Comment by timlinux** [comment]
Closing this in favour of the ticket in inasafe-realtime repo
