### ISSUE TITLE
Composition Rendering is not consistent

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#3282]
### Problem

There were some inconsistencies of the report result generated from QGIS Composition despite they have the same docker environment.
### Expected Behaviour

Report generated reliably
### Environment

QGIS: 2.16.1 QGIS LTR
### Sample

Flood report:

Local environment:
[impact-map-en.pdf](https://github.com/inasafe/inasafe/files/519275/impact-map-en.pdf)
Production server:
[impact-map-en_TKoTM7f.pdf](https://github.com/inasafe/inasafe/files/519278/impact-map-en_TKoTM7f.pdf)

Difference:
- District border in production is truncated and missing.

Ash report:

Local environment:
[report.pdf](https://github.com/inasafe/inasafe/files/519290/report.pdf)
Staging server:
[report_VE9GjIQ-2.pdf](https://github.com/inasafe/inasafe/files/519294/report_VE9GjIQ-2.pdf)

Difference:
- Mountain symbol was not rendered

CC @timlinux

**Comment by timlinux** [comment]
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.
