### ISSUE TITLE
Realtime flood translation in Bahasa Indonesia

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#3291]
### Problem

We have a good real time monitoring [http://realtime.inasafe.org/] , but there are some problems if we want to see it in Bahasa Indonesia mode. When a new user going to open the real time and they just only know in Bahasa, they will always want to translate it, from English to Bahasa Indonesia. But, in a current release when I want to translate the real time into Bahasa is not translate yet. From the menu until the data flood query most of them not translate yet.
![image](https://cloud.githubusercontent.com/assets/13621886/19261098/227e2fcc-8fb9-11e6-91e5-ee3ac4f97752.png)

After I have checked the real time product, some content of the report is not translated well. And, some of the translation maybe need a fixing, ie in InaSAFE analysis result : Perkiraan IDP (penduduk) proper to Perkiraan pengungsi. See the image below :
![image](https://cloud.githubusercontent.com/assets/13621886/19261390/fa9ea9bc-8fba-11e6-82b0-4fea0d3c6498.png)
The part is in the translation report that proper to fix :
1. Flood identity number, ie : ID-20161007-06
2. Event time 
3. Administrative boundary --> #3262 
4. Flood depth legend
5. InaSAFE Analysis Result
6. Disclaimer
### Expected Behaviour

Front page in flood realtime and the report can translate well.
### Environment
- InaSAFE : 
- QGIS : 
- OS : 
- Data used :
  - Exposure : 
  - Hazard : 
  - Aggregation :
### Proposed Solution

The realtime and report flood can easy read in to Bahasa Indonesia.

**Comment by lucernae** [comment]
Thank's @ivanbusthomi .

For the clarity of the discussion, I just want to point out some things.

1. For all the text in the website, all the translation stuffs should go and can be found in [InaSAFE Django Repo](http://github.com/inasafe/inasafe-django). For fixing and updating translations in django, the workflow is somewhat different from the usual transifex translation we used in InaSAFE. Actually maybe we can use transifex too, but we need to spend more time on researching that first. I will explain about the process a little bit more later.

2. For all the text found in the pdf report (or png if there is). It is coming from this InaSAFE repo. So, the usual transifex workflow applies. We can just fix the translations in transifex and we can pull the translation and patch it on the translation PR.

3. For some text, we haven't found a way to easily translate it. For example, it could be in the JavaScript files (in the case of webpage for Query Data), for this we have to make a workaround or somehow make the JavaScript files i18n independent (a little bit too technical and some effort needed). In the case of pdf report, an example would be for the legend files QML files, this is also needed a workaround, but probably possible by using string replacing in the code. Just note that some part may not be able to be translated easily (or not available yet to be translated) and I need some additional steps to make it translateable.

# Web Translations

The files that are able to be translated is located in: [django.po](https://github.com/inasafe/inasafe-django/blob/develop/django_project/locale/id/LC_MESSAGES/django.po). If not, then I need to do additional steps to make it available on that files. But, generally all strings should be mentioned there. To update the translation, just issue a pull request on **translation** branch in inasafe-django.

**Comment by timlinux** [comment]
Closing this in favour of the ticket in inasafe-realtime repo
