### ISSUE TITLE
Minimum Needs report in InaSAFE report in Bahasa Indonesia

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#3294]
### Problem

We have problems when I have a try in a flood IF and tsunami IF, problems appear in the InaSAFE analysis report. Most of the words in minimum needs part not to translate into Bahasa Indonesia, only the toilet translate to "jamban" and family kits to "perlengkapan rumah tangga". See the image below :
![image](https://cloud.githubusercontent.com/assets/13621886/19266522/14d46466-8fd4-11e6-81e9-8cb48cfcf513.png)
### Expected Behaviour

The minimum needs in analysis result can translate into Bahasa Indonesia.
### Environment
- InaSAFE : 3.5.2
- QGIS : 2.14.3
- OS : WIndows 7
- Data used :
  - Exposure : 
  - Hazard : 
  - Aggregation :
### Proposed Solution

Make it happy :smile: 

Cc: @Charlotte-Morgan @timlinux @ismailsunni @ivanbusthomi @samnawi

**Comment by Gustry** [comment]
I guess you need to change your profile to the translated version.
And I made some changes to have some translations.
