### ISSUE TITLE
Realtime earthquake report for event outside population extent

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#3315]
### Problem

Right now realtime InaSAFE generates reports that are outside the population extent. It results in zero people affected in the analysis report.
This happened for example in event with shake ID 20161017132313
![20161017132313](https://cloud.githubusercontent.com/assets/7351977/19433045/514170f6-9489-11e6-8b90-83a01ca432d6.PNG)
### Expected Behaviour

It should show some additional information if the event is outside the exposure (population) extent, that describe why there is no result shown in the report.
### Environment
- InaSAFE : Realtime Earthquake
- QGIS : 
- OS : 
- Data used :
  - Exposure : 
  - Hazard : 
  - Aggregation :
### Proposed Solution

![proposed_solution](https://cloud.githubusercontent.com/assets/7351977/19433813/7b4bf44a-948c-11e6-92f6-1060efb64555.PNG)

**Comment by timlinux** [comment]
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.
