### ISSUE TITLE
InaSAFE Fields with Default Value

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3325]
### Problem

Currently some of InaSAFE fields can have default value. For example gender_ratio. If the aggregation doesn't have specific field that contains the gender_ratio, InaSAFE should help to generate the field with default value. By doing this, we can run post processor properly.
Another case is when the aggregation layer has the gender_ratio field, but some of the features are Null. In this case InaSAFE should help the user whether to fill the Null value with default value or leave as it is.
Furthermore, InaSAFE should be able to store the default value in the setting, store the currently used default value in QSettings, make user able to use another value beside from setting when assigning keyword.

From discussion, we expect this wireframe to accomodate the requirements:
![aggregation_fields](https://cloud.githubusercontent.com/assets/1421861/19543423/873a3340-96a1-11e6-9dfc-19034498a7df.png)

We will implement the wireframe as a custom parameter, by extending the parameter module.

In the metadata side, we need to store the default value for the layer. Currently, we put each of default value in one properties, e.g. `adult ratio attribute`. Since we expect to support more Default Value in the future easily, we will use the same approach as `inasafe_fields` (using dictionary in one metadata property). Finally, we introduce `inasafe_default_value`.

We will need to add functionalities when preparing the layers:
1. Replace Null value if there is default value
2. Create new field if there is no field chosen and there is default value.

cc @timlinux @mbernasocchi @Gustry

**Comment by ismailsunni** [comment]
4 Cases:
1. It does **not** have inasafe_field and it does **not** have inasafe_default_value --> Do nothing.
2. It **has** inasafe_field and it does **not** have inasafe_default_value --> Do nothing.
3. It does **not** have inasafe_field but it **has** inasafe_default_value --> Create new field, and fill with the default value for all features
4. 2. It **has** inasafe_field and it **has** inasafe_default_value --> Replace the null value with the default one.

for @Gustry

**Comment by Gustry** [comment]
Done

**Comment by Gustry** [comment]
I think we need to rollback on this feature. See ticket #3763

When we use a postprocessor, the priority should be :
1. Exposure count
2. Exposure ratio
3. Aggregation ratio
4. Defaults (ratio and count)

Or by doing these 4 cases above from @ismailsunni , we don't take care about the aggregation ratio.

**Comment by Gustry** [comment]
I think we need to rollback on this feature. See ticket #3763

When we use a postprocessor, the priority should be :
1. Exposure count
2. Exposure ratio
3. Aggregation ratio
4. Defaults (ratio and count)

Or by doing these 4 cases above from @ismailsunni , we don't take care about the aggregation ratio.

**Comment by Gustry** [comment]
See ticket above for future reference
