### ISSUE TITLE
Proposed workflows for Report Generator

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#3326]
- [x] package jinja2 into safe_extras (Apparently, jinja2 is provided by QGIS Lib)
- [x] create series of jinja2 templates or qpt to render svgs and templates
- [x] create series of data extractions algorithms for a given report styles
- [x] associate icons with each minimum needs

**Comment by timlinux** [comment]
Can we close this?

**Comment by lucernae** [comment]
We can close this.
