### ISSUE TITLE
Volcanic Ash Realtime : add KRB context data to impact map

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3338]
### Problem
Friends from PVMBG have requested that realtime ash reports include the KRB pyroclastic boundaries as context data
### Expected Behaviour
The boundaries will be shown as lines over the ash model.
the lines will be coloured but no fill
### Proposed Solution
The map should show the official data from PVMBG
@willi09 will share the KRB data and volcano point data when it is ready.

@ivan will add the data to the realtime data share and the map can be updated

# cc
@lucernae @timlinux 

This is not a blocker for the release of ash realtime

**Comment by ivan** [comment]
Please don't @ivan, this sends me an email

**Comment by Charlotte-Morgan** [comment]
duplicate issue
