### ISSUE TITLE
Flood Realtime : Minimum Needs provided for affected or IDP?

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#3342]
### Problem

The report of minimum needs in Flood realtime report seems like refers to the affected people, not refers to the  IDP.
![image](https://cloud.githubusercontent.com/assets/8871958/19636792/a1bbc574-99f5-11e6-9169-7dde95641ccc.png)

Which stuff that should be referred by the system to calculate the result?
### Expected Behaviour

As the feedback from BPBD DKI Jakarta, the minimum needs should be provided refers to the number of IDP.

If we refer to the InaSAFE desktop, it should refers to the number of IDP.
![image](https://cloud.githubusercontent.com/assets/8871958/19637050/2d94e26e-99f7-11e6-8708-3942ccfe2178.png)
### Environment
- InaSAFE : Flood Realtime
- QGIS : -
- OS : -
- Data used : Flood Realtime analysis data
  - Exposure : -
  - Hazard : -
  - Aggregation : -
### Proposed Solution

Make it happy.
### CC

@lucernae @timlinux @Charlotte-Morgan

**Comment by timlinux** [comment]
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.
