### ISSUE TITLE
Flood Realtime : New Address of the Contact

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#3343]
### Problem

BPBD DKI jakarta has move to the new office, so we must update the address of the contact in the report
### Expected Behaviour

Change the address in the contact to the new Address.

Pusat Pengendalian Operasi (Pusdalops)
BPBD Provinsi DKI Jakarta
Gedung Dinas Teknis Lt. 5
Jl. Abdul Muis No. 66, Telp. 121
### Environment
- InaSAFE : 
- QGIS : 
- OS : 
- Data used :
  - Exposure : 
  - Hazard : 
  - Aggregation :
### Proposed Solution

Make it Happy
### CC

@lucernae @timlinux @Charlotte-Morgan

**Comment by za** [comment]
PR #3357 has been created.

**Comment by samnawi** [comment]
Hi, 
The address is already changed to the newest, but it's truncated
![image](https://cloud.githubusercontent.com/assets/8871958/20085315/992beb04-a59a-11e6-848e-4031d086437e.png)

**Comment by za** [comment]
@samnawi A new PR has been created.

**Comment by timlinux** [comment]
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.
