### ISSUE TITLE
RFC : Icon to support population and minimum needs report

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#3366]
# Problem

In the InaSAFE latest version tag, we do not have an infographic reporting. I will propose the simple one infographic report about the population that represents in InaSAFE reporting table.
# Duration

December 2016
# Proposers

  @felix-yew with input from :
  @Charlotte-Morgan 
  @fredychandra
  @samnawi
  @ivanbusthomi
# Proposal

The reporting reference in #3206  and the icon reference in #3360 . The population report includes a gender, ages, and minimum needs, like in sketch below :
< Infographic title > **People affected**

< Total affected >
< icon > < percentage > < total > < short description >
![image](https://cloud.githubusercontent.com/assets/13621886/19801009/8962e0c2-9d27-11e6-8bee-2013da325cac.png)

< Gender report > 
< icon > < percentage > < total > < short description >
![image](https://cloud.githubusercontent.com/assets/13621886/19800050/1e52298a-9d24-11e6-8f2b-23d662ad6692.png)

< Age report > 
< icon > < percentage > < total > < short description >
![image](https://cloud.githubusercontent.com/assets/13621886/19800075/46297e22-9d24-11e6-9e8a-af926e03c83b.png)

< Minimum needs > 
< icon > < total > < short description >
![image](https://cloud.githubusercontent.com/assets/13621886/19800131/90bb1a22-9d24-11e6-885d-a96b4bd30a11.png)

< Action checklist > 
< icon > < checklist >
![image](https://cloud.githubusercontent.com/assets/13621886/19800256/2465ca4c-9d25-11e6-9bd0-668d3c79771b.png)

Source (file in SVG format) : 
[Population icon.zip](https://github.com/inasafe/inasafe/files/558004/Population.icon.zip)
[Minimum needs icon.zip](https://github.com/inasafe/inasafe/files/558005/Minimum.needs.icon.zip)

Make it happy :smile: 
# CC

@Charlotte-Morgan 
@timlinux 
@fredychandra 
@samnawi 
@ivanbusthomi 
@Gustry 
@lucernae 
@ismailsunni

**Comment by Charlotte-Morgan** [comment]
Hi @felix-yew - this looks nice. I think we might need to use different thousand separators for English and Indonesian versions so that English speakers are not confused. :)  Can you please also check that you are using the Ubuntu fonts?  If necessary, download and install them on your machine.

**Comment by felix-yew** [comment]
Hi @Charlotte-Morgan 

Thank you for your feedback, I will adapt the template, especially the thousand separators and the Ubuntu's font.

**Comment by felix-yew** [comment]
Hi @Charlotte-Morgan 
This is the template revised, a thousand separators and Ubuntu's font has been added.

<infographic title> **People affected**

< Total affected >
< icon > < percentage > < total > < short description >
![image](https://cloud.githubusercontent.com/assets/13621886/20049962/19a8b6ce-a4f9-11e6-9e56-499fafea332f.png)

<Gender> 
<icon> <percentage> <total> <short description>
![image](https://cloud.githubusercontent.com/assets/13621886/20049810/12f39a84-a4f8-11e6-8011-ba8b2b0f15e4.png)

<Age> 
<icon> <percentage> <total> <short description>
![image](https://cloud.githubusercontent.com/assets/13621886/20049830/290d7e70-a4f8-11e6-8381-c9a4dad6aeb1.png)

< Minimum needs > 
< icon > < total > < short description >
![image](https://cloud.githubusercontent.com/assets/13621886/20049833/36e44344-a4f8-11e6-8bb7-1d6d330fda9f.png)

< Action checklist > 
< icon > < checklist >
![image](https://cloud.githubusercontent.com/assets/13621886/20049842/4535a91a-a4f8-11e6-83c1-2a6100e3e3a2.png)

**Comment by Charlotte-Morgan** [comment]
@felix-yew - can you please put the final list of proposed icons with file names and where you got them in this ticket please so people can provide feedback on the suitability of the icons.
