### ISSUE TITLE
Hazard Layer Generation Tools

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3367]
### Problem

Currently, we have problem with volcano point layer that doesn't fit with our metadata/schema. The reason is volcano point is not a hazard layer. We can say it is a pre-hazard layer. We can generate a hazard layer from it, which is a volcano polygon layer. In this volcano point, we can't get the hazard value field or similar information.
The similar layer is flood line (or river). People create the buffer zone manually to get the flood polygon hazard layer. I knew it when I attended the training.

Thus, we need a tool to manage this pre-hazard layer, for example creating hazard area from volcano point or buffer zone for flood line (river).

In the first implementaion, we should support to create several hazard zone by the radius that the user input. While doing that, the tool also should assign the proper hazard metadata/keyword so that it will be ready to be used.

Wireframe for this tool:
![hazard_creation_tool](https://cloud.githubusercontent.com/assets/1421861/19802047/efc0fd64-9d2b-11e6-989e-10795d80929a.png)

Please give some feedback about this. @timlinux @Gustry @Charlotte-Morgan @lucernae @samnawi @ivanbusthomi @felix-yew @fredychandra

**Comment by timlinux** [comment]
@Charlotte-Morgan FYI we discussed this during our site visit and we feel that:

1) Doing volcano buffering in the middle of the workflow breaks the standard model of having your hazard data at the start of the work flow
2) We should rather make a collection of hazard preparation tools (like the shake importer) that do any hazard creation work and then let the user start their analysis with an already prepared hazard layer.

+1 from me to go this route.

**Comment by samnawi** [comment]
Hi @ismailsunni Is the generation tool will be included on the keyword (so the process will be on the fly) or as the separate tool?

I agree with @timlinux to collect the hazard preparation tools to produce some data that ready to use in InaSAFE. But, for the efficiency, can this process is put into the keyword wizard?

FYI.
As I know, from the last Code Sprint, people from PVMBG says that besides PVMBG produce the volcano hazard map based on the pyroclastic flow (like what we are usually using), they also produce the hazard map based on the distance from the peak. The geometry type of this hazard on polygon also.

**Comment by ismailsunni** [comment]
> Hi @ismailsunni Is the generation tool will be included on the keyword (so the process will be on the fly) or as the separate tool?


hi @samnawi 
I prefer to create it as separated tool, some reasons:
- The main function of the wizard is to assign keyword, while this tool will create a hazard layer. The function is different (although the tool will assign keyword also). Put two big functionalities in one tool will make it more complicated. E.g. We will need to ask special step for asking whether the layer is hazard layer or not hazard layer or the wizard will not generate anything but the tool will generate new layer
- In the other hand, we will need to ask the user also about several keyword also, so perhaps it will be better to put it in the wizard.

Discussion and comment are welcomed :)

**Comment by samnawi** [comment]
Hi @ismailsunni I just realized that the data that will be used should in polygon or raster.
I agree to create it as a separate tool.

As the discussion with @ivanbusthomi , the tools is like shakemap converter.
I think we must create some hazard preparation tools (we must investigate some possibly pre-hazard data type), and collect it in a group.

**Comment by Charlotte-Morgan** [comment]
+ 1 for separate tool

Please note: PVMBG may well supply zKRB data (not generated as buffers around a vent) as vector data in future.

Once we have this we may not need the buffer a volcano tool pre hazard data preparation tool..

**Comment by ivanbusthomi** [comment]
Hi @ismailsunni,
I also agree to make it like a collection of hazard preparation tool because it will make sense more to have a polygon buffer of volcano/river as hazard data than the volcano point/river line. Like how shakemap converter works, we just need to process the pre-hazard data once and use the result many times. It will also be great if we can assign the keyword in the process. CMIIW, considering the possible combination of keyword for Volcano Buffer, it is possible to assign the keyword.

@samnawi 
> we must investigate some possibly pre-hazard data type

+1 also for this suggestion.

**Comment by timlinux** [comment]
Just an update that we propose a more simple ui for this:

* Input layer:
* Buffer distances (m):
* Output layer:
* Help ...Cancel....Create

**Comment by timlinux** [comment]
Added note: After the user creates the buffer then can use the value mapping functions in the keywords wizard to map the class to the hazard classes.

**Comment by Charlotte-Morgan** [comment]
FYI - we hope to get data from PVMBG that will have vent location and buffer distances listed - ie we can make the data once and not have to do it again

**Comment by myarjunar** [comment]
![inasafe 4 0 0b0 hazard layer generator tool_006](https://cloud.githubusercontent.com/assets/11134669/22322601/bf0a3f06-e3cf-11e6-9c52-acade3bbc959.png)
Here is a screenshot of the tool dialog. Any feedbacks will help :smile:

**Comment by timlinux** [comment]
That is looking great @myarjunar. Some tweaks:

- [ ] Please change the title to 'Multiple buffer tool'
- [ ] New classification -> New buffer
- [ ] Reserved classification -> Hazard classes
- [ ] Also please use HIG (captilise only first letter of label text)

**Comment by myarjunar** [comment]
closed in https://github.com/inasafe/inasafe/pull/3708

**Comment by ismailsunni** [comment]
Thanks @myarjunar
