### ISSUE TITLE
Ratio VS count

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3372]
### Problem
The GIS workflow should manage ratio VS count in the attribute table.

### Expected Behaviour
InaSAFE should transform to count at the beginning and then transform again to ratio

**Comment by timlinux** [comment]
@Gustry can you update this ticket with the table showing how we propose to manage ratios?

**Comment by timlinux** [comment]
We are going to ship 4.0 without density support - will add it back in a future release.

**Comment by Gustry** [comment]
I'm closing this ticket. We manage ratios and counts if we have extra attributes.
For population with densities, we have ticket #3181
