### ISSUE TITLE
We need to fix dock keywords display in v4.0

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3373]
![screen shot 2016-10-31 at 9 42 40 am](https://cloud.githubusercontent.com/assets/178003/19842747/7239db16-9f4e-11e6-82ec-da41b1c3e438.png)

**Comment by Gustry** [comment]
I should also clean keywords along the workflow.
Some keywords are missing and some keywords are not relevant at the end of the process.

**Comment by ismailsunni** [comment]
I will review this while fixing my new keywords.

**Comment by Gustry** [comment]
If you want to have a look to this ticket : https://github.com/inasafe/inasafe/issues/2800
