### ISSUE TITLE
use renameAttributes if QGIS > 2.16

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3434]
### Problem
For now, we are copying a field and removing the old one so as to rename a field.

In QGIS 2.16, we can now rename an attribute : 
https://qgis.org/api/classQgsVectorDataProvider.html#ae1661cdfd4cc785e5b1bf5afa23b7f3d

We will earn some processing time.

**Comment by ismailsunni** [comment]
I found this also when we were starting working on new architecture, but only to realise for QGIS 2.16 :)

**Comment by timlinux** [comment]
@Gustry lets move this into the 4.1 milestone unless you have some concrete plans to implement it now (presumably with an ifdef based on QGIS version so that the old code path still works?
