### ISSUE TITLE
Report numbers need to be rounded 

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3454]
### Problem

![screen shot 2016-11-17 at 2 24 20 pm](https://cloud.githubusercontent.com/assets/178003/20389489/83f20540-acd2-11e6-9e93-48b9dd3b5dca.png)

### Expected Behaviour

Please consult #2920 and docs/standards.md and make sure distances and areas are rounded off nicely.

Also please include units after count column headers)

### Environment
* InaSAFE : 
* QGIS : 
* OS : 
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :

**Comment by Gustry** [comment]
Can you apply the rounding if the debug mode is off ?

**Comment by Gustry** [comment]
I think this is done now.
