### ISSUE TITLE
We need a sharing data test

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#3460]
### Problem
We always use the training data to share the problems we find in the analysis with InaSAFE. But, it is very wasting time if we also do to zipping the data training. And, sometimes the data that we use is very large.

### Expected Behaviour
We need a sharing of test data, maybe we can call it "Real World Data". We can make into the smallest area that comes from training data and share to another, then can test together with the same data. So, we don't have to upload and zipping the data again, just share the data test into the link.

### Environment
* InaSAFE : 4.0.0.dev-master
* QGIS : 2.14.7 Essen
* OS : Windows 7 Professional 64-bit, RAM 12 GB
* Data used :
  * Exposure : -
  * Hazard : -
  * Aggregation : -

### Proposed Solution
Make it happy :smile: 

###Cc :
@Charlotte-Morgan 
@timlinux 
@fredychandra 
@samnawi 
@ivanbusthomi 
@Gustry 
@ismailsunni 
@lucernae

**Comment by Charlotte-Morgan** [comment]
hi @felix-yew - this is a great idea. Why not make a btsync file with some real world data that Minions use for testing. We can then share data via the btsync with Kartoza team when we report bugs with real world data.

**Comment by ismailsunni** [comment]
+1

**Comment by felix-yew** [comment]
Hi, @Charlotte-Morgan - sounds good, OK I will make it.

**Comment by Charlotte-Morgan** [comment]
@felix-yew - can we close this ticket?

**Comment by felix-yew** [comment]
@Charlotte-Morgan - yes
