### ISSUE TITLE
Setting for Keyword Assignment

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3463]
### Problem
Currently, we have default value for some field (e.g. youth_ratio_field) and we have default value for it. We need a setting windows to set this value.

![inasafe_default_values_setting](https://cloud.githubusercontent.com/assets/1421861/20515377/eff5bed6-b0c3-11e6-96cf-37fdd9fbe72e.png)

This window will be put in the setting tab.

**Comment by Gustry** [comment]
Add a button `Restore to defaults` to restore these defaults user values by hard-coded values.

**Comment by Gustry** [comment]
And also, why not using QgsExpressionContextScope ?

**Comment by ismailsunni** [comment]
> Please, add a button Restore to defaults to restore these defaults user values by hard-coded values.

Added to the wireframe. Will do it.

> And also, why not using QgsExpressionContextScope ? Just thinking about that, I will have a look and come back.

Never use that before. What's the benefit of it compared to store it in QSettings for this use case?

**Comment by ismailsunni** [comment]
@myarjunar the only thing that we need to do is adding "Restore to default" button

**Comment by Gustry** [comment]
For the button, think about the QButtonBox Reset button

**Comment by myarjunar** [comment]
@ismailsunni @Gustry Reset or Restore Defaults button?? :smiley:

**Comment by Gustry** [comment]
Ahah, sorry I meant check the QButtonBox class, there is one role for this kind of purpose. I didn't want to mean use **this** one.

Let's use a RestoreDefaults

**Comment by ismailsunni** [comment]
Done in #3768
