### ISSUE TITLE
Show Question Button is Gone

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#3465]
### Problem
In the new InaSAFE developer version, after I run an analysis, the show question button disappeared.
It usually appears at the top of the InaSAFE dock. So, I cannot run the analysis again.
![image](https://cloud.githubusercontent.com/assets/8871958/20513574/57f5a754-b0b9-11e6-947c-300e95af9a38.png)

But, when I remove the resulting layer from the previous analysis, the guideline question appeared again.
![image](https://cloud.githubusercontent.com/assets/8871958/20513744/a4548d94-b0ba-11e6-8e27-96c9cb7f0ace.png)

### Expected Behaviour
Appear it again

### Environment
* InaSAFE : 4.0.0 dev-master
* QGIS : 2.14.7
* OS : Win 7 64 Bit

### Proposed Solution
Make it happen

CC : @Charlotte-Morgan @timlinux @ismailsunni

**Comment by Gustry** [comment]
Or if you don't want to remove your layer, you can just move one layer up or down in the tree. (disable the impacted layer).
But I agree, we should fix that.

**Comment by samnawi** [comment]
Ok @Gustry I can see the guideline question again.
But, I think it's not a best solution,hahaha....
I agree with you to fixed it.

**Comment by Gustry** [comment]
The button should be back in develop.
