### ISSUE TITLE
Earthquake Realtime filter not showing properly

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#3467]
### Problem
In earthquake realtime, the filter button for end date input is not showing properly.
![eqeqeq](https://cloud.githubusercontent.com/assets/7351977/20514898/22e3a9e6-b0c1-11e6-966d-002d04f9e0dd.PNG)

The input for start date is working fine like this screenie below
![eqeq](https://cloud.githubusercontent.com/assets/7351977/20514897/21bb72c4-b0c1-11e6-9539-9f6821c8a177.PNG)

### Expected Behaviour
Input button for filtering should be working properly

### Environment
* InaSAFE : Realtime Earthquake
* QGIS : 
* OS : 
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :

### Proposed Solution
Make it happy

**cc** : @lucernae @samnawi @Charlotte-Morgan @timlinux

**Comment by timlinux** [comment]
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.
