### ISSUE TITLE
Graphic Elements for Infographic Reports

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3472]
# problem
We want to make infographic reports in InaSAFE but we do not know what is possible.

# proposed solution
@felix-yew will make a template for a simple infographic report for population and minimum needs #3473
This template will use icons and graphic elements.
Icons will come from UNOCHA as svg files (to be uploaded and added to definition @charlotte)
Graphic elements are supplied here for testing:
* donut graph
* scalable icon
* proportional icon

# requirements for donut graphic
* must have between 2 and 5 slices
* colours of slices must match colours in impact map
* slices to include labels for % 

eg the colour version in this image
https://cloud.githubusercontent.com/assets/13621886/18384820/fedf5a66-76b6-11e6-96c4-8e9a06f238d0.png

# requirements for scalable icons
*  have fixed size for whole population
*  have standard proportional scaling for affected population
* be able to include labels
*  icons to be monochrome

eg
![image](https://cloud.githubusercontent.com/assets/13621886/20553339/7265bf7a-b186-11e6-92c9-3c9a14edcaff.png)

# requirements for proportional icon
* have an icon per unit of population
* change the icon colour to show the affected proportion of the population

eg

https://cloud.githubusercontent.com/assets/13621886/18385019/30cad680-76b8-11e6-9081-9bae6485af5c.png

# cc
@felix-yew @lucernae @timlinux @samnawi @mbernasocchi @ismailsunni @Gustry

**Comment by Charlotte-Morgan** [comment]
hi @lucernae  - this is the ticket with the proposed requirements for graphic elements. Once we have your advice on whether this is possible we can be more specific with the templates and ideas we prepare.

@timlinux  - FYI

**Comment by lucernae** [comment]
My feedback on this:

# requirements for donut graphic

* What happened if the slice is very small and the labels doesn't fit?
* Does it mean the percentage and labels is inside the slice (in the sample, it was outside). Labels in the outside might be difficult to implement if it doesn't have any rule.

# requirements for scalable icons

* have fixed size for whole population (can be implemented)
* have standard proportional scaling for affected population (can be implemented). Might note, what is the scaling direction? Does it shrink to the center, or to one of the corners (bottom right, for example).
* be able to include labels (can be implemented)
* icons to be monochrome. There is a little note. With SVG, it is possible to have one SVG and then style it to a different color (one svg for different shades of gray). However it has to be true SVG. The current one is in SVG format but png data inside. If it's not true SVG, you have to provide different color version.

# requirements for proportional icon

* what does one icon represent? 1% ? So, there should be 10 icon in total?
* we can change the color, but see notes above about monochrome. If it's not true SVG, you have to provide different icon for different shades of gray/color.

**Comment by lucernae** [comment]
ping @felix-yew for feedback.
Also, if we can't have SVG, could you clean up the PNG provided?

**Comment by timlinux** [comment]
@lucernae and @felix-yew please ping me on this too - I think @MariaSolovyeva also sent me some cleaned up SVG's which I need to share with you. @MariaSolovyeva could you send them directly to rizky@kartoza.com too? Thanks.

**Comment by Charlotte-Morgan** [comment]
Hi @lucernae - a few comments. Thanks for your inputs above.
For small slices is it possible to make these at the origin and horizontal to make it easier to put a label in?

Scalable icon - my thought would be to fix the bottom left and scale down so the icons remain bottom aligned. 

Proportional  icons we might expect the unit for each to change depending on the scale of the disaster;
eg if there are 1000 people displaced it might be 10 icon of 100 people each
if its 100,000 people affected we might not want each to represent 100 people

SVG - I thought i have supplied proper svg in C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe\resources\img\definitions 
if you still need more please let me know which ones and we can get them
