### ISSUE TITLE
We need to fix missing earthquake event in EQ Realtime

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#3479]
### Problem
Due to the connection problem with BNPB server, some shake events are missing from EQ realtime. Now that the connection is already fixed again, we need to add the missing event to realtime so that the report of the event can be seen and tracked for future purposes.

The missing event ID is:
* 20161116211705
16-Nop-2016 Jam 22:10:11 WIB
Magnitudo 6.2 SR, 127 km Tenggara KAB-MALANG-JATIM

### Expected Behaviour
EQ realtime displays all events that occur in Indonesia.

### Environment
* InaSAFE : Realtime
* QGIS : 
* OS : 
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :

### Proposed Solution
Add the missing shake ID to the realtime servers so that it can be processed and the report can be shown in both realtime and inaware.

___
**CC** @Charlotte-Morgan  @timlinux @samnawi @felix-yew @fredychandra

**Comment by timlinux** [comment]
@lucernae can you look into this and respond please?

**Comment by lucernae** [comment]
Sorry, it's done. I forgot to close this.
http://realtime.inasafe.org/realtime/?sorts[time]=-1&perPage=20&queries[search]=20161116221011
http://realtime.inasafe.org/media/reports/earthquake/pdf/20161116221011-en.pdf

No event with that ID, but I found correct shake with the same timestamp.

**Comment by timlinux** [comment]
Thanks @lucernae

**Comment by ivanbusthomi** [comment]
thanks mas @lucernae
