### ISSUE TITLE
IF Wizard does not complete

### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe#3482]
### Problem
When re-attempting the same analysis as #3481 fro the Wizard (and after changing the osm flood layer from generic to flood keywords), I get to the end of the wizard (choosing the aggregation layer) and hit next. All that happens is that the canvas is filled with another layer of blue each time I hit Next. 

### Expected Behaviour
Complete the Wizard and start the analysis. 

### Environment
* InaSAFE : 3.5.2
* QGIS : 2.14.7
* OS : Ubuntu 16.04
* Data used :
  * Exposure : osm buildings
  * Hazard : osm flood
  * Aggregation : Tanzania admin areas

**Comment by Gustry** [comment]
@gubuntu We made a big refactoring in InaSAFE V4. I don't think we can replicate. Feel free to open a new ticket.
