### ISSUE TITLE
Dock does not display selected impact layer results

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3487]
# Problem
The impact layer results in the dock do not reflect the results for the selected impact layer.

eg If an impact analysis eg area 1 is run the impact results are displayed correctly
If a subsequent impact analysis is run for area 2, the impact results are displayed in the dock.
If i then highlight / select the results for area 1 (previously saved as an impact layer.tiff) the results in the dock continue to show the results for area 2.

The error persists even if I remove the impact layer for area 2 and or close and reopen the dock.

# Scenario
Aceh earthquake raster - downloaded via shakemap converter
Aceh raster population
Aceh admin boundaries

# Expected behaviour
The results in the dock will be displayed for the active impact layer in the map window.

# Environment
QGIS 2.14.2
InaSAFE 3.5.2 tagged version
Windows 64bit

# cc
@timlinux

**Comment by Charlotte-Morgan** [comment]
Unable to replicate - possibly an issue with no space on drive. However, I'm pretty sure @fredychandra had this same issue on a different machine

**Comment by Charlotte-Morgan** [comment]
@fredychandra  - please confirm you have this problem. If not we can close this

**Comment by timlinux** [comment]
Just a note from me that I tried to replicate it with 3.5.3 but it behaves normally. I will stand by in case you figure out how to replicated it reliably.

**Comment by Charlotte-Morgan** [comment]
Further note on this. The issue also relates to trying to save and share the analysis results as data. If we right click on the layer and save in QGIS and then let the data load in the map, the JSON file is not saved. However, with the new layer in the map if we click on it we still see results of a different layer in the dock and assumed the results we see in the doc were from the saved results. Clearly user error, but maybe an easy error to make.  

Maybe  a ticket to QGIS to say please save json file as well when it does a save as

This can be closed.

FYI @fredychandra @ivanbusthomi @samnawi @felix-yew -  i think this is the mistake were were making last Friday

**Comment by timlinux** [comment]
Ah ok that makes sense. I think we should keep this open and patch the custom save as slot we have to make sure that it also copies over the JSON. @Gustry can you take care of that while you are refactoring the dock?

**Comment by Gustry** [comment]
Nice catch ! Yes we can use the signal. But I'm wondering if we keep the JSON file for inasafe v4 ?

**Comment by Gustry** [comment]
This has been fixed. We now save the JSON file
