### ISSUE TITLE
Please btsync share shakemaps-extracted for realtime

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3492]
## Data Sync

We currently sync the grid inputs but I would like to have a synced folder of the 

* PDF reports generated (I thought we already have a btsync share for this)
* the shakemaps-extracted folder - so that we can also have the derivative products.

Currently if someone asks for the extracted products we dont have a smooth way to provide them and also if we spin up a new server instance, it would be good to restore the historical outputs seamlessly.

Note that currently shakemaps-extracted is 47GB so people syncing it should be aware of that.

```
timlinux@inasafe-docker:/home/data/docker-realtime-orchestration⟫ du -sh shakemaps-extracted/
47G     shakemaps-extracted/
```

## Data access by web front end

Additionally I would also like to see a download link on the realtime site that will let you download the derivative products on an event by event basis.

### Expected Behaviour

* We should have a shared RO key for anyone who wants to subscribe to these products
* The RW key should be part of the server config and used only by production server(s)

# CC 

@Charlotte-Morgan

**Comment by Charlotte-Morgan** [comment]
sounds good - I definitely think we would like to make the MMI contours available and the named places.
I checked with @samnawi that named places are actual places and not polygon centroids - so I think this is ok.
@dynaryu @RikkiWeber - please advise if there are any issues with sharing the MMI contours generated in the InaSAFE realtime analysis

**Comment by timlinux** [comment]
OK thanks - we will await any feedback from @dynaryu and @RikkiWeber and then go for it...

**Comment by timlinux** [comment]
Closing this in favour of the ticket in inasafe-realtime repo
