### ISSUE TITLE
z-order in realtime quake report seems incorrect

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3493]
### Problem

It looks like the MMI contours in our EQ realtime report are being obscured by land / population data:

From event 20161207050336:

![screen shot 2016-12-13 at 11 32 34 pm](https://cloud.githubusercontent.com/assets/178003/21160220/b1ff6d8c-c18c-11e6-9688-2b2019acb171.png)

Loading the same data in QGIS:

![screen shot 2016-12-13 at 11 32 20 pm](https://cloud.githubusercontent.com/assets/178003/21160227/ba351f10-c18c-11e6-9921-965ec7176524.png)

[20161207050336-en.pdf](https://github.com/inasafe/inasafe/files/650214/20161207050336-en.pdf)

### Expected Behaviour

Contours should draw over the top of land.

### Proposed Solution

@lucernae and @ivanbusthomi check the template and generated project and fix please.

### CC

@Charlotte-Morgan

**Comment by Charlotte-Morgan** [comment]
+1 to fix this - good catch thanks @timlinux

**Comment by timlinux** [comment]
Closing this in favour of the ticket in inasafe-realtime repo
