### ISSUE TITLE
Rounding: EQ raster analysis on population report

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3496]
# problem
The earthquake raster on population raster analysis report results are not rounded. This may lead InaSAFE users to think that the results are more accurate than the modelled estimate intends.
These reports also include estimates of fatalities.

# proposed solution
The earthquake raster on pop raster reports should have the same rounding applied as in all other InaSAFE on population analysis reports
The way estimates of fatalities are reported should be the same as the EQ Realtime reports or something similar. A range is preferable to a specific number even if rounded:
If 0 - 49 then show < 50
If 50 - 100 then show 0 - 100

This advice is based on discussion with EQ experts at GA

# cc
@timlinux @cchristelis @RikkiWeber @dynaryu @griffij @Gustry @lucernae

**Comment by Gustry** [comment]
This ticket has been superseded in https://github.com/inasafe/inasafe/issues/3666#issuecomment-283565297
@lucernae made a PR #3982
