### ISSUE TITLE
Default IF: EQ raster on population raster

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3497]
# problem
There are 3 EQ raster on raster population impact functions. The default is currently set as the ITB Fatality model. This is not the recommended model for the estimation of impact on people (ie fatalities and displacement).

# proposed solution
Following discussion with EQ experts at GA, we propose that the default IF be set as the ITB Bayesian Model

# cc
@RikkiWeber @dynaryu @griffij @ismailsunni @timlinux @Gustry @lucernae

**Comment by Gustry** [comment]
This has been fixed in master 3.5 and in develop 4.0

**Comment by timlinux** [comment]
Thanks @Gustry
