### ISSUE TITLE
Option for All Feature has the Same Hazard Level

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3506]
### Problem
From @vdeparday and @timlinux 's email:

> File a ticket for not needing field for wet (assume all polygons are wet)

Sample case: A user has a flood layer, but there is no field that indicate the level or the hazard level. He/she knows that all polygons (features) have the same hazard level, which is wet.

### Proposed solution
I suggest we put this feature in the future hazard generation tool (see: #3367). My reason is:
- The layer doesn't have hazard field, which means the layer is not a valid hazard layer. So, we need to create a hazard layer first from it. Just like we will do for volcano point layer. From this hazard generation tool, we can add new field to store the prefered hazard value. E.g. all wet.

Comment are welcomed

cc @Gustry @Charlotte-Morgan

**Comment by timlinux** [comment]
I'm not sure writing a whole tool to add 'wet' column to a polygons layer is justified. We can just as well explain how to use the field calculator. Lets park this for 4.1 for now.

**Comment by Charlotte-Morgan** [comment]
Agree - I think v 4 will run well with this data if it is value mapped

**Comment by ismailsunni** [comment]
What if the hazard field doesn't have field that represent the hazard class / level / depth ?

**Comment by Gustry** [comment]
> What if the hazard field doesn't have field that represent the hazard class / level / depth ?

What if the hazard *layer* doesn't have field that represent the hazard class / level / depth ?
I agree with the question from @ismailsunni. We can't do value mapping.

**Comment by timlinux** [comment]
But you can just use field calculator and create a new field 'wet' that you assign to each polygon. Then use Flood Classes on the layer when setting keywords.

**Comment by Gustry** [comment]
Yes of course. It's just not out-of-box as we usually do with inasafe.

**Comment by ismailsunni** [comment]
IMHO, it's easier to tell / teach the user to use field calculator rather than creating new tool (which is the same function as field calculator).
- If the user has already known the field calculator, it's great. No need to teach anything.
- If the user doesn't know the field calculator, it's better for them to able to use field calculator.

CMIIW, but field calculator is very common tools for common user, compared to poligonize or other tools that we embed in InaSAFE Impact Function.

So, I agree to close this ticket and tell the user to use field calculator. It will give the user more understanding about how field work in InaSAFE.
