### ISSUE TITLE
Some cosmetics on the default values window

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3538]
### Problem
![screen shot 2017-01-05 at 18 16 14](https://cloud.githubusercontent.com/assets/1609292/21690175/6628e598-d373-11e6-987e-c67a99770aaa.png)

* [x] Items are not ordered. Adult, Elderly and Youth are at the top. Youth is at the bottom.
* [ ] The UI with the sentence just after each item is misleading. I often think the text is a title for the next item but it's not. The text explains the item before. I think we can drop it.
* [x] Replace `mˆ2` per `²`.
* [ ] It could be nice to not be able to set elderly, adult and youth to one and check if the total is equal to 1.

**Comment by Gustry** [comment]
@ismailsunni I think you fixed some of these issues, right ?

**Comment by ismailsunni** [comment]
Hmm, I don't think so @Gustry . I was mostly working on the wizard lately. I just change some text and fix the typo in `eldery`

**Comment by ismailsunni** [comment]
Second point will be addressed in #4029 
4th point will be addressed in #4015 

I am closing this ticket then.
