### ISSUE TITLE
KW wizard threshold step wrong behavior when classes are higher than the max value in data 

### ISSUE THREAD

**Issue by mbernasocchi** [inasafe/inasafe#3540]
### Problem
when classes thresholds are higher than the max value in the data, all the thresholds are set to the max value from the data. This results in an incomprehensible dialog where the user does not know in which class the max value will land.
![blob](https://cloud.githubusercontent.com/assets/233663/21715960/b8354c16-d407-11e6-8702-0aaf65d897c9.png)

### Expected Behaviour
the classes thresholds should stay as defined in the hazard classification
### Environment
* InaSAFE : 4
* QGIS : 2.14
* OS : ubuntu 16.10
* Data used :
[tcrm.zip](https://github.com/inasafe/inasafe/files/689702/tcrm.zip)
  * Exposure : 
  * Hazard : vmax
  * Aggregation :

### Proposed Solution
let the classes min/max as defined in the classification

**Comment by ismailsunni** [comment]
Fixed.
