### ISSUE TITLE
Percentage of evacuated people is missing in V4

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3553]
### Problem

In InaSAFE 3, we had the number of people who need evacuation based on a percentage.
This feature is missing in the V4.

**Comment by Gustry** [comment]
@lucernae added `displaced_rates` in each hazard classification.
The thing is that the user can't update this value for now as it's hard coded in definitions.

**Comment by timlinux** [comment]
For me it is ok to hard code the displacement rates for v4.0. I think we must just make sure they are clearly documented in definitions help so that if users want to understand what displacement rates were used they can easily access that information.

**Comment by Gustry** [comment]
I think we can close this issue.
 Displacement rate has been implemented.
