### ISSUE TITLE
Support Exposure Spesific Hazard Classification

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3560]
### Problem
Currently we use the same classification for all exposure layer in the analysis. In fact, 1 meter flood has higher level hazard to population than structure.

### Expected Behaviour
We need to support exposure specifit hazard classification (including value mapping for classified hazard and threshold mapping for continuous hazard layer).

### Proposed Solution
To support this feature we need to do several things:
- [x]  Add support to store multiple hazard classification in hazard layer metadata #3563 
- [x] Update Keyword wizard to assign multiple hazard classifcation (including value map and threshold). #3561
- [ ] Add option in dock to run an analysis with custom hazard classifcation (and assigning temporary value map and threshold) for running the analysis
- [ ] Add step in impact function centric wizard to run an analysis with custom hazard classifcation (and assigning temporary value map and threshold) for running the analysis

I will use this ticket as ticket master and put each to do list above in smaller ticket.

cc @Charlotte-Morgan @timlinux @Gustry @lucernae

**Comment by ismailsunni** [comment]
cc @samnawi and @felix-yew and @ivanbusthomi

**Comment by ismailsunni** [comment]
I have done the first 2 items in the list. The other 2 are for the next InaSAFE as it's optional for now. 
I will remove Release Blocker label and move to the milestones .

**Comment by timlinux** [comment]
I think we should park the last two items here and implement if there is a specific need for this functionality.
