### ISSUE TITLE
Update Keyword wizard to assign multiple hazard classifcation

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3561]
### Problem
See #3560 

### Proposed Solution
In the keywords wizard for hazard layer, we need a step to assign classification for each exposure layer, and then set the threshold or value mapping. Based on discussion with @timlinux , we come out with this wireframe:

![wizard_multiple_hazard_classifications](https://cloud.githubusercontent.com/assets/1421861/21804117/d9eb1dee-d75f-11e6-8173-36292c543ec5.png)

In the first new step, we will ask the user to choose which hazard classification for each exposure in the left panel. Meanwhile on the right panel will show the value mapping or threshold mapping for the current chosen classifications.

There are also edit button next to each combo box / drop down to choose hazard classification. This button will allow the user to edit the threshold or the value mapping of the hazard classifications.

If it's a classified hazard layer, after the user click the edit button, he will see the second wireframe above. The right panel will show the value mapping (like the current wizard).

If it's a continuous hazard layer, it will show the threshold mapping like in the current wizard.

Both of them have 3 buttons:
- Load Defaults: Set the value of the threshold / value mapping to the default one
- Cancel: Abort the edit and back to the first wireframe
- Save: Save the edit, and back to the first wireframe.

While editing, the next button, combobox and the other edit button will be disabled.

By doing this, we will also remove the old choose classification, threshold and value mapping step for hazard from the Keyword Wizard. 

cc @Charlotte-Morgan @Gustry @lucernae

**Comment by timlinux** [comment]
Note that we will assume that the same field is used for all thresholds.

**Comment by ismailsunni** [comment]
cc @samnawi and @felix-yew and @ivanbusthomi

**Comment by ismailsunni** [comment]
Done in #3767
