### ISSUE TITLE
Error Message on Population Ratio with Aggregation Ratio

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#3570]
### Problem
Currently, we can set up the ratio or count field for female, youth, adult, and elderly in both of population vector keyword and aggregation keyword to enrich the report.

![image](https://cloud.githubusercontent.com/assets/8871958/21842692/82a80e00-d81a-11e6-8c7a-0b3c8ac8de31.png)

But, when I try to run the analysis using population that already set the ratio and aggregation that already set to the ratio too, I got some error message.

![image](https://cloud.githubusercontent.com/assets/8871958/21843474/ab8ea7d6-d81d-11e6-9120-d6d572522aff.png)

When I try to check the debug, I got the different error message
![image](https://cloud.githubusercontent.com/assets/8871958/21843524/de510b32-d81d-11e6-8064-daef483899c9.png)

### Expected Behaviour
When I run this kind of the data (population and aggregation), but with the different setting (for ratio or count). The analysist is fine and we get the result. See the table for detail
![image](https://cloud.githubusercontent.com/assets/8871958/21843766/bf22dd34-d81e-11e6-9d10-b622d673ba03.png)

### Environment
* InaSAFE : Develop
* QGIS : 2.14.10
* OS : Windows 7 64 bit
* Data used :
  * Exposure : Population vector
  * Hazard : Tsunami raster and volcano vector (maybe also for the other....)
  * Aggregation : Administration boundary

### Proposed Solution
Make it happy

cc : @Charlotte-Morgan @timlinux @Gustry @ismailsunni

**Comment by Gustry** [comment]
This ticket is also related to #3763

**Comment by Gustry** [comment]
@samnawi Can you try again your expected behaviour ?
![image](https://cloud.githubusercontent.com/assets/8871958/21843766/bf22dd34-d81e-11e6-9d10-b622d673ba03.png)

We made some fix in develop. Ratios and counts should work now. If you get another exception, please open another ticket.

**Comment by samnawi** [comment]
OK @Gustry I'll try it again

**Comment by samnawi** [comment]
Hi @Gustry Since there are some changing in the keyword wizard, the expectation behavior on the table was not relevant again. 
I just focus on the 2 last line
![image](https://cloud.githubusercontent.com/assets/8871958/22874396/57b5692a-f1f8-11e6-8759-6b9f7e313f0b.png)

Yes.... It's already work

**Comment by Gustry** [comment]
Yes I agree, we updated the wizard.

So I'm going to close this issue.
