### ISSUE TITLE
We need to update map report for version 4

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#3572]
### Problem
Currently, our map report does not contain data source and spatial reference. This information may help users to better understand the context of the event and how the analysis is prepared in the background.
This is the link to the reporting standard for reference 
https://github.com/inasafe/inasafe/blob/develop/docs/reporting-standards.md

### Expected Behaviour
Map report should display information that is available and useful to users.

### Environment
* InaSAFE : 
* QGIS : 
* OS : 
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :

### Proposed Solution
We should update the template for the version 4 release.

___
**CC** : @timlinux @lucernae @Charlotte-Morgan

**Comment by ivanbusthomi** [comment]
I have created some template that contains additional information and some other few changes. The template that I update are the size A4-blue portrait and landscape template. It should be easily adapted to the A3 size
* this is the portrait
![a4_portrait_v2](https://cloud.githubusercontent.com/assets/7351977/21874093/6fef120a-d8a5-11e6-883a-0662e428d8f7.png)

* this is the landscape
![a4_landscape_v2](https://cloud.githubusercontent.com/assets/7351977/21874101/75b6dc4a-d8a5-11e6-97ab-23fc8aa2b255.png)

**Comment by ivanbusthomi** [comment]
These are some changes that I proposed:
* update legend information according to the reporting standard
![image](https://cloud.githubusercontent.com/assets/7351977/21874323/f1756ff8-d8a6-11e6-9004-91c67946cd6d.png)

* Additional information in the analysis information
![image](https://cloud.githubusercontent.com/assets/7351977/21874442/8048dcf6-d8a7-11e6-8890-a3638c50f25e.png)

* a few changes in the map
![image](https://cloud.githubusercontent.com/assets/7351977/21874556/2f452d86-d8a8-11e6-808a-713ca0860882.png)

* InaSAFE supporter logo update
![image](https://cloud.githubusercontent.com/assets/7351977/21874590/69425fe0-d8a8-11e6-8a24-ca0a4a6da8a0.png)

**Comment by lucernae** [comment]
* What is the rounding rule when it is not a population exposure?
* Have you already made the qpt template?

**Comment by ivanbusthomi** [comment]
> What is the rounding rule when it is not a population exposure?

I need to check with the standard first.

> Have you already made the qpt template?

I've created the template, but I haven't tokenized it yet. I will upload the tokenized template here. Do you think all of those suggestions are possible?

**Comment by lucernae** [comment]
I need to check the legend thing to know that it is possible to put the number there. I do think it is possible though, but the legend is coming from the layer, so I think the legend in qgis will have to be changed too.

For the analysis information, it is possible. @ismailsunni is making some of the text available for me to put in the report (like analysis time).

**Comment by ivanbusthomi** [comment]
Hi mas @lucernae , this is the tokenized template for a4 portrait and landscape
[final_template.zip](https://github.com/inasafe/inasafe/files/703305/final_template.zip)

and this is the updated supporter logo. @Charlotte-Morgan, is this OK?
![updated-supporters](https://cloud.githubusercontent.com/assets/7351977/21915082/12796c0e-d96a-11e6-982f-51b0e91f3dde.jpg)

**Comment by Charlotte-Morgan** [comment]
Thanks @ivanbusthomi for the work on this.  I think the BNPB logos looks a bit bigger than the others. You might want to check the visual size as opposed to the file extent if you understand :) the Crest may have white space.
The order is perfect and its good to have World Bank logo stacked.

**Comment by Charlotte-Morgan** [comment]
I've added @lucernae to the assignees - I hope this is ok :)

**Comment by lucernae** [comment]
Yes, of course it is ok :)

**Comment by samnawi** [comment]
Hi...

I just have some thoughts about the template :
1. Should we keep the hazard in the map and legend?
2. For population style, I think it's better to show it just in **one color (using hash style) (for "affected = true")**. In my opinion, we will visualize the information in the map, and the focus in the population analysis to show the location of the people live and affected. So, the user can see the location of people affected, and the information of the hazard, will be showed by the original hazard map.

**Comment by Charlotte-Morgan** [comment]
@samnawi - I think these are good suggestions. If its not possible to implement in 4.0, something to implement soon after

**Comment by lucernae** [comment]
So, just to confirm:

1. What should we put in the map and legend? only hazard layer or only impact layer?
2. In population style, show hazard and population?

**Comment by ivanbusthomi** [comment]
Hi @samnawi and @lucernae,
>For population style, I think it's better to show it just in one color (using hash style) (for "affected = true"). In my opinion, we will visualize the information in the map, and the focus in the population analysis to show the location of the people live and affected. So, the user can see the location of people affected, and the information of the hazard, will be showed by the original hazard map.

and
>What should we put in the map and legend? only hazard layer or only impact layer?

I will try and make some possible combination of layer and its style. I will update here once I've finished

**Comment by Charlotte-Morgan** [comment]
Hi @lucernae - I think we are implementing the standards which is impact layer however this might be different for population exposed to earthquake

**Comment by lucernae** [comment]
This is fixed.
