### ISSUE TITLE
Move realtime to its own repo

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3586]
### Problem

* Realtime still uses the old InaSAFE logic - which we will probably keep in place for now until 4.0 is considered stable.
* Realtime is also very much a discrete project with specific interest to Indonesian audience.
* Realtime still uses inasafe_data for testing which is undesirable for the main code tree since we are deprecating the use of large datasets in testing.

### Proposed Solution

1. Move the realtime logic over to its own repo
1. Import the InaSAFE libs as a git submodule. I have created a repo for this purpose: https://github.com/inasafe/inasafe-realtime
1. Migrate the needed testing elements so that realtime tests can be run on the new repo and we still have travis, coverage etc. being done on realtime.
1. Later we can write up a ticket to move any interesting realtime functionality into the main inasafe repo where applicable.

**Comment by Gustry** [comment]
Maybe you can have a look @myarjunar ? ;-)

**Comment by ismailsunni** [comment]
Hi @myarjunar 
I write some step by step to help you address to move inasafe realtime to https://github.com/inasafe/inasafe-realtime
1. Clone InaSAFE repository to your local machine, but only the realtime directory (to keep the history of realtime directory).
2. Fork InaSAFE Realtime repository
3. Add your InaSAFE repository as remote repository for first step
4. Fetch and merge InaSAFE Realtime repository (from step 2) to your local machine, in the first step working directory
5. Fix conflict or rearrange code structure as needed and commit it
6. Push InaSAFE Realtime to your InaSAFE Realtime repository on github (from step 2)
7. Make a PR to upstream repository of InaSAFE Realtime (https://github.com/inasafe/inasafe-realtime) as usual.
8. Ask people to review, and merge if it's ok

**Comment by Gustry** [comment]
Thanks @ismailsunni. I don't see or understand when you need to add the inasafe submodule with the 3.5 version.

9. We can add [landscape](https://landscape.io/dashboard) to the realtime repo.

**Comment by ismailsunni** [comment]
> I don't see or understand when you need to add the inasafe submodule with the 3.5 version.

Ah yes, I forget to write that

10. Add InaSAFE 3.5 version as submodule

**Comment by ismailsunni** [comment]
It has been moved now by @myarjunar 

Last step, remove realtime directory from InaSAFE code.

**Comment by Gustry** [comment]
Done by @myarjunar thanks !
