### ISSUE TITLE
Feature rate - post processor

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3589]
Some thoughts on the feature rate concept.
As well as asking users in the key words which field has the feature rate, should we also ask them the units that apply to the rate ie m2 or hectares or km 2

We should also consider that it may tke 2 fields to determine the value of something
eg in landcover there may be more than one rate one for yield in tonnes per hectare  and one for crop value in currency per tonne

@fredychandra @Gustry @samnawi @timlinux

**Comment by Gustry** [comment]
I'm closing this ticket as landcover as been covered in InaSAFE 4.2
