### ISSUE TITLE
Fix the dock logo

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3606]
# Problem
We have a new partner logo in the dock.  The logo is very low resolution and appears pixellated on the screen.

![image](https://cloud.githubusercontent.com/assets/5743135/22007086/c14790fe-dca2-11e6-8910-568c1dfedc3b.png)

The new logo in the dock is the draft logo included on the draft map template being developed by @ivanbusthomi for version 4.0 #3572; however this has not been documented in a ticket or approved by partners, and possibly was not reviewed through a pull request.

# Proposed solution 1
- [ ] write a ticket to say we need to update the dock logo
- [ ] prepare a new logo and seek approval from partners
- [ ] update the dock with the approved logo
- [ ]  merge after pull request is reviewed

@ivanbusthomi - can you please write the ticket and use my feedback on #3572 as well as find a way to make a high resolution version

# Proposed solution 2
If solution 1 can not be implemented by beta 2 release today. Please reinstate the old logo until the new logo is ready.

# cc
@timlinux @lucernae @fredychandra @samnawi @felix-yew

**Comment by ivanbusthomi** [comment]
Hi @Charlotte-Morgan , I noticed that I forgot to add the "InaSAFE Supporter" text from our old logo. Do you still want to add it in the new one?
![image](https://cloud.githubusercontent.com/assets/7351977/22007528/dd84a826-dca5-11e6-840a-ab0d3d347c7f.png)

**Comment by timlinux** [comment]
How does this look @Charlotte-Morgan and @ivanbusthomi ?
![screen shot 2017-01-17 at 11 10 51 am](https://cloud.githubusercontent.com/assets/178003/22007592/798fc6ce-dca6-11e6-8f08-5f20e3ce81a0.png)

**Comment by timlinux** [comment]
If we really want good quality we should probably think about tweaking InaSAFE to have a low res supporters logo for the dock and a hi-res logo for reports.

**Comment by ivanbusthomi** [comment]
> If we really want good quality we should probably think about tweaking InaSAFE to have a low res supporters logo for the dock and a hi-res logo for reports.

I was also thinking that might be the issue why the current new logo looks a bit odd because it is from the high-resolution

**Comment by Charlotte-Morgan** [comment]
hi @timlinux - I think that looks clearer than  the previous one
