### ISSUE TITLE
Needs value for hygiene packs and weekly rice for pregnant and lactating women

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#3607]
CC @Charlotte-Morgan 

I just need to know/confirm the value of these minimum needs (based on number of females displaced):

1. Weekly hygiene packs:

    ```
    weekly hygene packs = affected pop * fem_ratio * 0.7937 * week / intended day-of-use
    ```

   in the code:
   displaced female * 0.7937 * ( 7 days / 7 days)

2. Additional weekly rice for pregnant and lactating women:
    in the code:
    rice for lactating women = displaced female * 2 * 0.033782
    rice for pregnant women = displaced female * 2 * 0.01281
    total additional rice = rice for lactating women + rice for pregnant women

**Comment by Charlotte-Morgan** [comment]
@samnawi  - can you please check this one for @lucernae ?

**Comment by samnawi** [comment]
OK @Charlotte-Morgan I'll check it

**Comment by Charlotte-Morgan** [comment]
hi @lucernae  - seems like this is a good question.
The minimum needs for this are not specified in the BNPB Perka 7 / 2008 nor in sphere standard.
We need to review some old tickets to find out when this was added to the code and where the advice came from.
@timlinux

**Comment by samnawi** [comment]
Hi @Charlotte-Morgan I still not found about the regulation of the stuff in above. I just found some link in your comment https://github.com/inasafe/inasafe/issues/1230#issuecomment-60903150 that refers to some standard. But I'm not find anything about the specific number like in above.

**Comment by Charlotte-Morgan** [comment]
@samnawi  - thanks for looking. This could go way back to some of the original work.

**Comment by samnawi** [comment]
Hi @Charlotte-Morgan I found a ticket that seems like an initial discussion about a vulnerable group in here https://github.com/inasafe/inasafe/issues/312, but I still try to find a ticket of the further discussion about it.

**Comment by lucernae** [comment]
@samnawi I don't know if this will help, but you can find the value in InaSAFE code here:

https://github.com/lucernae/inasafe/blob/e97187fda0f91ecc388995600abfe444ce0fa389/safe/postprocessors/gender_postprocessor.py#L110-L110

There is also some comments related to it.

**Comment by ismailsunni** [comment]
@samnawi 
Sorry, I missed to read this thread, perhaps because of the full of notifications.
And no, I didn't know much about it. I think we should ask @mbernasocchi about it. It seems he wrote the code. https://github.com/lucernae/inasafe/blame/e97187fda0f91ecc388995600abfe444ce0fa389/safe/postprocessors/gender_postprocessor.py#L110-L110

**Comment by Charlotte-Morgan** [comment]
hi @mbernasocchi. We are hoping you can dredge back in your memory and maybe recall where the default values and calculations come from for InaSAFE post processing for hygiene packs and extra rice for pregnant and lactating women?
For some reason I had assumed that this was included in the BNPB perka 7/2008 but when we checked its not there and we can't find a source for this.  We would like to know some more if we can so that the post processors in version 4.0 can be updated.

**Comment by Charlotte-Morgan** [comment]
ping @mbernasocchi - please respond

**Comment by mbernasocchi** [comment]
@Charlotte-Morgan looking, funny enough I get plenty of notifications but not when I'm mentioned... need to fix that

**Comment by mbernasocchi** [comment]
@Charlotte-Morgan @ismailsunni 

> It seems he wrote the code. 

indeed, and he is happy to have put in the doc string where the value come from :)

```
Weekly requirements of female hygiene packs indicator.
This indicator reports the weekly requirements of female hygiene packs
for further detail refer to the "Sample InaSAFE Actions for Vulnerable
Populations" [27.07.2012] paper
```

now where _that_ paper is to be found it is a whole different question. It was a word file I got given printed out in 2012 in my first JK assignment. I searched my emails and local files but I don't have it. it was written by an external consultant IIRC. @vanpuk or @uniomni might recall who this person was.

hope this helps

**Comment by Charlotte-Morgan** [comment]
hi @mbernasocchi - that is a help. Seems like no one else saw the comment in the doc string :)
I can have a rummage in the files here to see if I have access to that source.

**Comment by vanpuk** [comment]
Hi all,
Can't recall the article, but wonder if Widya would?

**Comment by Charlotte-Morgan** [comment]
Hi @vanpuk, nice to see you here. I can'f find anything in the archives. I will try and see if Widya has any info.

**Comment by Charlotte-Morgan** [comment]
hi @fredychandra - can you please follow up with Widya regarding the origin of the extra rice and hygiene kits that we use in the minimum needs.  Maybe she has the paper mentioned by @mbernasocchi above

**Comment by fredychandra** [comment]
Hi @Charlotte-Morgan,
I will try looking for information about this issue with Widya. Will back soon after it.

**Comment by fredychandra** [comment]
Hi All,
Based on my discussion with Widya. As she remembers, besides used Perka, AIFDR refer to UNICEF and ICRC (International Committee of Red Cross) as well. UNICEF is a leading sector from WASH sector and it has a supply catalog for disaster. I have checked it, however I couldn't find the standard number of hygiene packs for women in the catalogue.  Here is the link
https://supply.unicef.org/unicef_b2c/app/displayApp/(cpgsize=5&layout=7.0-12_1_66_68_115_2&uiarea=2&carea=5365C4F27B890B70E10000009E710FC1&cpgnum=3)/.do?rf=y

ICRC as well has emergency items cataloq, Inside the catalog only provide the list item not the rate/number of standard for Women in particular period (week/month/ etc).  Here the link for your information http://procurement.ifrc.org/catalogue

At this moment, What can I suggest is we stay use Sphere standard to calculate the extra rice for lactating and breastfeeding women. 

Please have a check on this link  http://www.spherehandbook.org/en/appendix-6/ 
Inside that link, you can see minimum population requirement table toward nutrients. It only defines minimum calories that needed for minimum population. Then following table give indicator of average global population (% of population) broken down by age, pregnant and breastfeeding. 
the figures in the tables can be used as the minimum requirements. 

Please see the simulation calculation for this issues : 

The ratio (Based on sphere standard)
1. Pregnant          = 2,4 % of Population
2. Breastfeeding   = 2.6 % of Population

**How many extra rice that needed for them?** we can calculate as below :

Normal daily Calories need = **2100 Kkal** 
100 gr white Rice = **129 Kkl** 
So we need minimum rice  **1627.9 gr/day** to meet normal daily calories need (with assumption the survivors' diet are rice). It can modify depend on survivors' diet, for example :  sweet potatoes, wheat, etc

If  Pregnant/Breastfeeding. 
Pregnancy Calories need = **2100 kkal + 500 Kkal (extra calories/day) = 2600 kkal**
**100 gr Rice**  can produce **129 Kkl**
Total minimum need rice for Pregnancy is **2015,5 gr/day**

If we just calculate the extra rice number, just minus the total rice for pregnancy/lactating  with normal daily rice [ 2015,5 gr/day - 1627.9 gr/day = 387.6 gr/day]

So **387.6 gr/day is needed to meet daily calories for pregnancy/breastfeeding.** 


Cheers,

**Comment by lucernae** [comment]
Just one more question. Does the global population used will be total population or affected population or displaced population?

**Comment by fredychandra** [comment]
Hi @lucernae 

The ratio basically is from total population. But I think we still can use it for affected population. For example, if we have 1000 people affected.  So we can assume there will be 24 pregnant women and 26 women give breastfeeding on the affected population.

**Comment by Charlotte-Morgan** [comment]
@fredychandra has supplied rates. I think they should be used to calculate needs for the displaced population. ie the same as the min needs should be for displaced population

**Comment by Gustry** [comment]
@lucernae I think we can close this ticket. You updated the code with these notes.
