### ISSUE TITLE
Chapter numbering in InaSAFE Help

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#3618]
### Problem
We have a wonderful InaSAFE help document, now. After I observe it, I get confuse about the chapter numbering, while the content was complete. For example:

![image](https://cloud.githubusercontent.com/assets/13621886/22011197/5a93eb14-dcc0-11e6-8d02-1603bf14673e.png)
==================================================================
and,
![image](https://cloud.githubusercontent.com/assets/13621886/22011250/9cdf7cea-dcc0-11e6-9d73-be27ed5db690.png)

### Expected Behaviour
The document can show the good chapter numbering. So, user can read easily.

### Proposed Solution
Make it happy

Cc:
@timlinux @Charlotte-Morgan

**Comment by timlinux** [comment]
Thanks @felix-yew this is fixed in #3623
