### ISSUE TITLE
Create Metadata for All Analysis Output Layers

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3633]
### Problem
Currently, we only add metadata to exposure_impacted_layer after the analysis. We should add to the other outputs also.

### Expected Behaviour
All output layer has metadata.

**Comment by ismailsunni** [comment]
I just found that we already creating metadata for all the output layers even though there is only `ExposureSummaryLayerMetadata` class. Do you know something about this @Gustry ?

**Comment by Gustry** [comment]
Yes, it's creating an XML file, using the base class I think. You know the metadata engine better than me.

**Comment by ismailsunni** [comment]
Fixed in #4265
