### ISSUE TITLE
Wrong Calculation in the Total Population Report

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#3636]
### Problem
![image](https://cloud.githubusercontent.com/assets/8871958/22059582/16f53832-dda0-11e6-9232-0016a2dd1123.png)

I got some weird number in the Total Population, Because if you see the number in above, Total Population is more than the real population number in the exposure data. We can see the real number of population in the picture below
![image](https://cloud.githubusercontent.com/assets/8871958/22059762/c48dc87e-dda0-11e6-963a-5f05eda49b75.png)

### Expected Behaviour
The total population in the report should same with the total population in the exposure data

### Environment
* InaSAFE : Develop
* QGIS : 2.14.10
* OS : Win 7 64 Bit
* Data used :
  * Exposure : Ambon_Malteng_Population_Vector_WGS84.shp
  * Hazard : Ambon_Banda_Tsunami_FD_90m_WGS84.tif
  * Aggregation : Ambon Village

### Proposed Solution
Make It Happen

CC : @timlinux @Charlotte-Morgan @Gustry

**Comment by samnawi** [comment]
Hi @Gustry This morning, when I try to do a population analysis for Jakarta Flood, I found a weird number in the result, similar to the comment on above. I found it when I run the InaSAFE analysis using data :
Hazard : Jakarta Flood raster
Exposure : Jakarta Population Raster
Aggregation : Jakarta District (Then just select 2 area)
![image](https://cloud.githubusercontent.com/assets/8871958/22093744/9cbac82a-de3a-11e6-973e-84f375d34edf.png)

But, When I try to run the analysis using same data, without aggregation, I got the sensible result
![image](https://cloud.githubusercontent.com/assets/8871958/22093771/f2487e5e-de3a-11e6-990f-c62e07a8129c.png)

FYI, @felix-yew says that he also found a weird result when he run the analysis. Maybe @felix-yew can add some comment in here.

**Comment by Gustry** [comment]
Can you check that this ticket is still relevant ?
I couldn't replicate with DKI Jakarta dataset and Ambon. I will try again, maybe some different aggregation area.

**Comment by Charlotte-Morgan** [comment]
@samnawi  - can you please review this

**Comment by samnawi** [comment]
Hi @Gustry I've got a python error message when try to run the Ambon Dataset. The process is stuck at 80%.
![image](https://cloud.githubusercontent.com/assets/8871958/22543426/0bfc8538-e963-11e6-96e1-4c5a6e093944.png)

This is the error message 
```
2017-02-02T16:08:28	1	Traceback (most recent call last):
			  File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 767, in accept
			    status, message = self.impact_function.run()
			  File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 981, in run
			    self._run()
			  File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling
			    ret = fn(*args, **kwargs)
			  File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1149, in _run
			    self.summary_calculation()
			  File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling
			    ret = fn(*args, **kwargs)
			  File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1614, in summary_calculation
			    self._aggregate_hazard_impacted, self._analysis_impacted)
			  File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling
			    ret = fn(*args, **kwargs)
			  File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\gis\vector\summary_3_analysis.py", line 192, in analysis_summary
			    assert total == affected_sum + unaffected_sum + not_exposed_sum
			AssertionError
```

But, it's **working properly** for DKI Jakarta Dataset.
![image](https://cloud.githubusercontent.com/assets/8871958/22543586/c269b5fc-e963-11e6-83f1-541fec525a05.png)

@Gustry Is your analysis using ambon data can run?

**Comment by Gustry** [comment]
> This is the error message

Can you update with the develop branch, I already made a fix for this one this morning. Thanks.

**Comment by samnawi** [comment]
Ok @Gustry I'll try to update my develop version

**Comment by samnawi** [comment]
Ok @Gustry 

Done.

The analysis is running very well.

**Comment by Gustry** [comment]
Thanks, can we close this one ?

**Comment by Gustry** [comment]
I remember you got an issue when you selected 2 aggregations areas and you got very big numbers. Is-it fixed ?

**Comment by samnawi** [comment]
Oh yeah @Gustry , I remember.
I still got this problem
![image](https://cloud.githubusercontent.com/assets/8871958/22545076/f222e182-e969-11e6-80aa-7db3c364f66e.png)

It's relevant with this ticket? or should we create a new ticket for this?

**Comment by samnawi** [comment]
Hi @Gustry I try to do a simple analysis to check some strange calculation in the aggregation.
I create a dummy administrative boundary and vector population like you in the picture below
![image](https://cloud.githubusercontent.com/assets/8871958/22578732/87264fce-e9fd-11e6-93d2-4676b1f5b405.png)

![image](https://cloud.githubusercontent.com/assets/8871958/22578744/9f52e40e-e9fd-11e6-9916-eba917adf3fa.png)
![image](https://cloud.githubusercontent.com/assets/8871958/22578749/a8da61aa-e9fd-11e6-9b0e-19ad47dcc9f4.png)

For the first step, I try to run the analysis just for A & B area. This is the result
![image](https://cloud.githubusercontent.com/assets/8871958/22579017/81bc30f6-e9ff-11e6-83c3-0f16afa108d1.png)
![image](https://cloud.githubusercontent.com/assets/8871958/22579022/8abf3a68-e9ff-11e6-984b-2fa08f83085d.png)

 Then, I try to run the analysis just for A & C area, and this is the result
![image](https://cloud.githubusercontent.com/assets/8871958/22579047/bd501cc2-e9ff-11e6-8cb3-593585036a03.png)
![image](https://cloud.githubusercontent.com/assets/8871958/22579050/c7613f70-e9ff-11e6-8284-862538a6d41f.png)

And the last, I try to run all of the area, still focus on the same polygon.
![image](https://cloud.githubusercontent.com/assets/8871958/22579099/0a9620d0-ea00-11e6-9b69-64bc3dc70496.png)
![image](https://cloud.githubusercontent.com/assets/8871958/22579101/1169ab66-ea00-11e6-968a-fdd348e5005d.png)

**Comment by Gustry** [comment]
@samnawi For ambon, can you tell me exactly which files did you use and the name of these aggregation areas that you tried to use ?

And thanks a lot for your tests above. It would very nice if you can share this dataset with us for testing (zip or btsync). We can also include this dataset on travis and write a unittest to check that these results are correct. If you can have a full dataset with all this kind of use cases, it would be awesome ;-)
I will work on that today

**Comment by samnawi** [comment]
Hi @Gustry I'm sorry for late response. 
This is the data that I use for Ambon Analysis (I see it's already there in your laptop)
Exposure : Ambon_Malteng_Population_Vector_WGS84.shp
Hazard : Ambon_Banda_Tsunami_FD_90m_WGS84.tif
Aggregation : Ambon Village

Yeah @Gustry I 'm very happy to share the test data in above. But, I don't know why if I try to add a zip file in here, I always got this message 
![image](https://cloud.githubusercontent.com/assets/8871958/22677577/405c75a6-ed26-11e6-9535-f8738896aa81.png)

I will send the zip file through your email.

Thank you.

**Comment by Gustry** [comment]
Thanks a lot. Well spotted. This should have been fixed in https://github.com/inasafe/inasafe/pull/3794

**Comment by samnawi** [comment]
OK @Gustry I'll try it

**Comment by samnawi** [comment]
Oh... apparently teh PR is already merge, hahaha

**Comment by samnawi** [comment]
I think the problem is already fixed. Should we closed this issue @Gustry ?

**Comment by Gustry** [comment]
Yes, thanks for the report.

I'm going to make another change about size, counts and ratios today. I hope it's gonna be ok.
