### ISSUE TITLE
Map report doesn’t show the building color properly

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3638]
### Problem
When @timlinux gave presentation about InaSAFE update, he got a map report. But the building in map report doesn't have the colours like in the legend (all is grey, iirc).

### Expected Behaviour
The building's colour should be the same as the legend (high, medium, low hazard)

**Comment by lucernae** [comment]
@ismailsunni could you provide a pic, so I can see what it is?

**Comment by ismailsunni** [comment]
@Gustry is it you or @timlinux who got the issue? Can you guys give more details or screenshot if you can replicate it?

**Comment by Charlotte-Morgan** [comment]
Same as #3711 - it looks like the map report has the original exposure layer still showing and its over
![image](https://cloud.githubusercontent.com/assets/5743135/22362140/0698402a-e493-11e6-8dae-bae6ec21545e.png)

**Comment by timlinux** [comment]
@ismailsunni Yeah it was me. Just run a flood on buildings analysis and then look at the PDF....

**Comment by lucernae** [comment]
Is this still become an issue?
<img width="899" alt="screen shot 2017-02-01 at 00 28 47" src="https://cloud.githubusercontent.com/assets/831865/22476574/730513c0-e815-11e6-8d61-7e4f39a7a6f9.png">

**Comment by timlinux** [comment]
@lucernae yes the houses show but a different issue now - it is not showing all the layers visible in the project in the map report.

![2017-01-31 23_41_36-](https://cloud.githubusercontent.com/assets/178003/22485607/f4660e8a-e80e-11e6-9436-26f8f9485742.png)

**Comment by lucernae** [comment]
@timlinux @Charlotte-Morgan 
So what is the rule? Do I need to show all the layer or only the impact layer?

**Comment by timlinux** [comment]
@lucernae I would have thought at least hazard, impact and aggregation layers should show. Personally I would have liked to see other layers that are loaded in QGIS too, maybe @Charlotte-Morgan has different ideas. Can you check in the standards?

**Comment by lucernae** [comment]
Check lists:
- [ ] impact layer should be on top
- [ ] toggle in the InaSAFE settings should work #3711 
- [ ] impact layer symbolized according to standards
- [ ] extent should match if only using particular aggregation area

**Comment by Gustry** [comment]
> extent should match if only using particular aggregation area

I guess you need to zoom to the analysis layer. (whenever you have aggregation layer or not, selected features or not)

**Comment by lucernae** [comment]
Fix is merged
