### ISSUE TITLE
QGIS crash after clicking the raster cell in DKI Jakarta analysis

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3640]
### Problem
When @timlinux run the analysis with raster flood hazard in Jakarta, and click in one of the cell of the hazard layer that has been classified, it makes the QGIS crash.

### Expected Behaviour
Fix it.

If you have more details, please add @timlinux

**Comment by timlinux** [comment]
Note that the crash happened when using the identify tool to check the raster value.

QGIS Version 2.14.10
OS : MacOS

**Comment by Gustry** [comment]
I think this is not related to InaSAFE.
We should check deeper.

**Comment by Gustry** [comment]
I'm closing this ticket as I don't think it's related to inasafe.
