### ISSUE TITLE
PetaJakarta Flood Hazard Data: migration to  Petabencana.id

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3641]
# problem
PetaJakarta has migrated to petabencana.id where the service will eventually be expanded to Jakarta, Surabaya and Bandung.

![image](https://cloud.githubusercontent.com/assets/5743135/22093807/4325c14c-de3b-11e6-8359-6aa16d080265.png)

What impact does this have on flood realtime and the petajakarta download tools.
@ivanbusthomi  - please check if flood realtime is working
@ivanbusthomi - please check if the petajakarta download works

There is nothing on the new website to explain the data or API

@timlinux @lucernae

**Comment by lucernae** [comment]
Wow, this is actually very important...

**Comment by timlinux** [comment]
Just to note that I did test the tool in InaSAFE desktop so it should be working in real-time. There is however the question as to whether they are still pushing data to the old api or not...

**Comment by Charlotte-Morgan** [comment]
@felix-yew  - can you please check when there is flooding in Jakarta if this is working?

**Comment by ivanbusthomi** [comment]
> please check if flood realtime is working

Last flood event is more than two months ago (14 - 11 - 2016). I am both happy and worried. Happy that there is no flood in Jakarta, worried that they are not pushing new data to the **petajakarta** API.

**Comment by felix-yew** [comment]
@Charlotte-Morgan - sure.

**Comment by Charlotte-Morgan** [comment]
Hi @felix-yew - as discussed, can you please check this regularly now that it has started raining?

**Comment by felix-yew** [comment]
Hi, @Charlotte-Morgan - yes, if the rain comes in Jakarta I will check it. Today, there is no rain puddles in https://petabencana.id/map/jakarta and no update from our flood realtime (last update on 14 - 11 - 2016).

**Comment by timlinux** [comment]
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.
