### ISSUE TITLE
Consolidated list of realtime issues needing attention

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3643]
### Problem

This is a meta ticket - please refer to the sub tickets (or create sub tickets) to for details.

Ticket # | Notes | Status | Who
--------|-------|-------|---------
#0 | Double earthquakes  | open | @ivanbusthomi  , @hadighasemi , @Charlotte-Morgan
#0 | Make sure that BMKG knows that we are still using their sftp push | open | @ivanbusthomi 
#0 | We need to resolve data flows and have a discussion with BMKG and BNPB to ensure that we are using the best approach. | open | @Charlotte-Morgan , @hadighasemi 
#3689 | PDC we need to have check why quakes are not publishing | open | @lucernae 
#3690 | Ash - change zip message on upload page | open | @lucernae 
#0 | Ash Badan Geologi to test  | open | @Charlotte-Morgan , @RikkiWeber 
#3691 | Standby server | open | @ timlinux @lucernae 
#3692 | Deploy fixes (contours ordering / zip) | open | @lucernae 
#3694 | EQ use ITB Bayesian model | open | @lucernae 
#3695 | Shakemap report needs to show ID | open | @lucernae @ivanbusthomi
#3695 | Need name of IF on report| open | @ivanbusthomi @lucernae 
#3696 | Move all issues on Realtime to new repo | open | @lucernae 
#0 | Mismatched place names in shake headers | open | @Charlotte-Morgan @hadighasemi 
#3697 | Pick up from when celery dies and restart / get notification | open | @lucernae 
#3698 | Write a list of things that can go wrong e.g. empty output folder, mismatch id and folder name etc. and make some system documentation on how we deal with these. | open | @timlinux @lucernae  @ivanbusthomi 
#0 | Write a bash script to check for race conditions | open | @lucernae  
#0 | Write a ticket for @hadighasemi listing the products we actually want (grid.xml, stations?)| open | @lucernae  
#3701 | Enable downloading derived products (contours etc) | open | @lucernae @ivanbusthomi 
#3701 | Ensure download icons and tooltips on flood and eq are consistent (change flood & volcano to match eq page)  | open | @lucernae  
#3701 | Ensure we can download all hazards and and reports (e.g. ash) | open | @lucernae 
#3701 | Missing hazard download in flood | open | @lucernae 
#0 | Triage open EQ issues | open | @lucernae 
#3701 | Translate realtime flood page to Indonesian | open | @lucernae @ivanbusthomi

**Comment by lucernae** [comment]
Note that all InaSAFE realtime ticket will be migrated to the new repo after architecture migrations.

**Comment by timlinux** [comment]
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.
