### ISSUE TITLE
The raster is clipped with a smaller extent than the analysis extent.

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3655]
### Problem
![screen shot 2017-01-20 at 15 50 37](https://cloud.githubusercontent.com/assets/1609292/22142305/5aad4afe-df28-11e6-8926-4b467a37a220.png)

This is the Maumere scenario.
We can see that one building is marked as 'not exposed' as the tsunami raster is clipped with a smaller extent that the analysis area.

### Expected Behaviour
The clipped raster should have one row more to cover the analysis area.

### Environment
* InaSAFE : 4.0b

**Comment by timlinux** [comment]
Maybe make a 1pix distance buffer around the edge of the aggregation area?

**Comment by Gustry** [comment]
I fixed this issue in the PR above.
