### ISSUE TITLE
We need a note about the possibility of errors of omissions

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3657]
### Problem

@charlotte-morgan raised the issue that in some cases it may be possible for a building to extend beyond an aggregation (where it is tagged as not flooded) into a hazard pixel / polygon that is not in an aggregation area - and in so doing be incorrectly counted as not flooded.

### Expected Behaviour

Users should understand the limitations of the analysis environment.

### Proposed Solution

Add a note in limitations indicating that in some cases exposure features may be incorrectly classified if hazards are in an adjacent area.

**Comment by Charlotte-Morgan** [comment]
hi @timlinux - i think this may fit well in caveats. We do not seem to be using existing caveats well. Can you please remind me how to add them to the notes for different exposures?

**Comment by timlinux** [comment]
Hi @Charlotte-Morgan 

To add a caveat to a hazard or exposure the general workflow is:

1) Define the caveat in caveats.py

```
caveat_simulation = tr(
    'The extent and severity of the mapped scenario or hazard zones '
    'may not be consistent with future events.')
```

2) Import the caveat in hazards.py or exposures.py

```
from safe.definitions.caveats import (
    caveat_simulation, caveat_local_conditions, caveat_analysis_extent, etc.)
```

3) Add the caveat to the notes list for the hazards you want it in.

```
hazard_volcano = {
    'key': 'volcano',
    'name': tr('Volcano'),
    'description': tr(
        'A <b>volcano</b> describes a mountain which has a vent through '
        'which rock fragments, ash, lava, steam and gases can be ejected '
        'from below the earth\'s surface. The type of material ejected '
        'depends on the type of <b>volcano</b>.'),
    'notes': [  # additional generic notes for volcano
        caveat_simulation,
        caveat_local_conditions,
        caveat_analysis_extent,
    ],
```

THE END

Perhaps it will be useful to have some standard hazard and exposure caveats that apply to all exposures and caveats - something we can easily do when the need arises...

**Comment by Charlotte-Morgan** [comment]
thanks @timlinux - I have filed this for future reference
