### ISSUE TITLE
Displaced postprocessors behaviour

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#3664]
We need some well defined behaviour for Displaced postprocessor:

- What are hazard classifications with displaced ratio?
- What is the displaced ratio for each hazard class in that particular hazard classification?
- Displaced postprocessor only applied for "affected" population
- Minimum needs is calculated from displaced count as input
- Gender, Youth, Adult, and Elderly field is calculated from displaced count as input
- Do we need to update report? Change Total affected population in the table into Total displaced population for minimum needs and vulnerability breakdown.

CC: @Charlotte-Morgan and @timlinux 
@ismailsunni @Gustry 
Please add more if I missed it.

**Comment by ismailsunni** [comment]
Do we need something like: displace female, affected female?

**Comment by lucernae** [comment]
For the report, I think we agreed that the number of females reported (and weekly hygiene + additional rice) is based on displaced female.

**Comment by Charlotte-Morgan** [comment]
Do you think we can implement this for any hazards apart from earthquake until we have displacement rates for other hazards?  I think maybe not and that we should wait for #3634 to be discussed before its implemented

**Comment by Gustry** [comment]
We need at least a displacement value for every kind of hazard as we need this value to compute minimum needs.

**Comment by lucernae** [comment]
What I can propose now is to set the displacement rates to 1.0 for other hazard. So the number will be the same as affected.

**Comment by timlinux** [comment]
@lucernae personally I don't think it makes sense to use 1.0 for each affected class. If we are going to use anything as a default I would put it to zero (with a note indicating that displacement rates are not yet defined) or use a nominal rate like 0.01, again with a note that a nominal displacement rate of 1% was used in the absence of input from hazard experts.

**Comment by lucernae** [comment]
Can we close this? Our current implementation is to use displacement rate 1% for flood.

**Comment by timlinux** [comment]
I think we can close it and add specific displacements on a case by case basis.
