### ISSUE TITLE
Check Reporting behaviour is correct for Earthquake

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#3666]
Reporting logic is generic, so we need to check that it is produced correctly for Earthquake.

**Comment by Gustry** [comment]
# Current problem : 
![screen shot 2017-01-30 at 15 01 31](https://cloud.githubusercontent.com/assets/1609292/22425785/082b102c-e6fd-11e6-9617-43cf952a5050.png)

> Is it MMI levels instead of hazard zones?

No, we don't display the breakdown I think.
I think in 3.5, we were using low, medium and high. I need to check.
We can have it with https://github.com/inasafe/inasafe/blob/develop/safe/definitions/hazard_classifications.py#L114 so in that case, I need to work on it.

**Comment by Gustry** [comment]
@Charlotte-Morgan Did you get some inputs in this issue ?

**Comment by Charlotte-Morgan** [comment]
@Gustry - we did not discuss this one. I still think we need to add a new classification for the full MMI range. I am not sure where the existing classification comes from.  I would need to check it against BNPB requirements and published maps

**Comment by lucernae** [comment]
I included displaced and fatalities to Analysis result, in case we want to show it.

<img width="404" alt="screen shot 2017-02-23 at 23 34 07" src="https://cloud.githubusercontent.com/assets/831865/23268525/9bf0d1e4-fa20-11e6-9c55-327f6ae5a4ef.png">

Also I prepared another section in case we want to show it:
For this one, I need mmi-related fields in analysis layer (for each mmi levels and each exposed/displaced/fatalities combinations).
<img width="402" alt="screen shot 2017-02-23 at 23 34 47" src="https://cloud.githubusercontent.com/assets/831865/23268561/b5edd632-fa20-11e6-8bc7-fe29f1501f41.png">

**Comment by Charlotte-Morgan** [comment]
Fatalities should always be shown as a range. Not an exact number or even rounded.
Let me get more advice from @hadighasemi on this on Thursday. 
FYI - @RikkiWeber

**Comment by lucernae** [comment]
Yes, @hadighasemi clarified some of my question just today.
CMIIW, @hadighasemi .
So, also a note for @Gustry and @timlinux 
In Earthquake, fatalities is a range of number and can be **with** a probability for that MMI range.
Hadi showed me this:

![cpebpnvwsaagbpe](https://cloud.githubusercontent.com/assets/831865/23401066/f2231016-fdd8-11e6-9b51-f7b1714c6ac7.png)

So fatalities can be a number with a probability of that number happens. So it might not fit very well with our fatalities rate in the hazard class definition. I'm not sure with other hazard, but we can't just multiply the number of population with fatality rate for earthquake. We might have to provide a function or table for that (like in the v3.5).

So, yeah, my example there in fatalities column is clearly wrong.

**Comment by timlinux** [comment]
Probably we should use roman numerals for MMI too. @lucernae please update with what info you think will be needed in order to generate a histogram like in pager.

**Comment by Charlotte-Morgan** [comment]
Hi - this example of the pager histogram is for InaSAFE realtime when it migrates to versioin 4.0 - not for now :). We should discuss this in the realtime repo.
@hadighasemi @RikkiWeber

**Comment by lucernae** [comment]
> Hi - this example of the pager histogram is for InaSAFE realtime when it migrates to versioin 4.0 - not for now :). We should discuss this in the realtime repo.

Yes @Charlotte-Morgan , I'm quoting it just to explain that fatalitites, is not a fixed number, rather a range with probabilities.

> Probably we should use roman numerals for MMI too. @lucernae please update with what info you think will be needed in order to generate a histogram like in pager.

The Roman numeral will be coming directly from the layer. For the MMI Detail section, it is just a section I propose (special section for EQ), and right now it is disabled and only showed up when using debug mode.

**Comment by Charlotte-Morgan** [comment]
Hi @lucernae - i have discussed the reporting of eq fatalites now with @hadighasemi.
he recommends that we report in the following classes:
0 - 100
100 - 1,000
1,000 - 10,000
10,000 - 100,000
>100,000.

This compares to the way the report is today, which does not apply the previous rules for reporting fatalities.
![image](https://cloud.githubusercontent.com/assets/5743135/23495011/e82946d6-ff48-11e6-9694-3d211ba78aa3.png)

We should look to add ranges or revert to the way fatalities were reported in 3.5 but not use the standard population rounding.

**Comment by lucernae** [comment]
I made it like this:
<img width="1180" alt="screen shot 2017-03-02 at 15 43 52" src="https://cloud.githubusercontent.com/assets/831865/23499553/2567c002-ff5f-11e6-863a-3244f393a1da.png">

**Comment by timlinux** [comment]
I think we have taken care of the pop ranges and for the histogram discussion we can start a separate issue for that when needed.
