### ISSUE TITLE
We need to add PetaJakarta flood thresholds

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3667]
### Problem

We discussed with @Charlotte-Morgan having more sensible hazard thresholds for floods. Currently You can choose between generic (High, Medium, Low) classes and Flood (wet, dry) classes. It would be much better to also provide classes similar to those used in PetaJakarta:

![screen shot 2017-01-24 at 10 04 49 am](https://cloud.githubusercontent.com/assets/178003/22238925/a5bb7484-e21c-11e6-9eb4-de0d2729b2a9.png)

### Expected Behaviour

User should be able to choose standard flood thresholds for continuous data.

### Proposed Solution

@timlinux to add a new set of flood thresholds based on PetaJakarta.

### CC

@Charlotte-Morgan @ismailsunni

**Comment by Charlotte-Morgan** [comment]
@felix-yew - please note that we need to incorporate plans here in the standards for flood hazard thresholds

**Comment by felix-yew** [comment]
@Charlotte-Morgan - yes, we will update this to our standard report and we need to discuss it related to the colour will we use, the same colour or we use with our standard colour adapt to the hazard class colour like an example that I create in https://github.com/inasafe/inasafe/issues/3676#issuecomment-275055224

**Comment by Charlotte-Morgan** [comment]
@felix-yew - we need to have exposed elements symbolised the same as others in the standard. How hazard data are shown is a separate issue. In this case I think we should use the same colours as we do for the download and as per pertabencana maps

**Comment by Gustry** [comment]
Can we close this one @timlinux ?
