### ISSUE TITLE
Padang project consistently crashes QGIS

### ISSUE THREAD

**Issue by mbernasocchi** [inasafe/inasafe#367]
how to reproduce: 
- open AMCDRRbranch qgis_projects/padang.qgs
- run, after a minute or so and taking up all Gb of ram and swap it segfaults during "calculating results" with this message:

Debug: src/core/qgsmessagelog.cpp: 41: (logMessage) 2012-10-22T11:47:55 InaSAFE[0] gdalwarp -q -t_srs EPSG:4326 -r near -tr 0.000899 0.000899 -cutline /tmp/inasafe/22-10-2012/marco/work/extent_Mcjm3X.kml -crop_to_cutline -of GTiff "/home/marco/dev/qgis-plugins/inasafe_data/exposure/population_sumatra.tif" "/tmp/inasafe/22-10-2012/marco/work/clip_7EwcHH.tif"
Debug: src/core/qgsmessagelog.cpp: 41: (logMessage) 2012-10-22T11:48:19 InaSAFE[0] calculate_impact called with:
Layers: [<safe.storage.raster.Raster instance at 0x54d8680>, <safe.storage.raster.Raster instance at 0x54d86c8>]
Function:<class 'safe.impact_functions.earthquake.itb_earthquake_fatality_model.ITBFatalityFunction'>
Segmentation fault (core dumped)

**Comment by timlinux** [comment]
This will be resolved in 4.0. Closing.
