### ISSUE TITLE
Report template papercuts

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3688]
We have new report templates for InaSAFE version 4.0 with updates to address the reporting standards - thanks @lucernae .

# papercuts
There are some small changes to make this report match well with the reporting standards.
- [x] please add the analysis question
- [x] please move the general table heading into the blue bar above and included the word estimated
- [x] please remove "total" from the hazard zone labels in the general table
![image](https://cloud.githubusercontent.com/assets/5743135/22322815/2d38c460-e3d1-11e6-9ca1-3932f23347ee.png)
- [x] please place the note about column and rows being excluded below the relevant table
- [x] please review list spacing - maybe the spaces can be smaller?
![image](https://cloud.githubusercontent.com/assets/5743135/22322890/9d905fe8-e3d1-11e6-9406-821d5526e995.png)
- [ ] please update the analysis details as per the standard. 
The proposed format is: Hazard source: <hazard layer name> - sourced from ..... 
and would include details for hazard, exposure, aggregation and analysis function
![image](https://cloud.githubusercontent.com/assets/5743135/22322907/bbc90d84-e3d1-11e6-8dfc-b22cdbebd3cb.png)

# proposed action
make it happy

cc @timlinux @ivanbusthomi @felix-yew

**Comment by lucernae** [comment]
@Charlotte-Morgan I have some parts unclear on this one:
> please update the analysis details as per the standard.
> The proposed format is: Hazard source: - sourced from .....
> and would include details for hazard, exposure, aggregation and analysis function

- What should I do if the source is empty, can I put ```Layer name - source not available - ```
Also for @timlinux @ismailsunni 
- How do I get the part: ```published reference for this type of analysis``` for now?

**Comment by Charlotte-Morgan** [comment]
Hi @lucernae - I think the easiest thing to do for now it to make the report have exactly the same details as we have included on the map template. This is three rows; one for hazard data, one for exposure and one for aggregation. There is also information about the analysis used.
Where aggregation is not used - it states 'not used'.

![image](https://cloud.githubusercontent.com/assets/5743135/22910870/8cebbc74-f28f-11e6-9a4d-b084475eef51.png)

I hope this is really easy to copy from the map template to the report.

**Comment by lucernae** [comment]
@Charlotte-Morgan have you looked at this PR yet? #3832 

> Where aggregation is not used - it states 'not used'.

Ok, I will show it for this.

What should I do if the source is empty for hazard, exposure, or aggregation? Is it ok if I put it like this:

**Comment by lucernae** [comment]
Closing this. Fix merged.
