### ISSUE TITLE
PDC we need to have check why quakes are not publishing

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#3689]
I have no proposed solutions at the moment, just to create new ticket first.

**Comment by Charlotte-Morgan** [comment]
hi @lucernae - I think this is quite urgent to fix.  DMI are working with BMKG on the issue of duplicate reports.  I believe PDC people are in Indonesia next week. Is it possible we should schedule a meeting to discuss the issue?
cc @timlinux @hadighasemi @lucernae @RikkiWeber

**Comment by timlinux** [comment]
@gubuntu cc for you too

**Comment by timlinux** [comment]
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.
