### ISSUE TITLE
EQ use ITB Bayesian model

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#3694]
Switch impact function to use ITB Bayesian Model.
Should be trivial.

**Comment by Charlotte-Morgan** [comment]
@lucernae To be clear, this should be the ITB Bayesian Fatality model and it's kinda really important to make this happen soon please :)

**Comment by timlinux** [comment]
@lucernae first thing to do would be to confirm that we can actually use the Bayesian IF for the report. If not we need to think about either porting realtime to InaSAFE 4.0 or patching the Bayesian IF to give you any outputs that may be missing.

**Comment by timlinux** [comment]
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.
