### ISSUE TITLE
BUG: We need to manage the map extent in default maps

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3699]

**Comment by timlinux** [comment]
Can you add some more description for this @Charlotte-Morgan? Thanks!

**Comment by Charlotte-Morgan** [comment]
hi @timlinux - I've had a look and this ticket was based on  a product from the batch runner where maybe zoom to impact layer is not selected.  I think we can close this .. I'll write a different ticket for maps

**Comment by timlinux** [comment]
Ok thanks @Charlotte-Morgan
