### ISSUE TITLE
Additional functionality for Realtime

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#3701]
- Enable downloading derived product (contours, flood hazard, etc)
- Ensure download icons and tooltips on flood and eq are consistent (change flood & volcano to match eq page)
- Missing hazard download tool in flood
- Translate realtime flood to Indonesian

**Comment by ivanbusthomi** [comment]
> Translate realtime flood to Indonesian

This ticket is about realtime flood translation into Indonesian.

**Comment by timlinux** [comment]
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.
