### ISSUE TITLE
New icon: Multi buffer tool

### ISSUE THREAD

**Issue by myarjunar** [inasafe/inasafe#3704]
### Problem
We need a new icon for multi-buffer tool in InaSAFE toolbar.

**Comment by myarjunar** [comment]
![donut-icons-65984](https://cloud.githubusercontent.com/assets/11134669/22334152/357cf34a-e40c-11e6-8788-f274b017e487.png)
Hi @MariaSolovyeva , just my idea, maybe we can make the icon looks like a donut but with InaSAFE theme. Because if the input is a point, the output layer after buffer will look like a donut :smile:

**Comment by Charlotte-Morgan** [comment]
yum - good suggestion @myarjunar

**Comment by timlinux** [comment]
+1 for donuts on the next site visit too :-)

**Comment by MariaSolovyeva** [comment]
hi @myarjunar, @Charlotte-Morgan  and @timlinux , here is the very simplified donut, let me know! 
I cannot attach SVG here, so here is the PNG preview with added gray background. I will copy it as a letter to Tim with SVG file.
![multi-buffer](https://cloud.githubusercontent.com/assets/10400420/22466422/3d2011a4-e7d1-11e6-9268-a20d6e292e3d.png)

**Comment by MariaSolovyeva** [comment]
Another version

![multi-buffer2](https://cloud.githubusercontent.com/assets/10400420/22466483/7d9ecb6c-e7d1-11e6-8fce-6a261aefe4e5.png)

**Comment by Charlotte-Morgan** [comment]
Hi @felix-yew and @samnawi - can you please look at this and comment on this icon for the new buffer tool?

**Comment by felix-yew** [comment]
Hi @MariaSolovyeva - the icon is awesome, I like the simple one in another version :+1: so we still see the grey light buffer :smile:

**Comment by ismailsunni** [comment]
@myarjunar can we close this? Since we have been using the icon in the tool?
