### ISSUE TITLE
BUG: Map PDF shows exposure layer

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3711]
### problem
the PDF map shows the exposure layer as well as the impact layer even though the option to hide the exposure layer is checked.
![image](https://cloud.githubusercontent.com/assets/5743135/22360887/edc3305c-e486-11e6-91cf-d4fdcb650e79.png)

![image](https://cloud.githubusercontent.com/assets/5743135/22360909/26c7d826-e487-11e6-9c1f-7caed3ff5b3e.png)

### expected behaviour
the exposure layer should not show in the printed map

### proposed solution
make it happy

**Comment by timlinux** [comment]
Ah I think this is the same thing we saw when I was doing a walk through in Jakarta last trip. @ismailsunni you made a ticket for that already right?

**Comment by Charlotte-Morgan** [comment]
I'm not sure if there is already a ticket

**Comment by ismailsunni** [comment]
Is it this one? https://github.com/inasafe/inasafe/issues/3638

**Comment by Charlotte-Morgan** [comment]
Yes - same thing. I just checked the buildings and it is the same. The original exposure layer is drawing over the top or instead of the impact layer.

**Comment by lucernae** [comment]
Can we close this? @ivanbusthomi ?

**Comment by ivanbusthomi** [comment]
@lucernae , Yeah I think we can close this, last time I tried opening a map pdf, the exposure layer has already been hidden. Thanks.
