### ISSUE TITLE
Add options for printing analysis  maps

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3712]
In InaSAFE 4.0 - the analysis runs quickly and the reports and maps are printed automatically.

# problem
The print button in the dock actually opens the pdfs that were produced when the analysis ran. This is great (maybe rename the button to say "Open Reports") but its not easy for a user to make a small change and print a custom map.

ie turn off one component of the default legend (eg dry in a wet dry flood scenario) and print the map again

# proposed solutions
Give users a "print map" button that prints their displayed layers* using the default map template
Make the default map template available in the map composer

* I think this would make it much easier than for us to guess what layers to show on various maps 

I would probably like to be able to print a map like this
![image](https://cloud.githubusercontent.com/assets/5743135/22361057/9e9aa18e-e488-11e6-850f-de194010b82c.png)

**Comment by timlinux** [comment]
@lucernae any thoughts on the best way to do this? I would still like to see the report classes moved into the ImpactFunction class. @Charlotte-Morgan it is on our plan but I am wondering how much of a blocker it is for you for 4.0? I know it is a functional regression so probably we should make a plan to at least let the user open the composer template as you have suggested....

**Comment by Charlotte-Morgan** [comment]
@timlinux - agree its a functional regression. I would prefer to not add a blocker but more to look for a workaround for now. Maybe there is some easy way to give access to the template in map composer and some notes for trainers in the short term.
Maybe this can be on the list for an early bug fix release?

**Comment by lucernae** [comment]
We'll be using #3822 for now to just provides the composer template
