### ISSUE TITLE
Realtime earthquake translation in Bahasa Indonesia

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#3714]
### Problem
Similar issue with InaSAFE Realtime flood translation (https://github.com/inasafe/inasafe/issues/3291), currently InaSAFE Realtime Earthquake in Bahasa Indonesia is not 100% translated yet. Some parts that need to be translated are:

* Menu section
![image](https://cloud.githubusercontent.com/assets/7351977/22362666/f61c21ea-e496-11e6-81fc-fb8fa1e6246b.png)
 * Description section
![image](https://cloud.githubusercontent.com/assets/7351977/22362674/09ea4c7e-e497-11e6-89a0-3f38a85cff25.png)

* Map Title
![image](https://cloud.githubusercontent.com/assets/7351977/22362680/16614b92-e497-11e6-84b5-7362f636977f.png)

* Contextual filter
![image](https://cloud.githubusercontent.com/assets/7351977/22362696/30e04f4a-e497-11e6-95ea-295fd66512c5.png)

* Search string and time unit in table of earthquake events,
![image](https://cloud.githubusercontent.com/assets/7351977/22362729/66af8e06-e497-11e6-8e30-fb9797a98405.png)
and also information on the bottom of the table
![image](https://cloud.githubusercontent.com/assets/7351977/22362749/8e516baa-e497-11e6-9594-f082bb4477bb.png)

* Supporter description at the bottom of the page
![image](https://cloud.githubusercontent.com/assets/7351977/22362760/a37b1580-e497-11e6-9411-a8467f66247c.png)

### Expected Behaviour
The Realtime Earthquake platform should properly show the page in Bahasa Indonesia if the language option is set to Bahasa Indonesia

### Environment
* InaSAFE : Realtime earthquake
* QGIS : 
* OS : 
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :

### Proposed Solution
Make it happy.

---

**CC** : @lucernae @Charlotte-Morgan @timlinux @felix-yew @samnawi

**Comment by timlinux** [comment]
Thanks for this @ivanbusthomi . Could I ask that when you make realtime related tickets, you label them with realtime and assign Gavin (@gubuntu) and Rizky to the issue so that they can be aware of them? Thanks!

**Comment by timlinux** [comment]
Closing this as the realtime work has been moved to its own repo and a ticket has been opened there.
