### ISSUE TITLE
Return of the purple patch

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3720]
### Problem
When the analysis extent is set using extent on map, I got a big purple patch that did not go away. 
It stayed there when the results were displayed

### Proposed Solution
I'm sure I've seen this before and it was fixed.

**Comment by Gustry** [comment]
Can you provide a screenshot or how can I replicate ?
I couldn't see it.

Thanks

**Comment by Gustry** [comment]
I'm closing this ticket as I can't replicate.
It might happen I think, but it's a very precise workflow.
