### ISSUE TITLE
KW Wizard - resample population raster data

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3721]
### Problem
The key word wizard asks if you want to resample the population raster or prevent this from happening.
I think this may be a legacy option and maybe its not relevant to ask this or have this key word for continuous population rasters?

### Expected Behaviour
Users will not be asked unnecessary steps

### Proposed Solution
Confirm if this is still required in version 4.0

**Comment by timlinux** [comment]
Hi

This is a an option that @maning and friends added / asked for (can't remember which) because they wanted to force raster resampling to be to the size of the population data rather than the hazard data. I'd also prefer to remove this now since with the new architecture I don't see much need for this behavior any more. It will also make the wizard simpler which is a +1

**Comment by ismailsunni** [comment]
This one maybe : https://github.com/inasafe/inasafe/issues/1008 ?

**Comment by Charlotte-Morgan** [comment]
I agree - it is important to control resampling behaviour. But if resampling is not part of the process any more, then we can remove this preference.  If resampling is still part of the process for data preparation or analysis, then this should stay.

**Comment by timlinux** [comment]
I think yes.#1008. I am wondering if we have any pop density based tests @ismailsunni? Maybe good to assign this to @rohmat who can close it after adding a test case for pop density

**Comment by ismailsunni** [comment]
@timlinux no as far as I know. Perhaps we can ask @felix-yew or @samnawi if they have test data for it

**Comment by Gustry** [comment]
> If resampling is still part of the process for data preparation or analysis, then this should stay.

Yes, for EQ raster on population raster, we are still using the keyword `allow_resampling` https://github.com/inasafe/inasafe/blob/develop/safe/gis/raster/align.py#L75 so as to align these rasters.

**Comment by Charlotte-Morgan** [comment]
ok - thanks to confirm.  Your call if it should stay in the wizard or move to options - ie what fatality function would you like to use and is it ok to resample your population data

For now - i think leave it in

**Comment by timlinux** [comment]
Ok, agreed lets leave it in for now!
