### ISSUE TITLE
EQ Raster on Population raster : raster symbology

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3732]
### Problem
With an EQ raster on population raster, InaSAFE V4 produces a raster of displaced people.

This raster doesn't have any symbology for now.

We agreed to display the raster with a binary style.
Can you provide the style (colors) that we should use ?

**Comment by Charlotte-Morgan** [comment]
hi @Gustry - I think @ivanbusthomi has already supplied this. Maybe to @lucernae 
If not; I'm passing this to @ivanbusthomi to follow up

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi - if this is finished - please close the ticket

**Comment by Gustry** [comment]
I didn't get any feedback on this one.
How should we style the exposed raster (binary style) and the vector aggregation ?

**Comment by Charlotte-Morgan** [comment]
maybe we are all stuck with key error :(
@ivanbusthomi  - please supply the symbology we developed for Pidie.

**Comment by ivanbusthomi** [comment]
This is the symbology that we did for the Pidie Earthquake raster on raster population.
![image](https://cloud.githubusercontent.com/assets/7351977/23004402/18cdc166-f429-11e6-8f4e-7bdc859ca6c8.png)

Zip containing the .qml files [Aceh_EarthquakeOnPopulation_Subdistrict_WGS84.zip](https://github.com/inasafe/inasafe/files/778899/Aceh_EarthquakeOnPopulation_Subdistrict_WGS84.zip)

**Comment by Gustry** [comment]
The raster styling has been done in the PR above.
