### ISSUE TITLE
Reports should work with a EQ raster on raster population

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3733]
### Problem
![screen shot 2017-01-30 at 15 01 31](https://cloud.githubusercontent.com/assets/1609292/22425785/082b102c-e6fd-11e6-9617-43cf952a5050.png)

You should wait for PR #3669 to be merged

**Comment by lucernae** [comment]
The PR is now merged. So I should check on this, right?

**Comment by Gustry** [comment]
I created the ticket before your merge. We will check. Thanks

**Comment by lucernae** [comment]
Ah, no, I meant your PR #3669 :D.
So, what do we want to report here?
Is it MMI levels instead of hazard zones?

**Comment by Gustry** [comment]
I think it's a duplicate of #3666
