### ISSUE TITLE
We need to report on hectares, not on square meters

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3742]
### Problem
![screen shot 2017-01-31 at 10 02 41](https://cloud.githubusercontent.com/assets/1609292/22458361/743e4366-e79c-11e6-80b4-3123d3dec7a7.png)

We do an analysis on landcover, we need to report with hectares, not, square meters.

**Comment by timlinux** [comment]
@Gustry  and @Charlotte-Morgan should we not do the same for roads (km vs m when the length exceeds 1000m?)

**Comment by Charlotte-Morgan** [comment]
sounds like a good idea - do I need to update the standards?

**Comment by Gustry** [comment]
Just to be sure, in a legend, is-it ok if we have two units (km and m for instance) ?
* Length of roads
  * High hazard zone (900m)
  * Medium Hazard zone (1.2km)
  * Low Hazard Zone (120m)

Or should we check if every values can be converted first ? (all to km if it's possible).

I think we can't do that for reports as units are in headings. I'm talking about the legend.

**Comment by Charlotte-Morgan** [comment]
hi @Gustry  - I think it would be better to use only one unit in the legend.  In the example above I would use meters- 1200m is better than 0.9 km if you are to be consistent.

**Comment by Gustry** [comment]
Ok so, in the legend, only if all values are greater than 1000 we switch to kilometres if I understood.

**Comment by Charlotte-Morgan** [comment]
I think its more about the range of values
if you have 20m in one class and 20,000m in another I would use metres for all.

However; if you get 1500m and 986000m then it would be better to use km ie 1.5 and 986Km

**Comment by Gustry** [comment]
Yes, so my rule works ;-)

**Comment by Gustry** [comment]
These 2 PR have been merged. I'm going to close this issue.
