### ISSUE TITLE
InaSAFE should be French friendly

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3743]
### Problem

When we use InaSAFE V4 in French : 
![screen-shot-2017-01-26-at-22 05 07](https://cloud.githubusercontent.com/assets/1609292/22463333/660ddaf8-e7b1-11e6-98d8-2c8587b8eb55.png)

@lucernae If you have an idea how to fix it easily in the report.

I will have a look too.

**Comment by lucernae** [comment]
LOL at the title :D. 
Is it unicode problem? Was it affecting just the report or with the legend too?

**Comment by Gustry** [comment]
> Is it unicode problem?

I guess yes.

> Was it affecting just the report or with the legend too?

Yes, the report. The legend is fine.

I noticed some other problems when using inasafe in french.

**Comment by lucernae** [comment]
How can I replicate this @Gustry ? Is it using a specific dataset, or can I just switch my qgis locale to french?

**Comment by timlinux** [comment]
Cheese and olive oil will fix it

**Comment by Gustry** [comment]
I could fix some issues when we use InaSAFE in French. Let's close this one for now.

**Comment by Gustry** [comment]
I got some other issues today

**Comment by Gustry** [comment]
The HTML is fine but the PDF is still ugly.

**Comment by Gustry** [comment]
@lucernae I could fix weird characters in reports when we display them in the dock.
<img width="434" alt="screen shot 2017-02-15 at 12 44 15" src="https://cloud.githubusercontent.com/assets/1609292/22973003/872625ca-f37c-11e6-988a-e8493ea329b8.png">

The HTML is OK in the browser. But then the PDF is bad:
![screen shot 2017-02-15 at 12 47 33](https://cloud.githubusercontent.com/assets/1609292/22973148/22c59790-f37d-11e6-8ba7-feb13da31596.png)
 
Do you generate the PDF from the HTML ? If yes, can you show me where you open the HTML ? You need to open it in UTF8, like in the dock : https://github.com/inasafe/inasafe/blob/develop/safe/gui/widgets/dock.py#L883
Can you tell me where in your code you are generating the PDF ?
Thanks @lucernae

**Comment by Gustry** [comment]
Thanks for your inputs @lucernae. I will close this issue until I find the next problem.
