### ISSUE TITLE
OSM downloader is not working

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3750]
### Problem

When I click OK I get this

![screen shot 2017-02-01 at 9 46 06 am](https://cloud.githubusercontent.com/assets/178003/22498833/61fbf938-e863-11e6-8604-d91acd7e3bda.png)

### Expected Behaviour

The data should be downloaded when pressing OK.

### Environment
* InaSAFE : 
* QGIS : 
* OS : 
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :

### Proposed Solution

Investigate and fix.

**Comment by Gustry** [comment]
Hehem this comes from me yesterday :(

**Comment by myarjunar** [comment]
earlier this morning I got another error message actually, it's something like `server unreachable` and the log is `host not found: http://staging.osm.kartoza.com/`. I don't know if it's a different thing or the same thing.

**Comment by Gustry** [comment]
It's another problem.
http://staging.osm.kartoza.com/ should work, but it's 502 for now. I'm going to restart on the server side.
@timlinux Is-it not possible to restart on rancher yet ?

@myarjunar You can still fix the issue, it should be very easy.

**Comment by Gustry** [comment]
I think you just need to remove line : https://github.com/inasafe/inasafe/blob/develop/safe/utilities/osm_downloader.py#L85 :D

**Comment by myarjunar** [comment]
> I think you just need to remove line : https://github.com/inasafe/inasafe/blob/develop/safe/utilities/osm_downloader.py#L85 :D

Argh you should not tell me, I nearly find it hahaha. :joy:  thanks anyway

**Comment by Gustry** [comment]
You should check !

Small hint, you can disable developer mode in your inasafe settings to use the not staging site : http://osm.inasafe.org You will be able to test your fix

**Comment by Gustry** [comment]
http://staging.osm.kartoza.com is up again.

Are you working on this issue ?

**Comment by myarjunar** [comment]
@Gustry ah I'm sorry, been afk for a while. Cool, it's working now.

**Comment by myarjunar** [comment]
closed in https://github.com/inasafe/inasafe/pull/3756

**Comment by timlinux** [comment]
@Gustry We can deploy it easily in rancher I think. But for now just spin it up manually as I will get lost in a pile of docker tweaks otherwise...
