### ISSUE TITLE
We have keywords.db and metadata.db, we need to remove one

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3751]
### Problem

We have metadata.db : https://github.com/inasafe/inasafe/blob/develop/safe/metadata/metadata_db_io.py#L61

And keyword.db : 
https://github.com/inasafe/inasafe/blob/develop/safe/utilities/keyword_io.py#L249

### Expected Behaviour
We should remove one I think. @ismailsunni Can you confirm ?

**Comment by ismailsunni** [comment]
I think we use metadata.db, let me check again after feature freeze.

**Comment by Gustry** [comment]
In inasafe options, my settings is keywords.db, I don't know if the value by default : 
![screen shot 2017-02-23 at 14 37 01](https://cloud.githubusercontent.com/assets/1609292/23261238/a8b7aa38-f9d5-11e6-8672-a5a60c808a57.png)
