### ISSUE TITLE
We need to manage ratios in the aggregation layer

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3763]
### Expected Behaviour
![screen-shot-2017-01-25-at-9 25 16-am](https://cloud.githubusercontent.com/assets/1609292/22543910/f099a288-e932-11e6-88be-5f7205e93ba1.png)

* Hazard no count, no ratio.

* Vector Exposure can have counts : 
  * Exposure Population : female, youth, adult, elderly
  * Exposures Road/Building/Landcover : value
* Vector Exposure can have ratios : 
  * Exposures Road/Building/Landcover : rate
* Raster exposure can have nothing. How do we choose if we want to use the global inasafe ?

* The aggregation can have ratios as well : 
  * Female, Youth, Adult, Elderly

* InaSAFE has ratios : 
  * Ratios : Youth, Adult, Elderly, Female, Rate

When we use a postprocessor, the priority is : 
* Exposure count
* Exposure ratio
* Aggregation ratio
* Defaults ratio

**Comment by ismailsunni** [comment]
Based on my discussion with @Charlotte-Morgan 
For ratio, we will use one of the two options below:
- Use default value (need to create new field in the attribute table)
- Use the data in the attributes tables as it is (No need to replace `None` or empty value)

**Comment by timlinux** [comment]
Just a note that in Jakarta in Jan 2017 we discussed that the behavior for defaults should be:

If a column is selected for a ratio e.g. female ratio, the values in that column should be used exclusively - defaults should not be used when no data is encountered.

Same thing as @ismailsunni is saying above but expressed in different words.

**Comment by Gustry** [comment]
![screen shot 2017-02-08 at 11 33 24](https://cloud.githubusercontent.com/assets/1609292/22733559/8504da00-edf2-11e6-8946-680c3e05b737.png)

**Comment by Gustry** [comment]
Can you please check, I'm confused @timlinux @ismailsunni

![screen shot 2017-02-08 at 11 33 51](https://cloud.githubusercontent.com/assets/1609292/22733572/90eb2fc2-edf2-11e6-8429-59e0afc9f415.png)

**Comment by timlinux** [comment]
This is my take on how the logic works, maybe it is easier to read:

![inasafe4 0architecturedetailedarchitecture](https://cloud.githubusercontent.com/assets/178003/22737094/3403c0d6-ee0a-11e6-9bef-ed8b371e14c9.png)

**Comment by timlinux** [comment]
To honor nulls means that we will not 'fill in' null values from global or aggregation defaults.

**Comment by Gustry** [comment]
First PR #3808 
Next PR coming : #3815

**Comment by Gustry** [comment]
Graph tha we made with Tim : 
![inasafe4 0architecturedetailedarchitecture](https://cloud.githubusercontent.com/assets/1609292/22856309/21aa4f86-f08f-11e6-87ad-1adcc83132f2.png)

This should be fixed in these 2 PR above.
