### ISSUE TITLE
Better definitions Function

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3770]
### Problem
Currently we have this `definition` function to get the full definition from a key. So far so good, until we have two definition which have the same key. It was unit `generic` in units.py and `generic` in hazards.py.

It's not good since we can get the wrong definition.

### Expected Behaviour
We should have a better mechanism to get the full definitions

### Proposed Solution
One of the solution is updating the method to have new parameter, that wil give the function a file to check the definitions. For example
```
def definition(definition_file, keyword):
    pass
```
Then we will need to list all of the file, and put them as a variable, for example:
```
UNITS_FILE = 'units.py'
HAZARDS_FILE = 'hazards.py'
```
By doing this, we can do the refactoring easily in the future

cc @Gustry @timlinux @lucernae @myarjunar

**Comment by Gustry** [comment]
Thanks, it was scary for me this `definition` function ;-)

**Comment by timlinux** [comment]
Yeah this is why I suggested before that we should use a naming scheme that makes all keys unique. Also that we should have a unit tests that fails if we find two keys the same. I prefer this approach to having a second parameters as we will still have hell if we move definitions between files.

I can help to come up with a better naming scheme for keys....

**Comment by ismailsunni** [comment]
> Yeah this is why I suggested before that we should use a naming scheme that makes all keys unique. Also that we should have a unit tests that fails if we find two keys the same. I prefer this approach to having a second parameters as we will still have hell if we move definitions between files.

Ah yes, I didn't thought that there is a case to move definitions....

I prefer to use a naming scheme now

**Comment by ismailsunni** [comment]
In the meeting we decided to review all the keys and make sure to avoid conflict. We will improve it later in the next version.
