### ISSUE TITLE
Tsunami on Population: displacement rates

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3779]
Following discussion with Tsunami hazard experts; please assign the following affected status and displacement rates for tsunami hazard classes in #2907

The same rates apply regardless of the 3 or 5 class classification

![image](https://cloud.githubusercontent.com/assets/5743135/22678127/df395912-ed4b-11e6-932f-1c3565fa83db.png)

**Comment by Gustry** [comment]
I did it in the PR above @Charlotte-Morgan
