### ISSUE TITLE
InaSAFE help enhancement

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3780]
It would be great to be able to minimise the help window or click outside it to interact with the main window without having to close the help each time

**Comment by Gustry** [comment]
For now @Charlotte-Morgan, you can right click on the page and choose `Open in webbrowser`.

@myarjunar Can you have a look to this issue ?

**Comment by ivanbusthomi** [comment]
I also noticed that everytime I open help, it creates new temporary file instead of calling already created one. Is it intended?

![image](https://cloud.githubusercontent.com/assets/7351977/22686603/4a27363a-ed57-11e6-8b09-73db6cd1fc79.png)

**Comment by Gustry** [comment]
Yes, I guess this is not a problem. And it's easier for us to create a new one.

**Comment by Gustry** [comment]
We can also on the right click menu save it as a PDF.

**Comment by timlinux** [comment]
It only creates that file if you use the open in browser context menu. Its not a problem if it does that, your OS should clean that away again....
