### ISSUE TITLE
Wizard : Improvements when we select the name field in the aggregation layer

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3786]
### Problem

In this step, we need to select a field which should be unique.

![screen shot 2017-02-07 at 10 34 47](https://cloud.githubusercontent.com/assets/1609292/22685600/38abb312-ed21-11e6-93ac-57d10e8d0e53.png)

### Expected Behaviour

It could be helpful we can know the number of features in the layer and also the number of unique values. We will quickly notice of this field is a kind of ID.
The same would be very nice when we have to select exposure ID, aggregation ID, hazard ID.

**Comment by Gustry** [comment]
Thanks Ismail for this first step.

I'm just thinking about exposure ID, hazard ID, aggr ID, can't we add the field name plus a number with brackets (or percent) and italic in the combobox?

**Comment by ismailsunni** [comment]
Yes, I am thinking the same solution also for that. I think it's possible to do it. I will try to implement it.

**Comment by ismailsunni** [comment]
Hi @Gustry 
Can you elaborate or give example regarding your comment:
> I'm just thinking about exposure ID, hazard ID, aggr ID, can't we add the field name plus a number with brackets (or percent) and italic in the combobox?

Is it something like : _aggregation_id (18)_
What about the `%` ?

I am sorry, I understood you comment on Aug, but not now :)

**Comment by Gustry** [comment]
In the combobox, to display the field name plus the percentage of uniqueness of this field.
If we display only the number, we still don't know if it's very unique or not, so not the best.

This is my combobox and fields available in this combobox for my district aggregation layer:
```
QComboBox: Aggregation field ID
-> country_name(1%)
-> province_name(20%)
-> district_name(100%)
-> district_id(100%)
```

We would need a sentence in the help string about this percent.

Does it make sense?

**Comment by ismailsunni** [comment]
Hmm, quite strange for me to use percentage to represent the uniqueness. Can we just use `number_of_unique_value / number_of_feature` ? e.g. `country_name (100/108)`. Or is it important to know the degree of uniqueness? I thought it's either unique or not.

**Comment by Gustry** [comment]
Yes, go for it! It's better ;-)

**Comment by ismailsunni** [comment]
Ouch, it turns out not so straight forward since we use the name of the combo box name directly. In order to change this, I need to modify SelectParameter and SelectParameterWidget to add `shown option` or something like that and store the value as data. I will move it back to backlog.

**Comment by ismailsunni** [comment]
Duplicate in #3765. I will close this ticket and use that one, since the title is more suitable.
