### ISSUE TITLE
Wizard : multi hazard classification

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3789]
### Problem

* [x] 1 : What does `No classification` mean ? We should not be able to launch an IF according to the exposure in the dock and wizard if the user didn't set this exposure in the hazard keywords ?
For now, it will raise an exception if you launch an IF with an exposure which has not been defined.
![screen shot 2017-02-07 at 10 43 09](https://cloud.githubusercontent.com/assets/1609292/22685861/3f87855c-ed22-11e6-843f-58bdf51adaff.png)

* [x] 2 : Should we be able to click `Next` if there is no hazard classification ? (screenshot above). We will get an empty value_map : 
![screen shot 2017-02-07 at 10 20 51](https://cloud.githubusercontent.com/assets/1609292/22685931/8ce5865a-ed22-11e6-8055-3402aa2bb004.png)

* [x] 3 : Same question when we start editing a value map : 
![screen shot 2017-02-07 at 10 18 01](https://cloud.githubusercontent.com/assets/1609292/22686035/ef98b894-ed22-11e6-9c57-e240a7942ac8.png)

* [x] 3 : Bug if we press `save` and `edit` again. It will not display the value map that we did just before.
![value_map](https://cloud.githubusercontent.com/assets/1609292/22685958/a9a0ff9a-ed22-11e6-98bf-6bff868e1a19.gif)

* [x] 4 : What is this small `1` ?
![screen shot 2017-02-07 at 10 15 43 copy](https://cloud.githubusercontent.com/assets/1609292/22686252/a653f800-ed23-11e6-87c0-c6fae0b2c874.png)

* [x] 4 : What is the button `Load default`, I tried, nothing happened on my laptop.
![screen shot 2017-02-07 at 10 15 43](https://cloud.githubusercontent.com/assets/1609292/22686134/3c440464-ed23-11e6-9299-692e1bdac229.png)

* [x] 5 : I don't think it's a good idea to display definitions. The user is thinking where does this come from. I think it's confusing to display Kawasan Rawan Bencana, especially when I use InaSAFE outside of Indonesia. And these values are not in my attribute table. 
![screen shot 2017-02-07 at 10 56 19](https://cloud.githubusercontent.com/assets/1609292/22686377/3fa63e8c-ed24-11e6-9a2a-62e9f4ffebcb.png)

* [x] 6 : If we set every classification to `Not Used` I think the wizard keeps the existing value map already set before. At the end of this GIF, my value map should be empty : 
![value_map](https://cloud.githubusercontent.com/assets/1609292/22686680/56c203ca-ed25-11e6-94f9-7df95c3b0915.gif)

* [x] 7 : I think `Edit` the classification should be compulsory, eg the value mapping window should open automatically when we set a classification. in my attribute table, I have `11`, `22` and `33` and I'm defining wrong keywords in my value mapping because for now I don't have to `edit`.
![value_map](https://cloud.githubusercontent.com/assets/1609292/22686789/cad32974-ed25-11e6-90d8-19f08687f51e.gif)

Sorry for this very long ticket. I didn't expect to have too many issues. This step in the wizard need some polishing IMHO. Some actions are not clear. I don't know what should be the behaviour if the user tries to launch an IF if this exposure is not defined in the hazard layer ??

**Comment by ivanbusthomi** [comment]
Hi @Gustry , maybe https://github.com/inasafe/inasafe/issues/3791 is related to this.

**Comment by timlinux** [comment]
Thanks for the detailed review @gustry. For 1 : What does No classification mean ?  - the behaviour IMHO should be that whenever there are no thresholds defined, the default thresholds should be used. Whenever there is no classification if is probably better to inform the user. I think when user is in dock or wizard and sets the exposure and hazard, we should do a runtime check to see if the classifications / thresholds are defined / consistent and if not advise them to run the keywords wizard.

**Comment by Gustry** [comment]
> I think when user is in dock or wizard and sets the exposure and hazard, we should do a runtime check to see if the classifications / thresholds are defined / consistent and if not advise them to run the keywords wizard.

So we should disable the button and display a message ? ok I will have a look

**Comment by timlinux** [comment]
Thanks @Gustry

**Comment by Gustry** [comment]
> What does No classification mean ? - the behaviour IMHO should be that whenever there are no thresholds defined, the default thresholds should be used. 

Maybe for value mapping, it makes sense. I'm not convinced, not sure.
But for a value mapping, it doesn't make any sense to use the "default value mapping". The main purpose of the value mapping is to match your attribute table with inasafe concepts. If you don't do it, the wizard is useless. Am I wrong ?

**Comment by timlinux** [comment]
> But for a value mapping, it doesn't make any sense to use the "default value mapping".

I agree - for thresholds we should be able to use defaults, for value mapping I think there are few cases where defaults would actually match user's data (perhaps one exception being for OSM downloaded data).

**Comment by Gustry** [comment]
>  I think there are few cases where defaults would actually match user's data (perhaps one exception being for OSM downloaded data).

Yes, but the value mapping is done automatically if some field names match. Isn't it @ismailsunni ?

**Comment by ismailsunni** [comment]
Thanks so much @Gustry I will check one by one :)

**Comment by ismailsunni** [comment]
> Thanks for the detailed review @gustry. For 1 : What does No classification mean ? - the behaviour IMHO should be that whenever there are no thresholds defined, the default thresholds should be used. Whenever there is no classification if is probably better to inform the user. I think when user is in dock or wizard and sets the exposure and hazard, we should do a runtime check to see if the classifications / thresholds are defined / consistent and if not advise them to run the keywords wizard.

From my side, it's more convenient for user to see message, "You can't run this analysis because you don't have classification / thresholds / value maps for this EXPOSURE in you HAZARD layer".
By doing this, we can avoid user to run analysis without knowing what's the thresholds / value maps.

**Comment by ismailsunni** [comment]
> Yes, but the value mapping is done automatically if some field names match. Isn't it @ismailsunni ?

Yes, we did it for the user, if possible.

**Comment by ismailsunni** [comment]
- Solution for poin 1, 2, 3a, 6:
User no longer able to choose no classification and click next. Shoul avoid the problem.
- Solution for poin 3b:
Fixed
- Solution for poin 4:
Temporarily hide it. I am not sure this is a blocker. I prefer to work on the other blocker issue. Comments are open :)
- Solution for poin 7:
Open edit panel directly after changing combobox.

**Comment by ismailsunni** [comment]
4a : remove the number 1. Keyword: header.

**Comment by ismailsunni** [comment]
End note:
After discussion with @Gustry , we agree to remove all cancel button, so that the behaviour would be natural when opening edit panel from edit button or changing the combo box.

All is done, the PR is merged. Closing this.
