### ISSUE TITLE
Hazard thresholds information in dock is not properly styled.

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#3791]
### Problem
I noticed that after we implemented the new thresholds, the dock shows it without a style. I think it is a little bit hard for the user to understand.
![image](https://cloud.githubusercontent.com/assets/7351977/22687045/13576efc-ed59-11e6-8767-fdae59896f95.png)

### Expected Behaviour
The dock should show the thresholds nicely :smile: 

### Environment
* InaSAFE : 4.0 develop
* QGIS : 2.14.10
* OS : Windows
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :

### Proposed Solution
The one in the keywords creation wizard is great. I think it would be great if it also implemented in the dock
![image](https://cloud.githubusercontent.com/assets/7351977/22687204/a3bdd846-ed59-11e6-80d4-a58c8860f261.png)
___
CC: @ismailsunni @Gustry  @timlinux @samnawi @felix-yew @Charlotte-Morgan @fredychandra

**Comment by Gustry** [comment]
Thanks, I forgot to put this one in my big ticket.
@ismailsunni is already aware about this issue.

**Comment by timlinux** [comment]
Eeesh yeah that does not look nice. @Gustry can you repurpose my logic for that from definitions_help.py?

**Comment by timlinux** [comment]
Ah sorry @ismailsunni above comment should apply to you since you are assigned.

**Comment by ismailsunni** [comment]
See also #3373

**Comment by ivanbusthomi** [comment]
I think we can close this since the dock is looking really nice when showing the hazard classifications.

**Comment by ismailsunni** [comment]
Thanks @ivanbusthomi
