### ISSUE TITLE
ValueError while generating the report

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3792]
### Problem
![screen shot 2017-02-07 at 12 02 14](https://cloud.githubusercontent.com/assets/1609292/22688608/53ba5972-ed2d-11e6-9ed4-eb3838da118f.png)

Using this dataset in debug mode.
[Dummy Data.zip](https://github.com/inasafe/inasafe/files/757351/Dummy.Data.zip)

If we don't use debug mode, we can see the exception quickly : 
![exception](https://cloud.githubusercontent.com/assets/1609292/22688714/c468e3be-ed2d-11e6-95b6-d076c59c00f7.gif)

### Expected Behaviour

* We fix this exception
* And we shouldn't hide the exception, it's more difficult to debug.

**Comment by lucernae** [comment]
Fix is on the way. Apparently char d is typed while I'm trying to Ctrl+S

**Comment by lucernae** [comment]
Should not occured anymore.
