### ISSUE TITLE
Zero result in minimum needs

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#3793]
### Problem
I find the zero result in minimum needs analysis when I run the Maumere tsunami raster on population raster, but there is a result in affected summary. Please see the image below:
![image](https://cloud.githubusercontent.com/assets/13621886/22688669/d6f73e18-ed5f-11e6-803c-f219f4ecf194.png)

### Expected Behaviour
The minimum needs can produce the correct result.

### Environment
* InaSAFE : v.4.0 dev
* QGIS : 2.14.10
* OS : Win 7 64-bit? 12 GB RAM
* Data used :
  * Exposure : Population raster
  * Hazard : Maumere tsunami raster
  * Aggregation : Village boundary

### Proposed Solution
Make it happy :smile: 

### Cc
@Charlotte-Morgan @timlinux @Gustry @ismailsunni @lucernae @samnawi @ivanbusthomi

**Comment by Gustry** [comment]
@felix-yew This is not a bug.

The minimum needs run on the `Displaced people`, not on the `Affected people`.
In case of a tsunami hazard, @Charlotte-Morgan provided us displacement rates to use this morning : ticket #3779 and PR #3782 

I just tried with the PR #3782, it works as expected : 
![screen shot 2017-02-07 at 12 22 22](https://cloud.githubusercontent.com/assets/1609292/22689230/4158f2c2-ed30-11e6-8f0a-c46fcf902d65.png)

**Comment by felix-yew** [comment]
Ok, we hope it will be a great result for the minimum needs result.

**Comment by Gustry** [comment]
Is this ticket still relevant @felix-yew ?

**Comment by felix-yew** [comment]
Hi @Gustry - I think the problem has been fixed in InaSAFE 4.0.1
![image](https://cloud.githubusercontent.com/assets/13621886/24987396/de3ff262-2029-11e7-83a5-cf0ba40d0909.png)

Thank you :pray:
