### ISSUE TITLE
Bug InaSAFE report not totaled correctly

### ISSUE THREAD

**Issue by lrpower** [inasafe/inasafe#3799]
###Problem###
Estimated number of structures by type is not correct
![image](https://cloud.githubusercontent.com/assets/10228025/22723157/5916a59a-ee10-11e6-9c31-965f3d1adeeb.png)

###Proposed Solution###
Add up the numbers

**Comment by Gustry** [comment]
Thanks for the report @lrpower.
This is a side-effect from rounding at two different levels.
We compute the total from raw numbers, then we apply the rounding rule for each exposure type AND the total. This brings some discrepancies.

If I run the impact function in 'debug mode',  we can notice the calculation is correct : 
![screen shot 2017-02-08 at 09 24 29](https://cloud.githubusercontent.com/assets/1609292/22728951/c05d0bf2-ede0-11e6-9d8e-4e7a35198d2d.png)

PS @lucernae Can you disable the rounding on the exposure breakdown when we use debug mode ? Thanks

**Comment by Charlotte-Morgan** [comment]
@lrpower - i think there is a note to say that totals may not agree because of rounding. If you want to edit or can think of a better note to add to explain this - please supply some text and we can add it to the notes on reports.

**Comment by timlinux** [comment]
@lrpower and @charlotte-morgan I propose that we add this text to the rounding note to clarify things further:
```
       tr('Rounding is applied to all population values, which may cause '
           'discrepancies between subtotals and totals. Note that the '
           'row containing totals is calculated from the entire analysis '
           'area totals and then rounded, whereas the subtotal rows are '
           'calculated from the aggregation areas and then rounded. Using '
           'this approach we avoid adding already rounded numbers and in '
           'so doing compounding the rounding.'),
```
