### ISSUE TITLE
We should disable radio buttons if a field is selected.

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3809]
### Problem
![screen shot 2017-02-09 at 17 08 51](https://cloud.githubusercontent.com/assets/1609292/22791710/9c1de90e-eeea-11e6-9969-81670d252927.png)

It's confusing to have radio buttons enabled if we set a field.

### Expected
Correct me if I am wrong : 
* If a field is selected (different than 'No Field') -> Disable every radio buttons, remove the checked radio button, even if it's disabled.
* If 'No field' is selected, enable every radios buttons, set 'Do not use' by default

**Comment by myarjunar** [comment]
sorry, which dialog is this? @Gustry @ismailsunni

**Comment by ismailsunni** [comment]
@myarjunar it is keyword wizard, in InaSAFE Default Step.

@Gustry yes, I agree with this behaviour, same one with I discussed with @Charlotte-Morgan and I put in the #3579 

Do you want to work on it @myarjunar ?

**Comment by Gustry** [comment]
We can close this one. Thanks @myarjunar !

**Comment by myarjunar** [comment]
closed in #3813
