### ISSUE TITLE
Attribute Error : landslide hazard with population vector

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#3814]
### Problem
I find an attribute error when I try to run the landslide vector in Nagekeo with population vector. 
```
Problem

The following problem(s) were encountered whilst running the analysis.

AttributeError
Suggestion

You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/inasafe/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Details
These additional details were reported when the problem occurred.

'NoneType' object has no attribute 'isGeosEmpty'
Diagnostics

In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1008, in run self._run()
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1164, in _run self.gis_overlay_analysis()
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1250, in gis_overlay_analysis self.aggregate_hazard_preparation()
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1465, in aggregate_hazard_preparation self._aggregate_hazard_impacted = union(self.hazard, self.aggregation)
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 93, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/yanuaf/.qgis2/python/plugins\inasafe\safe\gis\vector\union.py", line 247, in union if res_geom.isGeosEmpty() or not res_geom.isGeosValid():
```

### Expected Behaviour
The analysis can work properly.

### Environment
* InaSAFE : InaSAFE v.4 develop
* QGIS : 2.14.10
* OS : Win. 7
* Data used :
  * Exposure : population vector
  * Hazard : landslide risk
  * Aggregation : no

### Proposed Solution
Make it happy :smile: 

### Cc
@Charlotte-Morgan @timlinux @Gustry @ismailsunni @lucernae @fredychandra @samnawi @ivanbusthomi

**Comment by Gustry** [comment]
It seems we still have some problem with the union algorithm from QGIS. Some geometries are None.

CC: @wonder-sk

**Comment by wonder-sk** [comment]
Were the input geometries valid? If so, would be good to see a minimal reproducible case.

One thing I am aware of where the alg output may be incorrect is when union produces geometry collection (e.g. a polygon and a linestring) but it looks like here the returned geometry is null, suggesting invalid input.

**Comment by Gustry** [comment]
@felix-yew Can you share your data ?

We made a step before the union to make the layer clean. I can check once the data is provided.

@wonder-sk The error comes from : https://github.com/inasafe/inasafe/blob/develop/safe/gis/vector/union.py#L247 so the geometry is not straight from inputs. There were already some computations on the geometry, which may lead to a None geometry, isn't it ?

**Comment by ivanbusthomi** [comment]
Hi @Gustry and @felix-yew ,
I tried today using landslide and population vector. I don't receive any error and got the result. Maybe it has been fixed?
![image](https://cloud.githubusercontent.com/assets/7351977/22963269/c3988c34-f384-11e6-8a43-5db87b81cf30.png)

**Comment by felix-yew** [comment]
Hi @Gustry - sorry for the delay response. I still find the Attribute Error in this morning. This is the data that I use for analysis

- Exposure : population vector [NGK_population_vector_SP10_BPS.zip](https://github.com/inasafe/inasafe/files/778931/NGK_population_vector_SP10_BPS.zip)
- Hazard : landslide risk [NGK_Landslide_Risk.zip](https://github.com/inasafe/inasafe/files/778934/NGK_Landslide_Risk.zip)

Make it happy :smile:

**Comment by Gustry** [comment]
@timlinux made a fix : https://github.com/inasafe/inasafe/pull/3672/files#diff-e0f739584700d8aa0080c5b55c8a6d95R247

**Comment by Gustry** [comment]
@timlinux I'm giving you this one as it's in your PR

**Comment by timlinux** [comment]
Thanks @Gustry - note that I only fixed on case - maybe we should treat the other the same....

**Comment by Gustry** [comment]
What are the others @timlinux ?
What you did was maybe a hack to overpass the error. Maybe this geometry was needed.

**Comment by Gustry** [comment]
@felix-yew Do you still have the issue ? Can we close the ticket ?

**Comment by felix-yew** [comment]
Hi, @Gustry - sorry, for late response
![image](https://cloud.githubusercontent.com/assets/13621886/23443171/86088398-fe5f-11e6-9f2c-36b6de54d10e.png)
LGTM :+1: it work, thank you
