### ISSUE TITLE
When generating reports, the QPT should be made available to the user

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3822]
### Problem

When we generate the PDF's  for reports, please also generate and provide links to the QGIS composer templates:

![screen shot 2017-02-13 at 11 19 21 am](https://cloud.githubusercontent.com/assets/178003/22877505/592d8824-f1de-11e6-8968-21d77ee2bdd6.png)

**Comment by lucernae** [comment]
So, I assume I only need to provide the links for now/
