### ISSUE TITLE
IF Wizard should skip extent selector if an aggregation layer is provided

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3827]
### Problem
![aggregation](https://cloud.githubusercontent.com/assets/1609292/22888578/8db07d72-f206-11e6-9106-31b1350674e0.gif)

If the user has an aggregation layer in the IF wizard, then user shouldn't be able to use the extent selector dialog.

**Comment by timlinux** [comment]
Thanks - I agree it doesn't make sense.

**Comment by ismailsunni** [comment]
Fix in #3843
