### ISSUE TITLE
Enable size rate postprocessor

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3828]
### Problem
In V4.0, we started a size rate postprocessor.
Before the release, we decided to rollback a little bit and to disable it for 4.0.

It seems we need to improve it before to release it. (for 4.1).
* The cost should be at the exposure classification.
* It doesn't make sense to use a global default for value (100000) https://github.com/inasafe/inasafe/blob/develop/safe/definitions/default_values.py#L25

Moreover, @fredychandra gave some nice inputs about landcover. We would need him to design the architecture.

**Comment by timlinux** [comment]
I agree we should disable it and do a similar process to ratios to properly define the workflows.

**Comment by Gustry** [comment]
Now it has been disabled. I'm gonna update the ticket to ask to enable it

**Comment by ismailsunni** [comment]
Can we close this @Gustry ? The land cover productivity is using size rate
