### ISSUE TITLE
Minimum needs for entire displaced population should be shown in report

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3835]
### Problem

In our walk through today @Charlotte-Morgan noted that minimum needs reporting is only showing for the aggregation areas, but we don't have one for the entire analysis area. Please add a table with minimum needs for all displaced people above the aggregation area break down minimum needs.

**Comment by lucernae** [comment]
It should be in the report already. can you tell me the combination?

**Comment by timlinux** [comment]
Ah sorry you are right:

![2017-02-13 23_58_38-inasafe](https://cloud.githubusercontent.com/assets/178003/22905295/71d95ba4-f248-11e6-99c1-4bdef9558631.png)

Thanks @lucernae

**Comment by Charlotte-Morgan** [comment]
Um - sorry, I do not see a min needs report if there is no aggregation in the screenie above. But it is working now thank you

**Comment by lucernae** [comment]
there should be two minimum needs section if we use aggregation. both will not show up if all minimum needs zero. then, only one section will show up (for total area) if no aggregation used.
