### ISSUE TITLE
Wrong HTML page if we open in webbrowser

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3841]
### Problem

In the IF wizard, if we click 'Generate PDF', we get this new screen : 
```
Map Creator

Your PDF was created....opening using the default PDF viewer on your system. The generated pdfs were saved as:
```
but then, if we press open in webbrowser, we get the HTML page, I was expecting the report.

![open_pdf](https://cloud.githubusercontent.com/assets/1609292/22908671/15618b14-f250-11e6-868e-918447cd4d9a.gif)

This is not a big bug.

**Comment by Charlotte-Morgan** [comment]
@Gustry is this still a bug

**Comment by Gustry** [comment]
This is fixed. Especially in 4.3 the "print" has been updated a lot.
