### ISSUE TITLE
User warning: exposure specific thresholds not set

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3845]
### problem ###
In InaSAFE 4.0 when I load flood raster (Jakarta 2007) which does not have exposure specific thresholds defined in key words - I do not get a warning to say that key words need to be updated.
![image](https://cloud.githubusercontent.com/assets/5743135/22911642/561417a6-f293-11e6-859f-5e8453ed30e4.png)

ie the user does not know why the run button is not active in the dock.

### proposed solution ###
add a user warning to say that key words need to be updated

**Comment by Gustry** [comment]
The dock has many panels. Some of them are triggered by clicking on a layer, some are  triggered by pan&zoom, some by changing combobox in the question area.

So it is already done @Charlotte-Morgan but maybe you clicked on a layer, so it will show layer keywords. If you pan/zoom, it will display again the incompatibility between exposure/hazard.

**Comment by Charlotte-Morgan** [comment]
thanks @Gustry - i saw this warning now

**Comment by Gustry** [comment]
Unfortunately, these messages are not centralised in one file.
You will find a lot in safe/impact_function/impact_function.py between lines L665 and L1097.
This warning message you are talking about is L811 : https://github.com/inasafe/inasafe/blob/develop/safe/impact_function/impact_function.py#L811

**Comment by ismailsunni** [comment]
So, should I do something still?
