### ISSUE TITLE
BUG: Wizard mess up when setting exposure thresholds in key words

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3846]
### problem ###
I get a python error when i try to edit valued for flood classes

Key words wizard for setting population classifications in flood hazard data (jakarta raster 2007)
![image](https://cloud.githubusercontent.com/assets/5743135/22913320/9b57ac0c-f29c-11e6-90bb-2f3d755ac837.png)

```An error has occurred while executing Python code: 

TypeError: min_max_changed() got an unexpected keyword argument 'index' 
TypeError: min_max_changed() got an unexpected keyword argument 'index'


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.14.10-Essen Essen, 057b42a 

Python Path:
C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python
C:/Users/AIFDR_ADMIN/.qgis2/python
C:/Users/AIFDR_ADMIN/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.14/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\python_dateutil-2.1-py2.7.egg
c:\osgeo4~1\apps\python27\lib\site-packages\six-1.3.0-py2.7.egg
C:\Program Files (x86)\ArcGIS\Desktop10.2\bin
C:\Program Files (x86)\ArcGIS\Desktop10.2\arcpy
C:\Program Files (x86)\ArcGIS\Desktop10.2\ArcToolbox
C:\PROGRA~1\QGIS2~1.14\bin\python27.zip
C:\PROGRA~1\QGIS2~1.14\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.14\bin
C:\PROGRA~1\QGIS2~1.14\apps\Python27
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.14\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/AIFDR_ADMIN/.qgis2//python
C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe
C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe\safe_extras\parameters
C:\Users\AIFDR_ADMIN\.qgis2\python\plugins
C:\Users\AIFDR_ADMIN\.qgis2\python\plugins\inasafe\safe_extras
C:\PROGRA~1\QGIS2~1.14\apps\qgis-ltr\python\plugins\fTools\tools
C:/AIFDR/AIFDR II - SDA/05 Test Data/InaSAFE 4.0
```

### proposed solution ###
user can set values and any test to confirm they are within range / mutually exclusive is applied with the save click not the value click

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni the edit is working well but I still get weird display. It was happy while i set classes for population then went silly whey I chose another one

**Comment by ismailsunni** [comment]
Can you explain what silly looks like?  Screenshot / gif is better if possible
Unfortunatelly, I can't replicate the error.

**Comment by Charlotte-Morgan** [comment]
Hi @ismailsunni - the python error is fixed. I still have a problem with the display in this step of the wizard. Its the same as the screenie above and again replicated today.
![image](https://cloud.githubusercontent.com/assets/5743135/22958905/c8cf6936-f364-11e6-8c0a-61d9e74ed31b.png)

When I get to the wizard screen to set exposure specific thresholds for each hazard the screen is fine.
When I select the drop down to set flood classes for population exposure the screen ends up with lots of overlapping text. This is what we have been saying is wierd or silly.

I can continue to work with the wizard and set classification for another exposure etc; but eventually the list of set elements extends off the page and I do not have a scroll bar for the thresholds; only the status panel in the wizard window
![image](https://cloud.githubusercontent.com/assets/5743135/22958985/60580ae2-f365-11e6-9acf-14e4201c1d8c.png)

This is happening on 2 different windows machines; both with QGIS 2.14.10 and InaSAFE dev.
I am happy to show you via zoom if that helps

**Comment by ismailsunni** [comment]
Hmm, strange, I tried again this morning, followed your scenario, but still not get the problem.
Yes, showing via zoom can help :) Let me know if you are ready to show :D

**Comment by ismailsunni** [comment]
Assign this to @timlinux since he is the Windows-User now :)

I tried in Windows, it seems, it's Windows specific indeed.

**Comment by myarjunar** [comment]
It happens on Ubuntu as well :sweat_smile:

**Comment by Gustry** [comment]
@myarjunar So you can work on it too ;-)

**Comment by myarjunar** [comment]
It would be good if you could test it in windows @timlinux

**Comment by timlinux** [comment]
It works beautifully now:

![screencapture](https://cloud.githubusercontent.com/assets/178003/23262713/56aaf222-f9e4-11e6-8fac-bbed86dc489e.gif)

**Comment by Charlotte-Morgan** [comment]
Sorry - this much better but still having problems in windows

**Comment by myarjunar** [comment]
@Charlotte-Morgan ah sorry to hear that. Does the problem remain the same on your Windows?

**Comment by Charlotte-Morgan** [comment]
hi @myarjunar - the problem is not as bad as it was but still quite messy on my windows.
I now have the scroll bar on the left, but the left and right sides of the wizard screen overlap if i chose a different classification.
![image](https://cloud.githubusercontent.com/assets/5743135/23346679/fb01944c-fcce-11e6-9d6f-38d16f182b53.png)
I am happy to demo on zoom when I am at my desk :)

**Comment by myarjunar** [comment]
@Charlotte-Morgan could you please check this again? I already merged another PR regarding this issue. Actually, I cannot replicate your problem. But, looking at your screenshot, my PR should fix the problem.

**Comment by Charlotte-Morgan** [comment]
Hi @myarjunar - this is looking much better.
Still a little squashed but nothing like the overlap issues previously.
Thanks for fixing

**Comment by Gustry** [comment]
What is the little issue? Do you have a screenshot?
Should we check deeper? or can we close the issue?

**Comment by timlinux** [comment]
@Gustry I am going to close and we can re-open if someone reports it again.
