### ISSUE TITLE
Min Max Thresholds Discussion

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3849]
### Problem
Based on my discussion with @Charlotte-Morgan this morning (14 Feb 2017), we agree that the minimum is excluded, but maximum value is included. Example:
```
Very low 0.01 - 0.1
Low >0.1 - 2
Medium >2 - 5
High >5 - 10
Very high >10
```

So, in the keyword wizard it will be:
`Min > [  ]  Max <= [  ]`

IIRC, in our current IF code, we use the reverse (include min, but exclude max). So, we need to update the code also. I am not sure if it's easy, but perhaps @Gustry knows better where to put the < or >= symbol.

Another discussion, in the hazard classification, we don't need the `small_number` anymore as long as we use the comparison consistently everywhere. So, I suggest to remove the small number.
For example:
```
'numeric_default_min': 0,
'numeric_default_max': (1 - small_number),
```

will be 
```
'numeric_default_min': 0,
'numeric_default_max': 1,
```

To Do:
- [x] @ismailsunni to update the wizard and the small_number
- [x] @Gustry  to update the IF

CC @Gustry @Charlotte-Morgan @timlinux

**Comment by Gustry** [comment]
Is-it finished @ismailsunni ?

**Comment by ismailsunni** [comment]
@Gustry almost. Waiting for #3890 to be merged.

**Comment by ismailsunni** [comment]
- [ ] Add threshold and classification in the concepts.py (@ismailsunni)
