### ISSUE TITLE
Population count and default ratios

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3851]
### problem ###
I have raster population data (haha - quess where - Jakarta) and I want to run  a flood analysis. When I set the population key words i am not asked about the default age and gender profile on my data.

If I run without aggregation data, then I do not get an age gender report or detailed min needs for this analysis.

### proposed solution ###
allow users to set age gender defaults for raster population count data

This issue was mentioned  in #3763 but not addressed

cc
@samnawi

**Comment by timlinux** [comment]
@Charlotte-Morgan in our discussion in JK in Jan we agreed to do ratios on exposure and global defaults only and not on the exposure layer. So it's not a regression its a requested enhancement :-P

**Comment by Gustry** [comment]
So the graph is not finished : https://github.com/inasafe/inasafe/issues/3763#issuecomment-279165240 right ?
We missed if it's a raster population exposure. In this case, we don't take care of aggregations ratios, right ?

**Comment by Charlotte-Morgan** [comment]
Ok. Sounds like i should not expect to set population attributes for raster population data. But the missing report implies that my global defaults were also not applied.  If they were, I should get an age gender report for any population analysis

**Comment by ismailsunni** [comment]
Hi @Gustry 
I did a chat with @Charlotte-Morgan on [February 17, 2017 5:12 PM](https://gitter.im/inasafe/inasafe?at=58a6cca40ad50ac31529d521)

So, it seems I don't need to restore the raster default ratio step in the wizard. But, we just need to make sure the result has gender report for population analysis.

cc @timlinux also.

**Comment by timlinux** [comment]
@Gustry @ismailsunni Yes correct - just make sure the defaults are read but don't add back support for defaults on the exposure layer. Thanks.

**Comment by Gustry** [comment]
I think we can close this one @Charlotte-Morgan, it has been merged in develop.

**Comment by ismailsunni** [comment]
Closing this.
