### ISSUE TITLE
Local Layer Treated as Remote Layer

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#3857]
### Problem
In InaSAFE we have two kinds of layers, local and remote. Local is the one that sit in your computer. Everything else is remote layer. 

But, in InaSAFE we only use simple checker to see if a layer is local or not : 
`self._layer_is_file_based = os.path.isfile(layer_uri)`
https://github.com/inasafe/inasafe/blob/develop/safe/metadata/base_metadata.py#L236

This method is not enough for a layer that has parameter. For example, when we do filtering. We will get something like:
`/Users/ismailsunni/.qgis2/python/plugins/inasafe/safe/test/data/hazard/flood_multipart_polygons.shp|layerid=0|subset="OBJECTID" < 1700`

So, if you have path like that, the metadata will be written in the database, not in the xml file. Sometimes, it can give error. For example if you have already xml metadata file for the layer. It won't get updated. Then it will give you an unexpected problem.

### Proposed Solution
Create a better checker whether the layer is local or remote. Or may be pass a better URI to the base metadata.

cc @timlinux @Gustry

**Comment by timlinux** [comment]
This was originally by design so that in theory a layer with a filter on it could have different keywords to another filter applied to the same layer. However I think it will be better & simpler to make it work so that we only ever regard the non-filtered part of the layer for local layers.

**Comment by timlinux** [comment]
Please just check if the dataset is a file and then ignore the filter and look for the xml next to the file
