### ISSUE TITLE
Storage library handling of multipolygons not yet right

### ISSUE THREAD

**Issue by uniomni** [inasafe/inasafe#386]
This is not a high priority as it is handled by the qgis front-end, but would be good to get right in the safe library if you have some spare time.

The code in question is 
https://github.com/AIFDR/inasafe/blob/master/safe/storage/vector.py#L457

I don't believe this really works, since a multipolygon would have to create multiple features when converted to single parts.
In the current code it still just makes one geometry and keeps the one attribute.

What is needed is an improved unittest https://github.com/AIFDR/inasafe/blob/master/safe/storage/test_io.py#L2351

which presents a small multipolygon and verifies that it gets exploded properly.

**Comment by timlinux** [comment]
Fixed in 4.0 we no longer use storage but rather QGIS Geometries

**Comment by timlinux** [comment]
@Gustry cc
