### ISSUE TITLE
Aggregation result template when using Entire Area

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#3862]
### Problem

This is what currently happens when we tries to report total affected by aggregation, if we're not using aggregation area.

<img width="1177" alt="screen shot 2017-02-14 at 23 21 10" src="https://cloud.githubusercontent.com/assets/831865/22937925/b07ba50a-f30c-11e6-844f-bb42c9825216.png">

### Question

Should we just Delete 'Total' Rows or 'Entire Area' Rows? Or perhaps hide entire table?
To illustrate, this is what happens when we're using aggregation area:

<img width="1179" alt="screen shot 2017-02-14 at 23 41 21" src="https://cloud.githubusercontent.com/assets/831865/22938697/202c73b4-f30f-11e6-8896-eef013094435.png">

CC @Charlotte-Morgan @timlinux

**Comment by Charlotte-Morgan** [comment]
Hi @lucernae - I am happy to leave it for now. I would be far more concerned that the totals are not adding up in the aggregation report.
Leaving it for now gives us a cross reference for checking totals

**Comment by lucernae** [comment]
the total in the second screenshot not adding up because of the rounding in each row.
What approach do you like to address this?
maybe add another notes?

**Comment by Charlotte-Morgan** [comment]
ah - ok.  Its more obvious with small numbers. Hopefully not such a problem with real numbers. We already have a note so I think its fine.
