### ISSUE TITLE
BUG: report rounding has disappeared

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3865]
### problem ###
Rounding in all areas of the report been replaced by values with multiple decimal places.
![image](https://cloud.githubusercontent.com/assets/5743135/22960584/69695cb0-f371-11e6-877a-944ccb219d68.png)

### expected behaviour ###
rounding is applied according to the standards.

**Comment by lucernae** [comment]
What is the scenario for this?

**Comment by lucernae** [comment]
Ah perhaps you're using debug mode? @Charlotte-Morgan

**Comment by Charlotte-Morgan** [comment]
@lucernae - i think you are right. I owe you an ice cream for sure! :)

**Comment by Gustry** [comment]
Shame, I woke up too late 🙂
