### ISSUE TITLE
Demographic groups

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3869]
Here are some thoughts on demographic variables in InaSAFE.
We set age and gender variables and generate age and gender reports. This information should help with the definition of demographic groups and the validation of values.
Most of the concepts are already defined in concepts.py but may not have been applied.
### now ###
* we have age variables:
youth
adult
elderly
these should add up to 100% or a total of 1 if presented as a ratio

* We also  gender variable:
female
this should be less than or equal to 1
ie if the data is a females only dataset then it will equal 1; if its a population dataset, expect the value to be more like 0.5

### future ###
In the future we might want to add more reports for vulnerable populations and be more inclusive in our reporting

* we might change gender to included:
female
male
unspecified
these will still add to 100% or a ratio of 1

* we might want to add vulnerable groups:
infants
elderly
disabled
we would expect this to total to less than or equal to 1

**Comment by ismailsunni** [comment]
Just a note, I have done for make the ratio's limit from 0 to 1. It's already in develop. For sum up to 1, I am still working on it. The hacky fix is not easy since we use a framework to generate the GUI.

**Comment by ismailsunni** [comment]
It will be handled nicely in the field mapping tool and field group. Closing this.
