### ISSUE TITLE
Earthquake Hazard MMI

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3874]
### problem ###
Earthquake hazard is not well defined in terms of MMI classes

### proposed solution ###
We need to make sure that MMI classes are whole numbers (no decimal places) and preferably in roman numerals.
ie in this edit option in the KW wizard - only whole numbers should be available for classified data

We need to update the Earthquake MMI classes to include a complete MMI classification where
MMI I is MMI 1
MMI II is MMI II etc

ie each class has a unique MMI value that is mutually exclusive

I believe this should be used for both classified and continuous data

**Comment by Charlotte-Morgan** [comment]
@hadighasemi - can we please discuss this when you are in Jakarta
@RikkiWeber - FYI

**Comment by hadighasemi** [comment]
Sure :)


Sent from my Samsung GALAXY S5

-------- Original message --------

**Comment by Charlotte-Morgan** [comment]
here is a source for the MMI scale descriptions
https://earthquake.usgs.gov/learn/topics/mercalli.php

**Comment by timlinux** [comment]
@Gustry, @myarjunar  and @ismailsunni I chatted with @Charlotte-Morgan about this on Friday. We probably want to include this in 4.0. The main things to do will be:

* Update the EQ Shakemap Convertor tool to create a classified raster (where half decimal on either side of the mmi level get assigned eg. 0.5 - 1.5 get reclassed as 1)
* Ideally we should prevent any smoothing or interpolation of the imported grid dataset (currently we use invdist)
* Add classifications for MMI with descriptions of each MMI and displacement rate (>=6 displacement rate = 100% for now)
* Fataility rates will be left blank - they should still come from the IF - make sure to leave a note in hazard_classification
* Update EQ IF to read the displacement rates from MMI classification rather

**Comment by Charlotte-Morgan** [comment]
I can do the "add hazard classifications with descriptions and displacement rates" if you want

**Comment by timlinux** [comment]
That would be great thanks @Charlotte-Morgan 

See also https://en.wikipedia.org/wiki/Mercalli_intensity_scale#Modified_Mercalli_Intensity_scale (I am sure you have that anyway from some more official source). We do have the hazard class colours in our code somewhere. Hopefully we will stick with those since they seem to be somewhat standard (I think USGS uses them too).

**Comment by ivanbusthomi** [comment]
Hi @Charlotte-Morgan , this is the color code that you asked. You can find it in the code in /safe/utilities/styling.py at line 564

1 white (#ffffff)
2 blue (#209fff)
3 light_blue (#00cfff)
4 cyan (#55ffff)
5 light_cyan (#aaffff)
6 yellow (#fff000)
7 light_orange (#ffa800)
8 orange (#ff7000)
9 red (#ff0000)
10 dark_red (#dd0000)
11 brown (#880000)
12 dark_brown (#440000)

![image](https://cloud.githubusercontent.com/assets/7351977/23110159/b93d8e6c-f751-11e6-8f4a-637dd599fc49.png)

**Comment by timlinux** [comment]
Chatting today with @gustry we think the fatality rate can be fetched from the definitions too because when we work with classified integer based MMI raster then the fatality rate should be a constant per MMI level. Etienne tells me this is already the case in the code.

**Comment by Gustry** [comment]
Before to do that, we need to implement many fatality rates for one hazard class : 

```
        {
            'key': 'X',
            'value': 10,
            'color': MMI_10,
            'name': tr('X'),
            'affected': True,
            'description':
                tr('Some well-built wooden structures destroyed; most masonry '
                   'and frame structures destroyed with foundations. '
                   'Rails bent.'),
            'string_defaults': ['Extreme'],
            'displacement_rate': 1.0,
            'fatality_rate': {
                'itb_bayesian': 0.0314512157378,
                'itb': 0.02,
                'pager': 0.02
            },
            'numeric_default_min': 9.5,
            'numeric_default_max': 10.5,
            'citations': [
                {
                    'text': None,
                    'link': u'https://earthquake.usgs.gov/learn/topics/'
                            u'mercalli.php'
                }
            ]
        },
```

And for Pager, we need to keep in mind this ticket : https://github.com/inasafe/inasafe/issues/3855

**Comment by Gustry** [comment]
I'm just trying to see where the Low, Medium and High come from for EQ classification : 
* For EQ on Buildings (NEXIS) : https://github.com/inasafe/inasafe/commit/bbdcea69bd142a82da20a07cd23fc0b3f742bb01

**Comment by timlinux** [comment]
I think we must just remove the low/medium/high EQ classification

**Comment by timlinux** [comment]
I am going to remove blocker for this:

-[ ] Ideally we should prevent any smoothing or interpolation of the imported grid dataset (currently we use invdist)

But:

-[ ] please lets remove the h/m/l classification

**Comment by Gustry** [comment]
I think we can close this ticket.
@timlinux Is there still something we should take care here ?
