### ISSUE TITLE
Missing some translations in exposure classification

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3887]
### Problem

Exposure value mapping is translated in the wizard : 
![screen shot 2017-02-17 at 14 44 25](https://cloud.githubusercontent.com/assets/1609292/23067439/9dc9d462-f51f-11e6-8ae5-af322cfc7ac7.png)

* But then, in the dock, it's not translated anymore, for @ismailsunni : 
![screen shot 2017-02-17 at 14 43 08](https://cloud.githubusercontent.com/assets/1609292/23067458/b189cd0e-f51f-11e6-86db-e37b32264787.png)

* Not in the attribute table too. I'm not sure I will do it. We may have accents etc in French. I will check. 
![screen shot 2017-02-17 at 14 46 17](https://cloud.githubusercontent.com/assets/1609292/23067484/e0084412-f51f-11e6-9c48-6bb943d11afb.png)

* Not in the report too. @lucernae did you take values from the attribute table ? Can you check if there is a translation available ?
![screen shot 2017-02-17 at 14 36 13](https://cloud.githubusercontent.com/assets/1609292/23067502/f0d542e0-f51f-11e6-83fe-d50ceea8980d.png)

**Comment by Gustry** [comment]
BTW, we should check that the value mapping and exposure breakdown is ordered following the exposure classification. For instance, 'Other' should always be at the bottom IMHO.  ( @lucernae  and @ismailsunni )

**Comment by lucernae** [comment]
How do we sort it? Do we have something like definition for the order?

**Comment by Gustry** [comment]
Yes we have ordering in definitions : 
https://github.com/inasafe/inasafe/blob/develop/safe/definitions/exposure_classifications.py#L43

**Comment by Gustry** [comment]
Thanks @lucernae It's working for your side.

**Comment by lucernae** [comment]
Nice!
Was translation working too?

**Comment by Gustry** [comment]
@lucernae Yes it's working fine in the Analysis Details table : 
<img width="897" alt="screen shot 2017-03-06 at 22 24 03" src="https://cloud.githubusercontent.com/assets/1609292/23630539/cf0e6818-02bb-11e7-8e79-ffdab95ce9ee.png">

But translations are still missing on the aggregation table : 
<img width="906" alt="screen shot 2017-03-06 at 22 26 15" src="https://cloud.githubusercontent.com/assets/1609292/23630577/f53cb3be-02bb-11e7-907c-e5314d08c88c.png">

It's the only thing in English in the report for now.
@myarjunar or @lucernae if you have an idea where to fix this.
Also I think we should apply the same order. "other" should always be at the end for instance. (after primary and path)

**Comment by Gustry** [comment]
Ok, I fixed the translation in the PR above. I will not try to fix the order, I'm afraid to break the summary ;-)

**Comment by lucernae** [comment]
Thanks!
So, only the order for this.

**Comment by Gustry** [comment]
Yes, in the aggregation table, it could be nice ;-)

Note for my self : I didn't check if I could do it in the QGIS layer.
