### ISSUE TITLE
Multibuffering function is inconsistent

### ISSUE THREAD

**Issue by myarjunar** [inasafe/inasafe#3893]
### Problem

Multibuffering function shows inconsistent/unexpected/unpredictable pattern and behaviour with various input order. 
![selection_022](https://cloud.githubusercontent.com/assets/11134669/23116767/e9e9e254-f77e-11e6-8077-223a23e9e62d.png)

### Expected Behaviour
Create a perfect donut for the outer layer.

### Proposed Solution
stronger unit test

**Comment by Gustry** [comment]
@myarjunar The multi-buffer algorithm takes an OrderedDict : https://github.com/inasafe/inasafe/blob/develop/safe/gis/vector/multi_buffering.py#L38

I see in your code, you are giving a `dict` and not a `OrderedDict`.
Here : https://github.com/inasafe/inasafe/blob/develop/safe/gui/tools/multi_buffer_dialog.py#L192
Just update this line of code.

Keep in mind that python dictionaries are not ordered. If you need an ordered python dictionary, you need to use a OrderedDict.

**Comment by myarjunar** [comment]
@Gustry I already updated my code with the ordered dictionary as we discussed. But the behaviour is still the same. Let me check again.

**Comment by myarjunar** [comment]
@Gustry thanks. I only sort it automatically on the view, so it was sorted descending. :sweat_smile: ready to push.
