### ISSUE TITLE
Detailed report section

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe#3898]
I had some question about this section here in reporting standard:

<img width="927" alt="screen shot 2017-02-20 at 20 17 38" src="https://cloud.githubusercontent.com/assets/831865/23126598/fedc5716-f7a9-11e6-8594-0838bfb9160e.png">

These 3 cases were seemingly very different pattern. So, I had some questions:

1. In first sample (people or population) where can I get the values for male column? Also, was it coming from postprocessors calculations? If it is, then was it a duplicate of the information in aggregation report for population (the one with female and age section)
2. In the second sample, I guess we're not favoring this one since it is covered by the third sample? So I'm assuming you want a building report where the affected column contains each hazard breakdown?
3. In the third sample, I'm assuming, we also wants columns with total affected, total not affected, and total not exposed?

**Comment by lucernae** [comment]
If it is possible, I would like to have all remain consistent. In reporting standard, the sentence/phrase: "Length of roads" does not have a unit (m) on it. So, where should we move the unit (m)?
In #2691 , there is a suggestion to put it on Road type. Is this still valid? Other option is to put it on table header, like in Affected (m).

**Comment by Charlotte-Morgan** [comment]
Hi @lucernae - i will try to add some detail.
`In first sample (people or population) where can I get the values for male column? Also, was it coming from postprocessors calculations? If it is, then was it a duplicate of the information in aggregation report for population (the one with female and age section)`
 - we do not calculate male specifically, but you can get male by subtracting female from total.

The draft tables just give an idea of how we can progress from general information to more detailed information. In some cases the data can be combined into a single table.

Maybe refer to the overall examples for an idea of how we progress from general to detailed info in a single report.
![image](https://cloud.githubusercontent.com/assets/5743135/23151799/153c6f10-f830-11e6-96b7-d01089a1d681.png)

**Comment by Charlotte-Morgan** [comment]
Regarding the question about units; number of people and buildings does not have a unit in english but a unit is required in Indonesian.
I prefer to use the unit in the table heading. You will see in the examples:
Estimated number of people 
Estimated length (m) of roads

I would not add units to type. I think it is much better to use a table title and include units there. If not it belongs with each hazard class as it is in the total in #2691

**Comment by Gustry** [comment]
@lucernae Can we close this ticket ?

**Comment by lucernae** [comment]
Yes we can close this I guess.
