### ISSUE TITLE
Extra exposure notes should be shown in definitions help

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3906]
### Problem

See comment here https://github.com/inasafe/inasafe/pull/3891#issuecomment-281034766

Currently these definitions do not make it into any reporting:

```
        'earthquake_notes'
        'earthquake_pager_notes'
        'earthquake_itb_notes'
        'earthquake_fatality_model_limitations'
```

### Expected Behaviour

Users should see these notes.

### Proposed Solution

I am going to add it into the definitions_help. We need to see it added in the IF notes too. @Gustry can you look at that? I think we might need to re-jig things so that we can know the right context to determine if the note should be displayed. Can you think of a nice approach?

CC @Charlotte-Morgan FYI

**Comment by Gustry** [comment]
This ticket is still open, great ;-)
I moved these notes to the correct file, in earthquake.py. These notes where already there.

BTW, we also need to display notes/actions are hazard/exposure specific : https://github.com/inasafe/inasafe/blob/develop/safe/definitions/hazard_exposure_notes_actions.py
I think we need to do a new section for this, right ?

**Comment by Gustry** [comment]
This is done now.
