### ISSUE TITLE
Explaining the different resolution and resampling for hazard and exposure layer in the docs

### ISSUE THREAD

**Issue by maning** [inasafe/inasafe#391]
I asked this question in the inasafe-users mailing:

> Does pixel resolution influence the impact output?
> For instance, I used a different pixres for the hazard and exposure layer.

Which Kristy replied:

> When you are combining 2 rasters - 
> If the hazard is finer than the population the population density will be re-scaled
> If the population is finer the hazard will be resampled.

I would like to add this explanation in the docs.  Currently, there are two sections this can be added:
- http://inasafe.org/user-docs/dock.html#data-conversions-when-running-a-scenario
- http://inasafe.org/user-docs/faq.html

I what section should I add them?

**Comment by timlinux** [comment]
I'm closing this. In InaSAFE 4.0 we vectorise data (except for earthquake) so the pixel dimensions should no longer be a consideration.
