### ISSUE TITLE
We should provide some notes which exposure and hazard specifics

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#3914]
### Expected Behaviour
We should be able to provide some notes which are specifics to an exposure and a hazard.
For now we can only provide notes which are hazard specific or exposure specific.

For instance, we should have some notes for earthquake on population.

**Comment by Gustry** [comment]
Closing this one, I will keep the ticket from Charlotte.

**Comment by Charlotte-Morgan** [comment]
aw - sorry @Gustry - I'm pleased we agree :)
