### ISSUE TITLE
Note on displacement should only apply to pop exposure

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3931]
### problem ###
Flood impact on building includes the following in notes:
For this analysis, the following displacement rates were used: High - 5.00%, Medium - 3.00%, Low - 1.00%, Use caution - 0.00%

### proposed solution ###
this note should only be used on pop exposure
a similar note stating thresholds for each zone would be useful

**Comment by lucernae** [comment]
> this note should only be used on pop exposure

Ok. Noted, I haven't implement that one
