### ISSUE TITLE
BUG: Impact analysis fails to run

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3941]
### problem ###
when I click run it goes away thinks and then comes back and tells me to click run again

### environment ###
QGIS 2.14.10
windows
InaSAFE dev 4.0

### data ####
Aceh earthquake raster
inaRISK population raster
BPS village boundaries - much larger extent than hazard and exposure

![image](https://cloud.githubusercontent.com/assets/5743135/23267076/3bbe9e7c-fa1c-11e6-978f-67a0b0e1b815.png)

### proposed solution ###
click run returns analysis results or a nice error message :)

**Comment by Gustry** [comment]
@Charlotte-Morgan Can you give your logs ? It means something went wrong in the IF.

And the issue about nothing has been displayed, it's already fixed in my PR #3940 !

**Comment by Gustry** [comment]
Can you give some inputs @Charlotte-Morgan ?
Without any logs, we can't really know what was the issue.
Thanks.

**Comment by Charlotte-Morgan** [comment]
hi @Gustry - I think we already discussed and there was nothing in the log?
I'm not going to have time to look at this again until late next week

**Comment by Gustry** [comment]
Ok, so I'm closing this ticket. Feel free to open a new ticket with every python error you can get ;-)
