### ISSUE TITLE
Map Extent is Too Large in the PDF Map

### ISSUE THREAD

**Issue by uswatunkh21** [inasafe/inasafe#3944]
### Problem
Map extent is too large in the printed (PDF) map. The extent is based on exposure layer, instead of the analysis area. It happened only when I ran scenario with population layer exposure, either with or without aggregation.
[a4-landscape-blue.pdf](https://github.com/inasafe/inasafe/files/798630/a4-landscape-blue.pdf)

### Expected Behaviour
Map extent in printed (PDF) map should be the same with extent in analysis area.

### Environment
* InaSAFE : 4.0
* QGIS : 2.14.8
* OS : Windows 10
* Data Used :
  * Hazard layer : both  Jakarta_flood_HKV.tif  and Jakarta_flood_18113_WGS84.shp
  * Exposure layer : Java_Population_WGS84.tif

**Comment by lucernae** [comment]
Should be fixed by now
