### ISSUE TITLE
Wizard thresholds editor leaves combo in greyed out state

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#3945]
### Problem

Bug in wizard when assigning thresholds on pop:

* When editing the thresholds for tsunami on pop, after pressing  save the combo remains greyed out
* On windows when editing exsiting keywords for tsunami, editing the pop thresholds leaves the html content behind the widgets.

![screencapture](https://cloud.githubusercontent.com/assets/178003/23355726/cebb0eb6-fcdf-11e6-80ee-25c4ff6182f9.gif)

### Expected Behaviour

Greyed out combo box should only happen for EQ pop thresholds.

### Environment
* InaSAFE : 4 dev
* QGIS : 2.14.11
* OS : Win 10
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard :  E:/Sync/data.inasafe.org/InaSAFE 3.5 Training Data/West Sumatera/West Sumatera/01 Hazard Data/Padang_Tsunami_Hazard_WGS84.tif
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [x] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? btsync

**Comment by myarjunar** [comment]
closed in #3952
