### ISSUE TITLE
Landcover Classification

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#3947]
### Problem
We need to make the classification for landcover exposure match with the volcanic ash landcover classification. The landcover classification came from Badan Geologi.
![lc](https://cloud.githubusercontent.com/assets/178003/14305277/e0fd1d78-fbe4-11e5-80ae-b92335877840.png)
We might also need to automatically assign the value map from BIG landcover data to the classes because the value in BIG land cover data has already been standardised using either the Remark Field or the FCODE field.
![image](https://cloud.githubusercontent.com/assets/7351977/23359852/d96dee4c-fd1a-11e6-9a3b-60a7a6a998e8.png)

### Expected Behaviour
the landcover classification matches the Badan Geologi classification.

### Environment
* InaSAFE : 
* QGIS : 
* OS : 
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 

### Proposed Solution
Maybe by adding new land cover classification. This is the volcanic ash landcover classification and the value map for BIG land cover data

| Value Map      | Remark | FCODE
| -------------    | ------------- | ------------- |
| Settlement      | Permukiman dan Tempat Kegiatan | 50102 |
| Rice Field        | Sawah | 50306 |
| Plantation       | Perkebunan / Kebun  | 50304 |
| Water Supply  | Air Danau / Situ, Air Empang, Air Penggaraman, Air Tambak, Air Tawar Sungai, Air Waduk, Perairan Lainnya | 50404, 50420, 50418, 50416, 50408, 50406, 50400|
| Forest              | Hutan Rimba  | 50202 |

**Comment by Gustry** [comment]
I put the label release blocker because I though it was. If it's not, you can remove it. Should we go with this classification ? Should we remove the old one ?

**Comment by ivanbusthomi** [comment]
Hi @Gustry,
I am thinking maybe we can just add another classification for BIG landcover, and make it automatically value mapped if using the remark or FCODE field based on the table above.
And I believe it is not a release blocker. What do you think @Charlotte-Morgan ?

**Comment by Gustry** [comment]
Yes, good.
Do you want to do it @ivanbusthomi ?
You need to add new classification here : https://github.com/inasafe/inasafe/blob/develop/safe/definitions/exposure_classifications.py
(CC @myarjunar )

**Comment by Gustry** [comment]
Check #3626

**Comment by myarjunar** [comment]
is it ok if I named it `badan_geologi_landcover_classes`? @ivanbusthomi @Gustry

**Comment by ivanbusthomi** [comment]
@myarjunar yeah I think so.
