### ISSUE TITLE
InaSAFE action list

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3960]
We should separate the action checklist as its own report.
This would allow us to restyle the report with actions by sector.
See #3057

**Comment by ivanbusthomi** [comment]
This is a mock up that I proposed for separating the action checklist.
![image](https://cloud.githubusercontent.com/assets/7351977/23978454/a6daa65a-0a26-11e7-93cb-95a5544efacb.png)

The 5 sections are based on the Sphere Project minimum standard.
