### ISSUE TITLE
We need notes and actions for specific hazard exposure combinations

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3961]
Proposing we are able to add notes or actions for specific hazard exposure combinations.  ie the following action is for people exposed to volcanic ash

    'volcanic_ash_actions': [   # these are volcanic ash specific actions
        tr('Do you have enough masks for people in the affected area?'),
    ],
 see exposure.py

**Comment by Gustry** [comment]
Duplicate of #3914

**Comment by Gustry** [comment]
This possible in PR #3968
