### ISSUE TITLE
Displacement rate note should only appear for population exposure

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3962]
currently the displacement rate note appears for all exposures. It should only appear for population exposure

**Comment by Gustry** [comment]
Do you see these displacement ratios in reports or in QGIS layers ? Or both ?

**Comment by Charlotte-Morgan** [comment]
I am looking at the pdf report and i see a note that is not relevant to the exposure data

![image](https://cloud.githubusercontent.com/assets/5743135/23399952/cefa6ad4-fdd4-11e6-9374-007c66dcb980.png)

This note is in a report for buildings

**Comment by lucernae** [comment]
duplicate of #3931. Shouldn't it be fixed by now? I already merged PR for this.

**Comment by Gustry** [comment]
I think this ticket is fixed, I didn't see it anymore. Thanks @lucernae
