### ISSUE TITLE
InaSAFE report column order

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3964]
### problem ###
the detailed report for buildings and roads could be simplified a little by changing the order of columns and making good use of double headers
![image](https://cloud.githubusercontent.com/assets/5743135/23399319/66875446-fdd2-11e6-8bca-356a66dbe548.png)

### proposed solution ###
the total affected column is placed with the other affected columns
ie under the affected heading will be three columns: high, medium, total

the total not affected should be placed with the other not affected columns
ie under not affected will be three columns low, dry and total

we add a new top level heading total
under that we have 2 columns; not exposed and exposed

![image](https://cloud.githubusercontent.com/assets/5743135/23399554/35714456-fdd3-11e6-9f73-32bff8c624e2.png)

this makes good use of double headings and keeps totals in relevant places

**Comment by ivanbusthomi** [comment]
I created some mockups based on @Charlotte-Morgan paintings :smile:. And just to confirm, it might be based on previous result where we still have `hazard zone` in the classification table.
Let me know if I missed any point :smile: 
![image](https://cloud.githubusercontent.com/assets/7351977/23400734/8aea8330-fdd7-11e6-9487-4b4a52bd3e3e.png)

**Comment by lucernae** [comment]
We don't yet have total exposed in the qgis layer.
Otherwise, it's possible.

**Comment by myarjunar** [comment]
closed in #4142
