### ISSUE TITLE
BUG: gdal.exe window pops up

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#3980]
when i run earthquake raster on pop raster the dgal.exe window pops open and then closes.

Solution: this should not be visible to users

**Comment by Gustry** [comment]
@timlinux @Charlotte-Morgan Can you try on windows if you still have this issue ?

**Comment by Charlotte-Morgan** [comment]
I had this again on 4.0.0 yesterday - ie using master version

**Comment by Gustry** [comment]
I meant on develop, if you pulled this morning. It will be in 4.0.1 if it's working

**Comment by Gustry** [comment]
Can you check if you still have this window @Charlotte-Morgan ?
Or close the ticket, thanks.

**Comment by Charlotte-Morgan** [comment]
I think we can close this
