### ISSUE TITLE
Earthquake with population PDF did not show result layer

### ISSUE THREAD

**Issue by adhityadido** [inasafe/inasafe#3996]
### Problem
When I try to print the result of the analysis layer of Earthquake raster with population raster, the map did not show the same information as the analysis layer in QGIS. It only shows grey color map (exposure data) instead showing the analysis result in InaSAFE.
![result map](https://cloud.githubusercontent.com/assets/25237245/23542673/07c93bf8-0021-11e7-87f6-44553350edc6.JPG)

The result should be like this : 
![qgis result](https://cloud.githubusercontent.com/assets/25237245/23542681/12eac470-0021-11e7-8984-0e81daaa023f.JPG)

### Expected Behaviour
The result map should be the same with the analysis extent as in QGIS. 

### Environment
* InaSAFE : 4.0.b0
* QGIS : 2.14.9
* OS : Windows 10
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : Java_Population_WGS84.tif
  * Hazard : Earthquake_Yogyakarta_2006_WGS84.tif
  * Aggregation : DIY_District_Boundary_WGS84.shp
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ? No
* [ ] Is the data available ? Yes
  * If yes, where (BTSync, data.inasafe.org, zip) ? data.inasafe.org

### Proposed Solution
-

**Comment by timlinux** [comment]
@myarjunar please take this over - test and close if fixed otherwise work with @Gustry to resolve.

**Comment by Gustry** [comment]
This ticket will be fixed in the PR above. Feel free to open if you have any issue after this PR will be merged.
