### ISSUE TITLE
IFCW analysis didn't produce map pdf

### ISSUE THREAD

**Issue by adissadis** [inasafe/inasafe#3997]
### Problem
When i try to run analysis with IFCW with any analysis, it didn't produce map file (portrait & landscape). It say "No such file or directory"

![selection_005](https://cloud.githubusercontent.com/assets/2520159/23543666/c624ed96-0025-11e7-8901-da50caf3ca56.png)

When i check the template files, only this file printed:
![selection_006](https://cloud.githubusercontent.com/assets/2520159/23543682/d9c5ee5e-0025-11e7-9be0-c7355a51af5b.png)

This only happen with IFCW, when I tried with Dock, it produce all those files nicely
### Environment
* InaSAFE : 4.0.0
* QGIS : 2.14.12
* OS : Xubuntu 16.04
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : Java Population
  * Hazard : Earthquake D.I Yogyakarta
  * Aggregation : Yogyakarta district
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [x] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
When user print the pdf files while using IFCW, they can get all those files like when user using "print" button in InaSAFE Dock.

**Comment by felix-yew** [comment]
Hi mas @adissadis @Gustry 

I also find this problem in Windows. When I use the IFCW and then click `Generate PDF` it didn't produce map files, either PDF files or QPT files.
![image](https://cloud.githubusercontent.com/assets/13621886/23595469/ac700dd2-0254-11e7-8aec-d5d2a7b2c84c.png)

## Environment
* InaSAFE : 4.0.0
  - QGIS : 2.14.10
  - OS : Win 7 Pro/RAM 12GB 64-bit
* Data used (filenames and paths so as to reproduce, a project is better):
  - Exposure : Padang buildings
  - Hazard : West Sumatera earthquake raster
  - Aggregation : Padang villages

**Comment by Gustry** [comment]
This is fixed in the PR above.
Thanks
