### ISSUE TITLE
Too Large Font Size in PDF Map Legend

### ISSUE THREAD

**Issue by uswatunkh21** [inasafe/inasafe#3998]
### Problem
Font size in the PDF Map legend is too large. It then overlaps with other text in the PDF Map.
![too big font size](https://cloud.githubusercontent.com/assets/2535397/23543778/5769e04a-0026-11e7-85c2-9ba4135ae666.png)

### Expected Behaviour
Font size in the PDF Map legend should be in proportional size in order it do not overlaps with other text in the PDF Map.
![true font size](https://cloud.githubusercontent.com/assets/2535397/23543914/180a3552-0027-11e7-8e86-a92cdaa19748.png)

### Environment
* InaSAFE : 4.0
* QGIS : 2.14.8
* OS : Winddows 10
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : Padang building point (download with OSM downloader
  * Hazard : Padang_EQ_2009_WGS84.tif
  
### Proposed Solution
Minimize the font size, or split the legend into two columns

**Comment by lucernae** [comment]
@ivanbusthomi could you kindly take this over? I think this is about the template. You can give the template and assign it to me later.

**Comment by ivanbusthomi** [comment]
@lucernae sorry I missed this ticket yesterday.
I will create the template quickly and post it here

**Comment by ivanbusthomi** [comment]
@lucernae this is the zip template, sorry for the delay
[20170306_fix_template_v4.zip](https://github.com/inasafe/inasafe/files/820022/20170306_fix_template_v4.zip)

**Comment by Gustry** [comment]
@lucernae Can you have a look ? We will release 4.0.1 at the end of the week.

**Comment by lucernae** [comment]
Sorry, I will have a look at Thursday.

**Comment by lucernae** [comment]
Nice!
<img width="566" alt="screen shot 2017-03-09 at 21 49 11" src="https://cloud.githubusercontent.com/assets/831865/23755263/4b6cd27a-0512-11e7-9407-eb153142b7cd.png">

**Comment by Gustry** [comment]
@lucernae Can we close this ticket ?

**Comment by lrpower** [comment]
The legend text is overflowing for Cyclone IF landscape report. Maybe the (severe tropical cyclone) could be removed?
![image](https://cloud.githubusercontent.com/assets/10228025/24383474/c959c284-13a8-11e7-9167-0a509b26aec3.png)

**Comment by ivanbusthomi** [comment]
@lrpower interesting, I haven't had the chance to test the cyclone scenario, and I thought it won't be that long. Do you think it is enough to just pull to the left a little bit more?

**Comment by lrpower** [comment]
@ivanbusthomi I don't think there is enough space on the left. This is what its trying to show
![image](https://cloud.githubusercontent.com/assets/10228025/24787636/da659b6e-1bac-11e7-94ca-2cb5542a1ee1.png)

It still needs at least 12 more spaces on the right

I think we should get rid of the **(severe tropical cyclone)** and **(tropical cyclone)**

**Comment by timlinux** [comment]
For now lets try with a smaller font - 8 point for item font in composer might do it.

**Comment by ivanbusthomi** [comment]
Hi @timlinux , just like what I mentioned in https://github.com/inasafe/inasafe/issues/4047#issuecomment-300092635, It seems like changes that I made in the item font in map composer is not implemented in the pdf report.

mas @myarjunar - this is the updated qpt files. 
[20170509_maplegend.zip](https://github.com/inasafe/inasafe/files/986146/20170509_maplegend.zip)
