### ISSUE TITLE
Error: Fatality rounding - EQ analysis

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4033]
### problem ###
there is an error in the rounding of earthquake fatalities.
I have got a big earthquake planned. In the debug analysis - the results show 18589 fatalities but the rounded report shows 0 - 100.

![image](https://cloud.githubusercontent.com/assets/5743135/23698311/af0e829c-041d-11e7-9d5b-cb77585182e0.png)

### proposed solution ###
make it happy - kill more people

**Comment by Gustry** [comment]
It seems the problem comes in the reporting.
I will have a quick look this afternoon if I know where is it done in the reporting engine from @lucernae

**Comment by Gustry** [comment]
Fixed in PR above.
