### ISSUE TITLE
BUG: shakmap convertor

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4040]
when i used the shake map convertor it did not make version 4.0 ready key words.

I would expect key words are version compliant

**Comment by Gustry** [comment]
Yes, it's missing the multi-classification.

**Comment by Gustry** [comment]
According to @timlinux we did that on purpose. We put some default placeholders, but we still want users to run the keyword wizard.

I agree that if the layer is not 4.0 ready, we shouldn't display the layer in the hazard combobox.

**Comment by myarjunar** [comment]
@Gustry @Charlotte-Morgan I will create an option to launch the keyword wizard right after the shakemap converter finished just like what I did on multi-buffer tool. Is it ok?

**Comment by Gustry** [comment]
@myarjunar What is the status about this issue?

**Comment by myarjunar** [comment]
Hi @Gustry @Charlotte-Morgan , I think by adding the option to launch the keyword wizard will make the keyword match the version 4 keyword. If so, we can close this issue.
