### ISSUE TITLE
BUG: Min Needs Calculator

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4050]
### problem ###
the min needs calculator tool fails to run on the selected field if the same data are run twice.

Using BPS 2010 data for Jakarta subdistricts
run 1: used field pop_disabled as the IDP count - runs fine
run 2: used field pop_under5 as the IDP count - got the same results as the first run.

[Jkt_BPS2010_SubDistrict.zip](https://github.com/inasafe/inasafe/files/835607/Jkt_BPS2010_SubDistrict.zip)

problem 2:
If i update the min needs profile - ie modify the profile the min needs calculator is not reading the file

### proposed solution ###
Min Needs calculator tool should be able to be run many times on the same data using different fields - ie different populations with different needs

Min needs calculator tool can use the selected Min needs profile (this may be a new feature request for 4.1)

make it happy

**Comment by Gustry** [comment]
For problem 2, you need to restart QGIS and it will take care about your new selected profile.

For problem 1, I agree we can't run twice the tool on the same layer, using the same minimum need profile. We need to work on that.
But I guess, we should be able to run minimum needs twice if we change the minimum need profile between (with a restart of QGIS). But items need to be different between these two profiles.

**Comment by Charlotte-Morgan** [comment]
test comment to see if my email is working 
@charlotte_morgan

**Comment by ivanbusthomi** [comment]
ping @Charlotte-Morgan

**Comment by timlinux** [comment]
Duplicates #3967

**Comment by timlinux** [comment]
Short term fix: Display a message in minimum needs configuration to tell the user they need to restart QGIS for the change to take effect.

**Comment by Gustry** [comment]
I just added a small label in the profile manager saying that QGIS needs to reboot.
