### ISSUE TITLE
Hazard Keyword from Peta Bencana Downloader

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#4055]
### Problem
The hazard keyword for flood data that we download from petabencana.id set as Generic Class.
![image](https://cloud.githubusercontent.com/assets/8871958/23981960/dcb1b302-0a3c-11e7-8133-1c12b31c26a0.png)

Meanwhile, if we look at the flood classification in petabencana.id, similar with the classification in the flood classes at the keyword 
![image](https://cloud.githubusercontent.com/assets/8871958/23982101/c8809c9e-0a3d-11e7-9aae-bf97d1900bdd.png)

### Expected Behaviour
I just think, should we align the keyword from petabencana downloader with the hazard classification on petabencana.id (flood classes)

### Proposed Solution
Make it happen

cc : @Charlotte-Morgan

**Comment by Gustry** [comment]
@myarjunar Can you have a look to this issue ? Thanks

**Comment by myarjunar** [comment]
closed in #4056
