### ISSUE TITLE
Cyclone Hazard Keyword wizard

### ISSUE THREAD

**Issue by lrpower** [inasafe/inasafe#4057]
### Problem

Specified units (m/s, kn etc) do not carry over to the Cyclone classification - the default is km/hr.

### Expected Behaviour

If i specify my data is in a unit other than km/h, the output will be in that unit (knots for example)

### Environment
* InaSAFE : 
* QGIS : 2.14.4
* OS : windows
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : fake_buildings
  * Hazard : cyclone vmax.tif
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
Choose from the following:
1. the class values change to accommodate the units specified, or
2. we write a big disclaimer saying units displayed are in km/h and please enter the converted values of the units you want to use. Although, this makes the step of specifying your units prior pointless, or
3. we convert the geotif to km/h on the fly

Regardless, the units need to be specified in the output - maybe in the Analysis Details section(?)

**Comment by lrpower** [comment]
In addition, can the Minimum values for SSHWS No Hurricane be set to comply with https://docs.google.com/spreadsheets/d/1FbR0HarQcNTsmyYzHnw-h54-MrPkXXoM5V4rlEu2DOw/edit#gid=1107146610
It is not zero.
This will need to be updated in the help as well

**Comment by Gustry** [comment]
Hi @lrpower, 
* I made a PR to fix the SSHWS classification:
![capture d ecran 2017-03-20 a 10 09 13](https://cloud.githubusercontent.com/assets/1609292/24093677/514ef038-0d55-11e7-9d19-d63e2356aca4.png)

I'm not sure if I should include the minimum value for the "No hurricane" class. It will fall in "not exposed" if we don't put 0 km/h.

* About your issue with the unit, yes it's carried to the hazard classification: 
![units](https://cloud.githubusercontent.com/assets/1609292/24093765/c9e25f76-0d55-11e7-96ef-269fd7e71e63.gif)
As you can see, my maximum value for category 5 is updated from 252km/h, then 157 miles/h and 137 kt.
The wizard will read if you have some pre-existing keywords. So if you already put some values, and then change the unit, the wizard will still read your previous values. I made this GIF with a layer without existing keywords. I think it's fine as the unit are not updated on a layer.

**Comment by lrpower** [comment]
Thanks  @gusty 
I will try the keyword wizard again. I thought I had the most current version so I'm confused because it was definitely not changing units.

**Comment by Gustry** [comment]
> I thought I had the most current version so I'm confused because it was definitely not changing units.

It will work if your layer **hasn't** keywords **yet**. If your layer has already some existing keywords, the wizard will use the classification which has been made before.

I merged the new classification for SSHWS. It will be in 4.1. Can we close this issue ?

**Comment by Gustry** [comment]
I'm closing this ticket. Feel free to reopen if needed.
