### ISSUE TITLE
RFC: Population analysis and reporting

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4069]
## Problem
We would like to enhance InaSAFE to provide a high level of support for Contingency Planning. To do this we need to enhance the ability of InaSAFE to analyse and report on population data; including  reporting against age, gender and vulnerability measures.

This work is a high priority under DFAT contract for InaSAFE development in Indonesia.

This diagram summarises the current capacity of InaSAFE to report against population variables and the requirements for a BNPB contingency plan. This RFC addresses the age, gender and vulnerability requirements for contingency planning. Population displacement rates and fatalities are managed through hazard data and any hazard specific fragility functions. These are not included in this RFC.
![image](https://cloud.githubusercontent.com/assets/5743135/24278085/2b95f7e8-1074-11e7-8636-18f333584cf1.png)

In some cases; a hazard scenario may be homogeneous over a large area and appear to affect the whole population equally. The ability to identify and locate the most vulnerable sectors of the population allows government and humanitarian responders to prioritise contingency and response planning.

## Duration
1 week
DMI will meet with humanitarian partners on 11th April to test and finalise requirements
## Proposers
DMI Minions on behalf of BNPB, UNOCHA and the Humanitarian sector in Indonesia.
@samnawi 
@ivanbusthomi 
@felix-yew 
@fredychandra 

## Details
InaSAFE 4.0 has 3 ways of estimating the impact of a hazard event on population.
1. Global defaults - rates by age and gender
2. Population exposure data - with counts for total population (raster) and by age and gender (vector)
3. Aggregation data - with rates for age and gender

Users are able to specify if they want to report on age and or gender and how variables in the exposure and aggregation data will be used. Details of the affected population are used to generate the minimum needs and infographic reports.

## Proposed solutions
**1.** update global defaults to include more age, gender and vulnerability measures using international 'standards' where possible.
**2.** enhance InaSAFE to allow value mapping of population variables (counts in vector population exposure data) against a broader range of age, gender and vulnerability measures. 
**3.** enhance InaSAFE to allow value mapping of population variables (rates in vector aggregation data) against age, gender and vulnerability measures.

These proposed enhancements will:
* align well with contingency planning requirements in accordance with government regulations and international humanitarian practice.
* allow users to analyse a subset of the population - ie just youth, just women, just disabled.
* allow users to report against a subset of the population and in combination with customised minimum needs - create humanitarian, sector specific reports - ie shelter needs for disabled

### 1. Global defaults solution
**1. Retain current global defaults for age** as these match international standards used by World Bank, UNFPA & UN (but differ from BNPB standards):
Youth 0 - 14 yrs
Adult 15 - 64 yrs
Elderly 65+ yrs

A review of international standards is available here (thanks @samnawi ) with links to sources: https://docs.google.com/spreadsheets/d/1NFGIRPyb69yO4I-8QkB4MaiGn-Te2L0gPd9yDaj6tiA/edit#gid=0 

- [ ] update the global defaults dialog in the InaSAFE options. Separate the age, gender and vulnerability measures. Include definitions for concepts.
![image](https://cloud.githubusercontent.com/assets/5743135/24279223/21a85972-107b-11e7-8d3d-0475f1a20020.png)
- [ ] allow total of all age groups to be less than 1 - this allows users to analyse for only one group if they want to.
- [ ] update concept definitions to mention international standards (not CIA source :))

**2. Introduce more gender related global defaults:**
female - proportion of the population that is female
male - proportion of the population that is male
child bearing age - proportion of the female population of child bearing age (15 - 49)

- [ ] update global defaults dialog as above
- [ ] update concepts and definitions with sources
- [ ] use the child bearing age value as input to extra rice for pregnant and lactating min needs

**3. Introduce vulnerability global defaults:**
Infants - proportion of the population under 5 yrs
Elderly - proportion of the population over 60 yrs (note: same concept - new definition)
Dependency ratio - proportion of the population aged under 15 and over 65 to the working population (15 - 64) http://www.unfpa.org/world-population-dashboard  (53.9% - http://data.worldbank.org/indicator/SP.POP.DPND?end=2015&start=1960&view=chart) 
Disabled - proportion of the population disabled 

- [ ] update global defaults dialog as above
- [ ] update concepts and definitions with sources
- [ ] provide rates for vulnerability concepts from international sources
- [ ] define concept age: elderly separate from concept vulnerable: elderly

### 2. Population exposure data (vector) solution
**1. Introduce value mapping** in the key words wizard to allow users to assign variables in their rich population exposure data to age, gender and vulnerability concepts.
- [ ] the same variable may be mapped to age, gender and vulnerability concepts
- [ ] the raw data may not have denominator values - these may also need to be mapped
- [ ] the details of for vulnerability analysis and reporting will be discussed in a UN / humanitarian workshop on 11th April. Please build placeholders for now

**It may look something like this:**
![image](https://cloud.githubusercontent.com/assets/5743135/24280483/80aa0fb2-1083-11e7-91e2-dd362f9feb6b.png)

### 3. Aggregation data solution
Will be very similar to the population exposure solution above but inputs will be rates not raw counts

### 4. Open ended solution
- [ ] include value mapping place holders ie age 1, age 2, age 3, age 4 etc that users can then use as many or as few as they need and potentially define their own concepts.

## Challenges
InaSAFE 4.0 allows us to work with rich data. This RFC proposes how InaSAFE might handle rich population data. The next step is to define how the analyses will be reported.
suggestions:
- [ ] report against global default attributes if they are used
- [ ] report against value mapped attributes if they are used
- [ ] InaSAFE users may want to be able to generate age, gender or vulnerability reports for the exposed, affected or displaced populations.

## Record of votes
Vote of thanks to @samnawi for valuable research and diagrams supporting this proposal.

## CC

@Charlotte-Morgan 
@timlinux 
@vdeparday 
@samnawi 
@felix-yew 
@ivanbusthomi 
@fredychandra 
@ismailsunni 
@Gustry 
@adissadis

**Comment by samnawi** [comment]
Hi @Charlotte-Morgan I've tried to make some mockup of the population keyword like in the picture below.

**Age Group (5 class)**
![image](https://cloud.githubusercontent.com/assets/8871958/24343266/c173b4bc-12ef-11e7-8f08-cc34cb8bba7d.png)
**Age Group (3 class - global)**
![image](https://cloud.githubusercontent.com/assets/8871958/24343297/f14c1cce-12ef-11e7-946e-9e83c15d028d.png)

**Gender**
![image](https://cloud.githubusercontent.com/assets/8871958/24343329/14f859f8-12f0-11e7-9906-fd9c186e8b42.png)

**Vulnerability Group**
![image](https://cloud.githubusercontent.com/assets/8871958/24343368/423bc4e0-12f0-11e7-8ae6-d958ccd6674f.png)

I proposed to use one page with some tab (based on the group) on one page. So, user just chooses the tab and fill the information by grabbing the specified field/column that relevant with the concept. We use this way to accommodate the attribute data for one parameter that has more than one fields/columns.

**Comment by samnawi** [comment]
I just think, I just think, for many steps to doing value mapping of some variables, if it possible we can make it automated by InaSAFE.
In the last conversation with Pak Wawan, he wants that InaSAFE using a credible data. He also says that BNPB and BPS already has a MoU for data sharing. I just imagine like in the [DIBI](http://dibi.bnpb.go.id/data-kependudukan) that have an access directly to BPS server to get the Census and PODES data.
So, if BNPB also gives the permission for InaSAFE server to access that data, I think we can automatically mapping the field for each age group, gender, and disability.

**Comment by Charlotte-Morgan** [comment]
@fredychandra - please add BOBOT ideas here too. No promise they will be included

**Comment by fredychandra** [comment]
Hi @iwan and @Charlotte-Morgan 

I try to incorporate the vulnerable population index concept into this RFC. In this concept we can try to develop model of vulnerable population in certain area. Then the model can be used to localized and analyzed to see a certain area that will be most affected inside homogenous hazard extend. 

This concept basically uses Analytical Hierarchy Process (AHP) to define sub-indicators based on existing dataset (field) and give a weight on each (see below diagrams).  In this case, I propose population vulnerability and disability vulnerability because the dataset is available for this purpose. 

AHP to define sub-indicators on Population and Disability vulnerability

![image](https://cloud.githubusercontent.com/assets/6345285/24692980/9b9260d2-1a05-11e7-9b39-1fec98a7bd3f.png)

After we define the sub-indicator for both, then we need to define the ranking (score) for each sub-indicators (see table below).

![image](https://cloud.githubusercontent.com/assets/6345285/24693229/c09997aa-1a06-11e7-9c23-dc4a5c323a05.png)

The next step is scoring the dataset by using above sub-indicator and score. 
This is for Population Scoring Formula
![image](https://cloud.githubusercontent.com/assets/6345285/24693339/42f447ea-1a07-11e7-895c-9c62dc313aed.png)

This is for Disability Scoring Formula
![image](https://cloud.githubusercontent.com/assets/6345285/24693358/64a684de-1a07-11e7-8b3d-7b726def63e2.png)

Image below is an example of how Population Vulnerability Scoring process (See left table, yellow mark). 
![image](https://cloud.githubusercontent.com/assets/6345285/24693497/09dea2f6-1a08-11e7-9574-215e9f564876.png)

Image below is an example of how Disability Vulnerability Scoring process (See left table, yellow mark)
![image](https://cloud.githubusercontent.com/assets/6345285/24693519/23cecdbc-1a08-11e7-93d4-18dabbc9871c.png)

After we got the total bobot (weight) score for each model, Then we can rank it into 3 classes (High, Medium and Low) using natural break method. Based on the rank then we can set up threshold how many percentage for each class will be displaced in particular analysis area (define displacement rate). 

E.g  High       = 75 % will be displaced
       Medium = 40 % will be displaced
       Low        = 10 % will be displaced

If we have the threshold (displacement rate) so we can calculate automatically  the number of potential displacement in homogenous hazards extend. I think in order to develop this function in InaSAFE, I would prefer it can be set as user requirement (flexible). 

Cheers,

**Comment by Charlotte-Morgan** [comment]
I have been thinking about age, gender, population and vulnerability concepts.
I propose we use completely different terms for age and vulnerability.
Age in 5 classes: infant, child, youth, adult, elderly
Vulnerability in 3 classes: under 5, over 60, disabled
Gender in 3 classes: female, child bearing age, pregnant or lactating

Action: Charlotte to update concepts.py

**Comment by samnawi** [comment]
Hi @ismailsunni from your PR in #4094, I have a question for you.
Are we still keep the field mapping process in the keyword wizard?
![image](https://cloud.githubusercontent.com/assets/8871958/24848498/343c6bd6-1df1-11e7-83e1-d8b625805d84.png)

**Comment by ismailsunni** [comment]
@samnawi of course not. It's in my to do list to remove some of them (e.g. female count, youth count, etc) that can be set in the tool. I am planning to put the tool into the wizard, become one of the step of the wizard.

Btw, These are my to do list:
To do list:
- Write Metadata
    - [ ] drag and drop
    - [ ] Check spin box is stored properly
    - [ ] Save to metadata
    - [ ] Unit test for tab and widget
- Read metadata
    - [ ] Handle single field name from old keywords
    - [ ] Populate field based on metadata
    - [ ] Clear used field from the metadata
- Misc
    - [ ] Text for description and header text
    - [ ] Help page
    - [ ] Better size
    - [ ] Filter layer
    - [ ] Filter fields —> int and float only
    - [ ] Show 10 unique values
- Add to wizard
    - [ ] Check the wizard flow
    - [ ] Add the step to the wizard
    - [ ] Remove unused inasafe fields or default fields
- Others
    - [ ] Show pretty fields in the dock
    - [ ] Update definitions.py to list non-group fields
    - [ ] Update parameters repository

**Comment by timlinux** [comment]
@fredychandra thank you for your table above. Could you maybe meet us on Zoom.us to do a walk through of your thinking here?

**Comment by timlinux** [comment]
@samnawi do you you have some examples of the tables you are looking for us to produce here?

**Comment by fredychandra** [comment]
Hi @timlinux 
Yes, If the time is fit, I could join the Zoom meeting.

**Comment by samnawi** [comment]
> @samnawi do you you have some examples of the tables you are looking for us to produce here?

Hi @timlinux Did you mean the data sample with many populations attributes inside?

**Comment by timlinux** [comment]
@samnawi No I meant examples of the report tables you would like to see. @Charlotte-Morgan said you had in mind to produce some pivot tables too. We would like to start coding the logic for that this week if possible.

**Comment by samnawi** [comment]
Hi @timlinux Based on the contingency plan guideline from BNPB (still drafted), the table looks like this
![image](https://cloud.githubusercontent.com/assets/8871958/24939273/5b90cf3a-1f66-11e7-94e8-e39854cf0277.png)

**Comment by samnawi** [comment]
Hi @ismailsunni I've already tried your field mapping tool in the dev version.
Regarding your plan in [comment](https://github.com/inasafe/inasafe/issues/4069#issuecomment-292865602) to put the tool into a wizard, I still have a question for this stuff.

Whether this wizard also accommodate the data if they don't have an attribute that contains total population?
Such as the raw table that @Charlotte-Morgan mention in this RFC.
![image](https://cloud.githubusercontent.com/assets/8871958/25125850/7c72eef6-245a-11e7-8dd0-79d8a576bf5c.png)

I've got it when I try using the RAW data from BPS Census 2010.
![image](https://cloud.githubusercontent.com/assets/8871958/25125959/cf859508-245a-11e7-8a3a-b83dda90d3e7.png)

**Comment by ismailsunni** [comment]
Hi @samnawi 
For InaSAFE itself, we never support population with no total field.
For the case that you mention, I think it's will be easier to just use field calculator to create total population field.
We can make it work automatically, but it will introduce more complex problem (or at least more discussion). For example, what if there is only female field but no male field (we always automatically calculate male count with `total - female count`). Or in @Charlotte-Morgan 's comment here: https://github.com/inasafe/inasafe/issues/4069#issuecomment-292763098 the gender consist of 3 fields (female, child bearing age, pregnant or lactating), no male field also.

So, my suggestion, is creating the total field by using field calculator is easier. I think it's a part of data preparation step.

What do you think @timlinux ?

**Comment by samnawi** [comment]
Hi @ismailsunni I prefer not to make it automatically. I just think InaSAFE just recognize what user choose in the wizard. So, like in this step
![image](https://cloud.githubusercontent.com/assets/8871958/25125959/cf859508-245a-11e7-8a3a-b83dda90d3e7.png)
I imagine if the user can choose more than one field, then InaSAFE just calculate that.

**Comment by ismailsunni** [comment]
@samnawi Hmm that's a good idea to choose more than one field. Since it's should be also the same mechanism as in the field groups.

**Comment by samnawi** [comment]
Hi @ismailsunni Is your wizard which you build already fixed? Because I cannot do population analysis. 
![image](https://cloud.githubusercontent.com/assets/8871958/25327764/9e2b1ac4-28ff-11e7-8702-e5113b257f36.png)

**Comment by ismailsunni** [comment]
Hi @samnawi 

The problem you got is coming from the analysis. The impact function hasn't been updated to handle the new keywords (it expects string, but it got list). I will work on it if @Gustry hasn't worked on it.

**Comment by timlinux** [comment]
![screen shot 2017-04-25 at 9 45 02 am](https://cloud.githubusercontent.com/assets/178003/25373947/eb750f1e-299b-11e7-89dd-7cb17e9c24d4.png)

We discussed in our call today with @samnawi  - we will make a small report per vulnerability group like the image above. Then we will take the definitions to put explanatory notes underneath each table. The whole lot will go into a new report sections called 'Demographics'.

**Comment by myarjunar** [comment]
@timlinux @samnawi @ismailsunni will we create a different section for each table generated from this new metadata or just one section but we categorize it just like what we did in actions list and notes?

**Comment by samnawi** [comment]
Hi @ismailsunni from a wizard that you create, I see that the pregnant and lactating women input is combined in one process.
![image](https://cloud.githubusercontent.com/assets/8871958/25610394/3c0f415e-2f4d-11e7-9577-90c966a38be6.png)
If we refer to this [table](https://github.com/inasafe/inasafe/issues/4069#issuecomment-293458590) (BNPB CP guideline), the result of pregnant and lactating women separated in the different column.

Hi @Charlotte-Morgan if I see your comment in https://github.com/inasafe/inasafe/issues/4092, you proposed that gender in 3 classes, Should we still try to refer the table from BNPB CP guideline or not?
But, I prefer to make it separate, because this is the requirement for the document, also make the result more flexible. From the formulation that @fredychandra proposed in https://github.com/inasafe/inasafe/issues/3607, it also separates between the ratio for pregnant and lactating women. 
In this [comment ](https://github.com/inasafe/inasafe/issues/4092#issuecomment-297651386), I try to provide a separate definition for pregnant and lactating women.

**Comment by Charlotte-Morgan** [comment]
@ivanbusthomi - can you please link to this ticket the work you were doing on the new pivot table reports?

**Comment by ivanbusthomi** [comment]
I am still trying to see what other combination of information that can be generated from the rich data that we get from the table. the link to the rich reporting ticket is https://github.com/inasafe/inasafe/issues/4070
