### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by ingenieroariel** [inasafe/inasafe#407]
Inasafe does not run on Python3, but gdal and numpy do (when installed from sources). I will reference this ticket in my commits to make this possible with a single codebase, this may lead us to drop python2.6 compatibility in the future, since 2.7 is a lot easier to get to work in parallel with python3.

Let the fun begin:

```
>>> from safe.common.utilities import test_safe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./safe/common/utilities.py", line 80
    os.makedirs(path, 0777)
                         ^
SyntaxError: invalid token
>>> from safe.api import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./safe/api.py", line 24, in <module>
    from safe.storage.utilities import bbox_intersection
  File "./safe/storage/utilities.py", line 742
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by timlinux** [comment]
I'm going to close this. Next year we will port to QGIS 3 and python 3 will be a requisite.
