### ISSUE TITLE
Global Ratio defaults are not being used in the IF

### ISSUE THREAD

**Issue by lrpower** [inasafe/inasafe#4071]
### Problem

I am changing the Ratio Global Default values but they are not carrying through to the IF
![image](https://cloud.githubusercontent.com/assets/10228025/24532479/8a7b9e82-160c-11e7-9e1b-d0720cd89cb2.png)
![image](https://cloud.githubusercontent.com/assets/10228025/24532580/51de1cfc-160d-11e7-8697-fd9f2d5e7a7a.png)

### Expected Behaviour
The global ratio values set will be used.
 
### Environment
* InaSAFE : 4.0-develop
* QGIS : 2.18.3
* OS : windows
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : Population raster
  * Hazard : Tsunami
  * Aggregation :n/a
  * Extent : Tongatapu
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
Use the global ratio values that are set

**Comment by ismailsunni** [comment]
@lrpower did you re-assign your layer's metadata using keywords wizard again? You need to re-assign the metadata, since the metadata only stores the ratio, not global or not (to avoid changing result unexpectedly)

**Comment by lrpower** [comment]
Yes. deleted .xml and reran keywords. 
Still not evident. :(

**Comment by lrpower** [comment]
And a QGIS reboot did not help either.

**Comment by Gustry** [comment]
* Is the value updated in your keywords? (when you click on layer in the legend, you should see keywords on the right)

* Can you copy paste InaSAFE logs here? Open the log panel with the small icon in the bottom right corner of QGIS, it looks like a bubble comic strip, run the IF and then copy/paste all logs from the InaSAFE tab. Thanks.

**Comment by lrpower** [comment]
No, the value is not updated in the keywords. 
The log isn't that descriptive
`
2017-04-07T16:01:43	0	Showing No Keywords Message
2017-04-07T16:01:43	0	Showing No Keywords Message
2017-04-07T16:02:07	0	Showing No Keywords Message
'

**Comment by Gustry** [comment]
I'm trying to replicate your issue. Values are updated in my keywords:
* I changed my global defaults in InaSAFE
* I run the keyword wizard to update values
* Before the end of the wizard, I can see my old values in the dock and my new values in the wizard. As soon as I press "Finish", my keywords are updated in the dock. So for me, values are updated.

I tried my best, with subtitles ;-) 
![defaults](https://cloud.githubusercontent.com/assets/1609292/24788175/62a7d550-1b6c-11e7-897b-1a79b3b23e59.gif)

I'm sorry, I can't replicate the issue for now.

**Comment by Gustry** [comment]
Ah yes. We can't assign global default on a raster.
Because global default can be used only on an aggregation layer (which can be only vector).

Can you tell us your scenario? What kind of exposure/hazard/aggregation (vector/raster) ?

**Comment by Gustry** [comment]
Do you mean using global default when we don't use an aggregation layer in the impact function ?

**Comment by lrpower** [comment]
Yes, I did mean using global defaults with no aggregation layer. 
I was using a population raster and Tsunami raster which I now know doesn't work 
However, I do have a polygon village that I can use for aggregation.
Will this work?
Although I think the answer will be no because it's not working for me now

**Comment by Gustry** [comment]
Ok, thanks. I could replicate the issue!

When I was asking for logs, you need to run the impact function.
The impact function is very talkative about ratios and counts ;-)
I can understand what is happening in the impact function.

![defaults](https://cloud.githubusercontent.com/assets/1609292/24789131/cabed4f4-1b71-11e7-9b02-4864133ad275.gif)

It's woking with an aggregation layer if you assign keywords like in my previous screenshare.
I'm working on a fix about your issue. Thanks for reporting.

**Comment by Gustry** [comment]
The PR has been merged into develop. The fix will be in 4.1.
