### ISSUE TITLE
InaSAFE Help icon is missing

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#4073]
### Problem
Our InaSAFE help icon currently is not showing in the toolbar. We can still access the InaSAFE help from the toolbar by clicking on the empty space where the icon supposed to be.
![image](https://cloud.githubusercontent.com/assets/7351977/24599699/a019921e-187b-11e7-8a7c-92b3a8cacf73.png)

### Expected Behaviour
There should not be an invisible button in the toolbar, and the icons in the toolbar should be shown properly.

### Environment
* InaSAFE : Develop
* QGIS : 2.14.10
* OS : Windows 7

### Proposed Solution
Make it happy :)

___
**CC** @Charlotte-Morgan @timlinux @samnawi @felix-yew @ismailsunni

**Comment by ismailsunni** [comment]
Hi @ivanbusthomi 
CMIIW, but I have checked, we don't have icon for help until now. I have checked in several version of InaSAFE, I couldn't find it.

Hi @MariaSolovyeva 
Can you create one for us? Or do you remember that you have created one before? Maye be it's just lose.

cc @timlinux
