### ISSUE TITLE
Pre populate all combinations for keywords when using shakemap converter

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe#4078]
### Problem
When you convert an xml grid for earthquake it immediately allocates keywords so  that the resultant layer can be used in Inasafe. The problem is that not all combinations of keywords are generated. Only the keywords on population classification are generated. 

![earth_quake_hazard](https://cloud.githubusercontent.com/assets/2510900/24612548/e333b6ba-1885-11e7-9791-38f6844103e5.PNG)

### Expected Behaviour

Generate all keywords for each combination

### Environment
* InaSAFE : dev
* QGIS : 2.18.5
* OS :  Windows 10
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : `https://earthquake.usgs.gov/realtime/product/shakemap/us10008e0f/us/1491194290894/download/grid.xml`
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * The raw xml grid is available and converting it using shakemap converter

### Proposed Solution
Make it happy

**Comment by ismailsunni** [comment]
I think it should be easy to set the classification. It just the matter of which classification that we want to set. Any suggestion @timlinux @Charlotte-Morgan

**Comment by ismailsunni** [comment]
I have done this in #4832, set all classification for all exposure to mmi classification, closing this.
