### ISSUE TITLE
Constraint for Population Group

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4082]
### Problem
For #4069 we will have more ratios in the age ratio fields. We should be able to use group to make a constraint. for example: the sum of them should be at most 1. This can applied to the other groups (e.g. gender group ratio).

### Proposed Solution
Currently, I use very hard coded trick to make it work on version 4.0. We need to define the constraint  in the group definition.

Supersiding 3rd item #4077

**Comment by Charlotte-Morgan** [comment]
@ismailsunni - i think you have this under control

**Comment by ismailsunni** [comment]
@Charlotte-Morgan yes, I just need to merge #4126 first

**Comment by ismailsunni** [comment]
#4126 is merged, so we can close this.
