### ISSUE TITLE
Output problem with QGIS 2.18 and Mac OS 10.11.6

### ISSUE THREAD

**Issue by stanreb** [inasafe/inasafe#4083]
### Problem
Analyses work OK and risk layers are created correctly. 
But the output reports that are generated only include texts and charts, but no maps.

### Environment
* InaSAFE : 4.0.1
* QGIS : 2.18
* OS : Mac OS 10.11.6
* Data used (filenames and paths so as to reproduce, a project is better): "Rokatenda.zip" and "DKI Jakarta.zip" training data
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [x] Is the data available ?
  * http://data.inasafe.org/InaSAFE%203.5%20Training%20Data/

**Comment by stanreb** [comment]
Thanks
I run 2.18.0
I'll try again after updating it.

**Comment by Gustry** [comment]
hi @stanreb, is-it working now?

**Comment by stanreb** [comment]
With QGIS 2.18.2, it now works. 
Thanks !

**Comment by Gustry** [comment]
You're welcome !
