### ISSUE TITLE
Map Template: Suggestion to update map report

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#4085]
### Problem
Currently, our legend and analysis information sections in map report show the information using labels and some template elements. In the template, most of the positions and size of these elements are fixed and there are extra space reserved so that if the text is quite long it will not overlaps other information. These will create some small gaps if the text is not long enough.
![image](https://cloud.githubusercontent.com/assets/7351977/24737285/ac095a94-1ab7-11e7-81b4-57376292e320.png)

### Expected Behaviour
If possible, we should remove unnecessary gaps in the report so that the map report will look cleaner.
![image](https://cloud.githubusercontent.com/assets/7351977/24737240/5bac5d58-1ab7-11e7-9503-88329d36db23.png)

### Environment
* InaSAFE : 
* QGIS : 
* OS : 
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 

### Proposed Solution
We could use html table elements in the map template just like how we did in the realtime report. It will allow us using a responsive table that will resize with the content of the analysis information and remove the need to reserve extra space for long text.
![analysis_info](https://cloud.githubusercontent.com/assets/7351977/24737135/a29eaeec-1ab6-11e7-90ec-005eb21922dc.gif)

This approach might not solve the gaps between the legend and analysis information though.
___
**CC** : @Charlotte-Morgan @timlinux @felix-yew @samnawi @fredychandra @ismailsunni @myarjunar @lucernae

**Comment by samnawi** [comment]
Hi @ivanbusthomi I just curious, why we don't keep the gap? I prefer to keep it for consistency of the map report. 

I just think the more important problem to prevent the legend (dynamic content) not appear beyond the available space.

**Comment by samnawi** [comment]
How about the font size?

I think it's okay to use the same font-size for legend, analysis information, and disclaimer, since all of this elements has a role as edge information of the map.

**Comment by ivanbusthomi** [comment]
To keep the consistency, I think we can apply the responsibilities only in the analysis details section only. So it will keep the disclaimer and legend section unchanged.
what do you think mas @samnawi and @myarjunar ?

**Comment by timlinux** [comment]
So we will make a new report component that includes the complete analysis information content...

**Comment by timlinux** [comment]
We discussed this in our sprint and we think it is better to address this by making custom report templates where space is an issue . E.g. the custom report could add more pages to the layout and move legend onto a second page.
