### ISSUE TITLE
Project Portability - HTML file sharing

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4089]
### problem ###
I would like be able to take a project from one machine with all data and analysis results and put it on another computer and have it run under a different profile.

I would like to demonstrate the UNOCHA analysis at a workshop using a different machine to the one on which the analysis was run and share the project with working group members this week.

At present this is possible if the project stores relative paths and the results are stored with the project; however in the html file that appears in the dock for results, the file references the inasafe resources folder under the original user profile. This means that the file needs to be edited before it will work on a new machine.

### attempted solutions ###
1. edit the paths,  but this needs to be done by every user - not a good solution
2. copy the resources to the project folder and supply them with the package
3. save results as *.shp, *.geojson. *.geopackage - these all write a html file but its not the correct file.

### why the html is so important ###
If a user runs a modified analysis; ie uses age variables as vulnerability variables; they need to hack the html file to make the results reflect the analyses. ie replace youth with under 5 etc.
If the report is 35 pages long (analysis results for Jakarta villages) then the html is a better file to share than the pdf report.

### examples ###
1. html report with path
![image](https://cloud.githubusercontent.com/assets/5743135/24834536/e5c0fc4e-1d12-11e7-8ca4-8a3a4cba44b0.png)

2. html report in dock when project is moved to a different machine and different path
![image](https://cloud.githubusercontent.com/assets/5743135/24834532/c35cea32-1d12-11e7-8f9c-c1a1994e78bd.png)

3. dock display for exported files
![image](https://cloud.githubusercontent.com/assets/5743135/24834539/112a8094-1d13-11e7-8ca7-3efc494cfb53.png)

### other bright ideas ###
1.check out a branch and hack the labels on the variables before running the analysis so the html does not need editing.  this does not fix the path though
2. define a path in the html as a separate variable

@timlinux @ismailsunni @ivanbusthomi @samnawi - grateful for any suggestions

**Comment by timlinux** [comment]
My opinion to resolve the issue:

- [ ] Add an option in the options ui to allow the user to save resources (images, css etc) with the report
- [ ] When the above option is enabled, use relative paths for images and css, pointing to a directory in the output folder
- [ ] copy everything over to the output dir needed for the report to work

**Comment by Charlotte-Morgan** [comment]
Hi @timlinux 
I like your idea to resolve the issue. I think there are two situations.
1. **want to share and package the whole project** to someone who will open in QGIS with InaSAFE.
I think your proposal will be great however as you say; lots of duplication. Maybe if we write the relevant resources to a resources folder in the user specified results location and make the html look for that?
This way we only write once and if it exists it can be updated or over written.

 2. **Want to share the html only.** This would be when the html report has been tweaked and the audience is only interested in the results. In this case I think we can share the resources folder and tweaked HTML files with a revised resources path.

**Comment by Charlotte-Morgan** [comment]
How to share html only
[PortableReports.zip](https://github.com/inasafe/inasafe/files/909967/PortableReports.zip)

**Comment by myarjunar** [comment]
closed in #4160
