### ISSUE TITLE
InaSAFE install - submodule tricks

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4090]
### problem ###
When the github inasafe code is cloned to a new machine it does not run until the user runs the git submodule init etc routine.

### proposed solution ###
an inasafe clone to a new machine install should not require a git submodule init etc routine to be run by the user. It would be great if this can be avoided or a maybe give  warning message to advise new users what to do. There is a warning about disabling the geoprocessing plugin.

**Comment by Gustry** [comment]
Instead of doing only:
```
git clone git@github.com:inasafe/inasafe.git
```

You need to do 
```
git clone --recursive git@github.com:inasafe/inasafe.git
```

It's on a todolist to give a nicer warning about submodules.

**Comment by ismailsunni** [comment]
Can we close this?

**Comment by Gustry** [comment]
I added a warning when QGIS is starting.
