### ISSUE TITLE
Gender report - use real values

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4091]
### problem ###
The gender report calcs sphere min needs for females based on a hard coded formula. This means the extra rice for women is calculated regardless of whether the key word for female count was set in the exposure data or female rate was set in the aggregation layer.
This calc is using hard coded values; not values in data or defaults

### proposed solution ###
the calculation of females pregnant and lactating and the gender report should use the female count, female rate or female global default set in the data where possible.

### Gender report ###
The gender report could include : total pop, total females, total child bearing age, total pregnant / lactating and sphere min needs for women .. ie extra rice for pregnant and lactating and hygiene kits for others :)

please link this to #4069 
@ivanbusthomi  - please link this to the updated reports you are working on
@ismailsunni @ivanbusthomi @samnawi @timlinux

**Comment by samnawi** [comment]
Hi @Charlotte-Morgan Whether this stuff as a complement or replace this ticket https://github.com/inasafe/inasafe/issues/3607 ?

Just to add a note :
Based on the regulation from Ministry of Health (but I do know the number of regulation), childbearing age group is a female 15 - 49 years.

**Comment by Charlotte-Morgan** [comment]
hi @samnawi - thanks for the definition.
IMO it would be great to update InaSAFE to use real data when it exist and not have the calculation hard coded. What do you think?
