### ISSUE TITLE
Update Global Default Option for #4069

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4100]
### Problem
We have more global default values, it's better to group them like @Charlotte-Morgan 's comment in #4069.

### Proposed Solution
I think we can do it with tab to group them. But, it will be tabs inside tabs. Is that good @timlinux ?

Note: I made this ticket to have smaller and doable ticket.

**Comment by Gustry** [comment]
> But, it will be tabs inside tabs

I think I will go for QGroupBox (QgsGroupBox) on the same frame.

**Comment by ismailsunni** [comment]
Done in #4109
