### ISSUE TITLE
Minimum Needs Calculator's Output Location

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4117]
### Problem
Currently, there is no option to set where we want to save the output layer from the minimum needs calculator. I checked in the code, it will be stored in the same location (depends on the file name and user directory).

A problem will occur when a user try to do minimum needs calculation, with the same layer name but different content. It won't over write the old one (since data_store doesn't support overwritting). Thus, the user will get the wrong result.
```
Copy/paste some InaSAFE logs here if it was an error.
```

### Environment
* InaSAFE : develop/master
* QGIS : 2.14.10
* OS : MacOS
* Data used (filenames and paths so as to reproduce, a project is better):
   - Any
  
### Proposed Solution
We should support custom output location (with a default one). Then, if there is already existed file, we should ask if the user wants to over write it or not.

We should also do the same for MultiBuffer tool. In the other tool like `Add PetaBencana` or `ShakeMap Converter`, we already have this options.

**Comment by timlinux** [comment]
As a quick fix we can use a unique file name for the output data package.
