### ISSUE TITLE
IDP Camps

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#412]
- IDP camps have already been identified pre-disaster, is it safe post-disaster? – How far is it away from the hazard zone
- How to pick an IDP camp – based on certain criteria
- What is safe? – duration of hazard, other hazards could impact (flood and landslide)
- Combining Hazard, Buildings and Population, to find the buildings with enough capacity to accommodate IDP – need user case, and need to assess who would do this analysis (beginner or Advance users)

Note : IDP = Internally Displaced People

**Comment by timlinux** [comment]
Closing this pursuant to having a direct requirement and specification
