### ISSUE TITLE
Investigate Rule for Ratio vs Fields vs Global Default

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4127]
### Problem
Investigate if these rule are valid:

#### Rules

1. Population raster with no aggregation will use global defaults for demographics (based on ratios)
2. Population raster with aggregation will use aggregation defaults for demographics (based on ratios), falling back to globals if set in agg keywords
3. Population vector with no aggregation will use exposure keywords based on field mappings or global defautls based on ratios
4. Population vector with vector aggregation will use aggregation defaults for demographics (based on ratios), falling back to globals if set in agg keywords

cc @timlinux @Gustry

**Comment by Gustry** [comment]
Read the IF logs, it's quite detailed inside about what is used, falling back default ...
Maybe add new logs with the new demographic system. We should be able to understand what is going on by reading the log.

**Comment by ismailsunni** [comment]
Here is my investigation's result @Gustry @timlinux 
I made more detail cases here.

<img width="689" alt="screen shot 2017-05-08 at 14 21 25" src="https://cloud.githubusercontent.com/assets/1421861/25794111/bed3ac64-33f9-11e7-8de2-3a334ded0f73.png">


It seems everyt cases make sense. Beside...

The yellow one and red one is the one that I thought not consistent.

The red one makes sense, since we specify that we don't use the ratio/count.
The yellow one is also  fine, since we agree that we will run the post processor for raster population if there is no aggregation layer.

So, all is good.

**Comment by Charlotte-Morgan** [comment]
@samnawi & I need to provide comment on this

**Comment by timlinux** [comment]
@ismailsunni can you attach the original spreadsheet above here? Thanks

**Comment by ismailsunni** [comment]
@timlinux here is the link https://docs.google.com/spreadsheets/d/1jARdLW6cxEBk0wiUV0MJrlYVvuLseuS2zeM8prRn1dc/edit#gid=0

**Comment by samnawi** [comment]
Just try to link with #3971

**Comment by felix-yew** [comment]
Hi mas @ismailsunni - I wanna ask about one of case from your investigation's result. It is about the yellow one, if I run the flood raster with population raster and aggregation vector (ratio not set), so from your investigation maybe (the yellow one means) it is not be working or there maybe can give a result? or give the result but no calculations produced in detailed report? because I run it with batch runner and get the result but there are no calculations produced in the detailed report. 
[impact-report-output.pdf](https://github.com/inasafe/inasafe/files/1009781/impact-report-output.pdf)

![image](https://cloud.githubusercontent.com/assets/13621886/26186951/d9c68ce4-3bbf-11e7-8049-14f2ac1ac2f3.png)

**Comment by ismailsunni** [comment]
@felix-yew Your result is what's the expected, there should be not any breakdown since we specify to not use ratio/fields.
Perhaps the result in my test above is wrong. I will try to run it again.

**Comment by felix-yew** [comment]
Okay, maybe it will need some explanation in that detailed report why no calculations produced, so the user can make sure that the result is correct but because there are no ratio found or anything else so the calculations nothing happen.

**Comment by ismailsunni** [comment]
@myarjunar can you add the comment from @felix-yew to the report?

**Comment by ismailsunni** [comment]
@Charlotte-Morgan @timlinux 
I just found out that when the user use `vector count population` but set count to `do not use` with `no aggregation`, InaSAFE still calculate the ratio (from default ratio)*

In my opinion, this is unexpected. Or do we have historical reason why we do it (the policy or rule) ?

cc also @Gustry 

*: when the user doesn't use aggregation, InaSAFE create an aggregation layer with the ratio set to global default.

**Comment by Gustry** [comment]
@ismailsunni I'm reading again this graph and the current behaviour in InaSAFE is matching this : 
https://cloud.githubusercontent.com/assets/1609292/22856309/21aa4f86-f08f-11e6-87ad-1adcc83132f2.png

But I agree, it's misleading.

**Comment by Charlotte-Morgan** [comment]
Hi @ismailsunni 
In my mind we have 3 ways to calculate values: global default, count on exposure data and rate on aggregation data.
I would expect precedence to be: count if used, rate if used, global default.
I think it is good to calculate these things always to make rich data.
I think we should let the user choose if they want to report on age or gender or vulnerability (this might be an option in the options dialog) - we used to have this before when the calculations and report were all one process.
@samnawi - what do you think about this? ie separate rich data from reporting options

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
If it's the precendence and we want to always calculate the result, InaSAFE is in that state, like @Gustry said.

But since it will confuse the user (set to `do not use` but still calculating those things), we need to put the help / notes.

cc @timlinux

**Comment by Charlotte-Morgan** [comment]
yes - do not use means do not use the count or ratio.
The options dialog should ask - do not report

**Comment by Charlotte-Morgan** [comment]
thanks @ismailsunni - I will look more later this week and provide a note for users if its still not clear

**Comment by Charlotte-Morgan** [comment]
Hi @ismailsunni - I think the change you have made is fine. Maybe we can add a little more text to provide instruction to the user.
Maybe add: By default, InaSAFE will calculate the default ratio however users have the option to include this in the analysis report. If you do not want to see the default results in the report choose "do not report".
I think it belongs with the text in the red box or below.
![image](https://user-images.githubusercontent.com/5743135/28608405-9485c5a6-7223-11e7-998c-f7b7ac650b59.png)

**Comment by ismailsunni** [comment]
The text has been added, by me, but I forget :D. Closing this.
