### ISSUE TITLE
Report Enhancement

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#4134]
### Problem
Currently, there are some enhancements that we can give to the analysis report. i.e:
* standardising each section title in the report https://github.com/inasafe/inasafe/issues/4134#issuecomment-300118593
* sectioning and ordering the items in notes and assumptions https://github.com/inasafe/inasafe/issues/4138
* sectioning and ordering the items in action checklist https://github.com/inasafe/inasafe/pull/4088
* rich reporting https://github.com/inasafe/inasafe/issues/4070 https://github.com/inasafe/inasafe/issues/4069

### Expected Behaviour
We have a good report.

### Environment
* InaSAFE : 
* QGIS : 
* OS : 
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
### Proposed Solution
@ivanbusthomi to implement the idea into the prototype of the report and share it here, and to communicate with @myarjunar. More details are coming.
___
**CC** @Charlotte-Morgan @timlinux @myarjunar

**Comment by Charlotte-Morgan** [comment]
thanks @ivanbusthomi - I know you have been working on this alrady and discussing with @myarjunar. We need to document and share this discussion so that we can schedule the implementation in weekly planning meetings.

Please share a pdf that you have as a work in progress or some screenies of the version with my scribble on it so that we can see where things are up to. This will also save people providing the same feedback on 4.1 reports

**Comment by ivanbusthomi** [comment]
Some examples of our section title in the report at the moment look like this (using flood on population analysis):
* Detailed age report
* Detailed gender report
* Detailed minimum needs report

I think it will be good for us to also emphasise the idea that it is an estimated result that comes from the analysis. So my proposal is to change the wording of the above examples to this respectively:
* Estimated number of people displaced by age in each aggregation area
* Estimated number of people displaced by gender in each aggregation area
* Estimated number of minimum needs per week

My other suggestion is to also add some subtitle each section. For example:
![image](https://cloud.githubusercontent.com/assets/7351977/25845103/dd4c558c-34d6-11e7-9f76-d0b4ed047ed0.png)
But if the information is considered to be duplicated with the title, then maybe it is better to keep the information just in the title. :smile: 

The other thing that we also need to consider is about the information "0" and "No data" rows/columns. 
![image](https://cloud.githubusercontent.com/assets/7351977/25845520/6db93418-34d8-11e7-84ad-77727c2c4e7d.png)

While it is good to show the information below the table, I think it will be better to put the information along with other note and assumptions, to make it look tidier and less redundant information showing in the report

**Comment by Charlotte-Morgan** [comment]
Thanks @ivanbusthomi - I like these suggestions but I agree that the extra subtitle is a bit of duplication.
Have you shared your 'template' to @myarjunar and will it be possible to implement these changes soon?

**Comment by Charlotte-Morgan** [comment]
In addition: if the text in the blue bar is changed to say something like
"Estimated number of people displaced by age and aggregation area"
then we would no longer need to mention 'displaced' or 'count' for each column heading. Column heading would become simply the age group in this example.
![image](https://cloud.githubusercontent.com/assets/5743135/26197639/2358fbc6-3bed-11e7-891b-aa09857e2d36.png)

**Comment by Charlotte-Morgan** [comment]
hi @myarjunar and @ivanbusthomi - can you please advise if this work will be in 4.1?
cc @timlinux

**Comment by ivanbusthomi** [comment]
Hi @Charlotte-Morgan - so this is the status of this ticket after the 4.1 release:

- [x] Standardising table title
![image](https://cloud.githubusercontent.com/assets/7351977/26714793/436f7a78-479d-11e7-8e17-6efec9afc9a6.png)
![image](https://cloud.githubusercontent.com/assets/7351977/26714831/7070533a-479d-11e7-8272-39d2d10698e9.png)

- [x] Sectioning notes and assumptions
![image](https://cloud.githubusercontent.com/assets/7351977/26715032/43ed666c-479e-11e7-8ffb-d281ccc938d8.png)

- [x] Sectioning action checklist
![image](https://cloud.githubusercontent.com/assets/7351977/26715178/d8496b4e-479e-11e7-86d0-d2d7940a45fe.png)

- [x] Rich reporting and detailed population vulnerability report (and also table title standardisation)
![image](https://cloud.githubusercontent.com/assets/7351977/26715399/cf0f871a-479f-11e7-903f-13be4680a1d7.png)
![image](https://cloud.githubusercontent.com/assets/7351977/26715496/20e3e8ec-47a0-11e7-806c-7d15b2745813.png)
![image](https://cloud.githubusercontent.com/assets/7351977/26715555/5315161a-47a0-11e7-9b53-335b919d5048.png)

I think we can close this ticket, and potentially also the tickets that were referenced above. What do you think?

CC: @samnawi @myarjunar @timlinux
