### ISSUE TITLE
Section for the notes and assumptions

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#4138]
### Problem
We need to categorise the notes and assumptions so that it will be easier to be read and understand.

### Expected Behaviour
The notes and assumptions could easily be read

### Proposed Solution
We can implement some sections like the one that we are going to implement on action checklists. This is the rough idea of how it will looks. It will contains `General Notes`, `Caveats`, `Hazard` and `Exposure` sections. 
![image](https://cloud.githubusercontent.com/assets/7351977/25847730/7d9b5510-34e1-11e7-85a2-9a40603031d0.png)
The order of the item for the each section shown in the image above is just a sample.
___
**CC** @Charlotte-Morgan @timlinux @myarjunar

**Comment by timlinux** [comment]
Good idea. @myarjunar are we going to be able to squeeze this in by 4.1 though? Can you give an indication of how much work it will be?

**Comment by myarjunar** [comment]
closed in #4131
