### ISSUE TITLE
Use Percentage for Ratio

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4145]
### Problem
Currently, we use (0.0 - 1.0) for representing ratio. It's better to use percentage for the ratio. We can still store the value like now (0.0 - 1.0), but we show in the spinbox by using percentage. We can use this approach:

http://stackoverflow.com/questions/19172262/pyqt4-qspinbox-value-format

We need to decide whether we want it in `parameters` or in InaSAFE base code.

Note from @Charlotte-Morgan 
> but i think its a good bug fix for a rainy day

**Comment by Charlotte-Morgan** [comment]
I think we do need to review the way we use ratio.
In general we are using it as a proportion of 1; where a percent is a proportion of 100.
We do not use it as a true ratio; ie 1 per 100 or 1 per 1000

**Comment by ismailsunni** [comment]
Duplicate with #4508. I am closing this since the discussion in the other ticket is happening :)
