### ISSUE TITLE
Infographic result show unusual display

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#4146]
### Problem
I get the unusual display from infographic report. The vulnerability group (Gender, Age) and Minimum Needs has disappear.

![image](https://cloud.githubusercontent.com/assets/13621886/25894236/42b56dcc-35a5-11e7-9c22-3a7794c23a23.png)

### Expected Behaviour
The infographic result can display in normal report.

### Environment
* InaSAFE : 4.1.0b0
* QGIS : 2.14.10
* OS : Win-7 Professional/ 64-bit RAM 12GB
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : population raster
  * Hazard : Ambon tsunami raster
  * Aggregation : no

### Proposed Solution
Make it happy

**Comment by timlinux** [comment]
@myarjunar can you look at this when you get in tomorrow please?

**Comment by Charlotte-Morgan** [comment]
hi @myarjunar and @timlinux - is there an update on this issue?

**Comment by timlinux** [comment]
We are going to take a different approach here and implement the infographic as qpt layouts. @myarjunar to implement

**Comment by myarjunar** [comment]
closed in #4353
