### ISSUE TITLE
Analysis report shows unusual display

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#4148]
### Problem
Might be related to the issue in #4146, the analysis report also shows some tables that have a strange styling. 

![image](https://cloud.githubusercontent.com/assets/7351977/25938829/e05e293c-365a-11e7-87fc-dec59a017ab9.png)

### Expected Behaviour
The reports should have a nice styling.

### Environment
* InaSAFE : 4.1.0b
* QGIS : 2.14
* OS : 
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : Population
  * Hazard : Flood
  * Aggregation :Yes
  * Extent : 
  
Checklist (if applicable): 
* [x] Did you try to run it in debug mode ?
* [x] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
Make it happy

**CC** @Charlotte-Morgan @timlinux @myarjunar @samnawi @felix-yew

**Comment by timlinux** [comment]
Duplicates #4129 - see #4147 I think we can close this - can you confirm please?

**Comment by ivanbusthomi** [comment]
Thank's @timlinux, closing this now.
