### ISSUE TITLE
We need to display the demographic group help text 

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#4151]
### Problem

Demographic group's field's help text should be shown in the help window and also in the field mapping tool under each concept like this:

![screen shot 2017-05-11 at 4 13 04 pm](https://cloud.githubusercontent.com/assets/178003/25953836/d7022a82-3664-11e7-9ab3-2709eb508644.png)

## History

Based off discussion with @Charlotte-Morgan today.

**Comment by ismailsunni** [comment]
Done for the field mapping (below the field list)
