### ISSUE TITLE
Impact on roads/bridges/fly-overs and Network Analysis

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#416]
# General Functionality
1. Impacted roads structure (it can be roads/bridges/fly overs) are identified. The type of 'roads' structure in OSM data needs to be discussed.
2. Generally, make a function to give a 'safe' route from point A to point B given the conditions from 1
# Detailed Functionality
- Roads impacted
- Roads for evacuation
- Roads to get supplies into the hazard zone
# CC

@timlinux @vanpuk @Charlotte-Morgan 

note: Updated Feb 7, 2014 by @akbargumbira

**Comment by timlinux** [comment]
Note in the notes overhaul in V3.5 we have added a caveat that flyovers etc are not modelled.

**Comment by timlinux** [comment]
Closing as old, no details, no active requirement. Post 4.0 it should be more easy to do this, but not for now.
