### ISSUE TITLE
We need icons to vulnerability gender group

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#4165]
### Problem
We will have need icons to support the infographic report in a new population analyisis result in InaSAFE latest version. One of the new population analysis result, we will have a vulnerability gender group that consist of: `female`, `child bearing age`, and `pregnant and lactating woman`. 
Problem, we still need icons for `lactating`.

### Expected Behaviour
We must have `lactating` icon to support the vulnerability gender group icon. 

### Proposed Solution
Make it happy 😄 

### Cc:
@Charlotte-Morgan @timlinux @myarjunar

**Comment by Charlotte-Morgan** [comment]
hi @felix-yew - thanks for writing up this ticket and reviewing available icons. If we have 2 icons (one for pregnant and one for lactating) and then combine those same ones to make pregnant / lactating it would be better than something completely different.
Can you please look for icons of a similar style to the ones we already have ? I think the UNOCHA  / noun project might have something suitable. please KISS :) 
I propose we use something that is easily available if possible.

**Comment by felix-yew** [comment]
Hi @Charlotte-Morgan - for the `lactating` icon, I get the similar style and I think it is suitable from https://thenounproject.com/search/?q=breastfeeding&i=637611
![lactating_resize](https://cloud.githubusercontent.com/assets/13621886/26092673/7e49d0d0-3a3c-11e7-9887-8eac6dfd4a43.png)
This is the file
[PNG_SVG_format_noun_637611_cc.zip](https://github.com/inasafe/inasafe/files/1003398/PNG_SVG_format_noun_637611_cc.zip)

**Comment by Charlotte-Morgan** [comment]
nice - thanks @felix-yew

**Comment by Charlotte-Morgan** [comment]
@felix-yew: do you have a combined pregnant / lactating icon too?

**Comment by felix-yew** [comment]
Hi @Charlotte-Morgan - Sorry I reopen this ticket to make sure we also need an icon for pregnant & lactating women. I have create an icons pregnant & lactating women.
PNG format (I modify the lactating icon from above)
![pregnant_lactating](https://cloud.githubusercontent.com/assets/13621886/26304403/5f107cb8-3f15-11e7-8ce2-62ece7dbe18c.png)
SVG format [pregnant_lactating.zip](https://github.com/inasafe/inasafe/files/1018485/pregnant_lactating.zip)

and also modify the lactating women
PNG format
![lactating](https://cloud.githubusercontent.com/assets/13621886/26304485/c91b6b18-3f15-11e7-98c2-cce9b45af872.png)
SVG format [lactating.zip](https://github.com/inasafe/inasafe/files/1018492/lactating.zip)

I have updated the icon in Minion.

**Comment by Charlotte-Morgan** [comment]
nice thank you @felix-yew
