### ISSUE TITLE
Add earthquake notes to help file

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4174]
It would be good to add some notes to the help file about the earthquake fatality models; especially the default model and any limitations.

Please look at remmed out notes in definitions/earthquake.py for existing text supplied by @hadighasemi

**Comment by Gustry** [comment]
I added these notes to the help file I think.
Is it not 6.2.10.1.2 ?
<img width="748" alt="screen shot 2017-05-17 at 15 28 31" src="https://cloud.githubusercontent.com/assets/1609292/26145126/844d57fc-3b15-11e7-972a-3c9ca863186a.png">

**Comment by Charlotte-Morgan** [comment]
There are a heap of other notes including references, parameters, limitations and caveats that I think might be good to share in the help.
