### ISSUE TITLE
Earthquake models not rates

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4193]
Pls change the text in the earthquake fatality rates to say ... fatality model.
ie the word model is better than the word rates

all this stuff ...
![image](https://cloud.githubusercontent.com/assets/5743135/26344192/f6a50036-3fc8-11e7-9519-6558aef467c6.png)
 and everywhere else ... it is used

**Comment by Gustry** [comment]
We changed the display name.
