### ISSUE TITLE
Options: add vulnerability groups

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4194]
Sunni - pls fix what Tim forgot :)
I think the non-group fields is not required and could sections for age vulnerability ratio and then gender vulnerability ratio. 
![image](https://cloud.githubusercontent.com/assets/5743135/26344055/7989d41e-3fc8-11e7-9f39-f176ec060336.png)

**Comment by ismailsunni** [comment]
Done in #4195
