### ISSUE TITLE
Missing information from the report in the Population analysis

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#4209]
### Problem
Currently, some information is missing from the population analysis. This is the examples of the tables that appear in the report

* Detailed gender report
![image](https://cloud.githubusercontent.com/assets/7351977/26390676/cfdc636a-4089-11e7-980c-b1199709b431.png)
the information about the _hygiene pack_ and _additional rice for pregnant woman_ are missing. I used the global default for gender ratio and gender vulnerability ratio.

### Expected Behaviour
We should show information that is useful to the user.

### Environment
* InaSAFE : 4.1.0b0
* QGIS : 2.14.10
* OS : Windows
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : Population raster
  * Hazard : Tsunami raster
  * Aggregation :Yes
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
Make it Happy

---
@Charlotte-Morgan @timlinux @samnawi @ismailsunni @felix-yew @myarjunar @Gustry

**Comment by samnawi** [comment]
We just see the result in the attribute table
![image](https://cloud.githubusercontent.com/assets/8871958/26391504/4022aba4-408d-11e7-8e6c-3e8727e0983c.png)

**Comment by myarjunar** [comment]
close in #4337
