### ISSUE TITLE
Behaviour of Pregnant, Lactating, and Additional Rice

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#4210]
### Problem
1. For Additional Rice
Currently, If I set Pregnant and Lactating as combine parameter, I can see additional rice in the result
![image](https://cloud.githubusercontent.com/assets/8871958/26391845/8f873dc6-408e-11e7-9b02-9eff7f130f8a.png)
![image](https://cloud.githubusercontent.com/assets/8871958/26391900/c57da9f6-408e-11e7-998f-d88e4fab525e.png)

If I set Pregnant and Lactating separated, I cannot see additional rice in the result
![image](https://cloud.githubusercontent.com/assets/8871958/26392010/39539822-408f-11e7-9561-025373de1f09.png)
![image](https://cloud.githubusercontent.com/assets/8871958/26392047/5a296bc6-408f-11e7-83f9-99913aa7545f.png)

2. Also if the user set the pregnant and lactating (both of joined and separated), how should InaSAFE do the analysis, to calculate the additional rice? Moreover, if the user set both of them with the different sum (sum of separated P & L is not same with joined P & L). 
Currently, seems like InaSAFE calculate additional rice using joined P & L.
![image](https://cloud.githubusercontent.com/assets/8871958/26392259/2a8599d4-4090-11e7-8388-e827b96bb5c9.png)
![image](https://cloud.githubusercontent.com/assets/8871958/26392291/449c82ce-4090-11e7-9236-ee63e91dc525.png)

**Relevant Ticket**
#4069 #4092

### Expected Behaviour
Make it make sense

How about you @Charlotte-Morgan?

### Environment
* InaSAFE : 4.1
* QGIS : 2.14
* OS : Win 7 64 bit
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : Jakarta Population
  * Hazard : Flood
  * Aggregation : Jakarta Village
  * Extent : 
  
### Proposed Solution
Make it Happy

cc : @ismailsunni @timlinux @ivanbusthomi @felix-yew @fredychandra

**Comment by ismailsunni** [comment]
Hi @samnawi 
Yes, you are right. Currently InaSAFE (develop) only calculate the additional rice when there is `pregnant and lactating` ratio.

I can make it also calculate when you only have `pregnant` or/and `lactating` ratio.

If the user have `pregnant and lactating`, `pregnant`, and `lactating` ratio, I haven't decided how it will behave. You can decide which behaviour it will be:
- use `pregnant and lactating`
- use `pregnant` and `lactating`

which one?

**Comment by ismailsunni** [comment]
Note:
- We agree to use only `pregnant` and `lactating` only to calculate the addtional rice.
- We remove `pregnant_and_lactating` concept from InaSAFE

based on discussion with @samnawi @Charlotte-Morgan and @ismailsunni

**Comment by Charlotte-Morgan** [comment]
thanks @ismailsunni

**Comment by ismailsunni** [comment]
Implemented in #4222. Closing this.
