### ISSUE TITLE
Need more information/documentation on how InaSAFE works per function

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#422]
This is about giving contextual help on impact functions from within the dock.
Maybe a small link next to the impact function combo.
Also expanded out from current list of impact functions (impact_function_doc.py)

It requires #186 to be done.

Also put this information into the metadata section of the report.

**Comment by Charlotte-Morgan** [comment]
@easmetz  - here is another one for you

**Comment by Charlotte-Morgan** [comment]
hi @ivanbusthomi - as discussed we would like to make some progress on this for our rich reporting.
I think the first step is to look at each of the IF and see if they have a description of how they work.
Maybe the earthquake on people impact functions are best in this regard.
You may also look at the notes on the wallpaper to see if we have any details in our current reports.

For now these are the steps:
- [ ] do a stock take and let us know what you find.
- [ ] write a couple of sentences about how each IF works
- [ ] let me know and we will work out where these should be added to the code.

The idea is that these can be tokens for future rich reporting ....

@timlinux @easmetz  FYI

**Comment by ivanbusthomi** [comment]
Hi @Charlotte-Morgan 
> do a stock take and let us know what you find.

So I did a quick look (which actually took quite a while) on the IF in \inasafe\safe\impact_functions\. What I found is just like what @timlinux in this comment https://github.com/inasafe/inasafe/issues/3057#issuecomment-235098978
> all cases except EQ IF's impacts calculated are based on direct overlay / interpolation calculations and not on empirical analysis.

While EQ IF provides a clear explanation of how it works, I can't really find any specific information on how the other IF works. My current guess for the moment is like what Tim said, it calculates based on the overlay / spatial analysis operation between the hazard and exposure layer.

---
@timlinux  @easmetz

**Comment by timlinux** [comment]
Note that in #3548 I added detailed overview of the analysis process in definitions / docs. Closing this out for now. We can revisit adding more hazard specific methodology in the future.
