### ISSUE TITLE
Not all population included in displaced calculation EQ raster on pop raster

### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe#4220]
### Problem
Running EQ raster on population raster, many population cells in MMI 6 (100% displacement) showed as 0 displaced population in the people displaced output layer. In this screenshot, the grey-white cells are displaced and black not displaced. All the black population in yellow MMI should be displaced but is not. 

<img width="796" alt="screen shot 2017-05-25 at 14 49 39" src="https://cloud.githubusercontent.com/assets/496911/26441344/52315ca0-415a-11e7-85fa-6a0ef3dea5fe.png">

### Expected Behaviour

All cells with population > 0 should show as displaced, in an MMI zone with any displacement. 

### Environment
* InaSAFE : 4.1 master
* QGIS : 2.18.2
* OS : OSX
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : attached
  * Hazard : attached
  * Aggregation : n/a
  * Extent : n/a
  
[Archive.zip](https://github.com/inasafe/inasafe/files/1028399/Archive.zip)

Checklist (if applicable): 
* [x] Did you try to run it in debug mode ? Debug mode broken....
* [x] Is the data available ? attached
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
ensure all cells are included. No rounding should take place until reporting.

**Comment by Gustry** [comment]
I'm closing this issue. This is not relevant anymore with InaSAFE 4.2
