### ISSUE TITLE
improve EQ raster on population raster performance

### ISSUE THREAD

**Issue by gubuntu** [inasafe/inasafe#4238]
This analysis took 19h

<img width="795" alt="screen shot 2017-05-28 at 10 23 35" src="https://cloud.githubusercontent.com/assets/496911/26527275/a92ac5b8-4390-11e7-83a2-83e4026efecc.png">

[Analysis Log.csv.zip](https://github.com/inasafe/inasafe/files/1034030/Analysis.Log.csv.zip)

InaSAFE 14.1 master
QGIS 2.18.2

**Comment by Charlotte-Morgan** [comment]
hmm - have you considered testing with the QGIS LTR :)

**Comment by gubuntu** [comment]
this is probably moot since raster earthquake on raster population on its way out.

**Comment by Gustry** [comment]
Yes, I will remove the special EQ function tomorrow, the PR is nearly finished: https://github.com/inasafe/inasafe/pull/4257

So you will need to test again with the new version.
