### ISSUE TITLE
Inappropriate Aggregation ID in the result with the original

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#4242]
### Problem
I already set the Aggregation ID in the keyword, but seems like not show up in the result. 
I just see the ID that is generated from the InaSAFE.

![image](https://files.gitter.im/inasafe/inasafe/1aGz/image.png)
![image](https://files.gitter.im/inasafe/inasafe/xwBe/image.png)

### Expected Behaviour
The aggregation ID should be suitable with the original ID.

### Environment
* InaSAFE : 4.1
* QGIS : 2.14
* OS : Win 7 64 bit
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : Population
  * Hazard : Earthquake raster and Flood
  * Aggregation : Indonesia Village
  * Extent : -
  

### Proposed Solution
Make it happy

cc : @Gustry

**Comment by Gustry** [comment]
This should be fixed in the develop branch now.
