### ISSUE TITLE
EQ analysis with Pregnant and Lactating in the keyword not generating map and detail breakdown report

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#4243]
### Problem
When I run EQ analysis with pregnant and lactating is set-up in the aggregation keyword, I got a strange behaviour from InaSAFE.
![image](https://cloud.githubusercontent.com/assets/8871958/26577461/a4ea510e-4556-11e7-9e91-0558ecd67eb6.png)

In the report, InaSAFE not generating information of the detailed breakdown.
![image](https://cloud.githubusercontent.com/assets/8871958/26577682/6f9afb4c-4557-11e7-9ea3-42ab3ca5b290.png)

P & L was setup in the keyword : 
[use P L setup.pdf](https://github.com/inasafe/inasafe/files/1037865/use.P.L.setup.pdf)
P & L was not setup in the keyword : 
[without P L setup.pdf](https://github.com/inasafe/inasafe/files/1037867/without.P.L.setup.pdf)

When I push print button, it just generates report, provenance and action checklist without the map.
![image](https://cloud.githubusercontent.com/assets/8871958/26577870/ff8206c4-4557-11e7-8c0e-8997fc5e6b4c.png)

### Expected Behaviour
I should be working properly.

### Environment
* InaSAFE : 4.1
* QGIS : 2.14
* OS : Win 7 64 bit
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : raster population
  * Hazard : raster earthquake
  * Aggregation : BPS village
  * Extent : 
  
Checklist (if applicable): 
* [x] Did you try to run it in debug mode ? Yes, but it stopped at 100% without generate a result
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
Make it happy

cc : @timlinux @ismailsunni @myarjunar @Gustry  @Charlotte-Morgan @ivanbusthomi @felix-yew

**Comment by myarjunar** [comment]
Thanks, gotta take a look at it asap.

**Comment by myarjunar** [comment]
Hi @Gustry , I've checked this problem and it turns out that currently, we don't have the inasafe_fields keywords for 'pregnant_displaced_count_field' and 'lactating_displaced_count_field' in the aggregation summary keywords, and we need it to show the fields in the report. How can we achieve this?

**Comment by myarjunar** [comment]
@samnawi Could you check for me whether `InaSAFE Impact Report class initialised` is printed twice in the log message?

**Comment by samnawi** [comment]
Hi @myarjunar this is my InaSAFE log message
```

**Comment by Charlotte-Morgan** [comment]
hey @myarjunar and @Gustry ; it is possible to get this ready for a bug fix release as soon as 4.1 is released?

**Comment by ismailsunni** [comment]
@myarjunar 
You can add them in the list in `safe/definitions/fields.py` in `aggregation_summary_fields` list. Please check the other field list also to match with the current state (We add many things, I am not sure they have been added to the lists)

**Comment by Gustry** [comment]
and in `fields_groups.py`

**Comment by myarjunar** [comment]
@Charlotte-Morgan yes, it's ready in https://github.com/inasafe/inasafe/pull/4244, could you please try it @samnawi?

**Comment by samnawi** [comment]
Hi @myarjunar I already tried your PR in #4244 
LGTM.

**Comment by myarjunar** [comment]
closed in #4244
