### ISSUE TITLE
Badan Geology Landcover classification update from PVMBG

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#4246]
### Problem
In our previous workshop with our partner from PVMBG, we have the chance to show the InaSAFE realtime and also demo the InaSAFE desktop. At that workshop, we received a feedback regarding the land cover classification. They suggested changing the class `water supply` to be just `water`. 

### Expected Behaviour
We have an updated classification.

### Proposed Solution
Make it happy.

---
**CC**: @Charlotte-Morgan @samnawi @felix-yew @fredychandra @timlinux @myarjunar @estukriswati @RikkiWeber

**Comment by Gustry** [comment]
You can update it if you want in `safe/definitions/exposure_classifications`. Don't change the key, just remove 'supply` from the name.

**Comment by ivanbusthomi** [comment]
Hi @Gustry - I have tried changing the name in the exposure_classifications , but the column name still not using the name that I edited. This is how it looks like:
![image](https://cloud.githubusercontent.com/assets/7351977/26775496/6e181fe6-49ff-11e7-8c68-bfe18570313e.png)
