### ISSUE TITLE
The result became zero in age breakdown when setting count field in exposure KW

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#4248]
### Problem
When I try to run the flood hazard raster with population vector, and setting keyword wizard of exposure then fill the age count tab in the field of infant, child, adult, and elderly, except youth field. 
![image](https://user-images.githubusercontent.com/13621886/26861333-53cf1c88-4b6d-11e7-8d00-ec40214fca99.png)
But, I get zero result in the impact report in demographic breakdown section, except youth get the result although I have not set the count field.
![image](https://user-images.githubusercontent.com/13621886/26861400-b412ebf6-4b6d-11e7-868d-ffbf1f6904f2.png)

### Expected Behaviour
The impact report should get the result when the user setting the count field in the exposure keyword.

### Environment
* InaSAFE : 4.1.0
* QGIS : 2.14.14
* OS : Win 7 Pro-64 bit/ RAM 12GB
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : I have a problem to upload the zip file :sweat: 
  * Hazard : 

### Proposed Solution
Make it happy :smile: 

### Cc : @Charlotte-Morgan @samnawi @ivanbusthomi @ismailsunni @timlinux @Gustry

**Comment by ismailsunni** [comment]
The data that @felix-yew use:
[Jakarta_Flood_HKV_WGS84.zip](https://github.com/inasafe/inasafe/files/1056924/Jakarta_Flood_HKV_WGS84.zip)
[DKI_Jakarta_Population_Dukcapil_2013_WGS84.zip](https://github.com/inasafe/inasafe/files/1056925/DKI_Jakarta_Population_Dukcapil_2013_WGS84.zip)

**Comment by felix-yew** [comment]
thank you mas @ismailsunni and this data also I share in Real World Data.

**Comment by samnawi** [comment]
Hi @ismailsunni I also got this error message when using flood data from petabencana.id.
![image](https://user-images.githubusercontent.com/8871958/26872128-a7ecbce4-4b9f-11e7-8e7b-d8b3ba237b59.png)
![image](https://user-images.githubusercontent.com/8871958/26872137-b8d51308-4b9f-11e7-8f38-45268143b874.png)

**Comment by samnawi** [comment]
Hi @ismailsunni I think for this case, when we set the count as "do not use", InaSAFE will automatically set it to global default.

![image](https://user-images.githubusercontent.com/8871958/26873758-295b3bb6-4ba5-11e7-840d-344cbe6fb334.png)

**Comment by Gustry** [comment]
> I think for this case, when we set the count as "do not use", InaSAFE will automatically set it to global default.

For now, it's not a bug @samnawi , it's a feature ;-)
We already got some discussions about this : https://github.com/inasafe/inasafe/issues/4127#issuecomment-303956765 (cf 

InaSAFE is following this logic : https://cloud.githubusercontent.com/assets/1609292/22856309/21aa4f86-f08f-11e6-87ad-1adcc83132f2.png
