### ISSUE TITLE
We need to implement an InaSAFE expression group

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#4252]
@gustry to make first pass implementation

Start by exposing everything from the substitution list.

Make sure everything has help files too please.

**Comment by Gustry** [comment]
This is done I think in the PR above. @myarjunar is working on some new expressions. We need to check that we have what we need for now.

**Comment by timlinux** [comment]
@myarjunar  in the templates can you please remove any substitutions in favor of expressions. Please see https://github.com/inasafe/inasafe/wiki/Map-Composer-Templating#element-tokens - I would like to see all of this Replacement Tokens removed from the above page and implemented rather as QGIS / InSAFE Expressions which can be inserted into the template.

Also for the logos and images which can have their paths set via an expression, they should be remove from the above page and replaced with expressions in the template.

We also need to get the expressions and their help into the definitions_help please @Gustry

**Comment by Gustry** [comment]
We only remove tokens only from existing templates @timlinux? But we keep them in the code, because if we remove them, then it's a API break.

I added expression help in the dialog. We may need some polishing. Like translations will be missing with the current implementation.
