### ISSUE TITLE
Wrong Calculation in the Total Structures Report

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#4258]
### Problem
When I run the generic hazard with structure point in TTU, I get some wrong calculation in the total structures report in Analysis detail. If you see the result in the image below
![image](https://user-images.githubusercontent.com/13621886/26970831-ea5248ce-4d34-11e7-99f5-419ad0a82321.png)
The calculation in total affected and not affected was wrong, or maybe swapped out in the code.

But strangely when trying on Nagekeo project, run the generic hazard with structure point, I get the correct result.
![image](https://user-images.githubusercontent.com/13621886/26971151-48066878-4d36-11e7-8a45-6785b43beb2e.png)

### Expected Behaviour
The total structures report should give correct results in each section.

### Environment
* InaSAFE : 4.1.0
* QGIS : 2.14.14
* OS : Win 7 Pro 64-bit/RAM 12GB
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : TTU_Infrastructure_WGS84
  * Hazard : TTU_Landslide_Vulnerability_WGS84
I share in Real World Data :\Real World Data\Generic\TTU

### Proposed Solution
Make it happy

#### Cc
@Charlotte-Morgan @samnawi @ivanbusthomi @timlinux @ismailsunni @Gustry

**Comment by timlinux** [comment]
@myarjunar I think it is better if you look at this first and then pass back to @Gustry if the problem is in the calculations themselves.

**Comment by ismailsunni** [comment]
@felix-yew please review this ticket. It's already merged. Just tell @myarjunar if you find something funny. Otherwise, we can close this one.

**Comment by felix-yew** [comment]
Okay, I will check it

**Comment by felix-yew** [comment]
Yes, this issue has been fixed, I get the correct result
![image](https://user-images.githubusercontent.com/13621886/28007072-3594b574-657c-11e7-8a6c-6518a67e6feb.png)

:+1: LGTM

Thank you
