### ISSUE TITLE
RFC: Direction and distance tool

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4262]
We need a new analysis tool that calculates distance and direction from a point hazard. This tool will be based on the functionality in Earthquake  realtime analysis and will allow us to migrate realtime analyses to safe core.

## Requirements:
This tool will calculate the distance and direction from point hazards such as volcano vent and earthquake epicentre to a point exposure such as populated places or critical infrastructure such as airports.

## Limitations:
The aim is to replicate existing realtime analysis not build a mega do everything tool.

**Comment by timlinux** [comment]
@ivanbusthomi some useful links for you:

https://github.com/inasafe/inasafe/blob/realtime/realtime/shake_event.py#L442

This function calls out to various interesting bits - including the cardinality and distances:

        The following fields will be created for each city feature:
            QgsField('id', QVariant.Int),
            QgsField('name', QVariant.String),
            QgsField('population', QVariant.Int),
            QgsField('mmi', QVariant.Double),
            QgsField('dist_to', QVariant.Double),
            QgsField('dir_to', QVariant.Double),
            QgsField('dir_from', QVariant.Double),
            QgsField('roman', QVariant.String),
            QgsField('colour', QVariant.String),
        The 'name' and 'population' fields will be obtained from our geonames
        dataset.
        A raster lookup for each city will be done to set the mmi field
        in the city feature with the value on the raster. The raster should be
        one generated using :func:`mmiDatToRaster`. The raster will be created
        first if needed.
        The distance to and direction to/from fields will be set using QGIS
        geometry API.
        It is a requirement that there will always be at least one city
        on the map for context so we will iteratively do a city selection,
        starting with the extents of the MMI dataset and then zooming
        out by self.zoom_factor until we have some cities selected.
        After making a selection the extents used (taking into account the
        iterative scaling mentioned above) will be stored in the class
        attributes so that when producing a map it can be used to ensure
        the cities and the shake area are visible on the map. See
        :samp:`self.extent_with_cities` in :func:`__init__`.
        .. note:: We separate the logic of creating features from writing a
          layer so that we can write to any format we like whilst reusing the
          core logic.
        .. note:: The original dataset will be modified in place.

**Comment by ivanbusthomi** [comment]
Hi @Charlotte-Morgan and @timlinux ,
this is my to do list for this ticket

- [ ] design the workflow of the tools
- [ ] design the user interface
- [ ] write the function

**Comment by ivanbusthomi** [comment]
Hi @timlinux and @ismailsunni :
What I initially have in mind working on this function is creating it as a tool that can be used by the user through a dialog box, like the multibuffer tool. Do you think the function only something like a postprocessor?

### Workflow
![ddt_diagram](https://user-images.githubusercontent.com/7351977/29602393-28dcf4ee-880a-11e7-995c-1984183d96d6.png)

### UI
![direction_tool_v2](https://user-images.githubusercontent.com/7351977/29602494-8a16fb06-880a-11e7-91b6-7069d30ad360.png)

 ### WIP branch
https://github.com/ivanbusthomi/inasafe/tree/direction_tool

**Comment by ivanbusthomi** [comment]
Following our last discussion regarding this tools, this is the UI design changes that I proposed for the shakemap converter tools.
![image](https://user-images.githubusercontent.com/7351977/31266877-1e2b51cc-aaa0-11e7-98c0-c6819363eac4.png)

**Comment by timlinux** [comment]
Just based on our discussion today here is the updated workflow that we will implement (where calcs are done in a post processor):

![bearinganddistancepostprocessor](https://user-images.githubusercontent.com/178003/32264612-394f4c2c-bee8-11e7-8034-daa0094b5321.png)

**Comment by timlinux** [comment]
This means that @myarjunar will need to provide the QGIS Expression at the end of the workflow

**Comment by Gustry** [comment]
@ivanbusthomi made the PR #4599 to add these postprocessors.

I'm adding expressions in the coming PR
