### ISSUE TITLE
We need to support multi band rasters

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#4263]
This will fix issues where users have rasters with transparency layers.

**Comment by ismailsunni** [comment]
From metadata point of view:
1. Should we set the different metadata for all band? Then which one that we want to use in the analysis?
2. Or, we just set one band? It will needs a new attribute to specify which band is the active one
3. Or we set the active band on the fly (when run the analysis). But it may be gives wrong value mapping

**Comment by timlinux** [comment]
Hi @ismailsunni 

I think we just need something which indicates which band contains 'data' (so 2 in your list above).

In the wizard:

> This layer contains more than one band, which band contains the data for this layer to be used in analyses?

**Comment by ismailsunni** [comment]
@timlinux 
Ah I see. It's easier than the other options. Just need to add the band, and use it. Currently, by default is 0th band.

**Comment by Gustry** [comment]
@ismailsunni Let me know when keywords are ready. I will update the impact function

**Comment by Gustry** [comment]
@myarjunar We also need to add to provenance.

**Comment by ismailsunni** [comment]
@Gustry do we have multi band raster? We can create it with QGIS right? :D

**Comment by ismailsunni** [comment]
Related issue: #4087

**Comment by ismailsunni** [comment]
Hi @Gustry I have made a PR to support multi band in metadata and wizard https://github.com/inasafe/inasafe/pull/4301

**Comment by ismailsunni** [comment]
Done in #4301
