### ISSUE TITLE
Typos in the InaSAFE header in QGIS plugin list

### ISSUE THREAD

**Issue by severinmenard** [inasafe/inasafe#4270]
I am not a native English speaker, but I would rewrite:

"InaSAFE is free software that allows disaster managers to study realistic natural hazard impact scenarios for better planning, preparedness and response activities.

Developed for the Indonesian Government - BNPB, Australian Government - AIFDR and DMInnovation and, and World Bank - GFDRR"

this way:

**InaSAFE is a free software** that allows disaster managers to study realistic natural hazard impact scenarios for better planning, preparedness and response activities.

Developed for the Indonesian Government - BNPB, Australian Government - AIFDR **, DMInnovation and World Bank - GFDRR**

**Comment by timlinux** [comment]
> InaSAFE is a free software that allows disaster managers to study realistic natural hazard impact scenarios for better planning, preparedness and response activities.

In English we usually do not refer to 'a software'  - its a collective noun.

Thank you very much for you interest!
