### ISSUE TITLE
'QgsComposerItem' object has no attribute 'setKeepLayerSet'

### ISSUE THREAD

**Issue by mbernasocchi** [inasafe/inasafe#4271]
### Problem
```
composer_map = composition.getComposerItemById(item_id)
    """:type: qgis.core.QgsComposerMap"""
    if composer_map:```
```
this assumes getComposerItemById returns a QgsComposerMap but in my case it returns a QgsComposerItem. why do we make this assumption? Am I missing something?

```
In file "/home/marco/.qgis2/python/plugins/inasafe/safe/report/impact_report.py", line 763, in process_components output = _renderer(self, component)
In file "/home/marco/.qgis2/python/plugins/inasafe/safe/report/processors/default.py", line 403, in qgis_composer_renderer composer_map.setKeepLayerSet(True)
```

### Environment
* InaSAFE :  4.1.1
* QGIS :  2.18.9
* OS : ubuntu 17.4
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ?

**Comment by Gustry** [comment]
Is-this fixed?
I know you did a PR to avoid the python exception, but does it fix the original problem?

Thanks

**Comment by mbernasocchi** [comment]
nope. 
his does not fix the problem which is that getComposerItemById returns
QgsComposerItem and we erroneously expect QgsComposerMap and
QgsComposerLegend.

can't find the comment now, but @lucernae  mentioned it was a bug in qgis api?

**Comment by lucernae** [comment]
I mentioned it on the Pull Request #4280 

The problem comes from Python Bindings from getComposerItemById will always return QgsComposerItem for any (or maybe some) element because it was not type casted in the bindings, so python code doesn't know the original type.
I don't know if it's possible to cast the type from python side. If that's not possible then perhaps we have to fix the binding?

**Comment by Gustry** [comment]
Ok, thanks for your explanations. I will merge the backport to the master branch, but we keep this ticket. We need to fix this as 2.18 is the next LTR in 3 months.

**Comment by Gustry** [comment]
I put the label `Release blocker`, because even if it might be an upstream bug, it's a high priority for us.
I have the same issue with pictures, no more pictures in my report:
```
        image = composition.getComposerItemById(item_id)
        """:type: qgis.core.QgsComposerPicture"""
        if image is not None and path is not None:
            try:
                image.setPicturePath(path)
            except:
                pass
```
`setPicturePath` doesn't exist on my object.

**Comment by timlinux** [comment]
@Gustry what code is this affecting? Infographics stuff? Is this not similar to the SIP error we used to have on Mac  OS which was actually a problem with SIP rather than QGIS?

**Comment by Gustry** [comment]
Every python bindings in the composer, so infographics and map reports.

It's not specific to MacOS as @mbernasocchi has the issue on Linux too.

Can you give your results for 
```
from PyQt4.QtCore import QT_VERSION_STR
from PyQt4.Qt import PYQT_VERSION_STR
from sip import SIP_VERSION_STR
print("Qt version:", QT_VERSION_STR)
print("SIP version:", SIP_VERSION_STR)
print("PyQt version:", PYQT_VERSION_STR)
```

I have:
```
('Qt version:', '4.8.6')
('SIP version:', '4.18')
('PyQt version:', '4.11.4')
```

**Comment by myarjunar** [comment]
I don't have this problem on my machine. 
```
('Qt version:', '4.8.7')
('SIP version:', '4.17')
('PyQt version:', '4.11.4')
```

**Comment by Gustry** [comment]
I just tried an old QGIS app 2.14.8 released in November 2016, map reports were working well but it has the same SIP version:
```
print("Qt version:", QT_VERSION_STR)
('Qt version:', '4.8.6')
print("SIP version:", SIP_VERSION_STR)
('SIP version:', '4.18.1')
print("PyQt version:", PYQT_VERSION_STR)
('PyQt version:', '4.11.4')
import sip
print sip.__file__
/Applications/QGIS.app/Contents/MacOS/../Resources/python/sip.so
```

**Comment by Gustry** [comment]
@myarjunar and I could fix the issue we think. We got a hint from Martin by email, but it was still tricky with these IDs which are strings or integers. Something working for Rohmat was not working for me.

I think this issue can be closed. Let's wait a little to check everything is working nicely
