### ISSUE TITLE
Report does not show all active layers

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#4287]
### Problem

I'm sure we have been here before but this is what I see on my screen:

<img width="874" alt="screen shot 2017-06-27 at 4 04 03 pm" src="https://user-images.githubusercontent.com/178003/27591536-4a23522c-5b52-11e7-937a-598af4164663.png">

And this is what it looks like on the PDF:

<img width="1506" alt="screen shot 2017-06-27 at 4 04 33 pm" src="https://user-images.githubusercontent.com/178003/27591584-647d59f6-5b52-11e7-8e1b-2d229497e4da.png">

Please make the map print match the layers that the user has active in their QGIS project.

**Comment by myarjunar** [comment]
@timlinux I thought we only want to show the context data and the impact layer, and show the hazard data by check the option in InaSAFE option (based on #2920) , is it correct?
