### ISSUE TITLE
Analysis fails when using flood polygons with depth

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#4289]
### Problem

I'm trying to run a scenario (data attached) with flood polygons with depth classes and raster pop. The analysis fails to run properly.

The same data works when I set the flood keywords to wet/dry classes.

[floods.zip](https://github.com/inasafe/inasafe/files/1105560/floods.zip)
[pop.zip](https://github.com/inasafe/inasafe/files/1105564/pop.zip)

There are actually two issues I see:

1) The analysis fails to pull out any affected areas (I believe maybe related to https://github.com/inasafe/inasafe/issues/4288). I think this may be the trigger for item 2 below.

<img width="558" alt="screen shot 2017-06-27 at 7 24 53 pm" src="https://user-images.githubusercontent.com/178003/27601108-5f23634e-5b6e-11e7-8a4f-a431e5c84e7d.png">

You can see that it only produces not exposed categories where according to my data we should have some affected areas too.

2) We are getting a divide by zero during report creation:

From my logs:

```
 2017-06-27 16:22:34,198 - InaSAFE - INFO - Layer saved 17-Analysis Log
2202 2017-06-27 16:22:34,235 - InaSAFE - INFO - ANALYSIS : Styling
2203 2017-06-27 16:22:34,239 - InaSAFE - INFO - The impact function could run without errors.
2204 2017-06-27 16:22:35,278 - InaSAFE - DEBUG - InaSAFE Impact Report class initialised
2205 2017-06-27 16:22:35,370 - InaSAFE - INFO - float division by zero  
```

The python console shows it better but weirdly it is not letting me cut and paste from there (and the dock message flashes on and off too quickly for me to grab it).

<img width="764" alt="screen shot 2017-06-27 at 7 21 40 pm" src="https://user-images.githubusercontent.com/178003/27601153-9166a88e-5b6e-11e7-83e0-85b68a0b9b43.png">

Nice developers guard for divide by zero errors :-P 

### Expected Behaviour

It should just work....

### Environment
* InaSAFE : 4.1 Master
* QGIS : 2.14
* OS : macOS Sierra
* Data attached
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution

**Comment by timlinux** [comment]
@gustry can you look at the first issue above - the second is sorted out with my hay in PR #4290

**Comment by Gustry** [comment]
Nothing related to #4288.

Your flood zip is broken. Can you upload it again ? I would like to check this issue.

**Comment by timlinux** [comment]
[floods.zip](https://github.com/inasafe/inasafe/files/1108417/floods.zip)

The datasets are small enough they will be good to use for a unit test...

**Comment by Gustry** [comment]
Thanks, I'm looking at your issue. BTW, just looking at your screenshot, you need to update your QGIS ;-) You will get a nice vertically aligned attribute table.

**Comment by timlinux** [comment]
>  BTW, just looking at your screenshot, you need to update your QGIS ;-) You will get a nice vertically aligned attribute table.

Updated to 2.14.14 now (nice version number eh?)

**Comment by Gustry** [comment]
I'm starting fixing this issue in the PR above.
It seems a silly mistake ;-) Let's wait for travis, I expect it to fail.

**Comment by Gustry** [comment]
PR merged. I keeping the ticket open to do the frontport.

**Comment by Gustry** [comment]
Fix the division by zero in the PR above. Need to frontport this fix to develop.

**Comment by Gustry** [comment]
Both issues have been front-ported to develop : https://github.com/inasafe/inasafe/pull/4296
