### ISSUE TITLE
Reports are broken

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#4297]
### Problem

When running an analysis the reports are not printing properly. This needs to be fixed ASAP.

<img width="1294" alt="screen shot 2017-07-01 at 9 48 39 pm" src="https://user-images.githubusercontent.com/178003/27765540-510428fe-5eb4-11e7-9f09-6190b77c8f33.png">

SVG's are not showing in the repot on MacOS (I believe it works still on Windows).
The impact layer is not showing the correct symbolization compared to the QGIS main window (shown below for the same analysis as shown in the print report above).

<img width="1674" alt="screen shot 2017-07-01 at 9 48 20 pm" src="https://user-images.githubusercontent.com/178003/27765551-9a15d7b8-5eb4-11e7-856c-39ad5cc83c33.png">

### Expected Behaviour

The report should print exactly what is shown in QGIS after the analysis completes. 

### Environment
* InaSAFE : 4.1.2
* QGIS : 2.14.14
* OS : macOS Sierra
* Data used (filenames and paths so as to reproduce, a project is better):
```
[tsunami padang (Mw8.6)]
exposure = /Users/timlinux/gisdata/InaSAFE/InaSAFEPackages/West Sumatera/02 Exposure Data/Padang_Buildings_WGS84.shp
hazard = /Users/timlinux/gisdata/InaSAFE/InaSAFEPackages/West Sumatera/01 Hazard Data/Padang_Tsunami_Hazard_WGS84.tif
extent = 100.340129, -0.972915, 100.395241, -0.921374
extent_crs = EPSG:4326
```

These data can be obtained here:

  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [x] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

http://data.inasafe.org/InaSAFE%203.5%20Training%20Data/West%20Sumatera.zip

### Proposed Solution

**Comment by ismailsunni** [comment]
Hi @timlinux,

I use the same env as you only different in QGIS (I use 2.14.10). All is good here:

<img width="1427" alt="screen shot 2017-07-03 at 15 41 53" src="https://user-images.githubusercontent.com/1421861/27784941-2f00bfee-6006-11e7-8bfe-19b3b5322dad.png">
