### ISSUE TITLE
How can I get the InaSAFE documentation for coders

### ISSUE THREAD

**Issue by MMANGA** [inasafe/inasafe#4302]
### Problem
I am new user/developer of InaSAFE from Zanzibar Tanzania, as one among the peoples who want to use this great services from you, I need to know how to start to make modification or preparing new plugin based in our environment. 

Regards
```
Copy/paste some InaSAFE logs here if it was an error.
```

### Environment
* InaSAFE : 
* QGIS : 
* OS : 
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ?

**Comment by timlinux** [comment]
Hi @MMANGA Thank you for your ticket - I will be happy to help you during the training course - just tell me what you need to know!

Regards

Tim

**Comment by MMANGA** [comment]
Thanks @timlinux, just setting of InaSAFE together with Architecture of it, others I will take care. I am waiting ...........

**Comment by Gustry** [comment]
Welcome !
