### ISSUE TITLE
Analysis fails when doing floods on OSM buildings for Uganda

### ISSUE THREAD

**Issue by remigio-chilaule** [inasafe/inasafe#4305]
### Problem
I'm using the data set that Tim/Gavin gave us during InaSAFE training in Kampala, July 2017.
Note: When creating the keywords I put all the available building types under the "others" option in value mapping.

[uganda_osm_buildings.zip](https://github.com/inasafe/inasafe/files/1131424/uganda_osm_buildings.zip)

```
In file "C:/Users/Remigio/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1135, in run self._run()
In file "C:/Users/Remigio/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 122, in with_profiling ret = fn(*args, **kwargs)
In file "C:/Users/Remigio/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1340, in _run self.debug_layer(self._exposure_summary, add_to_datastore=False)
In file "C:/Users/Remigio/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1087, in debug_layer check_inasafe_fields(layer)
In file "C:/Users/Remigio/.qgis2/python/plugins\inasafe\safe\gis\sanity_check.py", line 49, in check_inasafe_fields raise InvalidLayerError(message)
```

### Environment
* InaSAFE : 
* QGIS : 
* OS : 
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ?

**Comment by Gustry** [comment]
Same problem as in https://github.com/inasafe/inasafe/issues/4304, I can't replicate really replicate the issue.

Which hazard layer did you use? Flood 2007? Full extent?

I know we have some problems with invalid geometries sometimes, and these issues are difficult to debug.

**Comment by Charlotte-Morgan** [comment]
hi @felix-yew - great if you can take a look at this one too. Kartoza to share the data

**Comment by felix-yew** [comment]
Hi @remigio-chilaule - the zip file that you share only contain the xml file, could you please share the complete data that include the shapefile?

Cc: @timlinux @Gustry

**Comment by timlinux** [comment]
@timlinux to get the data to @felix-yew

**Comment by timlinux** [comment]
To do as bug fix post 4.2 release

**Comment by timlinux** [comment]
@felix-yew the RO BTsync key is BWHM2A7KLHG5LFARSOZMQ4KUL7AM25XM6 (includes the full training course memory stick contents)

**Comment by felix-yew** [comment]
Ok thank you @timlinux - I already add it. It maybe will sync later.

**Comment by Charlotte-Morgan** [comment]
@felix-yew - did you manage to replicate this

**Comment by felix-yew** [comment]
Hi @remigio-chilaule - I try to run flood on buildings, I use:
uganda_flood_2007 --> hazard
uganda_osm_buildings --> exposure
I run it with InaSAFE 4.2.3 it can work properly, eventhough the result is zero for the hazard zone
![image](https://user-images.githubusercontent.com/13621886/31433479-b003be84-aea3-11e7-9ccb-caaab73e4674.png)

**Comment by Gustry** [comment]
Sorry, as we can't replicate the issue, I'm going to close this ticket. Feel free to open a new one if the problem still occurs with more detail. Thanks
