### ISSUE TITLE
Save scenario tool fails

### ISSUE THREAD

**Issue by remigio-chilaule** [inasafe/inasafe#4306]
### Problem

```
An error has occurred while executing Python code: 

UnicodeEncodeError: 'ascii' codec can't encode character u'\xcd' in position 6: ordinal not in range(128) 
Traceback (most recent call last):
  File "C:/Users/Remigio/.qgis2/python/plugins\inasafe\safe\plugin.py", line 888, in save_scenario
    dialog.save_scenario()
  File "C:/Users/Remigio/.qgis2/python/plugins\inasafe\safe\gui\tools\save_scenario.py", line 172, in save_scenario
    parser.write(open(scenario_file_path, 'a'))
  File "C:\PROGRA~2\QGIS2~1.14\apps\Python27\lib\ConfigParser.py", line 412, in write
    key = " = ".join((key, str(value).replace('\n', '\n\t')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xcd' in position 6: ordinal not in range(128)


Python version: 2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)] 
QGIS version: 2.14.16-Essen Essen, 3130f80 

Python Path:
C:/PROGRA~2/QGIS2~1.14/apps/qgis-ltr/./python/plugins\processing
C:/PROGRA~2/QGIS2~1.14/apps/qgis-ltr/./python
C:/Users/Remigio/.qgis2/python
C:/Users/Remigio/.qgis2/python/plugins
C:/PROGRA~2/QGIS2~1.14/apps/qgis-ltr/./python/plugins
C:\PROGRA~2\QGIS2~1.14\bin\python27.zip
C:\PROGRA~2\QGIS2~1.14\apps\Python27\DLLs
C:\PROGRA~2\QGIS2~1.14\apps\Python27\lib
C:\PROGRA~2\QGIS2~1.14\apps\Python27\lib\plat-win
C:\PROGRA~2\QGIS2~1.14\apps\Python27\lib\lib-tk
C:\PROGRA~2\QGIS2~1.14\bin
C:\PROGRA~2\QGIS2~1.14\apps\Python27
c:\progra~2\qgis2~1.14\apps\python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
c:\progra~2\qgis2~1.14\apps\python27\lib\site-packages\markupsafe-0.23-py2.7-win32.egg
c:\progra~2\qgis2~1.14\apps\python27\lib\site-packages\shapely-1.2.18-py2.7-win32.egg
C:\PROGRA~2\QGIS2~1.14\apps\Python27\lib\site-packages
C:\PROGRA~2\QGIS2~1.14\apps\Python27\lib\site-packages\win32
C:\PROGRA~2\QGIS2~1.14\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~2\QGIS2~1.14\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~2\QGIS2~1.14\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:/Users/Remigio/.qgis2//python
C:/Users/Remigio/.qgis2/python/plugins\inasafe
C:\Users\Remigio\.qgis2\python\plugins\inasafe\safe_extras\parameters
C:\Users\Remigio\.qgis2\python\plugins
C:\Users\Remigio\.qgis2\python\plugins\inasafe\safe_extras
C:\PROGRA~2\QGIS2~1.14\apps\qgis-ltr\python\plugins\fTools\tools
C:/REMÃGIO/01_ARQI/02_URBAN/outros/KAMPALA/Dia5_OSM QGIS InaSAFE/FINAL EXAM =)
```

### Environment
* InaSAFE : 
* QGIS : 
* OS : 
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ?

**Comment by ivanbusthomi** [comment]
Hi @remigio-chilaule - could you please paste here the full path of the folder where you want to put the scenario? It seems like the error occured because of the unicode character in the folder name.

**Comment by Gustry** [comment]
@ivanbusthomi We need to remove the 'str' function. Some users have an accent in their path for instance.

**Comment by ismailsunni** [comment]
@ivanbusthomi may be you can try using an accent in when you save the scenario to replicate it.

**Comment by ivanbusthomi** [comment]
Hi @Gustry and @remigio-chilaule , I still can't replicate the error.
I tried using this path to save the scenario, and  no error occured
```D:\temp\REMÃ`GIO\01_ARQI\02_URBAN\outros\KAMPALA\Dia5_OSM QGIS InaSAFE\FINAL EXAM =)\fichiers_à_télécharger```
how about you mas @ismailsunni ?

**Comment by ismailsunni** [comment]
Hmm, i tried in my laptop also, I set it to `~/temp/aååß∂ƒ∆Ω≈/Volcano_Point.txt`, but I can't replicate it.

**Comment by ivanbusthomi** [comment]
After looking at the error code again, it seems like the character that causes the error is `Í`. I tried modifying the directory again and then saving the scenario to that directory, but still got no error.
```D:\temp\REMÍGIO\01_ARQI\02_URBAN\outros\KAMPALA\Dia5_OSM QGIS InaSAFE\FINAL EXAM =)```

**Comment by Gustry** [comment]
I'm not sure, as we can't really replicate the issue, I may have fixed it now. @remigio-chilaule you will have to try (InaSAFE 4.2 will be released end of this month)

**Comment by Gustry** [comment]
No more feedback, I'm closing the issue
