### ISSUE TITLE
Translation for version 4.2

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4312]
### Problem
We need translation be ready for 4.2. Current status per 14 July 2017:
- Indonesian: 109 untranslated strings
- French: 184 untranslated strings

*not as many as I thought 

### Proposed Solution
Since we want to release version 4.2 on 31 July 2017, I propose these dates for the translation:
- [ ] Last day to submit new string: Tuesday, **25 July 2017**
- [ ] Last day to translate (0 untranslated strings): Wednesday, **26 July 2017**
- [ ] Buffer time to do small string update and translation: Thursday - Friday, **27 - 28 July 2017**
- [ ] Release version 4.2: Monday, **31 July 2017**

I have created a wiki if you want to remember what's the translation guidance in https://github.com/inasafe/inasafe/wiki/Translation-Guidelines

cc @timlinux @Charlotte-Morgan @Gustry @myarjunar @ivanbusthomi @felix-yew 

Thanks

**Comment by felix-yew** [comment]
Oke @ismailsunni :+1:

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni - @felix-yew is available to help with the Indonesian translation. He will work on it in between his other activities. @felix-yew - please schedule some time for this this week and next to make sure the strings are happy by 26th July

**Comment by ismailsunni** [comment]
Thanks @felix-yew and @Charlotte-Morgan 
@myarjunar and I will also help translating it (and review it).

**Comment by Gustry** [comment]
Let's close this ticket. ID and FR are both on their way for 4.2
