### ISSUE TITLE
Ability work with other standards (WCS, WFS, etc.)

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#432]
There are some standards data except OSM.

**Comment by ismailsunni** [comment]
Based on discussion between @timlinux  and @ismailsunni, we nee to make a test for 
- [ ] CSV
- [ ] WFS
- [ ] WCS
to make sure that they will work.

**Comment by timlinux** [comment]
@ismailsunni I am assigning this to you as in our work planning I think most of the issues here are going to relate to metadata management. Something to think about for 3.5...

**Comment by NyakudyaA** [comment]
WFS, WCS work nicely in inasafe version 4

**Comment by Gustry** [comment]
Thanks @NyakudyaA.
Let's close this ticket.
