### ISSUE TITLE
Additional minimum needs not shown in impact report of InaSAFE 4.1

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#4320]
### Problem
I run the tsunami raster with population vector and get the impact report of InaSAFE 4.1 then see the different report when present the additional minimum needs that not shown anymore. Additional minimum needs are additional weekly rice for pregnant and lactating women + weekly hygiene packs.
![image](https://user-images.githubusercontent.com/13621886/28411261-662c1cb8-6d6a-11e7-80f9-7d1b953690c2.png)

### Expected Behaviour
Bring back the additional minimum needs for gender vulnerable report.

### Environment
* InaSAFE : 4.1
* QGIS : 2.14.14
* OS : Win-7
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :

### Proposed Solution
Make it happy :smile: 

Cc:
@myarjunar @ismailsunni @ivanbusthomi @samnawi @Charlotte-Morgan @timlinux

**Comment by Charlotte-Morgan** [comment]
Hi @felix-yew - I think this was a deliberate move at 4.1 because we did not have a reference for the source of the additional minimum needs - ie we always referenced BNPB Perka 7 / 2008.
Now that we have a reference for the additional needs, it is good to add them back and make sure they are referenced accurately.

**Comment by myarjunar** [comment]
Hi mas @felix-yew how if we put the additional minimum needs under the min. needs breakdown table? because previously we put it along with the gender breakdown table and IMHO it seems irrelevant with the table title. What do you think? 

cc @Charlotte-Morgan @timlinux

**Comment by felix-yew** [comment]
Hi @myarjunar - yes I agree. LGTM

**Comment by myarjunar** [comment]
closed in #4337
