### ISSUE TITLE
Population Report tweak

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4334]
The population report is looking nice with additional information added in 4.1; however the information is a little inconsistent.
I propose to add a little more info in some places and remove some that may not be relevant.
At the bottom of the general report - please add definitions for exposed people, affected people and displaced people from concepts.py
in here 
![image](https://user-images.githubusercontent.com/5743135/28609341-a4e5968e-7227-11e7-80cc-7cac0fd24697.png)

And in these sections - I think the information about groups is not relevant on the report and are incorrect (highlighted in yellow)
Please remove these bits in the red area until we can tweak the words some more to explain the groups a little more clearly
![image](https://user-images.githubusercontent.com/5743135/28609490-3d711ac2-7228-11e7-875d-8b75ee4d61ba.png)

cc
@samnawi @felix-yew @timlinux @ismailsunni

**Comment by samnawi** [comment]
Hi @Charlotte-Morgan the definition that you mean is refers to the definition in the concept.py?

**Comment by myarjunar** [comment]
closed in #4361
