### ISSUE TITLE
Inasafe Plugin installation error

### ISSUE THREAD

**Issue by Germante** [inasafe/inasafe#4364]
Plugin is broken Python said ascii Problem

**Comment by Gustry** [comment]
Thanks for reporting an issue, but you need to give more informations so as to help us debugging.
Can you check in your `logs` panel? (the small bubble in the bottom right corner of QGIS, check in each tabs if there is something related to InaSAFE)

What is your full path where you `.qgis2` folder is located?

**Comment by NyakudyaA** [comment]
Tested this on Windows 10, Ubuntu 16.04  and found no similar issue. Guess we can close this if the feedback doesn't come in

**Comment by Gustry** [comment]
Yes, thanks.
It might be linked to a path on the OS.
