### ISSUE TITLE
Add Evacuation Centres as a Structure Keyword

### ISSUE THREAD

**Issue by lrpower** [inasafe/inasafe#4370]
Add 'Evacuation Centres' as a Classified Unique Value to the Generic Structure Classification

This will allow the user to identify if dedicated evacuation centres are potentially affected.
Otherwise they just get lumped in 'Other'.

Thanks

**Comment by Gustry** [comment]
Yes, this is possible.

**Comment by Charlotte-Morgan** [comment]
@ismailsunni  - can these be included in places ??

**Comment by ismailsunni** [comment]
Yes, I think so.
Do we have special information / field for evacuation center?

**Comment by Charlotte-Morgan** [comment]
@lrpower do you have any evacuation centre specific notes or actions that should also be added?

**Comment by Gustry** [comment]
The PR has been merged. It's adding a new class to places and buildings classifications.
Let me know if it's OK or if something else is needed

**Comment by Charlotte-Morgan** [comment]
I think we can close this. @lrpower can write a new ticket or make a PR if there are any new notes or actions to add
cc
@wcarthur
