### ISSUE TITLE
Quick review on Infographic

### ISSUE THREAD

**Issue by myarjunar** [inasafe/inasafe#4371]
### Problem
https://files.gitter.im/inasafe/inasafe/bk0t/Screen-Shot-2017-08-16-at-11.53.32.png
https://files.gitter.im/inasafe/inasafe/7mxS/Screen-Shot-2017-08-16-at-12.02.34.png

So quick review (from @Gustry):
- Some strings in French are longer, I wonder if we can set the font size by an expression according to size of the sentence? It will be I guess out of scope for now. Users should create/tweak the template
- Problem with unicode, it’s displaying some strange chars for me
- Some strings like `weekly` are sometimes translated, and sometimes not. Why?
- Some words are missing translations always, even if I added them into the `dynamic_translation` file from InaSAFE. Why is-it missing? Not a big deal for now
- For 2 items, I can see the expression it self. It’s not evaluated by QGIS. I can read `inasafe_field_header` in my PDF

**Comment by myarjunar** [comment]
I have no clue about missing translations.

**Comment by Gustry** [comment]
Thanks @myarjunar 
I think it was better now.
