### ISSUE TITLE
Population Exposure Definitions appearing in Structures Impact Report

### ISSUE THREAD

**Issue by lrpower** [inasafe/inasafe#4376]
### Problem
Population Exposure Definitions appearing in Structure impact reports. 

![image](https://user-images.githubusercontent.com/10228025/29500724-abff9c78-8666-11e7-81d4-03dadc6e7e5a.png)

### Expected Behaviour
Population exposure definitions only to appear in population analysis reports
### Environment
* InaSAFE : 4.2.0b0
* QGIS : 2.18.10
* OS :  Windows
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : Structure
  * Hazard : Cyclone
  * Aggregation : n/a
  * Extent : exposure layer
  
### Proposed Solution
Population exposure definitions only to appear in population analysis reports

**Comment by felix-yew** [comment]
Hi @lrpower - I also find this problem after I git pull this morning.
![image](https://user-images.githubusercontent.com/13621886/29504027-d60143be-8666-11e7-9919-86b48f76876d.png)
Last week when I run it with batch runner and I have check the result, I did not find this problem. I agree with your expected that population exposure only appear in population reports.

**Comment by myarjunar** [comment]
closed in #4382
