### ISSUE TITLE
Wizard real estate

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4411]
This is  a known issue but we may  need to  look for a tidy solution.
## problem ##
Some wizard screens for demographic fields are compromised by the limited real estate and the amount of supporting text shown.
Resizing the window does not improve the use of the realestate. With the detailed help informaiton, we find the actual space fro the wizard window is very small.
![image](https://user-images.githubusercontent.com/5743135/29903565-da99663e-8e47-11e7-81cc-361c2f98e98f.png)

This is managed better in the field mapping tool which has a smaller font and the real estate expands with the window.
![image](https://user-images.githubusercontent.com/5743135/29903600-0d6a27ce-8e48-11e7-877c-7a1fb4b69ebc.png)

## proposed solution ##
maybe its possible to use the same approach in the key words wizard as in the field mapping tool
- ie smaller fonts
- use the full real estate

make it happy

**Comment by ismailsunni** [comment]
We still need to change the font size. Reopen this.

**Comment by ismailsunni** [comment]
I just realized that making the font smaller is not the issue, but one of the proposed solution. So, it's been fixed then. Closing this.
