### ISSUE TITLE
InaSAFE reporting bugs

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4412]
A few bugs in the reports - Jakarta flood analysis. 

### problems ###
- [x] the report mentions aggregation area when no aggregation was used
![image](https://user-images.githubusercontent.com/5743135/29904163-dcbc6b52-8e4a-11e7-8350-0c0d8743c946.png)
- [x] map reference is not computing
![image](https://user-images.githubusercontent.com/5743135/29904198-ff69dd9c-8e4a-11e7-81b3-3c0042305a75.png)
-  [ ] action check list has 2 blank pages
- [x] infographic report - unit should be thousand not thousands; million not millions etc
![image](https://user-images.githubusercontent.com/5743135/29905911-ac6806dc-8e54-11e7-808d-24168b925e89.png)

### proposed solution ##
- [x] update title on tables - drop the "per aggregation area" if aggregation data set is not used
- [x] make expression for map reference happy
- [ ] remove blank pages
- [x] tweak the unit word

### Data ###
Petabencana flood and vector population with no aggregation.

**Comment by Gustry** [comment]
I'm only gonna fix the CRS element @myarjunar, it's in my next PR

**Comment by myarjunar** [comment]
closed in #4448
