### ISSUE TITLE
Tsunami and Structure IF Report Bugs

### ISSUE THREAD

**Issue by lrpower** [inasafe/inasafe#4428]
### Problem
A few issues I have noticed in the Tsunami Raster on Structure Point IF Report

1. High, Medium, Low and Dry does not equal the Total. While I don't want the Dry value to be rounded, doesn't InaSAFE logic mean it should be?
![image](https://user-images.githubusercontent.com/10228025/30310603-95ae9044-97d4-11e7-9382-2f5646300d1f.png)

2. There should be more definition between these two results because the affected, not affected, not exposed counts and totals have nothing to do with the hazard zones. 
![image](https://user-images.githubusercontent.com/10228025/30311408-6d0ff354-97d8-11e7-86b5-63b207c9f64d.png)

3. This table is a mishmash of rounding and not rounding. Residential and Other are rounded, but the others appear not to be.  
![image](https://user-images.githubusercontent.com/10228025/30310901-2c07ab10-97d6-11e7-8d0e-e2f1206cc0fc.png)

4. This should be titled _Estimated number of buildings **affected** by aggregated area_.
Since an aggregation has not been used, this probably doesn't need to be displayed because it is just a simplified version of the by Structure Type table.
![image](https://user-images.githubusercontent.com/10228025/30310761-6b68d7e4-97d5-11e7-9407-ab18db20e9ba.png)

### Environment
* InaSAFE : 4.3.0
* QGIS : 2.18.10
* OS : Windows-7-6.1.7601-SP1
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : Structure points
  * Hazard : Tsunami Raster
  * Aggregation :n/a
  * Extent : Nukalofa
  
### Proposed Solution
1. Either add Not Exposed to equal the total or calculate the total of the figures shown
2. Add a line to separate the two tables.
3. Be consistent with rounding values
4. Remove aggregation table when not applying an aggregation; add **affected** if the values are going to be the affected values. 
5. Make a decision regarding the term Structures or Buildings. They are both used throughout the report.

**Comment by Gustry** [comment]
Thanks a lot @lrpower for this ticket.
I will try to run analysis on my side to check your issues.

1. In the Analysis layer summary in your legend, is there a field  `Not exposed` ? I guess you are right, the not exposed class is not shown.


2. > There should be more definition between these two results because the affected, not affected, not exposed counts and totals have nothing to do with the hazard zones.

These definitions are based on the hazard class, so not really true.
@myarjunar Will you have a look to proposed solution 2?

Good point for `Structures` and `Buildings`. Which one should we use? Any preference @Charlotte-Morgan ?

**Comment by lrpower** [comment]
Hi @Gustry 
1. yes, there is a field total_not_exposed but it is not shown in the report table.
2. The table heading says 'per hazard type' and that table is by 'Affectedness'. I guess it's not clear that they are related... you have to dig into the notes to understand the definitions. 
Maybe if the Structures Table used the following as a way to link the two? (as an example; I don't know the exact defs)
Affected (High, Medium, Low)
Not Affected (Dry)
Exposed (High, Medium)
Not Exposed (Low, Dry)

**Comment by myarjunar** [comment]
Hi @lrpower , for issue number 3, we have a rounding rules as written in this ticket https://github.com/inasafe/inasafe/issues/4062

**Comment by lrpower** [comment]
@myarjunar I was not aware of #4062. Perhaps the notes and assumptions should be updated to reflect this. It currently reads that all values less than 1000 are rounded.
![image](https://user-images.githubusercontent.com/10228025/30571219-92ea4920-9d29-11e7-8185-4c03b56e7e4a.png)

**Comment by Gustry** [comment]
@myarjunar Can you do a status update on this ticket?

**Comment by NyakudyaA** [comment]
@myarjunar  I still see the bug here.
![sas](https://user-images.githubusercontent.com/2510900/31490685-157abc9e-af45-11e7-8d02-3f0b42769407.png)

Tsunami on roads

**Comment by Gustry** [comment]
Can you run it in debug mode @NyakudyaA I guess all should be fine? It's rounding rule.

**Comment by NyakudyaA** [comment]
@Gustry  how do I run it in debug mode. Any documentation on that

**Comment by Gustry** [comment]
Yes, because it's for developers using GIT, not using the plugin from the repository ;-)
**InaSAFE options** -> **Advanced** -> **Developer mode**

Then if you restart QGIS, you will have a checkbox `Debug mode` next to the `Run` button in the dock

In debug mode, we don't round values.

**Comment by NyakudyaA** [comment]
Ok will do so now and check

**Comment by NyakudyaA** [comment]
@Gustry  If I use the debug mode it works properly. But still, the issue remains that the rounded up figures are still giving a total that is wrong. Adding the values in the attachment gives a different value as opposed to adding the rounded up values with a calc. Or perhaps the total exposed

**Comment by Gustry** [comment]
If everything is fine in debug mode, so there is no bug.
We put some notes about this behavior in the report, under tables:
* Rounding is applied to all road lengths, which may cause discrepancies between subtotals and totals.
* Note that report rows containing totals are calculated from the entire analysis area totals and then rounded, whereas the subtotal rows are calculated from the aggregation areas and then rounded. Using this approach we avoid adding already rounded numbers and in so doing compounding the rounding.

**Comment by NyakudyaA** [comment]
Thanks for the explanation @Gustry

**Comment by Gustry** [comment]
I know it's a bug from the user point of view this rounding. But it's actually not a bug in InaSAFE itself.
You can open the attribute table of these layers, the analysis layer summary your case (even without debug mode), numbers will match perfectly.
