### ISSUE TITLE
[Multi Exposure] 2: Use the Same Aggregate Hazard for Running Several Analysis

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4438]
### Problem
This is the next step after finishing #4437 

Since we run several analysis with the same hazard and aggregation layer, it will be great if we can re-use the aggregate hazard layer for all analysis to save computation and time.

cc @timlinux @Gustry

**Comment by timlinux** [comment]
We investigated this and we can't do this because the hazard classifications might be different between each exposure.
