### ISSUE TITLE
[Multi Exposure] 3: Append Result for Several Output Layers

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4439]
### Problem
After finishing #4438 , we need to have one integrated output layer. We can do this for all output that doesn't depend on the exposure layer (Hazard Aggregation Summary, Aggregation Summary, Analysis Summary, Aggregation Summary, Analysis Summary, and Exposure Summary Table).

Since for each exposure will create several fields and we want to avoid the name collision, we need to add a namespace for it.

cc @Gustry @timlinux @myarjunar

**Comment by timlinux** [comment]
We could approach this by making a new aggregate report folder and leave the original exposure impact function results in their own folders.

**Comment by Gustry** [comment]
This ticket has been done
