### ISSUE TITLE
We need a new icon for the multi exposure analysis

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#4450]
Hi @MariaSolovyeva and @felix-yew 

We are introducing a new feature in InaSAFE. It's a multi exposure analysis. We will be able to run an analysis on population, structures, roads, landcover in one shot.

So we need a new icon for this tool.

FYI, existing exposures in InaSAFE, with icons:
<img width="118" alt="screen shot 2017-09-21 at 21 14 14" src="https://user-images.githubusercontent.com/1609292/30700503-f982c5e2-9f11-11e7-974b-74166346467e.png">

Let's drop ideas. I'm afraid if we do a mix of many exposure icons it will not be readable, no?

**Comment by felix-yew** [comment]
Hi @Gustry - I have an idea for the icon to support the multi exposure analysis tool, like this image below
![multi_exposure](https://user-images.githubusercontent.com/13621886/31263544-1abda246-aa8d-11e7-93c9-1543296efac9.png)
Maybe @MariaSolovyeva have another option for the icon or can modify from my icon suggestion.

**Comment by Charlotte-Morgan** [comment]
I think we will only have a max of 3 exposures? Do we want 1 multi exposure icon or different ones depending on the exposures?

**Comment by Gustry** [comment]
The icon is for the toolbar, so we need one icon.

**Comment by MariaSolovyeva** [comment]
Hello @Gustry , could you please send me a screen of the toolbar so I see the other icons style? or does the first screen show it? The one example provided by  @felix-yew is good for this, i just might remove few layers from there

**Comment by Gustry** [comment]
The toolbar: 
![screen shot 2017-10-11 at 14 42 02](https://user-images.githubusercontent.com/1609292/31441332-23388044-ae93-11e7-8dca-a28f957a357b.png)

The menu:
![screen shot 2017-10-11 at 14 48 12](https://user-images.githubusercontent.com/1609292/31441370-44fbcf1a-ae93-11e7-98d2-153ac25168e4.png)

The duplicated icon is the actual icon the multi exposure analysis. I don't know if we will keep the multiexposure tool in the main toolbar.

**Comment by felix-yew** [comment]
nice icon @MariaSolovyeva :+1: LGTM

**Comment by Gustry** [comment]
Ok thanks @MariaSolovyeva.
Can we have the SVG?

**Comment by Gustry** [comment]
Ok thanks @MariaSolovyeva for the email. I made the PR
