### ISSUE TITLE
Make the map report nicer

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#4477]
### Problem
One of the products from InaSAFE is a map.
Currently, since the old way to custom a map report was disappeared (https://github.com/inasafe/inasafe/issues/4240), the user just use the map that automatically generates from InaSAFE.

But, the default map still need more polish to make it nice and easy to understand.

1. Although the order of the impact layer already on the top, the impact layer not shown in the map report (seems like its covered by aggregation layer - the orange one)
![image](https://user-images.githubusercontent.com/8871958/30902212-a9b99392-a394-11e7-8745-b7c4fa0d90a9.png)

2. Information in the legend, it should represent all of the layer that shown in the map.
![image](https://user-images.githubusercontent.com/8871958/30902756-a271d35e-a396-11e7-80a2-fe52dd365721.png)

But, if the map more complicated, could InaSAFE turn off some layer and just turn on some layer that used in the analysis (impact layer, hazard, aggregation).

### Expected Behaviour
The map is one of the way to give the information. So, its should represent the information of InaSAFE analysis

### Proposed Solution
Make it happy

cc: @Charlotte-Morgan @timlinux @ivanbusthomi @felix-yew

**Comment by Charlotte-Morgan** [comment]
@samnawi  - thanks for writing this ticket. I agree there are problems with the way the maps display but this is largely what we asked for in the standards.  I think we also need to prepare an example of how we want the map to look. Which issues are bugs vs what is a new feature request?

It is possible to make general rules like? 
Always show hazard / never show hazard
Include all layers in legend
.. or is the requirement specific to the hazard / exposure combination

Do we need to revise the 'standard' symbology and labels for the impact layer? (I think this might be the issue)
Do we want to make smarter maps now we have richer data. eg in example 1 above we can do much more useful display.

Maybe we can deal with bugs now and new features with #4495?

**Comment by Gustry** [comment]
In the report, I can read:

**Reference:** ['crs_text_element( @crs )%]

I thought we fixed this issue. But it seems we need to have a look to this one.

**Comment by Charlotte-Morgan** [comment]
it could be we used an old report to illustrate a different point
