### ISSUE TITLE
InaSAFE Profile

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4482]
### Problem
Create a tool to support editing the displaced and affected people for each hazard classification. This should be stored somewhere in the `.qgis2/python/plugins/inasafe` directory, so that we can share it to another people.

### Expected Behaviour
User can edit the displaced and affected ratio people.

### Proposed Solution
- [x] Create the UI
  - [x] With logo, organisation name, contact in the first tab) --> save and load
  - [x] Second tab is the setting affected and displaced fields
  - [x] Run it on the first running InaSAFE
- [x]  Make it update the hazard classification definition value

cc @timlinux

**Comment by ismailsunni** [comment]
Another good thing to add here is currency. Currently, we put it in InaSAFE setting, it would be good to put it in the InaSAFE profile.

**Comment by ismailsunni** [comment]
Hi @timlinux @Charlotte-Morgan 
I have made a simple mock up for the UI. Do you have any comment about it?

<img width="656" alt="inasafeprofile" src="https://user-images.githubusercontent.com/1421861/31212784-c41976b0-a9cc-11e7-8ee9-6cd0618e3ba9.png">

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni thanks for the mock up. 
The organisation tab looks fine. 
* Will currency be a drop down?
* Might you want to add units too?

A few suggestions for the profile tab: - 
* I think it needs a different name but not sure what; maybe preferences / settings / ... / customisation
*Maybe  "Please fill in the custom value for your organisation profile"  could say "Please customise the population exposure preferences for your organisation profile:
* only relevant classifications should show for each hazard :) and only those that apply to population exposure
* swap affected to the left and displaced to the right
* please use the word rate not ratio 
* affected should be binary True or False
* displaced should only be editable if affected = true
* profile preview => customised profile

I think it would be good to have definitions for concepts; especially affected and displaced and how these are used by InaSAFE (analysis & reports)

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan thanks for the review
> Will currency be a drop down?

I was thinking to make it drop down, but the user also can set it manually (i.e. write in the dropdown). I think there is a widget for it. But for the first step, I will make it as drop down like in the current InaSAFE Setting.

> Might you want to add units too?

What units do you mean? I am not sure we can add unit since every layers use different unit. Or perhaps you mean another unit?

A few suggestions for the profile tab: -

> I think it needs a different name but not sure what; maybe preferences / settings / ... / customisation
> Maybe "Please fill in the custom value for your organisation profile" could say "Please customise the population exposure preferences for your organisation profile:
> only relevant classifications should show for each hazard :) and only those that apply to population exposure
> swap affected to the left and displaced to the right
> please use the word rate not ratio
> affected should be binary True or False
> displaced should only be editable if affected = true
> profile preview => customised profile

I have updated the mock up based on your comment, and add the behaviour in the check list above.

<img width="657" alt="inasafeprofile2" src="https://user-images.githubusercontent.com/1421861/31272654-ef8bbe0e-aab5-11e7-8549-114edb9436c3.png">


> I think it would be good to have definitions for concepts; especially affected and displaced and how these are used by InaSAFE (analysis & reports)

Put it as tooltip?

**Comment by Charlotte-Morgan** [comment]
hi @ismailsunni  - that looks good.
I am thinking if there are other things that should be in this profile like earthquake function, default age groups (ie adult, youth and elderly or , default rates for age gender and disability as per the InaSAFE options.
![image](https://user-images.githubusercontent.com/5743135/31324665-ccf2958c-ad00-11e7-8c23-9e85f7265656.png)
I note we have some inconsistency in the way we describe rates ( you use the word ratio) and the profile which uses % but the options with are  .... hmm I need to write a new ticket :)

**Comment by ismailsunni** [comment]
@ismailsunni to add new tab in the options dialog first. For the wizard, we can re-use the tab / widget from it.
It will be better to show all of them as a table, so the user can see all the value that have been set.

**Comment by timlinux** [comment]
<img width="845" alt="screen shot 2017-10-23 at 08 54 45" src="https://user-images.githubusercontent.com/178003/31876035-f30e4510-b7d0-11e7-9e45-cffc5d1f604f.png">


Some notes from our conversation today:

* We should refactor the options dialog as above
* We should re-use the options dialog
* We should add a 'Welcome' tab to the options' (Tim to write prose)
   * Welcome to the InaSAFE project, 
   * explain the project, 
   * link to home page, 
   * ask user to fill in basic options in next two tabs 
* For the hazard classification affected and deplaced rates @ismailsunni to use spinner for numeric entry and checkbox for whether things are affected or not.

![screen shot 2017-10-23 at 09 16 16](https://user-images.githubusercontent.com/178003/31876428-dd552fca-b7d2-11e7-9fe7-d3a538d6a61a.png)
