### ISSUE TITLE
Classification for Place Exposure

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4483]
### Problem
For place exposure, we can have several type of place in one layer (e.g. town, airport, harbour, etc). We need to do a classification like we did in the road and building classification. But, there will be more information (like number of population, distance to an epicentrum, etc) that is specific to each class.

### Expected Behaviour
InaSAFE supports to have special classification for place exposure

### Proposed Solution
- [ ] Define the classes, and each behaviour / custom data. Who will give it to me ? cc @timlinux @Charlotte-Morgan 
- [ ] Add the classification in the definition
- [ ] Make sure that metadata support it. Ouch. 
- [ ] Support this classification assignment in keyword wizard
- [ ] Present it beautifully in dock

cc @timlinux @Charlotte-Morgan

**Comment by Charlotte-Morgan** [comment]
@ismailsunni 
here is a brain dump of what the data may look like without actually looking at data. I think there are two different types you need to handle. Things that are just text and used to make lists and things with numbers that will need to be calculated
Populated Places (names with location, type and attributes):
- Big places with lots of people
- Little places with less people
- Really small places with not many people

Place labels (names with location and type):
Administrative - provinces, districts etc
Infrastructure - airports, ports, transport hubs 
![image](https://user-images.githubusercontent.com/5743135/31265655-aa5a2dba-aabb-11e7-8462-08a84bfc0055.png)

Please excuse silliness but I hope you get the idea. @ivanbusthomi can you please make a data set for @ismailsunni  to test while you find the real stuff?

**Comment by ismailsunni** [comment]
Thanks @Charlotte-Morgan I think I got the main idea. Btw, what does the location for? We can get it from the geometry attribute, can't we?

**Comment by Charlotte-Morgan** [comment]
yup - location is the geometry. I guess sometimes you will also have attributes for x and y

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
After checking deeper on the implementation detail, (now) I have another questions:
1. Which field that will be used for classifying the exposure place in your table above? Is it `Feature` or `Type`?
2. If it's the `Feature`, will it be only 3 classes like you put in there?
3. If it's the `Type`, we already have exposure classification (that of course we can extend based on what we need) which has `city, town, village, hamlet, airport` as the classes. If we use `Type`, then what's the different between administrative label and populated place (beside one has population column, and the other doesn't have)

**Comment by Charlotte-Morgan** [comment]
Hi @ismailsunni  - its hard for me to answer because i do not have the data already being used or the analysis logic.
for admin label vs populated place - yes, one has population and the other one doesnt. One might be used to label places others will be used to calculate population

**Comment by ismailsunni** [comment]
Ah I see...
Perhaps if we have data that already being used is better, since we can adapt with the current usage and the data that available before I code based on my taste :)

May be @felix-yew or @samnawi has the sample data that is being used?

**Comment by samnawi** [comment]
Hey @ismailsunni maybe you can use place dataset in InaSAFE realtime.
But, actually I haven't seen official point data with population data inside in Indonesia. The data that we use in Realtime platform, Coming from toponymy / place BIG which I add the population data from BPS.

If you want to refer to standard data, you can use the data from : 
1. Geonames.org (place with population data inside)
![image](https://user-images.githubusercontent.com/8871958/31758519-fe461fc6-b4d7-11e7-9b68-cf7e3b6f914e.png)
![image](https://user-images.githubusercontent.com/8871958/31758535-0d19d79a-b4d8-11e7-8a81-e7789444abf9.png)

2. Toponymy data from http://tanahair.indonesia.go.id/ (Choose toponymy data to download)
![image](https://user-images.githubusercontent.com/8871958/31758566-2ccf9a52-b4d8-11e7-9d39-08337d964555.png)

**Comment by ismailsunni** [comment]
Hi, the keywords support and the under the hood thing is already implemented. But we need to update our reporting to support this place with population. Currently, it's still not quite good for reporting.

See image below:
<img width="1279" alt="screen shot 2017-11-07 at 09 22 02" src="https://user-images.githubusercontent.com/1421861/32474102-6da063e4-c39d-11e7-8e19-0003519b876e.png">
<img width="637" alt="screen shot 2017-11-07 at 09 22 15" src="https://user-images.githubusercontent.com/1421861/32474103-6e245b0e-c39d-11e7-8ed0-32afbd61d46a.png">

I am passing this ticket to @myarjunar since he is the best person to handle this reporting.

**Comment by Gustry** [comment]
It's mixing count of places and count of population. We already talked about that for Ash Realtime about an airport being a place without population.

What should it be? The unit must be the same across the report? This might me be a problem in the IF @ismailsunni, not in the report. Because I guess QGIS layers are the same.

**Comment by ismailsunni** [comment]
> It's mixing count of places and count of population. We already talked about that for Ash Realtime about an airport being a place without population.

Yeah, in the data, the population field for airport is Null, and it will give zero affected also. The output layer is good I think.
And since the place is either affected or not, so all population in the affected place is affected population.

> What should it be? The unit must be the same across the report? 

IMHO, the unit can be derivated from the field name. For example, `population` field is the number of population. While the `high_hazard_count` has unit the number of exposure. So, I think the data in the output layer is fine, we just need to tweak the report to show it properly.

<img width="515" alt="screen shot 2017-11-08 at 17 24 38" src="https://user-images.githubusercontent.com/1421861/32544012-de13bdc6-c4a9-11e7-8d45-8de8c5f0c6a7.png">

**Comment by samnawi** [comment]
Hi @ismailsunni since user also set a population value in keyword wizard process (for city / town), Is it possible to add the information of total affected population in the report? not only just the number of place which affected, so user not doing something redundant.

**Comment by samnawi** [comment]
maybe something like this
![image](https://user-images.githubusercontent.com/8871958/33754346-61ee2420-dc1e-11e7-8858-9489dde2ae9a.png)

And if not too complicated, InaSAFE also could report the detailed breakdown of population group (because I see the detail information in the attribute of impact layer).

**Comment by ismailsunni** [comment]
hi @myarjunar can you check the report sample that @samnawi put above? and implement it?

**Comment by myarjunar** [comment]
Here are some ideas from me and @samnawi about the layout for place on pop report.

1. ![image](https://user-images.githubusercontent.com/8871958/33754346-61ee2420-dc1e-11e7-8858-9489dde2ae9a.png)
the values in `total` column would be ambiguous, because we put a value of population in the middle of the row even though it is not included in the `total` column. So the user mmight think that the total is incorrect.

2. ![place_on_pop](https://user-images.githubusercontent.com/11134669/33830334-4fb661d4-dea6-11e7-8f9e-dc82ee56869c.png)
we still dont have the detail of population (affected, not affected, not exposed) in the exposure summary table

3. ![selection_164](https://user-images.githubusercontent.com/11134669/33830217-d45909d8-dea5-11e7-9abd-56d7e027c41f.png)

**Comment by ismailsunni** [comment]
For me, I prefer the 3rd one. Just put the number of affected population for each row. It's quite clear for me.

**Comment by samnawi** [comment]
Hi @myarjunar Thank you for this.
From my side, I still prefer with the first one. From my perspective, the number of population is embedded with the place information.

I try to compare both of 1st and 3rd option :
![image](https://user-images.githubusercontent.com/8871958/33871983-7419c79a-df47-11e7-99d3-a001667c4b93.png)

I bit worried if we put population count at the end of the table, could make a confusion for user. Use the example in above,  Whether **Population Count** which showed in the report, just for affected or the summarize of affected + not affected + not exposed.

I also have some note for the information in the report :

1. According to sprint meeting on yesterday if place with population information is similar with population point, then population point will accommodate by population exposure analysis, whether we will show minimum need in the report?
2. The total population that showed in the report will be representing evacuated people or total population in that place.

How about you @Charlotte-Morgan ?

**Comment by ismailsunni** [comment]
Hi mas @samnawi 

Because this is a place exposure analysis, we need more process to get the more detail population breakdown. Currently, it will only return the affected population only. So, I think the only possible report is the 3rd one. We can put the better header (e.g. Affected Population Count) to make it clearer to the user. CMIIW @myarjunar 

That's why, we encourage the user to use population point to get the better breakdown.

**Comment by myarjunar** [comment]
> So, I think the only possible report is the 3rd one. We can put the better header (e.g. Affected Population Count) to make it clearer to the user. 

yes I agree, I have updated the header

**Comment by Charlotte-Morgan** [comment]
Hi Everyone - I'm not really happy with the way we are handling populated places.
I think all we can do is count the people exposed by hazard level. Population count should be an attribute of the place not treated as population exposure. ie 
Populated places should not IMO be used to calculate the number of people displaced, any demographic breakdowns or minimum needs.

Could we have separate tables for populated places??
How are you deciding if they are affected or not?

The help files, actions etc etc all need to be updated for this concept.
We also need to have access to the data (from realtime) so that we can do some testing.

Lets discuss :)

**Comment by samnawi** [comment]
If I refer to the note in help 
> Where places are represented as a single point, the effect of the hazard over the entire place may differ from the point at which the place is represented on the map.

Seems like the place population concept is to accommodate something like have existing in the realtime
![image](https://user-images.githubusercontent.com/8871958/33920932-587ffd86-dff3-11e7-8896-62aad27fc159.png)
![image](https://user-images.githubusercontent.com/8871958/33920934-60c78892-dff3-11e7-9ab8-46049b80f492.png)

In my opinion, it should show the number of population in the place which affected by hazard.

**Comment by Charlotte-Morgan** [comment]
@samnawi when you  set key words on places - how do you choose the hazard classification. Do you use one where affected is for structures or population?  This will change the results from if you use a population specific classification on the same points used as a population point dataset. 
Hence my concern to be very careful here & my desire to get some test data to use

**Comment by ismailsunni** [comment]
In the current architecture, InaSAFE will use the classification for place (since the exposure is place).

I agree with you @Charlotte-Morgan in term of getting test data (the real one) to see what's the real use case.

**Comment by samnawi** [comment]
Hi @Charlotte-Morgan as what @ismailsunni wrote, I use place specific when set-up the keyword for hazard. And for kind of the example above, I use place data that we use in InaSAFE realtime.

**Comment by ismailsunni** [comment]
In my PR above, I make the exposure summary to show the exposed population per place class. Something like this:
<img width="1421" alt="screen shot 2017-12-21 at 13 43 57" src="https://user-images.githubusercontent.com/1421861/34244102-709318ae-e656-11e7-8d93-ff308a150346.png">

I agree with @Charlotte-Morgan to only show exposed population, since we don't know the criteria of affected people in this scenario/hazard.

I will leave the reporting part to @myarjunar. It should be easy for him.

**Comment by ismailsunni** [comment]
Finished in #4834, closing this...
