### ISSUE TITLE
Reporting Option

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4495]
### Problem
From the last day discussion at October 2017 Site Visit, we decide to create a dialog to change / adjust  how the reporting will look like. Some of the features:
- [ ] Ordering/Show-Hide layers in the map from the current loaded layers, result layers.
- [ ] Choosing which template that the user want to use.
- [ ] Put some standard options to set the layers

This dialog will be put in the dock (like the old impact function option button with 3 dots.)

cc @timlinux @Charlotte-Morgan @Gustry @myarjunar @samnawi @felix-yew @ivanbusthomi 

PS: Let me know or just update the ticket if I missed something.

**Comment by Gustry** [comment]
Looks good.
I'm working on how to provide output layer names from the IF before the process.

**Comment by Gustry** [comment]
First PR here: https://github.com/inasafe/inasafe/pull/4488

Then my part should be more or less done. @myarjunar will you take these options in the reporting engine?

**Comment by Charlotte-Morgan** [comment]
@ismailsunni will this also address #4477 ?

**Comment by ismailsunni** [comment]
@Charlotte-Morgan 
I think yes, since the user can specifiy which layers that they want to see (and the order of the layer), it will solve the issue in #4477. Bug I agree, we need to put and option to use a standard option.

**Comment by ismailsunni** [comment]
Based on last discussion, we agree to use layer panel to set the layer order and visibility. So, we don't need this reporting option dialog. I am closing this. cc @Gustry @timlinux @myarjunar

**Comment by Gustry** [comment]
Don't we need it for the multiexposure? Or did I forgot something already?

**Comment by ismailsunni** [comment]
Can we do it in the layer canvas also for multi exposure?

**Comment by timlinux** [comment]
Just a note that

>  Ordering/Show-Hide layers in the map from the current loaded layers, result layers.

is only for multi exposure workflow

**Comment by timlinux** [comment]
> Choosing which template that the user want to use.

This should be for dock and multi-exposure etc.

**Comment by Gustry** [comment]
All implemented according to PR above
