### ISSUE TITLE
Typo in several place in Bahasa version

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#4497]
### Problem
I have found some typo in Bahasa Indonesia version. I find it in IFCW, when setting the flood hazard
![image](https://user-images.githubusercontent.com/13621886/31163140-26cb809a-a90b-11e7-80cc-eadc5a7be059.png)

And, in the impact report
![image](https://user-images.githubusercontent.com/13621886/31163779-435f4504-a90e-11e7-8903-b677ebaa8c78.png)
![image](https://user-images.githubusercontent.com/13621886/31163842-8e0e4a1e-a90e-11e7-8f52-72aa897294bc.png)

### Expected Behaviour
Typo can be fixed and easy read.

### Environment
* InaSAFE : 4.3.0 dev-master
* QGIS : 2.14.14
* OS : Win 7 Pro/64bit
* Data used (filenames and paths so as to reproduce, a project is better):
   *Exposure : Jakarta_Landcover_WGS84.shp
   *Hazard : Jakarta_Flood_HKV_WGS84.tif

### Proposed Solution
Make it happy

Cc: @Charlotte-Morgan @ismailsunni @myarjunar @samnawi @ivanbusthomi

**Comment by ismailsunni** [comment]
My check list:
- [x] bataran
- [x] flood
- [ ] Total Exposed
- [ ] Exposed
- [ ] affected by
- [ ] type
- [x] Jumlah terpapar.
- [ ] hundred_kilograms

**Comment by ismailsunni** [comment]
@myarjunar can you tell me where do you use the unit from the productivity (`hundred_kilograms`). It seems you use the key not the name.

**Comment by felix-yew** [comment]
hi @ismailsunni this 1 left in the setting for exposure keyword
![image](https://user-images.githubusercontent.com/13621886/31169474-e99a207e-a922-11e7-93ba-7355cf7830b0.png)

**Comment by ismailsunni** [comment]
Done, and backported
