### ISSUE TITLE
Infographic report can not produce with the batch runner

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#4504]
### Problem
I can not find the infographic report result when I run the InaSAFE population analysis with Batch Runner.

### Expected Behaviour
The infographic report can produce with the batch runner. It very helpful if we want to run a lot of population analysis.

### Environment
* InaSAFE : 4.3.0 dev-master
* QGIS : 2.14.14
* OS : Win 7 Pro/64bit

### Proposed Solution
Bring back the infographic report.

Cc: @Charlotte-Morgan @samnawi @ivanbusthomi @ismailsunni @myarjunar

**Comment by Gustry** [comment]
This is a duplicate of https://github.com/inasafe/inasafe/issues/4486

@myarjunar Can you have a look to this one? It's a bug on master.
