### ISSUE TITLE
BUG: definitions for default demographic rates

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4508]
### Problem
We are inconsistent in our use of the words rate and ratio (see demographic defaults vs profile #4482)  The demographic default definitions describe rate per 100 people yet the values are rates per 1 person 
![image](https://user-images.githubusercontent.com/5743135/31324770-e010e460-ad01-11e7-9c83-064e2654e583.png)

### Expected Behaviour
We use consistent terminology and definitions. My preference is to use the term rate and use percentages. ie the displacement rate is 5% in flood water
the disabled rate in the population is 15%

### Proposed Solution
We update definitions and rates to be consistent and ensure the code is not broken by changing rates.

@ismailsunni  - do you have a suggestion to fix this?

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
we have a ticket for using percentage here, https://github.com/inasafe/inasafe/issues/4145

Changing the text in the definition will be fine (no effect in the calculation).

For the percentage, we have to options (at least):
1. Changing the presentation only
    We keep using 0.0 - 1.0 in the code, but show it as percentage in the GUI / report.
    Pro:
    1. We don't need to change anything in the metadata/keywords level. Old keyword version is still supported

    Cons:
    1. Since the code save it as 0.0 - 1.0, we will always need to multiply by 100 and add percentage sign when we want to show it.
2. Changing the code and the presentation.
    We use 0.0 - 100.0 in the code and show it as percentagen in the GUI/report
    Pro:
    1. Only need to add % sign in the gui / report

    Cons:
    1. No support for old keywords, since the representation of rate is different
    2. Need to divide by 100 when doing calculation

For me, the first option is much better, and less code to be written / update / manage. So, I suggest we go with 1st option.

For rate vs ratio, CMIIW, I think it's not suitable for gender ratio or age ratio (they will be gender rate and age rate). But I agree it's more suitable for displaced people (as displaced rate). For me, ratio is the current proporsional of something. While rate is used for on the fly calculation.

Of course, I am not expert in this linguistic area :D

**Comment by Charlotte-Morgan** [comment]
Hi @ismailsunni - I am happy with option 1, especially if the UI shows a percentage - ie value between 1 and 100.
  I also looked up meaning of ratio and it is the same meaning as I use for rate so I think we can use them both when we need to

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 

> Hi @ismailsunni - I am happy with option 1, especially if the UI shows a percentage - ie value between 1 and 100.

Ok, I will move forward to show it as percentage in the GUI. But bear in mind, we still need to use 0.0 - 1.0 if the number is coming from the data.

> I also looked up meaning of ratio and it is the same meaning as I use for rate so I think we can use them both when we need to

Ok, I will leave it as it now, unless I find something not proper. Let me know which one you wanted to switch (or you can update it and make a PR, for the T-Shirts :) )

**Comment by ismailsunni** [comment]
Btw, I have a working code for creating the percentage: https://github.com/inasafe/inasafe/blob/develop/safe/gui/widgets/profile_widget.py#L137

**Comment by Charlotte-Morgan** [comment]
> Ok, I will leave it as it now, unless I find something not proper. Let me know which one you wanted to switch (or you can update it and make a PR, for the T-Shirts :) )
Hmm - no t-shirt for me this year

**Comment by ismailsunni** [comment]
Done in #4692
