### ISSUE TITLE
We need to serialise the impact function

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#4509]
We need to be able to serialise and deserialise impact function. Then these steps:

- [ ] Make sure the impact layer xml includes all needed properties of the IF
- [ ] We need a second IF associated with teh dock 'current_impact_function' which is the state of the current impact layer group
- [ ] We need to ba able to call the reporting engine, first tweaking the apt if needed on the deserialised IF

**Comment by ismailsunni** [comment]
Some more detail tasks for myself:
- [ ] Make a comparison method / operator to check if two IF is the same
- [ ] Unit test
- [ ] Loading IF from output layer's metadata

**Comment by timlinux** [comment]
This should fix #4240

**Comment by timlinux** [comment]
Once the deserialisation is done, @myarjunar to implement print as a separate step from the analysis with the ability for user to first select a QPT before running print:

![screen shot 2017-10-16 at 09 33 41](https://user-images.githubusercontent.com/178003/31600360-6973ddf8-b256-11e7-9154-14b80d77de76.png)
