### ISSUE TITLE
Remove Not Important File in the Output Directory

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4514]
### Problem
I just realized that we put some files that we don't need in the output directory:
<img width="1437" alt="screen shot 2017-10-11 at 13 08 40" src="https://user-images.githubusercontent.com/1421861/31424616-5c873d8a-ae85-11e7-90c6-423a9ce8d859.png">

For example under img directory, we have screenshots, icons, wizard.

### Expected Behaviour
We should only put the important / needed files in the output directory.

### Proposed Solution
Exclude the un-needed files from the output directory.

**Comment by Gustry** [comment]
I think we can now close this ticket.
