### ISSUE TITLE
Support Exposure That Doesn't Have Classification

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4535]
### Problem
Currently, classification is mandatory for assigning keywords / running analysis for exposure layer. But, perhaps, there is a use case where the data doesn't have field to be classified. Perhaps we should make it not mandatory to have classification. Using random field to do classification perhaps not a good solution.

May be it's low priority.

### Expected Behaviour
User can run analysis without having exposure classification.

**Comment by Gustry** [comment]
I think we already talked about that during the InaSAFE v4 refactoring. I agree it would be nice to have. But it's very quick to create a dummy field in the field calculator.

**Comment by ismailsunni** [comment]
Hmm, I think I forget the discussion. So, what's the decision?

**Comment by Gustry** [comment]
Only vector population doesn't have a classification, it's continuous exposure data, we create the exposure type on the fly in impact function.

If it's not vector population data, users should create first a dummy field "buildings=yes" for instance if needed.

**Comment by ismailsunni** [comment]
ah I remember it now. Perhaps we should put it somewhere in the help. Should I close this ticket?

**Comment by ismailsunni** [comment]
I think it's easier to teach the user to create dummy field, rather than adding a bunch of code for this very specific (and perhaps rare) case. I am closing this.
