### ISSUE TITLE
Correct terminology in translations

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#456]
From my last visit to Yogya, there is a suggestion to make the InaSAFE be language setting indenpendent. The reason is, some times it's easier to use QGIS in English (because the terms is more familiar in English), but we want to print the map/result in Bahasa or we want to use InaSAFE in Bahasa.

So, my idea for this suggestion is we put the options in the InaSAFE options, and user can choose between English or Bahasa.

**Comment by Charlotte-Morgan** [comment]
@timlinux @ismailsunni @adissadis  - is this still current :)

**Comment by ismailsunni** [comment]
Is this about the fixing QGIS translations or create a list for terminology (and it seems Tim has sent it Heri) ?

**Comment by timlinux** [comment]
Closing as old. We have our workflows in place, hopefully @ismailsunni is using beautiful terminology :-)
