### ISSUE TITLE
Update Welcome Message

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4567]
### Problem
We need to make a better welcome message than my welcome message.
<img width="1097" alt="screen shot 2017-10-30 at 21 03 19" src="https://user-images.githubusercontent.com/1421861/32175180-b4943376-bdb6-11e7-8510-ece601f2fd5e.png">

I put it as release blocker since it will be shown to the user after opening QGIS.

**Comment by Charlotte-Morgan** [comment]
see #4630

**Comment by Gustry** [comment]
Done in #4594 for @timlinux PR
The ticket from Charlotte is still open
