### ISSUE TITLE
Analysis extent not applied when using aggregation layer

### ISSUE THREAD

**Issue by lrpower** [inasafe/inasafe#4583]
### Problem
May be related to #4571

Tsunami hazard impact function on Population raster does not obey analysis extent when used with village polygon aggregation.
For context, Tsunami hazard does not cover the whole islands, just Tongatapu. When impact function is just hazard and exposure, the analysis extent is obeyed.
![image](https://user-images.githubusercontent.com/10228025/32423302-c30511e4-c2f9-11e7-9ece-0951cbda9ea3.png)

When used with village boundary aggregation, the map extent resets and the output is the whole country. I've tried using the bounding box and current view extent but it always refreshes to the whole extent.   
![image](https://user-images.githubusercontent.com/10228025/32423440-7e247762-c2fa-11e7-8efc-53eed6a1c432.png)

It also then fails to create a locator map - may be related to #4381 
![image](https://user-images.githubusercontent.com/10228025/32423567-3311208a-c2fb-11e7-8765-869aee147d47.png)

### Environment
* InaSAFE : 4.3.0.dev-master
* QGIS : 2.18.10
* OS : windows
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : Population raster
  * Hazard : Tsunami polygon
  * Aggregation : Village polygon
  * Extent : HAzard

**Comment by ivanbusthomi** [comment]
Hi @lrpower , does the data shareable? do you have the issue for another extent near that location?
cc @myarjunar

**Comment by lrpower** [comment]
[ExtentExample.zip](https://github.com/inasafe/inasafe/files/1445003/ExtentExample.zip)

Does the same thing using the Roads exposure. I don't really have another extent to test.

**Comment by Gustry** [comment]
The analysis extent behavior is different if you use an aggregation layer or not:
* If you don't use an aggregation layer, we use the setting in this dialog:
![screen shot 2017-11-08 at 13 22 02](https://user-images.githubusercontent.com/1609292/32548994-04b8e784-c488-11e7-8191-7a8c4426cd39.png)

* If you use an aggregation layer, you should notice that the green boundary is following your aggregation layer. If you want to do a smaller area, you can select some features in your aggregation layer. http://changelog.inasafe.org/en/inasafe/version/4.0.0/#added-support-for-analysis-irregular-areas

If you have some selected features in your aggregation layer, the analysis extent will be automatically updated.

So correct me if I'm wrong, but the analysis extent is working as expected. I agree, it's something new in InaSAFE 4 and it's not very well advertised.
I guess @myarjunar took this ticket for event location map.

**Comment by lrpower** [comment]
@Gustry - you know I never noticed the "**without an aggregation layer"** before!
Yes, it is working as expected - my apologies.
Thanks

**Comment by Gustry** [comment]
No problem. I agree, it's not very visible.

So don't forget that you can select some features in your aggregation layer if you want to run the analysis on a smaller area ;-)
