### ISSUE TITLE
Point Data on Population

### ISSUE THREAD

**Issue by jofloren** [inasafe/inasafe#4592]
I have tried to have create an flood impact function on a point data of population but it is not enabled in my InaSAFE version 4.2.3 OS:Win8 QGIS 2.18

**Comment by Gustry** [comment]
Thanks for the ticket.

We have two options:
* Enable an exposure population dataset to be a point layer
* Enable places to work with population, it overlaps #4483 I guess

First option would be better I think as we may have specific reports for population.
