### ISSUE TITLE
Uncomplete Information in Analysis Information - Map Report

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#4597]
### Problem
I get some different result in the map report when I run an analysis with batch runner. There is some uncomplete information in the `Analysis information` section. When I check it with run manually, I get a different result in that section have a complete information. See image below:
![image](https://user-images.githubusercontent.com/13621886/32592436-3ebac2b2-c556-11e7-9d86-2b0be98196e8.png)

### Expected Behaviour
Complete the information in `Analysis Information` 

### Environment
* InaSAFE : 4.2.3
* QGIS : 2.14.14
* OS : Win-7 Pro
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : Jakarta_Buildings_OSM_WGS84.shp
  * Hazard : Jakarta_Flood_HKV_WGS84.tif
  * Aggregation : Jakarta_District_Boundary_WGS84.shp
  * Extent : 106.657410, -6.379573, 107.002152, -6.082259

### Proposed Solution
Make it happen

Cc: @ivanbusthomi @samnawi @myarjunar

**Comment by Charlotte-Morgan** [comment]
also happening in the manual run now

**Comment by Gustry** [comment]
Linked to https://github.com/inasafe/inasafe/issues/4716 about the wrong expression to fetch the source in keywords
