### ISSUE TITLE
Make a Converter from Keywords 4.x to 3.5 for GeoSAFE

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4604]
### Problem
Currently, GeoSAFE is still working with InaSAFE 3.5, that needs keywords version 3.5 also. Since the current active InaSAFE is 4.x, we can't use the active version of InaSAFE to set keywords for GeoSAFE.

Short term solution is creating a converter tool from InaSAFE keywords 4.x to InaSAFE keywords 3.5.

This tool will be used until GeoSAFE migrate to 4.3

**Comment by timlinux** [comment]
Note that we will not always be able to map keywords from 4.3 to 3.5. In those cases we will raise an exception.

**Comment by ismailsunni** [comment]
Basic functionality is working, I have several polishing ideas. I will put in the other ticket.
