### ISSUE TITLE
Multi-Exposure serialisation needed

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#4612]
### Problem

Multi-exposure products should have keywords set and show summary

When running multi-exposure, the output dataset should be given keywords so that when we select it we can see the summary table in the dock and not the InaSAFE 'no keywords' error.

<img width="1676" alt="screen shot 2017-11-14 at 09 24 18" src="https://user-images.githubusercontent.com/178003/32767785-a0465a62-c91d-11e7-8f4b-ef148a343005.png">

To do this we need for print support to.

**Comment by Gustry** [comment]
This will be covered by https://github.com/inasafe/inasafe/pull/4582

**Comment by Gustry** [comment]
Covered also in the PR above. We might need to tweak it again a little bit
