### ISSUE TITLE
Smoothed MMI and contours should be produced as pre-processor step

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#4615]
### Problem

We should automatically generate the smoothed MMI grid and contours during IF run and then make this available as 'future products' so that they can be used in the multi-exposure dialog.

**Comment by ismailsunni** [comment]
The smoothing is happening in the parsegrid function, in the ShakeGrid class. So, we need the grid.xml file to get the contour in the current structure. There are two options:

1. Put the grid.xml URI in the `extra_keywords ` of the shakemap.tif. It should be easy to do. But, I am wondering will it work properly in GeoNode / GeoSAFE / Realtime.
    a. GeoNode doesn't accept xml only file to be uploaded (CMIIW). So, we can't upload the grid.xml
    b. We only able to upload shakemap.tif to the GeoNode, that means we need to convert grid.xml first then upload shakemap.tif to the GeoNode. If we convert it in desktop, obviously the geonode couldn't find the grid.xml, then GeoSAFE can't have the contour.
    c. If it's in realtime, may be we can make the URI of grid.xml accessible from GeoSAFE also. Then it will be fine.

2. Change the structure so that we can do this conversion : grid.xml --> shakemap.tif --> grid.xml (or csv). This has some advantages:
     a. No need external file, since we can do everything from the shakemap
     b. Easier to use in realtime
    But, we should make sure we can do the shakemap.tif --> grid.xml (or csv) part. I checked the code, it use a gdal command `gdal_grid`:
```
/Library/Frameworks/GDAL.framework/Versions/Current/Programs/gdal_grid -a nearest -zfield "mmi" -txe 122.14 128.14 -tye 2.465 8.435 -outsize 241 240 -of GTiff -ot Float16 -a_srs EPSG:4326 -l mmi "/Users/ismailsunni/Downloads/20170429042741-grid-vakso.vrt" "/Users/ismailsunni/Downloads/20170429042741-grid-vakso-nearest.tif"
```
I am not sure this command is reversible (to make csv from tif).

What do you think @timlinux @Gustry @lucernae ?

**Comment by timlinux** [comment]
@ismailsunni Maybe I am just missing something but:
if we have a gdal dataset (tif) and you want to process it with numpy
it is trivial to turn that gdal layer into a numpy array
we dont need to do such complex workflows
e.g. https://gis.stackexchange.com/questions/32995/how-to-fully-load-a-raster-into-a-numpy-array

**Comment by Charlotte-Morgan** [comment]
@ismailsunni -as discussed in gitter
@timlinux and I discussed if there was some upstream fix that would assist with grid.xml pre processing.
From discussion with @hadighasemi - the expectation is that grid.xml files are point data on a regularly spaced (x,y) grid.
Examination of the header in a recent grid.xml shows that the grid spacing is slightly off square *
_nominal_lat_spacing="0.024975" nominal_lon_spacing="0.025000"_ 
Hadi suggests that rounding the values to fewer decimal places would quickly bring things back into the square and remove any further preprocessing steps to rectify this.
I would tend to agree that using 4 decimal places and not 6 might be better than running an interpolation unless there is some need to change the cell size dramatically.

* note: in a geographic grid the linear distance between degrees is not constant in x and y.

**Comment by ismailsunni** [comment]
Done in #4832, we can polish it again if needed.

**Comment by timlinux** [comment]
<img width="483" alt="screen-shot-2018-01-18-at-17 13 40" src="https://user-images.githubusercontent.com/178003/35097816-7384c796-fc5a-11e7-9a70-ad765fce2b8e.png">
