### ISSUE TITLE
Metadata Converter Polishing

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4625]
### Problem
Basic functionality is working and merged to develop. But there are still some polishing to do:

- [x] Add unit test for the dialog (@ismailsunni)
- [x] Icon for the tool @MariaSolovyeva 
- [x] Fill the help text properly (currently lorem ipsum) @timlinux 

I will make it release blocker since it's not good to have wrong icon or missing help text.

Reference: #4604

**Comment by Charlotte-Morgan** [comment]
see #4732 for UI issue and #4733 for screenie

**Comment by ismailsunni** [comment]
Last item is done, closing this.
