### ISSUE TITLE
More profile polishing

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4630]
Hi @ismailsunni - this new profile wizard and the extra options tab looks great.  I would like to offer some suggestions on the text and a little bit about functionality. I apologise if any of my suggestions have already been considered - I'm sure some have.

**In the first run wizard: Welcome Screen**
1.  I propose the text be tweaked to say:

_Welcome to InaSAFE. Before you begin using InaSAFE, we would like to encourage you to review some options that will used by InaSAFE. On the "Organisation Profile" tab you can set options related to your organisation such as: the name and logo.
The "parameters" tab is used to define some parameters that will be used by InaSAFE in the  analysis of exposed population.  You have the option to change the parameters for whether exposed people are considered to be "affected" by each hazard type and class and the displacement rate that will be used for those affected people. 
Please refer to the InaSAFE manual for concept definitions and more information on the source of hazard classifications and default settings. We really encourage you to consider these parameters carefully and to choose appropriate values for your local situation based on past events and expert knowledge. 
You can return to these options any time by using the Plugins -> InaSAFE -> Options menu._

It would be great to add a link to the manual if that is possible.

2. It is possible to add a save option on this welcome screen or maybe a statement at the end of the welcome text about being able to save the options if you return to them at Plugins -> InaSAFE -> Options menu

3. I think the check box text should say "Always show welcome message when opening InaSAFE" or "Always show welcome message when opening QGIS with InaSAFE"

--------------------------------
**In the first run wizard: Parameters tab**
1. I propose we change the text to say " Please set parameters for population exposed to each hazard class below." 
and then add a link to the definitions for affected and displaced people from the manual.

ie make the following text appear on the parameters tab, just like we do in the reports.

Affected People | People who are affected by a hazardous event. People can be affected directly or indirectly. Affected people may experience short-term or long-term consequences to their lives, livelihoods or health and in the economic, physical, social, cultural and environmental assets. In InaSAFE, people who are killed during the event are also considered affected.UNISDR (2015)Proposed Updated Terminology on Disaster Risk Reduction: A Technical Review
-- | --

Displaced People | Displaced people are people who, for different reasons and circumstances because of risk or disaster, have to leave their place of residence. In InaSAFE, demographic and minimum needs reports are based on displaced / evacuated people.UNISDR (2015)Proposed Updated Terminology on Disaster Risk Reduction: A Technical Review
-- | --

I know this tab may evolve in future to include other parameters but we can deal with that later.

2. column widths. 
I suggest the classification column is made wider and the displacement rate column narrower

------------------------------------------------------------
**Disclaimer**

Do we have any disclaimer text to include on InaSAFE reports that states that parameters are user defined and not defaults? 

--------------------------------------------------------------
** Wizard vs Options**
Did you consider opening the whole options dialog in the first run?
Its possible users would want to modify demographic defaults more than they want to modify parameters for their organisation.
Did you consider a button to "open options"  on the first run wizard 
Did you consider a button to 'save' on the first run wizard

**Comment by ismailsunni** [comment]
> I propose the text be tweaked to say:

Ok, I will need to translate it also.

> It would be great to add a link to the manual if that is possible.

Do you mean the website page for the manual?

> It is possible to add a save option on this welcome screen or maybe a statement at the end of the welcome text about being able to save the options if you return to them at Plugins -> InaSAFE -> Options menu

Actually, the `Ok` button is the save button. Should I change the behaviour and add the save button?

> I think the check box text should say "Always show welcome message when opening InaSAFE" or "Always show welcome message when opening QGIS with InaSAFE"

Ok, it's clearer, agree.

> I propose we change the text to say " Please set parameters for population exposed to each hazard class below."

Ok

 > and then add a link to the definitions for affected and displaced people from the manual.

What do you mean with link here? Is it like a link to a web page? Or should we just add a tool tip when the user hover to the header? Or should we put those two definitions below the tree?

> Do we have any disclaimer text to include on InaSAFE reports that states that parameters are user defined and not defaults?

I think I only put the number, but doesn't say anything if it's default or not.

> I suggest the classification column is made wider and the displacement rate column narrower

Ok


> Did you consider opening the whole options dialog in the first run?

Yes, but it will make the first run too complicated (seeing many tabs).

> Its possible users would want to modify demographic defaults more than they want to modify parameters for their organisation.

Should we also put the demographic tab in the welcome dialog then?

> Did you consider a button to "open options" on the first run wizard

Not yet. But may be it can be the alternative rather than adding more tabs in the first run dialog.

> Did you consider a button to 'save' on the first run wizard

Yeah, like I said above. Should we add `save` button and change the behaviour of `Ok` button?

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan more discussion, if I added Save button, what will be the behaviour of `Ok` button? Is Ok button = Save + Close the dialog ?

List polishing, beside the one that I put in the PR #4663 

- [ ] Add open options in welcome message dialog
- [ ] Add save button
- [ ] Put notes that the current analysis is not using the InaSAFE default one (can you take this @myarjunar ?, perhaps just compare the used one and the default one). 
- [ ] Add definition and links below the dialog to the manual. Is it something like this [Hazard](http://manual.inasafe.org/en/index.html#Hazards). Just to confirm, the location would be in the red bix below:
    <img width="930" alt="screen shot 2017-11-22 at 17 15 09" src="https://user-images.githubusercontent.com/1421861/33123448-d03141ac-cfac-11e7-9db4-cd5ed97ff7c0.png">
     I think it will take some space, is it ok? There is also an alternative way to put it as tool tip or question mark if the mouse is hovering the column.

**Comment by Charlotte-Morgan** [comment]
Maybe a save button and then ok is the close button (close without saving)
I think its important to have the definitions for affected and displacement. We could add more to the welcome page or maybe your mouse over tool tip for the column heading is a good idea.

**Comment by Charlotte-Morgan** [comment]
or we can add it to the help which does not yet describe the new parameters or organisation profile tabs
@timlinux

**Comment by Charlotte-Morgan** [comment]
@ismailsunni  - more suggestions about parameters polishing (now that I wrote some help).. I think the displacement rate should be greyed out for all hazard classifications that are not available to population exposure.

ie if when i set key words for a hazard only some classes are available for population exposure - then only those classes should invite people to set displacement rates (because we only use displacement for population exposure).

all classes still need to give the option to consider  them affected or not.

**Comment by Charlotte-Morgan** [comment]
@ismailsunni - can you please change the text again (my mistake - I owe you ice cream)
On the parameters tab the text should read:
"Please set parameters fro features exposed to each hazard class below. Affected status applies to all exposure types. Displacement rate only applies to population exposure."

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
Regarding the displacement rate, I agree to disable the one that has nothing to do with population. Or should we even remove the displacement rate in the GUI? Do we need also to remove the displacement rate from the classification definitions? 

This parameters are only applied to calculation with population exposure. For the other exposure, we are using the default one from the definitions. I remember that in this first step, we want to make the profile only for populaiton only. So, should I also remove the affected for non-population classification?

Summary:
1. Should we remove the displacement rate for classification which doesn't support population from the GUI?
2.  Should we remove the displacement rate for classification which doesn't support population from the definitions?
3. Should we just remove the classification that doesn't support population? It won't be used anyway. Since we only use the value from this setting for the population analysis.


cc @timlinux perhaps you want to comment also

**Comment by Charlotte-Morgan** [comment]
Summary:

1. Should we remove the displacement rate for classification which doesn't support population from the GUI?
I think this is a good idea - will make the interface more user friendly and save the users changing things that will have no effect.
2. Should we remove the displacement rate for classification which doesn't support population from the definitions?
@timlinux and I discussed this once before and the choice was to leave things consistent in the code - ie have displacement rate even though its not used.
3. Should we just remove the classification that doesn't support population? It won't be used anyway. Since we only use the value from this setting for the population analysis.
Yes - i think so.

Summary:
remove displacement rate for non population classifications.
disable affected for non population for this step 1 with the plan to enable in the future

We need to make sure help is well aligned with the functionality - I think I need to update text and screenies again when you have updated the parameters
 #4676

**Comment by timlinux** [comment]
+1 to filter the list of classifications to only include population related classes (as per our weekly standup discussion)

**Comment by ismailsunni** [comment]
I have implemented the filterin gin #4691 Please check @Charlotte-Morgan
