### ISSUE TITLE
Exception reading keywords

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#4632]
### Problem

Reported by @lrpower :

```
2017-11-19T18:45:36    1    Traceback (most recent call last):
              File "C:/Users/PCUSER/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 662, in get_layers
                if title and self.set_layer_from_title_flag:
            UnboundLocalError: local variable 'title' referenced before assignment
```

> InaSAFE now does not recognise any of my data even after i run through the keyword wizard. And this is my usual data so it has keywords.

### Environment
* InaSAFE : 4.2.3
* QGIS : 
* OS : 
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution

**Comment by ismailsunni** [comment]
I think I already fix this, see https://github.com/inasafe/inasafe/pull/4484

The more is coming from the `.pyc`. We just need to remove them. See here : https://github.com/inasafe/inasafe/wiki/Common-Problem-in-Developing-and-Testing-InaSAFE#solution

**Comment by ismailsunni** [comment]
But it seems it hasn't been backported to master.
I have made a PR to backport it in #4634
