### ISSUE TITLE
Click Print: impact layer not symbolised correctly

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4637]
## problem ##
The 'impact layer' that is regenerated when we click on the 'print' option in the dock is displayed with a default symbology - ie polygons all the same colour for the whole analysis area

This is fine if we want to use the composer to make some changes but not good if we just click on "Print as PDF" when the print uses the default symbology rather than standard symbology

## proposed solution ##
The 'impact layer' should open with the standard symbology for that 'hazard x exposure' analysis combination.

**Comment by myarjunar** [comment]
Hi @Charlotte-Morgan , thanks for creating a ticket on this. Could you give me more details on this issue?

**Comment by Gustry** [comment]
Confirmed with me too.
The impact layer lost its symbology either in the QGIS composer or in the PDF when we press the `Print` button.
![screen shot 2017-11-22 at 15 07 51](https://user-images.githubusercontent.com/1609292/33131546-270ca0d6-cf97-11e7-8779-51b4741a013d.png)

Moreover, layers added to my legend eveytime, adding more and more layers
