### ISSUE TITLE
Multi Exposure Tool polishing

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4639]
Some suggestions for polishing the multi exposure tool.

On the analysis tab: suggest changing the text from " The impact function will **aggregate** the results ... in one report"  to
" The impact function will **combine** the results ... in one report"

because I think we already use the word aggregate to mean many other things
**bold** is for emphasis in this ticket only 

----------------------
On the reporting options tab
Suggest the following wording to replace the existing wording

"You can choose some of the available layers from the left panel to include in the map report by dragging them to the right panel.  You can also control the order of layers in the map report.  All layers remaining in the left panel will be turned off in your map report.  If you leave the right panel empty, the default legend will be used."

**Comment by Gustry** [comment]
Fixed in PR above
