### ISSUE TITLE
Print as PDF with a only one single template is generating 2 templates

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#4664]
### Problem

If I press print on this window:
![screen shot 2017-11-22 at 15 16 23](https://user-images.githubusercontent.com/1609292/33131873-3054fcaa-cf98-11e7-9f5d-bd5389aa4ef8.png)

I got two templates which have been printed in my folder:
![screen shot 2017-11-22 at 15 13 24](https://user-images.githubusercontent.com/1609292/33131884-3b580af2-cf98-11e7-964a-69551d56d0ab.png)

### Expected Behaviour

Only the selected template must be printed

**Comment by myarjunar** [comment]
on my last discussion with @timlinux , we agreed that we want to print the default template and possibile hazard-exposure template as well. CMIIW

**Comment by Gustry** [comment]
ok, but the `portrait` one is not one of the hazard-exposure combination. Is-it?

**Comment by myarjunar** [comment]
no its not, but it comes with the default template (landscape and portrait). We can make it work as we agreed on which report that we want to be generated when we use the print button
