### ISSUE TITLE
Custom logo doesn't appear in map report

### ISSUE THREAD

**Issue by wcarthur** [inasafe/inasafe#4671]
### Problem
I've set a custom organisation logo in the InaSAFE options dialog:
![image](https://user-images.githubusercontent.com/4098490/33155030-ffa7cb2e-d040-11e7-85dc-790bf7fb2150.png)

It appears in the InaSAFE Dock:

![image](https://user-images.githubusercontent.com/4098490/33155053-26f87b7e-d041-11e7-807b-b4f0451df8cf.png)

But doesn't appear in any of the PDF or HTML reports. 

![image](https://user-images.githubusercontent.com/4098490/33155085-61487bc6-d041-11e7-8e74-ecdb2ca73d9a.png)

### Expected Behaviour

Custom logo to appear on the reports in place of the default supporters logo

### Environment
* InaSAFE : 4.2.4
* QGIS : 2.18.6
* OS : Windows 7 (64-bit)
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ?

**Comment by Charlotte-Morgan** [comment]
hi @myarjunar I can replicate this in 4.3 as well.
I can fix the logo problem if I disable the expression in the map template. 
I am not sure why the expression is not working - it looks sensible to me :)
![image](https://user-images.githubusercontent.com/5743135/33155690-b3a48450-d046-11e7-8d2e-57cf6b484371.png)

**Comment by wcarthur** [comment]
Appears the organisation_logo_path() function is returning the default value, irrespective of any customisation. Same applies to the disclaimer text....
