### ISSUE TITLE
Consistency: ratios and percentages - again

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4682]
## problem ## 
The treatment of ratios and percentages in InaSAFE is inconsistent.
Eg; in the options we invite users to set displacement rates as a percentage 
![image](https://user-images.githubusercontent.com/5743135/33190265-027b1b1c-d0ff-11e7-9dfb-13f66456335b.png)

But in the demographic defaults the users are asked to define ratios as a proportion of 1.
![image](https://user-images.githubusercontent.com/5743135/33190656-243d746c-d103-11e7-8d7a-19cb4d6ef747.png)

## proposed solution ##
InaSAFE should be consistent in the way it handles rates for displacement or demographic groups etc
my preference is a percentage ie value between 0 and 100.

I recommend that we update demographic ratios to match the descriptions.
This has been discussed before but not resolved, maybe its time to resolve now that we have different approaches in a single options dialog

**Comment by ismailsunni** [comment]
We need to update the description and the help. The percentage spinbox has been done in #4692 

Hi @Charlotte-Morgan 
still in the same percentage spinbox, should I make the field mapping tool / demographic tool to use percentage also?
<img width="1087" alt="screen shot 2017-12-01 at 05 47 05" src="https://user-images.githubusercontent.com/1421861/33459020-1c57538c-d65b-11e7-8bcf-a14317120227.png">

**Comment by Charlotte-Morgan** [comment]
Yes please

**Comment by ismailsunni** [comment]
I think we can close this, already implemented in field mapping tool and demographic default.
