### ISSUE TITLE
Error when trying to open InaSAFE options

### ISSUE THREAD

**Issue by myarjunar** [inasafe/inasafe#4683]
### Problem

![python error_157](https://user-images.githubusercontent.com/11134669/33198647-fda3006c-d11e-11e7-93d8-30ec60d0f626.png)

### Expected Behaviour

No error

### Environment
* InaSAFE : develop
* QGIS : 2.14.17 Essen
* OS : Ubuntu
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ?

**Comment by ismailsunni** [comment]
Can you give more details @myarjunar ?

Can you also check in python console:
```
from PyQt4.QtCore import QSettings
QSettings().value("inasafe/profile")
```

**Comment by ismailsunni** [comment]
I am pretty sure that your QSettings is not clean. I can replicate your problem by doing:
```
from PyQt4.QtCore import QSettings
QSettings().setValue("inasafe/population_preference", None)
```

It should never happen. I will just put it in try catch to get the correct format of dictionary.
