### ISSUE TITLE
Volcanic Ash - hazard classes

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4720]
## Note ##
A request has been received from Badan Geologi to modify the volcanic ash hazard classes. Specifically to change the lower threshold of the very low class from >0.01 to >0
Geoscience Australia has advised that this is not scientifically valid and that it would still not produce the desired outcome (in this particular case, show ash on the ground in places where the model indicates that no ash will be on the ground).

This note is here to record this conversation and to confirm that the volcanic ash classes remain valid. Please feel free to contribute to the conversation. 

No action is required at this stage. 
![image](https://user-images.githubusercontent.com/5743135/33530607-0a74762c-d8d6-11e7-927b-4118e6b2b00c.png)

### cc ###
@RikkiWeber @timlinux @gubuntu @estukriswati @ivanbusthomi

**Comment by Charlotte-Morgan** [comment]
Closing this now as no further discussion has occurred

**Comment by ismailsunni** [comment]
Helping @Charlotte-Morgan to close this ticket. I hope it's ok :)
