### ISSUE TITLE
Bug: demographic analysis

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4721]
## problem ##
I get a python error when running earthquake analysis on population. 

## environment ##
Windows, QGIS 2.18, InaSAFE 2.3
Data: Jakarta population vector, Earthquake raster.

## error message ##
```
2017-12-04T15:52:45	0	The impact function could not run because of a bug.
2017-12-04T15:52:50	0	****Problem
			
			    The following problem(s) were encountered whilst running the analysis.
			
			 - InvalidLayerError
			
			****Suggestion
			
			    You can try the following to resolve the issue:
			
			 - inasafe_fields has more fields than the layer exposure itself : set(['infant'])
			
			*****Details
			
			    These additional details were reported when the problem occurred.
			
			 - inasafe_fields has more fields than the layer exposure itself : set(['infant'])
			
			*****Diagnostics
			
			 1. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1419, in run self._run()
			 2. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 126, in with_profiling ret = fn(*args, **kwargs)
			 3. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1620, in _run self.exposure_preparation()
			 4. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\utilities\profiling.py", line 126, in with_profiling ret = fn(*args, **kwargs)
			 5. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 2226, in exposure_preparation self.debug_layer(self.exposure)
			 6. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1371, in debug_layer check_inasafe_fields(layer)
			 7. In file "C:/Users/AIFDR_ADMIN/.qgis2/python/plugins\inasafe\safe\gis\sanity_check.py", line 48, in check_inasafe_fields raise InvalidLayerError(message)
			
```
 ## observations ##
1. Key words on population data: the same field F_0_4 has been used for infant and under 5 (I'm only running analysis for females)
![image](https://user-images.githubusercontent.com/5743135/33536904-298f25bc-d90c-11e7-9aa6-60cee15d92b3.png)

2. the analysis runs as expected if I do not include both infants (age group) and under_5 as age vulnerability group.

3. the analysis runs as expected with the same attributes used for both elderly (age) and over_60 as age vulnerability.

4. it looks to me like a problem with the concept of infant

## proposed solution ##
InaSAFE should run analysis with the same population attribute being used multiple times for different demographic measures.

### cc ###
@timlinux @samnawi @ismailsunni

**Comment by Gustry** [comment]
Can you try the PR above ? Thanks

**Comment by Gustry** [comment]
I merged the PR above. So I expect this ticket to be closed?

**Comment by Charlotte-Morgan** [comment]
thanks @Gustry - this is working now
