### ISSUE TITLE
OSM downloader

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4722]
## problem ##
OSM downloader is not fetching any buildings in Jakarta

## proposed solution ##
OSM downloader fetches buildings in Jakarta

**Comment by Gustry** [comment]
The hard drive was full on the server, because of logs.
Notes from @timlinux https://github.com/kartoza/osm-reporter/commit/dfa87d01138025cd816c636046918218d4407e9c

**Comment by Charlotte-Morgan** [comment]
Hi @Gustry and @timlinux - the problem is not resolved. If I try a large area I get a network time out area and if I try a small area I get the same error. I can try on a different network I guess :)

**Comment by Gustry** [comment]
Everything is fine me. I can download a shapefile: http://osm.inasafe.org
