### ISSUE TITLE
salah hitung keterpaparan

### ISSUE THREAD

**Issue by auliaismi** [inasafe/inasafe#4731]
### Problem
Saya menghitung menggunakan data punya BIG kok hasilnya berbeda dengan OSM
```
Copy/paste some InaSAFE logs here if it was an error.
```

### Expected Behaviour
Hasil hitungannya seharusnya mendekati nilainya
### Environment
* InaSAFE : versi 3.4
* QGIS : versi 2.10
* OS : windows 7
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : building
  * Hazard : banjir
  * Aggregation : BIG
  * Extent : 
  
Checklist (if applicable): 
* [x ] Did you try to run it in debug mode ?
* [x ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
Coba cek kalkulasinya

@ismailsunni @felix-yew @samnawi

**Comment by ismailsunni** [comment]
pertmax gan

**Comment by ismailsunni** [comment]
Coba cek #4730

**Comment by ismailsunni** [comment]
*tebal*
_test_
# ## _test_

- dgfhgfhgf
- jkhjkhjk
- jjljlj

> quote

`code`


[Google](google.com)

@auliaismi 

#4730
