### ISSUE TITLE
FMT allows empty attribute list

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#4739]
### Problem

Problem raised in #4729 from @Charlotte-Morgan 

It seems the FMT tools allows an empty attribute list, cf females in the screenshot:

![image](https://user-images.githubusercontent.com/5743135/33642100-772d63ac-da8c-11e7-9650-80d81a303a39.png)

This will raise an exception in the impact function when we run it.

### Expected Behaviour

FMT shouldn't allow an empty field list

### Environment
* InaSAFE : develop

**Comment by ismailsunni** [comment]
Done.
