### ISSUE TITLE
Update earthquake on population notes

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4744]
## problem ##
There is nothing in the notes or manual to explain how we report on earthquake fatalities.

## proposed solution ##
We need to update the earthquake on population notes to explain how fatalities are reported as ranges with no rounding.
see #3666 for implementation of the following ranges for reporting earthquake fatalities
0 - 100
100 - 1,000
1,000 - 10,000
10,000 - 100,000

Notes currently state:
 _The fatality calculation assumes that no fatalities occur for shake levels below 4 and fatality counts of less than 50 are rounded down._
and _For this analysis, the following fatality rates were used: X - 3.145%, IX - 0.787%, VIII - 0.185%, VII - 0.039%, VI - 0.003%, V - 0%, IV - 0%, III - 0%, II - 0%, I - 0%_

I propose to update the notes to say:
 _The fatality calculation assumes that no fatalities occur for shake levels less than or equal to V on the MMI scale._
_Estimated fatality counts are reported as ranges. The following ranges are used: 0 - 100, 100 - 1,000, 1,000 - 10,000, 10,000 - 100,000._

@lucernae or @myarjunar can you please confirm if we still round down or disregard fatality estimates of less than 50

cc
@hadighasemi @RikkiWeber

**Comment by myarjunar** [comment]
@Charlotte-Morgan I don't find anything in the code especially on the reporting side where we round down fatality counts below 50. So I would say that we already removed that kind of rule, except they are being used in the postprocessor. 
>The fatality calculation assumes that no fatalities occur for shake levels less than or equal to V on the MMI scale. Estimated fatality counts are reported as ranges. The following ranges are used: 0 - 100, 100 - 1,000, 1,000 - 10,000, 10,000 - 100,000.

are we removing the fatality rates note?

**Comment by Charlotte-Morgan** [comment]
Hi @myarjunar - I will look after the notes. No we are not removing fatality rate notes, but maybe the one about under 50 is rounded down.
Could you please explain more about the post processor? Is there something in the post post processor that handles fatalities less than 50?
Ie if less than 50 do we report no fatalities or report a range of 0 - 100
or is the range 0 - 100 only used for fatalities more than 50?
