### ISSUE TITLE
Jendela InaSAFE Metadata Converter tidak bisa menyesuaikan resolusi monitor

### ISSUE THREAD

**Issue by meysita** [inasafe/inasafe#4746]
### Problem
Ketika membuka jendela inasafe metadata converter, tampilan terlalu panjang, sehingga beberapa konten seperti pengaturan hazard dan tombol ok, cancel, tidak tampak pada monitor.

![image](https://user-images.githubusercontent.com/34266789/33699568-8604c61c-db46-11e7-9f4e-f186a3af2713.png)

### Expected Behaviour
Harapan saya, sebaiknya ukuran jendela bisa disesuaikan dengan resolusi monitor yang ada
### Environment
* InaSAFE : 4.2.5
* QGIS : 2.14.1
* OS : windows 8
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
make it happy

cc @ismailsunni @lucernae

**Comment by ismailsunni** [comment]
Terima kasih mbak @meysita atas issue-nya. Issue serupa sudah pernah dilaporkan di #4732 

Silakan ditunggu patch-nya...

**Comment by Gustry** [comment]
Do you have a workaround @ismailsunni ?
This issue is coming from the keyword viewer. I got it in the multiexposure dialog.
I moved it to another tab and it magically fixes the issue.

**Comment by ismailsunni** [comment]
@Gustry not yet :D I thought it was easy :) *still trying to fix it

**Comment by Charlotte-Morgan** [comment]
see #4732

**Comment by ismailsunni** [comment]
Fixed in #4748
