### ISSUE TITLE
Intermittent QGIS crash dump

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4750]
### Problem
InaSAFE analysis runs but fails to load data to TOC and exists with a QGIS crash dump
It seems to be triggered when I change key words on the exposure data set.

Comments from #4729 
Basically I am using one vector population data set and setting kw and options for different analysis runs. I am also changing the title so my analysis details have some record of the data.
ie only females and only some age groups
then males
then disabled etc
I get the feeling something is held in memory and clashes when I change the key words and title.
The process runs but then crash dumps with no new layers in TOC and a flash of kw in the dock. No error messages.

### Expected Behaviour
InaSAFE runs and QGIS remains open. If there is an error, then the user gets a nice error message just before the crash dump (or even instead of the crash dump)

### Environment
* InaSAFE : 4.3 Develop
* QGIS : 2.18.14
* OS : Windows
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : Vector population for Jakarta
  * Hazard : Sunda 7.8 raster earthquake
  * Aggregation : Jakarta districts
  * Extent : Jakarta DKI
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
We need to write a user friendly error message
Maybe - we need to find a tidy way of clearing memory and resetting key words.

**Comment by Gustry** [comment]
Thanks for the ticket. It's difficult to debug a crash. I thinking about old field index in the layer, according to what you are describing.
Does it happen with master as well?
It seems you are using the do-not-share hazard file?
Do you have layers in your folder on the file system?

**Comment by Charlotte-Morgan** [comment]
closing this one - not likely to try this analysis again
