### ISSUE TITLE
Polish Print Dialog

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4776]
### Problem
- [x] Disable option that not possible, for example check box for `Print infographic report as PDF` if the 
analysis doesn't have it (only population IIRC)
- [x] Open the current template file's directory when choosing the custom template file.
- [ ] It's quite strange to have `Open as PDF` in the left (on MacOS), just make sure it's consistent with the other tool.
- [x] In the 3rd option of `Custom and map report`, give more explanantion how to add the template override (e.g. `You can add the [override_filename] in the [directory] to use this option`)

**Comment by myarjunar** [comment]
> In the 3rd option of Custom and map report, give more explanantion how to add the template override (e.g. You can add the [override_filename] in the [directory] to use this option)

this is already there in the help of the dialog

**Comment by myarjunar** [comment]
> It's quite strange to have Open as PDF in the left (on MacOS), just make sure it's consistent with the other tool.

is it still bothering you ? it is in normal order on Ubuntu @ismailsunni

**Comment by ismailsunni** [comment]
I think it's fine (still in the left, but it's not a big problem). I will close this.
