### ISSUE TITLE
Multiexposure Dialog

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4793]
- [x] Padding in the text
- [x] Replace `Impact Function` with `InaSAFE Analysis`
- [x]  Indincate that aggregation use subset (in the combobox) *perhaps also for exposure, since @Gustry creates analysis on the selected exposure.
- [x] Change the style of the output of multi exposure analysis (combined analysis summary and combined aggregation summary) change color mostly, to make them more differentiable

**Comment by Gustry** [comment]
There is a ticket for all of them already waiting for the review: #4784
