### ISSUE TITLE
BUG: infographic report

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4797]
### problem ###
The infographic report is showing a graph of affected when it is infact exposed population
![image](https://user-images.githubusercontent.com/5743135/34063731-039343bc-e248-11e7-88cb-5cdcb4407019.png)

### proposed solution ###
Change the word 'affected' in the report to say 'exposed'

## cc ##
@ivanbusthomi @felix-yew @samnawi

**Comment by felix-yew** [comment]
Yes, I agree with @Charlotte-Morgan to change the word 'affected' to 'exposed' in the chart section.

**Comment by Charlotte-Morgan** [comment]
Hi @myarjunar I am not sure your fix has made it happy just yet.
It looks like you have changed the label and the data so there is still a problem.
In the example above; the data in the graph was the exposed population (I can tell be cause the number is much bigger than the affected population.

This is what i get now
![image](https://user-images.githubusercontent.com/5743135/34861191-4285bcf6-f7b7-11e7-9f60-e1f049ee7b59.png)

The graph is showing affected now but the graph heading says exposed.
We need to make sure the heading describes the data that are shown.
In the current situation; if the graph shows affected, then the title should say affected and the not affected class should be removed from the legend (because there will never be any if you are showing affected) - it would also be great to reduce the number of decimals in the %

However - if the intention is to show exposed in the graph. Then keep the graph title as it is now and show the exposed population in the graph and retain the not affected class in the legend.

ie exposed = affected (in each hazard class) + not affected

cc
@felix-yew @thamrinf
