### ISSUE TITLE
BUG: map template is not zooming

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#4799]
When I ran InaSAFE analysis and printed the default map it was zoomed out a lot more than I expected.
![image](https://user-images.githubusercontent.com/5743135/34135530-566a6542-e4b5-11e7-8618-9f738e8836a7.png)

**Comment by myarjunar** [comment]
Hi @Charlotte-Morgan , no description? I suspect you have forgotten to click the update button again :smiley:

**Comment by Charlotte-Morgan** [comment]
Oh dear - that is the second one today :(

**Comment by Charlotte-Morgan** [comment]
hi @myarjunar - i think you are correct.
I can not replicate this now.
