### ISSUE TITLE
Shakemap Converter Only Give One Threshold

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#4801]
### Problem
After running shakemap converter, I got a tiff shakemap but it only has one threshold:
<img width="528" alt="screen shot 2017-12-18 at 02 49 05" src="https://user-images.githubusercontent.com/1421861/34083150-26b8c478-e39e-11e7-821b-094104896a33.png">

### Expected Behaviour
It should give threshold with exposure specific.

### Environment
* InaSAFE : develop
* QGIS : 2.18
* OS : MacOS

### Proposed Solution
Assign proper threshold for it.

**Comment by Charlotte-Morgan** [comment]
and the threshold should be sorted ??

**Comment by ismailsunni** [comment]
@Charlotte-Morgan yes, it should be sorted. But, it's the same problem as in my comment here https://github.com/inasafe/inasafe/issues/4798#issuecomment-352280396

**Comment by Gustry** [comment]
So it can't be sorted, no? ;-)

**Comment by ismailsunni** [comment]
> So it can't be sorted, no? ;-)

It can, but need to do some magic first :)

**Comment by ismailsunni** [comment]
Hi @ivanbusthomi 
I have unassigned you in this ticket since I need to fix it for creating the contour and work on shakemap converter.
