### ISSUE TITLE
Extra keyword for Volcanic Ash

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#4805]
### Problem
At the moment, there is some extra information that was used in the workflow of volcanic ash realtime. This information is not yet used in the desktop version. in order to properly recreate the volcanic ash realtime report using the InaSAFE desktop, we need to add this information to the hazard file. The information is:
* Volcano name and coordinate
* eruption column height
* Eruption time
* alert level (if possible)

### Expected Behaviour
we can get the information above from the hazard file to replicate the report generated from realtime

### Environment
* InaSAFE : 
* QGIS : 
* OS : 
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
Maybe we can implement the usage of `extra keywords` just like in the earthquake hazard keywords. we maybe can use an extra dialog in keyword wizard to assign this extra information.

___
CC: @ismailsunni @myarjunar @timlinux @Charlotte-Morgan

**Comment by ismailsunni** [comment]
The time has come, when we use `extra_keywords` for more and more.

Steps to do (elaborate what @ivanbusthomi proposed):
- [ ]  List the extra keywords and their type, put it in `safe/definitions/extra_keywords.py`. See the other extra keywords for example
- [ ] Update the wizard to support adding this, if possible make it generic. I suggest to put it in the same step as source, scale, url.

I can help on it, while I am not working on my main priority (realtime), or I can give help for @ivanbusthomi to implement it. It shouldn't be a complex task. Just playing with the✨ ✨  _Wizard_ ✨ ✨ 

Update: ah, it's for 4.4, so relax :D

**Comment by Charlotte-Morgan** [comment]
Hi @ismailsunni
I discovered that there is no such thing as 4.4 ;) and that we will need to implement this now to support the alignment of desktop and realtime platforms.
Can you please advise what components of this are 'new features' that must be included in 4.3 and what might reasonably be considered a 'bug fix' that can be done after 4.3 is released/

@timlinux - copying you in here because I will mark this as a blocker until I am sure its not.

**Comment by ismailsunni** [comment]
Well, I am afraid that all of the components that i mentioned in my previos comment are a new feature.
1. Supports new extra keywords
2. Adding new step in the wizard (for user to assign the keywords)

I am not familiar with how the workflow for ash realtime. Where do they store the information above?

**Comment by ivanbusthomi** [comment]
Hi @ismailsunni ,
> I am not familiar with how the workflow for ash realtime. Where do they store the information above?

In ash realtime workflow, the user uploads the hazard data to the website. In the upload form, the user provides those details manually in addition to the hazard data that are going to be uploaded.

These are the details of the extra information that user provided:

|   Name | Type |   Description    |
| --- | --- | --- |
|   Volcano Name | String | The name of the volcano|
|   Eruption Column Height | Integer | The ash column height. It is calculated from the vent of the volcano. |
|   Eruption Time | Date | The time of the eruption. The data uploaded to the ash realtime is a hazard model, and the information usually valid for certain hours after the eruption time |
|   Alert level | String | This information shows the estimated severity level of the model. It is usually a choice between `Normal`, `Waspada`, `Siaga` or `Awas`

CC @estukriswati @Charlotte-Morgan

**Comment by ismailsunni** [comment]
Basic functionality is finished in #4846 move to polishing in #4851
