### ISSUE TITLE
Can't open an analysis made on another computer

### ISSUE THREAD

**Issue by Gustry** [inasafe/inasafe#4806]
### Problem

if I open a project with an analysis made on another computer:
```
Problem
The following problem(s) were encountered whilst running the analysis.

Exception
Suggestion
You can try the following to resolve the issue:

Check that you have the latest version of InaSAFE installed - you may have encountered a bug that is fixed in a subsequent release.
Check the InaSAFE documentation to see if you are trying to do something unsupported.
Report the problem using the issue tracker at https://github.com/inasafe/inasafe/issues. Reporting an issue requires that you first create a free account at http://github.com. When you report the issue, please copy and paste the complete contents of this panel into the issue to ensure the best possible chance of getting your issue resolved.
Try contacting one of the InaSAFE development team by sending an email to info@inasafe.org. Please ensure that you copy and paste the complete contents of this panel into the email.
Details
These additional details were reported when the problem occurred.

Layer "C:/AIFDR II - SDA/10_InaSAFE Analysis/20171215 Java EQ/Exposure/Java_Population_WGS84.tif" is not valid
Diagnostics

In file "/Users/etienne/.qgis2/python/plugins/inasafe/safe/gui/widgets/dock.py", line 972, in layer_changed keywords))
In file "/Users/etienne/.qgis2/python/plugins/inasafe/safe/impact_function/impact_function.py", line 2703, in load_from_output_metadata impact_function.exposure = load_layer_from_registry(exposure_path)
In file "/Users/etienne/.qgis2/python/plugins/inasafe/safe/gis/tools.py", line 87, in load_layer_from_registry return load_layer(layer_path)[0]
In file "/Users/etienne/.qgis2/python/plugins/inasafe/safe/gis/tools.py", line 217, in load_layer raise Exception(message)
```

I'm not using the computer `Layer "C:/AIFDR II - SDA/10_InaSAFE Analysis/20171215 Java EQ/Exposure/Java_Population_WGS84.tif" is not valid`

### Expected Behaviour

InaSAFE should open the HTML reports and be friendly without an exception.

@myarjunar This errors occurs because we are relying on the layer.source()
But the project in QGIS is fine, it could open all layers from the project:

![screen shot 2017-12-18 at 09 37 06](https://user-images.githubusercontent.com/1609292/34096827-10116f02-e3d7-11e7-8028-8425f4af557f.png)

Any idea we can handle that correctly?
* disable everything if the layer is not found. Not the best one, as the QGIS Project is correct with hazard/exposure layers loaded with impact layers.
* Check the QGIS Settings about saving relative/absolute paths
* ?

It's a regression as it was working before when we were not doing serialization/deserialization but reading HTML files straight from the datastore

**Comment by myarjunar** [comment]
@Gustry what if we show a dialog to fix the path?

**Comment by Gustry** [comment]
At we should be able to display the HTML, right? I have it in my datastore

Then we need to fix the path in order to use the print button, right?

**Comment by myarjunar** [comment]
yes, the path is for the print button

**Comment by Gustry** [comment]
Let's fix that first IMHO.

Even if you show a dialog to print the path, I don't have the original exposure and hazard layer, so it will be an issue, right?

**Comment by myarjunar** [comment]
it would be easier for me. :smiley:  I was giving you my argument on your first option because you said you have the hazard/exposure loaded with the impact layer.

**Comment by Gustry** [comment]
yes ok right in my case. but also maybe users exchange only the datastore. You have many situations, the best would be to have one solution for each ;-)

**Comment by Gustry** [comment]
Thanks for the patch @myarjunar
