### ISSUE TITLE
[GeoNode] How we can bring back the metadata in the layer?

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#4807]
### Problem
I have uploaded some layers in the geonode.inasafe.org a couple months ago. But last week I check in the website I can not find the metadata in the layer. How to bring back the metadata in the layer? By edit metadata or only upload the xml file that has the same name file?

### Expected Behaviour
The metadata can back in the layers

### Environment
GeoNode InaSAFE

### Proposed Solution
Make it happy

Cc: @lucernae @ismailsunni @samnawi @Charlotte-Morgan

**Comment by Charlotte-Morgan** [comment]
Hi @felix-yew - my understanding is that @lucernae ran the restore for you but this has overwritten some subsequent work.  I think we can close this
