### ISSUE TITLE
[GeoNode] How we manage the keyword that not match with the layers?

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#4808]
### Problem
Some of keyword in the geonode did not match with the layer or it need update. How we manage the keyword?

### Expected Behaviour
Tidy up the keyword and make an easy read, especially for the user.

### Environment
geonode.inasafe.org

### Proposed Solution
Keyword can match the layer target and more tidy up.

Cc: @lucernae @ismailsunni @samnawi @Charlotte-Morgan

**Comment by Charlotte-Morgan** [comment]
Hi @felix-yew  - I think you asking how to manage the geonode keywords / tags. Both managing the list of keywords and how those are tagged to data

**Comment by Charlotte-Morgan** [comment]
Hi @ismailsunni - are you the best person to help here ? or please assign to a friend :)

**Comment by ismailsunni** [comment]
Hi @Charlotte-Morgan 
I think @lucernae know better than me, since he is working on geonode lately, and I am not.

**Comment by lucernae** [comment]
I think I already explain the solution to mas @felix-yew here. You can manage the keywords from Django Admin Page (if you have administrator access).

**Comment by felix-yew** [comment]
Hi mas @lucernae - thank you for your explanation, I have enter the Django Admin Page and try your explanation. It works! :+1: Now, I'm still try to manage the keyword. Thank you :+1: 

So we can close this ticket.
