### ISSUE TITLE
Bug : Print button did not work

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#4809]
### Problem
When I want to print the result, unfortunatelly print button didn't work
```
2017-12-18T16:42:44	1	Traceback (most recent call last):
			  File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\gui\widgets\dock.py", line 798, in show_print_dialog
			    self.impact_function, self.iface, dock=self, parent=self)
			  File "C:/Users/kurnia/.qgis2/python/plugins\inasafe\safe\gui\tools\print_report_dialog.py", line 141, in __init__
			    self.is_population = isinstance(exposure_type, exposure_population)
			TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
			
```

I just update my InaSAFE develop version. And I see a new update for print report dialog.

### Expected Behaviour
It have to update 

### Environment
* InaSAFE : develop
* QGIS : 2.18.13
* OS : Win 7 64 Bit
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
Make it happen

**Comment by Gustry** [comment]
Was it a population exposure? (so without any exposure classification in the KW Wizard)

**Comment by samnawi** [comment]
I found it either in population and structure. Maybe it will be occurred in the other exposure.

**Comment by ismailsunni** [comment]
I think it's a bug in the code:
```
			    self.is_population = isinstance(exposure_type, exposure_population)
```

I bet the `exposure_population` is a dictionary.
