### ISSUE TITLE
Combined Aggregation Summary from MultiExposure tools not showing result

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#4814]
### Problem
While trying replicating the volcanic ash realtime report in the InaSAFE desktop, I tried running the multiexposure tools using the population, place and landcover as exposure data against a volcanic ash hazard. I choose to both `Combined Analysis Summary` layer and `Combined Aggregation Summary` layer as result of the analysis. While the `Combined Analysis Summary` layer contains all the expected values from the analysis, the `Combined Aggregation Summary` layer did not contains the expected value even though it already has the expected column/field to store the value. So I think there must be a bug there.

![image](https://user-images.githubusercontent.com/7351977/34149878-346be7f8-e4d9-11e7-8063-00033d4bd751.png)

### Expected Behaviour
The `Combined Aggregation Summary` layer should contain the combined value from each `Aggregation Summary` layer for all combination of hazard vs exposure in the multiexposure analysis tools.

### Environment
* InaSAFE : develop
* QGIS : 2.18.12
* OS : Windows 7
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : Population, Place, Landcover
  * Hazard : Volcanic ash
  * Aggregation : No
  * Extent : all areas
  
Checklist (if applicable): 
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
Make it happy

---
**CC:** @timlinux @Charlotte-Morgan @Gustry @samnawi

**Comment by Gustry** [comment]
I'm failing to replicate your issue. The maximum bug I could have is only one row missing in the combined aggregation summary, but you, all rows are missing.

Can you share your logs and that data if it's possible? Thanks
