### ISSUE TITLE
Landcover Analysis : Incorrect productivity calculation

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#4816]
### Problem
The calculation in landcover analysis for productivity, production cost and production value, seems like has an incorrect calculation in there.
If we look at the picture below, maybe the estimation of loss by affected landcover type calculate using Total area, not using total affected.
**Value setting**
![image](https://user-images.githubusercontent.com/8871958/34155521-4039de56-e4ec-11e7-9a6f-f95c5c49eea4.png)
**Report**
![image](https://user-images.githubusercontent.com/8871958/34155541-5492370e-e4ec-11e7-8db2-36ebbd58bd54.png)

This is the exposure summary table when I run in debug Mode
![image](https://user-images.githubusercontent.com/8871958/34155683-f0b1c794-e4ec-11e7-8ae1-12bb599d253d.png)

From the picture of exposure table in above, for the example, if I try to divide the _affected_productivity_ for _Sawah_ with the rate value, it will be like this
**2360.89800 / 27.9 = 84.62**

**84.62** is the total area for _Sawah_ based on the table in above.

### Expected Behaviour
To generate the loss estimation of productivity, production cost or production value, it should use the 
affected area

### Environment
* InaSAFE : 4.3.0.dev-master
* QGIS : 2.18.13
* OS : Win 7 64 bit
* Data used (filenames and paths so as to reproduce, a project is better):
  * Exposure : [Landuse.zip](https://github.com/inasafe/inasafe/files/1571561/Landuse.zip)
  * Hazard : [Ebulobo KRB.zip](https://github.com/inasafe/inasafe/files/1571556/Ebulobo.KRB.zip)
  * Aggregation :
  * Extent : 
  
Checklist (if applicable): 
* [x] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ? 

### Proposed Solution
Make it happy

**Comment by ismailsunni** [comment]
Hi @samnawi 
Thanks for submitting the issue. I can replicate it with another data. I also get this problem when working on population in place (where the population is always the total of all population, not the affected one).
I will need to ask @Gustry about this. Hopefully, today I can discuss with him.

**Comment by ismailsunni** [comment]
Fixed in #4818
