### ISSUE TITLE
New Exposure layers 

### ISSUE THREAD

**Issue by vanpuk** [inasafe/inasafe#482]
A post to the googlegroups has reminded me that we should write a post processing script to incorporated polygon numbers.  i.e. we have an admin boundary with population number and this gets converted into a raster and then analysed. -this should not be a big problem.
The next problem is the number of house per polygon, could this be a density layer? If it can I would expect we would need to have a new impact function for this exposure.
Happy to discuss further - just wanted to flag this now in a ticket.
Cheer

**Comment by timlinux** [comment]
Closing as old, no details, no active requirement.
