### ISSUE TITLE
[GeoNode] Failed to update metadata by upload the xml file

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#4823]
### Problem
When I try to update the metadata in geonode.inasafe.org through `Edit Layer` - `Upload Metadata` and then upload the xml file for the related layer files. But, when the process upload done, I do not get the results uploaded because I see the metadata is empty instead. Although I have completed the previous metadata in QGIS before I upload it into the geonode.
This is the picture of layer before I upload the metadata:
![upload metadata before](https://user-images.githubusercontent.com/13621886/34240939-649f9bf6-e644-11e7-8bad-d175fd68b843.png)

After done, I check the layer but the result was not as I expected
![upload metadata after](https://user-images.githubusercontent.com/13621886/34240971-9909c0b0-e644-11e7-8c74-2c354c0118e7.png)

I have edited to complete the metadata with MetaTools in QGIS.
![metadata viewer](https://user-images.githubusercontent.com/13621886/34242741-bbc28820-e64f-11e7-8d28-649b43dc681d.png)

Is there any step that I miss? or maybe for upload the metadata need another file, besides the *.xml file?

### Expected Behaviour
geonode can read the xml file and can update and fill the metadata as the user wants

### Environment
geonode.inasafe.org

### Proposed Solution
make it happy

Cc: @lucernae

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geonode#396
