### ISSUE TITLE
[GeoNode] Projection issue in the layers

### ISSUE THREAD

**Issue by felix-yew** [inasafe/inasafe#4856]
### Problem
When we finish upload some layers that have projection in geographical (EPSG:4326), ie jakarta_flood_18113_wgs_no_kw's layer, we can see that the layers can show in list of layer, especially in the thumbnail view that can directly show the type of layer. Then, it will different if we upload some layer with the differerent projection (in addition to EPSG:4326), ie UTM zone 49s, we find a problem to see the thumbnail view. In the list of layer, we can see that the Jalan_Sleman_49s's layer do not have a thumbnail view in the fixed view. See the image below:
![image](https://user-images.githubusercontent.com/13621886/34814961-235786a0-f6e2-11e7-8076-6dce0bacc85c.png)

Let see the different layer with the different projection, in the image below:
![image](https://user-images.githubusercontent.com/13621886/34815934-d9982a20-f6e5-11e7-9349-08404066debc.png)

When we check it in the metadata details, there have a different between them. 
![image](https://user-images.githubusercontent.com/13621886/34816447-8dbb0aee-f6e7-11e7-9b1c-c6cfe5e26ebc.png)
In this case, in the left side, maybe it is same explanation like map view. I think the layer shown but in the very small size. And when we see the layer extent look strange because the Projection System indicate that the layer in EPSG:4326 but why the layer extent show the different format (metres). This case also appear in the list of layer thumbnail preview.
In the right side, the extent layer show accordance with the Projection System. So the layer can directly show in the map view.

I assume that:
1. Maybe the layer in the map view not shown because have the different extent layer. The layer maybe appear, but because of extent layer have a wide coverage so the layer look very small and it as if no image in the thumbnail view.
2. We can see in the metadata details that the extent layer in the left side like in metres UTM's format but the projection system is in EPSG:4326. 
The question is: 
Do uploading layer into the geonode will change or transform coordinate to EPSG:4326? If yes, maybe the coordinate transformation also included the extent layer (ie. from metres/UTM to geographic coordinate)

### Expected Behaviour
If the CRS of layer need to transform into the WGS84 projection, it will better if the extent of layer also transform into the geographical coordinate.

### Environment
geonode.inasafe.org

### Proposed Solution
Make it happy.

@samnawi @adissadis @lucernae @gubuntu

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geonode#395
