### ISSUE TITLE
Documentation for writing impact functions 

### ISSUE THREAD

**Issue by uniomni** [inasafe/inasafe#487]
To assist new developers in writing impact functions, it would help to have some templates e.g. for each combination of hazard and exposure data types.

**Comment by timlinux** [comment]
Closing as old. @mbernasocchi can you add your notes for the processor creating an hazard + classifications to the wiki? Note that we dont really have the same concept of impact functions any more in V4 so it would be better to focus on how to define hazards and thresholds.

**Comment by mbernasocchi** [comment]
will do
