### ISSUE TITLE
Earthquake MMI classes on places

### ISSUE THREAD

**Issue by ivanbusthomi** [inasafe/inasafe#4875]
### Problem
At the moment, the earthquake on place analysis only supports generic classes. The Earthquake MMI scale classification which is specific to the earthquake is not yet enabled. We need to enable it since in InaSAFE Realtime Earthquake, the classification used for place analysis is using the Earthquake MMI classes.

### Expected Behaviour
Earthquake on place analysis can be run using Earthquake MMI hazard classification

### Environment
* InaSAFE : ver 4.3.0-dev
* QGIS : 2.18.15
* OS : Windows
* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
### Proposed Solution
Add the Earthquake MMI scale to the keyword wizard for Earthquake on places.

CC @timlinux @Charlotte-Morgan @ismailsunni @Gustry @myarjunar

**Comment by myarjunar** [comment]
hi @ivanbusthomi  , just to let you know, now we can have a report when we run multi-exposure analysis when there are multi-classifications in the analysis, for example EQ on pop (MMI) and place (generic), check https://github.com/inasafe/inasafe/pull/4868

**Comment by Gustry** [comment]
@ivanbusthomi Don't you need this patch in 4.3?

**Comment by ivanbusthomi** [comment]
Hi @Gustry - I have discussed it with mas @ismailsunni and we agreed that it can go into a bug fix release
>just to let you know, now we can have a report when we run multi-exposure analysis when there are multi-classifications in the analysis, for example, EQ on pop (MMI) and place (generic), check 4868

Ah, I see. thanks for it @myarjunar. I will check it. But I still think there is no reason to not enable Earthquake MMI classes for place data, right?.

**Comment by Gustry** [comment]
Yes sure it can. It was just to know how urgent is this ticket.

**Comment by ismailsunni** [comment]
Fixed in #4877
