### ISSUE TITLE
Add more space for decimal place

### ISSUE THREAD

**Issue by samnawi** [inasafe/inasafe#4900]
### Problem
In case of a minimum needs parameter which has a small ratio, I think we should add more decimal space to fill it in Minimum needs Manager.

example :
A tent should be provided for every 2500 persons.
So, in the default of minimum needs manager, we must fill 0,0004.
But ,currently we just allowed writing maximum 2 decimal place.

![image](https://user-images.githubusercontent.com/8871958/36092477-15b671cc-101a-11e8-8609-dbf559a98cd7.png)

### Proposed Solution
Make it happy

cc : 
@Charlotte-Morgan

**Comment by ismailsunni** [comment]
@samnawi so, how many decimal space that you want ? 4 ?

**Comment by samnawi** [comment]
hi @ismailsunni I think 4 - 6 is OK.

Bang @thamrinf do you have any proposed for it? Some relief which maybe has a smaller ratio such as 1 item for 1,000,000 people?

**Comment by Charlotte-Morgan** [comment]
@ismailsunni - I think this can be done and added to the next available bug fix release please. please allow 6

**Comment by ismailsunni** [comment]
Fixed in #4973
