### ISSUE TITLE
Mohon diganti gunungan di logo Inasafe

### ISSUE THREAD

**Issue by sridewanto** [inasafe/inasafe#4958]
### Problem
Gunungan terlalu jawa sentris, perlu yang lebih meng-Indonesia, misalnya bunga melati atau garuda pancasila. 

Terima kasih sekali

```
Copy/paste some InaSAFE logs here if it was an error.
```

### Environment
* InaSAFE : 
* QGIS : 
* OS : 

* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist: 

* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ?

**Comment by ismailsunni** [comment]
Training purpose only
