### ISSUE TITLE
Perhitungan Keterpaparan yang over estimate

### ISSUE THREAD

**Issue by khoiriyalatifa** [inasafe/inasafe#4959]
### Problem
Perhitungan keterpaparan pada inasafe seringkali over estimate. Misalnya ketika kami mengitung keterpaparan penduduk secara manual hasilnya 31.479 jiwa, tapi hasil di inasafe bisa menjadi 31.500. Inasafe seringkali melakukan pembulatan angka ke atas dan memberikan angka-angka bulat untuk menunjukkan hasil keterpaparan.
```
Copy/paste some InaSAFE logs here if it was an error.
```

### Environment
* InaSAFE : 4.3.2
* QGIS : 2.18.3
* OS : Windows

* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist: 

* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ?

**Comment by samnawi** [comment]
hi @khoiriyalatifa I'll try to answer this problem. There is an explanation of the behave of InaSAFE to present the information about population in [here](http://manual.inasafe.org/en/index.html#Population).

But, if you want to see the actual number, you can also see the attribute table of the impact layer or you can enable the "disable rounding" in the developer mode (set-up from InaSAFE option).

Please don't hesitate to write a comment in here if you still need more detail information about it.

Thank you.

**Comment by timlinux** [comment]
Please close when the reporter indicates they are happy with your explanation.
