### ISSUE TITLE
Request feature to divide analysis report per segment

### ISSUE THREAD

**Issue by danangwijaya** [inasafe/inasafe#4964]
### Problem
When i create a modify report, i try to use **[% analysis_summary_report() %]** to show my analysis result. I just want to show population analysis per agregation area segment, but when i've insert this expression, i get all informastion from it. I can not modify the appearance according to the segment that i want. Can i request an expression feature to separate any report analysis per segment?

When insert **[% analysis_summary_report() %]**,
![image](https://user-images.githubusercontent.com/18339168/37635828-909e7614-2c30-11e8-9a4c-2265746a6f27.png)

but i want to show just this part,
![image](https://user-images.githubusercontent.com/18339168/37635865-cf4647a2-2c30-11e8-9042-b264a2161c36.png)

### Environment
* InaSAFE : 4.3.2
* QGIS : 2.18.14
* OS : Windows 10

* Data used :
  * Exposure : 
  * Hazard : 
  * Aggregation :
  * Extent : 
  
Checklist: 

* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ?

**Comment by ismailsunni** [comment]
I think this is a good idea, to make the user have more option to do customization.
