### ISSUE TITLE
CRS prompt when loading results

### ISSUE THREAD

**Issue by olivierdalang** [inasafe/inasafe#5003]
### Problem

After successfully running an analysis, QGIS prompts for the CRS when loading the results layers.

The prompt appears for each result layer (around 4 times). This is a bit confusing for users.

I think this can be improved with the "use project CRS" layer in QGIS options, but unfortunately the default is "prompt for CRS".

### Environment
* InaSAFE : 4.3.2
* QGIS : 2.18.20
* OS : Windows
* Data used : any
  
Checklist:
* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?

### Proposed Solution

Make sure outputs correctly define the CRS so that there's no CRS prompt on loading them.

**Comment by Gustry** [comment]
You created a new ticket #5013
