### ISSUE TITLE
Name of Tsunami Impact Function is not valid

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#502]
From @takmid : 
If we load tsunami layer and population layer, so that the "FloodEvacuationFunction" will be available, and open the impact function configuration dialog, it will said "Flood Evacuation Function". So, this thing will be not consistent. It would be better if it says "Tsunami Evacuation Function".

But, the problem is they are the same function. And I doubt we can make "if statements" according to the layers that is loaded. Because it will be very messy.

I propose some alternatives:
<b>Change the "FloodEvacuationFunction to more general name for both Flood and Tsunami</b>, i.e. "InundationEvacuationName". And show in the configuration dialog something like:

Parameters for impact function {Function Name} for {Hazard layer's subcategory} on {Exposure layer's subcategory} that can be modified are:

real example:

Parameters for impact function ```Inundation Evacuation Function``` for ```Tsunami``` on ```Population``` that can be modified are:

<b>Create a super/parent class for inundation, and inherit the class to two child-class each for tsunami and flood.</b> And give different FunctionName. Moreover, we can put different aspect/attributes in each class except FunctionName. May be Parameters.

The first alternative is much easier to implement since we only have a problem with the name. But, if we found another aspect that make Tsunami and Flood very different, the second alternative will be better.

Another question, will we put it on version 1.1 ?

cc: @timlinux  @uniomni

**Comment by Charlotte-Morgan** [comment]
Hi everyone,
I think we have made lots of progress on this.
The current thinking is that we have separate IF for flood and tsunami; with different thresholds depending on the hazard and exposure. 
see #1427 #1428 #1251 and #1252.
Regarding terminology; as from version 3.2 we used flooded for floods and inundated for tsunami.

Unless there is anything else not covered by these tickets - i'm closing this one
