### ISSUE TITLE
Linux development environment

### ISSUE THREAD

**Issue by lrntct** [inasafe/inasafe#5026]
I am in the process of setting up a dev environment on Ubuntu 18.04, and I wonder if the [current documentation](https://github.com/inasafe/inasafe/wiki/Development-on-Linux) is up to date. At least the fabgis way seems to have been abandoned.

What is the current preferred way to set-up a dev environment on Linux?

**Comment by lucernae** [comment]
Hi @lrntct . Are you trying to develop InaSAFE? We are currently trying to migrate to QGIS 3 and Python 3, so the documentation is not up to date.
We usually use this step: https://github.com/inasafe/inasafe/wiki/Development-on-Linux#3-manual-installation-guide---linux-debian-based . CC our Linux based developer @myarjunar , maybe I'm wrong.
I think it's safe to say we abandon the fabgis way.
Ubuntu 18.04 with ubuntugis seems perfect for installing QGIS 2.18 (current LTR), I don't think you will have issues with dependencies.
For IDE, anything in Linux is fine, as long as you set the PYTHONPATH to resolve QGIS lib. The wiki is currently showing tips for Eclipse but we're currently using Jetbrains PyCharm Pro for IDE.

**Comment by lucernae** [comment]
I forgot to mention, currently `develop` branch is bleeding edge. If you want to look around, it is best to start from `master` branch.
CC @ismailsunni for confirmation.

**Comment by ismailsunni** [comment]
Hi @lrntct @lucernae 
- `develop` branch is for QGIS 3.2 (with Python 3, Qt5).
- `inasafe_4` branch is for QGIS 2.18 (with Python 2, Qt4).
- `master` branch is currently still for QGIS 2.8 (with Python 2, Qt4), but it will be updated in this month to the latest release of InaSAFE 5.0. I am currently working on releasing InaSAFE 5.0

We will only update `inasafe_4` one if there is a bug fix. 

So, if you want to start, please use `inasafe_4` branch or `develop` (depends on your needs, is it for QGIS 2.18 or QGIS 3).

I will try to update the Linux development env setup also if the time this week allows.

**Comment by Gustry** [comment]
@lrntct Why kind of change do you want to do?

Just do a git clone of the repository and add the clone to your qgis python plugins directory (with symlink for instance). For basic changes, there is nothing more to do.

If you need, you can:
* run tests inside docker with the `make docker-test`
* run tests inside QGIS by enabling developer mode in InaSAFE settings (last tab)

The missing part is auto-completion (PyQGIS and PyQT) if your IDE is not setup correctly.

**Comment by ismailsunni** [comment]
Hi @lrntct 

I have made my set up works for Ubuntu 18.04 with PyCharm CE.

I will write here before updating the wiki:
- Install QGIS 3.2, PyCharm CE, clone inasafe repo (and don't forget the submodule parameter)
- Set python interpreter to python 3.6 and add some paths like below:
![selection_002](https://user-images.githubusercontent.com/1421861/43853166-7d450738-9b69-11e8-9d4d-f5bbc62ea2f6.png)
- Set Unittest as default python test
- Add this variable (QGIS_PREFIX_PATH):
![selection_003](https://user-images.githubusercontent.com/1421861/43853217-adf5d286-9b69-11e8-85db-a2234866eb71.png)

Now, you should be able to run unit test from PyCharm CE.

To load your InaSAFE, do symlink like @Gustry mentioned above.

**Comment by Gustry** [comment]
> Install QGIS 3.2, PyCharm CE, clone inasafe repo (and don't forget the submodule parameter)

do a `git clone --recursive foo.git`

And don't use the plugin reloader in QGIS, it doesn't work for InaSAFE

@ismailsunni for you when you will update the wiki ;-)

**Comment by ismailsunni** [comment]
Hi @lrntct 

I have updated the wiki for QGIS 3. Please check https://github.com/inasafe/inasafe/wiki/Development-on-Linux#manual-installation-guide---linux-debian-based-with-qgis-3

We can still add more things there, but for the basic one, I think it's already covered.

You may update the wiki if you feel there is something is missing.

Thanks

**Comment by lrntct** [comment]
I followed the steps in the wiki and it seems to be working. `make docker-test` runs as well.
Thank you all.

**Comment by ismailsunni** [comment]
Thanks @lrntct, I will close this then.

**Comment by Gustry** [comment]
>  make docker-test runs as well.

Hum, I was just checking quickly. How does it work with QGIS 3 @ismailsunni ? I saw in the makefile it's using 2.14
https://github.com/inasafe/inasafe/blob/develop/Makefile#L341

**Comment by lrntct** [comment]
I tried to run the `test_suite.py` from pycharm but get the following error.
Any idea?

```
Collecting coverage
  Downloading https://files.pythonhosted.org/packages/a4/5c/b3eac6aa7eb4af83c8580d9c1578343910bdcc59e64e3565402f9a527f9c/coverage-4.5.2-cp36-cp36m-manylinux1_x86_64.whl (205kB)
Installing collected packages: coverage
Successfully installed coverage-4.5.2
Traceback (most recent call last):
  File "/home/laurent/Sync/FloodFinJava/inasafe/source/test_suite.py", line 32, in <module>
    from safe.utilities.gis import qgis_version
  File "/home/laurent/Sync/FloodFinJava/inasafe/source/safe/__init__.py", line 29, in <module>
    from safe.common.custom_logging import setup_logger
  File "/home/laurent/Sync/FloodFinJava/inasafe/source/safe/common/custom_logging.py", line 35, in <module>
    from safe.common.utilities import log_file_path  # NOQA
  File "/home/laurent/Sync/FloodFinJava/inasafe/source/safe/common/utilities.py", line 26, in <module>
    from safe.utilities.rounding import (
  File "/home/laurent/Sync/FloodFinJava/inasafe/source/safe/utilities/rounding.py", line 8, in <module>
    from safe.definitions.units import unit_mapping, nominal_mapping
  File "/home/laurent/Sync/FloodFinJava/inasafe/source/safe/definitions/__init__.py", line 15, in <module>
    from safe.definitions.exposure import *
  File "/home/laurent/Sync/FloodFinJava/inasafe/source/safe/definitions/exposure.py", line 13, in <module>
    from safe.definitions.field_groups import population_field_groups
  File "/home/laurent/Sync/FloodFinJava/inasafe/source/safe/definitions/field_groups/__init__.py", line 5, in <module>
    from .field_groups import *
  File "/home/laurent/Sync/FloodFinJava/inasafe/source/safe/definitions/field_groups/field_groups.py", line 6, in <module>
    from safe.definitions.field_groups.age_field_group import (
  File "/home/laurent/Sync/FloodFinJava/inasafe/source/safe/definitions/field_groups/age_field_group.py", line 5, in <module>
    from safe.definitions.fields import (
  File "/home/laurent/Sync/FloodFinJava/inasafe/source/safe/definitions/fields.py", line 2959, in <module>
    from safe.definitions.minimum_needs import minimum_needs_fields  # noqa
  File "/home/laurent/Sync/FloodFinJava/inasafe/source/safe/definitions/minimum_needs.py", line 10, in <module>
    from safe.common.parameters.resource_parameter import ResourceParameter
  File "/home/laurent/Sync/FloodFinJava/inasafe/source/safe/common/parameters/resource_parameter.py", line 13, in <module>
    from parameters.float_parameter import FloatParameter  # NOQA
ModuleNotFoundError: No module named 'parameters.float_parameter'
```

**Comment by Gustry** [comment]
It was already mentionned earlier https://github.com/inasafe/inasafe/issues/5026#issuecomment-411487963

You need the submodule. You already did the `git clone` without submodules, so now I think you can do:

```
git submodule init
git submodule update
```
