### ISSUE TITLE
website formatting broken?

### ISSUE THREAD

**Issue by lrntct** [inasafe/inasafe#5031]
It seems that the formatting/stylesheet of the website is wrong:
![screenshot_2018-08-08 inasafe](https://user-images.githubusercontent.com/12278765/43853360-d81e6a64-9b37-11e8-8a4e-487a27ffd00a.png)

This can be replicated from a mobile phone from another network.
Am I the only one having this issue?

**Comment by ismailsunni** [comment]
Hi @lrntct 

Thanks for your ticket, I have fixed it. The server was full.

Fyi @timlinux I did the usual procedure to fix it.
