### ISSUE TITLE
polygons in 'low' flood level are classified as 'medium'

### ISSUE THREAD

**Issue by lrntct** [inasafe/inasafe#5056]
### Problem

When running an analysis of raster flood hazard vs polygon exposure, buildings in the 'low' hazard category are instead reported as part of the 'medium' category.

See in that screenshot that some buildings indeed fall into the 'low' category, but are not classified as such (number of structures in 'Low' is zero):

![screenshot from 2018-12-11 17-14-03](https://user-images.githubusercontent.com/12278765/49817502-4a504200-fd68-11e8-84f5-6481ff51cbea.png)

### Expected Behaviour

I would expect the buildings fully included in the relevant flooding category to be classified accordingly.

### Environment
* InaSAFE : 5.0.0 831d60abba
* QGIS : 3.4.2
* OS : Ubuntu 18.10

* Data used :
  * Exposure : OSM polygons
  * Hazard : Continuous raster water depth
  * Aggregation : None
  * Extent : Entire Area

**Comment by Gustry** [comment]
Please check the hazard aggregation summary to see the polygon where it's wrong.
If you don't give us some data, we won't be able to check. Or zoom in and check every cells of the raster under the building.
You said you are using a continuous raster with depth, so the raster style (Use caution, low etc) might not be linked with your keywords.

**Comment by lrntct** [comment]
It can be replicated with the DKI Jakarta dataset.

http://data.inasafe.org/InaSAFE%203.5%20Training%20Data/

Absolutely no area of the hazard aggregation summary is classified as 'low' (0.1-0.7m), even though those areas exist, see histogram. 

![screenshot from 2018-12-12 10-56-57](https://user-images.githubusercontent.com/12278765/49865392-bf6d5700-fdfc-11e8-8dd1-fdfa2fda819c.png)

![dki_flood_histo](https://user-images.githubusercontent.com/12278765/49865489-f93e5d80-fdfc-11e8-821f-d916682792f7.png)

**Comment by Charlotte-Morgan** [comment]
Hi @lrntct and @Gustry 
I can confirm / replicate this issue using the Jkt raster flood data and buildings. I also note some additional errors where buildings are assigned to the wrong flood hazard class.
![image](https://user-images.githubusercontent.com/5743135/50170295-7e3ae280-02e7-11e9-8415-0757410c1476.png)
The blue annotation shows a building in low water that has been assigned a hazard class of use_caution.
Confirming the observation from @lrntct that nothing is correctly classified as "low".
I note also (see red annotation) that some buildings are incorrectly classified as "medium" when I would expect them to be low - however this is inconsistent.  I am using 'discrete' symbology to display the flood raster.
![image](https://user-images.githubusercontent.com/5743135/50170821-b4c52d00-02e8-11e9-9a13-377dee4d7817.png)
I can not see anything wrong with the definition for the hazard classes, so assume its in the processing @Gustry ?? It's possible any bug has been inherited by inundation (dam burst function).

cc @samnawi @adisadit @thamrinf

**Comment by Charlotte-Morgan** [comment]
@Gustry - anticipating your next question :)
Screenie of hazard aggregation - no low
![image](https://user-images.githubusercontent.com/5743135/50171888-9876bf80-02eb-11e9-887f-b2305c10d02f.png)
Screenie of key words flood classification
![image](https://user-images.githubusercontent.com/5743135/50171951-cd831200-02eb-11e9-8784-bc327b93d765.png)

**Comment by Gustry** [comment]
@Charlotte-Morgan I will try to have a look.
Can you just confirm which QGIS and InaSAFE version?

**Comment by Charlotte-Morgan** [comment]
hi @Gustry - nice to see you too!
I just upgraded to QGIS 3.4.2 and its InaSAFE 5.0 dev
I grabbed the data from data.inasafe.org and applied the bare minimum of key words ....
I had a look at the definitions etc and everything looked ok in there so I think its deeper in the works for your expertise.

**Comment by lrntct** [comment]
Is anyone already looking at the bug?
If not, if someone could point me where to look at in the code base, I might have a go.

**Comment by Charlotte-Morgan** [comment]
@timlinux are you able to provide any pointers on this one?

**Comment by lrntct** [comment]
After some investigation I think I found the bug.
The layer passed to `reclassify()` is transformed to integer during `clip_bounding_box()`, messing up the classification.
Setting `parameters['DATA_TYPE']` to 0 ('Use input layer data type') seems to solve the issue.
I'll prepare a PR.

**Comment by lucernae** [comment]
Fixed from @lrntct commit in my PR here: #5076

**Comment by lucernae** [comment]
A pic for documentation:

The InaSAFE now detected buildings in 'low' class. (Number of features shown in the legend)

<img width="1920" alt="Screen Shot 2019-11-21 at 15 37 46" src="https://user-images.githubusercontent.com/831865/69321032-ebcc5d00-0c74-11ea-9d27-910463b0cbc9.png">
