### ISSUE TITLE
InaSAFE 5.0.1 does not work within QGIS 3.16.5

### ISSUE THREAD

**Issue by haytastan** [inasafe/inasafe#5088]
### Problem

```
The following problem(s) were encountered whilst running the analysis.

- StopIteration

**Diagnostics**

1. In file "C:/Users/hayati.tastan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\impact_function\impact_function.py", line 1470, in run self.style()

2. In file "C:/Users/hayati.tastan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\impact_function\impact_function.py", line 2494, in style self.debug_mode)

3. In file "C:/Users/hayati.tastan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inasafe\safe\impact_function\style.py", line 126, in generate_classified_legend analysis_row = next(analysis.getFeatures())

```

### Environment
* InaSAFE :  5.0.1
* QGIS : 3.16.5
* OS :  Windows 10

* Data used :
  * Exposure :  Population
  * Hazard : Jakarta_Flood_18113_WGS84
  * Aggregation : None
  * Extent : 
[DKI Jakarta.zip](https://github.com/inasafe/inasafe/files/6272152/DKI.Jakarta.zip)
  
Checklist: 

* [ ] Did you try to run it in debug mode ?
* [ ] Is the data available ?
  * If yes, where (BTSync, data.inasafe.org, zip) ?

**Comment by lucernae** [comment]
Hi @haytastan is it correct that the data is in this zip files https://github.com/inasafe/inasafe/files/6272152/DKI.Jakarta.zip?

I found the layer names to be different.

**Comment by haytastan** [comment]
Problem has been solved with sample data (above) suggested by **lucernae**. 
Thanks a lot, **lucernae.**
