### ISSUE TITLE
Batch runner needs to be documented

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#515]
# Requirement
- We need user documentation on how to use the batch runner
- We need developer documentation on how to programme batch scripts
# Expected outcome

Users and developers have a helpful reference guide when using the script runner.

**Comment by timlinux** [comment]
@jannes can you take a look at this please. I would like you to get to know the batch runner because we need to set up a nightly service to run a whole range of scenarios for integration testing.

**Comment by Jannes123** [comment]
Hi @timlinux I get the following error when trying to save a scenario for the batch runner.

File "/home/jannes/.qgis2/python/plugins/inasafe/safe/gui/tools/save_scenario.py", line 171, in save_scenario
    title, 'extent_crs', self.dock.extent.user_extent_crs.authid())
AttributeError: 'NoneType' object has no attribute 'authid'


Maybe I'm doing something wrong but I think the code for saving a scenario needs some work

**Comment by ivanbusthomi** [comment]
Now that we have the information on how to use batchrunner in InaSAFE help, I think we can close this issue.

![image](https://cloud.githubusercontent.com/assets/7351977/22284313/526339ae-e319-11e6-8874-360d177e325f.png)

**Comment by timlinux** [comment]
Thanks @ivanbusthomi - closing this.
