### ISSUE TITLE
Batch runner should only rerun a script multiple times if a single script is selected

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#517]
# Requirement

We need to prevent the situation where e.g. the user has set the batch runner to run multiple times and they then launch multiple scenarios. My suggestion would be to disable the multiple runs beviour unless a single scenario is being used.
# Expected outcome

User can run a single scenario (typicaly py script) multiple times but does not inadvertantly run 100 scenarios 100 times!

**Comment by ivanbusthomi** [comment]
Hi @timlinux , could you please explain a little bit related to this issue? I still don't get the idea yet, or maybe if this is not relevant anymore can we close this?

**Comment by timlinux** [comment]
I think we can close it. In earlier versions we had the ability to batch run a number of times to stress test InaSAFE. We have since removed this.
