### ISSUE TITLE
Batch runner needs save report option

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#519]
# Requirement

The user should be able to save a report of the batch run easily.

When the batch run is in progress the report should be written to the users scenario output folder after each scenario is completed. This is to prevent the situation where a major crash occurs and the user has no record of which scenario had failed.

The user should also have an 'open report' option in the runner gui that pops up the report in a text widget so they can cut & paste it to e.g. their email app or a github ticket.
# Expected outcome
- The reporting of a batch run is robust even in the event of full application failure.
- The user has the flexibility to get the report as text easily and paste it into another app.

**Comment by timlinux** [comment]
Please close if no longer relevant

**Comment by ivanbusthomi** [comment]
Closing this as per https://github.com/inasafe/inasafe/pull/3597, PDF report is always saved in either the same directory as scenario directory or other directories that user specified from the dialogue.
