### ISSUE TITLE
Building needs building_s and building_l attribute but not exactly explain what the key word for each attribute 

### ISSUE THREAD

**Issue by adissadis** [inasafe/inasafe#552]
## Issue

When I using shapefile that not exported from hot-export and running InaSAFE for Earthquake Analysis with scenario "be damage depending on building type" it come error message that need to building_s and building_l columns attribute. But its not explain more what the exactly keyword from the error message and InaSAFE Impact Function Browser. From InaSAFE Impact Function Browser is not explain more about the data information for specific hazard. 
1. And the others if from Verification Error Problem, It say "Input data to osm2padang must have attribute..." (why does it say osm2padang? not the data's name)
## Screenshot

![ticket](https://f.cloud.github.com/assets/2520159/365885/73e34866-a264-11e2-929a-316ef07c95a4.JPG)

![ticket 2](https://f.cloud.github.com/assets/2520159/365903/7a92c712-a265-11e2-887e-db17d62e237a.JPG)
## Suggested Solution

Make InaSAFE Impact Function Browser more detail about the  exposure data and the keyword for each attribute data

**Comment by timlinux** [comment]
Closing as old, no details, no active requirement.
