### ISSUE TITLE
Request for "Cancel" button after clicking Run 

### ISSUE THREAD

**Issue by emirhartato** [inasafe/inasafe#558]
Most participant in PMI training request cancel button after clicking run.
The reason why they want it is, they would like to cancel the process if somehow they forgot the set things in keyword editor so they don't need to wait the entire process.

**Comment by timlinux** [comment]
I'm going to assign to Martin - possibly,  he can create a standard background task service in QGIS.

**Comment by timlinux** [comment]
We still need threading support for this to work. Closing as old, no details or no active requirement plans. Post QGIS 3.0 we can revisit this idea as we can use the QGIS threading task manager.
