### ISSUE TITLE
We need to let the user know when 'all is well'

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#583]
# Problem

When no impact is expected we should communicate clearly to the user that 'all is well'.

In some cases, no buildings are flooded, no people are affected etc. InaSAFE does not really communicate this clearly to the user. It also does not do any form of checking as to why this may be the case.

# Proposed solution

Implement the following checks post analsis:

- [x] Check that one or more (in case of vector hazard) hazard intersects with the AOI
- [x] Check that at least one exposure instance intersects with the AOI
- [ ] Check that the threshold is appropriate (e.g. flood depth of 50cm may not 'catch' any buildings)
- [ ] Identify further check such as above that could be made and communicate to the user in cases where the success may be caused by data limitations
- [ ] Show a nice 'ALL CLEAR' message where we are fairly certain that no infrastructure or people will be affected

# Expected outcome

When we have no impact expected this should be clearly communicated to the user.

**Comment by timlinux** [comment]
@timlinux has covered some items with new extent selector

@cchristelis please make this a priority for 3.3

**Comment by ismailsunni** [comment]
Hi @timlinux 
I think we can close this since we have already ZeroImpactException to be raised when there is all is well case.

**Comment by timlinux** [comment]
Ok agreed thanks @ismailsunni
