### ISSUE TITLE
Idea for Batch Runner

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#588]
Below are some idea to be implemented in batch runner.
- [x] Show busy cursor when run the scenario
- [x] Better log file as result of run all (many) scenarios. I.e. give name for each scenario.
- [ ] If we clicked on a scenario that has been run, it will show the result in the dock
- [x] Clear previous result when click run all again
- [ ] Open the pdf for scenario by clicking on a button in the table
- [x] Run several times for a scenario
- [x] Better GUI size and resize
- [ ] Option to show the log files directly after ran all scenarion (?)
- [ ] Add checkbox for each scenario. Only checked checkbox will be run. Or add run selected scenario button.
- [ ] Make the table item not editable (?)
- [x] Add explanation why the scenario error in batch report
- [x] User feedback for parsed scenario result
- [ ] Will be added in the future ....

**Comment by timlinux** [comment]
Closing as old, no details or no active requirement plans.
