### ISSUE TITLE
Implement the Calgary Flood Closures as an impact function

### ISSUE THREAD

**Issue by ingenieroariel** [inasafe/inasafe#597]
Canada experienced floods in June, 2013. Here is an example from a Canadian website listing very complete resources about affected areas, shelters, information dissemination points and tools for self assessment. In the spirit of impact functions with checklist, it would be great to implement a similar function in Inasafe.

http://www.cbc.ca/news/canada/calgary/story/2013/06/21/calgary-flood-closures-list.html

Evacuation updates
Officials in Calgary announced Sunday that they will allow thousands of people affected by flood evacuations to do self-assessments of their homes.

They're being urged to follow safety guidelines when they enter their homes after the mandatory evacuation orders are lifted at 1 p.m. MT.

Map of the assessment zones
Interactive map of Calgary evacuation areas
A few "red zones" are still off limits in certain neighbourhoods:

Roxboro
Inglewood
Bowness
Bridgeland
Chinatown
East Village
Elbow Park
Rideau
Erlton
Mission
Stanley Park
Elboya
Sunnyside
Downtown.
Residents are asked to visit one of the re-entry information centres prior to heading home for important information that will support them in self-assessing their home and provide guidance on next steps:

Cliff Bungalow/Mission: 2201 Cliff St. S.W.
Montgomery: 5003 16th Ave. N.W.
Bowness: 7904 43rd Ave. N.W.
Sunnyside – 1320 Fifth Ave. N.W.
Roxboro/Rideau Park/Parkhill: 4013 Stanley Rd. S.W.
Elbow Park: 800 34th Ave. S.W.
Ramsay Community Centre: 1136 Eighth St. S.E.
Windsor Park: 5304 Sixth St. S.W.
Westmount – Louise Dean School: 120 23rd St. N.W.
Bridgeland: 917 Centre Ave. N.E.
Bonnybrook – Ogden Legion: 2625 78th Ave. S.E.
Calgary residents who live in apartments and condos should contact their building managers.

Only attempt re-entry if the following criteria is met:
The road and sidewalk is dry
There is no flood water on entry
Inspect the basement for water. If there’s water above electrical outlets, leave the home immediately.
The city says if the safety criteria is met, proceed with the self-assessment. Residents that find issues should take a sheet of 8x10 paper and write as boldly as possible:
GAS NEEDED, for natural gas issues
ELECTRICITY NEEDED
WATER PUMPING NEEDED
Nenshi on Saturday said the downtown core probably won't reopen until mid-week, and power in certain areas could be out for weeks — even months.

The Canadian Red Cross is asking Calgarians looking to connect with family members who have been displaced to call 1-866-696-6484.

For a comprehensive list of affected city services and evacuations, check the City of Calgary blog here.

Shelters
Evacuees with no place to go will be provided with food, shelter, bedding and other essential services at one of these reception centres:

Acadia Recreation Complex A, 240 90th Ave. S.E.
Village Square Leisure Centre, 2623 56th St. N.E.
Central Memorial High School, 5111 21 St. S.W.
Southland Leisure Centre, located at 2000 Southland Dr. S.W.
St. Francis High School, 877 Northmount Dr. N.W. (registration only, no onsite lodging)
Centre Street Church, 3900 2 St N.E. (registration only, no onsite lodging)
South Fish Creek Recreation Centre at 333 Shawville Blvd. S.E. is at capacity.
Canada Olympic Park/Winsport Lodging is now closed.
Check here to see which centres have lodging available
SAIT Polytechnic's residence buildings have also been opened to flooding evacuees.

Citizens placed in two-day accommodations have now been extended to three days.

People can take pets to the Animal Service Centre, at 2201 Portland St. S.E., or the Calgary Humane Society, at 4455 110th Ave S.E., if they can't find an alternative place for them.

Blue cart collection suspended
The city announced Sunday evening that it will be suspending blue cart collection service in all Calgary communities until further notice.

Residents are asked to store recyclable materials until collection resumes or take them to the community recycling depots.

Other residential collection services will continue on usual collection days for communities not impacted by flooding.

In flood areas, garbage trucks and dumpsters will only be available at re-entry information centres in each of the flooded communities.

Residents can bring their garbage and flood-damaged materials to these locations for collection.

Residents of flooded communities can also leave large items on their front lawns for collection. They are asked to mark items with a sign if they do not wish for those items to be collected.

Electronics, appliances and household hazardous waste such as propane tanks, chemicals and paints will not be accepted in the garbage but will be collected later from flooded communities.

Recreation centres reopen
The City of Calgary reopened four recreation centres around the city that were closed as a precautionary response to the recent flooding of the Bow and Elbow rivers.

Thornhill Aquatic and Recreation Centre – 6715 Centre St. N.W.
Killarney Aquatic and Recreation Centre – 1919 29th St. S.W.
Canyon Meadows Aquatic and Fitness Centre – 89th Canova Rd. S.W.
Bob Bahan Aquatic and Fitness Centre – 4812 14th Ave. S.E.
These four facilities will operate with the following schedules:
9 a.m. to 11:30 a.m. public swim
11:30 a.m. to 1:30 p.m. adult lengths
1:30 p.m. to 4:30 p.m. public swim
Schools, final exams
All public and Catholic schools in Calgary are closed Monday because of the flooding.

High schools in non-evacuated areas will remain open for students writing diploma exams this week; however, Grade 9 Provincial Achievement Tests are cancelled and students will receive a mark awarded by their teacher.

The Calgary Board of Education has cancelled Grade 12 diploma exams, but will make arrangements for those students who still want to write the exams.

Find out where to write your diploma exams
The University of Calgary's four campuses will also remain closed Monday and Tuesday. Most campus buildings remain locked, and all classes and events have been cancelled or will be postponed.

Classes held on the Bow Valley College campus and online are cancelled until further notice.

As well, classes are cancelled at Mount Royal University and all exams on June 24 and 25 have been postponed.

Power outages
24,000 Calgarians were still without power late Sunday morning.
Enmax said 10,000 of those customers without power are in and around the downtown core.
The military brought heavy equipment to Douglasdale on Sunday to shore up land around the electrical substation that provide power to south Calgary. The substation was declared "stabilized" around 8 a.m. MT.
CEMA director Bruce Burrell said power substation No. 5 remained offline on Sunday and it could take "three, four or five days to restore power to downtown Calgary," but if extensively damaged could take weeks — even months.
Just before noon on Friday, the decision was made to evacuate many buildings downtown because of power outages.
Enmax has a list of current outages affecting Calgary.

Weather
More rain is in the forecast for parts of southern Alberta with an additional 10 millimetres possible over the weekend, CBC meteorologist Danielle Savoni said.

The highest amounts are expected west of Calgary and just north of Canmore. Showers are also forecast for the weekend, she said.

Current weather conditions
Limit water use
City officials say water quality in Calgary has not been affected and there is no boil-water advisory in place at this time, but they are asking residents to limit water use. For example, avoid using dishwashers and washing machines and take quick showers and shallow baths.

"The very high river flows have resulted in high levels of silt and debris in the water coming into the city’s drinking water treatment plants," said the city in a release.

"This silt is starting to slow down the treatment process, creating a growing load on the filtration processes. As a result, it is taking longer to treat the incoming water which presents a challenge to meet water demand."

Get the latest from CBC News on the Alberta flooding
Water levels, traffic and road closures
Officials said on Saturday that the Elbow River is slowly coming down, while the Bow is also seeing improvements.

The city is providing updates on road and bridge closures on its blog.

Calgarians can call 311 for any flood-related updates.

Looting concerns
Police Chief Rick Hanson says earlier reports Friday of looting have been checked out, but found to be false. He says there are huge numbers of officers patrolling the evacuated areas right now.

Courts, trials
Alberta Justice says the Calgary Court Centre will be open Monday but that no trials will be held until Thursday.

People with scheduled trials can go to the Alberta Justice website for information on rescheduling.

The Court of Appeal is closed Monday and there is no timeline as of Sunday for when it will reopen.

Hospitals, surgeries
AHS says all emergency services departments in Calgary were open as of 10:30 p.m. MT Thursday, but the Sheldon M. Chumir Urgent Care Centre is closed and will remain closed until further notice.

AHS clinics, appointments and elective procedures at the Holy Cross building in Mission are closed. All appointments scheduled for Friday have been postponed. Cancer treatments at the Tom Baker Cancer Centre in northwest Calgary are not affected.

Roughly 30 surgical procedures in Calgary urban hospital sites were postponed on Friday. They were all elective procedures and Alberta Health Services said patients would be contacted directly.

Patients at the Agape Hospice and two continuing care sites in Calgary — Bowview Manor and BowCrest Centre — are being relocated.

For a list of which health-care centres are affected by flooding in other cities, including High River, Canmore and Sundre, click here: www.albertahealthservices.ca/8644.asp.

Transit
Calgary Transit is reporting several weather-related detours: calgarytransit.com

C-Train service in the downtown core has been suspended. Trains 201 and 202 outside of the core have limited service.

As of Sunday, Calgary Transit said there was no service on the following routes: 9, 17, 30, 31, 62, 63, 64, 66, 69, 70, 75, 89, 102, 103, 107, 109, 110, 116, 117, 125, 126, 133, 142, 145, 151, 181, 182, 300, 302, 305, 411, 412, 419, 439 and 502.

Routes on detour: 1, 2, 3, 4, 5, 6, 10, 13, 18, 24, 33, 40, 72, 73, 112, 301, 405, 407, 408, B201 (C-Train Shuttle), and B202 (C-Train Shuttle).

For the latest on transit service, follow @calgarytransit or check for service updates at www.calgarytransit.com.

Emergency alerts
For a list of emergency alerts in Calgary and Alberta, check here: emergencyalert.alberta.ca/.

Bridge integrity
The city says it has a high degree of confidence in the structural integrity of local bridges, but they are asking pedestrians to stay off.

"At this time our bridges remain stable as they’ve been built on bedrock," said the city in a release.

Once the waters recede all bridges will undergo a comprehensive engineering evaluation, according to the city.

Hotel closures
Many out of town visitors should know that most major downtown hotels are currently closed:

Calgary Marriott Downtown
Delta Bow Valley
Hyatt Regency Calgary
Le Germain
Sheraton Suites Calgary Eau Claire
The Fairmont Palliser
The Westin Calgary
Hotel Arts
International Hotel and Suites
Cancelled events
All remaining concerts and events of the Sled Island music and arts festival have been cancelled. It was slated to wrap up on Saturday with a concert at Olympic Plaza.

"Our commitment to the safety of the citizens of Calgary remains paramount. Please take care of your friends and family who may require assistance and stay safe," according to the Sled Island website.

The festival's office in Mission has been evacuated and organizers are asking for patience from ticket and pass holders.

Events cancelled:

Banff Marathon.
Sled Island music and arts festival.
First Street Market Walk.
Go Skateboarding Day.
Wing Kei Walkathon.
Allied Memorial Remembrance Ride.
Remington Race for Pace 2013.
Aboriginal Awareness Week.
Enbridge Ride To Conquer Cancer.
Relay For Life in Calgary and Medicine Hat.
MEC Paddlefest.
CBC's auditions for Recipe to Riches at Deerfoot Meadows Superstore.
United Way and UPS Plane Pull is postponed.
Bruce Burrell, director of the Calgary Emergency Management Agency, on Saturday said officials still hope the water will have receded to the point where there's time to go ahead with the Calgary Stampede as planned July 5.

**Comment by timlinux** [comment]
Closing as old, no details or no active requirement plans.

**Comment by uniqeorn** [comment]
The only one that can get
