### ISSUE TITLE
Create Script for get the text

### ISSUE THREAD

**Issue by ismailsunni** [inasafe/inasafe#627]
Please look at the following image
![selection_014](https://f.cloud.github.com/assets/1421861/883988/4c65b1e4-f9a2-11e2-8b32-c2c225106973.png)

The text that I circled sometimes is loaded late. If issue #626  is finished, it would be easy.
Just create a html file and put it in a specific directory. The webmaster of the website  will use that.

**Comment by timlinux** [comment]
Closing as old, no details or no active requirement plans.
