### ISSUE TITLE
Batch Runner to use Configure Impact Function Paramaters

### ISSUE THREAD

**Issue by vanpuk** [inasafe/inasafe#651]
# Problem

Tried to run the batch runner for volcano, on the default distance of 3,5,10 and then changed it to 5,10,25 saved each one (buildings and population) hence I had 4 scenarios saved, went to run and it failed completely.
# Solution

Batch runner should save the config file details.

![screen shot 2013-08-21 at 4 04 35 pm](https://f.cloud.github.com/assets/1421818/1000029/bdb6d7de-0a40-11e3-8475-812bf6354f6a.png)
![screen shot 2013-08-21 at 4 04 31 pm](https://f.cloud.github.com/assets/1421818/1000030/bdf70174-0a40-11e3-80c1-4982c6d7fcac.png)

**Comment by timlinux** [comment]
Closing as old, no details or no active requirement plans. Configuration should be done by keywords now. In case of the volcano example above, user should prepare the datasets with desired buffer zones first.
