### ISSUE TITLE
OSM Downloaded Does not work with internet proxy

### ISSUE THREAD

**Issue by wonderchook** [inasafe/inasafe#667]
# Problem

When using proxy with OSM downloaded data never downloads and 'socket error' occurs.

# Expected results

When using a internet proxy OSM data should still download for use in InaSAFE. Would expect InaSAFE to use QGIS proxy configuration.

**Comment by Gustry** [comment]
Instead of using [QNetworkAccessManager](https://github.com/inasafe/inasafe/blob/develop/safe/utilities/osm_downloader.py#L25), perhaps we should use [QgsNetworkAccessManager](http://qgis.org/api/classQgsNetworkAccessManager.html) ?

**Comment by Gustry** [comment]
InaSAFE is now using the QNetworlAccessManager provided by QGIS. Any bug should be raised in the QGIS bug tracker.
