### ISSUE TITLE
Nice to have a feedback form on InaSAFE website

### ISSUE THREAD

**Issue by vanpuk** [inasafe/inasafe#680]
# Problem

InaSAFE website does not yet have a place for users to provided feedback.
# Solution

Provide a 'feedback' button on the front page that ask you a series of questions

eg
![screen shot 2013-10-01 at 9 30 01 pm](https://f.cloud.github.com/assets/1421818/1245906/5dea9bca-2aa6-11e3-8a8e-3fe7962c510c.png)

**Comment by mach0** [comment]
survey prepared a long time ago - but was never integrated in the webpage .. 
is this still an issue or can this be closed?

**Comment by timlinux** [comment]
Closing as old, no details or no active requirement plans.
