### ISSUE TITLE
refactor deintsect to be a static method

### ISSUE THREAD

**Issue by mbernasocchi** [inasafe/inasafe#715]
impact functions that deal with vector hazards and vector exposures (for example the new categorical vector hazard function from essc) might need to use  deintersect before running.

deintersect should be a static method that takes 2 layers and dentersects them.

@timlinux what do you think?

**Comment by timlinux** [comment]
Maybe a candidate @wonder-sk to work on

**Comment by timlinux** [comment]
Closing as old, no details or no active requirement plans.
