### ISSUE TITLE
Display a progress bar while the calculation is running to give feedback to the user

### ISSUE THREAD

**Issue by vdeparday** [inasafe/inasafe#727]
Currently there is no feedback to the user when running an impact function so it feels like QGIS is not responding and it is going to crash although it ends up working. Would be great to have a progress bar and maybe even some texts underneath to the different as it is going through them ( see for instance overpass api turbo progress indicator)

**Comment by timlinux** [comment]
![imag3163](https://cloud.githubusercontent.com/assets/178003/9404922/bc7a1c1c-47f3-11e5-8510-335ccd82a4cb.jpg)


Just an update / note on this - for 3.3 I am proposing that we implement a generalised API like this which can be used both by IF mixins and by the progress callbacks. Also a note to say that in our new IF archticture in 3.2 we have added progress callbacks to the IF base class - in 3.3 we need to go through all the IF's and hook them up to use the new API.

**Comment by timlinux** [comment]
Lower priority if you have time for this milestone...

**Comment by timlinux** [comment]
We have this in 4.0

![qgis](https://cloud.githubusercontent.com/assets/178003/22010938/dbd4adf0-dcbe-11e6-983f-9198413ee7c2.gif)
