### ISSUE TITLE
Harmonize InaSAFE Report Template with BNPB's map template

### ISSUE THREAD

**Issue by fredychandra** [inasafe/inasafe#752]
# Problem/Establishment #
We need to harmonize InaSAFE template report with BNPB's map template standard refers to Head of BNPB law Head of BNPB Law No. 2/2012 on General Guidelines on Disaster Risk Analysis (http://bnpb.go.id/uploads/pubs/30.pdf). 

# BNPB's Map Template #
![bnpb template map](https://f.cloud.github.com/assets/6345285/1917001/6e93eb50-7d87-11e3-8954-c708ebd6812b.PNG)

# The Details
**Note :** I have no high resolution for this map. I will try looking for that.

Datum Information
![datum information](https://f.cloud.github.com/assets/6345285/1917003/75ef9232-7d87-11e3-9b7d-d53f2775b76d.PNG)

Legend
![legend colour index gradation](https://f.cloud.github.com/assets/6345285/1917004/78133b0e-7d87-11e3-94e6-47ba57dc1490.PNG)
![legend](https://f.cloud.github.com/assets/6345285/1917006/7a224b24-7d87-11e3-8f88-c0696c0e07e7.PNG)

Map file name
![map file name](https://f.cloud.github.com/assets/6345285/1917008/7dc355c0-7d87-11e3-94d1-42e5147d0203.PNG)

Map Location Index
![map location index](https://f.cloud.github.com/assets/6345285/1917010/80d9233e-7d87-11e3-9495-eb88babd7f70.PNG)

Map Scale & North Arrow
![map scale](https://f.cloud.github.com/assets/6345285/1917011/835e44cc-7d87-11e3-8e43-1b0081364524.PNG)

Map Tittle
We can adjust it "Impact map of ...."
![tittle](https://f.cloud.github.com/assets/6345285/1917012/859deaf8-7d87-11e3-802b-72d24d9805b7.PNG)

# Discussion
1. Even InaSAFE is not for Risk Assessment, but the map template will be good if similar with BNPB standards. This is because almost Disaster Management Agency (BPBD) in sub national level will use the same template of BNPB for their maps product
2. The BNPB's template is landscape view and for A1 size paper. Maybe we need some adjustment for A4 size paper to input all important information in one view.

@akbargumbira @alexbruy @vanpuk

**Comment by samnawi** [comment]
@Charlotte-Morgan Can we closed this ticket? I see this ticket is for milestone 3.3, but I think the solution of this ticket was represented by ticket #1314 that has been closed.

For the future, I think we can focus on infographic #1775 

Thank you.

**Comment by timlinux** [comment]
See also #2920 - I will close this issue for now but it can serve as reference for the general reporting standards work.
