### ISSUE TITLE
define a data model for building type postprocessor

### ISSUE THREAD

**Issue by mbernasocchi** [inasafe/inasafe#760]
as discussed on http://irclogs.geoapt.com/inasafe/%23inasafe.2014-01-23.log, the no data issue is not a code issue. it is a data problem. the osm_building_footprints.shp has no "type" attribute like the data downloaded from our downloader.
since 3a9ea72 the building_type_postprocessor doesnt use "amenity" anymore to calculate, this because the data from the downloader are preprocessed as mentioned in #722

![inconsistency3](https://f.cloud.github.com/assets/992519/1971171/08150b5c-8322-11e3-950e-a4a2618be52a.png)

**Comment by ismailsunni** [comment]
Been fixed in 3.5
