### ISSUE TITLE
Reorder detail in InaSAFE report template

### ISSUE THREAD

**Issue by Charlotte-Morgan** [inasafe/inasafe#761]
# Problem

The report\* content could be presented in a more logical order.
It starts with detailed gender age and minimum need and then goes into general information. It could be good to start with the title, general and then more detailed information.

*ie the report produced when the InaSAFE print button is pushed and then the pdf button.
# Example

![image](https://f.cloud.github.com/assets/5743135/2026712/9b211cb4-889b-11e3-9f69-5c2d5d418e96.png)
# Solution

Reorder the existing information as follows:
1. Title and summary information
   ![image](https://f.cloud.github.com/assets/5743135/2026732/1de68f26-889c-11e3-8896-0f5ea2cb0d76.png)
2. Detailed reports by post processors and aggregation as relevant
   ![image](https://f.cloud.github.com/assets/5743135/2026739/4db114ec-889c-11e3-9e92-54c65c3c090f.png)
3. Notes and metadata
   ![image](https://f.cloud.github.com/assets/5743135/2026745/79ca0584-889c-11e3-853a-e557df4d3939.png)
## Suggestions

a. Title could be bigger font to make it stand out
b. The action checklist could stay at the bottom of 1 above
# CC

@akbargumbira 

Please reassign to the relevant person :)

**Comment by ismailsunni** [comment]
I think this is no longer relevant (already fixed).
Can you check it @samnawi ?

If so, we can close this ticket.

**Comment by samnawi** [comment]
I think it's good for the order.
The order from general to detail information, followed by some action and note (has been updated).
It's good also to give the color box in the title.

But, just make it tidier like in the picture :
![selection_012](https://cloud.githubusercontent.com/assets/8871958/12109101/5e98b548-b3b1-11e5-90d9-8b4743f78a50.png)

@ismailsunni maybe we can also ask @Charlotte-Morgan about it, to make sure it's OK.

**Comment by Charlotte-Morgan** [comment]
i think this was fixed by @timlinux when he tweaked the reports and with @fredychandra when we reviewed the action lists

**Comment by samnawi** [comment]
@ismailsunni to respond your comment, as the comment from @Charlotte-Morgan in above, I think for reorder issue has been done.

Maybe just a paper cut issue to make tidier the color box for like the picture in above.

Thank you.

**Comment by timlinux** [comment]
This should be addressed in #2920 too.

**Comment by timlinux** [comment]
@Charlotte-Morgan can we close this please and pick up the work via #2920?

**Comment by Charlotte-Morgan** [comment]
@timlinux - we can close this. 
@ivanbusthomi  - FYI - polishing reports has been ongoing activity
