### ISSUE TITLE
Impact Functions need to have a consistent impact layer as for the output

### ISSUE THREAD

**Issue by akbargumbira** [inasafe/inasafe#768]
# Problem

Currently we have over a dozen impact functions, these functions should be consistent in their format and output.  It would be good to check the following:
- Doc string completely filled in and updated if necessary - doc strings should also state units if its a raster and attribute name if its a vector.
- All impact functions follow the same structure i.e. Import, Doc String, Title, Function documentation, configurable paramaters, etc
- All impact functions spatial result should be the same as the exposure (in the case of exposure as a raster it should be the same resolution and position)
- All results tables should be consistent and hold the same information (total number affected, action list, break downs, source etc).
- Ensure all impact functions are united tested appropriately
- Ensure all impact results are constantly reported and formatted (json) (#587, #23)
# Solution

We need to review all impact functions and make them consistent. It would be good to agree on how an impact function should look and make sure all old functions are updated and we have a manual for developers that walks them through the agreed upon structure.
# Related Issues:
- Building Impact function (Break down for buildings) (https://github.com/AIFDR/inasafe/issues/598)
- Impact result style (https://github.com/AIFDR/inasafe/issues/637)
- Moving all impact functions to use the QGIS layer (https://github.com/AIFDR/inasafe/issues/707 and RFC #609) 
- Impact function action lists should be refracted into their own class (https://github.com/AIFDR/inasafe/issues/692)
- Need to clarify the Imact Function listing to differentiate vectors as point OR polygons (https://github.com/AIFDR/inasafe/issues/335)
# edited by

@vanpuk 
# CC

@vanpuk @Charlotte-Morgan @timlinux

**Comment by akbargumbira** [comment]
Just to update this. Some bits that have not addressed at current InaSAFE:
- All results tables should be consistent and hold the same information (total number affected, action list, break downs, source etc). This could be solved by @cchristelis Population Exposure MIxin
- Ensure all impact results are constantly reported and formatted (json) (#587, #23)

**Comment by timlinux** [comment]
Closing as old, no details or no active requirement plans. Impact functions are dead in InaSAFE 4...
