### ISSUE TITLE
Combining 2 impact functions derived from 2 different hazards with the same exposure data

### ISSUE THREAD

**Issue by vanpuk** [inasafe/inasafe#769]
# Problem

Currently InaSAFE only allows for impact results for 1 hazard, however in reality one hazard may trigger another hazard i.e. if an earthquake occurs generating a tsunami.  It would be beneficial for a disaster manager to understand the combined impact of these 2 hazards.
# Expect Results

Run 2 hazards on the same area and exposure and be able to combine these 2 impact results. If the exposure is:
Population count (raster): combine rasters ensure full coverage
Buildings (point): Result should have 3 columns added to the exposure layer: affected1, affected2, combined_affected.

**Comment by timlinux** [comment]
We can do this in the future using a prep tool that combines the two hazards but there are lots of notches here so we need clear use cases and descriptions before we can implement. I am going to close for now and we can re-approach this when we know what problem we are trying to solve.
