### ISSUE TITLE
Impact layer should always be added above the input layers

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#771]
# Problem

The impact layer often appears below one of the impact layers which is confusing.
# Proposed solution

Implement a simple algorithm to calculate the legend layer position above either of the input layers.
# Expected outcome

The impact should always be visible in the context of the two inputs used to define the analysis.

**Comment by Gustry** [comment]
Recently, the layer is added above the exposure/hazard. Ticket #2899, PR #2905 

Can we close @timlinux ?

**Comment by timlinux** [comment]
Yes - closing thanks.
