### ISSUE TITLE
Scenario comparison for different hazard layers

### ISSUE THREAD

**Issue by tdhu** [inasafe/inasafe#81]
Need to be able to compare the outputs of two different scenarios. For example, in our Jakarta flood modelling work we have two different hazard layers (one that includes a structural mitigation option and one that doesn't).  We would like to be able to automatically see the difference that the difference in the hazard layer makes to the resultant impacts.

I could imagine that this tool would work on all the exposure datasets in a project and allow the user to have "difference" outputs available for all of the exposure layers.  This will then need some careful thought about how to link this with automatic reporting and publication preperation (eg. Issue #24).

This concept could also extend to working with different exposure layers (for example, how many lives would be saved if we moved this school, or we built this bridge in a different location). However, I think that is likely to be an additioanl functionality that we are some way off needing - suggest it become an additional ticket if and when it is asked for.

**Comment by timlinux** [comment]
I'm closing this as old. We did have the impact merge tool but it was removed in 3.5. In the future we can look at re-instating it using 4.0 architecture.
