### ISSUE TITLE
We need a prototype Impact Function implementation of flood on landuse

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#883]
# Problem

Although we don't have a details use-case analysis available yet, we would like to get a basic implementation of flood on landuse (polygon on polygon) in place so that we can develop this capability.

# Proposed solution

- [ ] Implement a new impact function using the native QGIS approach
- [ ] Produce an impact summary that shows an enumeration by landuse type and the total flooded and not flooded land in each class (expressed as areas in m2 and as percentages)
- [ ] There is no action list available at this stage so it is not currently a requirement
- [ ] Be sure to use a UTM zone (based on the centroid of each part) when computing areas

![selection_001](https://f.cloud.github.com/assets/178003/2421706/b467bbbc-ab85-11e3-9b70-59abf49528d4.png)

# Expected outcome

After implementing this, users should be able to compute the impact of a flood polygon layer on landuse. For raster floods we can later user @KolesovDmitry 's polygoniser logic to convert rasters to polygons, but for now it is not a requirement.

**Comment by Charlotte-Morgan** [comment]
#1216

**Comment by fredychandra** [comment]
I am on progress develop prototype data for landcover (rice) polygon with attribute for using in prototype impact function implementation of flood on landuse. The polygon will consist of type of landcover, harvest area (Ha), Production (Ton) and productivity (Ku/Ha). 

In my though this prototype data can be use for basic landcover analysis to measure : 
1. How many crops area (ha) that inundated by flood
2. How many % harvest area that inundated by flood that will influence how many production (ton) will potentially loss

I use Jawa Timur for develop this prototype data. The attribute data source come from Agriculture Ministry and the landcover data (spatial) from MInistry of Forestry/BIG.

**Comment by timlinux** [comment]
There is a landuse impact function added to experimental branch - please try it out and provide feedback.

**Comment by timlinux** [comment]
There is a landuse impact function added to experimental branch - please try it out and provide feedback.

**Comment by timlinux** [comment]
Closing this as we already have landuse in 3.4
