### ISSUE TITLE
OSX: QGIS Crashes When Using Roads Exposure Layer

### ISSUE THREAD

**Issue by Erve1879** [inasafe/inasafe#909]
# Problem

Using OSM roads data (downloaded with InaSAFE tool) against tsunami data, QGIS crashes after choosing a CRS for the new layer. 

Quick screencast:
https://dl.dropboxusercontent.com/u/604941/QGIS%20Crash.mp4

OSX Crash report:
https://dl.dropboxusercontent.com/u/604941/QGIS%20crash%20report.txt

**Comment by timlinux** [comment]
Close as old, no longer replicable in InaSAFE 4.0
