### ISSUE TITLE
Missing admin boundary on output layer after running 'Minimum Needs Tool'

### ISSUE THREAD

**Issue by emirhartato** [inasafe/inasafe#912]
# Problem

After we are running Minimum Needs Tool using Jakarta district boundary (there are 5 districts), an admin boundary from the layer output is missing (East Jakarta is missing), but when we open the attribute table, the minimum needs is calculated well (there are 5 rows, so East Jakarta is calculated as well)

![kebutuhan minimum masalah](https://cloud.githubusercontent.com/assets/1563226/2606251/e25270e4-bb4d-11e3-9867-a5169ef1bfc2.jpg)

![screen shot 2014-04-03 at 11 42 27 pm](https://cloud.githubusercontent.com/assets/1563226/2606349/f6d5bc00-bb4e-11e3-8614-6ab1980cda35.png)
# System

Windows 7 64 Bit
QGIS 2.2 Valmiera (32-bit)
InaSAFE 2.0.5 Final

Windows 7 32 Bit
QGIS 2.2 Valmiera (32-bit)
InaSAFE 2.0.5 Final

OS X 10.9 64 Bit
QGIS 2.2 Valmiera
InaSAFE 2.0.5 Final
# Expected Outcome

The layer output should not have missing boundary.
# Data

Here is the admin boundary data
https://www.dropbox.com/s/wza13kwumr0e6r2/district_jakarta.zip
# CC

@akbargumbira  @timlinux

**Comment by timlinux** [comment]
Please check @myarjunar  - take note of comments above about broken geom.
