### ISSUE TITLE
New QGIS style IF assume data is in ESPG:4326

### ISSUE THREAD

**Issue by assefay** [inasafe/inasafe#934]
It is assumed in the IF that hazard and exposure data is in espg:4326.
The self.extent is set from a higher api that make sure that epsg:4326 is used for the extent.
The IF use that value with converting it to the data's projection (for hazard and exposure)

We should be able to have other types of projections for the data.

**Comment by timlinux** [comment]
In InaSAFE 4.0 we no longer constrain the CRS type.
