### ISSUE TITLE
RFC Unify hazards to be represented as polygon data

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe#949]
# Status

This RFC is in **draft**
# Problem
- We have a large technological debt in maintaining many different moving parts in the core safe package. See also #1195 
- There is a large amount of code dedicated to performing basic GIS operations such as overlay analysis etc. #1195
- The local implementations have limitations in terms of the ability to deal with multi-part features, different coordinate reference systems, inner rings, island polygons etc.
- Explaining the workflow in InaSAFE is often difficult and the inner workings of the system lean towards complexity rather than simplicity.
- A lot of 'rote' code is devoted to dealing with different types of hazard data formats (raster, vector lines, vector polygons, vector points).
# Proposal

In this RFC we propose that we should migrate to a design where the general processing workflow is as follows:

![unifiedimpactfunction - new page](https://cloud.githubusercontent.com/assets/178003/5329842/92c1da56-7df8-11e4-9928-55e7ababae56.png)

The idea is to generalise as much of the analysis process as possible such that all analyses follow the same core steps in the workflow:
- convert hazard layer to a polygon layer
- select algorithm implementation: point on polygon, line on polygon, polygon on polygon or raster on polygon (typically zonal stats based).
- add impact function specific logic using the generically derived base data above
- apply generic post processing logic to the impact layer

A side effect of this migration would be pervasive use of 'new style' impact functions. In particular we would migrate all impact functions to use the QGIS API and in the process deprecate the 'legacy' impact functions.

Thus the goal will thus be to make impact function implementations all work in as homogenous a manner as possible, minimise our internally implemented geospatial algorithms as much as possible and maximise the benefit we obtain from being implemented on top of the QGIS platform.

**Note:** One key test we should make before proceeding with this architectural approach is to verify that we will be able to effectively use InaSAFE in web context as per the geonode integration work being carried out by @ingenieroariel and colleagues.
# Comments and concerns
- We should look at ITB Earthquake function and similar functions that need literal pixel values and not classified values to ensure the methodology above will work. One approach could be to allow the IF to define / overload the categorisation logic of the ABC so that it can apply e.g. its own damage curve logic before classification is made. On further investigation by @akbargumbira it seems like we will have edge cases where it will not make sense to polygonise the hazard since we need to use discrete cell values in tandem with discrete exposure cell values. In such cases the IF implementer would choose to overload the prepare method in the IF base class and use e.g. numpy.
- For buildings any part of a building that intersects with the hazard polygon we should consider the building to be affected.
- For exposure which is raster population, the IF should iterate the cells of the hazard polygon and generate an output raster matching cell size and extents of the exposure, where any cell inside the hazard (1 or high) class is assigned the original population value, and any value outside would be assigned the value of null.
-  We should consider adding the option to apply a high (low?) pass filter to eliminate single pixels that are marked as flooded
# Expected outcomes
- Reduced technical debt
- Easier and more rapid implementation of new impact functions
- Simpler and easier to understand architecture
- Remove the need for resampling and the various bits of black magic that happen during clipping (see #695)
# CC

@AIFDR/inasafe-developers 
@vanpuk 
@Charlotte-Morgan 
# See also
#1195 (RFC for fully embracing the QGIS library)
#689 (RFC to implement a robust resampling scheme)

**Comment by timlinux** [comment]
@Gustry you may want to read through this as a lot of it is still relevant for our '7 base classes' discussion.

**Comment by timlinux** [comment]
I'm very pleased to say that the architecture in InaSAFE v4.0 is aligned to and implements this RFC.

**Comment by ismailsunni** [comment]
Cool
